microsoft/DirectXShaderCompiler

lib/HLSL/DxilModule.cpp, utils/hct/hcttest-samples.py
- link dump methods when compiled with _DEBUG or DBG
- d3d12warp to d3d10warp in hcttest-samples.py
=> Integrate internal changes

tools/clang/tools/dxc/dxc.cpp
Hello,
this is a very simple change, but using BYTE as alias type for generated code makes header file not compiling by default, switching to standard unsigned char instead fixes that issues.
Many Thanks
Julien
=> Modify dxc header generator to use unsigned char instead of BYTE

utils/hct/hctbuild.cmd, utils/hct/hctstart.cmd
- avoids running out of memory during incremental linking
=> Use amd64 VS build tools instead of default x86 tools

utils/hct/hctbuild.cmd, utils/hct/hctstart.cmd
python 2.7 is now looked for the same way other dependencies are.
Improves logging as well by providing minimal console output during build, while providing a file logger with additional details.
=> Close #54 - hctstart should include python if missing

include/dxc/HLSL/DxilConstants.h, include/dxc/HLSL/DxilShaderModel.h, include/dxc/HLSL/DxilSignature.h, include/dxc/HLSL/DxilSignatureAllocator.h, include/dxc/HLSL/HLModule.h, include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilSignature.cpp, lib/HLSL/DxilSignatureAllocator.cpp, tools/clang/include/clang/Frontend/CodeGenOptions.h, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/BasicHLSL11_PS.hlsl, tools/clang/test/CodeGenHLSL/BasicHLSL11_PS3.hlsl, tools/clang/test/CodeGenHLSL/BasicHLSL11_VS.hlsl, tools/clang/test/CodeGenHLSL/SimpleHs5.hlsl, tools/clang/test/CodeGenHLSL/multiStreamGS.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/DxilContainerTest.cpp, tools/clang/unittests/HLSL/ValidationTest.cpp
Closes #75 
Add options:
- "-pack_prefix_stable" - (default) packs signature elements maintaining prefix-stable property that appended elements do not affect the packing of prior elements.
- "-pack_optimized" - pack with whole signature optimization, requiring all signature elements to be defined in the same way for placement of any individual elements to be identical.
=> Close #75 - Pack prefix-stable by default

tools/clang/lib/Lex/LiteralSupport.cpp, tools/clang/test/CodeGenHLSL/literals_Mod.hlsl
Treat h/H suffixes as f/F as "half" scalar type is converted to "float" type.
This should be changed in the future when we support true half types.
=> Treat half suffixes as floats

tools/clang/lib/Parse/ParseDecl.cpp, tools/clang/lib/Parse/ParseHLSL.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/uppercase-register1.hlsl, tools/clang/test/HLSL/packreg.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp, utils/hct/VerifierHelper.py, utils/hct/hcttestcmds.cmd
- enable upper case for valid registers ('B', 'C', 'I', 'S', 'T', 'U')
- fix VerifyHelper.py to output ast when expected errors are present
- fix buffer view register validation check
=> Enable Upper Case for Registers

utils/hct/hctbuild.cmd, utils/hct/hctstart.cmd
python 2.7 is now looked for the same way other dependencies are.
Improves logging as well by providing minimal console output during
build, while providing a file logger with additional details.
=> Close #54 - hctstart should include python if missing (#84)

include/dxc/HLSL/HLSLExtensionsCodegenHelper.h, include/dxc/Support/ErrorCodes.h, include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/Lex/HLSLMacroExpander.h, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Frontend/FrontendActions.cpp, tools/clang/lib/Lex/CMakeLists.txt, tools/clang/lib/Lex/HLSLMacroExpander.cpp, tools/clang/test/CodeGenHLSL/rootSigDefine1.hlsl, tools/clang/test/CodeGenHLSL/rootSigDefine10.hlsl, tools/clang/test/CodeGenHLSL/rootSigDefine11.hlsl, tools/clang/test/CodeGenHLSL/rootSigDefine2.hlsl, tools/clang/test/CodeGenHLSL/rootSigDefine3.hlsl, tools/clang/test/CodeGenHLSL/rootSigDefine4.hlsl, tools/clang/test/CodeGenHLSL/rootSigDefine5.hlsl, tools/clang/test/CodeGenHLSL/rootSigDefine6.hlsl, tools/clang/test/CodeGenHLSL/rootSigDefine7.hlsl, tools/clang/test/CodeGenHLSL/rootSigDefine8.hlsl, tools/clang/test/CodeGenHLSL/rootSigDefine9.hlsl, tools/clang/test/CodeGenHLSL/rootSigProfile5.hlsl, tools/clang/test/HLSL/rewriter/correct_rewrites/semantic-defines_gold.hlsl, tools/clang/test/HLSL/rewriter/semantic-defines.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/tools/libclang/dxcrewriteunused.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/ExtensionTest.cpp, tools/clang/unittests/HLSL/RewriterTest.cpp
This commit adds a standalone class for expanding macros and uses it
to for root signature and semantic define processing. Previously,
we were using the raw macro value instead of the expanded value
so something like:
#define MYRS "DescriptorTable(SRV(t0))"
#define RS   MYRS
would fail to compile the root signature with an entry point of
RS because it would get a root signature value of MYRS instead
of the expanded value. Similarly, for semantic defines we were
saving the non-expanded value into the bitcode.
This commit also adds a new flag that is used to specify that
the root signature should be read from a #define. So compiling
with `-rootsig-define RS` will read the root signature from
a `#define RS ...` in the source. The -roosig-define flag
takes precedence over a root signature …
=> Expand macros in root signature and semantic defines

include/dxc/HLSL/HLOperationLowerExtension.h, lib/HLSL/HLOperationLowerExtension.cpp, tools/clang/unittests/HLSL/ExtensionTest.cpp
Previously, If an extension uses the replication lowering strategy
and a non-vector overload was chosen we would return the function
un-modified. This change makes sure that we still use the
custom lowering name for the extension if one was specified.
=> Translate extension name when no replication is needed

README.md, appveyor.yml, cmake/modules/FindDiaSDK.cmake, utils/appveyor/appveyor_setup.ps1, utils/appveyor/appveyor_test.ps1, utils/hct/hctbuild.cmd
This commit makes the necessary changes to run the project with AppVeyor
CI. The `appveyor.yml` file contains the configuration settings for the
build. Currently we only build x64-Debug, but we can build the full
x32/x64-Debug/Release matrix by adding a few lines to the config.
The remaining changes are somewhat tied to the specifics of how appveyor
provisions the build machines. The standard VS2015 machines build on
Windows Server 2012. We can build on these machines, but cannot run tests
because we require d3d12.dll which is not available on Windows Server
2012. However, it is present on Windows Server 2016, but appveyor only
provides VS2017 on those machines. So part of the changes are to allow
the compiler to build with VS2017 so we can run tests as part of CI.
The …
=> Add support for AppVeyor continuous integration

lib/HLSL/DxilCompType.cpp, tools/clang/include/clang/AST/HlslTypes.h, tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/include/clang/Sema/DeclSpec.h, tools/clang/include/clang/Sema/SemaHLSL.h, tools/clang/lib/AST/HlslTypes.cpp, tools/clang/lib/Parse/ParseDecl.cpp, tools/clang/lib/Sema/DeclSpec.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/lib/Sema/SemaType.cpp, tools/clang/test/CodeGenHLSL/unsignedShortHandMatrixVector.hlsl, tools/clang/test/HLSL/matrix-syntax.hlsl, tools/clang/test/HLSL/vector-syntax.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
1. enable unsigned keyword for int vectors/matrices
(for example, "unsigned int2" will be converted to  "vector<unsigned int, 2>")
2. disable unsigned keyword as a complete type specifier to be consistent with old compiler.
=> Support Unsigned for shorthand vectors/matrices

tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/include/clang/Sema/Sema.h, tools/clang/lib/Sema/SemaChecking.cpp, tools/clang/lib/Sema/SemaExpr.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/lib/Sema/SemaOverload.cpp, tools/clang/test/HLSL/matrix-syntax.hlsl, tools/clang/test/HLSL/vector-syntax.hlsl
Currently front-end check for HLSL matrix/vector subscript operators([]) are not implemented. 
This checkin should handle syntax errors that deal with this issue.  
- Throw errors for subscript operators with index out of bounds
- Throw errors for cases where matrix/vectors are modified using subscript operators
=> Check Syntax errors for matrix/vector subscript operators

lib/HLSL/DxilContainerReflection.cpp, tools/clang/unittests/HLSL/DxilContainerTest.cpp
These changes are to fix issue #134.
The existing code in `DxilContainerReflection.cpp` had two cases where it initialized a `CShaderReflectionType*` variable to null, and then never filled it in (one even had a `TODO` comment). The corresponding code to actually construct a suitable reflection type was also missing.
This change adds a kind of best-effort implementation of that interface. There are cases where the extraction of information from the DXIL is a bit ad hoc, but I expect it to be good enough for many users.
There were existing test cases to verify that the reflection data extracted from DXIL matches that produced by FXC/DXBC, but those tests weren't looking at type information. In order to test the new code, I modified the existing tests to also compare reflection type …
=> Generate fxc-compatible reflection type info for buffer members

include/dxc/HLSL/DxilGenerationPass.h, include/dxc/HLSL/DxilMetadataHelper.h, include/dxc/HLSL/HLModule.h, include/dxc/HLSL/HLOperationLower.h, include/dxc/HLSL/HLOperationLowerExtension.h, include/dxc/HLSL/HLOperations.h, lib/HLSL/DxcOptimizer.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilMetadataHelper.cpp, lib/HLSL/HLModule.cpp, lib/HLSL/HLOperationLower.cpp, lib/HLSL/HLOperationLowerExtension.cpp, lib/HLSL/HLOperations.cpp, lib/Transforms/IPO/PassManagerBuilder.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/bindings1.hlsl, utils/hct/hctdb.py
1. A HL createHandle will have 1 or 2 parameters.
For  uav/srv/sampler, 1 parameter. 1 is the resource load from resource ptr.
For cbuffer, 2 parameter. 1 is the same. 2 is for dynamic indexing on array of cbuffers.
uav/srv/sampler don't have 2 is because all the use of them is on builtin methods. Resource on methods is scalar.
createHandle function will have metadata to save the resource information like class/kind/type/...
2. Added 2 more passes DxilLegalizeResourceUsePass DxilLegalizeStaticResourceUsePass to remove load/store on local/static resource.
Also make sure HL createHandle don't have phi operand.
3. For DxilGenerationPass,  Dxil createHandle will be generated after GenerateDxilOperations.
And HLObjectOperationLowerHelper now get RK/RC from MetadataAsValue argument of HL …
=> Lower resource to createHandle at clang code gen.

lib/HLSL/HLOperationLower.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/firstbitHi.hlsl, tools/clang/test/CodeGenHLSL/firstbitLo.hlsl, tools/clang/test/CodeGenHLSL/firstbitshi_const.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
This patch changes codegen for firstbithigh and firstbitlow.
For firstbitlow we do not generate a select on the return value from the
intrinsic. The previous codegen would check if the value is 0 and return -1 if
it was. However, the FirstbitLo intrinsic will return -1 when the input is 0 so
the select is not needed. So regardless of the input value we can take the
result of the intrinsic. This would match the code produced by fxc.
For firstbithi we check the value returned from the intrinsic for -1. If
the value returned is -1 we return -1. We do this for both signed and
unsigned intrinsics. The old codegen would check the input value for
0 and so would produce wrong code when the input value was -1.
We also disable constant folding in the front end for these intrinsics.
There was a bug …
=> Fix #169 - Bad codegen for firstbithigh/firstbitlow

.gitignore, CMakeSettings.json, README.md
Use the new CMake build support in VS15 to build
without having to run cmake separately. Removes the
need to download cmake separately.
By default binaries are built in:
%LOCALAPPDATA%\CMakeBuild\DirectXShaderCompiler\build\{build-flavor}
Build settings can be changed by modifying CMakeSettings.json.
=> Add support for building with VS 2017

tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/ShaderOpTest.cpp
- Fix #180 Use device passed to RunShaderOpTest()
- Fix reversed inf/-inf and comment typos
- Print adapter being used when hardware adapter selected
=> Fix #180 Select correct device when running ShaderOp tests.

include/dxc/HLSL/DxilOperations.h, include/dxc/HLSL/DxilShaderModel.h, include/llvm/IR/Module.h, lib/Analysis/DxilConstantFolding.cpp, lib/HLSL/DxcOptimizer.cpp, lib/HLSL/DxilModule.cpp, lib/HLSL/DxilOperations.cpp, lib/HLSL/DxilShaderModel.cpp, tools/clang/test/HLSL/constprop/bfi.ll
The original goal of this change was to use opcode class for deciding when we
can perform constant folding on a function.
We maintain a mapping from Function* to OpCodeClass inside the OP class.
We wanted to use this map in constant folding to decide if we can constant
fold a function to avoid string comparison on the function names.
However, it turns out that the DxilModule is not always available during
constant folding of dxil calls so we cannot use the map inside of OP. The
change contains a few bug fixes and improvements that came out of trying
to get opcode class working inside constant folding.
1. Use opcode class in dxil constant folding where possible.
2. Make sure the opcode cache is refreshed properly.
3. Remove 64-bit test for bfi.
4. Add equality comparison for the …
=> Ensure the cached Function->OpCodeClass map is updated

include/dxc/HLSL/DxilGenerationPass.h, lib/Analysis/DxilConstantFolding.cpp, lib/HLSL/DxcOptimizer.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/Transforms/IPO/PassManagerBuilder.cpp, tools/clang/test/HLSL/constprop/bfi.ll, tools/clang/test/HLSL/constprop/ibfe.ll, tools/clang/test/HLSL/constprop/ubfe.ll, utils/hct/hctdb.py
This change modifies dxil constant folding to use the opcode class when
deciding if a dxil function can be constant folded. We now require a
DxilModule to be available when constant folding dxil functions.
To ensure that the dxil module is available we add a new pass that loads a
dxil module from metadata if it does not exist. We use the new pass in the
dxopt tests for constant folding.
=> Use opcode class to guide constant folding possibilities

include/dxc/Support/Global.h, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp, utils/hct/hcttest.cmd
Normalizes API-provided names to include at least a current-relative
directory, simplifying file lookups. There are still restrictions on
how expressive include handlers enable the virtual file system to be,
these should be documented on the project wiki.
Handle some errors in BeginSourceFile paths where include handlers may
cause early errors, before compilation execution can begin.
Removes the prior scheme for directory handles, where the same handle
would be returned for any parent directory.
Future improvements would be to expand dxc paths before calling into
dxcompiler, and/or to fully implement OS API calls from console apps.
=> Move unused global tracing flags into single usage, closes #157.

tools/clang/lib/AST/HlslTypes.cpp, tools/clang/lib/CodeGen/CGHLSLRuntime.cpp
These functions are defined in [`HlslTypes.h`](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/include/clang/AST/HlslTypes.h#L351-L356) in clang AST so they
should have implementations in libclangAST.a.
=> Move some functions from clang CodeGen to clang AST

lib/HLSL/DxilCondenseResources.cpp
=> Use typename to mark subtypes in templated class

utils/hct/hctbuild.cmd
Quick fix; we tend to be more constrained by memory than cycles in many build configurations, so ease back a bit.
=> Update default maxcpucount in hctbuild

include/llvm/InitializePasses.h, include/llvm/Transforms/Scalar.h, lib/HLSL/DxcOptimizer.cpp, lib/Transforms/Scalar/CMakeLists.txt, lib/Transforms/Scalar/HoistConstantArray.cpp, tools/clang/test/HLSL/hca/01.hlsl, tools/clang/test/HLSL/hca/02.hlsl, tools/clang/test/HLSL/hca/03.hlsl, tools/clang/test/HLSL/hca/04.hlsl, tools/clang/test/HLSL/hca/05.hlsl, tools/clang/test/HLSL/hca/06.hlsl, tools/clang/test/HLSL/hca/07.hlsl, tools/clang/test/HLSL/hca/08.hlsl, tools/clang/test/HLSL/hca/09.hlsl, tools/clang/test/HLSL/hca/10.hlsl, tools/clang/test/HLSL/hca/11.hlsl, tools/clang/test/HLSL/hca/12.hlsl, tools/clang/test/HLSL/hca/13.hlsl, tools/clang/test/HLSL/hca/14.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp, utils/hct/hctdb.py
This commit adds a new pass to hoist arrays from local to global scope
when the array only contains constant values. A local array will use
alloca and stores for initialization, but a global array uses a global
variable with a constant initializer.
The idea is that a global array with constant initializer will allow the
backend compilers to produce better code because it is much easier to see
that the array is fully constant.
=> Add pass to hoist constant arrays

utils/hct/hctgettaef.py
Create all missing directories to target directory as needed.
If urllib.urlretrieve fails, try to download via powershell.
=> Improvements to hctgettaef.

docs/DXIL.rst, include/dxc/HLSL/DxilConstants.h, include/dxc/HLSL/DxilInstructions.h, tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/CMakeLists.txt, tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/HlslTestUtils.h, tools/clang/unittests/HLSL/ShaderOpArithTable.xml, tools/clang/unittests/HLSL/ShaderOpTest.cpp, tools/clang/unittests/HLSL/ShaderOpTest.h, tools/clang/unittests/HLSL/clang-hlsl-tests.rc, utils/hct/hctdb.py, utils/hct/hctdb_inst_docs.txt, utils/hct/hctdb_instrhelp.py
This change is to add execution tests for individual DXIL arithmetic operations. 
1. Using TAEF's data-driven model to group operations by the type/number of operands for each instructions.
2. Updating DXIL.rst for these instructions.
3. Update hctdb.py to enable internal links for DXIL instructions.
=> Adding Execution Tests for ShaderOp Arithmetic operations

include/dxc/HLSL/DxilRootSignature.h, lib/HLSL/DxilContainerReflection.cpp, lib/HLSL/DxilRootSignature.cpp, tools/clang/lib/Sema/SemaHLSL.cpp
Esp. since `__in` is used as method parameters in STL frequently.
=> Upgrade SAL annotations in some source files

lib/HLSL/HLModule.cpp, lib/HLSL/HLOperationLower.cpp, tools/clang/include/clang/AST/HlslTypes.h, tools/clang/include/clang/Frontend/ASTUnit.h, tools/clang/lib/Frontend/ASTUnit.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/lib/Sema/SemaInit.cpp, tools/clang/lib/Sema/SemaType.cpp
This solves compiler warnings given `-Wreorder`.
cc @dneto@ @ehsannas
=> Fix initialization order of various class members

cmake/modules/FindD3D12.cmake, cmake/modules/FindTAEF.cmake, utils/hct/hctbuild.cmd
This PR supports using Ninja as the generator.
It also hopefully enables other generators, but not for targeting ARM. I see there are different D3D12 configurations for ARM and ARM64, but no clear way to differentiate them in hctbuild.
=> Support Ninja as the generator

include/dxc/HLSL/DxilMetadataHelper.h, include/dxc/HLSL/HLModule.h, lib/HLSL/HLOperationLowerExtension.cpp, tools/clang/include/clang/Frontend/CompilerInstance.h
This fixes compiler warnings generated by -Wnon-virtual-dtor.
=> Add default virtual destructors for virtual classes

utils/hct/hctbuild.cmd, utils/hct/hcttest.cmd
Now we can run `hctbuild -s -ninja` to configure to use Ninja as
the generator, run `hctbuild -b` to build the artifacts with Ninja,
and then run `hcttest -ninja` to run the tests.
Also fixes the wrong order in hcttest help message.
=> Support -ninja in hcttest

include/dxc/HLSL/DxilOperations.h, include/dxc/HLSL/DxilTypeSystem.h, lib/HLSL/DxilOperations.cpp, lib/HLSL/DxilTypeSystem.cpp
This solves compiler warnings given by -Wignored-qualifiers.
@dneto0 @ehsannas
=> Remove unnecessary const qualifier on return type

include/llvm/Analysis/DxilConstantFolding.h, lib/Analysis/CMakeLists.txt, lib/Analysis/DxilConstantFolding.cpp, lib/Analysis/DxilConstantFoldingExt.cpp
This commit adds placeholder hooks to support constant folding of
extensions.  They are defined in a separate file to make it easy to merge
changes or link in other versions. There should be no upstream changes to
these definitions.
=> Add hooks for constant folding extensions

tools/clang/include/clang/Frontend/CompilerInstance.h
`DxcLangExtensionsHelperApply` uses `clang::Sema`, which was declared after it.
@dneto0 @ehsannas
=> Declare clang::Sema before referencing it

tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/dxexp/dxexp.cpp, utils/hct/hctcopy.cmd, utils/hct/hcttest.cmd
- Improve option and error handling for hcttest.cmd
- Add hctcopy.cmd for checking source directory and files
- ExecutionTest: Correct experimental mode message when running release
- dxexp: print adapters when experimental fails
=> Improve hcttest.cmd, add hctcopy.cmd

docs/DXIL.rst, include/dxc/HLSL/DxilConstants.h, include/dxc/HLSL/DxilInstructions.h, tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/HlslTestUtils.h, tools/clang/unittests/HLSL/ShaderOpTest.cpp, tools/clang/unittests/HLSL/ShaderOpTest.h, utils/hct/hctdb_inst_docs.txt
This change is to add another execution test case for partial derivative operations specific to pixel shaders.
The way we did this is by passing in the texture resource to the shader and taking the partial derivatives of these texture values.
Test is assuming the arithmetic precision of 1 ulp for derivative operations.
This change also has some changes on existing execution test
- enable passing in Texture2D resource type as a default heap
- reading primitive topology from XML file
- clean up data driven tests: use DirectX Math structures and removing unused structures
=> Add partial derivative test cases for pixel shaders

tools/clang/tools/dxcompiler/dxcvalidator.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/DXIsenseTest.cpp, tools/clang/unittests/HLSL/DxilContainerTest.cpp, tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/ExtensionTest.cpp, tools/clang/unittests/HLSL/FunctionTest.cpp, tools/clang/unittests/HLSL/MSFileSysTest.cpp, tools/clang/unittests/HLSL/Objects.cpp, tools/clang/unittests/HLSL/RewriterTest.cpp, tools/clang/unittests/HLSL/ValidationTest.cpp, utils/hct/hcttest.cmd
- Also refactors DxcDllSupport initialization to setup method.
=> Disable tests requiring name preservation on release builds.

lib/DxcSupport/HLSLOptions.cpp, lib/HLSL/DxilGenerationPass.cpp, tools/clang/lib/CodeGen/CGCall.cpp, tools/clang/test/CodeGenHLSL/BasicHLSL11_PS2.hlsl, tools/clang/test/CodeGenHLSL/temp_dbg_info.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
1. Remove debug info when strip function parameter from entry function.
2. Set OptLevel to 0 for -Od.
3. If optimization is disabled, always load ReturnValue.
=> Fix dbg info for temp variable.

include/dxc/HLSL/DxilMetadataHelper.h, include/dxc/HLSL/DxilModule.h, include/dxc/HLSL/DxilTypeSystem.h, include/dxc/HLSL/HLModule.h, include/dxc/HLSL/HLOperations.h, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilMetadataHelper.cpp, lib/HLSL/DxilModule.cpp, lib/HLSL/DxilTypeSystem.cpp, lib/HLSL/HLModule.cpp, lib/HLSL/HLOperationLower.cpp, lib/HLSL/HLOperations.cpp
1. Add resource attribute to FieldAnnotation.
2. Find resource arribute from Argument in FindCreateHandleResourceBase.
3. Remove limitation handle must be instruction.
4. Add HandleToResCast to help lower resource parameter to handle parameter.
=> Prepare to support handle as parameter.

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/ShaderOpArithTable.xml, utils/hct/hcttest.cmd
This change adds execution unit tests for WaveActiveOp intrinsics.
For wave operations, there is no guarantee of how many lanes exist in a given wave. The test therefore has to manually compute the expected output by identifying different waves in shaders and group lanes by the waves they belong to. This can be done by providing different id's for each structured resource and call WaveReadLaneFirst() on each shader, and mimic what wave intrinsics to compute expected results.
This change also includes other fixes in ExecutionTests including 1)Have TableParameterHandler to read data driven table parameters and 2) fixing typos
=> Add WaveActiveOp execution test

tools/clang/unittests/HLSL/ShaderOpArithTable.xml
This change is to prevent hcttest from producing a known execution test failures on WARP.
These should be enabled once WARP is fixed in the future.
=> Temporalily disabling failing cases: isfinite(NaN) and atan(NaN)

docs/DXIL.rst, include/dxc/HLSL/DxilConstants.h, include/dxc/HLSL/DxilInstructions.h, include/dxc/HLSL/DxilModule.h, include/dxc/HLSL/DxilValidation.h, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilModule.cpp, lib/HLSL/DxilOperations.cpp, lib/HLSL/DxilSemantic.cpp, lib/HLSL/DxilShaderModel.cpp, lib/HLSL/DxilSigPoint.cpp, lib/HLSL/DxilValidation.cpp, tools/clang/test/CodeGenHLSL/attributeAtVertex.hlsl, tools/clang/test/CodeGenHLSL/barycentrics.hlsl, tools/clang/test/HLSL/system-values.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/SystemValueTest.cpp, tools/clang/unittests/HLSL/ValidationTest.cpp, utils/hct/hctdb.py, utils/hct/hctdb_instrhelp.py
- Add SV_ViewID loaded from intrinsic in Dxil, for input to all graphics shader stages
- hctdb: rename shader_models to shader_stages, add shader_model for min required shader model
- Validator: validate dxil version required for shader model
- DxilModule: Add GetDxilVersion
- Set Barycentric intrinsics to SM 6.1
- Update SystemValueTest for SM 6.1
=> Add SV_ViewID support

lib/HLSL/HLMatrixLowerPass.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/cbuffer_copy.hlsl, tools/clang/test/CodeGenHLSL/cbuffer_copy2.hlsl, tools/clang/test/CodeGenHLSL/cbuffer_copy3.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
1. Try to propagate if the pointer is only write once by the memcpy.
2. Use correct size for memcpy created in AppendBuffer::Append.
3. Ignore unused Constant user of Matrix value.
=> Lower memcpy before SORA a pointer.

utils/hct/hctstart.cmd
This allows us to remove cmake instructions for the Visual Studio 2017 Community setup path, then simplify the README.md and move some of the other support build configurations into the Wiki pages.
=> hctstart improvements - use VS2017 cmake, fix cmake version checks

lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/HLOperationLower.cpp, tools/clang/test/CodeGenHLSL/evalInvalid.hlsl, tools/clang/test/CodeGenHLSL/evalMat.hlsl, tools/clang/test/CodeGenHLSL/evalMatMember.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
Currently the compiler crashes when we pass in matrix or vectors with reduced dimension from the original signature element for EvalAttribute functions. This change resolves this issue by replacing allocas before we translate these function calls from DXIR to DXIL and find LoadInputs to replace correctly.
=> Fix EvalauteAttribute Intrinsics

CMakeLists.txt, include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/SPIRV/EmitSPIRVAction.h, tools/clang/include/clang/SPIRV/SPIRVBuilder.h, tools/clang/lib/CMakeLists.txt, tools/clang/lib/SPIRV/CMakeLists.txt, tools/clang/lib/SPIRV/EmitSPIRVAction.cpp, tools/clang/lib/SPIRV/SPIRVBuilder.cpp, tools/clang/tools/dxc/dxc.cpp, tools/clang/tools/dxcompiler/CMakeLists.txt, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, utils/hct/hctbuild.cmd
* Add `libclangSPIRV` and skeleton `ASTFrontendAction` for SPIR-V
* Add `-spirv` into `dxc` for invoking `EmitSPIRVAction`
* Build SPIR-V codegen conditionally using `ENABLE_SPIRV_CODEGEN`
in CMake and `-spirv` in `hctbuild`.
For #216
=> [spirv] Add bare bone code for SPIR-V codegen

include/dxc/HLSL/DxilGenerationPass.h, include/dxc/HLSL/HLModule.h, include/llvm/InitializePasses.h, include/llvm/Transforms/Scalar.h, lib/HLSL/DxcOptimizer.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/HLModule.cpp, lib/HLSL/HLOperationLower.cpp, lib/IR/Pass.cpp, lib/Transforms/IPO/PassManagerBuilder.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/CodeGenHLSL/eval.hlsl, utils/hct/hctdb.py
1. Add ResourceToHandle pass to lower resource to handle.
2. Don't performPromotion in SROA_HLSL.
3. Add Option support for DynamicIndexingVectorToArray.
4. Fix bug in GetPassOption.
5. Replace GEP ptr, 0 with ptr in DynamicIndexingVectorToArray::ReplaceStaticIndexingOnVector.
6. Run mem2reg before DxilGenerationPass.
7. Legalize EvalOperations before change vector to array.
=> Lower static global resource and local resource to handle.

tools/clang/include/clang/AST/OperationKinds.h, tools/clang/include/clang/Sema/Overload.h, tools/clang/lib/CodeGen/CGExpr.cpp, tools/clang/lib/Sema/SemaExprCXX.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/lib/Sema/SemaOverload.cpp, tools/clang/test/CodeGenHLSL/cast7.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
1. Support base in FlattenedTypeIterator.
2. Generate GEP for DerivedToBase except empty struct.
=> Generate GEP for DerivedToBase instead of bitcast.

.gitignore, CMakeLists.txt, external/CMakeLists.txt
We need SPIRV-Headers for spirv.hpp11 and SPIRV-Tools for SPIR-V
diassembling.
=> [spirv] Add SPIRV-Headers and SPIRV-Tools as external dependencies

docs/DXIL.rst, include/dxc/HLSL/DxilValidation.h, lib/HLSL/DxilValidation.cpp, tools/clang/test/CodeGenHLSL/barycentrics1.hlsl, tools/clang/test/CodeGenHLSL/barycentricsThreeSV.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/ValidationTest.cpp, utils/hct/hctdb.py
Unlike other system value semantics, pixel shader is allowed to declare at most two input attributes with SV_Barycentrics such that one declaration uses perspective interpolation type, while other declaration uses noperspective interpolation type.
=> Allow two SV_Barycentrics

tools/clang/unittests/HLSL/ExecutionTest.cpp
The test for WaveActiveAllEqual test was assuming that all inputs had equal masks as the first input.
=> Fix WaveActiveAllEqual test

include/dxc/HLSL/ComputeViewIdState.h, include/dxc/HLSL/DxilContainer.h, include/dxc/HLSL/DxilMetadataHelper.h, include/dxc/HLSL/DxilModule.h, include/dxc/HLSL/DxilPipelineStateValidation.h, include/dxc/HLSL/DxilShaderModel.h, include/dxc/HLSL/HLModule.h, lib/HLSL/ComputeViewIdState.cpp, lib/HLSL/DxilContainerAssembler.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilMetadataHelper.cpp, lib/HLSL/DxilModule.cpp, lib/HLSL/DxilShaderModel.cpp, lib/HLSL/DxilValidation.cpp, lib/HLSL/HLModule.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/CodeGen/CodeGenModule.cpp, tools/clang/tools/dxcompiler/dxcassembler.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp
* Make validator version a first-class citizen of DxilModule
* Add validator version checks to DxilContainerAssembler
- eliminates need to check validator version in dxcompilerobj.cpp
* Copy dynamic index mask and ViewID state to PSV data
- Make const version of DxilViewIDState::GetSerialized() that just returns serialized state
=> Copy ViewID state to PSV data and select PSV version based on validator

include/dxc/HLSL/HLOperations.h, lib/HLSL/HLOperations.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/cbuffer_copy4.hlsl, tools/clang/test/CodeGenHLSL/class.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
1. Generate memcpy in EmitHLSLFlatConversionAggregateCopy if type is match.
2. If value is used as Src of memcpy, mark load instead of store.
3. Do not do replace on GEP and bitcast.
4. Delete inst instead of push into DeadInsts when safe.
This will prevent same inst added into DeadInsts more than once.
=>  Remove copy be replace dst with src.

tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/ShaderOpArithTable.xml
This change adds execution tests for three wave intrinsics: WavePrefixCountBits, WavePrefixSum, and WavePrefixProduct. Like other wave intrinsics tests, these are not set to default hcttests yet.
=> Add WavePrefix execution tests for signed/unsigned integers.

tools/clang/unittests/HLSL/ExecutionTest.cpp
To resolve bad merge conflict for execution test
=> Fix bad merge conflict for WaveActiveAllEqual Execution Test

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
1. Don't require entry function for flattenGlobal.
2. Don't check bForParam for flattenArgument.
3. Don't clone and remove return when replace return value with alloca.
=> Code cleanup.

include/dxc/HLSL/DxilPipelineStateValidation.h, include/dxc/HLSL/ViewIDPipelineValidation.inl
- bFinalStage indicates a non-PS stage is the final one and validation should be performed on direct outputs, rather than waiting for the next stage to merge outputs with inputs.
- Extra validation for PSV
- Treat tessfactors as dynamically indexed to prevent breaking them up
=> Add bFinalStage to ViewIDPipelineValidation

CMakeLists.txt, cmake/modules/AddLLVM.cmake, external/CMakeLists.txt, external/GTestConfig.cmake, tools/clang/unittests/CMakeLists.txt, tools/clang/unittests/SPIRV/CMakeLists.txt, tools/clang/unittests/SPIRV/TestMain.cpp, utils/hct/hctbuild.cmd, utils/hct/hcttest.cmd
GoogleTest will be used for unit testing and codegen testing for
SPIR-V.
* Added SPIRV_BUILD_TESTS option in CMake to control building
of SPIR-V tests.
* Added "-spirvtest" into hctbuild to enable it.
* Added "spirv" and "spirv_only" targets for hcttest.
Running `hcttest spirv` will run ALL tests including SPIRV tests.
Running `hcttest spirv_only` will ONLY run SPIRV tests.
The default behavior of hctbuild and hcttest is not changed.
=> [spirv] Add GoogleTest as an external dependency

include/dxc/HLSL/DxilMetadataHelper.h, include/dxc/HLSL/DxilModule.h, lib/HLSL/DxilMetadataHelper.cpp, lib/HLSL/DxilModule.cpp, lib/HLSL/HLModule.cpp
- Get/Set precise on in instruction in DxilMDHelper
- Get precise based on instruction/global flags in DxilModule
=> Add helper functions for working with precise

include/dxc/HLSL/DxilGenerationPass.h, lib/HLSL/CMakeLists.txt, lib/HLSL/DxcOptimizer.cpp, lib/HLSL/DxilExpandTrigIntrinsics.cpp, tools/clang/test/HLSL/expand_trig/acos.hlsl, tools/clang/test/HLSL/expand_trig/acos_h.hlsl, tools/clang/test/HLSL/expand_trig/asin.hlsl, tools/clang/test/HLSL/expand_trig/asin_h.hlsl, tools/clang/test/HLSL/expand_trig/atan.hlsl, tools/clang/test/HLSL/expand_trig/atan_h.hlsl, tools/clang/test/HLSL/expand_trig/hcos.hlsl, tools/clang/test/HLSL/expand_trig/hcos_h.hlsl, tools/clang/test/HLSL/expand_trig/hsin.hlsl, tools/clang/test/HLSL/expand_trig/hsin_h.hlsl, tools/clang/test/HLSL/expand_trig/htan.hlsl, tools/clang/test/HLSL/expand_trig/htan_h.hlsl, tools/clang/test/HLSL/expand_trig/keep_precise.0.hlsl, tools/clang/test/HLSL/expand_trig/keep_precise.1.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp, utils/hct/hctdb.py
We can now expand the following intrinsics to a sequence of dxil instructions:
Acos
Asin
Atan
Hcos
Hsin
Htan
The expansion uses the same approximation algorithms used by the d3d compiler.
=> Add support for expanding trig intrinsics

include/dxc/HLSL/DxilModule.h, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilModule.cpp, tools/clang/unittests/HLSL/CMakeLists.txt, tools/clang/unittests/HLSL/DxilModuleTest.cpp
This commit updates the `IsPrecise` helper to also check for the fast math
flags on an instruction. Now, the function will return the correct value
for any instruction. Before it only worked for intrinsic calls.
We also added two helpers to get and set precise fast math flags on an
instruction.
Finally, we added a unit test for DxilModule that we can use to ensure
that the `IsPrecise` helper returns the correct value.
=> Update helpers for working with precise

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Parse/ParseDecl.cpp, tools/clang/lib/Sema/SemaDecl.cpp, tools/clang/test/CodeGenHLSL/enum6.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
This change fixes a bug on HLSL 2017 where the compiler crashes when input/output signature contains enum types.
=> Annotate enum type for field attribute.

tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/ShaderOpArithTable.xml, tools/clang/unittests/HLSL/ShaderOpTest.cpp
Restoring default tests as WARP has been fixed for future release.
=> Fix ShaderOpTest parsing and enable tests from warp failures.

tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/ShaderOpArithTable.xml
This change is to check the dll version for D3DWarp10.dll on execution tests so that we don't run tests with dlls with known issues.
=> Check warp version for execution test

tools/clang/unittests/HLSL/ExecutionTest.cpp
This change fixes vs2015 build break by removing equal initializer of TableParameter.
=> Fix VS 2015 Build Break

include/dxc/HLSL/DxilModule.h, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilModule.cpp, tools/clang/test/CodeGenHLSL/multiUAVLoad1.hlsl, tools/clang/test/CodeGenHLSL/multiUAVLoad2.hlsl, tools/clang/test/CodeGenHLSL/multiUAVLoad3.hlsl, tools/clang/test/CodeGenHLSL/multiUAVLoad4.hlsl, tools/clang/test/CodeGenHLSL/multiUAVLoad5.hlsl, tools/clang/test/CodeGenHLSL/multiUAVLoad6.hlsl, tools/clang/test/CodeGenHLSL/uint64_2.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
This change is to fix the bug on fixing multi component UAV Load Flag Check by iterating over UAV resources in a DxilModule and check if a given resource is 1) either texture or typed buffer and 2) multi component resource. This change also changes shader flag collection stage after all necessary passes are complete from higher level DXIL to DXIL.
=> Fix Multiple Component UAV Load Flag Check

include/dxc/HLSL/DxilModule.h, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilModule.cpp, tools/clang/test/CodeGenHLSL/multiUAVLoad1.hlsl, tools/clang/test/CodeGenHLSL/multiUAVLoad2.hlsl, tools/clang/test/CodeGenHLSL/multiUAVLoad3.hlsl, tools/clang/test/CodeGenHLSL/multiUAVLoad4.hlsl, tools/clang/test/CodeGenHLSL/multiUAVLoad5.hlsl, tools/clang/test/CodeGenHLSL/multiUAVLoad6.hlsl, tools/clang/test/CodeGenHLSL/uint64_2.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
This change is to fix the bug on fixing multi component UAV Load Flag Check by iterating over UAV resources in a DxilModule and check if a given resource is 1) either texture or typed buffer and 2) multi component resource. This change also changes shader flag collection stage after all necessary passes are complete from higher level DXIL to DXIL.
=> Fix Multiple Component UAV Load Flag Check (#356)

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/unittests/HLSL/DXIsenseTest.cpp
Sema::InstantiatingTemplate::InstantiatingTemplate is backing off at
this point, and so the HLSL built-ins that have the expectation of
succeeding are not going to deal well with this case. In the (common)
case of a file missing, it might be interesting to continue, but for
robustness the first fix to be made is to be resilient under these
conditions and simply back out.
=> Don't attempt to fault-in HLSL symbols after a fatal error is found.

tools/clang/include/clang/SPIRV/InstBuilder.h, tools/clang/lib/SPIRV/CMakeLists.txt, tools/clang/lib/SPIRV/InstBuilderAuto.cpp, tools/clang/lib/SPIRV/InstBuilderManual.cpp, tools/clang/unittests/SPIRV/CMakeLists.txt, tools/clang/unittests/SPIRV/InstBuilderTest.cpp, tools/clang/unittests/SPIRV/SPIRVTestUtils.h
The instruction builder is responsible for constructing SPIR-V
instructions. It provides a corresponding method for each SPIR-V
instruction, with signature mimicking the instruction layout.
Minimal checking is provided to make sure that the constructed
instruction has the correct layout at least.
=> [spirv] Add low-level instruction builder

lib/HLSL/DxilModule.cpp, tools/clang/test/CodeGenHLSL/multiUAVLoad5.hlsl, tools/clang/test/CodeGenHLSL/multiUAVLoad6.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
Multi component UAV load check should only be done on Load operation, not Store operations.
=> [DXIL-2017-06] Check multi component uav on load not store operations.

tools/clang/include/clang/SPIRV/Structure.h, tools/clang/lib/SPIRV/CMakeLists.txt, tools/clang/lib/SPIRV/Structure.cpp, tools/clang/unittests/SPIRV/CMakeLists.txt, tools/clang/unittests/SPIRV/StructureTest.cpp
Added classes for various SPIR-V concepts, including instruction,
basic block, module, and function, and others. These will be used
in the module builder.
=> [spirv] Add structured representaion of SPIR-V entities

include/dxc/HLSL/DxilPipelineStateValidation.h, include/dxc/HLSL/ViewIDPipelineValidation.inl
- Differentiate inputs/outputs for return code
- Use original element id for easier debugging of ViewID packing
=> Interpret all elements as arbitrary for ViewID packing validation

include/dxc/HLSL/DxilPipelineStateValidation.h, include/dxc/HLSL/ViewIDPipelineValidation.inl
- Differentiate inputs/outputs for return code
- Use original element id for easier debugging of ViewID packing
=> [dxil-2017-06] Interpret all elements as arbitrary for ViewID packing validation

tools/clang/include/clang/Basic/DiagnosticParseKinds.td, tools/clang/lib/Parse/ParseDecl.cpp, tools/clang/test/HLSL/effects-syntax.hlsl
dxc requres equals sign to use brace-enclosed initializer.
=> Fix dxc crash on invalid brace-enclosed initializer

appveyor.yml, external/CMakeLists.txt, tools/clang/include/clang/SPIRV/String.h, tools/clang/include/clang/SPIRV/Type.h, tools/clang/lib/SPIRV/String.cpp, tools/clang/lib/SPIRV/Type.cpp, tools/clang/test/CodeGenSPIRV/basic.hlsl2spv, tools/clang/unittests/SPIRV/CMakeLists.txt, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp, tools/clang/unittests/SPIRV/SPIRVContextTest.cpp, tools/clang/unittests/SPIRV/SPIRVTestOptions.cpp, tools/clang/unittests/SPIRV/SPIRVTestOptions.h, tools/clang/unittests/SPIRV/TestMain.cpp, tools/clang/unittests/SPIRV/TypeTest.cpp, tools/clang/unittests/SPIRV/WholeFileCheck.cpp, tools/clang/unittests/SPIRV/WholeFileCheck.h, utils/hct/hcttest.cmd
This change enables CodeGenSPIRV test flow.
New tests can be added by simply adding the test file to
`tools/clang/test/CodeGenSPIRV/` directory and running:
```cpp
TEST_F(WholeFileTest, NewTest) {
EXPECT_TRUE(runWholeFileTest("new-test-name"));
}
```
The input file with the format described in `WholeFileCheck.h` is read in;
the HLSL portion is passed to the compiler with SPIR-V codegen enabled.
The resulting SPIR-V binary is disassembled and compared to the expected
result in the input file.
=> [spirv] Adding test fixture for HLSL to SPIRV codegen flow

tools/clang/include/clang/Basic/DiagnosticParseKinds.td, tools/clang/lib/Parse/ParseDecl.cpp, tools/clang/lib/Parse/Parser.cpp, tools/clang/test/HLSL/effects-syntax.hlsl, tools/clang/test/HLSL/rewriter/correct_rewrites/shared.hlsl, tools/clang/test/HLSL/rewriter/shared.hlsl, tools/clang/unittests/HLSL/RewriterTest.cpp
1. Fix dxc crash on invalid brace-enclosed initializer
2. Ignore shared keyword on cbuffer/tbuffer
=> Bug fixes for dxil-2017-06

cmake/modules/FindTAEF.cmake, tools/clang/unittests/HLSL/clang-hlsl-tests.vcxproj.user.txt
The WDK was used before because it used x64 rather than amd64, like msbuild/VS.
This didn't work when there was no WDK installed and only external TAEF was available.
This fix includes a check for amd64 when x64 msbuild is used, and so external can now be used.
=> Fix te discovery from external dir, including x64/amd64 usage.

utils/hct/hctdb.py, utils/hct/hctdb_instrhelp.py
Allows the hctdb_instrhelper.py script to be run from outside
utils/hct. No change in generated code.
=> Look for extra hctdb files in same dir as hctdb scripts

lib/HLSL/DxilModule.cpp, tools/clang/test/CodeGenHLSL/multiUAVLoad7.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
Previous fix on this checked for multi component elements for UAV, but not its resource types. This change checks if UAV Load is of typed buffer or texture and sets the flag accordingly.
=> Fix Typed UAV Load flag collection

tools/clang/unittests/HLSL/ExecutionTest.cpp
Right now this test is assuming that QuadReadLaneAt is returning correctly values for all lanes in same quad, which is not necessarily true for buggy drivers.
New test is fixed so that only assumption we make is that WaveReadLaneFirst is always correct.
=> WaveIntrinsicsInPS test fix (#409)

tools/clang/lib/AST/ASTContextHLSL.cpp, tools/clang/lib/Basic/Targets.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/PatchLength1.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
- use IntTy for object template dimension argument.
- Fix name of TypenameTrue to TypenameFalse, since that's what it means.
- Fix index of vector dimension template argument.
- Fix long bit width/align to 32 for DXILTargetInfo
=> Implement Length on Input/OutputPatch objects

include/llvm/ADT/StringRef.h, tools/clang/lib/Basic/DiagnosticIDs.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
In particular, out-of-memory exceptions thrown during string construction in the context of certain move constructors (in this case, and std::pair) would cause the runtime to terminate the process.
The problem is that a noexcept specification was added to some STL move constructors incorrectly, and when the runtime finds such a frame while unwinding, it will invoke std::terminate(). See the comments and static assertions for more details.
A future change will remove debug iterators from Debug builds (the default) and so the out-of-memory tests will be run more regularly; at the time it seems to be of more use finding issues than the iterator checks.
=> Additional fixes for error handling exposed by OOM testing

include/dxc/HLSL/DxilGenerationPass.h, lib/HLSL/CMakeLists.txt, lib/HLSL/DxcOptimizer.cpp, lib/HLSL/DxilReduceMSAAToSingleSample.cpp, tools/clang/test/HLSL/pix/msaaLoad.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp, utils/hct/hctdb.py
This pass will be used in PIX for "Dr. PIX experiments", wherein a workload is re-rendered with MSAA turned off in order to get an approximate understanding of the performance impact of MSAA.
=> (PIX) Reduce msaa to single-sample

tools/clang/test/HLSL/pix/msaaLoad.hlsl
This change deletes the operands that change when fre builds are run. As luck would have it, they all appear in these checked lines after the parts that the test needs to check.
(These tests now pass on x86 fre)
=> Test Fix: Deleted checks for fields that are different in fre builds

tools/clang/lib/CodeGen/CGExprConstant.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/static_const_global.hlsl, tools/clang/test/CodeGenHLSL/static_const_global2.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
For static const globals like:
cbuffer A {
float a;
int b;
}
const static struct {
float a;
int b;
}  ST = { a, b };
We want to replace use of ST with a and b.
Also support CK_HLSLMatrixSplat in ConstExprEmitter::VisitCastExpr.
=> Replace static const global struct for library.

tools/clang/include/clang/SPIRV/InstBuilder.h, tools/clang/lib/SPIRV/InstBuilderAuto.cpp
=> [spirv] Use ArrayRef instead of initializer_list in InstBuilder

tools/clang/lib/SPIRV/EmitSPIRVAction.cpp, tools/clang/unittests/SPIRV/WholeFileCheck.cpp
* Added DiagnosticsEngine to the SPIRVEmitter
* Updated the WholeFileCheck flow to show the warning and error
messages.
* If an Error level message is added to the Diagnostics, the compiler
is considered to have failed (gtest will be marked as FAILED).
* Warning level messages are printed and considered a PASS.
=> [spirv] Start using DiagnosticsEngine.

tools/clang/tools/dotnetc/D3DCompiler.cs, tools/clang/tools/dotnetc/DotNetDxc.cs, tools/clang/tools/dotnetc/EditorForm.Designer.cs, tools/clang/tools/dotnetc/EditorForm.cs, tools/clang/tools/dotnetc/dia2.cs, tools/clang/tools/dotnetc/dndxc.csproj.txt, tools/clang/tools/dxcompiler/dxcdia.cpp, tools/clang/tools/dxcompiler/dxcdisassembler.cpp, tools/clang/tools/dxcompiler/dxcutil.cpp, tools/clang/tools/dxcompiler/dxcutil.h, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/DxcTestUtils.h
Fixes failure when bitcode cannot be parsed by the dxc dia data source.
Adds support for ILDB parts to dia (saves the need to skip header in clients).
Adds support to dndxc to dump debug information.
Adds support to dndxc to compile and disassemble d3dcompiler-based shaders.
=> dia improvements

tools/clang/include/clang/SPIRV/BlockReadableOrder.h, tools/clang/include/clang/SPIRV/Constant.h, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/include/clang/SPIRV/Structure.h, tools/clang/lib/SPIRV/BlockReadableOrder.cpp, tools/clang/lib/SPIRV/CMakeLists.txt, tools/clang/lib/SPIRV/EmitSPIRVAction.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/Structure.cpp, tools/clang/test/CodeGenSPIRV/cf.if.for.hlsl, tools/clang/test/CodeGenSPIRV/for-stmt.nested.hlsl, tools/clang/test/CodeGenSPIRV/if-stmt.nested.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp, tools/clang/unittests/SPIRV/ConstantTest.cpp, tools/clang/unittests/SPIRV/SPIRVContextTest.cpp
SPIR-V spec requires basic blocks to appear in an order satisfying
the dominator-tree direction. Added a BlockReadableOrderVisitor
class for visiting basic blocks in a human-readable order following
the spec's requirements.
Also fixed a bug in Constant::operator==(), which causes hashing
weirdness.
=> [spirv] Handle basic block orders

tools/clang/tools/dxlib-sample/lib_share_preprocessor.cpp, tools/clang/unittests/dxc_batch/dxc_batch.cpp
Fix release fail on dxc_batch caused by string append using llvm::Twine and CW2A.
=> Fix release fail on dxc_batch caused by string append

external/CMakeLists.txt
With this change, targets in the subdirectory will not be included
in the ALL target of the parent directory by default, and will be
excluded from IDE project files.
=> [spirv] Use EXCLUDE_FROM_ALL to ignore unused external targets

docs/SPIR-V.rst, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/EmitSPIRVAction.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.dot.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
The translation supports dot product of vectors of floats using
SPIR-V's OpDot.
The translation also supports dot product of vectros of integers
using multiplication and addition.
=> [spirv] Translate intrinsic dot product.

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/EmitSPIRVAction.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/test/CodeGenSPIRV/switch-stmt.opswitch.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
SPIR-V OpSwitch can be used to represent HLSL switch statements when all
case values are integer literals (or constant integer variables).
This CL also handles pass-through cases and nested switch statements.
=> [spirv] Translate switch statements using OpSwitch

include/dxc/Support/WinIncludes.h, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/CodeGenHLSL/shader-compat-suite/lib_arg_flatten/lib_empty_struct_arg.hlsl, tools/clang/test/CodeGenHLSL/shader-compat-suite/lib_arg_flatten/lib_ret_struct.hlsl
1. Support empty struct as call arg.
2. Define _ATL_DECLSPEC_ALLOCATOR for older atlbase.h
3. Fix typo in SROA_Parameter_HLSL::preprocessArgUsedInCall for use AllocaBuilder when need RetBuilder.
=> Bug fixes.

tools/clang/lib/SPIRV/EmitSPIRVAction.cpp, tools/clang/test/CodeGenSPIRV/op.matrix.access.1x1.hlsl, tools/clang/test/CodeGenSPIRV/op.matrix.access.1xn.hlsl, tools/clang/test/CodeGenSPIRV/op.matrix.access.mx1.hlsl, tools/clang/test/CodeGenSPIRV/op.matrix.access.mxn.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
This PR handles two formats for indexing matrices: _mXX and _XX.
The operator[] format will be handled in the next PR.
=> [spirv] Add support for matrix swizzling

tools/clang/lib/SPIRV/EmitSPIRVAction.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/op.matrix.access.1x1.hlsl, tools/clang/test/CodeGenSPIRV/op.matrix.access.1xn.hlsl, tools/clang/test/CodeGenSPIRV/op.matrix.access.mx1.hlsl, tools/clang/test/CodeGenSPIRV/op.matrix.access.mxn.hlsl, tools/clang/test/CodeGenSPIRV/op.vector.access.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
A temporary variable will be created if we are indexing into
a rvalue vector/matrix. This is because we can have variables
as indices, which mandates the use of OpAccessChain. And
OpAccessChain requires a variable that can be loaded or stored.
=> [spirv] Translate operator[] for vector and matrix types

tools/clang/lib/AST/ExprConstant.cpp, tools/clang/test/CodeGenSPIRV/cast.vector.splat.hlsl, tools/clang/test/CodeGenSPIRV/var.init.hlsl
Initializer lists in HLSL are very flexible; the front end right
now doesn't handle their const evaluation to the full. This change
only turns on a specific case: intializing vectors.
=> Allow const evaluating vector initializer lists in the frontend

tools/clang/lib/SPIRV/CMakeLists.txt, tools/clang/lib/SPIRV/InitListHandler.cpp, tools/clang/lib/SPIRV/InitListHandler.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/var.init.hlsl, tools/clang/test/CodeGenSPIRV/var.init.matrix.1x1.hlsl, tools/clang/test/CodeGenSPIRV/var.init.matrix.1xn.hlsl, tools/clang/test/CodeGenSPIRV/var.init.matrix.mx1.hlsl, tools/clang/test/CodeGenSPIRV/var.init.matrix.mxn.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Initializer lists are flexible in HLSL to the extent that as long
as the total number elements is correct, it will be accepted.
To support such flexibility, we need to conduct composite
extraction/construction and proper casting when necessary.
A new dedicated class is introduced for handling initializer lists.
It is built on top of the SPIRVEmitter class. It holds the logic
for correct initializer list handling and calls into SPIRVEmitter
for normal translating tasks. So is in a sense higher level than
the SPIRVEmitter class.
Also extended cast methods and vector type probing functions to
support ExtVectorType since we need to construct ExtVectorType
when handling initializer lists.
=> [spirv] Revise to provide more initializer list support

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/binary-op.arith-assign.mixed.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.arithmetic.mixed.hlsl
SPIR-V has a specific OpMatrixTimesScalar for scaling floating
point matrices.
=> [spirv] Optimize floating point matrix scaling codegen

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv, tools/clang/test/CodeGenSPIRV/passthru-vs.hlsl2spv, tools/clang/test/CodeGenSPIRV/semantic.arbitrary.hlsl, tools/clang/test/CodeGenSPIRV/semantic.depth.ps.hlsl, tools/clang/test/CodeGenSPIRV/semantic.instance-id.ps.hlsl, tools/clang/test/CodeGenSPIRV/semantic.instance-id.vs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.position.ps.hlsl, tools/clang/test/CodeGenSPIRV/semantic.position.vs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.target.ps.hlsl, tools/clang/test/CodeGenSPIRV/semantic.vertex-id.vs.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Includes: SV_Position, SV_Target, SV_VertexID, SV_InstanceID,
and SV_Depth.
Also use existing DXIL classes for stage variables. There already
exist classes for semantics and SigPoints. Reuse them to create a
StageVar class for holding information about stage variables.
=> [spirv] Support several SV semantics in VS and PS

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/spirv.storage-class.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
We now compute and store decl storage class in DeclResultIdMapper.
Querying is done using RecursiveASTVisitor to check DeclRefExpr,
FunctionDecl, ParmVarDecl, and FieldDecl for normal and remapped
Decls.
Fixed various hard coded storage class in SPIRVEmitter.
=> [spirv] Derive storage class properly from original variables

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h
Make the type probing methods in TypeTranslator much more clear
as for their responsibilities.
=> [spirv] Sanitize scalar/vector/matrix type probing methods

docs/SPIR-V.rst, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/break-stmt.mixed.hlsl, tools/clang/test/CodeGenSPIRV/cf.if.for.hlsl, tools/clang/test/CodeGenSPIRV/constant-ps.hlsl2spv, tools/clang/test/CodeGenSPIRV/empty-void-main.hlsl2spv, tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv, tools/clang/test/CodeGenSPIRV/passthru-vs.hlsl2spv, tools/clang/test/CodeGenSPIRV/semantic.arbitrary.hlsl, tools/clang/test/CodeGenSPIRV/semantic.depth.ps.hlsl, tools/clang/test/CodeGenSPIRV/semantic.instance-id.ps.hlsl, tools/clang/test/CodeGenSPIRV/semantic.instance-id.vs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.position.ps.hlsl, tools/clang/test/CodeGenSPIRV/semantic.position.vs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.target.ps.hlsl, tools/clang/test/CodeGenSPIRV/semantic.vertex-id.vs.hlsl, tools/clang/test/CodeGenSPIRV/spirv.entry-function.wrapper.hlsl, tools/clang/test/CodeGenSPIRV/spirv.storage-class.hlsl, tools/clang/test/CodeGenSPIRV/var.init.hlsl, tools/clang/test/CodeGenSPIRV/var.init.struct.hlsl, tools/clang/test/CodeGenSPIRV/var.static.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Previously for an entry function, we decompose its parameters and
return value and create stage input/output/builtin variables from
them directly. This is fine for simple shaders, but it will have
problems for shaders using structs to group stage variables.
Accessing paramters and return values (using operator. and return)
needs special handling for entry functions, which is nasty.
With the wrapper function, we can handle entry functions just like
normal functions. Stage variable handling are all done in the
wrapper funtion.
=> [spirv] Converted to generate wrapper for entry function

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/test/CodeGenSPIRV/constant-ps.hlsl2spv, tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv, tools/clang/test/CodeGenSPIRV/passthru-vs.hlsl2spv, tools/clang/test/CodeGenSPIRV/semantic.arbitrary.location.hlsl, tools/clang/test/CodeGenSPIRV/semantic.duplication.hlsl, tools/clang/test/CodeGenSPIRV/semantic.target.ps.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp, tools/clang/unittests/SPIRV/FileTestFixture.cpp, tools/clang/unittests/SPIRV/FileTestFixture.h, tools/clang/unittests/SPIRV/FileTestUtils.cpp, tools/clang/unittests/SPIRV/FileTestUtils.h, tools/clang/unittests/SPIRV/WholeFileTestFixture.cpp
SV_Target[N] is treated differently; they will always be assigned
the location N. For other semantics that does not map to builtin
variables, assign locations to them alphabetically.
Also extended FileTest fixture to support checking the contents
of error messages.
=> [spirv] Assign locations to stage I/O variables alphabetically

tools/clang/include/clang/Basic/Attr.td, tools/clang/include/clang/Basic/LangOptions.h, tools/clang/include/clang/Parse/Parser.h, tools/clang/lib/Parse/ParseDeclCXX.cpp, tools/clang/lib/Parse/ParseTentative.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv, tools/clang/test/CodeGenSPIRV/vk.location.exp-in.hlsl, tools/clang/test/CodeGenSPIRV/vk.location.exp-out.hlsl, tools/clang/test/CodeGenSPIRV/vk.location.hlsl, tools/clang/test/CodeGenSPIRV/vk.location.large.hlsl, tools/clang/test/CodeGenSPIRV/vk.location.mixed.hlsl, tools/clang/test/CodeGenSPIRV/vk.location.reassign.hlsl, tools/clang/test/HLSL/cxx11-attributes.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/VerifierTest.cpp, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp, tools/clang/utils/TableGen/ClangAttrEmitter.cpp
This commit turns on C++11 attributes for HLSL globally. C++11
attributes will be parsed where they are allowed in C++11.
However, they will just result in an warning of ignored attribute,
without any semantic impact for the general DXIL CodeGen.
For SPIR-V CodeGen, C++11 attributes within the vk namespace will
be interpreted and converted to semantic AST nodes.
=> [spirv] Turn on C++11 attributes and support [[vk::location(X)]]

docs/SPIR-V.rst, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/type.sampler.hlsl, tools/clang/test/CodeGenSPIRV/type.texture.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
This commit add support for the following types:
* Texture1D, Texture2D, Texture3D, TextureCube
* Texture1DArray, Texture2DArray, TextureCubeArray
* SamplerState, SamplerComparisonState, sampler
Buffer, Texture2DMS, and Texture2DMSArray is not supported yet,
also setting sampler states.
Texture types will be translated OpTypeImage, and sampler types
will be translated into OpTypeSampler.
=> [spirv] Support texture and sampler types

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/texture.array.gather.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.load.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample-bias.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample-grad.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample-level.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample.hlsl, tools/clang/test/CodeGenSPIRV/texture.gather.hlsl, tools/clang/test/CodeGenSPIRV/texture.load.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-bias.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-grad.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-level.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
This commit add support for the following methods on textures:
* .Sample()
* .SampleLevel()
* .SampleGrad()
* .SampleBias()
* .Load()
* .Gather()
=> [spirv] Support six texture methods

docs/SPIR-V.rst, tools/clang/include/clang/Basic/Attr.td, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenSPIRV/vk.binding.explicit.error.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.explicit.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.implicit.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.register.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
This commit add support for resource binding number assignment via
both the explicit and the implicit way.
The explicit way:
[[vk::binding(X[, Y])]] is introduced, with X denoting the binding
number and the optional Y denoting the set number. If Y is missing,
the set number will be set to 0. This attribute can only be attached
to variables.
The implicit way:
register(xX, spaceY) will be used to deduce the correct set and
binding number for a given resource. X will be used as the binding
number and Y will be used as the set number. Right now we do not
consider the resource type x, which means binding numbers can
overlap given the same X and Y but not x. That is to be addressed
later.
=> [spirv] Support setting resource binding numbers

docs/SPIR-V.rst, include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/SPIRV/EmitSPIRVAction.h, tools/clang/include/clang/SPIRV/EmitSPIRVOptions.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/EmitSPIRVAction.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/passthru-vs.hlsl2spv, tools/clang/test/CodeGenSPIRV/semantic.arbitrary.location.alpha.hlsl, tools/clang/test/CodeGenSPIRV/semantic.arbitrary.location.decl.hlsl, tools/clang/test/CodeGenSPIRV/vk.location.exp-in.hlsl, tools/clang/test/CodeGenSPIRV/vk.location.exp-out.hlsl, tools/clang/tools/dxc/dxc.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp, tools/clang/unittests/SPIRV/FileTestFixture.cpp, tools/clang/unittests/SPIRV/FileTestFixture.h, tools/clang/unittests/SPIRV/FileTestUtils.cpp, tools/clang/unittests/SPIRV/FileTestUtils.h, tools/clang/unittests/SPIRV/WholeFileTestFixture.cpp, tools/clang/unittests/SPIRV/WholeFileTestFixture.h
A new CL option -fvk-stage-io-order={alpha|decl} is added to
control the order for assigning stage I/O location numbers.
The default is also changed to declaration order (decl) instead
of alphabetical order (alpha).
Also extended testing fixtures to support additional CL options.
=> [spirv] Add CL option for stage I/O location assignment order

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/include/clang/SPIRV/Structure.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/texture.array.gather.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample-bias.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample-grad.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample-level.hlsl, tools/clang/test/CodeGenSPIRV/texture.load.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-bias.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-grad.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-level.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample.hlsl
Non-constant offset should be translated into the Offset image
operands instead of ConstOffset.
=> [spirv] Support non-constant offset in texture methods

tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/ShaderOpArithTable.xml
Fix Wave intrinsics tests to not assume that lane id is in same order as thread id
=> Fix Wave Intrinsics Tests

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/method.structured-buffer.load.hlsl, tools/clang/test/CodeGenSPIRV/op.array.access.hlsl, tools/clang/test/CodeGenSPIRV/op.constant-buffer.access.hlsl, tools/clang/test/CodeGenSPIRV/op.rw-structured-buffer.access.hlsl, tools/clang/test/CodeGenSPIRV/op.struct.access.hlsl, tools/clang/test/CodeGenSPIRV/op.structured-buffer.access.hlsl, tools/clang/test/CodeGenSPIRV/spirv.storage-class.hlsl, tools/clang/test/CodeGenSPIRV/type.structured-buffer.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.explicit.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.implicit.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.register.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.sbuffer.nested.std430.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.sbuffer.std430.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
* Supported (RW)StructuredBuffer types
* Supported accessing elements in (RW)StructuredBuffer
* Supported the Load() method
* Supported std430 layout
Also optimized OpAccessChain CodeGen. This is necessary right
now because otherwise we will have pointers to intermediate
composite objects like structs and arrays. Structs/arrays are
different types with and without layout decorations. To have the
correct struct/array pointer type for OpAccessChain, we need to
always pass in the correct layout rules when translating the
types, which is not easy. Optimizing intermediate OpAccessChain
away solves the problem because scalar/vector/matrix types are
unique given the same parameter.
=> [spirv] Add support for (RW)StructuredBuffer

README.md, docs/SPIR-V.rst
Moved logistics and designs to the wiki page. Now the doc is only
for HLSL to SPIR-V mappings.
Also link to the doc and wiki page in the main README.md.
=> [spirv] Update SPIR-V.rst doc

lib/HLSL/DxilContainerReflection.cpp
If reflection version is not D3D12, ZeroMemoryToOut will overwrite
memory outside of the user's pDesc struct, leading to stack or
heap corruption.  I removed ZeroMemoryToOut, since the right amount
of data should be written in each case.
=> Fix out of bounds memory write in GetResourceBindingDescByName

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/buffer.load.hlsl, tools/clang/test/CodeGenSPIRV/op.buffer.access.hlsl, tools/clang/test/CodeGenSPIRV/texture.load.hlsl
Also fixes 2 bugs:
1- RWBuffer must use OpImageRead rather than OpImageFetch.
2- OpImageFetch/Read take a parameter whose type is an image. We were
incorectly passing the *variable* (which is of type pointer-to-image).
This change also allows TextureXX<type> to be used with types other than
float4. Tests were added for such cases.
=> [spirv] Refactor Buffer and Texture load functions

tools/clang/lib/AST/ExprConstant.cpp, tools/clang/test/HLSL/const-expr.hlsl
Support for scalars was inconsistent, with the CheckICE path reporting that expressions of functional casting "typename (args)" was supported for scalars, but the evaluator rejecting them. Fixing the scalar path (as well as the init list case) so it's consistently supported.
=> Fix #604 by handling scalar functional inits in ICE and evaluation

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/binary-op.assign.composite.hlsl, tools/clang/test/CodeGenSPIRV/method.structured-buffer.load.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
For these objects, if the lhs and rhs are of different storage
class, we may need to do the assignment recursively at the
non-composite level since OpStore requires that the pointer's
type operand must be the same as the type of object.
=> [spirv] Support assigning to objects of composite types

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/method.append-structured-buffer.append.hlsl, tools/clang/test/CodeGenSPIRV/method.consume-structured-buffer.consume.hlsl, tools/clang/test/CodeGenSPIRV/type.append-structured-buffer.hlsl, tools/clang/test/CodeGenSPIRV/type.consume-structured-buffer.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.explicit.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.implicit.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.register.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.asbuffer.std430.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.csbuffer.std430.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
* Supported the `{Append|Consume}StructureBuffer` type
* Supported `.Append()` and `.Consume()`
`{Append|Consume}StructureBuffer<S>` is implemented as `OpTypeStruct`
with an `OpTypeRuntimeArray` of `S`. And each such array will have
an associated counter, whose type is `OpTypeStruct` of 32-bit integer.
The index for `.Append()`/`.Conume()` is fetched by doing atomic
operations on the associated counter.
=> [spirv] Support {Append|Consume}StructuredBuffer

docs/SPIR-V.rst
There was a typo on the section headline for HLSL semantic and Vulkan Location
=> Fix typo in SPIR-V.rst

docs/DXIL.rst, include/dxc/HLSL/DxilCompType.h, include/dxc/HLSL/DxilConstants.h, include/dxc/HLSL/DxilSignature.h, include/dxc/HLSL/DxilSignatureAllocator.h, include/dxc/HLSL/DxilSignatureAllocator.inl, include/dxc/HLSL/DxilSignatureElement.h, include/dxc/HLSL/DxilValidation.h, include/dxc/HLSL/ViewIDPipelineValidation.inl, lib/HLSL/DxilCompType.cpp, lib/HLSL/DxilContainerAssembler.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilModule.cpp, lib/HLSL/DxilSignature.cpp, lib/HLSL/DxilSignatureElement.cpp, lib/HLSL/DxilValidation.cpp, tools/clang/test/CodeGenHLSL/signature_packing.hlsl, tools/clang/test/CodeGenHLSL/signature_packing_by_width.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/ValidationTest.cpp, utils/hct/hctdb.py
This change is to enforce the new constraint on signature packing: pack signature elements by data width. Before we introduce fp16 type, every element was assumed to reserve 32 bits. Since we are introducing a new 16 bit data type, we need a new way to enforce signature rules.
After discussions we decided that it would be nice to pack elements based on data width. However, we are still enforcing the rule that each row contains up to 4 elements, regardless of the size. This way, depending on the hardware support drivers can optimize packing signatures, while on DXIL level we maintain the assumption that there are 4 elements per row. We are also still constraining on the total number of rows to be 32 for now. This can be changed in the future if people find this limit to be an issue.
=> Group Signature Elements by Element Width

include/dxc/HLSL/ViewIDPipelineValidation.inl
ignore element interpolation since normal signature ignores it.
=> ViewID validation fix

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/method.struct.method.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Member functions are translated into SPIR-V standalone functions
with an additional first parameter for the struct type.
=> [spirv] Support struct member functions

appveyor.yml
This pull request enables uploading build artifacts to Appveyor Artifacts
page. I've tried out this pull request and it works. You can check it [here](https://ci.appveyor.com/project/antiagainst/directxshadercompiler/build/1.0.504/artifacts).
With this, devs can just directly download the latest build from Appveyor
instead of building by themselves.
All `.exe` and `.dll` in the `build` directly are uploaded. We can revisit
the list later if necessary.
Also made a few other changes to the script:
* Change Git clone depth to 1
* Removed duplicated env setting commands (the default CD is already
source repo root)
=> Upload artifacts in Appveyor Artifacts page

docs/SPIR-V.rst, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/buffer.get-dimensions.hlsl, tools/clang/test/CodeGenSPIRV/method.byte-address-buffer.get-dimensions.hlsl, tools/clang/test/CodeGenSPIRV/method.structured-buffer.get-dimensions.hlsl, tools/clang/test/CodeGenSPIRV/rwtexture.get-dimensions.hlsl, tools/clang/test/CodeGenSPIRV/texture.get-dimensions.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
GetDimensions function implementation for:
Textures, RWTextures,
Buffers, RWBuffers,
ByteAddressBuffers, RWByteAddressBuffers,
StructuredBuffers, RWStructuredBuffers.
=> [spirv] GetDimensions for several types.

lib/HLSL/DxcOptimizer.cpp, lib/HLSL/DxilAddPixelHitInstrumentation.cpp, lib/HLSL/DxilMetadataHelper.cpp, lib/HLSL/DxilModule.cpp, tools/clang/test/HLSL/pix/forceEarlyZ.hlsl, tools/clang/test/HLSL/pix/pixelCounter.hlsl, tools/clang/test/HLSL/pix/pixelCounterAddPixelCost.hlsl, tools/clang/test/HLSL/pix/pixelCounterEarlyZ.hlsl, utils/hct/hctdb.py
The changes in DxilModule and DxilMetaDataHelper allow passes to re-emit the DXIL type system, which is helpful when adding new resources.
The changes to the pass itself are:
-Convert to raw UAV access. A certain driver is apparently not inferring the stride (for a structured buffer) from the type defined in the DXIL, but is rather taking the stride from the API-defined element stride. Unfortunately, this stride isn't definable at the API for a root-parameter UAV, so the driver really has to infer the stride from the structured UAV type.
-Move the UAV handle creation to the top of the function. This isn't strictly necessary but makes the resulting DXIL more idiomatic.
-Assign the correct resource handle to the UAV. Previously, the UAV was picking the default 0 handle, which could conflict …
=> PIX pixel-hit instrumentation: Re-emit type system, fix several issues with the UAV

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/ShaderOpTest.cpp
This test is mainly to test that half types in function signature works as expected. Not enabled by default yet.
=> Add Basic Triangle Half Test

README.md
We have moved the instructions for ninja into the wiki.
=> Stop mentioning ninja for testing in README

docs/SPIR-V.rst, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/test/CodeGenSPIRV/vk.binding.explicit.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.register.hlsl
Now we essentially assign binding numbers to all resources in
three passes: [[vk::binding(...)]], register(...), and then
no annotation.
=> [spirv] Tweak binding number assignment scheme

tools/clang/include/clang/Basic/Attr.td, tools/clang/include/clang/Parse/Parser.h, tools/clang/lib/Parse/ParseDecl.cpp, tools/clang/lib/Parse/ParseHLSL.cpp, tools/clang/test/CodeGenSPIRV/vk.binding.explicit.hlsl, tools/clang/test/HLSL/cxx11-attributes.hlsl
This commit adds support for explicit binding assignment in
cbuffer/tbuffer/ConstantBuffer/TextureBuffer.
=> [spirv] Add support explicit binding for CTBuffer

tools/clang/lib/AST/Decl.cpp, tools/clang/lib/CodeGen/CodeGenModule.cpp, tools/clang/lib/Parse/ParseDecl.cpp, tools/clang/lib/Sema/SemaDecl.cpp, tools/clang/test/CodeGenHLSL/staticGlobals5.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
For now we are setting static data member to have internal linkage simply because current module passes does not remove global variable for static data member unless it's an internal linkage (LowerStaticGlobalIntoAlloca), and we do not allow instructions using global variables. This can be fixed in the future if we want to keep static data member to maintain external linkage and create an extra pass to handle this.
=> Fix static data member const issue. 

docs/SPIR-V.rst, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/texture.array.gather-alpha.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.gather-blue.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.gather-green.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.gather-red.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.gather.hlsl, tools/clang/test/CodeGenSPIRV/texture.gather-alpha.hlsl, tools/clang/test/CodeGenSPIRV/texture.gather-blue.hlsl, tools/clang/test/CodeGenSPIRV/texture.gather-green.hlsl, tools/clang/test/CodeGenSPIRV/texture.gather-red.hlsl, tools/clang/test/CodeGenSPIRV/texture.gather.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Also extended tests for .Gather() tests to cover scalar element
types and vector element types with less than 4 components.
=> [spirv] Add support for .GatherRGBA() methods on texture types

tools/clang/lib/SPIRV/SPIRVEmitter.cpp
This prevents us from calling legalization/optimization passes
on invalid SPIR-V binary code.
=> [spirv] Stop if errors happen during translating Decls

docs/SPIR-V.rst, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/texture.array.gather-cmp-red.hlsl, tools/clang/test/CodeGenSPIRV/texture.gather-cmp-red.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
`.GatherCmp{Green|Blue|Alpha}()` is not supported yet.
=> [spirv] Add support for texture .GatherCmpRed() method

cmake/modules/AddLLVM.cmake, tools/clang/lib/Basic/CMakeLists.txt
Updating dxcompiler file version and llvm.ident version to 2017 10 for new release.
=> Update version to 2017 10

tools/dxexp/dxexp.cpp
dxexp.cpp tries to define some types if they are not found in
the SDK. However, we cannot use #ifndef to test whether a type
is defined or not. Use WDK_NTDDI_VERSION instead to do the
check instead.
d3d12.h in Windows SDK 10.0.16299.0 defined the types we want in
dxexp.cpp, but the one in Windows SDK 10.0.15063.0 does not.
WDK_NTDDI_VERSION is set to NTDDI_WIN10_RS3 for the former, and
NTDDI_WIN10_RS2 for the later.
=> Fix Windows SDK check in dxexp.cpp

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/cf.return.storage-class.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
If we are returning some struct value not in the Function storage
class, we need to decompose it and write each component to the
corresponding component of a temporary variable adn then return
that temporary variable.
Also fixed a crash regarding implicitly generated constructors
and destructors for structs.
=> [spirv] Fix returning from non-Function storage class

docs/SPIR-V.rst, tools/clang/include/clang/SPIRV/Constant.h, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/Constant.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/constant.scalar.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.rcp.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Also includes creating 64-bit float constants that are needed for
reciprocating a 64-bit float.
=> [spirv] Add translation for intrinsic rcp.

lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilValidation.cpp, lib/HLSL/HLModule.cpp, lib/HLSL/HLOperationLower.cpp, tools/clang/lib/CodeGen/CGRecordLayoutBuilder.cpp, tools/clang/test/CodeGenHLSL/cbufferHalf.hlsl, tools/clang/test/CodeGenHLSL/struct_buf_new_layout.hlsl, tools/clang/test/CodeGenHLSL/typed_buffer_half.hlsl, tools/clang/unittests/HLSL/CMakeLists.txt, tools/clang/unittests/HLSL/CompilerTest.cpp
Structure buffer alignment change for float16. Starting in shader model 6.2, the structure will match that of #pragma pack(8) alignment in C++
- Removing padding for structure buffer. We will not have any padding in HLSL structure since load/store operation already handles offset as if padding exist in #pragma pack(8) mode in C++
- Disable legacy alignment for non precision mode as it was only needed for min precision
=> Structure alignment Change

docs/SPIR-V.rst, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/vk.binding.explicit.error.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.register.error.hlsl
Vulkan combined image sampler is logically considered a sampled
image and a sampler bound together.
=> [spirv] Allow the same binding number for combined image sampler

docs/SPIR-V.rst, tools/clang/include/clang/Basic/Attr.td, tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/include/clang/Sema/AttributeList.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenSPIRV/method.append-structured-buffer.append.hlsl, tools/clang/test/CodeGenSPIRV/method.consume-structured-buffer.consume.hlsl, tools/clang/test/CodeGenSPIRV/method.rw-structured-buffer.counter.hlsl, tools/clang/test/CodeGenSPIRV/vk.attribute.error.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.counter.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.explicit.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
A new attribute [[vk::counter_binding(X)]] can be used to specify
the binding number for associated counters for RW/append/consume
structured buffers.
Also added support for .IncrementCounter() and .DecrementCounter()
for RWStructuredBuffer.
Also fixed the type error of OpAtomicI{Add|Sub}.
=> [spirv] Add support for [[vk::counter_binding(X)]]

tools/clang/lib/SPIRV/SPIRVEmitter.cpp
https://github.com/KhronosGroup/SPIRV-Tools/pull/920 changed all static local non-POD info tables into static global POD ones. This picks up that change and should solve #725.
=> [spirv] Update dependencies and use two new opt passes

include/dxc/HLSL/DxilConstants.h, include/dxc/HLSL/HLModule.h, lib/HLSL/DxilValidation.cpp, lib/HLSL/HLModule.cpp, lib/HLSL/HLOperationLower.cpp, tools/clang/include/clang/Basic/TargetOptions.h, tools/clang/lib/Basic/Targets.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/cbufferHalf-struct.hlsl, tools/clang/test/CodeGenHLSL/cbufferHalf.hlsl, tools/clang/test/CodeGenHLSL/dataLayout.hlsl, tools/clang/test/CodeGenHLSL/dataLayoutHalf.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/ValidationTest.cpp
This change is to update correct target data layout for DXIL. Now that we have a scalar type of size less than dwords, we need to correctly print string data layout to determine non-packed structure layout.
This change also fixes alignments issues with ConstantBuffer as it was having different CG path from cbuffer.
=> DataLayout String and ConstantBuffer Offset Fix

lib/HLSL/DxilAddPixelHitInstrumentation.cpp, lib/HLSL/DxilModule.cpp, tools/clang/test/HLSL/pix/pixelCounterAddPixelCost.hlsl
Update pixel cost visualizer: this should be a byte offset, so multiply by sizeof(dword)
Set UAV to r/w (matching usage used by other PIX UAVs in other passes)
Replaced ReEmitDxilResources with clear-and-emit.
=> PIX pixel-cost visualizer: Fix byte offset, simplify ReEmitDxilResources

lib/HLSL/DxilDebugInstrumentation.cpp
The debug instrumentation doesn't cope well with pointers- they can't be described in the PIX UI properly. Consequently, I'm skipping these instructions and not instrumenting them at all. Subsequent dereferences of the pointers will be instrumented, and the retrieved values will show up in the UI just fine.
=> PIX: Skip getelementptr instructions

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/SimpleHs10.hlsl, tools/clang/test/CodeGenHLSL/SimpleHs11.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
This is a seemingly simple change, but David raised the possibility that there may be other backends relying on this early check. Let me know what you think, and please add other reviewers you find appropriate.
=> moves the patch constant fn validation to the backend.

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/spirv.interface.ds.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.hs.hlsl
Also make parameter names clear that they are for patch constant
function (PCF), not generally patch constant, which also involves
some domain shader inputs.
=> [spirv] Add check for Patch decoration in interface tests

docs/SPIR-V.rst, tools/clang/lib/SPIRV/GlPerVertex.cpp, tools/clang/lib/SPIRV/GlPerVertex.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/spirv.interface.ds.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.hs.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.ps.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.vs.hlsl
Declaring but not using (reading/writing) ClipDistance/CullDistance
does not require the ClipDistance/CullDistance capability.
=> [spirv] Require ClipDistance/CullDistance capability on use

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/var.init.cbuffer.hlsl, tools/clang/test/CodeGenSPIRV/var.init.tbuffer.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp, tools/clang/unittests/SPIRV/FileTestFixture.cpp, tools/clang/unittests/SPIRV/FileTestFixture.h
Also modified the testing infrastructure to support checking
warning messages.
=> [spirv] Emit warnings for cbuffer/tbuffer member initializers

lib/HLSL/DxilMetadataHelper.cpp
After dxil generation, there should be no empty struct used in instructions.
=> Don't emit type annotation for empty struct.

docs/SPIR-V.rst, tools/clang/include/clang/Basic/Attr.td, tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/include/clang/Sema/AttributeList.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenSPIRV/vk.attribute.error.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.push-constant.std430.hlsl, tools/clang/test/CodeGenSPIRV/vk.push-constant.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
[[vk::push_constant]] can be attached to a global variable of
struct type to put that variable in the PushConstant storage
class.
PushConstant should be of OpTypeStruct type with std430 layout.
=> [spirv] Add support for [[vk::push_constant]]

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/test/CodeGenSPIRV/vk.binding.cl.error.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.explicit.error.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.register.error.hlsl
This makes it easier for the devs to see with which a binding
numbers is conflicting.
=> [spirv] Emit note for the intial use location of bindings

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/vk.attribute.invalid.hlsl, tools/clang/test/CodeGenSPIRV/vk.push-constant.multiple.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Attaching vk::push_constant and vk::binding to the same global
variable is disallowed.
=> [spirv] Validate vk::push_constant usage

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/test/CodeGenSPIRV/vk.binding.cl.error.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.explicit.error.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.register.error.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
This is to enable certain workflows that reflection is used to
change the binding numbers after codegen.
=> [spirv] Emit warnings for the same binding number

docs/SPIR-V.rst, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.abort.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.get-render-target-sample-count.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.get-render-target-sample-position.hlsl, tools/clang/test/CodeGenSPIRV/texture.calculate-lod-unclamped.hlsl, tools/clang/test/CodeGenSPIRV/texture.gather-cmp-alpha.hlsl, tools/clang/test/CodeGenSPIRV/texture.gather-cmp-blue.hlsl, tools/clang/test/CodeGenSPIRV/texture.gather-cmp-green.hlsl, tools/clang/test/CodeGenSPIRV/texture.get-sample-position.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
* abort
* GetRenderTargetSampleCount
* GetRenderTargetSamplePosition
* GatherCmpGreen
* GatherCmpBlue
* GatherCmpAlpha
* GetSamplePosition
* CalculateLevelOfDetailUnclamped
=> [spirv] Emit unsupported error for some intrinsics

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SpirvEvalInfo.h
Cleaned up methods on SpirvEvalInfo. Also added a new field or
lvalue/rvalue, which will be used later.
=> [spirv] Turn SpirvEvalInfo into a class

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/test/CodeGenSPIRV/bezier.domain.hlsl2spv, tools/clang/test/CodeGenSPIRV/bezier.hull.hlsl2spv, tools/clang/test/CodeGenSPIRV/spirv.interface.ds.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.hs.hlsl
Uses location assignments in alphabetical order for HS outputs and DS
inputs. This will make the interface matching for these two stages
robust.
=> [spirv] Fix location mismatches between HS and DS

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/op.vector.swizzle.buffer-access.hlsl, tools/clang/test/CodeGenSPIRV/op.vector.swizzle.hlsl, tools/clang/test/CodeGenSPIRV/op.vector.swizzle.texture-access.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Previously we reply on Expr::isGLValue() to check whether an
expression is lvalue. That requires lots of ad-hoc fixes in
the CodeGen for missing/wrong lvalue/rvalue.
Now we use SpirvEvalInfo to calculate the lvalueness together
with the <result-id>. It is much cleaner.
Fixes https://github.com/Microsoft/DirectXShaderCompiler/issues/819
=> [spirv] Use SpirvEvalInfo to convey lvalue/rvalue

tools/clang/lib/SPIRV/InitListHandler.cpp, tools/clang/lib/SPIRV/InitListHandler.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/var.init.opaque.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Samplers, (RW)Buffers, and (RW)Textures are translated into SPIR-V
opaque types OpTypeSampler and OpTypeImage. Putting them in init
list will result in illegal SPIR-V. But we still allow it in the
CodeGen. Relying on SPIRV-Tools opt to correct them.
=> [spirv] Allow samplers and textures in initializer list

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/binary-op.assign.resource.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp, tools/clang/unittests/SPIRV/FileTestFixture.cpp, tools/clang/unittests/SPIRV/FileTestFixture.h
Right now we just do a load and then a store over of whole struct,
completely ignoring the storage class (and thus layout). This is
surely invalid SPIR-V, but we need this right now to enable some
workloads. Hopefully SPIRV-Tools will be able to remove these
loads/stores.
Updating associated counters for certain types is a TODO.
=> [spirv] Write values of resource types as a whole

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/GlPerVertex.cpp
cast<RecordType>(T.getTypePtr()) cannot handle cases in which
T is typedef of some struct type.
=> [spirv] Use .getAs<>() instead of cast<>() for RecordType

tools/clang/tools/dotnetc/EditorForm.Designer.cs, tools/clang/tools/dotnetc/EditorForm.cs, tools/clang/tools/dotnetc/EditorModels.cs, tools/clang/tools/dotnetc/HlslHost.cs, tools/clang/tools/dotnetc/OptEditorForm.Designer.cs, tools/clang/tools/dotnetc/OptEditorForm.cs, tools/clang/unittests/HLSL/ShaderOpTest.cpp, tools/clang/unittests/HLSL/ShaderOpTest.h
Adds a clipboard format to copy containers from optimizer and paste them encoded in shader ops and render them.
Adds a command to view the bitcode on the clipboard.
Adds a tab page for compilation options.
Relays out some of the UI on the main form to allow the render output pane to be visible again.
Some more text work missing, but this should help render output scenarios.
=> Container clipboard and XML serialization

docs/SPIR-V.rst, tools/clang/include/clang/Basic/Attr.td, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/GlPerVertex.cpp, tools/clang/lib/SPIRV/GlPerVertex.h, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenSPIRV/spirv.builtin.helper-invocation.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.ds.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.gs.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.hs.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.vs.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
[[vk::builtin("...")]] is introduced to support Vulkan-specific
builtins.
There are two supported in this commit:
* gl_PointSize
* gl_HelperInvocation
Validating the usages of these two builtins is left for anther
commit.
=> [spirv] Add mechanism for Vulkan-specific builtins

tools/clang/tools/dxcompiler/dxcfilesystem.cpp
I am hitting the max include file count limit on some workloads. I'm increasing the limit a bit to get unblocked. I have filed issue #866 to follow up with a data-structure and/or algo update to avoid having this limit.
=> Increased MaxIncludeFiles limit & filed issue #866

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/method.buffer.load.hlsl, tools/clang/test/CodeGenSPIRV/op.buffer.access.hlsl, tools/clang/test/CodeGenSPIRV/op.rwbuffer.access.hlsl, tools/clang/tools/dxc/dxc.cpp, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Refreshed SPIRV-Tools and re-enabled all validations for texure/
buffer methods.
Also added support for -Cc to color the disassembly.
=> [spirv] Add missing capability for storage image read/write

docs/SPIR-V.rst, include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/SPIRV/EmitSPIRVOptions.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/vk.cloption.ignore-unused-resources.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Added a new command line option -fvk-ignore-unused-resources
to avoid emitting SPIR-V code for resources defined but not statically
referenced by the call tree of the entry point in question.
=> [spirv] Add support for ignoring unused resources

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/spirv.legal.cbuffer.hlsl, tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.hlsl, tools/clang/test/CodeGenSPIRV/spirv.legal.tbuffer.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
ConstantBuffer/TextureBuffer are rerepresented the same as normal
structs upon which they are parameterized. So, using the normal
translation path via TypeTranslator, we have no way to tell whether
a struct is indeed just a normal struct or a Constant/Texture
buffer. Thus, we cannot apply the Block/BufferBlock decoration
appropriately. This causes type mismatch for OpLoad instructions.
=> [spirv] Fix type mismatch when loading Constant/Texture Buffer

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/method.append-structured-buffer.get-dimensions.hlsl, tools/clang/test/CodeGenSPIRV/method.byte-address-buffer.get-dimensions.hlsl, tools/clang/test/CodeGenSPIRV/method.consume-structured-buffer.get-dimensions.hlsl, tools/clang/test/CodeGenSPIRV/method.structured-buffer.get-dimensions.hlsl
OpArrayLength takes a pointer to an OpTypeStruct whose last member
is a run-time array, not a loaded struct value.
=> [spirv] Fix structured buffer .GetDimensions()

tools/clang/tools/libclang/dxcrewriteunused.cpp
Because hasBody will try to find body from all redeclations.
=> Use doesThisDeclarationHaveABody instead of hasBody when check function body

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h
ValueDecl is a subclass of NamedDecl and provides .getType().
=> [spirv] Use ValueDecl instead of NamedDecl

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/test/CodeGenSPIRV/method.rw-structured-buffer.counter.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.counter.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.explicit.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.implicit.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.register.hlsl
This will make handling RWStructuredBuffer aliasing legalization
easier later.
=> [spirv] Always emit a counter variable for RWStructuredBuffer

tools/clang/tools/dotnetc/DotNetDxc.cs
This makes it so the path with the DLL the user points to is also included in the search path.
=> Make dndxc dll search path more user friendly

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/op.vector.swizzle.const-scalar.hlsl
For vector casting that can be const-evaluated, we need to call
tryToEvaluateAsConst(). Previously we only handled the scalar
case.
=> [spirv] Fix vector casting that can be const-evaluated

docs/SPIR-V.rst, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/type.matrix.majorness.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
According to the SPIR-V Spec on decorations:
> RowMajor
> Applies only to a member of a structure type. 
>
> ColMajor
> Applies only to a member of a structure type. 
We currently do add these decorations for struct members. For now we will emit a warning if they are used on stand-alone matrices. We could consider fixing this via creating a struct with 1 matrix inside in the future.
=> [spirv] warn {row|col}_major on standalone matrix.

README.md
The r387 driver series is the first to support DXIL
in release mode on Win10 FCU and later.
=> Update NV section of README to reflect r387

tools/clang/test/CodeGenSPIRV/intrinsics.interlocked-methods.cs.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.interlocked-methods.ps.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Interlocked*() can only be performed on int or uint typed resources
and shared memory variables.
=> [spirv] Test atomic intrinsics on primitive types in CS

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/SpirvEvalInfo.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.methods.hlsl, tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.usage.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
This is to aid legalization passes to do their work.
For non-external variables of the following types
* (RW)StructuredBuffer
* (RW)ByteAddressBuffer
* AppendStructuredBuffer
* ConsumeStructuredBuffer
An extra level of pointer is applied. We use this extra level of
pointer to indicate that they are aliases. Loads and stores of
these alias variables will get the pointers of the aliased-to-
variables.
Associated counters is not handled in this commit.
=> [spirv] Emit alias structured/byte buffer as pointer to pointer

docs/SPIR-V.rst, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.packoffset.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
We do not support packoffset right now. Emit warning and ignore it.
=> [spirv] Emit warning for packoffset

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/bezier.hull.hlsl2spv, tools/clang/test/CodeGenSPIRV/binary-op.assign.composite.hlsl, tools/clang/test/CodeGenSPIRV/cs.groupshared.hlsl, tools/clang/test/CodeGenSPIRV/method.consume-structured-buffer.consume.hlsl, tools/clang/test/CodeGenSPIRV/method.structured-buffer.load.hlsl, tools/clang/test/CodeGenSPIRV/op.array.access.hlsl, tools/clang/test/CodeGenSPIRV/op.cbuffer.access.hlsl, tools/clang/test/CodeGenSPIRV/op.constant-buffer.access.hlsl, tools/clang/test/CodeGenSPIRV/op.rw-structured-buffer.access.hlsl, tools/clang/test/CodeGenSPIRV/op.structured-buffer.access.hlsl, tools/clang/test/CodeGenSPIRV/op.tbuffer.access.hlsl, tools/clang/test/CodeGenSPIRV/op.texture-buffer.access.hlsl, tools/clang/test/CodeGenSPIRV/var.init.array.hlsl, tools/clang/test/CodeGenSPIRV/vk.push-constant.hlsl
Try to figure out what is the intended usage for a literal type (e.g.
'literal int' or 'literal float').
Provide a hint to the TypeTranslator and translateAP{Int|Float} methods
so they better reflect the usage of literal types.
=> [spirv] Update the handling of literal types.

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/intrinsics.ldexp.hlsl
We cannot use GLSL extended instruction Ldexp for ldexp() since
they have different type requirements on the exponent parameter.
=> [spirv] Refresh dependencies and fix ldexp() translation

tools/clang/lib/SPIRV/SPIRVEmitter.cpp
Instead of checking whether the function signature contains
some opaque types, we check in storeValue(). Since all function
argument evaluation and value return calls storeValue().
=> [spirv] Adjust legalization detection checks

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/var.init.cross-storage-class.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
If the initializer is in a different storage class, we sometimes
need to decompose it and assign basic components recursively.
Fixes https://github.com/Microsoft/DirectXShaderCompiler/issues/968
=> [spirv] Fix static variable init from different storage class

docs/SPIR-V.rst, tools/clang/include/clang/SPIRV/Constant.h, tools/clang/include/clang/SPIRV/EmitSPIRVOptions.h, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/Constant.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/bezier.hull.hlsl2spv, tools/clang/test/CodeGenSPIRV/binary-op.assign.composite.hlsl, tools/clang/test/CodeGenSPIRV/constant.scalar.16bit.disabled.hlsl, tools/clang/test/CodeGenSPIRV/constant.scalar.16bit.enabled.hlsl, tools/clang/test/CodeGenSPIRV/constant.scalar.64bit.hlsl, tools/clang/test/CodeGenSPIRV/constant.scalar.hlsl, tools/clang/test/CodeGenSPIRV/cs.groupshared.hlsl, tools/clang/test/CodeGenSPIRV/op.array.access.hlsl, tools/clang/test/CodeGenSPIRV/op.cbuffer.access.hlsl, tools/clang/test/CodeGenSPIRV/op.constant-buffer.access.hlsl, tools/clang/test/CodeGenSPIRV/op.rw-structured-buffer.access.hlsl, tools/clang/test/CodeGenSPIRV/op.structured-buffer.access.hlsl, tools/clang/test/CodeGenSPIRV/op.tbuffer.access.hlsl, tools/clang/test/CodeGenSPIRV/op.texture-buffer.access.hlsl, tools/clang/test/CodeGenSPIRV/var.init.array.hlsl, tools/clang/test/CodeGenSPIRV/vk.push-constant.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
* Added Int64, Uint64, Int16, Uint16.
* Added 16-bit float constants.
* Get the -enable-16bit-types cmd option.
* Add tests for constant Int64/Uint64/Int16/etc.
=> [spirv] 16-bit and 64-bit int, uint, and float.

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/oo.method.on-static-var.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Static variables are in the Private storage class but all methods
are generated to take pointers of the Function storage class. So
to call a method on a static variable, we need first create a
temporary variable initialized with the contents of the static
variable. After the method call, we also need to write the contents
back to the static variable in case there are side effects.
=> [spirv] Use temporary variable for method call on static variable

docs/SPIR-V.rst, include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/SPIRV/EmitSPIRVOptions.h, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/GlPerVertex.cpp, tools/clang/lib/SPIRV/GlPerVertex.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/vk.cloption.invert-y.ds.hlsl, tools/clang/test/CodeGenSPIRV/vk.cloption.invert-y.gs.hlsl, tools/clang/test/CodeGenSPIRV/vk.cloption.invert-y.vs.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
This is to accommodate Vulkan's coordinate system, which is different
from DX's.
Fixes https://github.com/Microsoft/DirectXShaderCompiler/issues/959
=> [spirv] Add support for -fvk-invert-y

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.methods.hlsl, tools/clang/test/CodeGenSPIRV/spirv.legal.tbuffer.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp, tools/clang/unittests/SPIRV/FileTestFixture.cpp, tools/clang/unittests/SPIRV/FileTestFixture.h, tools/clang/unittests/SPIRV/FileTestUtils.cpp, tools/clang/unittests/SPIRV/FileTestUtils.h, tools/clang/unittests/SPIRV/WholeFileTestFixture.cpp
We still want to make sure that the generated raw SPIR-V does not
have other validation errors except for allocating variables
containing pointers and returning pointers.
=> [spirv] Legalization: validate with relaxed logical pointer

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.struct.hlsl
A temporary struct object containing alias fields are already
a rvalue. We should avoid loading it again in the CodeGen.
=> [spirv] Fix method call on temporary struct containing aliases

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/binary-op.assign.vector.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
For such vector swizzling, we cannot get the pointer and use OpStore
like normal vectors. Instead we should use OpImageWrite.
=> [spirv] Fix vector swizzling on RWBuffer/RWTexture elements

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/binary-op.assign.image.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
When using a storage image on the lhs of a compound assignment,
we need to load the image and do the calculation with rhs first
before actually assigning back to the storage image again. That
load won't result in an OpAccessChain, actually it will result
in a rvalue.
=> [spirv] Fix extra OpLoad when using images on lhs of assignment

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.usage.hlsl
We need to call loadIfAliasVar() to set the correct storage class
and layout rule for the pointer type.
=> [spirv] Legalization indexing StructuredBuffer containing array

tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/type.matrix.majorness.zpr.hlsl
Previously we will return defaultRowMajor as long as the type
is an array. That will hit an assertion failure in translateType()
for arrays of non-matrices.
Also refreshed SPIRV-Tools
=> [spirv] Fix array of non-matrix with -Zpr

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/ternary-op.cond-op.hlsl
HLSL ternary operator allows scalar, vector, and matrix arguments.
The SPIR-V CodeGen used to use OpSelect which only works on scalars and
vectors.
=> [spirv] Handle all types for ternary op

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/InitListHandler.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h
* Counter variable emission is merged into getTypeForPotentialAliasVar
* Changed to use DeclaratorDecl instead of ValueDecl for some methods
* collectArrayStructIndices is extended to suppor raw index
=> [spirv] Forbid using buffers as initializers and code refactoring

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/SpirvEvalInfo.h
* Loading the pointer from an alias variable turns the evaluation
info into lavalue again.
* loadIfGLValue() should suppress the immediate LValueToRValue
implicit cast.
=> [spirv] Fix lvalue/rvalue handling

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.counter.struct.hlsl, tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.struct.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
For structs containing RW/Append/Consume structured buffers, to
properly track aliasing and use the correct associated counter
for each buffer after legalization, we need to create temporary
counter variables for all struct fields that are RW/Append/Consume
structured buffers and assign them accordingly if the corresponding
buffer field is updated.
Because of structs, now we have four forms an alias RW/Append/
Consume structured buffer can be in:
* 1 (AssocCounter#1). A stand-alone variable,
* 2 (AssocCounter#2). A struct field,
* 3 (AssocCounter#3). A struct containing alias fields,
* 4 (AssocCounter#4). A nested struct containing alias fields.
For AssocBuffer#3 and AssocBuffer#4, it means we need to update all
fields' associated counters.
This commit only handles the first three forms.
=> [spirv] Legalization: associated counter in structs

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/cast.2literal-int.implicit.hlsl, tools/clang/test/CodeGenSPIRV/ternary-op.cond-op.hlsl
This change does type handling more properly and removes a hack
regarding binary ops. Also fixes the way ternary ops provide hints about
usage of literal types.
=> [spirv] Better handling of ternary and binary ops.

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.counter.method.hlsl, tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.struct.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
An implicit object is translated into the first argument to the
method call. If the implicit object is of struct type and its
fields have associated counters, we need to assign its associated
counters accordingly like other normal arguments.
For each such method, we generate associated counters for its
implicit object. At a call site, we assign the associated counters
from the real object to the ones associated with the method implict
object.
=> [spirv] Legalization: associated counters in implicit objects

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/test/CodeGenSPIRV/semantic.inside-tess-factor.ds.array1.hlsl, tools/clang/test/CodeGenSPIRV/semantic.inside-tess-factor.hs.array1.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Some developers use float[1] instead of float as the type for
SV_InsideTessFactor when input topology is "tri".
=> [spirv] Support float[1] as the type of SV_InsideTessFactor

tools/clang/include/clang/SPIRV/Constant.h, tools/clang/include/clang/SPIRV/Decoration.h, tools/clang/include/clang/SPIRV/InstBuilder.h, tools/clang/include/clang/SPIRV/Structure.h, tools/clang/include/clang/SPIRV/Type.h, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/InstBuilderAuto.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/SpirvEvalInfo.h, tools/clang/lib/SPIRV/Structure.cpp, tools/clang/unittests/SPIRV/ModuleBuilderTest.cpp, tools/clang/unittests/SPIRV/SPIRVTestUtils.h
This requires us to regenerate the InstBuilder class and also
manually pin the SPIR-V version as 1.0 instead of relying on
spv::Version.
Also refreshed SPIRV-Tools
=> [spirv] Use unfied1 grammars and headers in SPIRV-Headers

docs/SPIR-V.rst, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/texture.get-sample-position.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
This only supports .GetSamplePosition() for standard sample
positions, i.e., sample count is 1, 2, 4, 8, or 16. For other
cases, the method will just return float2(0, 0).
=> [spirv] Add support for .GetSamplePosition()

include/dxc/HlslIntrinsicOp.h, lib/HLSL/HLOperationLower.cpp, tools/clang/include/clang/Basic/Attr.td, tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/include/clang/Sema/AttributeList.h, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/lib/Sema/gen_intrin_main_tables_15.h, utils/hct/gen_intrin_main.txt, utils/hct/hctdb.py, utils/hct/hctdb_instrhelp.py
Two new Vulkan specific intrinsic resource types, `SubpassInput` and
`SubpassInputMS`, are introduced to provide a way to use subpass inputs
in Vulkan. Their signatures:
```c++
template<typename T>
class SubpassInput {
T SubpassLoad();
};
template<typename T>
class SubpassInputMS {
T SubpassLoad(int sample);
};
```
`T` can be a scalar or vector type.
If compiled without `ENABLE_SPIRV_CODEGEN`, the compiler will report
unknown type name for `SubpassInput(MS)`. If compiled with SPIR-V
CodeGen and trying to use `SubpassInput(MS)` in DXIL CodeGen, the
compiler will report an error saying the type is Vulkan-specific.
A new Vulkan-specific attribute, `vk::input_attachment_index` is
introduced to provide a way to set the input attachment index for
`SubpassInput(MS)` objects.
=> [spirv] Add SubpassInput(MS) and vk::input_attachment_index

tools/clang/include/clang/SPIRV/Constant.h, tools/clang/include/clang/SPIRV/Structure.h, tools/clang/lib/SPIRV/Constant.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/unittests/SPIRV/ConstantTest.cpp
Specialization constants are more like variables. Unlike normal
constants, we cannot unify spec constants, even if two of them
have exactly the same arguments. Neither can we replace a spec
constant with its default value (initializer) or folding exprs
containing spec constants.
We can use the SpecId decoration to distinguish spec constants
with the same arguments, but the problem is that not all spec
constants have SpecId decorations. Only those explicitly marked
in the source code have, derived ones do not.
Also, we cannot decorate normal constants. So we can remove the
decoration member in the Constant class.
=> [spirv] Remove spec constants from Constant class

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/cbuffer_fn.hlsl, tools/clang/test/CodeGenHLSL/cbuffer_fn_copy.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
Functions within cbuffers declarations are effectively global functions.
Includes a test case for copying cbuffers that have nested functions.
=> Fixes #679 - missing scenario with *it is of type FunctionDecl

tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
Code had a (reasonable) assumption that sources have names, but the
entry point wasn't verifying that. For compat with prior compilers and
the annotation, we choose to support it. Unlikely other implementations,
the name is a simple hard-coded one, instead of varying, to allow for
easier deduping when the output is checked (name is in debug section).
=> Fixes #823 - Compile crashes if pSourceName if nullptr/empty

docs/SPIR-V.rst, tools/clang/include/clang/Basic/Attr.td, tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/include/clang/SPIRV/InstBuilder.h, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/include/clang/Sema/AttributeList.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/InstBuilderManual.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/SpirvEvalInfo.h, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenSPIRV/vk.spec-constant.error.hlsl, tools/clang/test/CodeGenSPIRV/vk.spec-constant.init.hlsl, tools/clang/test/CodeGenSPIRV/vk.spec-constant.usage.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
This commit add support for generating OpSpecConstant* instructions
with SpecId decorations. Spec constants are only allowed to be of
scalar boolean/integer/float types. Using spec constant as the array
size does not work at the moment.
=> [spirv] Add initial support for specialization constant

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/op.vector.swizzle.const-scalar.hlsl
isVectorType() only returns true for real vectors with more than
one element.
=> [spirv] Handle vector<literal int/float, 1> in type hints

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/cast.flat-conversion.struct.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
For a struct `T` with only one member of type `S`, `(T)<an-instance-of-S>`
is allowed and will be interpreted as constructing an instance of
`T` using the instance of `S` as its member.
=> [spirv] FloatConversion for structs with one single member

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/op.vector.swizzle.size1.hlsl
Some times we won't have proper LValueToRValue implicit cast for
binary operator operands; HLSLVectorElementExpr is one example.
=> [spirv] OpLoad for lvalue operands of binary operators

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/ternary-op.cond-op.hlsl
The AST won't have LValueToRValue implicit casts for all three
operands for such cases.
=> [spirv] Handle selecting resources using conditional operator

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.zpc.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.zpr.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
cbuffers/tbuffers are handled differently than other resource types
becuase their members do not need to be qualified when using.
That is, their members are distinct entities. However, in SPIR-V,
we need to generate one single entity to hold them all for all
members in a cbuffer/tbuffer.
Previously we didn't record the marjorness annotated on each member,
which results in returning the wrong types for members.
=> [spirv] Fix neglecting majorness on cbuffer/tbuffer members

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/cast.flat-conversion.no-op.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
For array wholesale assignments, the rhs will be wrapped in a
FlatConversion implicit cast. This cast can be ignored since it
does not affect CodeGen.
=> [spirv] Support assigning arrays as a whole

tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/spirv.interpolation.hlsl
We need to check the element types of PS input variables to
properly apply interpolation decorations. Previously the method
used to query element type does not support array types, which
caused an assertion eventually.
=> [spirv] Accept array types for PS stage input variables

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSL/derived-to-base.hlsl, tools/clang/unittests/HLSL/VerifierTest.cpp
This will enable us to trace back the whole base chain.
=> Carry BasePath within CK_HLSLDerivedToBase casts

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/var.static.resource.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
For static resources not explicitly initialized, we cannot initialize
them since there are no meaningful zero values. Just do nothing.
Fixes https://github.com/Microsoft/DirectXShaderCompiler/issues/1055
=> [spirv] Avoid getting constant zero for static resources

tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/ShaderOpArithTable.xml, tools/dxexp/dxexp.cpp, utils/hct/hctdb_test.py
Fixing device support for > SM 6.0 and updating dxexp
Also fixing the following tests:
ExecutionTest::DenormBinaryFloatOpTest#FDivDenormFTZ
ExecutionTest::DenormBinaryFloatOpTest#FAddDenormAny
ExecutionTest::DenormBinaryFloatOpTest#FMulDenormAny
ExecutionTest::DenormBinaryFloatOpTest#FDivDenormAny
ExecutionTest::DenormBinaryFloatOpTest#FMulDenormFTZ
ExecutionTest::DenormBinaryFloatOpTest#FAddDenormFTZ
ExecutionTest::DenormBinaryFloatOpTest#FSubDenormFTZ
ExecutionTest::DenormBinaryFloatOpTest#FSubDenormAny
ExecutionTest::DenormTertiaryFloatOpTest#FMadDenormAny
ExecutionTest::DenormTertiaryFloatOpTest#FMadDenormFTZ
=> Fix denorm tests and sm support

include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/Lex/PreprocessorOptions.h, tools/clang/lib/Lex/TokenLexer.cpp, tools/clang/tools/dxc/dxc.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
The fxc compiler evaluates both operands before performing the
token-pasting operation. But the default Clang way is to follow
C standard, which token-pastes operands as-is, without any
pre-expanding.
This PR adds support for the fxc behavior via the command
line option: `-fexpand-token-pasting-operand`.
Fixes #1005
=>  Add an option to allow pre-expand token-pasting (##) operands

tools/clang/lib/SPIRV/SPIRVEmitter.cpp
Some method calls are wrapped in assert(), which gets removed
in Release build and results in some local variables not updated.
=> [spirv] Fix crashes in atrix casting for Release build

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/test/CodeGenSPIRV/cast.flat-conversion.no-op.hlsl, tools/clang/test/CodeGenSPIRV/fn.ctbuffer.hlsl, tools/clang/test/CodeGenSPIRV/op.cbuffer.access.hlsl, tools/clang/test/CodeGenSPIRV/op.tbuffer.access.hlsl, tools/clang/test/CodeGenSPIRV/type.cbuffer.hlsl, tools/clang/test/CodeGenSPIRV/type.tbuffer.hlsl, tools/clang/test/CodeGenSPIRV/var.init.cross-storage-class.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.explicit.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.implicit.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.register.hlsl, tools/clang/test/CodeGenSPIRV/vk.cloption.ignore-unused-resources.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.zpc.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.zpr.hlsl
This will help reflection libraries to do their work.
=> [spirv] Remove the "var." prefix on cbuffer/tbuffer names

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/quick-test/immSel.hlsl
Choose i32 as result type for case like 
float4 P;
((P.x < -P.w) ? 3 : 9) | ((P.y < -P.z) ? 5 : 3);
=> Choose i32 as result type for select used by binary operator.

tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/vk.layout.64bit-types.std140.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.64bit-types.std430.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Fixes https://github.com/Microsoft/DirectXShaderCompiler/issues/1094
=> [spirv] Support 64bit types during resource calculation

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/test/CodeGenSPIRV/cs.groupshared.hlsl
Also fix missing row-major-ness for external matrices that need
struct wrapping.
=> [spirv] Do not assign descriptors to Workgroup variables

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/bezier.domain.hlsl2spv, tools/clang/test/CodeGenSPIRV/bezier.hull.hlsl2spv, tools/clang/test/CodeGenSPIRV/spirv.interface.hs.hlsl, tools/clang/test/CodeGenSPIRV/vk.location.composite.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Scalars and vectors typically takes only one location. But matrices
and other composite types takes multiple sequential locations.
=> [spirv] Fix location assignment for composite stage IO types

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/binary-op.arith-assign.mixed.form.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.arith-assign.mixed.type.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Compound assignments don't have the proper AST nodes to implicitly
casting LHS and RHS to the same type. But it has an API called
getComputationLHSType() to tell us what the LHS are expected to
convert to when doing the computation. We need to take into
consideration of that information when CodeGen'ing compound
assignments.
=> [spirv] Fix type mismatch for compound assignment

utils/hct/hctgettaef.py
Default TLS1.0 now fails to retrieve files with Github's new change:
https://developer.github.com/changes/2018-02-01-weak-crypto-removal-notice/
=> Modified hctgettaef.py to use tls1.2 when requesting files files github.

docs/SPIR-V.rst, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/test/CodeGenSPIRV/constant.scalar.16bit.enabled.hlsl
Capability Float16 is not allowed by Vulkan 1.0 specification.
SPV_AMD_gpu_shader_half_float should be used if 16bit floats are used.
=> [spirv] Don't emit Float16 capability.

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SpirvEvalInfo.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/op.cbuffer.access.majorness.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Moved majorness info into SpirvEvalInfo so that we can translate
type correctly based on it. This affects accessing matrices inside
cbuffer; otherwise, we will have wrong type for the matrix field
loaded out of a cbuffer.
=> [spirv] Consider majorness when accessing matrix in cbuffer

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/cast.flat-conversion.literal-initializer.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Handle FlatConversion for cases such as:
```
S myS = (S)(1.0/0.0);
```
These cases result in an initializer of type 'literal float', even
though the initializer is *not* a FloatingLiteral!
=> [spirv] Non-literal 'literal float' as initializer

docs/SPIR-V.rst, include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/SPIRV/EmitSPIRVOptions.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/method.append-structured-buffer.get-dimensions.hlsl, tools/clang/test/CodeGenSPIRV/method.consume-structured-buffer.get-dimensions.hlsl, tools/clang/test/CodeGenSPIRV/method.structured-buffer.get-dimensions.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.std140.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.push-constant.std430.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.sbuffer.std430.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.vector.relaxed.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Based on GLSL std140/std430 layout rules, relaxed layout allows
using vector's element type's alignment as the vector types's
alignment, so that we can pack a float value and a float3 value
tightly. This is the default right now.
Also add an option, `-fvk-use-glsl-layout`, to turn off the relaxed
layout for vectors and use conventional GLSL std140/std430 layout
rules.
=> [spirv] Implement relaxed layout for vector types

tools/clang/lib/CodeGen/CGHLSLMS.cpp
SimplifyBitCast could dropAllReferences() on a future instruction, such as a store.  Iteration in SimpleTransformForHLDXIR would later inspect that instruction, dereferencing its operands, which are NULL, causing AV.  This fixes it by skipping instructions that have already been added to deadInst list.
=> Skip deadInsts in SimpleTransformForHLDXIR to prevent AV

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/quick-test/anon_struct.hlsl
Anonymous structures were not added to $Globals because they are
not externally visible.
=>   Fix anonymous struct cbuffer

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SpirvEvalInfo.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/op.cbuffer.access.majorness.hlsl
Previously we use an additional parameter to translateType()
to convey the matrix majorness info. It causes lots of type
inconsistency issue.
Now the majorness info is queried directly from the QualType.
This should be more robust.
=> [spirv] Revamp matrix majorness handling

lib/Transforms/Scalar/HoistConstantArray.cpp, tools/clang/test/HLSL/hca/15.ll, tools/clang/unittests/HLSL/CompilerTest.cpp
Fix HoistConstantArray pass to recognize more complex load & store patterns.
Previously it was expecting no nesting and just a simple list of GetElementPtr's that fed loads or stores.  Now it can accept a tree (DAG) of GetElementPtrs that feed leaf node loads or stores.
These patterns cannot be directly derived from HLSL, however they can occur due to previous optimizations that transform the array accesses (like a partial CSE or similar).
=> Handle more complex addressing modes

docs/SPIR-V.rst, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/binary-op.bitwise-assign.scalar.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.bitwise-assign.shift-left.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.bitwise-assign.shift-right.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.bitwise-assign.vector.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.bitwise.scalar.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.bitwise.shift-left.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.bitwise.shift-right.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.bitwise.vector.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
In SPIR-V, if shifting a value by an amount that is greater than
the value's bitwidth, the result is undefined.
FXC and DXC/DXIL performs a bitwise and over the RHS of the shift
operation to only consider its (n - 1) least significant bits,
where n is the bitwidth of LHS.
=> [spirv] Cull RHS of shift operations

lib/HLSL/DxilGenerationPass.cpp, tools/clang/test/CodeGenHLSL/attributeAtVertexNoOpt.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
This change is to fix LoadInput check for GetAttributeAtVertex call with no optimization. Currently it was emitting wrong error message with no codegen.
=> Fix checking LoadInput for GetAttributeAtVertex for no Opt

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/binary-op.assign.composite.hlsl, tools/clang/test/CodeGenSPIRV/cast.flat-conversion.no-op.hlsl, tools/clang/test/CodeGenSPIRV/cf.return.storage-class.hlsl, tools/clang/test/CodeGenSPIRV/fn.ctbuffer.hlsl, tools/clang/test/CodeGenSPIRV/method.append-structured-buffer.append.hlsl, tools/clang/test/CodeGenSPIRV/method.consume-structured-buffer.consume.hlsl, tools/clang/test/CodeGenSPIRV/spirv.legal.cbuffer.hlsl, tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.counter.hlsl, tools/clang/test/CodeGenSPIRV/spirv.legal.tbuffer.hlsl, tools/clang/test/CodeGenSPIRV/var.init.cross-storage-class.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.zpc.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.zpr.hlsl
Previously we emit a store for each sub-element, which is not
friendly to SPIR-V transformations. This commit converted that
into first constructing a temporary value of the target storage
class, and the store once.
=> [spirv] Emit single store for cross-storage-class composite types

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/quick-test/vector-matrix-binops.hlsl
The compiler was crashing on binary operations used on vectors and
matrices of varying sizes. This fix aligns the matrix/vector conversion
behavior and allowed combinations with FXC.
Vector initialization from matrices of equivalent dimensions now works
as well.
Fixes: #1090, #1157
=> Matrix and vector binary operations and conversions fix

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/quick-test/vector-matrix-binops.hlsl, tools/clang/test/HLSL/implicit-casts.hlsl, tools/clang/test/HLSL/uint4_add3.hlsl, tools/clang/test/HLSL/vector-conditional.hlsl
There was no warning when the truncation happened
due to a binary operation.
Fixes #1159
=> Add 'implicit truncation of vector type' warning

tools/clang/unittests/HLSL/ShaderOpTest.cpp, tools/clang/unittests/HLSL/ShaderOpTest.h
Longform explanation:
Views/descriptors over resources may specify some non-default properties.
The prior implementation was trying to check values and infer whether
they had been set or were forcibly needed. For starters, this wasn't
always properly initialized, so results were not consistent. Guessing
at this point is a bad idea in any case, so the new implementation
keeps track of whether anything was in fact specified (and if so, values
should have been initialized by the reader, although that is still WIP
for some cases).
=> Fixes failures in two execution tests that used SRVs

tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/include/clang/Basic/LangOptions.h, tools/clang/lib/AST/ASTDumper.cpp, tools/clang/lib/Parse/ParseDecl.cpp, tools/clang/lib/Sema/SemaDecl.cpp, tools/clang/test/CodeGenHLSL/quick-test/void-param.hlsl, tools/clang/test/HLSL/cpp-errors.hlsl
We should support void in an empty parameter list. There are shaders that use this syntax and the old compiler supports it as well.
Fixes #1064
=> Allow void in function parameter list

tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/cbuffer-struct.hlsl, tools/clang/test/CodeGenHLSL/cbuffer-structarray.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
fxc errors out if the template argument for ConstantBuffer or
TextureBuffer is not a struct type with "D3D12 constant/texture
buffer template element can only be a struct". This commit
enforces that behavior on dxc.
=> Require ConstantBuffer/TextureBuffer arguments to be structs

lib/HLSL/HLMatrixLowerPass.cpp
Building without asserts enabled fails the build due to unused variable warning.
=> Silence unusued variable warning when building without asserts

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/var.globals.hlsl, tools/clang/test/CodeGenSPIRV/var.resource.array.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
An array of resources will be translated into an SPIR-V array
behind one single descriptor.
=> [spirv] Add support for arrays of resources

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/binary-op.assign.opaque.array.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Copy opaque arrays (arrays of SPIR-V images and samplers) by
copying each element separately via access chains. This is to
aid SPIR-V transformations to avoid loading an array of opaque
objects as a whole.
=> [spirv] Do per-element copying for opaque arrays

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/texture.sample.sample-cmp.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Drivers are expecting to see the Dpeth hint to be 1 in OpTypeImage
for OpImageSample*Dref* instructions. Hack to get the OpTypeImage
have the expected hint for OpSampledImage.
=> [spirv] Fix OpSampledImage for depth-comparison sampling

docs/SPIR-V.rst, include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/SPIRV/EmitSPIRVOptions.h, tools/clang/lib/SPIRV/EmitSPIRVOptions.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/method.append-structured-buffer.get-dimensions.hlsl, tools/clang/test/CodeGenSPIRV/method.consume-structured-buffer.get-dimensions.hlsl, tools/clang/test/CodeGenSPIRV/method.structured-buffer.get-dimensions.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.std140.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.push-constant.std430.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.sbuffer.std430.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp
GLSL as a shading language does not define the layout rules for
std140/std430; the OpenGL graphics environment defines that.
This is also more consistent with -fvk-use-dx-layout.
=> [spirv] Rename -fvk-use-glsl-layout to -fvk-use-gl-layout

tools/clang/unittests/SPIRV/FileTestUtils.cpp, tools/clang/unittests/SPIRV/TestMain.cpp
* Stop outputting warning/error messages in tests
They were useful initially; but as we become more and more
mature and having more and more tests, they are just flooding
the output.
* Stop outputting info for successful tests
=> [spirv] Reduce messages printed when testing

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/type.struct.hlsl, tools/clang/test/CodeGenSPIRV/vk.push-constant.anon-struct.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
When skipping decls not externally visible, we should make sure
that they are in the translation unit or a namespace, which means
they are for $Globals cbuffer. For other cases, we should not
skip them.
Fixes https://github.com/Microsoft/DirectXShaderCompiler/issues/1221
=> [spirv] Fix push constant defined from anonymous struct

tools/clang/include/clang/SPIRV/FeatureManager.h, tools/clang/lib/SPIRV/FeatureManager.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/test/CodeGenSPIRV/spirv.interface.ds.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.gs.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.hs.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.ps.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.vs.hlsl
Its functionality is subsumed by SPV_GOOGLE_hlsl_functionality1.
See https://github.com/KhronosGroup/SPIRV-Registry/pull/4
=> [spirv] Stop emitting SPV_GOOGLE_decorate_string

lib/HLSL/HLOperationLower.cpp, lib/HLSL/HLSignatureLower.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/quick-test/static_global_copy.hlsl, tools/clang/test/CodeGenHLSL/quick-test/static_global_copy2.hlsl, tools/clang/test/CodeGenHLSL/quick-test/static_global_copy3.hlsl
1. MergeGepUse for cbuffer and temp gep created when flatten.
2. When flatten alloca, always keep order by size of type.
So we can make sure big alloca flattened first, then small alloca can easier remove memcpy.
3. For global variable which has zero init value, ignore it if the initializer not used.
4. In ResourceToHandle::ReplaceResourceWithHandle only assert when has user.
5. MergeGepUse for input output in collectInputOutputAccessInfo.
=> Better memcpy propagation.

include/dxc/HLSL/DxilPipelineStateValidation.h
The value obtained by calling table.Get was not actually returned.
=> Fix PSVSemanticIndexes::Get function return value.

docs/SPIR-V.rst, tools/clang/include/clang/Basic/Attr.td, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenSPIRV/semantic.target.dual-blend.error1.hlsl, tools/clang/test/CodeGenSPIRV/semantic.target.dual-blend.error2.hlsl, tools/clang/test/CodeGenSPIRV/semantic.target.dual-blend.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
In HLSL, dual-source color blending is enabled only via API;
the shader needs no special marks: it only writes SV_Target0
& SV_Target1 like normal.
But in Vulkan, to enable dual-source blending, the shader need
to mark the two participating output variables with Index = 0
and Index = 1, respectively.
So we introduce a new attribute, vk::index(), to let developers
to specify the index of an output variable so dual-source
blending can be enabled.
See Vulkan spec "26.1.2. Dual-Source Blending".
=> [spirv] Add support for dual-source blending

tools/clang/include/clang/SPIRV/Decoration.h, tools/clang/include/clang/SPIRV/FeatureManager.h, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/Decoration.cpp, tools/clang/lib/SPIRV/FeatureManager.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/SpirvEvalInfo.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.non-uniform-resource-index.hlsl, tools/clang/test/CodeGenSPIRV/type.runtime-array.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
This intrinsic function is translated using the SPIR-V extension
SPV_EXT_descriptor_indexing.
Also added support for unbounded resource arrays.
They are translated into runtime arrays of resources with the
RuntimeDescriptorArrayEXT capability from the SPIR-V extension
SPV_EXT_descriptor_indexing.
=> [spirv] Add support for NonUniformResourceIndex()

include/dxc/Support/FileIOHelper.h, include/dxc/Support/microcom.h
CDxcTMHeapPtr templated with 2 classes does not exist.
A code block has also been moved so that the caller function knows about
the existence of the callee function. Previous code order is not allowed
by some compilers.
=> Minor fixes that will make compilers happier.

tools/clang/include/clang/SPIRV/Type.h, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVContext.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h
* Using 'auto' as return type is supported starting c++14.
* The ternary operator cannot deduce whether it should evaluate each
side as uint or SpirvEvalInfo (ambiguous expression error).
* Remove extra 'SPIRVEmitter::' in header file.
=> [spirv] Compile improvements.

lib/Bitcode/Reader/BitcodeReader.cpp, lib/DxcSupport/FileIOHelper.cpp, lib/DxcSupport/dxcmem.cpp, lib/MSSupport/MSFileSystemImpl.cpp, tools/clang/lib/Frontend/CompilerInstance.cpp, tools/clang/tools/dxcompiler/dxcfilesystem.cpp, tools/clang/tools/libclang/dxcisenseimpl.h
Some compilers require function prototypes and bodies to match with
throw() attributes. This corrects them.
Additionally, it replaces thrown std::exceptions with a string
parameter with runtime_errors, which can take a string on any
system.
Finally, as an incidental change, I moved GetPosition in 
FileIOHelper.cpp to its proper place with the rest of the 
AbstractMemoryStream implementation instead of grouping it 
with the IDxcBlob implementation
Nonfunctional change. 
Just inching toward cross platform compatibility
=> Match throws and use standard string exception

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/fn.param.inout.storage-class.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
AST will use reference types for function parameters that are
marked as out or inout.
=> [spirv] Support storing to values of reference types

include/dxc/HLSL/DxilSigPoint.inl
The DxilSigPoint.inl file depends on an esoteric distinction in how
different preprocessors expand macros included as parameters to
other macros.
When a macro receives another macro as its argument, different
preprocessors expand these parameter macros at different times. MSVC
defers expanding the macro until the macros taking parameters
have been completely expanded. GCC and others expand the parameter
macro just as soon as it can.
At issue is the expansion of the three _## macros: _41, _50, and
_61 which expand to ,#,# respectively. These macros can be passed
into an initial macro that plugs them directly into a function that
takes multiple parameters without issue with any preprocessor.
Regardless of when the _## macro is expanded, it will be interpretted
correctly as passing multiple …
=> Correct preprocessor dependent expansion

tools/clang/lib/Lex/HeaderSearch.cpp
This turns off warnings on non-portable MSVC include search
rules completely.
If we are trying to migrate to the C++ default behavior for
include file resolution for the long run, then maybe it makes
more sense to still have this warning and use a command-line
option to get the old behavior like what we've done for
macro expansion.
Let me know if you prefer the later. I'd happy to change.
=> Turn off warnings on MSVC include search rules

include/dxc/dxcapi.internal.h, tools/clang/lib/Sema/SemaHLSL.cpp
Replaces -i64 suffixes with -LL which are said to be equivalent by
MSDN. Both should result in 64 bit behavior.
Additionally, I dropped a superfluous repetition of the class name
on the inlined CheckVectorConditional method of HLSLExternalSource. 
By all rights, it should be its own change, but it gets lonely so it came
along for the ride. The repeated class name made some compilers
unhappy and losing it doesn't bother anyone.
=> [linux-port] Use standard int literal suffixes

include/dxc/HLSL/DxilSpanAllocator.h
MSVC is very forgiving of crimes committed in templated functions
and methods of templated classes that never actually get instantiated.
Consequently, the fact that the public variant of Find in SpanAllocator
referenced an unknown variable, seemingly as a copy paste error
was left unnoticed. Other compilers are not so magnanimous.
The call to the private version of Find() takes an iterator as a starting
location to search for a place to put a span of the given size. The
public Find() searches through the known spans to find the one just
past the range requested by the current pos and size. If it reaches
the end, then the span can be placed at the end safely. If it
fits before some other span, overlap needs to be checked. If the
new span would overlap its neighbor, another location is …
=> Unknown variable in SpanAllocator::Find

lib/Transforms/IPO/Inliner.cpp, lib/Transforms/Scalar/LoopUnrollPass.cpp
A few ternary operators took different types in the second and
third position, which some compilers refuse to resolve. By casting
the third operand to the type of the assigned variable and make
it match the second operand.
=> [linux-port] Resolve ternary type ambiguities

lib/HLSL/DxilModule.cpp, lib/HLSL/DxilValidation.cpp
Templated iterators often have a dependent scope, which annoys
some compilers because they can't tell if the typename evaluates
to a type or a variable name. This adds typename keywords to
remove the ambiguity in removeResources.
Additionally, the std toupper function can't be found for the sake
of the templated call to std::transform in ValidateSignature
function. By adding :: to clarify it, the template can be evaluated.
=> [linux-port] Fix template ambiguities

lib/HLSL/DxilAddPixelHitInstrumentation.cpp, lib/HLSL/DxilDebugInstrumentation.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilLinker.cpp, lib/HLSL/DxilModule.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/Frontend/FrontendActions.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/tools/libclang/dxcrewriteunused.cpp
Use llvm::make_unique instead of std::make_unique. Same functionality, fixes some
compiler errors on Linux, and makes the code more consistent with the
rest of the code base.
=> use llvm::make_unique

lib/HLSL/DxilContainerAssembler.cpp
Fixes compiler error on Linux. pHashStream is of CComPtr\<AbstractMemoryStream\> type.
=> Fix type ambiguity for ternary operator.

include/dxc/HLSL/DxilPipelineStateValidation.h
Fix Linux compile error:
types cannot be declared in an anonymous union.
=> Avoid defining types in anonymous union.

tools/clang/unittests/SPIRV/FileTestUtils.cpp
=> [spirv] File names are case sensitive.

external/GTestConfig.cmake, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/test/CodeGenSPIRV/texture.array.gather-blue.hlsl, tools/clang/test/CodeGenSPIRV/texture.gather-alpha.hlsl, tools/clang/test/CodeGenSPIRV/texture.gather-green.hlsl, tools/clang/unittests/SPIRV/CMakeLists.txt
* ConstOffsets now requires ImageGatherExtended capability
* This reverts commit ea1bf8d24ceb05883b6e24517f6cbbb117d4a385.
=> [spirv] Update external dependencies

include/dxc/HLSL/DxilMetadataHelper.h, lib/DxcSupport/HLSLOptions.cpp, lib/HLSL/DxilMetadataHelper.cpp, lib/HLSL/DxilModule.cpp, tools/clang/lib/CodeGen/ModuleBuilder.cpp, tools/clang/test/CodeGenHLSL/share_mem_dbg.hlsl, tools/clang/tools/dxcompiler/dxcdia.cpp, tools/clang/tools/dxcompiler/dxcdisassembler.cpp
1. Change llvm.dbg.contents into dx.source.contents.
2. Fix crash when SemanticIndexVec is empty.
3. Fix case Utf8StringVector is reallocated in MainArgs::operator=(const MainArgs &other).
=> Change llvm.dbg.contents into dx.source.contents.

lib/HLSL/DxilValidation.cpp
Using an enum class as the key of an unordered_set is supported starting
C++14.
The two possible solutions are: a) provide a hash function b) cast to
unsigned. Given the usage here, it latter is a simpler fix.
=> [linux-port] Avoid using enum class as set key

tools/clang/include/clang/SPIRV/FeatureManager.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/FeatureManager.cpp, tools/clang/test/CodeGenSPIRV/semantic.render-target-array-index.ds.hlsl, tools/clang/test/CodeGenSPIRV/semantic.render-target-array-index.vs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.viewport-array-index.ds.hlsl, tools/clang/test/CodeGenSPIRV/semantic.viewport-array-index.vs.hlsl
Using SV_RenderTargetArrayIndex (translated into Layer builtin)
and SV_ViewportArrayIndex (translated into ViewportIndex builtin)
in VS and DS output requires the SPV_EXT_shader_viewport_index_layer
extension.
=> [spirv] Support ViewportIndex & Layer in VS and DS

CMakeLists.txt, tools/clang/unittests/HLSL/CompilerTest.cpp
Suddenly the `CompileWhenNoMemThenOOM` test started to fail
even for a pull request that is trivial and does not touch the source
code (e.g., #1294). And we cannot reproduce this failure locally.
It's likely an Appveyor infrastructure issue; they updated a few things
[yesterday](https://www.appveyor.com/updates/2018/05/16/).
I temporary disabled this test on Appveyor CI for now to unblock
other work. A following up PR to try to revert this PR and fix the issue.
=> [appveyor] Disable CompileWhenNoMemThenOOM

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp
The spec does not define the order in which function parameters are evaluated. In order to make the results consistent on different platforms, we should avoid invoking multiple functions as function parameters.
=> [spirv] Function parameter evaluation order

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/fn.param.inout.hlsl, tools/clang/test/CodeGenSPIRV/fn.param.inout.no-copy.hlsl, tools/clang/test/CodeGenSPIRV/fn.param.inout.vector.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
When calling functions with arguments that references local
variables as a whole and annotated with out/inout, we don't
need to create temporary variables for them again. Just pass
the pointers to the original local variables.
=> [spirv] Avoid creating temporary variables for local variables

CMakeLists.txt
`if ( $ENV{CI} AND $ENV{APPVEYOR} )`
would evaluate to
`if (true AND )`
for non-appveyor environments, and cmake would error out because there is no argument to the right of AND. This will fix that.
=> Fix cmake for non-appveyor buildbot environments.

include/dxc/HLSL/DxilConstants.h, tools/clang/include/clang/AST/HlslTypes.h, tools/clang/include/clang/AST/Type.h, tools/clang/lib/CodeGen/CGHLSLMS.cpp
Just a few warning conditions in a handful of common headers
was producing pages and pages of warning messages. By fixing them,
the output spew is reduced significantly.
Static variables in a header produce a separate variable for every
file that includes it. In many of these, these variables were unused.
Instead, variables used in multiple files should be defined only
once in a source file and declared as extern in the header.
Many unsigned variables were checked to be greater than zero and less
than 3 in HlslTypes.h. If they were somehow assigned a negative
value, it would appear as much greater than 3 in unsigned form.
So we can just check that they are less than or equal to 3.
In Type.h, parammods_begin() was casting its return value to the
proper pointer, but without const, producing …
=> [linux-port] Fix a handful of warnings in headers

include/dxc/HLSL/DxilOperations.h, lib/HLSL/DxilDebugInstrumentation.cpp, lib/HLSL/DxilOperations.cpp, lib/HLSL/DxilShaderModel.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
GCC5 has a few limitations that later versions do not. The
most pervasive issue is the confusion of scoped operators on enum
names when the name of the enum is shared with a local variable.
The only other issue concerns intialization of a union containing
structs and how many curly braces is enough.
=> [linux-port] Compile improvements (helps gcc).

include/dxc/Support/microcom.h, lib/DxcSupport/FileIOHelper.cpp, tools/clang/tools/dxr/CMakeLists.txt, tools/clang/unittests/HLSL/CompilationResult.h, tools/clang/unittests/HLSL/HlslTestUtils.h, tools/clang/unittests/HLSLHost/CMakeLists.txt
InterlockedIncrement and InterlockedDecrement are atomic operations to
increment or decrement the value pointed to by the pointer parameter and
return the same.
There are already platform abstractions available to LLVM in Atomics.h.
This change leverages them to implement the same functionality in a
platform-agnostic way. Mostly it's just a matter of swapping
InterlockedIncrement for AtomicIncrement.
=> [linux-port] Use llvm::sys::Atomic*

include/dxc/HLSL/DxilOperations.h, lib/HLSL/DxilOperations.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/CodeGen/BackendUtil.cpp, tools/clang/lib/CodeGen/CodeGenModule.cpp
GCC has what seems to me to be a bug where it disapproves of the members
of a member struct of class OP having the same name as a type imported
by "using". It's the only compiler with the issue and I don't see any real
conflict, but it's easier to placate it than to fix GCC. GCC
claims its ambiguous. Making the member variables lowercase fixes
this neatly.
Removed some PointerStatus:: prefixes from references within the
class itself which upsets GCC.
HLSL changes excluded Transforms/Instrumentation directory entirely
including BoundsChecking. However it didn't excluder one reference
to a function declared there in BackendUtil that fails to link on GCC.
The function that references the missing BoundsChecking function
is static and not used anywhere with current settings. So it's not …
=> [linux-port] More compile improvement (helps GCC).

include/dxc/HLSL/DxilMetadataHelper.h, include/dxc/HLSL/DxilModule.h, include/dxc/HLSL/DxilOperations.h, include/dxc/HLSL/DxilResourceBase.h, include/dxc/HLSL/DxilTypeSystem.h, include/dxc/HLSL/HLModule.h, lib/HLSL/DxilShaderAccessTracking.cpp, lib/HLSL/HLOperationLowerExtension.cpp, tools/clang/lib/SPIRV/GlPerVertex.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/Sema/SemaHLSL.cpp
Terminating classes may create a muscle memory for typing a
semicolon after a left-justified closed brace. Whatever the reason
to GCC's chagrine there were many functions ended with unnecessary
semicolons. Each one caused a warning. This removes them.
Fixes 285 GCC warnings
=> [linux-port] Remove extra semicolons

include/dxc/HLSL/DxilSignatureAllocator.h, lib/HLSL/DxilContainerAssembler.cpp, lib/HLSL/HLMatrixLowerPass.cpp, tools/clang/lib/Sema/SemaHLSL.cpp
There is the possibility of a few variables being used without
initialization, which causes some warnings.
Fixes 2 clang warnings
GCC worries that assigning a variable to the result of an
assignment of that same variable may be undefined. It's a silly
thing to do anyway. So it's removed.
Fixes 1 gcc warning.
GCC is quite sure that Interp is too small to hold values of up
to 9 with only 4 bits. Perhaps because the RHS is a variable of 8 bits.
Fixes 47 gcc warnings
=> [linux-port] Scalar initialization warnings

include/dxc/Support/dxcapi.impl.h, include/dxc/Support/microcom.h, lib/DxcSupport/FileIOHelper.cpp, lib/HLSL/DxcOptimizer.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/tools/dxc/dxc.cpp, tools/clang/tools/dxcompiler/dxcassembler.cpp, tools/clang/tools/dxcompiler/dxclibrary.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/tools/dxcompiler/dxcontainerbuilder.cpp, tools/clang/tools/dxcompiler/dxcvalidator.cpp, tools/clang/tools/libclang/dxcrewriteunused.cpp
Clang produces a warning when a method that overrides another is
not marked with the override keyword. Adding the keyword has no
effect on overridden functions, but it is good practice to mark
all methods intended to override as such because if they fail to
do so, the keyword will produce an error.
Fixes 78 Clang warnings.
=> [linux-port] Mark all overridden methods

lib/HLSL/HLOperations.cpp, tools/clang/lib/CodeGen/CGClass.cpp, tools/clang/lib/Frontend/FrontendAction.cpp, tools/clang/lib/Sema/SemaChecking.cpp, tools/clang/tools/dxcompiler/dxcfilesystem.cpp, tools/clang/tools/dxcompiler/dxcutil.cpp
Remove pragma once from source files. It has no meaning in a source
file unless it's used as a header, which, fortunately, none of
these are.
Fixes 3 clang and 3 gcc warnings.
Remove trailing tokens after #endifs. Common result from copy,
paste, and slightly alter the beginning #if line to keep the
comments after consistent.
Fixes 3 clang and 3 gcc warnings.
=> [linux-port] Fix preprocessor warnings

include/dxc/HLSL/DxilPipelineStateValidation.h, lib/DxcSupport/FileIOHelper.cpp, lib/HLSL/DxilMetadataHelper.cpp, lib/HLSL/DxilRootSignature.cpp, tools/clang/tools/dxc/dxc.cpp, tools/clang/tools/dxcompiler/dxcdisassembler.cpp, tools/clang/tools/dxcompiler/dxcfilesystem.cpp
There are a lot of cases where const is carelessly cast off. Some
of them lead to really dramatic changes in multiple interfaces to
fix properly. This is instead a subset of cases where const was
disrespected, often for no apparent reason at all. likely just a
mistake in type casting.
Fixes 88 gcc and 88 clang warnings.
=> [linux-port] Correct const casts

include/dxc/Support/WinIncludes.h, lib/DxcSupport/FileIOHelper.cpp, tools/clang/tools/dxcompiler/dxcfilesystem.cpp, tools/clang/tools/dxr/dxr.cpp
A most pervasive warning from a minimal amount of code. The Wintypes
header included an anonymous struct in the form of LARGE_INTEGER
which is specified by Microsoft, but the actual MS header includes
another struct in the union for environments that don't want
anonymous structs. Given the minimal usage, I think this can
qualify. Microsoft's own headers will exclude the anonymous struct
in favor of the named one if NONAMELESSSTRUCT is defined before
windows.h. To prevent future uses of the anonymous part of LARGE_
INTEGER, this defines that in WinIncludes.h.
Fixes 148 clang and 148 gcc warnings.
=> [linux-port] Fix anonymous struct warnings

lib/Target/TargetMachine.cpp, tools/clang/lib/AST/MicrosoftMangle.cpp, tools/clang/lib/CodeGen/CGStmtOpenMP.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp
Various lambda functions included captured variables that they
didn't actually use. This produces a warning on clang.
Fixes 6 clang warnings.
=> [linux-port] Fix warnings from lambda functions

include/dxc/Support/Global.h, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilSignatureElement.cpp, lib/HLSL/HLMatrixLowerPass.cpp, lib/HLSL/HLModule.cpp, lib/HLSL/HLOperationLower.cpp, lib/HLSL/HLSignatureLower.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/ShaderOpTest.cpp
The various DXASSERT macros produced a number of different warnings.
The most obvious was providing an empty string for a macro expecting
a message. Substituting in the _NOMSG macro fixes this.
Fixes 13 clang warnings.
A trickier problem for GCC and Clang is a variadic macro that is
provided no variadic arguments. Both Clang and GCC will avoid
errors by using the ##__VA_ARGS__ non-standard behavior, but it's
not an ideal solution. It turns out there aren't that many DXASSERT
macros that actually take variadic arguments. So I added an _ARGS
variant and replaced those instances with that. An ancillary benefit
is that non variadic asserts can present a message with the assert.
Fixes 583 clang warnings and 582 gcc warnings.
In what I expect was an earlier attempt to overload the DXASSERT …
=> [linux-port] Fix DXASSERT warnings

lib/HLSL/DxilGenerationPass.cpp, tools/clang/lib/Parse/HLSLRootSignature.cpp, tools/clang/lib/Parse/HLSLRootSignature.h, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/GlPerVertex.cpp, tools/clang/lib/SPIRV/GlPerVertex.h, tools/clang/tools/dxcompiler/dxcompilerobj.cpp
Clang is smart enough to detect when a class member function or
variable is not used and emits a warning for that case. This
removes all such members as well as any corresponding parameters
and other variables that might have been used to initialize such.
Fixes 8 clang warnings.
NotOptimized in DxilGenerationPass echoed in places that made us
think that it might be needed at some point in spite of not being
used now. So it gets a dummy reference instead of being removed.
=> [linux-port] Remove/dummy unused class components

lib/HLSL/ComputeViewIdState.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilOperations.cpp, lib/HLSL/DxilValidation.cpp, lib/HLSL/HLSignatureLower.cpp, tools/clang/include/clang/Frontend/CompilerInstance.h, tools/clang/lib/AST/Decl.cpp, tools/clang/lib/Sema/SemaChecking.cpp, tools/clang/lib/Sema/SemaDeclObjC.cpp, tools/clang/lib/Sema/SemaHLSL.cpp
Simply including a variable as the entirity of an expression is
insufficient to silence warnings for gcc and clang. The variable
is not reported as unused, which is the intent, but the expression
result is reported in a warning as unused. By casting that
expression as (void), both warnings are silenced.
Fixes 110 clang and 40 gcc warnings.
=> [linux-port] Dummy access to unused variables

external/CMakeLists.txt, external/GTestConfig.cmake, tools/clang/unittests/SPIRV/DecorationTest.cpp, tools/clang/unittests/SPIRV/ModuleBuilderTest.cpp
clang-spirv-tests uses a lot of external projects that keep
themselves clean with different standards of warnings flags.
This alters the appropriate cmake files to disable flags that
the DXC build enables.
Fixes 72 gcc and 166 clang warnings.
Additionally catch some sign mismatch comparisons in tests
built as part of clang-spirv-tests.
Fixes 2 gcc and 2 clang warnings, but one of them has multiple sources
So it's kind of a lot more.
=> [linux-port] Fix spirv test warnings

lib/DxcSupport/dxcapi.use.cpp, lib/HLSL/DxilOperations.cpp, lib/HLSL/DxilValidation.cpp, lib/HLSL/HLModule.cpp, lib/Transforms/IPO/PassManagerBuilder.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/AST/DeclPrinter.cpp, tools/clang/lib/CodeGen/CGCall.cpp, tools/clang/lib/CodeGen/CodeGenModule.cpp, tools/clang/lib/Lex/LiteralSupport.cpp, tools/clang/lib/Lex/TokenLexer.cpp, tools/clang/lib/Parse/ParseExpr.cpp, tools/clang/lib/Parse/ParseTemplate.cpp, tools/clang/lib/Parse/Parser.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/lib/Sema/SemaOverload.cpp
Clang and gcc complain when AND and OR logical operations are both
used in a single conditional because of the possibility of mistakes
when depending solely on operator precedence. In fact, this change
fixes a few clear errors mostly in asserts that would never fire.
Fixes 13 clang and 22 gcc warnings.
Additionally, when two if statements are followed by an else, there
may be some ambiguity in terms of which if the else applies to. It
is the closest one, the second in the case of two, but it is another
area of potential mistakes. Adding braces around the code intended
as the block of the first if conditional clarifies this.
fixed 8 clang and 8 gcc warnings.
Clang complains sometimes when assignments take place in a
conditional without additional parenthesis around it. It can
indicate when …
=> [linux-port] Correct conditional groupings

cmake/modules/HandleLLVMOptions.cmake, external/CMakeLists.txt
Defaults in switch statments can mask warnings that might
indicate that a new enum value was added and corresponding changes
to a switch statement that relies on that enum are missed. For this
reason, clang reports when switch statements that fully define case
statements for all possible enum values contain default: statements.
However, this is a warning of a potential problem that might arise
from future changes to the code rather than anything that might be
wrong now. Additionally, while unlikely that an enum switch might
be presented with a value that isn't valid for that enum, it isn't
impossible. So rather than respect this warning, we will silence it.
It's not included by default. LLVM wanted it. We don't, so it's
removed. This makes the earlier external cmake change unnecessary. …
=> [linux-port] disable covered-switch-default warning

lib/HLSL/ComputeViewIdState.cpp, lib/HLSL/DxilOperations.cpp, lib/HLSL/DxilTypeSystem.cpp
Found as part of a project to eliminate warnings, but this is an
actual bug. An HLSL change adds the possibility of a Dxil and an
HLSL module to the base LLVM Module as well as the ability to
retrieve a reference to them when the are present. This reference
retrieval was mistakenly used to determine if the module was
present in spite of the fact that references are never null. Worse
the reference is from a dereferenced pointer, so if it wasn't there,
it would cause a null dereference. The module interface had methods
to query the presence of these submodules, but they weren't used.
fixes 4 clang warnings and possibly some mysterious crashes
The same warning for a different cause is encountered where an
address is taken of a value passed by reference and compared to
null, which can never …
=> [linux-port] Replace tests of never null addresses

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/method.append-structured-buffer.append.hlsl
The AppendStructuredBuffer's Append method was not checking for lvalues.
=> [spirv] Append must load pointers first

lib/DxcSupport/Global.cpp, lib/HLSL/DxilAddPixelHitInstrumentation.cpp, lib/HLSL/DxilRootSignature.cpp, lib/HLSL/DxilShaderAccessTracking.cpp, lib/HLSL/PauseResumePasses.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/GlPerVertex.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/tools/dxcompiler/dxcdisassembler.cpp
Various comparisons produce warnings because the values differ in
signedness. This either changes the type of one of the parameters
or else it casts one. This includes adding casts to all of the
defined return error values. Which is more than was needed, but
consistent with some existing values anyway.
Fixes 11 clang and 12 gcc warnings.
Eliminate a few greater than or equal comparisons of unsigned
values which are always true. The most aggressive of this is
the exclusion of a function that has become a no-op because of
HLSL initialization of a key variable that had some invalid
comparisons because of the same const value.
Fixes 4 clang and 7 gcc warnings.
Additionally casts a few parameters to the proper type to silence
warnings about confusing or problem casts. This includes printing …
=> [linux-port] Casts for compares and assigns

include/dxc/HLSL/DxilRootSignature.h
pParameters and pStaticSamplers were both marked const in spite of
the qualifier being cast off at nearly every usage. So they lose
their const. If you're the target of memcpy or memset, you are
not const.
Fixes 12 gcc and 12 clang warnings
=> [linux-port] de-const variables not used as const

lib/DxcSupport/dxcmem.cpp
LLVM includes cross-platform thread local storage methods for
saving, retrieving, and deleting thread-specific objects. Using
these methods is superior to the thread_local storage qualifier
because the former works on Apple, Linux, and Windows. It also
uses the same mechanism as the previous Windows implementation
used without compiler idiosyncracies.
Placement new is needed in DxcInitThreadMalloc because operator
new requires the TLS malloc to be in place.
=> [linux-port] Use cross-platform TLS methods

cmake/modules/FindD3D12.cmake, cmake/modules/FindTAEF.cmake, tools/clang/unittests/HLSL/CMakeLists.txt, utils/hct/hctbuild.cmd, utils/hct/hctstart.cmd
hctstart.cmd and hctbuild.cmd now support ARM64 build.
Note that building ARM64 on x86/x64 machine needs a location
of x86/x64 version of TableGen tools (clang-tblgen and llvm-tblgen).
Before starting the ARM64 build set the BUILD_TBLGEN_PATH to point
to the TableGen binaries or use the -tblgen option on hctbuild.cmd.
Also had to rearrange control flow around the cmake --build call
in hctbuild.cmd due to a flaky batch behavior around brackets.
=> Modify build script and environment to support ARM64 build

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
A persistent and occasionally confusing warning is produced on
Windows release builds because of a conditional expression that only
contains an assert. On a release build, this amounts to nothing but
a semicolon, which produces the warning.
This folds the conditional into the previously explicit assert so
it is included or excluded entirely regardless of build type.
=> Fix warning on windows release builds (#243)

lib/HLSL/DxilDebugInstrumentation.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilRootSignature.cpp, lib/HLSL/DxilValidation.cpp, lib/HLSL/HLMatrixLowerPass.cpp, lib/HLSL/HLModule.cpp, lib/HLSL/HLOperationLower.cpp, lib/HLSL/HLSignatureLower.cpp, lib/IR/LegacyPassManager.cpp, lib/IR/Verifier.cpp, lib/Support/CommandLine.cpp, lib/Support/Timer.cpp, lib/Transforms/IPO/MergeFunctions.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/AST/ASTContextHLSL.cpp, tools/clang/lib/AST/ExprConstant.cpp, tools/clang/lib/AST/HlslTypes.cpp, tools/clang/lib/CodeGen/CGExprAgg.cpp, tools/clang/lib/CodeGen/CGExprCXX.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Parse/HLSLRootSignature.cpp, tools/clang/lib/Parse/ParseDecl.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/Sema/SemaExprObjC.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/lib/Sema/SemaOpenMP.cpp, tools/clang/tools/dxcompiler/dxcdisassembler.cpp
Removes unused variables and functions from code between HLSL
change comments in LLVM code or else in HLSL or SPIRV original
source files along with any code correspondingly rendered unused
or originally in service of these ultimately unused elements.
Each of these produces a warning in clang, gcc, or both.
Fixes around 458 clang warnings and 461 gcc warnings.
=> [linux-port] Remove unused from HLSL code

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp
ModuleBuilder had a catch-all function to apply decorations not
taking additional parameters, however, every single call to this
has an explicit decoration parameter. The switch only slows things
down and doesn't help with code length or anything else. The switch
is missing the other decorations that have custom functions, which
produce warnings. Rather than add a default: case, I've provided
custom decorate functions for each decoration.
=> [linux-port] Multiplex ModuleBuilder decorations

lib/DxcSupport/dxcapi.use.cpp, tools/clang/tools/dxc/dxc.cpp, tools/clang/unittests/dxc_batch/dxc_batch.cpp
CreateFile2() is only available from Windows 8. Changed to use CreateFileW(),
which is more widely supported.
Fixes https://github.com/Microsoft/DirectXShaderCompiler/issues/1265
=> Use CreateFileW instead of CreateFile2

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/op.buffer.access.hlsl
Accessing sub-elements in (RW)Buffer with adjacent array subscript
operators was falsely translated into an OpAccessChain with two
indices. Instead, we need to perform OpImage* on the (RW)Buffer
object and then do single-index OpAccessChain.
=> [spirv] Fix accessing (RW)Buffer sub-element using [][]

include/dxc/Support/Global.h, lib/HLSL/ComputeViewIdState.cpp, lib/HLSL/DxilDebugInstrumentation.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/HLMatrixLowerPass.cpp, lib/HLSL/HLOperationLower.cpp, lib/HLSL/HLSignatureLower.cpp, lib/Transforms/Scalar/IndVarSimplify.cpp, lib/Transforms/Scalar/PlaceSafepoints.cpp, lib/Transforms/Scalar/SROA.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/CodeGen/CGCall.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Frontend/FrontendActions.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/Sema/SemaDecl.cpp
A number of warnings unique to release buildsi persist. Some of these
same errors were fixed earlier for debug builds.
DXASSERT_LOCALVAR still took a variadic macro on release builds.
Fixes 85 clang warnings
Expressions used only as conditionals for asserts were not properly
dummied out with (void) cast.
Fixes 7 clang warnings
Variables used only in asserts dummied out.
Fixes 27 clang warnings
Potential uninitilized uses of variables assigned in switches/ifs.
fixes 5 clang warnings
put braces around empty else statements
11 gcc warnings
=> [linux-port] Eliminate warnings on release builds

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/test/CodeGenSPIRV/vk.binding.precedence.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
A missing `else` made it possible for a resource variable with a
corresponding counter variable that was defined with both
vk::binding and :register, each indicating a different descriptor
set to have the main variable assigned the set indicated by
vk::binding while the counter went to the set indicated by the register
Adds a new test for this and other such conditions.
=> [spirv] Fix counter_binding precedence and test

appveyor.yml
Right now we have a mechanism to version rolling build. It depends
on the Git history and will count number of commits. So we need
the full history.
=> [appveyor] Clone the whole history

tools/clang/lib/AST/ItaniumMangle.cpp
Determines what the type is represented as in function name mangling.
Just as easy to get it right. Simple typo fix.
Fixes https://github.com/Microsoft/DirectXShaderCompiler/issues/1368
=> Correct min21_int typo in ItaniumMangle

tools/clang/include/clang/SPIRV/Type.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/Type.cpp, tools/clang/test/CodeGenSPIRV/empty-struct-interface.vs.hlsl2spv, tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.counter.method.hlsl, tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.struct.hlsl, tools/clang/test/CodeGenSPIRV/type.struct.uniqueness.hlsl, tools/clang/test/CodeGenSPIRV/vk.cloption.invert-y.ds.hlsl, tools/clang/test/CodeGenSPIRV/vk.cloption.invert-y.gs.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.nested.empty.std140.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.vector.relaxed.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp, tools/clang/unittests/SPIRV/SPIRVContextTest.cpp, tools/clang/unittests/SPIRV/TypeTest.cpp
We were unifying struct types as long as they have the exact
same members (regardless of names). BUt it turns out some
reflection workflow requires the exact original struct type
to work.
=> [spirv] Avoid unifying struct types with different names

include/dxc/Support/WinAdapter.h, include/dxc/Support/WinFunctions.h, include/dxc/Support/WinIncludes.h, lib/DxcSupport/CMakeLists.txt, lib/DxcSupport/WinAdapter.cpp, lib/DxcSupport/WinFunctions.cpp
This change completes the necessary adapter code needed to enable
cross-platform compilation.
Discussion on the design/implementation of these are in issue #1341 and
isuee #1342.
In addition to the adapter classes/structs, there exists usages of
Windows-specific functions in the codebase. In some cases, we won't need
to compile/run some of those methods on non-Windows platforms. For the
few cases where we do, we have implemented equivalent functionality in
WindowsFunctions.cpp.
=> [linux-port] Complete the Windows adapter code.

include/dxc/Support/HLSLOptions.h, include/dxc/dxcisense.h, include/llvm/PassRegistry.h, include/llvm/Support/Mutex.h, lib/DxcSupport/HLSLOptions.cpp, lib/DxcSupport/dxcapi.use.cpp, lib/IR/PassRegistry.cpp, lib/Support/ErrorHandling.cpp, lib/Support/assert.cpp, tools/clang/include/clang/Frontend/FrontendActions.h, tools/clang/lib/Frontend/FrontendActions.cpp, tools/clang/tools/dxcompiler/dxcfilesystem.cpp, tools/clang/tools/libclang/dxcrewriteunused.cpp
Some code originally in llvm/clang was commented out, and was replaced
with Windows-specific implementation. In this change we bring back some
of those.
Also disabled some code that is not relevant any more.
And a few minor improvements towards cross-platform compilation.
=> [linux-port] Enable some code. Disable some code.

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/bezier.domain.hlsl2spv, tools/clang/test/CodeGenSPIRV/bezier.hull.hlsl2spv, tools/clang/test/CodeGenSPIRV/empty-struct-interface.vs.hlsl2spv, tools/clang/test/CodeGenSPIRV/hs.pcf.primitive-id.1.hlsl, tools/clang/test/CodeGenSPIRV/hs.pcf.view-id.1.hlsl, tools/clang/test/CodeGenSPIRV/semantic.dispatch-thread-id.int2.cs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.dispatch-thread-id.uint.cs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.domain-location.ds.hlsl, tools/clang/test/CodeGenSPIRV/semantic.group-id.int2.cs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.group-id.uint.cs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.group-thread-id.int2.cs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.group-thread-id.uint.cs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.inner-coverage.ps.hlsl, tools/clang/test/CodeGenSPIRV/spirv.entry-function.inout.hlsl, tools/clang/test/CodeGenSPIRV/spirv.entry-function.unused-param.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.ds.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.gs.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.hs.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.ps.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.vs.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Some workflow relies on trimming off unused stage output variables.
But we created a wrapper around the source code entry function to
satisfy Vulkan's requirement over entry function signature.
Previously we just blindly write back all stage output variables
in the wrapper function no matter whether the corresponding stage
output variable is used or not in the source code entry function.
Now we can be a little bit clever based on the usedness info
from the AST.
=> [spirv] Avoid writing unused stage output variable back

include/dxc/Support/WinAdapter.h, include/dxc/Support/WinFunctions.h, lib/DxcSupport/FileIOHelper.cpp, lib/DxcSupport/WinFunctions.cpp, lib/MSSupport/MSFileSystemImpl.cpp, lib/Support/Unix/Path.inc
Some interactions with the FileSystem are not used by any API and are
therefore not implemented for Unix at the moment. We have put assertions in
place to make it easy to spot if any of those methods are ever used.
=> [linux-port] FileSystem and IO.

include/llvm/Analysis/TargetLibraryInfo.def, lib/Analysis/TargetLibraryInfo.cpp, lib/Transforms/IPO/FunctionAttrs.cpp
Alpine Linux and probably several others, define fopen64, fseeko64,
ftello64, and tmpfile64 to their 32 bit equivalents in system
headers. This results in duplicates in areas of the code that
include 32 bit and 64 bit references to this. Since HLSL doesn't
have any of these functions anyway, we can safely exclude them.
=> [linux-port] Fix gcc6.4 alpine(and others) compile

include/dxc/Support/dxcapi.use.h, lib/Support/CMakeLists.txt, tools/clang/tools/dxcompiler/dxillib.cpp
LLVM includes a DynamicLibrary class that works on multiple platforms
Rather than ifdefing between dlopen for non-Windows and LoadLibraryW
on Windows, using this class allows us to abstract platform differences
while using the same code.
Changed DxilLibInitialize to attempt to initialize dxil.dll so the
smart mutex inside the dynamic library object uses the same IMalloc
as the other ManagedStatic objects so they can all be freed in order.
=> [linux-port] Use cross-platform dynamic lib load

include/dxc/dxcapi.h, include/dxc/dxcisense.h, include/dxc/dxctools.h, lib/HLSL/DxilContainerReflection.cpp, tools/clang/tools/dxcompiler/dxcapi.cpp
As described #1342, this change makes it possible for interfaces to
compile on other platforms, without making any intrusive changes.
=> [linux-port] Enable cross-platform interfaces.

include/dxc/Support/Global.h, lib/DxcSupport/HLSLOptions.cpp, lib/DxcSupport/dxcmem.cpp, lib/Support/regerror.c, lib/Support/regex_impl.h, tools/clang/tools/dxcompiler/DXCompiler.cpp
The REGEX_H define prevented the inclusion of an Apple system header.
Not coincidentally, the same header regex_impl.h was derived from.
Prevent Apple warning by splitting macro args with an #else. Add HLSL
change comments too which were missing from the start.
MacOS resolves symbols differently from Linux. Linux takes the first
valid resolution and then uses it wherever it is referenced. MacOS
more similar to Windows, favors symbols that are local to the
compilation unit.
This comes into play where functions set static globals such as
the malloc tls and the IMalloc contained there. The dxc binary
initializes these. For Linux, that's enough because all calls
resolve to the ones from this binary because they are encountered
first. MacOS calls that originate from within the dynamic library …
=> [macos-port] Allow dxc and tests to run on mac

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/unittests/SPIRV/FileTestUtils.cpp
Keeping the original struct type is important for some reflection
workflows.
The validation check for layout is alo included. But we disable
it for now and will re-enable it after fixing all the failures.
Fixes https://github.com/Microsoft/DirectXShaderCompiler/issues/1364
=> [spirv] Update SPIRV-Tools for not merging resource types

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/op.struct.access.hlsl
We should always create a temporary variable for rvalues if we
are trying to get an access chain from it. Now do it in the
turnIntoElementPtr() function, which is used everywhere.
Fixes https://github.com/Microsoft/DirectXShaderCompiler/issues/1387
=> [spirv] Fix returning struct containing arrays

CMakeLists.txt, docs/DxcOnUnix.rst, tools/clang/unittests/SPIRV/CMakeLists.txt
This way we can just run ctest to invoke the tests, instead of
remembering the binary and its parameters.
=> [spirv] Do not build tests by default and hook up with ctest

lib/HLSL/DxilContainerAssembler.cpp
A lambda function relied on captured variables after they went out
of scope. The result on Linux was access to random data. The effect
varies randomly just as returning a point to a variable that goes
out of scope might.
=> Fix lambda captures in dxilcontainer serializer

include/dxc/Support/WinAdapter.h, lib/DxcSupport/Unicode.cpp
MultiByteToWideChar and WideCharToMultiByte were returning -1 on
failure, which caused failures to be ignored. When successful, they
were returning the number of characters converted excluding the
terminating null character because that's what the std:: functions
used for the implementation do. Both are inconsistent with the
original Windows implementations.
Simply adding one to the return value works in all cases save those
where the number of characters converted was limited by the parameter
In this case, the number of characters converted doesn't include
the terminating null. So no addition is warrented.
Added addition errors in keeping with the function descriptions.
The CW2A conversion class left out the terminating null character
when calculating the max size of the converted …
=> [linux-port] Correct char convert size in/out

tools/clang/lib/Parse/ParseDecl.cpp
Like on other platforms, on Windows, strtoul is limited to the size
long. However, long on windows is 32, on linux, it's 64. So Linux
happily converts a string that requires more than 32 bits.
However, it is returned into a variable that is only 32 bits.
In order to keep Linux behavior consistent with Windows, and for
lack of a strtou function, strtoul is still called, but overflow
of 32 bits is detected and reported as an error, making Verifier-
Test happy.
=> [linux-port] Handle register number limits

tools/clang/tools/dxcompiler/dxcfilesystem.cpp
Included file HANDLEs are generated using the type, the file index
and some representation of the directory. Since they are not real
files on a real filesystem, they don't have genuine handles.
This conversion is performed using a union containing the above
values and a HANDLE object, which is returned after these are assigned
However, the size of the above values is far less than that of the
HANDLE, which leaves many bits uninitialized, containing random
values.
By initializing the handle to 0, then the capital-B "Bits" values,
no small-b bits are left uninitialized.
=> Initialize all bits in IncludedFileIndexToHandle

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/type.cbuffer.hlsl, tools/clang/test/CodeGenSPIRV/type.struct.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.struct.relaxed.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp, tools/clang/unittests/SPIRV/FileTestFixture.cpp, tools/clang/unittests/SPIRV/FileTestFixture.h, tools/clang/unittests/SPIRV/FileTestUtils.cpp, tools/clang/unittests/SPIRV/FileTestUtils.h, tools/clang/unittests/SPIRV/WholeFileTestFixture.cpp
For VK_HKR_relaxed_block_layout, a vector inside structs can have
its offset as a multiple of its base element type's alignment.
But the vector's alignment is unaffected, esp. when used for
calculating the alignment of the whole enclosing struct.
Also enables SPIRV-Tools validation on block layouts.
=> [spirv] Fix Vulkan layout struct member alignment bug

tools/clang/include/clang/Basic/TokenKinds.h, tools/clang/lib/Parse/ParseDecl.cpp, tools/clang/lib/Parse/ParseStmt.cpp, tools/clang/lib/Parse/ParseTentative.cpp, tools/clang/test/CodeGenHLSL/quick-test/sample_kwd.hlsl
There are more cases in which the `center`/`sample`/etc modifier
should be treated as identifiers:
* Inside decoration groups
* In assignments
* Inside parentheses
* etc.
This commit adds a few more special handling cases that turns these
modifiers into identifiers, upon seeing the next token as punctuator.
=> Turn modifier 'center' and friends into identifiers in more cases

lib/DxcSupport/WinFunctions.cpp
The StringCchPrintfA implementation for Unix systems mistakenly
used the wrong printf variants. Instead of accessing the variadic
arguments, it was just using the va_list variable as a format
parameter. Additionally, reusing va_list has undefined results.
So a copy needs to be made using va_copy.
=> [linux-port] Varargs in StringCchPrintfA

include/dxc/Support/WinAdapter.h, include/dxc/Support/WinFunctions.h, lib/DxcSupport/WinFunctions.cpp
A number of Windows-specific features are present in the HLSL tests
as well as driver features that had to be enabled to get those tests
running, notably intellisense classes.
This change adds to the existing WinAdapter and WinFunctions files
to include the features needed for these additions to compiler and tests.
They cover a lot of ground, but mostly consist of memory allocation
and string changes, because you can never have enough ways to
allocate memory and manipulate strings.
An incidental change is to the existing CreateFileW implementation
to retry a file if the error indicated it was interrupted. This was
taken from the LLVM Path.inc implementation for Unix.
=> [linux-port] Win adapter changes for HLSL tests

include/dxc/dxcisense.h, lib/HLSL/DxilContainerReflection.cpp, tools/clang/tools/dxcompiler/dxcapi.cpp, tools/clang/tools/libclang/CMakeLists.txt, tools/clang/tools/libclang/dxcisenseimpl.cpp
Several HLSL tests, notably VerifierTest, require intellisense classes
To get these working on Unix platforms, we need to add support.
This involves mostly exposing the instance creation, the UUID, and
adding the right headers. 
Additionally adds definitions of a couple UUIDs that were declared
but previously not defined. These are also useful for HLSL tests.
=> [linux-port] Enable intellisense classes for Unix

tools/clang/unittests/CMakeLists.txt, tools/clang/unittests/HLSL/CMakeLists.txt, tools/clang/unittests/HLSL/HLSLTestOptions.cpp, tools/clang/unittests/HLSL/HLSLTestOptions.h, tools/clang/unittests/HLSL/TestMain.cpp
On Windows, HLSL tests run using TAEF. Since that's not available
on other platforms, this change adapts the tests to work on gtest
framework with minimal alterations to the tests themselves.
TestMain.cpp is pilfered and enhanced from Spirv tests. It provides
a starting point for the gtest binary to initialize variables and
launch tests, though gtest hides most of that.
Derived from SpirvTestOptions, this lists a number of potential
options from the command line and provides a crude, but effective
mechanism to access the as needed.
With this commit, you can run clang-hlsl-tests, but it does't really
do anything. Tests will follow shortly.
=> [linux-port] gtest interface for HLSL tests

include/dxc/Support/WinAdapter.h, include/dxc/Support/WinFunctions.h, lib/DxcSupport/FileIOHelper.cpp, lib/DxcSupport/WinFunctions.cpp, tools/clang/tools/dxc/dxc.cpp
Heap allocation functions were previously partially implemented via
a few macros that provided some of the functionality.
This replaces those macros with a more expansive implementation of
the interface as defined in Microsoft documents. Simple structs are
used to store pointer and size implementation, enabling queries of
allocation sized from pointers, putting an upper limit on the total
amount of memory allocated by the given heap, retrieving a
default heap for the process, and freeing of all heap memory at the
time of heap destruction.
Most flags are unsupported save ZERO_MEMORY. Heap creation includes
an initial size that is meant to preallocate memory and make latter
allocations more efficient. This does not support that. Still for
the usages in the code base, this should appear …
=> [linux-port] Unix Heap* allocation implementation

include/dxc/Support/WinAdapter.h
In rebasing the heap change, I mistakenly removed the sysallocstringlen
and sysfreestring functions. This restores them.
=> [linux-port] restore mistakenly removed sysallocs

docs/SPIR-V.rst, include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/SPIRV/EmitSPIRVOptions.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/vk.cloption.invert-w.ps.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
This option receiprocates (multiplicatively inverts) SV_Position.w
after reading it from stage input in PS. This is used to accommodate
the difference between Vulkan and DirectX.
=> [spirv] Add -fvk-invert-w

tools/clang/lib/Frontend/CompilerInvocation.cpp
Due to the format that Windows arguments take, files on Unix systems
can sometimes be mistaken for them. A notable example of this is a
file from a directory starting with /U because it will look to the
arg processor exactly like the undefine-macro argument. Because of
this, the VerifierTest might seem to hang because, seeming to have
no input file, it falls back to reading stdin.
The dxc binary avoids this by using a completely different set of
options that doesn't include any of these. clang itself uses
inclusion and exclusion flags that determine on which systems and
under what circumstances / arguments are allowed.
CompilerInvocation::CreateFromArgs was altered to not take any of
these bitfields for the sake of the HLSL tests. I've made a slight
alteration to that to exclude the …
=> [linux-port] Fix conflict with /U arg and files

docs/SPIR-V.rst, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/vk.cloption.invert-w.ds.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Allow using -fvk-invert-w in non-PS stages and make it a no-op.
=> [spirv] -fvk-invert-w in non-PS stages is no-op

.travis.yml, tools/clang/unittests/HLSL/AllocatorTest.cpp, tools/clang/unittests/HLSL/CMakeLists.txt
Enable gtest support and create temp variable to pass to std::min
by reference as it does on Linux.
Also enables clang-hlsl-tests for travis as it will now be running
something useful
=> [linux-port] Enable AllocatorTest for Unix

lib/DxcSupport/FileIOHelper.cpp
Recent changes to FileIOHelper enabled HeapMalloc, which extends
IMalloc, but didn't mark the overriden functions with override.
This produces warnings on some compilers. Added a little clang-
formatting to the affected region too.
=> Add overrides to HeapMalloc

include/dxc/Support/WinAdapter.h, tools/clang/unittests/HLSL/CMakeLists.txt, tools/clang/unittests/HLSL/DXIsenseTest.cpp
Mostly required converting simple member function definitions
to include the TEST_F macro, which works for either gtest or taef,
but is optional for the latter.
Fixed an additional bug that I can't imagine being unique to Unix
where the address of the pointer in one CComPtr in an array was
used with the expectation that the subsequent pointer would follow
immediately after in memory with no CComPtr members in between.
Maybe it is on Windows, it certainly isn't on the Unix implementation.
=> [linux-port] Enable DXIsenseTest on Unix

tools/clang/unittests/HLSL/CMakeLists.txt
There are several object files that get included in the dynamic
library as well as the executable binary that is linked to it.
This is probably due to the limited way that the Windows linker
exposes symbols. Regardless, the duplicate inclusion doesn't cause
much of a problem, it just includes two copies of various variables
and functions. One set is used, the other is wasted. The executable
is a bit larger as a result, but there are no other consequences.
However, for some linkers in some cases, this is a problem. Of
particular concern are cases where where addresses of static
variables are used as identifiers. Each compilation unit, will have
its own set of static symbols. Where the call begins and possibly
some compiler optimizations will determine which static variable's
address is …
=> Remove unneeded object files from HLSL tests

tools/clang/unittests/HLSL/CMakeLists.txt, tools/clang/unittests/HLSL/Objects.cpp
Use runtime_error for throwing strings. Remove inaccurate comment.
Add gtest support
=> [linux-port] Enable ObjectTest for Unix

tools/clang/include/clang/SPIRV/InstBuilder.h, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/include/clang/SPIRV/Structure.h, tools/clang/lib/SPIRV/InstBuilderAuto.cpp, tools/clang/lib/SPIRV/InstBuilderManual.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/Structure.cpp, tools/clang/test/CodeGenSPIRV/spirv.debug.opsource.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp
Preprocessed source code could be quite useful for developers
to have a functionality-equivalent shader that they want to
debug.
=> [spirv] Embed preprocessed source code when -Zi

lib/Transforms/IPO/PassManagerBuilder.cpp, tools/clang/test/CodeGenHLSL/quick-test/enable-partial-unroll-test01.hlsl, tools/clang/test/CodeGenHLSL/quick-test/enable-partial-unroll-test02.hlsl
The loop-idiom pass identifies idioms such as memset/memcpy in a loop and replace those idioms with llvm intrinsic such as `llvm.memset` / `llvm.memcpy` which breaks the DXIL. This change disables the loop-idiom pass.
=> Disable loop idiom pass which may break dxil

lib/HLSL/HLPreprocess.cpp, tools/clang/test/CodeGenHLSL/quick-test/alloca-non-entry-basic-block.hlsl
In `HLPreprocess` pass, we assume that allocas could be present in non-entry block only when during inlining `stacksave` / `stackstore` are inserted. However, there could be other cases where allocas could be present in non-entry blocks. This change always tries to move allocas in the non-entry blocks.
=> Always move allocas to entry block

tools/clang/unittests/HLSL/CMakeLists.txt, tools/clang/unittests/HLSL/OptimizerTest.cpp
Add gtest support. Eliminate wsprintf, since there is not a simple
alternative on Linux (to its discredit). It was overkill for just
appending a single numerical digit to two characters anyway.
=> [linux-port] Enable OptimizerTest for Unix

tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/DXIsenseTest.cpp, tools/clang/unittests/HLSL/DxilContainerTest.cpp, tools/clang/unittests/HLSL/OptionsTest.cpp
There are a lot of compares between unsigned variables and literal
integers in HLSL tests that produce a long list of warnings on
Unix platforms.
This appends a -U suffix to the literals to silence the warnings
=> [linux-port] HLSL test unsigned compare warnings

lib/Bitcode/Reader/BitcodeReader.cpp, tools/clang/unittests/HLSL/CMakeLists.txt, tools/clang/unittests/HLSL/FileCheckerTest.cpp, tools/clang/unittests/HLSL/ValidationTest.cpp
Cast negative char literals. Fix capitalization of various shader
files. Add FileCheckerTest and FileCheckForTest to the build. These
are utility files in spite of the *Test suffix on one that enable
running tests according to header comment instructions and testing
results automaticlaly, which ValidationTest and other tests still to
come make use of.
=> [linux-port] Enable ValidationTest for Unix

tools/clang/unittests/HLSL/CMakeLists.txt, tools/clang/unittests/HLSL/FunctionTest.cpp
Exclude reflection and dxil.dll portions that are unsupported or
unneeded.
=> [linux-port] Enable FunctionTest on Unix

tools/clang/unittests/HLSL/CMakeLists.txt, tools/clang/unittests/HLSL/SystemValueTest.cpp
Enable gtest support. Add default or missing cases from switch
statements to quiet warnings.
=> [linux-port] Enable SystemValueTest on Unix

tools/clang/unittests/HLSL/CompilationResult.h, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/FileCheckerTest.cpp, tools/clang/unittests/HLSL/FunctionTest.cpp, tools/clang/unittests/HLSL/HlslTestUtils.h, tools/clang/unittests/HLSL/Objects.cpp
Compiling HLSL tests on Unix produces a long list of warnings that
obfuscate the results of the build and ambiguates the intent.
This includes reordering the constructor initialization lists to
match the actual initialization order, removing unused variables,
changing pointer parameters to const to avoid casts that remove
the const qualifier when the value pointed to is not altered anyway,
removes deprecated and unused header, changes type to match
comparison, casts a few pointers to const when passed in, removes
unused functions.
=> [linux-port] Misc HLSL test warnings

include/dxc/dxcapi.internal.h, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/CMakeLists.txt, tools/clang/unittests/HLSL/ExtensionTest.cpp
Enable the UUID for IDxcLangExtensions so its interface can be
properly queried. Sundry const, semicolon, and override warning
eliminating changes that might have been included in the larger
corresponding changes had this test not been an afterthought.
=> [linux-port] Enable extensiontest for Unix

.travis.yml, tools/clang/unittests/HLSL/CMakeLists.txt, tools/clang/unittests/HLSL/DxilContainerTest.cpp, tools/clang/unittests/HLSL/DxilModuleTest.cpp
Mostly just excluding portions that require reflection allows this
test to run with the usual corralling of header files behine a WIN32
ifdef and adding the gtest inheritence for non-win.
Change an include file capitalization so it can be found on case
sensitive filesystems.
=> [linux-port] DxilContainer/ModuleTest on Unix

lib/HLSL/DxilContainerAssembler.cpp, lib/HLSL/DxilPreserveAllOutputs.cpp
Due to iterating through an unordered_map, and sorting a vector
using a comparison that didn't handle ties completely, some
disassembly outputs were in implementation-dependent order in spite
of tests depending on a certain order.
=> Fix random ordering of disassembly

include/dxc/Support/WinAdapter.h, lib/DxcSupport/Unicode.cpp, lib/DxcSupport/WinAdapter.cpp, tools/clang/test/CodeGenHLSL/quick-test/assignCast.hlsl
Windows char conversion functions differ from the std methods in
a few ways. Windows ignores null terminators when lengths are
provided, length limits represent character lengths not byte sizes,
the current linux implementation ignores codepages, but the files
used in many HLSL tests are in iso 8859-1 not utf8. So some
differentiation is needed.
This solves all but one of the above problems. To limit conversion
by source characters instead of solely the size of the output
buffer, where necessary, a temporary buffer is created to hold the
source string that corresponds to the provided character length and
a null terminator is appended to make the std:: conversion stop there.
If there is a null terminator there already, this is skipped for
performance purposes. Such is often the case.
To …
=> [linux-port] Better match Windows char conversion

tools/clang/unittests/HLSL/CMakeLists.txt, tools/clang/unittests/HLSL/OptionsTest.cpp
Add gtest support. Use llvm::make_unique. Exclue character
conversion test that doesn't work with Unix character conversion
=> [linux-port] Enable OptionsTest on Unix

include/dxc/dxcapi.h, tools/clang/tools/dxcompiler/dxclibrary.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/FileCheckerTest.cpp, tools/clang/unittests/HLSL/RewriterTest.cpp, tools/clang/unittests/HLSL/ShaderOpTest.cpp, tools/clang/unittests/HLSL/ValidationTest.cpp
CreateBlobWithEncodingFromPinned is unlike any of the other
CreateBlob* functions in that its pText argument is a non-const
byte pointer. All the others use const void pointer for this
same parameter. Because the parameter is not const, in many cases
const pointers need to have their const qualifier cast off to be
used for this parameter in spite of the fact that the next level
call passes it to a const pointer. This produces a bunch of
warnings in places where its used.
By changing the variable to const void, there is less unnecessary
casting, fewer warnings, no change in behavior, and a clearer
external indication of the way it is used by the function from the
prototype.
=> Change CreateBlobWithEncodingFromPinned argument to LPCVOID; silence lost const warnings

lib/DxcSupport/WinAdapter.cpp
Conversions on Apple didn't work. That's because the locales are
formatted a bit differently. This alters the codepage to locale
conversion in WinAdapter on Apple to conform to their practices
=> [apple-port] Format locales for Apple

tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_BuildGridCS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_BuildGridIndicesCS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_ClearGridIndicesCS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_DensityCS_Grid.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_DensityCS_Shared.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_DensityCS_Simple.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_ForceCS_Grid.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_ForceCS_Shared.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_ForceCS_Simple.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_IntegrateCS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_RearrangeParticlesCS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/POM_PS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/POM_VS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/Particle_GS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/Particle_PS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/Particle_VS.hlsl, tools/clang/test/CodeGenHLSL/scalarOnVecIntrisic.hlsl, tools/clang/unittests/HLSL/CMakeLists.txt, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/WEXAdapter.h
Fix sundry errors and warnings that only show up on Unix systems.
Exclude unsupported features such as Dia. Provide functional
alternatives for windows-specific methods and strings.
Removed a lot of unused code. Change some capitalization to match
the files sought. Minimal changes for gtest support.
=> [linux-port] Enable CompilerTest for Unix

tools/clang/tools/dotnetc/EditorForm.cs
This change fixes a crash in dndxc when clicking on "Interactive Editor" or "Run Passes" button under the Optimizer tab without entering valid hlsl source text.
=> Fix crash in dndxc

docs/DxcOnUnix.rst
Now we can run a large portion of them on Linux & macOS.
=> [linux-port] Update on HLSL/DXIL test suite

lib/Support/DynamicLibrary.cpp
This causes problems on GCC 6. To compile the existing code,
-fpermissive is needed.
Copied the new implementation from newer version of LLVM.
=> [linux-port] Fix mising cast from const void* to void* in macro

tools/clang/lib/SPIRV/SPIRVEmitter.cpp
Fixes the unimplemented feature which was exposed via the latest builtin type changes.
=> [spirv] Reuse existing function to find bitwidth

include/dxc/Support/microcom.h, lib/DxcSupport/FileIOHelper.cpp, tools/clang/unittests/HLSL/CompilationResult.h, tools/clang/unittests/HLSL/HlslTestUtils.h
llvm::sys::Atomic* was removed in upstream llvm.
=> Use std::atomic.

tools/clang/include/clang/Basic/Version.h, tools/clang/include/clang/SPIRV/Structure.h, tools/clang/lib/Basic/CMakeLists.txt, tools/clang/lib/Basic/Version.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/Structure.cpp, tools/clang/test/CodeGenSPIRV/spirv.debug.commit.hlsl, tools/clang/tools/dxcompiler/CMakeLists.txt, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/tools/dxcompiler/dxcvalidator.cpp, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp, utils/GetCommitInfo.py
If targeting Vulkan 1.1 & requesting debug information with -Zi,
two new OpModuleProcessed instruction will be emitted to contain
"dxc-commit-hash" & "dxc-commit-count".
=> [spirv] Emit Git commit info when debug information requested

docs/SPIR-V.rst, include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/SPIRV/EmitSPIRVOptions.h, tools/clang/include/clang/SPIRV/Structure.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/Structure.cpp, tools/clang/test/CodeGenSPIRV/spirv.debug.ctrl.file.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.ctrl.line.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.ctrl.source.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.ctrl.tool.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.ctrl.unknown.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp, tools/clang/unittests/SPIRV/StructureTest.cpp
Added a new command-line option: -fspv-debug=<category>, where
category can be file, source, line, and tool, to give developers
fine-grained control of what debug information they want in
the generated SPIR-V code.
=> [spirv] Add mechanism for fine-grained control of debug info

tools/clang/include/clang/AST/Stmt.h, tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/include/clang/Basic/LangOptions.h, tools/clang/include/clang/Basic/TypeTraits.h, tools/clang/include/clang/Sema/SemaHLSL.h, tools/clang/lib/AST/ASTDumper.cpp, tools/clang/lib/AST/ExprConstant.cpp, tools/clang/lib/AST/ItaniumMangle.cpp, tools/clang/lib/AST/StmtPrinter.cpp, tools/clang/lib/Basic/LangOptions.cpp, tools/clang/lib/Sema/SemaExprMember.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSL/array-length.hlsl, tools/clang/test/HLSL/rewriter/array-length-rw.hlsl, tools/clang/test/HLSL/rewriter/correct_rewrites/array-length-rw_gold.hlsl, tools/clang/unittests/HLSL/RewriterTest.cpp, tools/clang/unittests/HLSL/VerifierTest.cpp
The FXC compiler supports Length property on arrays. This change adds it
to the DXC compiler for backwards compatibility. However, it is marked
obsolete and will be removed in future versions of HLSL.
=> Implement Length property on constant arrays (FXC regression)

tools/clang/lib/SPIRV/Structure.cpp, tools/clang/test/CodeGenSPIRV/spirv.debug.commit.hlsl
The commit hash should suffice to pinpoint in Git history.
=> [spirv] Stop emitting commit count

include/dxc/Support/dxcapi.use.h, lib/Support/CMakeLists.txt
Fixes #1525 
This CL changes dxcapi.use.h back to what it was before the Linux-port work. It does, however, add a snippet into it to redirect FreeLibrary to dlcose, LoadLibraryW to dlopen, and GetProcAddress to dlsym for non-Windows platforms.
=> [linux-port] Do not use llvm DynamicLibrary in dxcapi.use.h

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/quick-test/global-var-write-test05.hlsl
Exclude certain globals which are either HLSL objects or group shared when enabling them for write in /Gec mode.
=> Exclude certain globals when enabling them for write in /Gec mode

tools/clang/tools/libclang/dxcrewriteunused.cpp
Fixes failing RewriterTests
The EnableBackCompatMode flag was not initialized when the compiler was used via DxcRewriter. The flag is new and has been introduced shortly after the DxcRewriter change PR. The tests failures were caused by unfortunate merge timing of the two changes.
=> Propagate EnableBackCompatMode flag in DxcRewriter

tools/clang/unittests/SPIRV/ModuleBuilderTest.cpp
Otherwise, the compiler issues
warning: missing field 'debugInfoFile' initializer [-Wmissing-field-initializers]
=> [spirv] Fix ModuleBuilder initializer waring on Unix systems

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.interlocked-methods.static-error.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
=> [spirv] Error out if static variable is used in interlocked method

tools/clang/tools/dxrfallbackcompiler/dxcdxrfallbackcompiler.cpp, tools/clang/unittests/DxrFallback/test_DxrFallback.cpp
In the interest of getting RS5 DXR compatibility the raytracing samples were upgraded to target shader model 6_3. This, unfortunately, broke the fallback layer. Fixing the fallback layer requires adjusting the fallback compiler to target 6_3. 
This change has been tested+verified working with the fallback layer on all samples on develop-dxr-rs5-preview.
Once this change is in, the plan is for a build of it to be available in a release on the [samples releases page](https://github.com/Microsoft/DirectX-Graphics-Samples/releases).
=> Fix fallback compiler to ensure raytracing samples' compatibility with 6_3 under fallback layer

lib/DxrFallback/CMakeLists.txt
The dependency for this library had a typo, which failed
to add intrinsics_gen as a dependency, leading to spuirous
failures when building with high leveles of concurrency.
=> Fix dependencies for DxrFallback.

lib/Transforms/InstCombine/InstructionCombining.cpp, tools/clang/test/CodeGenHLSL/quick-test/check_inst_combine_phi_with_undef.hlsl
Don't fold a binop into phi having undef values
=> Don't fold a binop into phi having undef values

include/llvm/IR/Value.h
Replacing the tail-recursive function Value::MergeUseLists with an iterative version (used in LLVM  version 8.0.0)
The tail recursive version of the function was causing stack overflow in a large
shader.
=> Replacing recursive Value::MergeUseLists implementation with an iterative one

lib/Transforms/IPO/PassManagerBuilder.cpp, tools/clang/test/CodeGenHLSL/quick-test/resource_cleanup.hlsl
Convergence annotations prevent unused instructions from being removed. Currently, resources used by of those instructions get added to the final DXIL since the instructions don't get removed until after the resources are finalized.
This change adds a DCE after removing convergence annotations and before generating final resources so no unused resources make it to the final DXIL.
=> Properly clean up resources involved in unused convergent values.

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSL/matrix-assignments.hlsl, tools/clang/test/HLSL/vector-assignments.hlsl
The compiler did not report an error when an element in initialization list could not be converted to a target element type. It went though the conversion checks but never reported an error on the clang level. The compiler then crashed in code gen. This commit fixes that.
=> Report error for mismatched types in initialization lists

include/dxc/HLSL/HLOperationLower.h, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/HLOperationLower.cpp
Fix crash caused by NonUniformSet being invalidated before use 
- Instead of using NonUniformSet, defer lowering of
NonUniformResourceIndex until last, then mark all GEPs that use
the incoming value (including ones not marked as non-uniform,
to conform with previous behavior).
=> Fix #1629 - crash when using NonUniformResourceIndex

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/CodeGenHLSL/quick-test/lower-memcpy-gep-test.hlsl
Allow lower memcpy if gep is only used for memcpy's dest address
=> Fix lower memcpy for nested struct with single element

lib/DxcSupport/FileIOHelper.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/DxcTestUtils.cpp, tools/clang/unittests/HLSL/DxcTestUtils.h
- Prevent needless conversion of empty file to UTF-16, failing due to unexpected file size.
- Add validating test.
Addresses #861
=> Fixed failure on including empty files, and added test.

include/llvm/IR/Module.h, lib/DXIL/DxilModule.cpp, lib/HLSL/HLModule.cpp, lib/IR/Function.cpp, lib/IR/Globals.cpp
- Use one callback for global removal - Function and GlobalValue use this
- Share callback for HLModule and DxilModule, transfer is handled by
setting callback on construction and checking pointer before clearing
=> Fix remaining HLModule/DxilModule dependencies from llvm::Module, etc.

include/dxc/DxilRootSignature/DxilRootSignature.h, tools/clang/include/clang/Parse/ParseHLSL.h, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Frontend/FrontendActions.cpp, tools/clang/lib/Parse/HLSLRootSignature.cpp, tools/clang/lib/Parse/HLSLRootSignature.h, tools/clang/test/CodeGenHLSL/quick-test/subobjects.hlsl, tools/clang/unittests/HLSL/FunctionTest.cpp, utils/hct/hcttestcmds.cmd
- Add LOCAL_ROOT_SIGNATURE flag in RootFlags
- Add DESCRIPTORS_STATIC_KEEPING_BUFFER_BOUNDS_CHECKS flag in DescriptorTable
- New DxilRootSignatureCompilationFlags argument on Compile/ParseRootSignature to specify whether the root signature is local or global.
=> Add root signature flags

tools/clang/tools/dxc/dxc.cpp, utils/hct/hcttestcmds.cmd
The include paths were not piped as preprocessor command args.
Fixes #1636
=> Added support for custom include paths when compiling with /P

lib/DXIL/DxilModule.cpp, tools/clang/include/clang/Parse/Parser.h, tools/clang/lib/Parse/ParsePragma.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
- DxilModule was not freed
- PragmaMatrixHandler was freed twice when the compiler execution was aborted prematurely by an exception
- Improve diagnostic tracing in CompilerTest::CompileWhenNoMemThenOOM
=> Fix memory allocation issues

tools/clang/lib/CodeGen/CGLoopInfo.cpp, tools/clang/lib/CodeGen/CGLoopInfo.h, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSL/rewriter/attributes_noerr.hlsl, tools/clang/test/HLSL/rewriter/correct_rewrites/attributes_gold.hlsl
DXC internally used an unroll count of zero to represent no unrolling, so it encoded `[unroll]` as an unroll count of 1 to not lose the information. However, in HLSL the former represents full unrolling while the latter represents generating only the first iteration of the loop. This change ensures that we can internally distinguish between `[unroll]` and `[unroll(1)]`, by making `[unroll]` equivalent to `[unroll(0)]`, like FXC does. Modified a rewriter test to verify this (we can't test codegen yet due to #1534).
Fixes #1533
=> Fixed [unroll] being interpreted as [unroll(1)].

include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/test/CodeGenHLSL/quick-test/MinimalTraverseShaderLib-pp.hlsl, tools/clang/test/CodeGenSPIRV/spirv.opt.with-O4.cl.oconfig.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
This was a merely cosmetic issue, /O4 is unrecognized and ignored by the compiler.
Fixes #661
=> Remove unsupported /O4 option from help text.

include/dxc/DXIL/DxilConstants.h, include/dxc/DXIL/DxilSubobject.h, include/dxc/DxilContainer/DxilRuntimeReflection.h, lib/DXIL/DxilMetadataHelper.cpp, lib/DXIL/DxilSubobject.cpp, lib/DxilContainer/DxilContainerAssembler.cpp, lib/DxilContainer/DxilContainerReader.cpp, tools/clang/include/clang/AST/HlslTypes.h, tools/clang/lib/AST/HlslTypes.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/quick-test/subobjects.hlsl, tools/clang/test/HLSL/subobjects-syntax.hlsl, tools/clang/tools/dxcompiler/dxcdisassembler.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
- Replace HitGroup subobject by TriangleHitGroup and ProcedurePrimitiveHitGroup
- Add internal HitGroupType enum that maps to D3D12_HIT_GROUP_TYPE
- Add corresponding HitGroupType field to metadata, RDAT and reflection
=> HitGroup subobject changes

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/test/CodeGenSPIRV/spirv.interface.alias-builtin.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
This behavior is supported by FXC.
Fixes https://github.com/Microsoft/DirectXShaderCompiler/issues/1690
=> [spirv] Allow aliasing builtin variables

tools/clang/test/CodeGenHLSL/fpexcept.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
We were crashing while constant folding in `CGHLSLMS.TryEvalIntrinsic` when libc functions cause floating-point exceptions and the compiler caller had enabled floating-point exceptions.
I really wanted to use the standard `<cfenv>` header, but `feholdexceptions` and `fesetround` somehow had no impact on the floating-point environment, as seen by checking the x87/xmm registers before and after, so I had to use non-standard `_controlfp_s`, which makes this fix Windows-specific.
Fixes #1607
=> Set default floating-point environment at compiler boundaries

include/dxc/DXIL/DxilModule.h, include/dxc/DxilContainer/DxilContainerReader.h, include/dxc/DxilContainer/DxilRuntimeReflection.h, include/dxc/DxilContainer/DxilRuntimeReflection.inl, lib/Analysis/ReducibilityAnalysis.cpp, lib/DXIL/DxilModule.cpp, lib/DXIL/DxilSubobject.cpp, lib/DxilContainer/DxilContainerAssembler.cpp, lib/DxilContainer/DxilContainerReader.cpp, lib/HLSL/DxilValidation.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/quick-test/subobjects.hlsl, tools/clang/tools/dxcompiler/dxcdisassembler.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
- re-serialize module when changed by removing either subobjects or
root signature metadata
- improve error detection/handling for loading/creating subobjects
- load subobjects from RDAT if not in DxilModule for RDAT comparison
- fix subobjects missing from desc in DxilRuntimeReflection
- default ReducibilityAnalysis to pass so it doesn't fail when no
functions are present
- report error on subobject if validator (< 1.4) will not accept
them, so they will not be captured
- container validation for required/disallowed parts for libraries
=> Fix Validation for RDAT and other issues with Subobjects

include/dxc/DXIL/DxilSubobject.h, include/dxc/DxilContainer/DxilRuntimeReflection.inl, lib/DXIL/DxilSubobject.cpp
DxilSubobject:
- combine string and raw bytes storage in m_BytesStorage
- use StringRef as key, since memcmp is used with explicit length
DxilRuntimeReflection:
- add m_BytesMap for local unique copy of raw bytes in RDAT
to prevent pointing into RDAT blob for root sig
- clean up some insertion patterns
=> Fix subobject raw bytes storage; don't point into RDAT for reflection

lib/HLSL/HLMatrixLowerPass.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/quick-test/global-var-write-test01.hlsl
- An earlier bitcast would create an unused GEP instruction referencing the matrix, which the matrix lowering code couldn't handle. Removed that GEP.
- `float1x1` was special-cased as if we lowered it to `[1 x float]`, but that's not the case, it gets lowered to `[1 x <1 x float>]`, so the more general code applies.
Fixes #1530
=> Fix crash when assigning to global matrix in compat mode

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/quick-test/static_method.hlsl
We were unconditionally trying to manipulate the `this` pointer.
Also added a simple test.
Fixes #1711
=> Fixed crash when static methods are used.

lib/HLSL/HLMatrixLowerPass.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/CodeGen/CodeGenModule.cpp, tools/clang/test/CodeGenHLSL/quick-test/global-var-no-init.hlsl, tools/clang/test/CodeGenHLSL/quick-test/global-var-write-test03.hlsl, tools/clang/test/CodeGenHLSL/quick-test/global-var-write-test04.hlsl, tools/clang/test/CodeGenHLSL/quick-test/incomp_array.hlsl
Per LLVM rules, globals must be initialized unless they have external linkage. It makes sense to consider constant buffer values as having external linkage, since they are "linked in" by the application, so this change:
- Changes CBuffer globals to have external linkage
- Fixes a few cases not handling the lack of initializers properly
- Fixes some tests which were testing for initialization
- Added a test for non-initialization of cbuffer-promoted globals
=> Changed cbuffer-promoted global vars to have external linkage as to not have initializers

lib/DXIL/DxilModule.cpp
`DxilModule::GetTessellatorPartitioning` didn't follow the model of other methods of returning `Undefined` when it does not apply to the shader stage and would assert.
Introduced by pull request #1704
=> Fix assert following reflection changes.

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp
This change adds a barycentric execution test. Note that there will be tiers introduced for barycentrics support for preserving provoking vertex, and this test only tests SV_Barycentrics value. Once tier is introduced, we should add a new test for GetAttributeAtVertex to keep provoking vertex ordering.
=> Barycentrics support execution test

include/llvm/IR/ValueMap.h
The function is not actually used so VC++ lazily avoids reporting an error, but GCC does.
Mimicked the fix in the official LLVM repo and omitted `// HLSL Change` to simplify merging:
https://github.com/llvm-mirror/llvm/commit/81361659c523e6cef9cd66046334fe46619b9c00#diff-6daed8fde4789051cc55875ce87080b4
Fixes #1692
=> Fix implicit unique_ptr to bool conversion error when compiling with GCC.

include/dxc/DXIL/DxilMetadataHelper.h, include/dxc/DXIL/DxilModule.h, include/dxc/HLSL/DxilSpanAllocator.h, include/dxc/HLSL/HLModule.h, include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DXIL/DxilMetadataHelper.cpp, lib/DXIL/DxilModule.cpp, lib/DXIL/DxilResource.cpp, lib/DxcSupport/HLSLOptions.cpp, lib/HLSL/DxilCondenseResources.cpp, lib/HLSL/DxilContainerReflection.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilPatchShaderRecordBindings.cpp, lib/HLSL/DxilPreparePasses.cpp, lib/HLSL/HLModule.cpp, lib/Transforms/IPO/GlobalDCE.cpp, tools/clang/include/clang/Frontend/CodeGenOptions.h, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/quick-test/resource_binding_fxccompat_arrays_sm50.hlsl, tools/clang/test/CodeGenHLSL/quick-test/resource_binding_fxccompat_arrays_sm51.hlsl, tools/clang/test/CodeGenHLSL/quick-test/resource_binding_fxccompat_sm50.hlsl, tools/clang/test/CodeGenHLSL/quick-test/resource_binding_fxccompat_sm50_no_unbounded.hlsl, tools/clang/test/CodeGenHLSL/quick-test/resource_binding_fxccompat_sm51.hlsl, tools/clang/tools/dxc/dxc.cpp, tools/clang/tools/dxcompiler/dxcdisassembler.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/OptimizerTest.cpp
- Added front-end `-flegacy-resource-reservations` to control behavior (added automatically for SM <= 5.0)
- Added a mechanism for `DxilModule` to preserve intermediate options during its passes but not in the final DXIL
- Changed `HLModule` to not remove unreferenced `DxilResources` but rather make their symbol UndefValue
- Fixed assumptions of `DxilResources` having a valid `GlobalVariable`
- Added reserved resource range gather pass before elimination of unused resources (if SM <= 5.0)
- Changed resource allocation to account for reserved ranges
Fixes #1660
=> Added support for pre-SM5.1 resource allocation algorithm

tools/clang/lib/AST/ASTContextHLSL.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/quick-test/builtin_types_no_inheritance.hlsl
=> Mark built-in types as 'final' to prevent inheritance.

external/CMakeLists.txt
Before adding subdirectories, detect the existence of these external libraries first.
=> Skip external libraries if they are already included in parent project

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/quick-test/matrix_orientation_preserved_with_typedef.hlsl
The code attempted to cast a `QualType` to an `AttributedType`, which would fail if it was in fact a `TypedefType`. Better use the existing helper function we have.
Fixes #1647
=> Fix row_major being lost through typedefs.

tools/clang/tools/dxc/dxc.cpp
It was done to improve the compile time, but it does not seem to be
better.  The use of `HEAP_NO_SERIALIZE` turns off the
low-fragmenataion-heap, which is what we want for this application.
See https://github.com/Microsoft/DirectXShaderCompiler/pull/1712 for a
discussion.
=> Remove use of `NoSerializeHeapMalloc` mem manager.

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/intrinsics.mad.hlsl
According to the [GLSL extended instruction set reference](https://www.khronos.org/registry/spir-v/specs/1.0/GLSL.std.450.html), using Fma without NoContraction decoration does not guarantee usage of precise single-instruction multiply-add hardware. So also added this decoration.
=> [spirv] Support non-fp MAD intrinsic function.

tools/clang/lib/Basic/DiagnosticIDs.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
I got bothered by always hitting this failure and investigated. It turns out that this is a regression in the VC++ STL implementation, but there's a simple workaround. See code comments for description. I'm following up with the compiler guys to report it. I've also re-enabled the appveyor test.
Fixes #1464
=> Fix CompileWhenNoMemThenOOM  test failure

lib/HLSL/HLOperationLower.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/quick-test/texture_of_array_error.hlsl, tools/clang/test/CodeGenHLSL/quick-test/texture_of_matrix_error.hlsl, tools/clang/test/CodeGenHLSL/quick-test/texture_of_struct_error.hlsl
For structs and arrays, this matches FXC's behavior. For matrices, FXC accepts it if the number of elements is <= 4 and reports an error otherwise. DXC also accepted it but would crash if the number of elements was > 4. After this change, DXC will reject textures of matrices, regardless of the number of elements.
Fixes #1695
=> Prevent texture of structs/matrices/arrays, and don't crash

lib/HLSL/HLMatrixLowerPass.cpp, lib/HLSL/HLOperationLower.cpp, tools/clang/test/CodeGenHLSL/quick-test/bool_matrix_cbuflegacy_conversion.hlsl, tools/clang/test/CodeGenHLSL/quick-test/bool_matrix_conversion.hlsl
The matrix lowering code special-cased bools and converted from i32s using `CmpEQ(%bool,0)` instead of `CmpNE(%bool,0)` in a few places. This change fixes it, where possible by leveraging `MemToReg` to remove the special cases.
Fixes #1740
=> Fix invalid CmpEQ(%bool,0) for converting bools

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/CodeGenHLSL/quick-test/sroa_memcpy_from_cbuf_nested_field.hlsl
There was already code to detect `memcpy` with `cbuffer` sources, but they only accounted for one level of GEP indirection. In the presence of complex nested structs and arrays, this might not be the case, so I extended it to support arbitrary GEP nesting.
Fixes #1737
=> Fix SROA bug when lowering a memcpy whose source is a cbuffer

tools/clang/lib/CodeGen/CGDecl.cpp
Fixes #1705
- Declare of arg variable would point to non-pointer value, which was not
legal llvm.
- This change fixes that, but SROA_HLSL will be unable to find the arg's
debug info in certain cases.  That code has to be changed anyways,
so that fix needs to come in a later change.
=> Fix debug info for arguments in EmitParmDecl during CodeGen

tools/clang/include/clang/Sema/DeclSpec.h, tools/clang/include/clang/Sema/Sema.h, tools/clang/lib/CodeGen/CGCall.cpp, tools/clang/lib/Parse/ParseDecl.cpp, tools/clang/lib/Sema/SemaType.cpp, tools/clang/test/CodeGenHLSL/quick-test/test_matrix_orientation_matrix_ret_type.hlsl, tools/clang/test/CodeGenHLSL/quick-test/test_matrix_orientation_matrix_ret_type_multiple_calls.hlsl, tools/clang/test/CodeGenHLSL/quick-test/test_matrix_orientation_matrix_ret_type_with_branches.hlsl, tools/clang/test/CodeGenHLSL/quick-test/test_matrix_orientation_matrix_ret_type_with_branches_ast.hlsl
- Adds matrix orientation attribute (at AST-level) in the return type of a function returning a matrix.
- Adds default matrix orientation field in `DeclSpec`.
=> Add matrix orientation attribute in return type

include/dxc/DXIL/DxilUtil.h, lib/DXIL/DxilUtil.cpp
`llvm::Twine`s are dangerous. When concatenated, they store a pointer to their operands to defer the actual string concatenation as long as possible. Hence every `Twine` being concatenated must be kept alive. `FormatMessageWithoutLocation` took a twine by value, concatenated, and returned the result. This means that the concatenation pointed to the by-value argument, which gets destroyed when the function returns.
=> Fix use-after-free due to by-value Twine parameters.

lib/HLSL/DxilGenerationPass.cpp, tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/quick-test/rawbufferloadstore_64bit_6_2.hlsl, tools/clang/test/CodeGenHLSL/quick-test/rawbufferloadstore_64bit_6_3.hlsl, tools/clang/test/HLSL/intrinsic-examples.hlsl
Enable RawBufferLoad/RawBufferStore for 64-bit vectors bigger than 16 bytes
Add tests to verify correct 64-bit rawBufferLoad/Store is generated.
Verify that for model shader 6.2 the 64bit load/store is split into two 32-bit load/store instructions.
Fix buffer indexing bug when splitting 64-bit load/store.
=> Enable RawBufferLoad/RawBufferStore for 64-bit vectors bigger than 16 bytes

tools/clang/unittests/HLSL/DxcTestUtils.h, tools/clang/unittests/HLSL/FileCheckerTest.cpp
Other parts of LLVM have this feature of the filecheck framework allowing expected failures to be declared such that the test will succeed if and only if the filecheck fails. This is not quite equivalent to CHECK-NOT, because it allows us to write a test with CHECKs for the expected correct output and specifically mark them as currently being broken. I have a bunch of tests demonstrating compiler bugs which I want to check in using this feature in a future PR.
=> Implement XFail for HLSL unit tests.

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/CodeGenHLSL/quick-test/semantics_conflict_warning.hlsl, tools/clang/test/CodeGenHLSL/quick-test/semantics_conflict_warning_return_struct.hlsl, tools/clang/test/CodeGenHLSL/quick-test/semantics_duplicate_param_error.hlsl, tools/clang/test/CodeGenHLSL/quick-test/semantics_duplicate_struct_error.hlsl
This mainly fixes a crash with this code:
```
struct Input { float a : TEXCOORD0; float b : TEXCOORD0; };
float main(Input input) : SV_Target { return 1; }
```
The crash happened because of our strategy for handling this:
```
struct Input { float a; float b; };
float main(Input input : TEXCOORD0) : SV_Target { return 1; }
```
When expanding `Input`, we would label every field with the original semantic, so we would end up with two parameters annotated `TEXCOORD0`, we would then run a pass on all adjacent `TEXCOORD0` parameters and change them to properly number them. However, this couldn't detect the situation in my original snippet, where we have two 'TEXCOORD0' in a row that are not the expansion of a struct marked with that semantic. It incorrectly attempted to renumber `b` in a way …
=> Improve handling of semantics through SROA

tools/clang/lib/Sema/SemaType.cpp, tools/clang/test/CodeGenHLSL/quick-test/matrix_orientation_overrides.hlsl
Thanks to Vishal for the fix!
I'm submitting an XFail'ing test for another bug that would previously crash due to this issue, so it works as a regression test at the same time (XFail won't make a crashing test succeed).
Fixes #1787
=> Fixed crash with #pragma pack_matrix followed by explicit orientation

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
There's some discussion on this issue here:
http://www.cplusplus.com/forum/general/171799/
Clang builds (on Linux and macOS) were not broken. only gcc.
=> [linux-port] Fix gcc build error.

tools/clang/lib/CodeGen/CGStmt.cpp, tools/clang/test/CodeGenHLSL/quick-test/matrix_orientation_output_return.hlsl, tools/clang/test/CodeGenHLSL/quick-test/matrix_orientation_transpose_in_function.hlsl
When storing to the clang-generated temporary variable for the return value, use the matrix type from the return type, not from the return value (which is irrelevant), as to store with the proper orientation.
Fixes #1781 
Fixes #1790
=> Fixed matrices being returned after a store with the wrong orientation

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp
Covers:
- SRV (Load) and UAV buffers (Load, Store)
- declared in root signature as root values and in a descriptor table
- used as [RW]ByteAddressBuffer and [RW]StructuredBuffer
- data types half, float, double, int16_t, int32_t, int64_t,
- scalar type + vectors with 2 to 4 elements
The 16-bit type tests are temporarily disabled because of a bug in WARP
(set to Priority 2 and not run by hcttest).
=> Add rawBufferLoad/rawBufferStore tests for the graphics pipeline

tools/clang/test/CodeGenHLSL/cast_between_type_shapes/array_to_scalar.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/array_to_struct.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/array_to_vector.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/matrix_to_array.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/matrix_to_array_return_vector.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/matrix_to_scalar.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/matrix_to_struct.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/matrix_to_vector.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/scalar_to_array.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/scalar_to_array_return_scalar.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/scalar_to_matrix.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/scalar_to_struct.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/scalar_to_vector.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/struct_to_array.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/struct_to_array_return_vector.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/struct_to_vector.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/vector_to_array.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/vector_to_array_return_vector.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/vector_to_matrix.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/vector_to_scalar.hlsl, tools/clang/test/CodeGenHLSL/cast_between_type_shapes/vector_to_struct.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
Adds tests for all combination of explicit casts between scalar, vector, matrix, array and struct types.
- To-array tests are XFail'ed because of #1808, so I added a variant that doesn't try to directly return the array.
- Array-to-matrix, struct-to-matrix and struct-to-scalar are not included because they crash the compiler (#1799)
- Array-to-vector and struct-to-vector are XFail'ed because of #1795
=> Add a test suite for casting between type shapes

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/CodeGenHLSL/quick-test/streamout_multiple_aggregates.hlsl
When SROA'ing this pattern: `append(struct1, struct2)`, we would generate `append(float, struct2)` when processing `struct1` and add the original call to the list of dead instructions, but it would still be a user of `struct2`, so we would process it a second time when generating the final `append(float, float)`. Not only is this a double-delete, but it's also an `O(n^2)` algorithm. Fixed by `undef`'ing all operands of the original `append` after processing it so that we don't visit it again.
Fixes #1812
=> Fixed double-delete when SROA'ing OutputStream.Append with multiple structs

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/max_min_literal.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
`EvalBinaryIntrinsic` does not support functions with integer arguments, and since min/max do support ints this causes a crash.
The min/max expressions are still evaluated at compile time before optimization even when not handled in `TryEvalIntrinsic`, the same is true for other functions, such as sign(int), which do not appear at all here.
Fixes #1822
=> Do not try to use EvalBinaryIntrinsic for min/max with integer type arguments.

.travis.yml
We let a few build breaks in due to this lately, and it looks like there's agreement that we should flip this on again.
=> Re-enable failures for linux and OSX travis builds.

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/unittests/HLSL/ExtensionTest.cpp
Assert was too strict and would fire when no methods were defined on the original object, but were defined in extended intrinsic tables.
This change initializes output variables, checks the objectName, which indicates whether the object was valid (the main reason for the assert's comment), and allows null intrinsics if m_IntrinsicTables have been defined so they can be searched as well.
=> Fix assert in DeduceTemplateArgumentsForHLSL for extension methods

cmake/modules/FindD3D12.cmake, cmake/modules/FindDiaSDK.cmake
Enable detection of Win10 SDK from environment variable instead of registry
Fix typo
=> Enable detection of Win10 SDK from environment variable instead of registry

tools/clang/unittests/HLSL/CompilerTest.cpp, utils/hct/hcttest.cmd
The `ShaderCompatSuite` and `Unroll` tests randomly supported being used to batch run file-check on directories. This change rather updates `hcttest file-check` to support directories as well as individual files.
=> Support directory paths with hcttest file-check.

.travis.yml
due to issues of Travis `homebrew`, let's see if we can manually get `ninja`
=> [ci] Try to fix Travis osx bot

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/quick-test/implicit_numerical_shape_conversions.hlsl, tools/clang/test/HLSL/binop-dims.hlsl
There was a bogus condition that made this dependent on whether we were truncating vectors/matrices, so later code would unexpectedly get an LValue (llvm pointer) instead of an RValue (llvm value) and crash. Coincidentally it also made strings work... ugh.
Fixes #1844 and #1845
=> Fix conversions not always honoring LValue-to-RValue

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/declarations/functions/overloading/intrinsic_overloading.hlsl, tools/clang/test/CodeGenHLSL/declarations/functions/overloading/intrinsic_shadowing.hlsl, tools/clang/test/CodeGenHLSL/declarations/functions/overloading/namespace_qualified_no_intrinsic_candidate.hlsl
Intrinsics should never be candidates for qualified calls, except global qualifier.
Fixes #1884
=> Fix intrinsics being considered as overload candidates in namespace-qualified calls

lib/DxilPIXPasses/DxilAnnotateWithVirtualRegister.cpp, lib/DxilPIXPasses/DxilDebugInstrumentation.cpp, lib/DxilPIXPasses/DxilPIXVirtualRegisters.cpp, lib/DxilPIXPasses/DxilPIXVirtualRegisters.h, tools/clang/test/CodeGenHLSL/pix/DebugFlowControl.hlsl, tools/clang/tools/dxcompiler/dxcassembler.cpp
This PR modifies the DxilAnnotateWithVirtualRegister pass to also annotate
each instruction in the DXIL module with a unique ID. This ID can then be
used by trace debuggers to uniquely identify an instruction in DXIL module.
This PR also modifies the DxilDebugInstrumentation pass to output this
unique ID on each entry in the debug trace. The debug trace is also expanded
to include the Value Ordinal (i.e., the virtual register modified by the
instruction).
Finally, this PR bundles a small bugfix to the dxassembler. The bug prevented
the DxcAssembler to add the debug DXIL to the container it assembles.
=> [DxilPIXPasses] Assigns unique ID to each instruction.

include/dxc/HLSL/HLModule.h, lib/HLSL/HLMatrixLowerPass.cpp, lib/HLSL/HLModule.cpp, tools/clang/include/clang/AST/HlslTypes.h, tools/clang/lib/AST/HlslTypes.cpp, tools/clang/lib/CodeGen/CGExpr.cpp, tools/clang/lib/CodeGen/CGExprConstant.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/CodeGen/CGHLSLRuntime.cpp, tools/clang/lib/CodeGen/CGHLSLRuntime.h, tools/clang/test/CodeGenHLSL/declarations/bool_representation/const_init_list_no_crash.hlsl, tools/clang/test/CodeGenHLSL/declarations/matrix_pack/static_const_init_list.hlsl, tools/clang/test/CodeGenHLSL/expressions/conversions_and_casts/numerical_const_init_list.hlsl, tools/clang/test/CodeGenHLSL/expressions/conversions_and_casts/numerical_indirect.hlsl, tools/clang/test/CodeGenHLSL/expressions/conversions_and_casts/numerical_matrices.hlsl, tools/clang/test/CodeGenHLSL/quick-test/bool_matrix_conversion.hlsl
Lots of different code in `CGHLSLMS.cpp` did numerical conversions in slightly different ways, most of them forgetting to take into account bools. This change introduces a single `ConvertScalarOrVector` function which handles both and updates code to use it. This implied a partial rewrite of const init list handling code because they lost the `QualType` information necessary to properly cast. They were also not handling register/memory representations properly so I fixed it at the same time.
Fixes #1880 
Fixes #1878 
Adds a test for #1875
=> De-duplicate numerical conversions code

tools/clang/test/CodeGenHLSL/expressions/conversions_and_casts/between_type_shapes.hlsl
Those used to generate code that would fail validation or crash the compiler in different ways, but were presumably fixed by my PR #1876.
Fixes #1861
Related to #1799
=> Reenable tests for casts between type shapes that have been fixed

tools/clang/lib/SPIRV/LiteralTypeVisitor.cpp, tools/clang/test/CodeGenSPIRV/cast.literal-type.array-subscript.hlsl, tools/clang/test/CodeGenSPIRV/cast.literal-type.ternary.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] Fix missing coverage for literal types.

include/dxc/DXIL/DxilUtil.h, include/dxc/HLSL/HLMatrixLowerHelper.h, include/dxc/HLSL/HLMatrixType.h, lib/DXIL/DxilUtil.cpp, lib/HLSL/CMakeLists.txt, lib/HLSL/DxilCondenseResources.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/HLMatrixBitcastLowerPass.cpp, lib/HLSL/HLMatrixLowerPass.cpp, lib/HLSL/HLMatrixSubscriptUseReplacer.cpp, lib/HLSL/HLMatrixSubscriptUseReplacer.h, lib/HLSL/HLMatrixType.cpp, lib/HLSL/HLOperationLower.cpp, lib/HLSL/HLOperationLowerExtension.cpp, lib/HLSL/HLSignatureLower.cpp, lib/Transforms/IPO/PassManagerBuilder.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/RValSubscript.hlsl, tools/clang/test/CodeGenHLSL/staticGlobals.hlsl, tools/clang/test/CodeGenHLSL/static_matrix.hlsl, tools/clang/tools/dxcompiler/dxcdisassembler.cpp
Updates the HLMatrixLower pass logic to eliminate the nondeterminism and randomly bogus codegen that came from iterating over a pointer-keyed map and modification of that map during the iteration. The new approach does a single pass on every instruction consuming or producing matrices, replacing it by its vector equivalent. Any consumed matrix is replaced by a temporary mat-to-vec translation stub, and any formerly produced matrix is emitted as a temporary vec-to-mat translation stub. Stubs get cleared as both ends of a consumer-producer dependency get lowered.
This version is squashed and rebased on the common ancestor between master and 19h1-rel, so it can be merged into both
Fixes #1818
=> Update the HLMatrixLower pass to make it deterministic and correct.

lib/HLSL/HLSignatureLower.cpp, tools/clang/test/CodeGenHLSL/declarations/functions/entrypoints/unused_matrix_input_regression.hlsl
HLMatrixLower asserted that all matrix parameters had a single use, instead of also allowing them to be unused.
Fixes #1947
=> Fixed a crash on unused matrix inputs

tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/lib/Sema/SemaChecking.cpp, tools/clang/test/HLSL/array-index-out-of-bounds.hlsl, tools/clang/unittests/HLSL/VerifierTest.cpp
Out-of-bound array indices cause SROA to generate `undef` values. If returning that value, the finalize dxil pass will get rid of the `storeOutput`. See issue #1879 
We do produce a warning on out-of-bounds errors, but FXC makes it an error and that's probably sensible due to the cascading effects of such `undefs`. We can only do that on constant expressions though, so the `undef` scenario can still happen for constant-valued indices resulting from later IR passes.
=> Added an error for constant array indices being out of bounds.

include/dxc/HLSL/DxilGenerationPass.h, lib/HLSL/DxcOptimizer.cpp, lib/HLSL/DxilPreparePasses.cpp, lib/HLSL/HLOperationLower.cpp, lib/Transforms/IPO/PassManagerBuilder.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/passes/sroa_hlsl/groupshared_array_struct_matrix_regression.hlsl, tools/clang/test/CodeGenHLSL/quick-ll-test/cleanup-addrspacecast.ll, tools/clang/test/CodeGenHLSL/quick-test/addrspace_stress.hlsl, tools/clang/test/CodeGenHLSL/quick-test/addrspacecast.hlsl, tools/clang/test/CodeGenHLSL/quick-test/flat_addrspacecast.hlsl, tools/clang/test/CodeGenHLSL/quick-test/matrix_array_arg_copy_optimized_away.hlsl, tools/clang/test/CodeGenHLSL/quick-test/remove-addrspacecastinst.hlsl, tools/clang/test/CodeGenHLSL/share_mem_dbg.hlsl, utils/hct/hctdb.py
- Add a pass to remove unwanted addrspacecast from final dxil.
- Avoid elementwise matrix copies when orientations match.
(now against the proper target branch!)
=> Additional 19H1 fixes

tools/clang/test/CodeGenHLSL/crashes/equivalent_struct_argument_conversion.hlsl, tools/clang/test/CodeGenHLSL/expressions/conversions_and_casts/identical_layout_structs/explicit_cast_as_out_param.hlsl, tools/clang/test/CodeGenHLSL/expressions/conversions_and_casts/identical_layout_structs/explicit_cast_as_return_val.hlsl, tools/clang/test/CodeGenHLSL/expressions/conversions_and_casts/identical_layout_structs/implicit_cast_as_func_param.hlsl, tools/clang/test/CodeGenHLSL/expressions/conversions_and_casts/identical_layout_structs/implicit_cast_as_func_param_user_scenario.hlsl, tools/clang/test/CodeGenHLSL/expressions/conversions_and_casts/identical_layout_structs/implicit_cast_as_streamout_append.hlsl
It turns out that latest `master` fixes #1725 and #1842. Nevertheless, this PR adds the respective failing scenarios as tests. It also reorganizes existing tests to bring together all tests involving cast between structs of identical layout.
=> Reorg test coverage for cast between structs of identical layout.

tools/clang/test/CodeGenHLSL/crashes/derived_to_base_argument_conversion.hlsl, tools/clang/test/CodeGenHLSL/crashes/matrix_to_aggregate_conversion.hlsl, tools/clang/test/CodeGenHLSL/crashes/run_all.cmd, tools/clang/test/CodeGenHLSL/crashes/static_const_struct_bool_matrix_subscript.hlsl, tools/clang/test/CodeGenHLSL/crashes/struct_truncation_cast.hlsl, tools/clang/test/CodeGenHLSL/declarations/bool_representation/const_init_list_no_crash.hlsl, tools/clang/test/CodeGenHLSL/declarations/groupshared/this_ptr_address_space.hlsl, tools/clang/test/CodeGenHLSL/expressions/argument_passing/aggregates_by_value_semantics.hlsl, tools/clang/test/CodeGenHLSL/expressions/conversions_and_casts/between_type_shapes.hlsl, tools/clang/test/CodeGenHLSL/expressions/conversions_and_casts/derived_to_base_argument.hlsl
Fixes #1835, #1881, #1799 (remaining crash tracked by #1970), removing crash repros
Adds a test for #1843, #1957, and a crash repro for #1970
=> Update tests to reflect new fixes in master

tools/clang/lib/Sema/SemaExpr.cpp, tools/clang/test/CodeGenHLSL/expressions/64bit_integer_literals.hlsl, tools/clang/test/CodeGenHLSL/expressions/conversions_and_casts/numerical_const_init_list.hlsl, tools/clang/test/HLSL/rewriter/correct_rewrites/intrinsic-examples_gold.hlsl, tools/clang/test/HLSL/subobjects-syntax.hlsl
One consequence of this fix is that 0x/0b/0 literals are now considered of the literal int type instead of some unsigned integral type, hence some rewriter output changes.
Fixes #1973
=> Fix non-decimal integer literals being truncated to 32 bits if not suffixed by LL

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/expressions/intrinsics/atan2_const_eval_vs_optims.hlsl
We were evaluating it as `atan(y/x)`, which is incorrect. Note that the `atan2` code in `HLOperationLower` is correct.
Fixes #1928
=> Fix constant evaluation of atan2 intrinsic

include/dxc/DXIL/DxilUtil.h, lib/DXIL/DxilUtil.cpp, lib/HLSL/DxilCondenseResources.cpp, lib/HLSL/HLMatrixBitcastLowerPass.cpp, lib/HLSL/HLSignatureLower.cpp, lib/Transforms/Scalar/SROA.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/tools/dxcompiler/dxcdisassembler.cpp
I added this nice new HLMatrixType, so let's use it! Besides, matrices are not technically part of DXIL.
=> Eliminate dxilutil::IsHLSLMatrixType in favor of HLMatrixType::isa

tools/clang/test/CodeGenHLSL/declarations/functions/recursion/lib_struct_member_unconditional.hlsl
This was reported as a bug by @simontaylor81, but stopped repro'ing only a few commits later, probably as part of the various fixes we merged back into master, so I'm just adding a regression test and calling it good.
Fixes #1943
=> Add a test for recursion in structure members failing validation

lib/DxilContainer/DxilContainerAssembler.cpp, tools/clang/test/CodeGenHLSL/quick-test/sig-bool-as-uint.hlsl
Fix bool mapping to unknown component type in shader signature that can cause PSO signature validation error.
Fixes #1993.
=> Map CompType::Kind::I1 to DxilProgramSigCompType::UIn32

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/declarations/bool_representation/buffer_append_consume.hlsl
Our codegen for Append/Consume is unfortunate because it happens after initial codegen and we don't have access to lots of what would have made this easy. I've had to duplicate the register to memory conversion logic.
Fixes #1882
=> Fix crashes on Append/ConsumeStructuredBuffer of bools

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/lib/SPIRV/CapabilityVisitor.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvModule.cpp
The is a cleanup for the way we add extensions (and capabilities) to the SPIR-V module in memory.
We should only be adding extensions and capabilities in one pass over the SPIR-V IMR. With this PR, CapabilityVisitor is **the only** class that is adding capabilities and extensions. Since CapabilityVisitor is figuring out the extensions&capabilities to add, it should be the one that communicates with FeatureManager. So I've removed FeatureManager from SpirvBuilder.
SpirvBuilder was also keeping a separate set of existing capabilities and extensions to avoid duplicates. This was bad. SpirvModule already has a list of these, and it should be the one making sure there are no duplicates.
=> [spirv] Clean up extension & capability management.

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
Like in the matrix lower case, we were iterating over pointer-keyed maps :(. I wonder if there are more of those hiding in the codebase, the mistake is just too easy to make. No new test since this is nondeterministic behavior.
Fixes #1995
=> Fix nondeterminism in HLSL Parameter SROA

tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/include/clang/SPIRV/SpirvModule.h, tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/lib/SPIRV/SpirvModule.cpp, tools/clang/test/CodeGenSPIRV/literal.constant-composite.hlsl, tools/clang/test/CodeGenSPIRV/literal.unused.hlsl, tools/clang/test/CodeGenSPIRV/literal.vec-times-scalar.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Deducing literal types works by traversing the SPIR-V module in the
reverse order. We were only performing the reverse oreder within
functions, but we should have also reversed the order for SPIR-V
instructions that lay outside of functions. For example: constants,
constant composites, etc.
Before this fix, constants were visited before functions, and therefore
if they had a literal type, it wouldn't be deduced properly.
=> [spirv] Fix handling of literals for constants.

lib/Transforms/Scalar/DxilLoopUnroll.cpp, tools/clang/test/CodeGenHLSL/unroll/intact_child_loops.hlsl, tools/clang/test/CodeGenHLSL/unroll/nested3.hlsl
=> Removing child loops of successfully unrolled loops from queue

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/include/clang/SPIRV/SpirvVisitor.h, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.h, tools/clang/lib/SPIRV/LiteralTypeVisitor.cpp, tools/clang/lib/SPIRV/LiteralTypeVisitor.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvInstruction.cpp
Cleanup for better naming:
This is mainly just renaming the `SpirvComposite` class to `SpirvCompositeConstruct`. Also, the OpConstantComposite and OpSpecConstantComposite are handled by `SpirvConstantComposite` class. so removed any reference to these inside the `SpirvComposite` class.
=> [spirv] (Spec)ConstantComposite are handled by SpirvConstant classes.

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.modf.swizzle.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
The second parameter of modf() intrinsic is an output. This CL
assumes modf() has assignment expression for the second parameter.
Fixes #1741
=> [spirv] Set assignment for second param of modf()

tools/clang/include/clang/SPIRV/SpirvBasicBlock.h, tools/clang/lib/SPIRV/SpirvBasicBlock.cpp, tools/clang/unittests/SPIRV/SpirvBasicBlockTest.cpp
This PR changes the container for instructions inside a basic block.
Instead of a vector, we are going to use a linked list (doubly-linked). We can simply use `llvm::ilist`. This will help when we want to make changes to the SPIR-V module in memory.
=> [spirv] Use llvm::ilist to store instructions in BB.

lib/HLSL/HLModule.cpp, tools/clang/test/CodeGenHLSL/quick-test/namespace-global-debug.hlsl
- Change algorithm to no longer assume that getScope() returns either
DICompileUnit or DISubprogram, searching for the global var in each
compile unit until found instead.
=> Fix crash lowering GlobalVariable when scope is DINamespace

tools/clang/lib/CodeGen/CGDebugInfo.cpp, tools/clang/test/CodeGenHLSL/debug/duplicate_difile_regression.hlsl
When compiling with debug info and passing in a full path, we ended up with a bogus `!DIFile` metadata entry where the path had the drive and directory components twice before the filename. Other code would compute the correct path and create a second `!DIFile` metadata entry.
Apparently we're misusing `CodeGenOptions::MainFileName`, because it should not contain a full path but, due to other code of ours, it seems like a riskier change to fix that because we depend on it in `CodeGeneratorImpl::HandleTranslationUnit`.
=> Fix bogus DIFile debug metadata

lib/HLSL/HLSignatureLower.cpp, lib/IR/DIBuilder.cpp, lib/IR/LegacyPassManager.cpp, lib/Transforms/Scalar/SROA.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, lib/Transforms/Scalar/Scalarizer.cpp, tools/clang/test/CodeGenHLSL/debug/input_vector.hlsl, tools/clang/test/CodeGenHLSL/debug/input_vector_in_struct.hlsl
We were systematically losing input vector debug info because of `HLSignatureLower`, which would replace them by per-element `loadInput` calls and then re-creating the vector through an `insertelement` chain. The `llvm.dbg.value` intrinsic was preserved for the recomposed vector, but this is not the authoritative source of data anymore - its elements are. Further optimizations would read past the insertelements and eventually we'd drop the vector and its debug info. To fix this, I'm now migrating the debug info to the individual vector elements as loaded from `loadInput`.
Also standardized on bitpieceexpression arguments being in bits everywhere, because it was becoming too confusing. The header for createBitPieceExpression had OffsetInBits while the source file had OffsetInBytes and …
=> Fix input vectors not having debug info

lib/HLSL/DxilCondenseResources.cpp, lib/HLSL/DxilPreparePasses.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
Disable CompileWhenNoMemThenOOM when debug iterators are enabled
Note that debug iterators are still disabled in the build by default.
We will do internal runs with debug iterators on to catch these bugs
sooner, but we do not want to enable them by default because it blocks
the OOF memory handling tests CompileWhenNoMemThenOOM.
=> Fix bugs discovered by temporarily enabling debug iterators

tools/clang/lib/CodeGen/CGExprAgg.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/expressions/conversions_and_casts/between_type_shapes.hlsl, tools/clang/test/CodeGenHLSL/expressions/conversions_and_casts/to_aggregate_ignored.hlsl, tools/clang/test/HLSL/conversions-between-type-shapes.hlsl
FXC treats scalars, vector1s and matrix1x1s the same, at least as far as conversions go. We allowed splats from scalars to aggregates, but not from vector1s or matrix1x1s.
Also fixes a bug where we would crash on conversions to aggregates where the result was ignored, because clang wouldn't allocate an `AggValueSlot` and we didn't handle the destination pointer being `nullptr`.
Fixes #1863 and #1978
=> Fix vec1/mat1x1 to aggregate type splats and a crash

tools/clang/lib/CodeGen/CGDebugInfo.cpp, tools/clang/lib/CodeGen/CGDebugInfo.h, tools/clang/test/CodeGenHLSL/debug/vector_members.hlsl, tools/clang/test/CodeGenHLSL/debug/vector_members_bool.hlsl
The clang type we generate for HLSL vectors contains a single field `h` of type `DependentSizedExtVectorType`, which shows up as an `int[4]` in DWARF. This change specifically emits debug info for `x`, `y`, `z` and `w` fields instead.
With this change, we also stop emitting a vector member for `operator[]`, whose implementation was marked "external" so I don't think it'll have any impact.
I thought I could easily do the same for matrices, but I can foresee this being very tricky given how the memory representation varies with the packing order, in constant buffers and with our terrible `rowToCol` intrinsics.
=> Make debug info of HLSL vectors more user friendly

lib/Transforms/Scalar/Scalarizer.cpp, tools/clang/test/CodeGenHLSL/debug/locals/scalarized_vector.hlsl
Fixes some bugs with how the scalarizer emitted debug info:
- It wrongly emitted a non-zero Offset argument, which would cause the intrinsic to get discarded by newer LLVM versions which removed that parameter. (and the offset value it emitted wasn't even correct).
- It didn't take into account the offset of any existing bit piece expressions on the vector.
=> Fix debug info generated by scalarizer.

tools/clang/tools/dxc/dxclib/CMakeLists.txt
Add PUBLIC to dxclib to fix the warning.
=> Fix a cmake warning of policy CMP0023 in dxclib

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/var.init.struct.hlsl
If the "from type" or "to type" for bitwidth conversion is a 'literal type', then we should not perform the bitwidth conversion. The LiteralTypeVisitor should deduce the right type for the literal.
=> [spirv] convertBitwidth should do nothing for literal types.

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp
All usages of `createBinaryOp` overload have already been removed. This change removes the function itself.
=> [spirv] Remove createBinaryOp API which uses SpirvType.

lib/Transforms/Scalar/SROA.cpp
All uses of dead instructions are replaced by `undef` before we have a case for AllocaInst and try to find any `llvm.dbg.declare` intrinsic, so we never find them.
This was fixed in a later LLVM version, see: https://github.com/llvm-mirror/llvm/commit/0e1ce271574ac0f9097000a08f13736c45352ced
=> Fix SROA leaving some llvm.dbg.declare(undef) behind

tools/clang/include/clang/SPIRV/SpirvInstruction.h
It's simply hiding a method declaration and making the code
difficult to read.
=> [spirv] Remove DECLARE_INVOKE_VISITOR_FOR_CLASS macro

tools/clang/lib/SPIRV/InitListHandler.cpp, tools/clang/lib/SPIRV/InitListHandler.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/test/CodeGenSPIRV/cast.flat-conversion.array-to-vector.hlsl, tools/clang/test/CodeGenSPIRV/cast.flat-conversion.struct-to-struct.hlsl, tools/clang/test/CodeGenSPIRV/cast.flat-conversion.struct.hlsl, tools/clang/test/CodeGenSPIRV/cast.flat-conversion.vector.hlsl, tools/clang/test/CodeGenSPIRV/var.init.array.hlsl, tools/clang/test/CodeGenSPIRV/var.init.extvector.hlsl, tools/clang/test/CodeGenSPIRV/var.init.hlsl, tools/clang/test/CodeGenSPIRV/var.init.matrix.1xn.hlsl, tools/clang/test/CodeGenSPIRV/var.init.matrix.mx1.hlsl, tools/clang/test/CodeGenSPIRV/var.init.matrix.mxn.hlsl, tools/clang/test/CodeGenSPIRV/var.init.opaque.hlsl, tools/clang/test/CodeGenSPIRV/var.init.struct.hlsl, tools/clang/test/CodeGenSPIRV/var.init.vec.size.1.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Without this CL, type casting array to vector generates multiple
redundant expressions. For example, type casting array return value
of a function call to vector generates multiple duplicated function
call expressions, which must be actually a single function call. It
is because InitListHandler generates multiple Expr from the same
Expr. This CL updates InitListHandler not to generate redundant Expr.
=> [spirv] Fix type cast array to vector bug

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/expressions/conversions_and_casts/between_type_shapes.hlsl, tools/clang/test/HLSL/conversions-between-type-shapes.hlsl
FXC considers arrays the same as structures for implicit conversions, so `int[2]` should be convertible to `struct { int x; float y; }`, for example.
Fixes #1862
=> Fixed implicit conversions between arrays and structs.

tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/unittests/SPIRV/SpirvConstantTest.cpp
Finishes switching all constant instruction constructors to use QualType rather than SpirvType.
=>  [spirv] Use QualType in constant instruction constructors

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSL/incomplete-type.hlsl, tools/clang/unittests/HLSL/VerifierTest.cpp
Using a forward declared type without a definition may well be illegal, but it shouldn't crash the compiler.
Fixes #2058
=> Fix compiler crash on using incomplete types

tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/lib/Sema/SemaChecking.cpp, tools/clang/test/HLSL/array-index-out-of-bounds-HV-2016.hlsl, tools/clang/test/HLSL/array-index-out-of-bounds.hlsl, tools/clang/unittests/HLSL/VerifierTest.cpp
#1931 added this error, but it was later found to be a breaking change from FXC as FXC would only produce the error if the out-of-bounds error was in a function being referenced somewhere. This change makes the error conditional on the HLSL version for backwards compatibility. With `-HV 2016`, it is only a warning.
=> Make the array out of bounds error conditional on the HLSL version.

tools/clang/test/CodeGenHLSL/debug/types/double.hlsl, tools/clang/test/CodeGenHLSL/debug/types/half.hlsl
Those are pretty trivial tests but we should have coverage for those cases.
=> Add tests for debug info of half and double types (16 and 64-bit).

tools/clang/lib/AST/ASTContext.cpp, tools/clang/lib/CodeGen/CGDebugInfo.cpp, tools/clang/test/CodeGenHLSL/debug/types/resources.hlsl
Two changes in here:
- Hide the resource members in the debug information as they are internal implementation details.
- Force the size of resources to be reported as 32 bits (`sizeof(intptr)`). It's not useful for resources to have a size based on the internal fields we stick in there, it's more useful for backends to be able to expect a fixed resource size, even though what they end up generating might be bigger.
The latter change seems a little riskier, but none of the tests were impacted.
=> Improve debug type information for resources.

include/dxc/DXIL/DxilUtil.h, lib/DXIL/DxilUtil.cpp, lib/HLSL/HLOperationLower.cpp, lib/HLSL/HLSignatureLower.cpp
After loading a vector from a cbuffer, we attempt moving the debug info upstream, to the individually loaded elements, assuming that they got converted into a vector by a sequence of `insertelement` instructions. This is not the case for bool vectors, because the `insertelement` sequence will be followed by a mem-to-reg conversion. Made the code more resilient to such unexpected patterns (better to lose debug info than to crash compilation).
=> Fix an assert on cbuffer loads of bool vectors

docs/DXIL.rst, include/dxc/DXIL/DxilConstants.h, include/dxc/DXIL/DxilSigPoint.inl, include/dxc/HLSL/DxilSignatureAllocator.h, include/dxc/HLSL/DxilSignatureAllocator.inl, lib/HLSL/DxilValidation.cpp, lib/HLSL/HLSignatureLower.cpp, tools/clang/test/CodeGenHLSL/quick-test/pack-clip-cull-opt.hlsl, tools/clang/test/CodeGenHLSL/quick-test/pack-clip-cull-opt2.hlsl, tools/clang/test/CodeGenHLSL/quick-test/pack-clip-cull-opt3.hlsl, tools/clang/test/CodeGenHLSL/quick-test/pack-clip-cull.hlsl, tools/clang/test/CodeGenHLSL/quick-test/pack-clip-cull2.hlsl, tools/clang/test/CodeGenHLSL/quick-test/pack-clip-cull3.hlsl, utils/hct/hctdb.py
- This approach fixes validation and packing to handle this case.
- fix some issues found in packing related to rowsUsed result from Pack
functions.  Make these return 0 on failure, instead of startRow.
- Split PackNext into FindNext and PackNext that uses it for greater
flexibility.
- ensure reserved rows adjacent when multi-row clip/cull element found
and rows already allocated.
- clean/fix up clip/cull allocation code
=> Allow clip/cull elements to be declared as array [2]

tools/clang/lib/SPIRV/AstTypeProbe.cpp, tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/test/CodeGenSPIRV/pragma.pack_matrix.hlsl, tools/clang/test/CodeGenSPIRV/type.matrix.majorness.zpc.hlsl, tools/clang/test/CodeGenSPIRV/type.matrix.majorness.zpr.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
The front-end has taken care of annotating the AST nodes with
the right attribute on QualTypes. We need to read that information
properly and use it in the SPIR-V backend.
=> [spirv] Support for #pragma pack_matrix().

tools/clang/include/clang/SPIRV/AstTypeProbe.h, tools/clang/lib/SPIRV/AstTypeProbe.cpp, tools/clang/lib/SPIRV/InitListHandler.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/cast.no-op.matrix.float-to-int.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Type cast float2x2 to int2x2 causes a validation error when emitting
SPIR-V. This CL fixes it by adding type conversion in InitListHandler.
=> [spirv] fix no-op matrix type cast bug

lib/HLSL/DxilContainerReflection.cpp, tools/clang/test/CodeGenHLSL/batch/misc/d3dreflect/cb_sizes.hlsl, tools/clang/unittests/HLSL/DxilContainerTest.cpp
Used to report next member minus this offset, which would include cb
padding in the size.  This is not correct.
Now we calculate the size based on the packing rules for the type.
- basic types are:
(((elements * rows) - 1) * row stride) + cols * element size
where row stride is 16, or 32 if 64-bit and cols > 2.
- for struct:
struct size = offset of last field + size of last field
struct size += (elements - 1) * 16-byte aligned struct size
Turned on Size check in reflection tests since it should be correct now.
=> Fix CB Var Size reported by reflection

include/dxc/Support/FileIOHelper.h, include/dxc/Support/dxcapi.impl.h, lib/DxcSupport/FileIOHelper.cpp, lib/DxilRootSignature/DxilRootSignatureSerializer.cpp, tools/clang/tools/libclang/dxcrewriteunused.cpp
`DxcCreateBlobOnHeapCopy` allocated using the COM allocator and freed using the default thread allocator, leading to crashes.
But more generally, some `DxcCreateBlob` functions would take ownership of the passed-in buffer without also having the caller explicitly specify what `IMalloc` to use for deallocation, which is an error-prone pattern, so I reworked these methods a bit.
This also lead me to find some memory leaks and general memory mismanagement in the the rewriter.
=> Fix allocator issues for dxc blob allocations

tools/clang/lib/CodeGen/CGExpr.cpp
Fixes llvm assert and debug-only test failure (CodeGenHLSL\batch\misc\emptyStruct.hlsl).
=> Fix empty struct check

tools/clang/tools/dxcompiler/dxcompilerobj.cpp
We declare `CHeapPtr<wchar_t> DebugBlobName;`, where `CHeapPtr` uses the `CCRTAllocator` by default, but initialize it with: `Unicode::UTF8BufferToUTF16ComHeap(pDebugName, &DebugBlobName)`, which uses `CComHeapPtr<wchar_t> p;`
If we don't hit any exceptions, things are fine because we end up doing: `*ppDebugBlobName = DebugBlobName.Detach();` , so the destructor will be a no-op.
=> Fix allocator mismatch with CompileWithDebug output string

include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, lib/DxilContainer/DxilContainerAssembler.cpp, tools/clang/tools/dxc/dxclib/dxc.cpp, tools/clang/tools/dxcompiler/dxcassembler.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/tools/libclang/CMakeLists.txt, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/DxilContainerTest.cpp, tools/clang/unittests/HLSL/LinkerTest.cpp, utils/hct/hcttestcmds.cmd
- New -Qembed_debug is required to embed PDB in shader container
- -Zi used without -Qembed_debug will not embed debug info by
default unless there's no separate debug output location, in which
case it embeds and issues a warning.  This is the case when using
the Compile() method.
- In dxc and CompileWithDebug() -Fd implies -Qstrip_debug
- Debug name is based on -Fd, unless path ends with '\', meaning you
want auto-naming and file written under the specified directory
- Debug name always embedded when debug info used, or -Fd used
- -Fd without -Zi just embeds debug name for CompileWithDebug(),
still error with dxc, since it can't write to your file.
- If not embedding debug info, it doesn't get written to the container,
only to be stripped out again.
- Fix padding for alignment in …
=> Add -Qembed_debug, don't embed debug info by default

include/llvm/ADT/BitVector.h, include/llvm/ADT/SmallVector.h, lib/CodeGen/LiveIntervalUnion.cpp, lib/IR/LegacyPassManager.cpp, lib/Support/SmallPtrSet.cpp, lib/Support/SmallVector.cpp
In a few places, llvm uses `malloc` instead of `operator new`, especially with collections that want to avoid calling constructors. In those cases, the allocation won't go through our custom allocator and will crash rather than throw on out-of-memory conditions. This fixes the biggest offenders.
=> Remove malloc usages in favor of operator new

tools/clang/lib/AST/HlslTypes.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/batch/declarations/resources/norm_floats/assign_different_error.hlsl, tools/clang/test/CodeGenHLSL/batch/declarations/resources/norm_floats/global_struct_field.hlsl, tools/clang/test/CodeGenHLSL/batch/declarations/resources/norm_floats/srv_uav.hlsl
This is a partial solution to preserving `snorm` and `unorm` for `Buffer` and other resource types. In the clang type system, the canonical type of `Buffer<snorm float>` is a `RecordType` for the template specialization, which is `Buffer<float>`, so the information is lost. However, the type of the variable itself has a sugar node of type `TemplateSpecializationType` which provides the exact type arguments that were provided to the template class to select its specialization. Hence we can retrieve the information if we have access to the `VarDecl`'s type.
This is a partial solution, because the `snorm`/`unorm` is still not encoded in the canonical type of the variable, which means that it is still legal to assign resources that differ between their use of the attribute. However, it should …
=> Preserve snorm/unorm on resource template args

include/dxc/DXIL/DxilModule.h, lib/DXIL/DxilModule.cpp, lib/DxilContainer/DxilContainerAssembler.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, utils/hct/hcttestcmds.cmd
-Qstrip_reflect would reserialize the root signature, leading to
validation failure #2162.  Fixed by moving root sig to writer to clear
from module and prevent re-serialization to metadata.
Fixed -Qstrip_debug with -Zi and no output location still embeding
debug module.
Fixes #2162.
=> Fix issues with -Qstrip_reflect and -Qstrip_debug

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/batch/expressions/argument_passing/xvalue_to_rvalue_regression.hlsl, tools/clang/test/CodeGenSPIRV/type.append.consume-structured-buffer.cast.hlsl
In a few places, we used rvalue references as if they meant read-only references, which is not at all their semantics. This change ensures that we never deal with rvalue references, which in any case have no place in HLSL and only introduce weird edge cases, but only with const and non-const lvalue references.
Fixes #2153
Fixes #2152
=> RValue references no more!

lib/DxilPIXPasses/DxilShaderAccessTracking.cpp
Also added a static-assert to help us catch similar issues in future.
=> PIX passes: Add RawBufferStore to shader-access-tracking

lib/Bitcode/Reader/BitcodeReader.cpp, tools/clang/unittests/HLSL/ValidationTest.cpp
We added an exception when the bitcode reader reports an error, however the code higher up in the call stack isn't fully exception-safe and it turns out that two unique_ptrs over the same `MemoryBuffer` are alive at the same time, hence the double-delete and, more often than not, crash.
Tested manually by running `dxc /dumpbin` and forcing an exception to happen. Also later on added a test.
=> Fix double-delete when failing to load llvm bitcode

tools/clang/tools/dxc/dxclib/CMakeLists.txt
Fixes build break on parallel builds
=> Add TablegenHLSLOptions dependency to dxclib

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/HlslTestUtils.h, tools/clang/unittests/HLSL/MSFileSysTest.cpp, tools/clang/unittests/HLSL/ShaderOpTest.cpp
Fixes 2 test bugs and a few razzle build warnings
Removes HlslTestUtils.h dependency on llvm/Support/Atomic.h
Brings it in sync with the HLK version of the tests
=> Bug fixes and minor changes to ExecutionTest

tools/clang/test/CodeGenHLSL/batch/declarations/matrix_pack/preserved_with_typedef.hlsl, tools/clang/test/CodeGenHLSL/batch/declarations/resources/structured_buffers/layout.hlsl, tools/clang/test/CodeGenHLSL/batch/misc/bindings1.hlsl, tools/clang/test/CodeGenHLSL/batch/misc/cbuffer5.51.hlsl, tools/clang/test/CodeGenHLSL/batch/misc/cbuffer6.51.hlsl, tools/clang/test/CodeGenHLSL/batch/misc/cbufferMinPrec.hlsl, tools/clang/test/CodeGenHLSL/cbufferHalf-struct.hlsl, tools/clang/test/CodeGenHLSL/cbufferHalf.hlsl, tools/clang/test/CodeGenHLSL/cbufferInt16-struct.hlsl, tools/clang/test/CodeGenHLSL/cbufferInt16.hlsl, tools/clang/tools/dxcompiler/dxcdisassembler.cpp
We printed:
```
struct structName
{
int fieldName;
} fieldName // No semicolon
```
=> Added missing semicolon in struct layout output

lib/HLSL/HLOperationLower.cpp, tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/batch/declarations/resources/byteaddressbuffers/load_type_shapes_sm60.hlsl, tools/clang/test/CodeGenHLSL/batch/declarations/resources/byteaddressbuffers/load_type_shapes_sm62.hlsl, tools/clang/test/HLSL/intrinsic-examples.hlsl
Implements `[RW]ByteAddressBuffer.Load<T>` for all numerical or aggregate of numerical `T`s, leveraging the same code from `StructuredBuffer<T>.Load`.
It turns out that supporting stores is going to be much more involved, because of a problem similar to #1768 . For stores, we have an intrinsic that has a `Struct*` param, which means that SROA must be able to break it down a per-element intrinsic version. This is especially tricky with arrays of structs and the way they change the layout. It may be that a solution to both of these issues is to generate per-element store/append intrinsics during codegen (with GEPs), such that SROA does not have to handle breaking down those intrinsics.
Related to #1901
=> Add support for generalized templated byte address buffer loads

tools/clang/tools/dxcompiler/CMakeLists.txt
Fixes build break in parallel builds
=> Add TablegenHLSLOptions dependency to dxcompiler

lib/DxilDia/DxilDiaSymbolManager.cpp, lib/DxilDia/DxilDiaSymbolManager.h
Modifies DxilDia's to use factories instead of lambdas to create symbols
DxilDia used to hold a vector of lambdas -- constructors -- for the symbols
it knew about. When the user requested a symbol, said constructor was to be
invoked, creating a brand new symbol.
C++ lambdas can be hard to debug (i.e., how does one inspect the lambda's
state?), so the library is modified to hold a vector of factories -- i.e.,
objects with fields and a CreateSymbol method.
=> DxilDia uses factories (not lambdas) for symbol creation

tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/include/clang/Sema/Sema.h, tools/clang/lib/AST/HlslTypes.cpp, tools/clang/lib/Parse/ParseExpr.cpp, tools/clang/lib/Sema/SemaExpr.cpp, tools/clang/test/CodeGenHLSL/batch/expressions/operators/sizeof.hlsl, tools/clang/test/HLSL/sizeof.hlsl, tools/clang/unittests/HLSL/VerifierTest.cpp
To complement the new `[RW]ByteAddressBuffer.Load/Store<T>` feature, it's useful to have operator sizeof to compute offsets. This supports both type and expression forms of the operator, as in C++. The size returned is consistent with struct layouts in `StructuredBuffer`, but not necessarily with that of constant buffers, which use different rules. Using `sizeof` on resources or aggregates containing resources will result in a compile-time error. It is only supported for "blittable" types.
Supporting `offsetof` is trickier because in C++ it's implemented as a macro in a standard header that's backed by a compiler intrinsic. We might have to make it into an actual operator.
Related to #1291
=> Support operator sizeof

lib/DXIL/DxilModule.cpp, lib/DxilContainer/DxilContainerAssembler.cpp, tools/clang/test/CodeGenHLSL/batch/compiler_options/Qstrip_reflect_lib.hlsl, tools/clang/test/CodeGenHLSL/batch/compiler_options/Qstrip_reflect_subobj.hlsl
Make sure submodule doesn't get re-emitted into metadata.
Strip reflect *BEFORE* writing RDAT, so that the names don't get put into RDAT and fail validation.
Debug info doesn't actually need any value names, as all the names are strings in the debug metadata.
=> Fixed a validation failure with stripping reflect with library shaders.

include/dxc/DXIL/DxilModule.h, lib/DXIL/DxilModule.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
Deleted some old code where we manually delete users of resource GV's while stripping debug modules. This is normally unnecessary but harmless, because we are guaranteed to have reduced all resource variables, and any failure to do so would result in a validation failure. However, library shaders *can* have resource variables. Removing the instructions here would result in incorrect code.
=> Fixed a bug where necessary code gets deleted with library shaders.

docs/SPIR-V.rst, tools/clang/include/clang/Basic/Attr.td, tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/include/clang/Sema/AttributeList.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenSPIRV/vk.attribute.error.hlsl, tools/clang/test/CodeGenSPIRV/vk.attribute.invalid.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.shader-record-nv.std430.hlsl, tools/clang/test/CodeGenSPIRV/vk.shader-record-nv.hlsl, tools/clang/test/CodeGenSPIRV/vk.shader-record-nv.offset.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
@ehsannas 
Please review fix for issue #2019 
Tests have been added along with documentation update.
Thanks
=> [spirv] Add support for [[vk::shader_record_nv]]

utils/hct/hctgettaef.py
Python 2 was dropped from the project, but this utility still required it.
=> hctgettaef: Update for Python 3

include/dxc/DxilContainer/DxilContainer.h, lib/DxcSupport/HLSLOptions.cpp, lib/DxilContainer/DxilContainerAssembler.cpp, lib/HLSL/DxilValidation.cpp, tools/clang/test/CodeGenHLSL/container/ShaderHash.hlsl, tools/clang/tools/dxcompiler/dxcdisassembler.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/DxilContainerTest.cpp
Includes minor behavior changes regarding debug name/hashing:
1. Default to hashing shader module rather than debug module, so separate compilation for debug version can match by default, without having to include special flags.
2. Produce debug name and hash when using -Zsb, even without -Zi or -Fd
=> Add shader hash blob part

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/test/CodeGenSPIRV/cs.groupshared.function-param.hlsl, tools/clang/test/CodeGenSPIRV/cs.groupshared.function-param.out.hlsl, tools/clang/test/CodeGenSPIRV/cs.groupshared.struct-function.hlsl, tools/clang/test/CodeGenSPIRV/decoration.no-contraction.hlsl, tools/clang/test/CodeGenSPIRV/fn.call.hlsl, tools/clang/test/CodeGenSPIRV/fn.ctbuffer.hlsl, tools/clang/test/CodeGenSPIRV/fn.param.inout.storage-class.hlsl, tools/clang/test/CodeGenSPIRV/fn.param.inout.vector.hlsl, tools/clang/test/CodeGenSPIRV/fn.param.isomorphism.hlsl, tools/clang/test/CodeGenSPIRV/oo.method.on-static-var.hlsl, tools/clang/test/CodeGenSPIRV/oo.struct.method.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp, tools/clang/unittests/SPIRV/FileTestFixture.cpp, tools/clang/unittests/SPIRV/FileTestFixture.h, tools/clang/unittests/SPIRV/FileTestUtils.cpp, tools/clang/unittests/SPIRV/FileTestUtils.h, tools/clang/unittests/SPIRV/WholeFileTestFixture.cpp
Previously, when passing a variable whose scope is not Function,
DXC creates a temporal variable with Function scope and copies
the value of the variable to the temporal one. It produces legal
SPIR-V code but it causes unnecessary loads / stores if the
function is inlined by spirv-opt.
This commit decouples argument scope from call-by-value
decision to avoid creation/load/store of temporal variables.
This generates illegal SPIR-V code but spirv-opt HLSL
legalization handles it.
Related to #1977
=> [spirv] decouple argument scope from call-by-value decision

cmake/modules/HandleLLVMOptions.cmake, include/dxc/Support/Global.h, include/dxc/Support/WinAdapter.h, include/dxc/dxcapi.h, lib/DxcSupport/HLSLOptions.cpp, lib/DxcSupport/dxcmem.cpp, tools/clang/lib/CodeGen/CMakeLists.txt, tools/clang/tools/dxcompiler/dxcapi.cpp, tools/clang/unittests/HLSL/CMakeLists.txt
Using the -fvisibility=hidden by default only exposes symbols that have
the __attribute__((visibility("default"))) attribute applied to them.
There are only a couple of functions that are meant to be exposed from
libdxcompiler. To expose the proper functions, the macros used to create
the UUIDs for class types are redefined with the attribute and
DXC_API_IMPORT is defined with the attribute above for non-windows
platforms.
Since we're hiding everything now, the portions that were explicitly
hidden to make MacOS work are removed.
This exposed a number of missing dependencies of libraries and unit
tests. Namely clang-hlsl-tests, clang-spirv-tests, and libclangCodeGen.
Resolves #2203
=> Hide Unix symbols by default

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/vk.spec-constant.init.hlsl, tools/clang/test/CodeGenSPIRV/vk.spec-constant.usage.hlsl
=> [spirv] Add OpName for specialization constants.

utils/hct/hctstart.cmd
Look for Python 3 instead of Python 2 if python.exe is not already on the path.
=> hctstart.cmd - Look for Python 3 instead of Python 2

include/dxc/dxcisense.h, tools/clang/lib/Frontend/ASTUnit.cpp, tools/clang/tools/libclang/CIndexCodeCompletion.cpp, tools/clang/tools/libclang/dxcisenseimpl.cpp, tools/clang/tools/libclang/dxcisenseimpl.h, tools/clang/unittests/HLSL/DXIsenseTest.cpp, tools/clang/unittests/HLSL/WEXAdapter.h
I've made a start on extending the existing IntelliSense support by exposing code completion APIs.
There's still a lot to do, but I've hit an early obstacle, which I'm hoping somebody more experienced with the codebase can maybe help me with!
I've added a new `DXIntellisenseTest` test called `CompletionWhenResultsAvailable`. This test calls `DxcTranslationUnit::CodeCompleteAt`, which eventually crashes on this line in `DXCompiler.cpp` because `DxcGetThreadMallocNoRef()` returns a `nullptr`:
``` cpp
return DxcGetThreadMallocNoRef()->Alloc(size);
```
I've looked at the other functions in `DxcTranslationUnit`, and I think I'm doing the same thing they are with this code:
``` cpp
DxcThreadMalloc TM(m_pMalloc);
```
What am I missing?
=> Expose code completion API

tools/clang/lib/SPIRV/SpirvEmitter.cpp
We should have the same decision for HLSL legalization of spirv-opt
and --before-hlsl-legalization option of spirv-val.
=> [spirv] same variable for legalization and before-hlsl-legal

include/llvm/InitializePasses.h, include/llvm/Transforms/Scalar.h, lib/HLSL/DxcOptimizer.cpp, lib/Transforms/IPO/PassManagerBuilder.cpp, lib/Transforms/Scalar/DxilLoopUnroll.cpp, tools/clang/test/CodeGenHLSL/batch/declarations/precise/matrix.hlsl, tools/clang/test/CodeGenHLSL/batch/unroll/big_step.hlsl, tools/clang/test/CodeGenHLSL/batch/unroll/big_step_non_trivial.hlsl, tools/clang/test/CodeGenHLSL/batch/unroll/fail.hlsl, tools/clang/test/CodeGenHLSL/batch/unroll/large_count.hlsl, tools/clang/test/CodeGenHLSL/batch/unroll/warning.hlsl, utils/hct/hctdb.py
Using Scalar Evolution to figure out trivial loop trip count, but it needs Mem2reg to have been done, so we can't just run promote allocas as part of the unroll pass.
This change adds a pass to conditionally run m2r on functions that have loops that need to be unrolled when Od option is used.
=> Loop count for all trivial form loops. Mem2Reg only when necessary.

include/dxc/dxcisense.h, tools/clang/tools/libclang/dxcisenseimpl.cpp, tools/clang/tools/libclang/dxcisenseimpl.h, tools/clang/unittests/HLSL/DXIsenseTest.cpp
Add `IDxcSourceLocation::GetPresumedLocation` as a wrapper for `clang_getPresumedLocation`.
This is important for (e.g.) showing errors in the correct location in IDEs when the `#line` directive is used, primarily in generated code.
=> Add IDxcSourceLocation::GetPresumedLocation

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/GlPerVertex.cpp, tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp
This change results in better handling of storage classes. This is useful for when we want to implement the templated Load/Store for (RW)ByteAddressBuffers.
=> [spirv] Cleanups related to handling of storage classes

lib/HLSL/HLOperationLower.cpp, tools/clang/test/CodeGenHLSL/batch/declarations/resources/typed_buffers/struct_loads.hlsl
`Buffer<Struct>[i].Field` was handled by the structuredbuffer code, which emitted a `rawBufferLoad` intrinsic. However, typed buffers cannot use `rawBufferLoad`, so some further code patched it back into a `bufferLoad`. The problem is that `bufferLoad` cannot take a byte offset into the element to be loaded, it has to load the entire thing, so we always ended up loading the first struct field.
This fix makes us emit a `bufferLoad` directly, and use the offset to determine which `ResRet` components to return, falling back to using a temporary array for dynamic indexing if needed.
Fixes #2258
=> Fixed offset being lost when lowering Buffer<Struct>[i].Field

lib/HLSL/HLOperationLower.cpp
Looks like we have a cmake problem because it generates a visual studio solution which doesn't have /D DBG in its debug configuration, so I never caught this locally because asserts were compiled out.
=> Fix off-by-one in assert

docs/DXIL.rst
This corrects "Systen" to "System".
=> Fix typo in documentation

include/dxc/DXIL/DxilPDB.h, include/dxc/DxilContainer/DxilContainerAssembler.h, lib/DXIL/DxilPDB.cpp, lib/DxilContainer/DxilContainerAssembler.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/tools/dxcompiler/dxcutil.cpp, tools/clang/tools/dxcompiler/dxcutil.h
This would break when official DXIL.dll was used, since it would exclude
the shader hash part that the validator wouldn't recognize, and is not
required for a valid shader.  This prevented shader signing for the
output of newer compiler versions.
=> Fix PDB generation to not require embedded hash inside DxilContainer

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/CodeGenHLSL/batch/passes/sroa_hlsl/memcpy_nested_input.hlsl
`LowerMemcpy` tries to see if a variable is only written to by a single memcpy. There is a special case for `llvm::Argument`s, since arguments have an implicit first write for their initialization in addition to whatever memcpy they might have. During parameter SROA, aggregate arguments get broken down into their constituing elements as plateholder `AllocaInst`s, and at the end of the pass they'll get promoted back into `llvm::Argument`s of the SROA'd function. In the intermediate steps, however, a test for `isa<Argument>` will fail to detect that an `AllocaInst` is a placeholder for a future argument, and so its implicit initialization will not be taken into account. This would cause a bad `ReplaceMemcpy`, yielding reads from uninitialized locals, causing undefs and all of that fun …
=> Fix memcpy mishandling in parameter SROA

lib/HLSL/DxilContainerReflection.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/Samples/DX11/BC6HEncode_EncodeBlockCS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/BC6HEncode_TryModeG10CS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/BC6HEncode_TryModeLE10CS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_BuildGridCS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_BuildGridIndicesCS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_ClearGridIndicesCS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_DensityCS_Grid.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_DensityCS_Shared.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_DensityCS_Simple.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_ForceCS_Grid.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_ForceCS_Shared.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_ForceCS_Simple.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_IntegrateCS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_RearrangeParticlesCS.hlsl, tools/clang/test/CodeGenHLSL/batch/misc/d3dreflect/structured_buffer_layout.hlsl, tools/clang/unittests/HLSL/DxilContainerTest.cpp
- Added test with a number of apparently untested cases
- Updated some tests used for the more exhaustive reflection test
which were failing to compile on fxc due to utf-8 bom and bool `|=`.
- Don't ignore dxc failures with ignore dxbc fails flag.
=> Fix CBuffer and StructuredBuffer offsets for packing and reflection.

tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.h, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.precedence.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Based on SPIR-V spec, OpSelectionMerge must immediately precede
either an OpBranchConditional or OpSwitch instruction. Similarly
OpLoopMerge must immediately precede either an OpBranch or
OpBranchConditional instruction.
=> [spirv] fix OpLine emission bug

lib/HLSL/HLOperationLower.cpp, tools/clang/test/CodeGenHLSL/batch/expressions/intrinsics/Interlocked_groupshared.hlsl
The code handled instruction addrspacecasts but not constant expression ones. Refactored into a common method between two code paths.
Fixes #2282
Found and filed bug #2283
=> Fixed InterlockedCompareExchange failing validation

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
Multiplying by the alignment made no sense, and there are cases where it is not 1.
=> Fix memcpy size calculation in ScalarReplAggregatesHLSL::ReplaceMemcpy

lib/HLSL/HLSignatureLower.cpp, tools/clang/test/CodeGenHLSL/batch/declarations/functions/entrypoints/semantics/cs_sv_id_int16.hlsl, tools/clang/test/CodeGenHLSL/batch/declarations/functions/entrypoints/semantics/cs_sv_id_min12int.hlsl, tools/clang/test/CodeGenHLSL/batch/declarations/functions/entrypoints/semantics/cs_sv_id_not_int32.hlsl, tools/clang/test/CodeGenHLSL/crashes/float_cs_sv_semantic.hlsl
It seemed overkill to request backends to support a `@dx.op.threadId.i16` intrinsic so I'm always calling the `i32` version and then truncating or zextending to the final type.
Fixes #2268
=> Support non-int32 types with SV_***ID semantics

lib/HLSL/DxilValidation.cpp
=> Fix external validator crash on empty struct

lib/DxilDia/DxilDiaSession.cpp, lib/DxilDia/DxilDiaSymbolManager.cpp, lib/DxilDia/DxilDiaSymbolManager.h
1) avoids leaking exceptions during symbol initialization
2) returns E_FAIL when the scope for a local variable is not found
3) uses getInlinedAtScope when searching for the local variable's scopes.
=> DxilDia bugfixes:

tools/clang/lib/SPIRV/CMakeLists.txt, tools/clang/lib/SPIRV/RawBufferMethods.cpp, tools/clang/lib/SPIRV/RawBufferMethods.h, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/test/CodeGenSPIRV/method.byte-address-buffer.templated-load.matrix.hlsl, tools/clang/test/CodeGenSPIRV/method.byte-address-buffer.templated-load.scalar.hlsl, tools/clang/test/CodeGenSPIRV/method.byte-address-buffer.templated-load.struct.hlsl, tools/clang/test/CodeGenSPIRV/method.byte-address-buffer.templated-load.vector.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
In SPIR-V, ByteAddressBuffers are represented as structures with 1 member: a RuntimeArray of 32-bit uints.
In order to perform templated Load on a raw buffer (e.g. `buf.Load<T>`), we'll need to perform one or more 32-bit uint loads and construct the target type (`T`). The target type is only allowed to be numerical types, boolean types, structures containing them, or arrays of any of these.
This is only the `Load` side of things. The support for templated `Store` is not yet implemented.
=> [spirv] Support for ByteAddressBuffer.Load<T>

tools/clang/include/clang/AST/HlslBuiltinTypeDeclBuilder.h, tools/clang/include/clang/AST/HlslTypes.h, tools/clang/lib/AST/ASTContextHLSL.cpp, tools/clang/lib/AST/CMakeLists.txt, tools/clang/lib/AST/HlslBuiltinTypeDeclBuilder.cpp, tools/clang/lib/Sema/SemaHLSL.cpp
There's a lot of repeated boilerplate needed to declare builtin types with the Clang API. This change encapsulates it in a friendlier "Builder" class.
=> Refactor builtin type declaration

include/dxc/DXIL/DxilConstants.h, include/dxc/DXIL/DxilSubobject.h, include/dxc/DxilContainer/DxilRuntimeReflection.h, include/dxc/DxilContainer/DxilRuntimeReflection.inl, lib/DXIL/DxilMetadataHelper.cpp, lib/DXIL/DxilSubobject.cpp, lib/DxilContainer/DxilContainerAssembler.cpp, lib/DxilContainer/DxilContainerReader.cpp, tools/clang/include/clang/AST/HlslTypes.h, tools/clang/lib/AST/ASTContextHLSL.cpp, tools/clang/lib/AST/HlslTypes.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/batch/shader_stages/raytracing/subobjects_raytracingPipelineConfig1.hlsl, tools/clang/tools/dxcompiler/dxcdisassembler.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
This adds support for the HLSL DXR subobject type RaytracingPipelineConfig1 {uint MaxTraceRecursionDepth, uint Flags}. This extends the existing RaytracingPipelineConfig subobject, adding the Flags field. This is valid for DXR 1.1 devices (which the runtime enforces).
The API definition for the subobject is below (flags shown below match what can be specified in HLSL by omitting the D3D12_ prefix.
typedef enum D3D12_RAYTRACING_PIPELINE_FLAGS
{
D3D12_RAYTRACING_PIPELINE_FLAG_NONE = 0x0,
D3D12_RAYTRACING_PIPELINE_FLAG_SKIP_TRIANGLES = 0x100,
D3D12_RAYTRACING_PIPELINE_FLAG_SKIP_PROCEDURAL_PRIMITIVES = 0x200,
D3D12_RAYTRACING_PIPELINE_FLAG_VALID_MASK = 0x300, ;internal
} D3D12_RAYTRACING_PIPELINE_FLAGS;
typedef struct D3D12_RAYTRACING_PIPELINE_CONFIG1
{
UINT MaxTraceRecursionDepth; …
=> Add RaytracingPipelineConfig1 subobject to DXR

lib/Transforms/InstCombine/InstCombineAddSub.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/batch/declarations/globals/array_cast.hlsl
Add TypeAnnotation for static global and support nested struct in IsTypeMatchForMemcpy.
Also skip A+B --> A|B on i32.
=> Support nested struct in IsTypeMatchForMemcpy

include/dxc/DXIL/DxilModule.h, include/llvm/IR/Module.h, lib/DXIL/DxilModule.cpp, lib/Transforms/IPO/GlobalOpt.cpp, tools/clang/test/CodeGenHLSL/batch/passes/globalopt/entrypoint_name_invariant_main.hlsl, tools/clang/test/CodeGenHLSL/batch/passes/globalopt/entrypoint_name_invariant_main2.hlsl
GlobalOpt has an explicit test for a function called "main" (eww...) to enable an optimization. This updates the test to match the entry point, independent of its name.
Fixes #2350
=> Remove globalopt dependency on the name of the entrypoint

lib/HLSL/ComputeViewIdStateBuilder.cpp, tools/clang/test/CodeGenHLSL/mesh/vertices_sig_bigger_than_primitives_sig_regression.hlsl
The primitive signature was being used with `vertexStoreOutput` instructions. It would crash if the vertex signature was bigger than the primitive signature.
=> Fix crash with mesh shader output signatures

tools/clang/test/CodeGenHLSL/batch/expressions/conversions_and_casts/derived_to_base_assign.hlsl
The original test succeeded even in the presence of the bug whose fix it was trying to verify. I've further simplified it and added more cases for different combinations of LHS/RHS conversions and casts.
=> Improve derived to base assignment test

tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/ShaderOpArithTable.xml, utils/hct/hctdb_test.py
The tests were manually added to ShaderOpArithTable.xml in PR #1867,
but ShaderOpArithTable.xml should be generated by hctdb_test.py script.
No actual changes to the test data, just the order of the tests is different
because of rearranging done by the script XML processing.
Added a check for shader model 6.5 so the tests will be skipped on lower
shader models.
=> Change WaveMultiPrefix test data to be generated by hctdb_test.py

docs/DXIL.rst, include/dxc/DXIL/DxilConstants.h, include/dxc/DXIL/DxilMetadataHelper.h, include/dxc/DXIL/DxilResource.h, include/dxc/HLSL/DxilValidation.h, lib/DXIL/DxilMetadataHelper.cpp, lib/DXIL/DxilResource.cpp, lib/DXIL/DxilResourceBase.cpp, lib/DXIL/DxilUtil.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilValidation.cpp, tools/clang/include/clang/AST/HlslTypes.h, tools/clang/lib/AST/ASTContextHLSL.cpp, tools/clang/lib/AST/HlslTypes.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/batch/declarations/resources/textures/feedback.hlsl, tools/clang/test/CodeGenHLSL/batch/declarations/resources/textures/feedback_metadata.hlsl, utils/hct/hctdb.py
- Update the HLSL syntax from `FeedbackTexture2DMinLod` to `FeedbackTexture2D<SAMPLER_FEEDBACK_MIN_MIP>`
- Update DXIL to only have two UAV types for `FeedbackTexture2D[Array]` and use an extra metadata field to distinguish between the sampler feedback type.
=> Update FeedbackTexture2D types to be templated

lib/DxilPIXPasses/DxilShaderAccessTracking.cpp, tools/clang/test/CodeGenHLSL/batch/pix/AccessTracking.hlsl, tools/clang/test/CodeGenHLSL/batch/pix/rawBufferStore.hlsl
(Turns out the original implementation with atomic ORs was very good at inducing TDRs on otherwise-functional shaders.)
This change uses three times the UAV memory to write a single DWORD per access type using BufferStore, rather than to set a single bit using AtomicOr. The resultant less-interlocky instrumented shaders no longer TDR. Repro case in PIX bug # 22725204
=> PIX: Change shader access tracking pass to use non-atomic stores

docs/DXIL.rst, include/dxc/DXIL/DxilConstants.h, include/dxc/DXIL/DxilFunctionProps.h, include/dxc/DXIL/DxilMetadataHelper.h, include/dxc/DXIL/DxilModule.h, include/dxc/DXIL/DxilOperations.h, include/dxc/HLSL/DxilValidation.h, lib/DXIL/DxilMetadataHelper.cpp, lib/DXIL/DxilModule.cpp, lib/DXIL/DxilOperations.cpp, lib/DxilContainer/DxilContainerAssembler.cpp, lib/HLSL/DxilValidation.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/unittests/HLSL/ValidationTest.cpp, utils/hct/hctdb.py
- Compute mesh payload size before final object serialization
- During CodeGen for MS based on payload parameter
- During CollecShaderFlagsForModule for AS based on DispatchMesh call
- Store payload sizes in corresponding funtion properties, serializing
these properly for HL and Dxil Modules
- Use payload sizes from function props for PSV0 data during serialization
- Validate measured and declared payload sizes, don't just fill in
properties during validation
- Fix Wave/Quad allowed shader stages, enabling Quad* with CS-like models
- rename payloadByteSize members to payloadSizeInBytes
- Add GetMinShaderModelAndMask overload taking CallInst for additional
detail required to produce correct SM mask for Barrier operations
=> Store mesh payload in function props, fix Wave/Quad/Barrier validation

include/dxc/DxilContainer/DxilPipelineStateValidation.h, include/dxc/DxilRootSignature/DxilRootSignature.h, lib/DxilContainer/DxilContainerAssembler.cpp, lib/DxilRootSignature/DxilRootSignatureValidator.cpp, tools/clang/lib/Parse/HLSLRootSignature.cpp, tools/clang/lib/Parse/HLSLRootSignature.h, tools/clang/test/CodeGenHLSL/mesh/mesh-rootsig.hlsl
- Fix PSV so MS output topology doesn't overlap SigInputVectors
- Fix PSV version code to use latest when validation disabled
=> Add mesh shader support to RootSignature parsing/validation and fix PSV

lib/HLSL/HLOperationLower.cpp
Later versions of clang fail to compile a lambda function that includes
a parameter that shadows an explicit capture. Such a one was introduced
to HLOperationLower recently. This preserves the existing behavior while
removing the shadow.
=> Remove lambda parameter shadow

lib/HLSL/DxilValidation.cpp
Compare:
```
error: validation errors
at 'call void @dx.op.bufferStore.f32(i32 69, %dx.types.Handle %buf_texture_structbuf, i32 0, i32 0, float 3.000000e+00, float undef, float undef, float undef, i8 1)' in block 'entry' of function 'main' (E:\Sandbox\playground.hlsl:3:22): store should on uav resource.
```
to the previous
```
error: validation errors
at 0x1236957db30 inside block #0 of function main store should on uav resource.
```
=> Improve validation error message formatting

lib/DxilDia/DxilDiaSession.cpp, lib/HLSL/DxilContainerReflection.cpp
This is a C++14 STL feature and we're not technically compiling against C++14, so llvm has an equivalent.
Fixes #2365
=> Remove std::make_unique with llvm::make_unique

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/batch/declarations/functions/recursion/free_function_error.hlsl, tools/clang/test/CodeGenHLSL/batch/declarations/functions/recursion/instance_function_error.hlsl, tools/clang/test/CodeGenHLSL/batch/declarations/functions/recursion/static_function_error.hlsl
Recursion detection did not consider member functions.
Fixes #2370
=> Improve recursion detection to handle member functions and add tests.

include/dxc/DxilContainer/DxilContainer.h, lib/DxilContainer/DxilContainerAssembler.cpp, lib/HLSL/DxilContainerReflection.cpp, lib/HLSL/DxilValidation.cpp, tools/clang/test/CodeGenHLSL/batch/declarations/functions/entrypoints/semantics/misc/shadingrate1.hlsl, tools/clang/test/CodeGenHLSL/batch/declarations/functions/entrypoints/semantics/misc/shadingrate2.hlsl, tools/clang/test/CodeGenHLSL/mesh/mesh.hlsl, tools/clang/tools/dxcompiler/dxcdisassembler.cpp
(and fill in some missing SV_ShadingRate entries)
One part of the change depends on an enum value being added to d3dcommon.h, which I have staged in the OS.   For now I just locally #defined the value D3D_NAME_CULL_PRIMITIVE in dxilcontainerreflection.cpp.  Advice on how to get this #define removed and d3dcommon.h updated?  Need to wait until public SDK has been updated?
=> flesh out SV_CullPrimitive support 

include/dxc/HLSL/DxilExportMap.h, lib/HLSL/DxilLinker.cpp
Always the same culprit: iterating over a pointer-keyed map/set. There are more issues remaining because I'm still seeing my linked dxil module have unpredictible function orderings, but hopefully this part of the code should be good now.
=> Fix a few sources of nondeterminism in the dxil linker

utils/GetCommitInfo.py, utils/version/gen_version.py
Adds exception handling around git invocations to supply replacement values when building outside of git enlistment.
Fixes #2364
=> Enable build without git enlistment

tools/clang/lib/Sema/SemaHLSL.cpp
Removed repeated include of #include "clang/Sema/SemaHLSL.h"
=> SemaHLSL header was included twice

tools/clang/lib/Sema/AnalysisBasedWarnings.cpp, tools/clang/test/HLSL/matrix-syntax-exact-precision.hlsl, tools/clang/test/HLSL/matrix-syntax.hlsl, tools/clang/test/HLSL/uninitialized-warnings.hlsl, tools/clang/unittests/HLSL/VerifierTest.cpp
As listed in issue #2419, unlike DXC, FXC has some support for generating diagnostic for uninitialized variables/structs (which is rather inconsistent). For example, FXC generates error for uninitialized variables, but only warns for uninitialized structs. Also, FXC fails to generate any warning when variables "may" be uninitialized (e.g., when initialized conditionally). This PR enables Clang warning for uninitialized variables/structs which produces much better diagnostic than FXC. 
Fixes #2419
=> Enable clang warnings for uninitialized variables/structs

tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/ShaderOpArithTable.xml, utils/hct/hctdb_test.py
1)	Ensure wave lane-id’s are sorted when accumulating result
2)	Fix made for HLSL in ShaderOpArithTable.xml to ensure the input aligns with what is being tested
3)	Added support for the “UBit” version for all of these tests.
=> Adding test fixes and more support for SM6.5 WaveMultiPrefix functions

tools/clang/test/HLSL/ShaderOpArith.xml
ShaderOpArithTable.xml contains test "Dot2AddHalf" that references shader op "Dot2AddHalfOp" but ShaderOpArith.xml has just "Dot2AddOp."
This results in an "unable to find shader op" error when running test Dot2AddHalfTest.
Fixes #2429
=> Fix Dot2AddHalf test

lib/DxilPIXPasses/DxilDebugInstrumentation.cpp
...eventually causing cases where these inserted functions didn't dominate all uses.
=> PIX shader debug pass was (pointlessly) caching added fn pointers

tools/clang/test/CodeGenHLSL/batch/expressions/intrinsics/misc/abs1.hlsl, tools/clang/unittests/HLSL/FileCheckerTest.cpp, tools/clang/unittests/HLSL/HlslTestUtils.h
- Add support for multiple `RUN:` lines in test files. This should help reduce the number of test files we have as multiple closely related scenarios can be tested in a single test file.
- Add support for multiple check prefixes using a new option `-check-prefixes` passed to `FileCheck`.
- Examples:
```
// RUN: %dxc -E main -T vs_6_0 %s | FileCheck %s -check-prefixes=CHK1,CHK3
// RUN: %dxc -E main -T vs_6_2 -enable-16bit-types %s | FileCheck %s -check-prefix=CHK2
```
=> Add support for check prefixes and multiple RUN lines in file checker

tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/lib/Sema/SemaType.cpp, tools/clang/test/HLSL/cpp-errors-hv2015.hlsl, tools/clang/test/HLSL/cpp-errors.hlsl, tools/clang/test/HLSL/indexing-operator.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/array/large_resource_array.hlsl
- This restriction from fxc is not needed for dxc
- It was being applied to resource arrays in dxc, but not in fxc.
=> Remove array dimension limitation (1 <= dimension <= 65536)

cmake/modules/FindDiaSDK.cmake, utils/TableGen/AsmWriterEmitter.cpp
Use vswhere when possible to locate the VS install.  This enables VS to be found when it isn't on the C drive.
- Also mark a function const as 2019's STL doesn't like putting it in a map if it isn't.
=> Enable non-C VS installs

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.interlocked-methods.texture.swizzling.error.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.interlocked-methods.texture.swizzling.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
1. Report an error if interlocked op has a texture argument whose
result type is non-scalar. This is not allowed in SPIR-V.
2. If the argument for interlocked op is a vector swizzling of a
texture, we should use the texture instead of the swizzling.
Fixes #2409
=> [spirv] handle texture swizzling used in interlocked op

lib/DxilContainer/DxilContainerAssembler.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
And stop trimming quotes from pdb name.  This is the responsibility of cmd.exe, not the API.  The API user should not be adding extra quotes to the pdb name string if they don't want them.
=>   Always write shader hash when supported, don't tie to debug name

tools/clang/lib/Driver/Driver.cpp, tools/clang/unittests/dxc_batch/dxc_batch.cpp
The call to `OptTable::PrintHelp` in Driver.cpp takes 6 arguments.
https://github.com/microsoft/DirectXShaderCompiler/blob/c25c44dabf9c18269966ccf9d82b99b956b73faa/include/llvm/Option/OptTable.h#L166-L168
=> Fix call to OptTable::PrintHelp

tools/clang/lib/Parse/ParseHLSL.cpp, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/missing_identifier_name_objects.hlsl
Fix a crash when no identifier name is provided to ConstantBuffer decl.
Fixes #2471
=> Fix a crash when no identifier name provided for constant buffer

tools/clang/lib/SPIRV/SpirvEmitter.cpp
If -fvk-use-dx-layout or -fvk-use-scalar-layout option is given,
we use dx or scalar memory layout that must follow
scalarBlockLayout feature of Vulkan memory layout rule. This commit
lets dx/scalar layout use SPIR-V validator with
--scalar-block-layout option.
Fixes #2408
=> [spirv] spirv-val scalar-block-layout for dx/scalar layout

CMakeLists.txt
When put DXC into a parent project, the CMAKE_BINARY_DIR and CMAKE_SOURCE_DIR are the paths of the parent project, makes HLSL_VERSION_LOCATION a wrong path. Change them to CMAKE_CURRENT_BINARY_DIR and CMAKE_CURRENT_SOURCE_DIR to locate the DXC's paths.
=> Fix the HLSL_VERSION_LOCATION when build DXC in a parent project

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/basic/Frc_const_prop.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/basic/frac_literal.hlsl
- Fix implementation `frac` intrinsic for literal case which would evaluate `frac(-1.5)` to `-0.75` instead of `0.5`.
- Improve test coverage of `frac` intrinsic for literal case.
=> Fix implementation of frac intrinsic for literal case

lib/DXIL/DxilModule.cpp, tools/clang/unittests/HLSL/DxilContainerTest.cpp
Note: unit test support for PSV0 is lacking.  This is only a regression test for this bug, but additional unit testing for PSV data should be added in the future by adding a PSV dump step to FileCheckerTest.cpp, then adding tests under HLSLFileCheck.
Fixes #2485.
=> Fix Amplification Shader (AS) payload size in runtime data

tools/clang/lib/CodeGen/CGCall.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/atomic/atomic.hlsl
Fixes a crash with atomic intrinsics when vector component access op is applied on scalars passed to atomic intrinsics.
Fixes #2434
=> Fix crash with atomic op intrinsics

tools/clang/unittests/SPIRV/FileTestUtils.cpp
This is a follow up commit of #2473 that uses scalar-block-layout
spirv-val option for dx/scalar layout. I forgot to apply the same
thing for unittests.
=> [spirv] spirv-val scalar-block-layout for unittests

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/test/CodeGenSPIRV/raytracing.nv.anyhit.hlsl
Fixes issue reported in our internal testing for SPV_NV_ray_tracing.
Corresponding google test updated as well
@ehsannas : Please review
Thanks!
=> [SPIRV] Fix bug in any-hit raytracing shaders not writing out payload for early exits.

lib/DxilDia/DxilDiaSymbolManager.cpp
The previous code took the dbg-declare instruction to be the start of the live range for a variable. But the actual variable can be created and used before this declaration.
This change seeks the first and last use of each variable, and defines the live range to be the first use through to the end of the local scope, or the last use, whichever is later. (But of course, the end of the scope should really always be later.)
=> PIX DIA: Use min/max RVA of variable's uses as live range

lib/HLSL/DxilContainerReflection.cpp, tools/clang/test/HLSLFileCheck/d3dreflect/clip-dist-refl.hlsl
No idea why this was here, but it was very old (predates GitHub repo),
and no tests failed when I removed it, so I think it's fine to remove.
Fixes #2540.
=> Reflection: Remove code preventing more than one SV_ClipDistance

lib/DxilPIXPasses/DxilShaderAccessTracking.cpp, tools/clang/test/HLSLFileCheck/pix/AccessTrackingForSamplerFeedback.hlsl, tools/clang/test/HLSLFileCheck/pix/rawBufferStore.hlsl
This fixes a bug caused by a recent change to this pass: Previously it would write one of three bits into a single DWORD per resource, but was changed to write a whole DWORD into one of three DWORDs per resource. (The RMW of a bit-set turned out to be a lot slower than the newer write-only version.)
Unfortunately the offset into the three DWORDs was being calculated as a byte offset, not a DWORD offset.
=> PIX: Shader access tracking pass: Use DWORD-aligned accesses for raw stores.

lib/DxilPIXPasses/DxilAddPixelHitInstrumentation.cpp, lib/DxilPIXPasses/DxilAnnotateWithVirtualRegister.cpp, lib/DxilPIXPasses/DxilDebugInstrumentation.cpp, lib/DxilPIXPasses/DxilForceEarlyZ.cpp, lib/DxilPIXPasses/DxilOutputColorBecomesConstant.cpp, lib/DxilPIXPasses/DxilPIXPasses.cpp, lib/DxilPIXPasses/DxilPIXVirtualRegisters.cpp, lib/DxilPIXPasses/DxilReduceMSAAToSingleSample.cpp, lib/DxilPIXPasses/DxilRemoveDiscards.cpp, lib/DxilPIXPasses/DxilShaderAccessTracking.cpp
Zero code change here, except moving the #include for DxilOperations.h to be on its own in a few files, in order to cope with our clang-format's habit of ordering includes alphabetically.
This is in preparation for a real change coming next.
=> Just run clang format on PIX passes

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvContext.h, tools/clang/include/clang/SPIRV/SpirvFunction.h, tools/clang/include/clang/SPIRV/SpirvType.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvContext.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvFunction.cpp
this is a cleanup that will help us with debug type representation
later.
=> [spirv] Cleanup: Remove SPIRV hybrid function type.

tools/clang/test/CodeGenSPIRV/spirv.debug.o1.option.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.o2.option.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.o3.option.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
When we use -Zi option without -fcgl, shader compile results in an
error. This is because SPIR-V backend of DXC does not have code
for PBD file, but the debug info gen with optimization lets DXC
use the PBD file. This CL lets DXC skips it.
=> [spirv] fix crash from debug info gen with opt

utils/hct/hctbuild.cmd
After initial generation, subsequent invocations of cmake will
only alter the defines that are specified by that command. Any
defines that were set previously retain their earlier settings
by being stored in the CMakeCache.txt in the build directory.
hctbuild.cmd allows specifying certain defines when arguments are
passed to it, but many of these do not allow resetting the defines
they set. So if you define an official versioned build, every
subsequent build with use the official version unless the cmake
cache is edited or the whole build directory is wiped clean. This
is true of several other settings.
This change sets the defines hctbuild cares about every time it is
invoked regardless of arguments. If the official build is specified
the official define is set to ON. If it isn't, it is …
=> Clear Cmake defines on reuse of hctbuild

utils/version/gen_version.py
According to the description at the top of gen_version.py and the
commit that introduced it, the "Official build" versioning is meant
to add 10000 to the number of commits since the last official release
when the build is in the master branch. However, because of the use
of "is" instead of "==", the comparison between the variable and
the string literal in the python script was never succeeding. The
"is" operator only succeeds when it compares two variables that
have been assigned the same variable or one has been assigned to
the other. For comparisons of contents, "==" should be used.
=> Correct official versioning in master branch

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/oo.inheritance.member.function.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
When a derived struct inherits a base struct and the derived one has a
member function, accessing its member variable in the member function
emits an invalid index. This CL fixes it.
=> [spirv] fix invalid index of member in derived class

include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/lib/Lex/Pragma.cpp, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/warnings/disable-warning-with-option.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/warnings/show-option-names.hlsl, tools/clang/test/HLSLFileCheck/hlsl/preprocessor/pragma/pragma-diagnostic.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp
Fixes #2655.
- Adds `#pragma dxc diagnostic ...` so specific warnings may be ignored.
- Prints the option name for disabling the warning after the warning message, when available.
Future improvements:
- Add the diagnostic options to dxc command line arguments
- Better categorization of HLSL warnings
=> Add pragma control for diagnostics and option printing

include/dxc/HLSL/HLModule.h, lib/HLSL/HLMatrixLowerPass.cpp, lib/HLSL/HLModule.cpp, tools/clang/test/HLSLFileCheck/hlsl/types/modifiers/precise/matrix_od.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/modifiers/precise/propagate_to_producers_interproc_matrix.hlsl
To flag a variable as precise, a dx.attribute.precise call is inserted.
In the case of matrices, this becomes a problem if it persists too long
due to validation errors because the matrix is never lowered. When we
reach the HLMatrixLowerPass, the matrix can be lowered to vector. This
change detects when the precise call is applied to a matrix, lowers the
parameters and replaces the call with one taking a vector instead.
The call is necessary to keep the precise informaton across function
calls.
Adds variante of precise tests. precise/matrix.hlsl is modified by
matrix_od.hlsl to take the -Od parameter.
precise/propagate_to_producers_interproc.hlsl is modified to use
matrices since an earlier fix for this bug caused a regression when this
alteration was made.
Fixes #2189
=> Fix crash when using precise matrix with -Od

tools/clang/test/HLSLFileCheck/hlsl/preprocessor/version_defines/target_version_vertex.hlsl
The existing DXC version macro test is hitting problems in some esoteric
build cases that have different version values. This restricts the tests
to just determine that the macro is defined for now. When we can decide
what form these version macros should take, they'll be adapted to the
new expectations.
=> Relax dxc version macro tests

tools/clang/tools/dxcompiler/dxcfilesystem.cpp
When an include path is detected to not be absolute, "./" is inserted in
front of it. The absolute path detection only allowed for *:\ and not
*:/ even though windows functions are defined as accepting paths with /
instead of \ which meant that all other paths could be specified this
way.
By changing the absolute path detection to allow for c:/* and similar,
when the file descriptor is searched in dxcfilesystem, it will be
found to match the original definition so the includes will succeed.
Fixes #2669
=> Correct include of absolute '/' paths on windows

lib/DxilDia/DxilDiaSession.cpp, lib/DxilDia/DxilDiaSymbolManager.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/tools/d3dcomp/d3dcomp.cpp, tools/clang/tools/dxa/dxa.cpp, tools/clang/tools/dxcompiler/dxcfilesystem.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp
- These need to be converted back to UTF-16 after argument processing for
a couple APIs and CA2W constructors were missing CP_UTF8 for the input
encoding from the utf-8 argument strings.
=> Add missing UTF8 for source and output filenames

lib/HLSL/DxilValidation.cpp, tools/clang/test/HLSLFileCheck/d3dreflect/cbuffer_alignment.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/empty_struct2.hlsl
Due to partial reflection stripping, sometimes a constant buffer will
start to be validated even though not every level of the aggregates or
arrays has annotation information. Specifically, when an array contains
structs, the annotation on the array element might be missing. When this
happens, the element size is returned as zero. In this case, early
return prevents the check for overlaps since the incorrect zero value
results in a false extent which is detected as an overlap and validation
failure.
=> Avoid validation failure when missing annotation

CMakeLists.txt, tools/clang/lib/Frontend/CMakeLists.txt, tools/clang/lib/Frontend/InitPreprocessor.cpp, tools/clang/test/HLSLFileCheck/hlsl/preprocessor/version_defines/target_version_vertex.hlsl, utils/version/CMakeLists.txt
The original generation of HLSL macros containing version information
used the same generated header file as the RC file. This was fine except
when building in xbtools where the version information in the RC is
overridden to match the GDK.
To maintain the DXC macros as communicating the version of the DXC
component to better enable workarounds based on that information, the
same generator script is used, but the header file is separate and
doesn't abide by the fixed version location provided via cmake defines.
This way it will always contain DXC information while the RC file can
continue to contain the version information as it did before.
To allow for the case where the headers are not the same, a preliminary
version.gen file is created according to the dxc version requirements
and …
=> Separate generation of DXC macro version info

lib/DXIL/DxilModule.cpp, tools/clang/test/HLSLFileCheck/d3dreflect/cbuffer_alignment_16.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/cbuffer_alignment_matrix.hlsl
When stripping reflection data, structures are searched for any member
or submember scalars that are smaller than 32 bits. When one is found
and min precision is being used, the structure is identified as not
being able to be stripped.
In the case of a shader that has a resource that contains a struct which
contains an array which contains a struct, the struct was not being
processed as a struct, but rather as a scalar, which would cause it to
return a size of zero, which was found to be less than 32 bits. This
isn't right if the innermost struct contained a 32 bit integer. Either
way, this resulted in inconsistent results for the parent struct and the
innermost struct. As a result, the annotations were stripped from the
innermost, but left on the outermost. Because the parent struct had …
=> Correct 16-bit detection in reflection stripping

lib/DXIL/DxilMetadataHelper.cpp
Bug triggered DXASSERT, but otherwise harmless on fre builds.
=> Update DxilMDHelper's SM for correct MinValVersion info.

utils/version/CMakeLists.txt
When run on a fast system with a lot of threading, the custom cmake
commands to generate version include information ran into a problem
because the two include files both depended on the same intermediate
file for some builds. As a result, when the first thread started writing
to it, the second thread couldn't access it if it started to try before
the first finished. The result was an empty header and no defined
version macros
By elminating the common intermediate file and giving each output file
their own intermediate file, the generation should proceed no matter how
many threads and unnecessary recompilation won't result when
regeneration results in no changes.
To facilitate this, I've added a cmake macro that handles both cases.
The peculiarities of how they are generated are all …
=> Correct generated version race condition

include/dxc/DxilPIXPasses/DxilPIXPasses.h, lib/DxilPIXPasses/CMakeLists.txt, lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp, tools/clang/test/HLSLFileCheck/pix/DbgValueToDbgDeclare.hlsl
This PR adds a pass to convert calls to the dbg.value intrinsic to dbg.declare. After the pass, each
call to dbg.value becomes a store to a newly-alloca'd location. For example,
entry:
dbg.value(metadata 1, var i)
br loop1
loop1:
t0 = phi(1, entry, t, loop1)
dbg.value(metadata t0, var i)
...
br i1 cond, loop1, exit
exit:
t1 = phi(1, entry, t0, loop1)
dbg.value(metadata t1, var i)
ret
would become
entry:
a = alloc [1 x float]
dbg.declare(metadata a, var i)
store 1, a
br loop1
loop1:
t0 = phi(1, entry, t, loop1)
store t0, a
...
br i1 cond, loop1, exit
exit:
t1 = phi(1, entry, t0, loop1)
store t1, a
ret
This pass is to be used for the trace-based, HLSL debugging in WinPix.
=> Adds pass for converting calls to dbg.value to dbg.declare

include/dxc/Support/dxcapi.impl.h, tools/clang/tools/dxclib/dxc.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, utils/hct/cmdtestfiles/smoke.hlsl, utils/hct/hcttestcmds.cmd
Fixes #2712
- Fix output naming for StringRef
- Support /Fc when /Fh is provided
- Fix root sig strip flag
- Create root sig stream output
- Validate -Frs root sig output for signing with DXIL.dll
- Move outputs under valHR success branch
- Add test for -Fre, -Fsh, -Frs, and -Fc with -Fh
- Rework hcttestcmds.cmd completely: checks a lot more stuff and is way more robust,
while being much easier to read, add to, and maintain, I hope.
=> Fix outputs -Fre, -Fsh, -Frs, and -Fc with -Fh

include/dxc/Support/dxcapi.impl.h, tools/clang/tools/dxclib/dxc.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, utils/hct/cmdtestfiles/smoke.hlsl, utils/hct/hcttestcmds.cmd
- Fix output naming for StringRef
- Support /Fc when /Fh is provided
- Fix root sig strip flag
- Create root sig stream output
- Validate -Frs root sig output for signing with DXIL.dll
- Move outputs under valHR success branch
- Add test for -Fre, -Fsh, -Frs, and -Fc with -Fh
- Rework hcttestcmds.cmd completely: checks a lot more stuff and is way more robust,
while being much easier to read, add to, and maintain, I hope.
cherry-picked from #2716 - 367dd44.
=> Fix outputs -Fre, -Fsh, -Frs, and -Fc with -Fh (#2716)

CMakeLists.txt, projects/CMakeLists.txt, tools/CMakeLists.txt, utils/hct/hctbuild.cmd
The recently added DXBC to DXIL converter requires header d3d12TokenizedProgramFormat.hpp from the latest Windows Driver Kit (version 10.0.18362.0) and therefore introduces a build dependency on the latest WDK.
This PR adds an option to hctbuild.cmd that enables a build of DXC without the converter and latest WDK.
=> Add option to hctbuild.cmd to skip building dxilconv.dll and related tools

include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, include/llvm/Option/OptTable.h, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/AST/PrettyPrinter.h, tools/clang/lib/AST/DeclPrinter.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSL/rewriter/correct_rewrites/array-length-rw_gold.hlsl, tools/clang/test/HLSL/rewriter/rewrite-uniforms.hlsl, tools/clang/tools/dxclib/dxc.cpp, tools/clang/tools/dxclib/dxc.h, tools/clang/tools/dxr/CMakeLists.txt, tools/clang/tools/dxr/dxr.cpp, tools/clang/tools/libclang/dxcrewriteunused.cpp, tools/clang/unittests/HLSL/OptionsTest.cpp, tools/clang/unittests/HLSL/RewriterTest.cpp
- Added rewriter functions for extracting uniforms into global scope
- Will not work if name collides (namespaces have bugs)
- Values under cbuffer _Params, resources outside (more bugs)
- Added rewriter HLSLOptions and support all through RewriteWithOptions
- Refactored dxr.exe to use HLSLOptions and RewriteWithOptions
- Exposed Write*VersionInfo functions from dxclib
- Fixed issue with External[Lib/Fn] for version printing.
=> Rewriter: improvements plus extract uniforms to global scope

include/dxc/Support/WinAdapter.h
The Linux adapter code includes an implementation of the IUnknown
interface that contains m_count to keep track of the reference counts.
That variable is used extensively, but is not initialized.
Complaints about use before initialization due to this make up the
overwhelming majority of the complaints Valgrind makes against DXC on
Linux. Adding a constructor makes IUnknown no longer an interface,
but the build doesn't seem to care.
=> [linux] Initialize m_count for IUnknown

include/dxc/dxcpix.h, lib/DxilDia/CMakeLists.txt, lib/DxilDia/DxcPixCompilationInfo.cpp, lib/DxilDia/DxcPixCompilationInfo.h, lib/DxilDia/DxcPixEntrypoints.cpp, lib/DxilDia/DxilDiaSession.h, tools/clang/unittests/HLSL/CompilerTest.cpp
(Tests coming in a subsequent commit in this PR.)
This allows PIX to retrieve these data directly, without having to go through the DIA abstraction.
(There was a bug in that abstraction, in that if the user defined a macro with embedded spaces with no surrounding quotes, then DIA would return the last word in that definition in place of the shader source filename.)
=> PIX: Add new API to retrieve info about compilation options (macros, target profile etc) 

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/HLSLFileCheck/hlsl/control_flow/basic_blocks/cbuf_memcpy_replace.hlsl
When the only use of an alloca is as the destination of a memcpy
operation, the compiler will try to replace all uses of the alloca with
the source of the memcpy. That's fine when all the uses are in locations
where the source of the memcpy is sure to be defined, otherwise, a lot
of complicated PHI insertion is needed to get things right. Lacking it
made LCSSA checks fail. When LCSSA did succeed in inserting PHIs, it did
it wrong which caused other problems.
Rather than do the complicated PHI insertion at memcpy replace, this
change borrows from the previous work for global variables in similar
circumstances and recharacterizes the use of the pointer to be stored
only, but not uniquely. The result of this is the memcpy is replaced
with a load/store pair. There is a good chance that pair …
=> Fix memcpy replace with undominated users

lib/HLSL/DxilPromoteResourcePasses.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/HLSLFileCheck/hlsl/types/modifiers/static/static_res_array.hlsl
Fixes #2061 
Additional work needed to support unroll case since GEP not known to be constant there.  Either need simplification between unroll and DxilPromoteStaticResources (no good for /Od case though), or DxilValueCache access in LoadAndStorePromoter.  But not sure LoadAndStorePromoter should be used on static global uses in the first place.  Perhaps an another solution is needed.
=> Fix static global resource arrays.

docs/SPIR-V.rst, tools/clang/include/clang/SPIRV/FeatureManager.h, tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/FeatureManager.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/raytracing.khr.closesthit.hlsl, tools/clang/test/CodeGenSPIRV/raytracing.nv.anyhit.hlsl, tools/clang/test/CodeGenSPIRV/raytracing.nv.callable.hlsl, tools/clang/test/CodeGenSPIRV/raytracing.nv.closesthit.hlsl, tools/clang/test/CodeGenSPIRV/raytracing.nv.enum.hlsl, tools/clang/test/CodeGenSPIRV/raytracing.nv.intersection.hlsl, tools/clang/test/CodeGenSPIRV/raytracing.nv.library.hlsl, tools/clang/test/CodeGenSPIRV/raytracing.nv.miss.hlsl, tools/clang/test/CodeGenSPIRV/raytracing.nv.raygen.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Added support for generating SPIR-V for provisional cross vendor spec.
By default we generate code for NV extension(to preserve compatibility) and enable KHR extension using -fspv-extension=SPV_KHR_ray_tracing
Note: Opcodes for KHR extension alias with NV other than below
1) GeometryIndex() is supported only in KHR extension.
2) New Capability : CapabilityRayTracingProvisionalKHR.
Added unit test and updated documentation
Once provisional spec is ratified to final, i plan to cleanup existing NV suffixes used for various internal symbols( for ex IK_RayTracingOpNV) and generate code for KHR by default
@ehsannas @jaebaek : Please review or redirect to appropriate folks
Thanks!
=> Add support for SPV_KHR_ray_tracing.

include/dxc/DXIL/DxilUtil.h, include/dxc/HLSL/HLModule.h, lib/DXIL/DxilUtil.cpp, lib/HLSL/DxilCondenseResources.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilLegalizeSampleOffsetPass.cpp, lib/HLSL/DxilLinker.cpp, lib/HLSL/DxilValidation.cpp, lib/HLSL/HLModule.cpp, lib/HLSL/HLOperationLower.cpp, lib/HLSL/HLSignatureLower.cpp
This change adds to the existing EmitErrorOnInstruction functionality in
dxilutil to include EmitErrorOnFunction and EmitErrorOnGlobalVariable.
Each derives line number information from the metadata of these objects
if available. If it isn't available, the error or warning messages are
still printed, but an additional suggestion to add a -Zi flag is added.
=> Print Lines or "add -Zi" on error messages

README.md
At some point, the capitalization of the Microsoft organization name on
github was changed to lowercase to better match precedent. Update the
links in README.md to reflect this.
=> Correct capitalization of microsoft in Readme

include/dxc/Support/WinAdapter.h
When using libdxcompiler.so, UUIDs of classes don't match
because on Linux a UUID is effectively an address of a
static member variable.
This change replaces UUIDs with a consistent value -
a hash of the class name.
=> [linux-port] Fix incorrect UUIDs on Linux

include/dxc/HLSL/DxilGenerationPass.h, include/dxc/HLSL/HLOperations.h, lib/HLSL/DxcOptimizer.cpp, lib/HLSL/DxilPreparePasses.cpp, lib/HLSL/HLOperations.cpp, lib/IR/Verifier.cpp, lib/Transforms/IPO/PassManagerBuilder.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp, tools/clang/lib/CodeGen/CGHLSLMSHelper.h, tools/clang/lib/CodeGen/CGHLSLRuntime.h, tools/clang/lib/CodeGen/CGStmt.cpp, tools/clang/test/HLSLFileCheck/hlsl/control_flow/basic_blocks/cbuf_memcpy_replace.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/wave/reduction/WaveAndBreakLib.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/wave/reduction/WaveAndBreakPS.hlsl, utils/hct/hctdb.py
This introduces dx.break, an internal global that is applied as a
condition to any unconditional break in order to keep the basic block
inside the loop. The load is made volatile in order to keep the
optimizations from identifying the global as a constant and removing it.
Because it remains in the loop, operations that depend on wave operations
inside the loop will be able to get the right values.
Normal break blocks don't need this conditional, but we don't know that
at code generation. So a later pass identifies break blocks with wave
sensitive operations that depend on wave ops that are inside the loop they
are breaking out of and preserves those conditionals while removing all
the rest.
Initially, the global variable is set to not constant to avoid
instruction simplification that …
=> Conditionalize breaks to keep them in loops

lib/HLSL/DxilPreparePasses.cpp
The original code expected that optimizations wouldn't remove any of the
users of a call to dx.break(). In loop unrolling cases, simplifyCFG may
do just that, which caused the original assert and assume we're right
method to break.
Now we assert we're in the confines of what is now known to be possible,
but we don't assume anything. There's a loop over the users of the call
instruction that I only ever expect to be executed once or never, but
it's there just in case.
=> Account for non-one user of dx.break call

docs/DXIL.rst
`@dx.op.bufferLoad` is for `BufferLoad`, not `RawBufferLoad`.
This matches what DxilOperations.cpp does.
=> Correct function name for RawBufferLoad

lib/HLSL/DxilPreparePasses.cpp
The previous lowering of dx.break() assumed that the user was still a
branch as it was when it was set up. However, optimizations can switch
things around so this assumption is wrong.
By allowing for other instructions or even not an instruction, the
replacement takes place just the same regardless of whether its a
branch.
=> Don't assume branch user of dx.break

include/dxc/Test/DxcTestUtils.h, tools/clang/test/HLSLFileCheck/rewriter/remove-unused-globals.hlsl, tools/clang/tools/libclang/dxcrewriteunused.cpp, tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp
- Add support for rewriter (dxr) to FileCheckerTest
- Add test for removing globals
Can help in scenario #2726
=> Make remove-unused-globals remove non-static globals

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/HLSLFileCheck/hlsl/functions/arguments/inout_from_arg.hlsl
- Update existing optimization that skipped extra copying of inout call
args when passing a local var, to also skip when passing a function
argument.
=> Skip copy of inout args when coming from function arg

include/dxc/DXIL/DxilConstants.h, include/dxc/HLSL/DxilGenerationPass.h, include/llvm/Analysis/DxilValueCache.h, lib/Analysis/DxilValueCache.cpp, lib/HLSL/DxilPreparePasses.cpp, tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/wave/reduction/WaveBreakAndUnrollCS.hlsl
To allow loop unrolling, call instructions that reference dx.break()
are given a constant true boolean simplification in DxilValueCache.
This required making the constant string available by moving it into
Analysis.
As an incidental change, I corrected the spelling of simplify in a
couple cases.
=> Add simplify to DxilValueCache for dx.break()

include/dxc/dxcpix.h, lib/DxilDia/DxcPixDxilDebugInfo.cpp, lib/DxilDia/DxcPixDxilDebugInfo.h, lib/DxilDia/DxcPixDxilStorage.cpp, lib/DxilDia/DxcPixEntrypoints.cpp, lib/DxilDia/DxcPixLiveVariables.cpp, lib/DxilDia/DxcPixTypes.cpp, lib/DxilDia/DxcPixVariables.cpp
This is a direct implementation of a new API for PIX that shortcuts the large and unwieldy (and not-really-working-well) DIA equivalent to find the set of instructions that correspond to a given source location.
=> Pix source-to-instruction offsets

lib/HLSL/HLOperationLower.cpp, projects/CMakeLists.txt
1. A warning about unused "group" variable
2. A CMake warning about unmatched if and endif
=> Fix a couple warnings in code

include/dxc/Support/WinAdapter.h, lib/DxcSupport/WinAdapter.cpp
Move the declaration of UuidStrHash into #ifdef __EMULATE_UUID/#endif, and move its implementation to WinAdapter.cpp.
=> Fix the "unused function" warning caused by UuidStrHash

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/HLSLFileCheck/passes/hl/sroa_hlsl/memcpy_domuser.hlsl, tools/clang/test/HLSLFileCheck/passes/hl/sroa_hlsl/memcpy_preuser.hlsl, tools/clang/test/HLSLFileCheck/passes/hl/sroa_hlsl/memcpy_split_replace.hlsl, tools/clang/test/HLSLFileCheck/passes/hl/sroa_hlsl/memcpy_split_replace2.hlsl
By copying the code meant for memcpy used on global variables, I forced
recalculation of the DominatorTree for each and every memcpy. This
was pretty slow and entirely unnecessary. The global variables are
invoked from SROA_HLSL_Parameters, which is a module pass that doesn't
really know which function its dealing with until it addresses the
actual memcpy. SROA_HLSL already depends on the domination tree analysis
pass which allows the pass to draw from that for the dominator tree.
In addition, copying from the original code made use of a Post Dominator
Tree. This was a mistake. What we really want to know is if the source
dominates the uses of the destination. In practice, rarely would
anything be found to post dominate unless they shared a block. In the
contrived case where a memcpy post …
=> Correct DomTree usage in memcpy lowering

tools/clang/include/clang/Sema/SemaHLSL.h, tools/clang/lib/AST/HlslTypes.cpp, tools/clang/lib/Sema/SemaExpr.cpp, tools/clang/lib/Sema/SemaExprMember.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/lib/Sema/TreeTransform.h, tools/clang/test/HLSLFileCheck/hlsl/functions/arguments/arrayArgErr.hlsl, tools/clang/test/HLSLFileCheck/shader_targets/mesh/illegalOutIndicesAssignment.hlsl
When an output index array vector is accessed by element instead of the
whole, DXIL generation must produce an error. Previously, when the
access was performed using the dot operator, the error was produced, but
the processing wasn't terminated, so a second error erroneously saying
that the vector had no member by that name was also produced by falling
through to the struct processing. When the index was performed using a
numerical subscript, no error was produced at all and a crash resulted
when the indices were processed later.
By changing the interface for functions that process records that are
really HLSL Matrix, Vector or Array types, inapplicable structs can be
distinguished from expressions that result in an error and the error can
be returned, preventing the duplicate error.
A …
=> Return error on subscript access of index vector

lib/HLSL/DxilPreparePasses.cpp, tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp, tools/clang/lib/CodeGen/CGHLSLMSHelper.h, tools/clang/lib/CodeGen/CGHLSLRuntime.h, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/wave/reduction/WaveAndBreakMerge.hlsl
This includes a number of different changes to allow the dx.break
artificial branch conditional to function properly in different
situations that might arise as a result of optimization passes.
First of all, the dx.break usage is eliminated entirely for any function
found to not have need of it during code gen finishing. The dependencies
are not all clear at this stage, so it only determines if the function
makes use of any wave operations.
During the original dx.break elimination pass, the code allows for any
kind of instruction. This requires a bit more information about the user
of dx.break since the immediate user might not be a branch. So first the
dx.break users are traversed the same way that the wave users are. Then
the wave users are used to cull the list of dxbreak users. Then …
=> Handle more complicated dx.break circumstances

lib/HLSL/DxilPreparePasses.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/wave/reduction/WaveAndEmptyBreak.hlsl
After replacing an unneeded call to dx.break with a constant, the call
instruction remained. This removes it when it is replaced entirely.
Incidental optimization replacing ```getNumUses()``` with ```!use_empty()```
=> Erase dx.break call instruction when replaced

CMakeLists.txt, cmake/modules/FindD3D12.cmake, cmake/modules/FindDiaSDK.cmake, utils/hct/hctbuild.cmd
Add new options to hctbuild that enable passing in additional arguments to cmake invocation
and also cmake customization hooks that will be included at the beginning and end of DXC's cmake processing.
Rework library search in FindD3D12.cmake and add one more library to look for.
Fix case in FindDiaSDK.cmake - fixes a cmake warning.
=> CMake customization and bug fixes

tools/clang/lib/SPIRV/AstTypeProbe.cpp, utils/hct/hctbuild.cmd
Two issues.
1. When building with VS2019, -A<arch> is not set by hctbuild. It'll generate the project in x64, but set the TAEF path as x86, causing a linking problem.
1. A signed/unsigned mismatch warning (as error) in AstTypeProbe.
=> Fix compiling issues in x86 configuration

tools/clang/lib/CodeGen/CGExprConstant.cpp, tools/clang/test/HLSLFileCheck/hlsl/types/vector/constVecTrunc.hlsl
This adds implementations for HLSL vector and matrix truncation. Using
Constant classes to construct a constant vector or structure.
Incidental changes to vector and struct splatting to take advantage of
an existing operation for that purpose.
Adds a test for truncations and splats in constant expressions.
Fixes #2832
=> Support constant expression truncation

projects/dxilconv/unittests/DxilConvTests.cpp, utils/hct/hcttest.cmd
Adds an option to hcttest to specify a custom set of binaries to copy to a test folder
plus a custom location of dxilconv.dll.
=> hcttest.cmd: Enable specifying location of dxilconv.dll and custom set of binaries

tools/clang/test/HLSLFileCheck/hlsl/types/vector/constVecTrunc.hlsl
Debug adds a target for the entry that release doesn't. This accounts
for that slight discrepancy.
=> Correct Const vector truncation test for debug

lib/DxilDia/DxcPixLiveVariables_FragmentIterator.cpp, tools/clang/unittests/HLSL/PixTest.cpp
Previously, this fragment iterator would attempt to figure out offsets for each struct fragment by itself. This was error-prone and unnecessary: the debug info already has this information.
In particular, the old code didn't handle natural alignment and the possible dead space between fragments that this might create.
Unfortunately the debug info is pretty hard to parse: things with the "member" tag are a few layers of type above the basic type that they actually represent, and contained structs' members have offsets relative to the start of that contained struct, not to the start of the whole struct. Both of these necessitate a recursive approach.
Subsequent work: run these tests with and without -enable-16bit-types and with different optimization levels. The latter is blocked behind …
=> PIX: Rely on debug info for struct packing

lib/DxilPIXPasses/DxilDebugInstrumentation.cpp, lib/DxilPIXPasses/DxilPIXMeshShaderOutputInstrumentation.cpp
Previously, the counter-of-instrumentation-bytes-written for the shader debug pass was at offset zero into the UAV. This presented problems when overflow/wraparound occurred. This change moves the counter up into the unused overflow space in the UAV. The counter for the mesh shader output pass is moved to the same place for simplicity.
PIX bug # 26371771.
=> PIX: Move debug counter out of harm's way

lib/DxilRootSignature/DxilRootSignatureValidator.cpp, tools/clang/unittests/dxc_batch/dxc_batch.cpp
Possibly due to a visual studio update, building with vs2019 started
causing build failures due to using std::hex without the necessary
iostream include. This adds that include to the two files that need it.
=> Add iostream header to files using std::hex

docs/DXIL.rst, include/dxc/DXIL/DxilSigPoint.inl, lib/HLSL/HLSignatureLower.cpp, tools/clang/test/HLSL/system-values.hlsl, tools/clang/test/HLSLFileCheck/hlsl/semantics/sv_cullprimitive/cullprimitive.hlsl, utils/hct/hctdb.py
Allow SV_CullPrimitive to be declared on PS input so structures are more easily shared between mesh shader and pixel shaders.
This would just resolve to constant false if read, and won't appear in the input signature for the compiled shader.  So this is only a front-end change, not a change to DXIL.
=> Allow SV_CullPrimitive on PS input, resolve to false

tools/clang/include/clang/SPIRV/FeatureManager.h, tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/lib/SPIRV/FeatureManager.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/cf.discard.hlsl, tools/clang/test/CodeGenSPIRV/cf.discard.to-demote.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Generate OpDemoteToHelperInvocationEXT instruction only if
`-fspv-extension=SPV_EXT_demote_to_helper_invocation` is specified by
the user.
Fixes #2823.
=> [spirv] Update the SPIR-V codegen for HLSL discard.

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/HLSLFileCheck/passes/hl/sroa_hlsl/memcpy_gv.hlsl
The previous code was written under the belief that static globals
used as parameters couldn't result in a ReplaceMemCpy. They can when
they are not initialized to zero.
To handle this and any other circumstances that might result in a null
dominatortree, the function checking for user domination will regenerate
the dominatortree when necessary.
=> Handle null dominator tree in memcpy replace

lib/HLSL/HLOperationLower.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/ByteAddressBuffer/raw_buf4.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/ByteAddressBuffer/raw_buf5.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/ByteAddressBuffer/store_type_shapes.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/StructuredBuffer/rawbufferloadstore_64bit_6_2.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/StructuredBuffer/rawbufferloadstore_64bit_6_3.hlsl
Fixes #2263.
Note: This does not change StructuredBuffer case.  This is because view offset is in elements (struct strides), and that will have the alignment of the largest component type already.  Need to double-check on the buffer base address though.
Future work: Allow base alignment to be defined at buffer definition in HLSL to allow better than pessimistic alignment on load/store.
=> Don't claim alignment above 4 for raw buffer due to base

lib/Transforms/Scalar/DCE.cpp
Profiling this code showed significant wasted cycles removing potentially duplicated instructions from the center of the WorkList vector.
This PR moves to using an llvm::SmallSetVector to avoid unnecessary duplication and increase performance. A SmallSetVector is also used by the LLVM project here: https://github.com/llvm/llvm-project/blob/master/llvm/lib/Transforms/Scalar/DCE.cpp#L123 although the surrounding code is slightly different.
On a sample shader this change showed between a 1.5% to 2.5% reduction in total compile time.
=> Change std::vector to llvm::SmallSetVector for speed boost in DCE::runOnFunction

include/llvm/InitializePasses.h, include/llvm/Transforms/Scalar.h, include/llvm/Transforms/Utils/Local.h, lib/HLSL/DxcOptimizer.cpp, lib/HLSL/DxilNoops.cpp, lib/Transforms/IPO/PassManagerBuilder.cpp, lib/Transforms/Utils/Local.cpp, lib/Transforms/Utils/PromoteMemoryToRegister.cpp, tools/clang/test/HLSLFileCheck/dxil/debug/out_args.hlsl, utils/hct/hctdb.py
* Peeled the `restrict &` type off of `out` and `inout` arguments with `DxilRewriteOutputArgDebugInfo` pass before inlining.
* The inlined code have multiple `dbg.declare` pointing to the same alloca (since "out" args would refer to the same allocas as the variables passed in)
* Modified `PromoteMemoryToRegister.cpp` to allow multiple `dbg.declare` per alloca. The old behaviour was to throw all but one dbg.declares away. Now multiple variables can share a single alloca peacefully.
=> Fixed broken debug info for "out" and "inout" args.
