microsoft/DirectXShaderCompiler

include/dxc/DXIL/DxilUtil.h, include/llvm/IR/DiagnosticInfo.h, lib/DXIL/DxilUtil.cpp, lib/HLSL/HLSignatureLower.cpp, lib/IR/DiagnosticInfo.cpp, lib/Transforms/Scalar/DxilLoopUnroll.cpp, tools/clang/lib/CodeGen/CodeGenAction.cpp, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/AddUint64Odd.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/InnerCoverage.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/invalid_input_output_types.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/local_resource2.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/local_resource3.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/local_resource5.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/local_resource5_dbg.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/local_resource6.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/local_resource6_dbg.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/optForNoOpt3.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/optForNoOpt4.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/unsupported_error.hlsl
The existing diagnosticinfo and handler relied on a token for the source
location that isn't available to these locations. By creating
specialized versions, we can retrieve the information from where it is
available and convert it to the source location ID that allows the usage
of the existing diagnostic output complete with code snippets
=> Better post-CG error formats using custom diaginfo

include/dxc/DXIL/DxilConstants.h, include/llvm/Analysis/DxilValueCache.h, lib/Analysis/DxilValueCache.cpp, lib/HLSL/DxilPreparePasses.cpp, lib/Transforms/Scalar/DxilRemoveDeadBlocks.cpp, tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp, tools/clang/test/HLSLFileCheck/dxil/debug/new_noop_no_fold_double.hlsl, tools/clang/test/HLSLFileCheck/dxil/debug/new_noop_no_fold_int.hlsl, tools/clang/test/HLSLFileCheck/dxil/debug/new_noops_no_fold.hlsl, tools/clang/test/HLSLFileCheck/dxil/debug/new_noops_no_fold_vec.hlsl, tools/clang/test/HLSLFileCheck/dxil/debug/no_fold.hlsl, tools/clang/test/HLSLFileCheck/dxil/debug/no_fold_vec.hlsl, tools/clang/test/HLSLFileCheck/dxil/debug/noop_no_fold_double.hlsl, tools/clang/test/HLSLFileCheck/dxil/debug/noop_no_fold_int.hlsl, tools/clang/test/HLSLFileCheck/dxil/debug/noops_no_fold.hlsl, tools/clang/test/HLSLFileCheck/dxil/debug/noops_no_fold_vec.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/wave/reduction/WaveBreakAndUnrollCS.hlsl
This change modified DxilRemoveDeadBlocks to rewrite conditional branches to unconditional branches for cases even when no blocks are actually dead, so the cfg becomes simpler.
To avoid removing dx.break annotations, during compilation a special metadata was added to branches in dx.break blocks so DxilRemoveDeadBlocks knows not to rewrite them.
=> Simplifying branches to reduce complexity of cfg.

lib/DxilRootSignature/DxilRootSignatureValidator.cpp, tools/clang/unittests/dxc_batch/dxc_batch.cpp
It seems that a include is missing, when compiling I get this error: 
`DxilRootSignatureValidator.cpp(286,1) error C2039: 'hex' is not a member of 'std'`. I also get the same error on my CI.
Adding `#include <ios>` to DxilRootSignatureValidator.cpp seems to resolve the issue.
This error is similar to #2897
=> Missing import causing error on compilation

tools/clang/include/clang/SPIRV/AstTypeProbe.h, tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvFunction.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/lib/SPIRV/AstTypeProbe.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvFunction.cpp, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/test/CodeGenSPIRV/fn.param.unsized-opaque-array-o3.hlsl, tools/clang/test/CodeGenSPIRV/fn.param.unsized-opaque-array.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
When a function has a bindless opaque array type as its function
parameter, we have to use a pointer to a pointer of
`OpTypeRuntimeArray` e.g.,
`%_ptr_Function__ptr_UniformConstant__runtimearr_type_2d_image`.
This commit handles the bindless opaque array type argument
passing.
In addition, this commit drops `astParamTypes` of `SpirvFunction`.
`astParamTypes` is used only by lowering the parameter type of
a function type but we can replace it to `resultType` of
`parameters`, which makes the code simpler. Previously, whenever
we update the code for function parameters, we have to update
two places i.e., function type and parameters, but now we can
simply update the code handling parameters.
=> [spirv] handle bindless opaque array type argument passing

include/dxc/DxilContainer/DxcContainerBuilder.h, lib/DxilContainer/CMakeLists.txt, lib/DxilContainer/DxcContainerBuilder.cpp, tools/clang/tools/dxcompiler/CMakeLists.txt, tools/clang/tools/dxcompiler/dxcapi.cpp
- move from dxcompiler to DxilContainer.lib
- rename source file, move class definition to header file
- enable inheritance by changing microcom fields to protected
- enable AddPart for shader debug info
- move CreateDxcContainerBuilder to dxcapi.h to remove dependency
on DxilLibCreateInstance from DxcContainerBuilder.cpp
=> Dxil container builder refactor + bug fix

tools/clang/tools/dxa/dxa.cpp
Note this tool and others have horrible command line argument processing.  I fixed up dxr.exe a little while ago, but these could use a little more attention too.  Basically they crash or return without any message if anything isn't just right, and the arguments aren't consistent with the style of dxc.
This change doesn't fix all that, but at least if dxa fails it prints error messages now, and prints a success message telling you where it wrote the output if it succeeds.
=> Slightly improve dxa to print assembly errors and success/fail message

tools/clang/test/HLSLFileCheck/dxil/linker/TempReg.hlslh, tools/clang/test/HLSLFileCheck/dxil/linker/TempReg.ll, tools/clang/test/HLSLFileCheck/dxil/linker/use-TempReg.hlsl, tools/clang/unittests/HLSL/LinkerTest.cpp
Test linking to an assembled library that wraps TempRegLoad/TempRegStore, normally inaccessible from HLSL.  This pattern could also be extended to other intrinsic ops that cannot be directly, fully accessed using HLSL, such as the mul/div with two outputs and others.
=> Write and test example library for accessing TempRegLoad/TempRegStore

include/dxc/Test/DxcTestUtils.h, include/dxc/Test/HlslTestUtils.h, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp, utils/hct/hcttest.cmd
So far, the option only applies to `CompilerTest::*` tests that use `FileCheck`.  Dumps the `FileCheck` input to `<filename>.<num>.txt`, where `<filename>` is the input test filename, and `<num>` increments for each `RUN` line in the file.
Processing/filtering will still likely be needed to eliminate differences you don't care about, but it's a start.
Use with hcttest:
`hcttest -file-check-dump <target-path>`
=> Add option to dump FileCheck input to directory for diffing

include/dxc/Test/HlslTestUtils.h, projects/dxilconv/unittests/DxilConvTests.cpp, projects/dxilconv/unittests/dxilconv-tests.vcxproj.user.txt, utils/hct/hcttest.cmd
This was using a define before a header to change the option name.
An inline function used the define when adding the path to a filename.
Unfortunately, this header was included from multiple places with
different values defined for the variable name, and it seems that
sheer luck made it work for a while, even when called from a cpp
file that would have had it defined differently.
=> Use HlslDataDir for DxilConv instead of DxilConvDataDir

include/dxc/Support/HLSLOptimizationOptions.h, include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, include/llvm/Transforms/IPO/PassManagerBuilder.h, lib/DxcSupport/HLSLOptions.cpp, lib/Transforms/IPO/PassManagerBuilder.cpp, tools/clang/include/clang/Frontend/CodeGenOptions.h, tools/clang/lib/CodeGen/BackendUtil.cpp, tools/clang/test/HLSLFileCheck/passes/hl/gvn/disablegvn.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp
It can be helpful to disable an optimization pass or set of passes in
select circumstances. This adds the ability to disable the gvn pass
only, but introduces a way to disable various passes just by accepting
the chosen string to represent them in HLSLOptions and using the
DisablePasses values to determine when a pass needs to be left out in
PassManagerBuilder.
=> Add hidden flag to disable optimization passes

tools/clang/tools/dxclib/dxc.cpp
`#pragma comment(.., some.lib)` causes a build failure in some Linux
compilers. This commit disables it for Linux build.
=> Disable pragma in Linux build

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp, tools/clang/lib/CodeGen/CGHLSLMSHelper.h, tools/clang/lib/CodeGen/CGHLSLRuntime.h, tools/clang/lib/CodeGen/CGStmt.cpp, tools/clang/test/HLSLFileCheck/hlsl/control_flow/return/multi_ret.hlsl, tools/clang/test/HLSLFileCheck/hlsl/control_flow/return/whole_scope_returned_if.hlsl, tools/clang/test/HLSLFileCheck/hlsl/control_flow/return/whole_scope_returned_loop.hlsl, tools/clang/test/HLSLFileCheck/hlsl/control_flow/return/whole_scope_returned_switch.hlsl
For case like
if () {
...
return;
} else {
...
return;
}
both path is returned.
When whole scope is returned, the endScopeBB will be deleted in codeGen.
Add ScopeInfo::LegalizeWholeReturnedScope to update the whole returned scope's endScope to parent scope's endScope.
=> Support case whole scope is return.

appveyor.yml
`-cmd:` commands get executed only on Windows bots
`-sh:` commands get executed only on Linux bots
With this change we should hopefully have Linux build artifacts automatically uploaded and stored as well.
=> [ci] Build on Linux using Appveyor and upload artifacts

include/dxc/DXIL/DxilModule.h, include/dxc/DXIL/DxilOperations.h, include/dxc/HLSL/DxilGenerationPass.h, lib/DXIL/DxilModule.cpp, lib/DXIL/DxilOperations.cpp, lib/HLSL/CMakeLists.txt, lib/HLSL/DxcOptimizer.cpp, lib/HLSL/DxilLinker.cpp, lib/HLSL/DxilRenameResourcesPass.cpp, tools/clang/test/CodeGenHLSL/lib_res_bound1.hlsl, tools/clang/test/CodeGenHLSL/lib_res_bound2.hlsl, tools/clang/unittests/HLSL/LinkerTest.cpp, utils/hct/hctdb.py
- Add method to DxilModule to rename resources based on a prefix,
preventing resource merging during linking.
- Also one to rename by binding if desired.
- Add pass to access this resource renaming.
- Fix dxil intrinsic overload names when type disambiguation causes
types with same name to be renamed with .0+ suffix, but intrinsic
names remain in collision.
- Handle colliding intrinsic names with unique types in linker.
=> Add resource rename pass, dx op overload fix

tools/clang/lib/CodeGen/CGDebugInfo.cpp, tools/clang/test/HLSLFileCheck/dxil/debug/pound_line.hlsl, tools/clang/test/HLSLFileCheck/hlsl/control_flow/attributes/unroll/pound_line.hlsl
This change made the debug metadata store the original unprocessed source locations instead of the #line locations.
The debug metadata used to contain the #line locations, but since we use the source stored in the PDB instead of actual source files on disk, the debug info ended up mapping to non-existent files. Maybe when we could restore this old behaviour when debuggers support loading source files on disk.
This change also fixes error messages whenever there are #line directives. Since the error messages use the same mechanism to create location info as generating the debug info, they need the original unprocessed locations (rather than the #line locations).
=> Fixed #line issues with debug info and error messages

tools/clang/tools/dxclib/dxc.cpp, utils/hct/cmdtestfiles/inc2.hlsli, utils/hct/cmdtestfiles/include/inc1.hlsli, utils/hct/cmdtestfiles/smoke.hlsl
When recompiling, the dxc executable stores all file blobs under names
that use backslashes. However, when recompiling, the filenames of the
includes in a shader are joined with the directory using a forward
slash. In addition, many authors use forward slashes to separate
subdirectories in these includes. Because of this, no includes could
ever match.
By converting all / in the path to \ just before trying to retrieve the
associated pseudo-file, the file is found. Recompilation is only
supported on Windows presently, so other OS path dividers needn't be
considered.
Modify smoke.hlsl to verify that recompilation works
=> Enable recompile of shaders with includes in dxc

docs/SPIR-V.rst, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.fmod.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.intrinsic.hlsl
In HLSL fmod() function, first argument is used to deduce return value sign,
which is equivalent to spirv OpFRem, not OpFMod.
Please see the following documentation links for further reference.
https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-fmod
https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpFRem
=> [spirv] Fix incorrect opcode generation for fmod() function

tools/clang/lib/CodeGen/CGStmt.cpp, tools/clang/test/HLSLFileCheck/hlsl/control_flow/loops/midbreak.hlsl
Anything after a break should be ignored. An unconditional break
followed by additional statements was producing a basic block with a
branch that was not the final instruction.
By clearing the builder insertion point, all subsequent instructions in
the compound statement are completely ignored, making the branch the
final instruction as it should be.
Includes a simple test that verifies that no crash occurs and the
subsequent instructions are excluded.
=> Correct break followed by additional statements

include/llvm/ADT/ilist_node.h, tools/clang/test/HLSLFileCheck/validation/no_return_unreachable.hlsl
=> Avoid crash in ilist_node getPrev/getNext when Next/Prev is null

include/dxc/DXIL/DxilShaderModel.h, include/llvm/LinkAllPasses.h, include/llvm/Transforms/Scalar.h, lib/Analysis/DxilValueCache.cpp, lib/DXIL/DxilCounters.cpp, lib/DXIL/DxilShaderFlags.cpp, lib/DXIL/DxilShaderModel.cpp, lib/DxcSupport/FileIOHelper.cpp, lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp, lib/DxilPIXPasses/DxilPIXMeshShaderOutputInstrumentation.cpp, lib/HLSL/DxilNoops.cpp, lib/Transforms/IPO/Inliner.cpp, lib/Transforms/IPO/PassManagerBuilder.cpp, lib/Transforms/Scalar/DxilEliminateVector.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/CodeGen/CGCall.cpp, tools/clang/lib/CodeGen/CGDebugInfo.cpp, tools/clang/lib/SPIRV/RawBufferMethods.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/Sema/SemaAccess.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/atomic/umaxObjectAtomic.hlsl, tools/clang/tools/dxclib/dxc.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/tools/libclang/dxcrewriteunused.cpp
Many of these take the form of removing unused member variables and
unused functions. Where they were truly unused, I removed them. Where
they were only used in asserts, I hid them for the release builds. Where
the code in question was original to LLVM, I didn't remove so much as
comment out the offending code. In most cases these changes are
counterparts to already excluded code for HLSL.
A few cases concern indexing or type matches. Where relevant, I lifted
the same solutions in the current source of the llvm project.
I altered the fix made recently to LinkAllPasses.h. Instead of just
disabling the warning, I used the temporary variables that the current
llvm project uses to avoid having to cast null pointers.
=> Fix remaining Clang warnings

include/dxc/DXIL/DxilMetadataHelper.h, lib/DXIL/DxilMetadataHelper.cpp, lib/Transforms/Utils/Local.cpp, tools/clang/test/CodeGenHLSL/precise/precise_gvn.hlsl
We were not correctly preserving precise metadata when replacing instructions
in various transformations. This caused precise metadata to be dropped
when one a precise instruction was replaced with a non-precise instruction.
For example, given the two equivalent mul expressions
float x = mul(a, b)
precise float y = mul(a, b)
z = x + y
GVN would replace `y` with `x` in the computation of `z`. This caused x to
be computed in non-precise mode.
The fix is to make sure we combine known dxil metadata when replacing instructions.
=> Preserve precise metadata when replacing instructions in transformations

lib/Transforms/Scalar/DxilConditionalMem2Reg.cpp, tools/clang/test/HLSLFileCheck/dxil/debug/vs_output2.hlsl
In order to be able to insert a rewritten declare before the store that
uses it, the declare must be in the same scope as the store. In some
cases where the blocks are broken up a bit, this isn't the case.
By performing the check before making the call, the erroneous case is
avoided.
=> Avoid subprog mismatch inserting dbg value intrinsic

.travis.yml, appveyor.yml, include/dxc/DXIL/DxilInterpolationMode.h, include/llvm/ADT/PackedVector.h, include/llvm/IR/ValueHandle.h, lib/HLSL/HLOperationLowerExtension.cpp, lib/Transforms/Scalar/LoopStrengthReduce.cpp, tools/clang/lib/AST/ASTImporter.cpp, tools/clang/lib/CodeGen/CGBlocks.cpp
This fixes up the last of the clang warnings that are unique to clang 10.
These take two forms, First, indentation that might indicate the mistaken
impression that a line is within an unbraced conditional block produces
a warning and is corrected in a few places. Second, a warning is
produced when a class has one of copy constructor or assignment operator
explicitly defined and the other left to implicit definition. The
solution is generally to add a definition with the = default assignment.
Finally, this adds the -Werror flag to all clang builds to keep the
build warnings clean and detect flaws that can affect all builds and
platforms.
=> Enable warnings as errors for clang builds

lib/Option/Option.cpp, tools/clang/unittests/HLSL/OptionsTest.cpp
A frequent mistake is to pass arguments to the compiler API where the
option is in the same string as the value, separated by a space, such
as L"-T ps_6_0".  This is normally interpreted as a joined form of the
"-T" option, with the value being " ps_6_0" - note the leading space in
the value.  This is not intentional and leads to confusion.
This change handles the case where an option is either the SeparateClass
or JoinedOrSeparateClass, and it appears to be joined form, starting with
spaces.  It's more than likely this is the mistake, so the spaces are
skipped, and the value starts after the spaces.  If you really want a
value that starts with space, that value can still be provided by using
the separate option: L"-Fo", L" filename-starting-with-space.dxo".
=> Intuitively handle space in joined option syntax

lib/DXIL/DxilOperations.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/pixel/attr/attributeAtVertexInt.hlsl, utils/hct/hctdb.py
An oversight left out integer types for the attribute accessed by
GetAttributeAtVertex. This adds the integer indicator to the generation
script, which prevents the validation fail.
=> Allow integer attribs to GetAttributeAtvertex

tools/clang/include/clang/Basic/DiagnosticGroups.td, tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/HLSL/attributes.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/warnings/Wno-attribute-statement.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/warnings/Wno-attribute-type.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/warnings/Wno-comma-in-init.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/warnings/Wno-packoffset-override.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/warnings/Wno-specifier-override.hlsl
It is a well-known practice to treat warnings as errors to force developers to don't ignore compiler warnings. Sometimes some warnings are treated by developers as minors and compilers provide mechanisms to disable specific warnings. FXC for each warning has unique IDs which allows us to disable any warning. DXC on counterpart miss IDs for some HLSL specific warnings. This pull request introduces several new diagnostic groups and puts HLSL specific warnings without diagnostic groups in those new groups.
=> Put hlsl specific warnings in diagnostic groups

tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.cpp, tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.h, tools/clang/test/CodeGenSPIRV/vk.1p2.remove.bufferblock.runtimearray.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Removing BufferBlock and replacing Uniform to StorageBuffer
must be done for not only the struct type whose interface type
is StorageBuffer but also for an array or runtime array type whose
element type is such struct type.
Fixes #3035
=> [spirv] Remove BufferBlock for array types

projects/dxilconv/tools/dxilconv/dxilconv.cpp, tools/clang/tools/d3dcomp/d3dcomp.cpp, tools/clang/tools/dxcompiler/DXCompiler.cpp, tools/clang/tools/dxlib-sample/dxlib_sample.cpp, tools/clang/tools/dxrfallbackcompiler/DXCompiler.cpp
DisableThreadLibraryCalls acts as a no-op due to TLS section
=> Removing unnecessary DisableThreadLibraryCalls() calls

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/HLSLFileCheck/passes/hl/sroa_hlsl/memcpy_gv_and_bitcast.hlsl
In SROA, we create a GEP and later expect it to be an Instruction.
However, if the indices are all constant, it will return a constant
expression, which crashes hard. By setting the flag added for just this
purpose, this is avoided.
=> Avoid constant expr from GEP create

tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/sm6.wave-read-lane-at.hlsl, tools/clang/test/CodeGenSPIRV/sm6.wave-read-lane-at.vulkan1.2.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.intrinsic.vulkan1.1.hlsl
WaveReadLaneAt should be translated to OpGroupNonUniformShuffle, not OpGroupNonUniformBroadcast.
=> [spirv] Fix translation for WaveReadLaneAt.

include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/Frontend/CodeGenOptions.h, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/HLSLFileCheck/hlsl/control_flow/return/multi_ret.hlsl, tools/clang/test/HLSLFileCheck/hlsl/control_flow/return/whole_scope_returned_if.hlsl, tools/clang/test/HLSLFileCheck/hlsl/control_flow/return/whole_scope_returned_loop.hlsl, tools/clang/test/HLSLFileCheck/hlsl/control_flow/return/whole_scope_returned_switch.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp
This conforms to the established -opt-enable -opt-disable flag standard
to enable this optimization as well as tying in with the semantic
defines mechanism.
=> Modify structurize returns option to use opt-enable

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/lib/Sema/SemaOverload.cpp, tools/clang/test/HLSL/wave.hlsl, tools/clang/test/HLSLFileCheck/hlsl/functions/overloading/intrinsic_overloading.hlsl, tools/clang/test/HLSLFileCheck/hlsl/functions/overloading/intrinsic_overloading_errors.hlsl
In a couple of cases, intrinsics with parameters that weren't supposed
to allow casts were getting at least one parameter cast to a type not in
the accepted list.
Where an intrinsic referred to another parameter to determine
acceptable types, all parameters fed into a single parameter
representing the common type. If the first parameter was acceptable, but
the second wasn't, the second would get merged with the first regardless
of allowable casts. By checking the parameters before the merging is
performed, these failures are detected.
If an intrinsic call with valid arguments is followed by one
with invalid arguments, the second will be accepted and casts added to
convert to the existing intrinsic because it has already been added to
the list of possible overloads. By disallowing the …
=> Verify valid intrinsic parameter casts

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/rayquery_equal.cs.hlsl
Trying to add astcontext decls to the astDecls tables if decl is not
inserted at the beginning.
=> [SPIRV] Fix missing implicit decls

include/dxc/HLSL/HLSLExtensionsCodegenHelper.h, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp, tools/clang/lib/CodeGen/CGHLSLMSHelper.h, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/ExtensionTest.cpp
For structurize-returns, the codegenopts assigned were a copy of those
the compiler possesses. This is by design in clang as explicitly stated
in comments. As a result, when the compiler codegenopts are updated, the
codegenmodule's are not.
By adding the ability to query the optimization enables from the hlsl
extension helper, these options can be reflected.
Additionally, the structurize-returns flag would have required a define
with a '-' in it, which isn't possible. So now it converts between '_'
for defines and '-' for options, which is consistent with how other
flags are interpretted.
Adds a unit test similar to that of disable gvn that makes a simple
check to verify that the resturn structurization is enabled.
=> Correct codegenoption assigning from semantic defines

lib/HLSL/HLLowerUDT.cpp, lib/HLSL/HLMatrixLowerPass.cpp, lib/HLSL/HLMatrixSubscriptUseReplacer.cpp, lib/HLSL/HLMatrixSubscriptUseReplacer.h, lib/HLSL/HLSignatureLower.cpp, tools/clang/test/HLSLFileCheck/hlsl/types/matrix/matrix_subscript.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/matrix/matrix_subscript_ds.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/matrix/matrix_subscript_hs.hlsl
Matrix lowering was not handling subscript oeprations when the matrix
was a shader input. copying the matrix to a temporary explicitly or
implicitly as part of a copy in function call worked around the problem.
When the argument copy was eliminated, this problem was exposed.
By adding a load for the indicated matrix for a subscript of a shader
input matrix, the lowering can procede using the lowered matrix from the
load.
Additionally, hull shaders with their uninlineable functions were
failing to detect the constanthull function as a graphics function so
the subscript lowering was being treated as if it were in a library.
Even when it got to signature lowering, there was no support for
lowering matrix loads.
The test for shaderism now tests the function attributes of the module's
entry …
=> Add load for argument matrix subscript lowering

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/hs.pcf.output-patch.hlsl, tools/clang/test/CodeGenSPIRV/method.input-output-patch.access.hlsl
The existing code uses the Function storage class for the output patch
of a hull shader that will be used by the patch constant function.
DirectX automatically transmits the output patch to the all threads,
which are identical between threads. Even though Vulkan does not have
the patch constant function, we can simulate it using the execution
barrier and the variable with WorkGroup storage class.
Fixes #2641
=> [spirv] Hull shader output patch must be shared between threads

external/CMakeLists.txt
* SPIRV-Tools build has changed slightly
* SPIRV-Tools-static is now the target to use instead of plain
SPIRV-Tools
=> [spirv] Update SPIRV-Tools and SPIRV-Headers

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/method.rwtexture.load.invalid-residency-arg.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] Handle invalid arg for residency code.

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/ByteAddressBuffer/store_template_specification.hlsl
Prior to a more robust mechanism of handling types determined by
explicit templates in MatchArguments, a special case was made for
ByteAddressBuffer Loads that explicitly assigned the return type. When
the more robust mechanism was added as part of support for
ByteAddressBuffer Store, not only was this explicit assignment left in,
but it was also applied to the new Store method. The result was an
assert later on a store operation that is expected to return void.
By removing this now unneeded assignment, the assert no longer fires and
nothing else is changed sonce the return value was never read apart from
that anyway.
Fixes #2438
=> Remove unneeded rawbuf Ld/St return type reassign

include/llvm/Transforms/IPO/PassManagerBuilder.h, include/llvm/Transforms/Scalar.h, lib/Analysis/DxilValueCache.cpp, lib/HLSL/DxcOptimizer.cpp, lib/HLSL/DxilCondenseResources.cpp, lib/Transforms/IPO/PassManagerBuilder.cpp, lib/Transforms/Scalar/DxilLoopUnroll.cpp, tools/clang/include/clang/Frontend/CodeGenOptions.h, tools/clang/lib/CodeGen/BackendUtil.cpp, tools/clang/test/HLSLFileCheck/hlsl/control_flow/attributes/unroll/nested_update_counter.hlsl, tools/clang/test/HLSLFileCheck/hlsl/control_flow/attributes/unroll/nested_vector.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, utils/hct/hctdb.py
The vector operations are not completely removed until dxilgen lowers all HL operations and scalarizer is run. Without scalarizing, loop bounds that are part of vectors cannot be computed even if the elements are independent.
This change moves the unroll passes to after dxilgen and scalarizer.
Also made hlsl-dxil-allocate-resources-for-lib check for counter on UAV's. dxilgen used to be the one to set that flag, but that required unroll to have been run before it, otherwise it might find all the global UAV's since global resources have not necessarily been mapped to local resources yet. At hlsl-dxil-allocate-resources-for-lib, all the global resources are guaranteed to be mapped, so we wouldn't miss a counter update.
Fixes #2392
=> Moved unroll to after dxilgen and scalarizer.

include/dxc/DxilContainer/DxilPipelineStateValidation.h
This change:
- Adds a DxilPipelineStateValidation::CheckedReaderWriter to handle size calculation, reading/writing values, and mapping pointers/arrays to data, with more robust error checking than what was performed before (such as overflow checking).
- Replaces the three independent blocks of code for computing the size, writing data, and reading data, with a single function that does all three with the same code by using the CheckedReaderWriter in a particular mode.
The old code was tricky to maintain and update without introducing bugs.  The new code should be better.
=> Refactor PSV code for improved maintainability and error handling

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/texture.sample-invalid-implicit-lod.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Report an error when using implicit-lod sampling in non-fragment shaders for spirv codegen.
- The spirv legalization pass `replace-invalid-opcode` replaces texture sampling opcodes that expect implicit derivatives with a `0xDEADBEEF` constant for shader stages that don't support implicit derivatives (see https://github.com/KhronosGroup/SPIRV-Tools/blob/726af6f78f80988271c8b558ae9cc84fa5a65016/source/opt/replace_invalid_opc.cpp#L189). This traces a warning but is hard to oversee and definitely not in the programmers intend. Therefore, this pr triggers an error instead of requiring legalization when such an instruction is processed by the spirv emitter.
Addresses #2663
=> [spirv] Error on implicit-lod sampling in non-fragment shaders

include/dxc/DxilContainer/DxilPipelineStateValidation.h, lib/DxilContainer/DxilContainerAssembler.cpp, lib/DxilRootSignature/DxilRootSignature.cpp, lib/DxilRootSignature/DxilRootSignatureConvert.cpp, lib/DxilRootSignature/DxilRootSignatureSerializer.cpp, lib/DxilRootSignature/DxilRootSignatureValidator.cpp, lib/HLSL/DxilSignatureValidation.cpp, tools/clang/tools/dxcompiler/dxcdisassembler.cpp, tools/clang/unittests/HLSL/DxilContainerTest.cpp
Also:
- fixed size_t to uint32_t error when building with other tools.
- removed DxilPipelineStateValidation.h where unused.
=> Remove assert.h include from DxilPipelineStateValidation.h

lib/HLSL/HLMatrixLowerPass.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/HLSLFileCheck/hlsl/types/matrix/hs_static_mat.hlsl
Also lower ConstantAggregateZero directly when lower matrix.
=> Not init undef when recover init value for patch constant function.

lib/IR/LegacyPassManager.cpp
Made `-print-after-all` print directly to stderr instead of into the error buffer. This is a hidden debug feature that mainly helps compiler development. When debugging things that crash or fail the compilation, it's helpful to see history of the IR. It's also helpful for large shaders since we don't have to wait for the whole thing to finish to see the output.
=> -print-after-all directly prints to stderr.

appveyor.yml, cmake/modules/FindDiaSDK.cmake, utils/hct/hctbuild.cmd, utils/hct/hctstart.cmd
This PR is switching the default build of DXC to Visual Studio 2019.
The build script hctbuild.cmd will error when VS2019 is not installed. Use -vs2017 option to build with VS2017.
VS2015 is no longer supported.
Removes cmake version checking from hctstart.cmd
Fixes cmake detection in Visual Studio installations 
Fixes DIA SDK lookup - use CMAKE_GENERATOR to detect VS version used and select the corresponding DIA SDK
Use environment variable instead of c:\Program Files
=>  Enable Visual Studio 2019 build by default

lib/DxrFallback/readme.md
Caused by wrongly using backslash
=> Fix the redundant back-slash issue to make the link work in readme.md

utils/hct/hctbuild.cmd
These checks were there only to provide a nice error message when VS 2019 is not installed but it does not take into account that it can be installed at other locations than the default one. Removing these will still result in an error from cmake if it can't find Visual Studio installed.
Fixes #3151
=> Remove VS checks that assume Visual Studio is installed on C: drive

include/dxc/DXIL/DxilUtil.h, lib/DXIL/DxilUtil.cpp, lib/DxilPIXPasses/DxilAddPixelHitInstrumentation.cpp, lib/DxilPIXPasses/DxilDebugInstrumentation.cpp, lib/DxilPIXPasses/DxilPIXMeshShaderOutputInstrumentation.cpp, lib/HLSL/DxilCondenseResources.cpp, lib/HLSL/DxilEliminateOutputDynamicIndexing.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilLinker.cpp, lib/HLSL/DxilPreparePasses.cpp, lib/HLSL/HLMatrixLowerPass.cpp, lib/HLSL/HLMatrixSubscriptUseReplacer.cpp, lib/HLSL/HLOperationLower.cpp, lib/HLSL/HLSignatureLower.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/RayQuery/rayquery-array-2d-dynamic.hlsl, tools/clang/unittests/HLSL/ValidationTest.cpp
Instead of skipping past allocas whenever inserting a new insruction,
which ate up a lot of compilation time, they are inserted at the default
insertion point.
The result is that allocas that would have coalesced just after the
global load and input loads are dispersed throughout the commands. So as
part of dxil finalization, the allocas are moved to the beginning of the
entry block of each function. This results in some minor changes to a
couple tests due to the allocas preceding the loads.
=> Optimize compile times by not skipping allocas

tools/clang/lib/SPIRV/InitListHandler.cpp, tools/clang/lib/SPIRV/InitListHandler.h, tools/clang/test/CodeGenSPIRV/initializelist.rwbyteaddressbuffer.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
RWByteAddressBuffer object in the initList should be handled like
OpaqueType RWBuffer or Texture2D.
=> [spirv] Fix issues of RWByteAddressBuffer in the InitList

lib/DxcSupport/dxcmem.cpp
When dxilconv initialization fails in InitMaybeFail (for example under memory pressure) the malloc references are null yet  DxcClearThreadMalloc is called expecting non-null references.
Adds nullptr checks to DxcClearThreadMalloc before erasing and releasing the allocators.
=> Fix dxilconv crash when initialization fails

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/texture.sample.invalid.tex2d.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Calling tex2D must report an error but the multiplication using it
crashes instead of an error report.
Fixes #3166
=> [spirv] report error for invalid tex2d multiplication

lib/DxilPIXPasses/DxilDebugInstrumentation.cpp
A simple change to allow PIX to debug shaders with DispatchRay calls. Previously, the instrumentation would attempt to cast the handle to an integer and store the result in the UAV. The nvidia driver, at least, disliked this notion and declared device-removed.
=> PIX: Don't attempt to write ray query handles to the debug trace UAV

cmake/modules/FindDiaSDK.cmake
- Build platform is not included generator string for VS2019; use CMAKE_GENERATOR_PLATFORM instead
- Use release version of VS by default
=> DIA SDK lookup fixes

include/dxc/DXIL/DxilUtil.h, lib/DXIL/DxilUtil.cpp, lib/DxilPIXPasses/DxilAddPixelHitInstrumentation.cpp, lib/DxilPIXPasses/DxilDebugInstrumentation.cpp, lib/DxilPIXPasses/DxilPIXMeshShaderOutputInstrumentation.cpp, lib/HLSL/DxilCondenseResources.cpp, lib/HLSL/DxilEliminateOutputDynamicIndexing.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilLinker.cpp, lib/HLSL/DxilPreparePasses.cpp, lib/HLSL/HLMatrixLowerPass.cpp, lib/HLSL/HLMatrixSubscriptUseReplacer.cpp, lib/HLSL/HLOperationLower.cpp, lib/HLSL/HLSignatureLower.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/RayQuery/rayquery-array-2d-dynamic.hlsl, tools/clang/unittests/HLSL/ValidationTest.cpp
Reverts microsoft/DirectXShaderCompiler#3168
breaks some external users.
=> Revert "Optimize compile times by not skipping allocas"

tools/clang/lib/CodeGen/CodeGenAction.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/Texture/assign_texture_error.hlsl
When reporting a globalvariable associated error message without -Zi,
an attempt is made to report the associated function, but there was no
check to see if that function existed, so it crashed.
Fixes #2989
=> Correct GV error message crash

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/rich.debug.scope.after.compound.statement.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Before/after handling a compound statement i.e., `{ .. }`, we have to
add DebugScope for the lexical scope updates. We added it before
handling a compound statement, but we did not add it after doing it.
This commit adds a DebugScope after handling a compound statement.
=> [spirv] add DebugScope after compound statement

README.md
The previous instructions would have users go to appveyor and click on the platform and find the "Artifacts" tab and click download. I have added direct links to the download zip files.
=> Make it easier to see (and download) artifacts

include/dxc/dxcpix.h, lib/DxilDia/DxcPixDxilDebugInfo.cpp, lib/DxilDia/DxcPixDxilDebugInfo.h, lib/DxilDia/DxcPixEntrypoints.cpp
The impetus for this was a recent change that modified how dx.source.contents was filled out.
But, on the plus side, I'd wanted to do this forever so that PIX is pretty much ready to stop using DIA altogether (and we'll be able to delete the DIA implementation from dxcompiler).
Tests exist in the PIX repo (which broke, which is how I noticed this :-) ).
=> PIX: Add an API to retrieve source location from RVA

tools/clang/test/HLSLFileCheck/pix/DbgValueToDbgDeclare.hlsl, tools/clang/test/HLSLFileCheck/pix/DebugBasic.hlsl, tools/clang/test/HLSLFileCheck/pix/DebugFlowControl.hlsl
These tests had gone stale while I wasn't looking.
The numeric value of disassembled "undef" arguments appears to be something other than 0 now.
The syntax for multiple prefixes in FileCheck <string> is now -check-prefixes and not --check-prefixes .
No longer need to check value-to-declare pass' workaround for a fixed bug.
=> Fix PIX file-check tests (no product impact)

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvFunction.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvFunction.cpp, tools/clang/test/CodeGenSPIRV/fn.noinline.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
This PR will add `DontInline` function control flag to the OpFunction in generated SPIR-V if the function has `[noinline]` in HLSL shader.
This is the first step of work for #3158.
After the `DontInline` flag is added, spirv-opt needs an option to control whether it should honor the flag or not (it ignores the flag currently), and the option should be passed down by DXC.
=> [SPIR-V] Add noinline support for SPIR-V generation

include/dxc/HLSL/DxilGenerationPass.h, include/dxc/HLSL/DxilNoops.h, include/llvm/Analysis/DxilSimplify.h, lib/Analysis/DxilSimplify.cpp, lib/Analysis/DxilValueCache.cpp, lib/Analysis/InstructionSimplify.cpp, lib/HLSL/CMakeLists.txt, lib/HLSL/DxcOptimizer.cpp, lib/HLSL/DxilNoOptLegalize.cpp, lib/HLSL/DxilNoops.cpp, lib/Transforms/IPO/PassManagerBuilder.cpp, lib/Transforms/Scalar/DxilRemoveDeadBlocks.cpp, tools/clang/test/HLSLFileCheck/passes/dxil/dxil_o0_legalize/selects.hlsl, tools/clang/test/HLSLFileCheck/passes/dxil/dxil_o0_legalize/store_undef.hlsl, tools/clang/test/HLSLFileCheck/passes/dxil/dxil_remove_dead_pass/dxil_ops.hlsl, tools/clang/test/HLSLFileCheck/passes/dxil/dxil_remove_dead_pass/store_only.hlsl, utils/hct/hctdb.py
- Fixed value tracking for dxil intrinsics
- Fixed some selects holding on to invalid resource uses
- Fixed some cases where unused globals hold on to invalid resource uses
- Fixed some cases where stores of undefs stick around
=> Fixed some cases where O0 fails compilation

lib/HLSL/HLLegalizeParameter.cpp, lib/HLSL/HLOperationLower.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/HLSLFileCheck/shader_targets/library/lib_arg_flatten/lib_empty_struct_arg.hlsl, tools/clang/test/HLSLFileCheck/shader_targets/library/lib_skip_copy_in.hlsl, tools/clang/test/HLSLFileCheck/shader_targets/raytracing/raytracing_raydesc_from_cbuffer.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
Skip extra arg copies in codegen, but copy when matrix orientation change
must be captured for call.
Copy what's necessary for translation around external calls, like cbuffer,
in HLLegalizeParameter.
This fixes cbuffer RayDesc case as well.
Also fixes issue with -file-check-dump.
=> Skip extra argument copying at callsite for library targets

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/op.sizeof.same.for.init.and.return.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
```
struct StructA
{
float3 one;
float3 two;
};
```
`sizeof(StructA)` must be 24 bytes. `AlignmentSizeCalculator` with a void
memory layout will return 32 bytes for it. We have to use the constant
folding provided by Clang.
Fixes #3198
=> [spirv] handle sizeof using Clang's const folding

tools/clang/lib/AST/ASTContextHLSL.cpp, tools/clang/test/CodeGenSPIRV/vk.push-constant.constantbuffer.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
This commit fix a regression introduced by #3147: when`[[vk::push_constant]]` is apply to a  ConstantBuffer, error shows that `'push_constant' attribute only applies to global variables of struct type`.
=> [spirv] Fix [[vk::push_constant]] on ConstantBuffer

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/decoration.coherent.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
globallycoherent on resource variables should result in decoration Coherent in generated SPIR-V.
=> [spirv] globallycoherent should generate SPIR-V decoration Coherent

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/test/CodeGenSPIRV/vk.push-constant.constantbuffer.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
I wasn't noticing that the last fix #3215 only fixed the error-checking. It was generating an OpTypeStruct without any member.
This commit fixes that push constant should use the templated type of constant buffer to create the struct.
=> [spirv] Fix [[vk::push_constant]] on ConstantBuffer part II

tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.h, tools/clang/test/CodeGenSPIRV/rich.debug.debugdeclare.hlsl, tools/clang/test/CodeGenSPIRV/rich.debug.debugdeclare.without.init.hlsl, tools/clang/test/CodeGenSPIRV/rich.debug.scope.after.compound.statement.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.branch.hlsl
The current DXC emits `OpLine` for the first instruction in the location
and does not emit the same `OpLine` for the following instructions.
However, it does not specify the end of the effectiveness of the
`OpLine`, which is technically wrong based on the spec of OpLine and
OpNoLine. We have to specify the `OpLine` is not applied to the
following instructions when we meet an instruction without the location
information.
=> [spirv] wrap instructions with OpNoLine

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/test/CodeGenSPIRV/rich.debug.debugdeclare.hlsl
This commit adds the SourceLocation to SpirvDebugDeclare class that will
result in emitting the OpLine for the declaration (where the declaration
happens). It will help the spirv-opt to preserve the value assignment
location. In particular, it will be useful for simple shaders that
spirv-opt almost strips out all the instructions and keeps only
DebugValue instructions. We can recognize the location of value
assignments based on OpLine.
=> [spirv] add location for DebugDeclare

lib/HLSL/DxilCondenseResources.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilLinker.cpp, lib/HLSL/DxilPreparePasses.cpp, lib/HLSL/HLMatrixLowerPass.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
Many places that previously relied on skipallocas to find the right
place for a non-alloca instruction are replaced with at least the
attempt to find a valid location depending on conditions. This is a
piecemeal case by case determination. The exception is the SROA pass
which made heavy and necessary use of the skipallocas call. Instead, at
the end of the pass, allocas are shuffled to the top of the entry block.
PIX passes are ignored here because they are not involved in the compile
time complaints and I'm unfamiliar with the circumstances when they are
invoked.
=> New approach to avoid skipallocas

lib/Transforms/Scalar/DxilRemoveUnstructuredLoopExits.cpp, tools/clang/test/HLSLFileCheck/hlsl/control_flow/loops/struct_exit_exit_value.hlsl
Removed the limitation in structurize loop exit where values exiting a loop has to dominate loop latch.
Rather than threading just the exit condition through the blocks, do the same for all the exiting values.
=> Made exit values not have to dominate latch in structurize loop exit

tools/clang/lib/Sema/SemaHLSL.cpp
When not initialized, an unlikely, but possible set of circumstances
could produce spurious warnings.
=> Initialize conversion remarks result

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/test/CodeGenSPIRV/rich.debug.debugdeclare.hlsl
Reverts microsoft/DirectXShaderCompiler#3230
- I considered this change for a while. I think it is weird that DebugDeclare has a line instruction
because DebugDeclare must be not control-dependent by the [definition](
https://llvm.org/docs/SourceLevelDebugging.html#llvm-dbg-declare) i.e., the declaration is
effective in the scope of the local variable regardless of its location. This revert will let DXC
not emit the OpLine for DebugDeclare.
=> Revert "[spirv] add location for DebugDeclare"

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/HLSLFileCheck/dxil/debug/as_payload_debug.hlsl
Note that this debug info was lost only when the payload struct used was a local variable, which shouldn't be the common case, since the idea is to cooperate across threads to construct a single payload in groupshared memory, rather than constructing a payload in per-thread (local) memory, then only using the one from the first thread.
=> Fix lost debug info on DispatchMesh payload in AS

tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.end.of.shader.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
For some cases, spirv-opt removes all line information because of the
optimization. Emitting at least a single OpLine helps debuggers know it
is the end of the shader execution.
=> [spirv] emit OpLine at the end of entry function

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSLFileCheck/hlsl/functions/arguments/inout_trunc.hlsl
Previously, trying to pass a scalar to a vector out parameter would
cause an assert and no truncation warning. This scales back the assert
and adds the missing warning.
Trying to pass a scalar to an inout parameter would cause a crash. This
allows for the necessary splat and avoids the erroneous attempts to
create a cast that leads to the crash.
Finally, as an incidental, this adds output parameter information to an
error that ostensibly required it, but never had it.
=> Handle scalar args to out vector params

include/dxc/Support/WinAdapter.h, lib/DxcSupport/WinAdapter.cpp
While this prefix may be an implementation detail the `BSTR` type guarantees to be able to store `NULL` values without accidentally truncating the string, hence its length must be available to replace the usual `NULL` terminator.  This string length in bytes is stored in the four bytes preceding a `BSTR `pointer [1], whose value can be retrieved using `SysStringLen`.
This commit implements the type in the same way in `WinAdapter` such that users of the functions returning a `BSTR` (currently only in `dxcisense`) can expect and use the type in the same way on Linux as they would on Windows.
While this function and type currently only seem to be involved in names and logging where `NULL`s are unlikely, it is good practice to mirror the Windows type exactly for future-proofing.
Besides, …
=> Linux: Implement prefix-counted BSTR allocation in SysAllocStringLen

tools/clang/include/clang/SPIRV/AstTypeProbe.h, tools/clang/lib/SPIRV/AstTypeProbe.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resources.1.hlsl
Fixes #3169.
hlsl::IsResourceType does not cover SubpassInput (which is
vulkan-specific).
=> [spirv] Use isResourceType to cover SubpassInput.

tools/clang/tools/libclang/dxcisenseimpl.cpp, tools/clang/tools/libclang/dxcisenseimpl.h
When running valgrind over a program using `DxcIntelliSense` (to validate our own deallocations [1]) a bunch of mismatching `new` with `free()` show up:
Mismatched free() / delete / delete []
at 0x483B9AB: free (vg_replace_malloc.c:538)
by 0x52B06A8: IMalloc::Free(void*) (WinAdapter.cpp:34)
by 0x6DC7D19: DxcTranslationUnit::Release() (dxcisenseimpl.h:308)
by 0x14278E: com_rs::unknown::IUnknown::release (unknown.rs:55)
[...]
Address 0x4c3c930 is 0 bytes inside a block of size 40 alloc'd
at 0x483B07F: operator new(unsigned long, std::nothrow_t const&) (vg_replace_malloc.c:385)
by 0x6DC06EB: DxcIndex::ParseTranslationUnit(char const*, char const* const*, int, IDxcUnsavedFile**, unsigned int, DxcTranslationUnitFlags, IDxcTranslationUnit**) (dxcisenseimpl.cpp:1192)
by 0x13020A: …
=> dxcisense: Allocate "TM" classes using IMalloc instead of new

include/dxc/Support/HLSLOptions.td, tools/clang/test/HLSLFileCheck/passes/llvm/simplifycfg/fold-cond-branch-on-phi.hlsl
- The flag is supposed to be temporary.
- Also remove check that was accidentally left in from a test.
=> Move force-zero-store-lifetimes flag to help-hidden

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/cf.return.memory-layout.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
For a function `ReturnType foo( .. ) { .. return value; }`, if the type
of value has a memory layout, `value` cannot be used for the operand of
OpReturnValue because of the type mis-match. Note that the `ReturnType`
for the return value must have a void memory layout (i.e., unknown).
This CL converts the type of the return value if it has an explicit
physical memory layout.
Fixes #3247
=> [spirv] convert return type if memory layout is different

lib/HLSL/HLOperationLower.cpp, tools/clang/test/HLSLFileCheck/hlsl/operators/swizzle/swizzleAtomic2.hlsl
Saying that typed buffers are not supported is inaccurate. Scalar types
are required for it to work though.
=> Reword misleading type buffer atomic error message

include/dxc/dxcapi.h, include/dxc/dxcapi.internal.h, include/dxc/dxctools.h, lib/HLSL/DxilContainerReflection.cpp, tools/clang/tools/dxcompiler/dxcapi.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp
This is a preliminary PR for #3062 as [requested](https://github.com/microsoft/DirectXShaderCompiler/pull/3062#discussion_r527084241) by @pow2clk to make the review diff more digestible.
=> Remove unnecessary trailing whitespace in files touched by #3062

tools/clang/include/clang/SPIRV/FeatureManager.h, tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/lib/SPIRV/CapabilityVisitor.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.h, tools/clang/lib/SPIRV/FeatureManager.cpp, tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.cpp, tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/test/CodeGenSPIRV/binary-op.mul-assign.type-mismatch.hlsl, tools/clang/test/CodeGenSPIRV/fn.export.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.ctrl.line.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.ctrl.unknown.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp, tools/clang/unittests/SPIRV/FileTestFixture.cpp, tools/clang/unittests/SPIRV/FileTestFixture.h, tools/clang/unittests/SPIRV/FileTestUtils.cpp, tools/clang/unittests/SPIRV/FileTestUtils.h, tools/clang/unittests/SPIRV/WholeFileTestFixture.cpp, tools/clang/unittests/SPIRV/WholeFileTestFixture.h
DXIL could export functions with export attribute while spirv would
ignore such functions. Currently glsl spirv does not have linkage
export decorate. so the exported function would be treated as normal
function while add dummy entry point according to the spirv validations
=> [SPIRV] Add support hlsl export function attribute

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/bezier.hull.hlsl2spv, tools/clang/test/CodeGenSPIRV/hs.const.output-patch.hlsl, tools/clang/test/CodeGenSPIRV/hs.pcf.output-patch.hlsl, tools/clang/test/CodeGenSPIRV/method.input-output-patch.access.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
This CL lets DXC create a immediate variable with `Output` storage class
for the constant output patch of a hull shader instead of using `Workgroup`
storage class because a variable with `Workgroup` storage class is not
allowed in a Vulkan tessllation shader.
Fixes #3248
=> [spirv] do not use WorkGroup storage class for hull shader output patch

lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp, tools/clang/unittests/HLSL/PixTest.cpp
A customer provided a shader that uses many language features that the value-to-declare pass couldn't handle:
-member functions
-resource variables
-arguments passed by pointer
-struct inheritance
Note the highly "creative" method used to determine if a type is a resource- by name string compare. Unfortunately there isn't a cleaner way to do this based on type alone.
These changes aren't the end of this road: GS output payloads aren't covered. Resource types are merely worked-around, not turned into debuggable variables that PIX can display.
Also, these changes disturbed the DIA debug lines reporting, which isn't used by PIX anymore so I just deleted that test case rather than fix it. (A future checkin will delete the DIA implementation properly.)
=> PIX: Update debugging passes for certain language features

lib/HLSL/HLOperationLower.cpp, tools/clang/lib/Sema/SemaHLSL.cpp
the VK namespace change introduced some variables and defines that are
used in areas not protected by the same ifdefs that protect the
declarations. As a result, where this wasn't defined, builds and hearts
were broken. </3
=> Add conditionals around vk namespace usage

tools/clang/unittests/HLSL/ExecutionTest.cpp
Presently, lifetime markers are only generated for 6.6
=> Make lifetimes test use 6.6

lib/DxilDia/DxilDiaSymbolManager.cpp, lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp
A customer couldn't recompile their large shader with -Od for debugging in PIX.
-The symbol manager would quit early, so now it continues to discover other variables
-The value-to-declare pass was adding an incorrect debug location, which tripped up the verifier.
=> PIX: Fixes for symbol manager and value-to-declare pass for recompiling to -Od

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp
Corrected disabling compute shader and incorrect indices.
Removed test that attempted to confirm that the indepenent samples would
match where the derivatives were the same. First of all, they weren't as
the same as intended. Second, even with that corrected, position in
quads affected the LOD calculation. The check was beyond the intended
scope of this test anyway.
Improved comments describing the function of this test
=> Correct ComputeSample Execution Test

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/fn.forward-declaration.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] Forward declaration of function inside another.

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/raytracing.khr.closesthit.hlsl, tools/clang/test/CodeGenSPIRV/raytracing.nv.anyhit.hlsl, tools/clang/test/CodeGenSPIRV/raytracing.nv.closesthit.hlsl
Fixes #3322
`HitTKHR` was [removed] from the spec as it merely shadows `RayTmaxKHR`. Emitting it results in invalid SPIR-V:
generated SPIR-V is invalid: Operand 3 of Decorate requires one of these capabilities: RayTracingNV
OpDecorate %6 BuiltIn HitTNV
Replace the builtin by `RayTmaxKHR` if `NV_ray_tracing` is not enabled to resolve this.
[removed]: https://github.com/KhronosGroup/SPIRV-Headers/commit/bdd2aa34c450edb77441c82fdc2f20f1dc9d833d
---
Is this valid in all of the [cases outlined here](https://docs.microsoft.com/en-us/windows/win32/direct3d12/raytcurrent)? I assume - given that that commit says it shadows `RayTmax` anyway, likely also on NV - that the max is updated upon hit?
=> SPIR-V: Emit RayTmaxKHR builtin for RayTCurrent IOP

tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/lib/SPIRV/CapabilityVisitor.h, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.64bit-interlocked-methods.cs.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.64bit-interlocked-methods.ps.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Note: This doesn't add 64-bit atomic functions for `RWByteAddressBuffer`s. That will be done in a separate PR.
=> [spirv] Support 64-bit interlocked intrinsics.

tools/clang/unittests/HLSL/ShaderOpTest.cpp
Where there's no render target, the runtime throws errors if you try to
retrieve the gpu descriptor handle.
=> Skip gpudescriptorhandles where there is no RTV

tools/dxexp/dxexp.cpp
To report support correctly, it needs to start with 6.6 and work
backward.
=> Update dxexp to 6.6

lib/Transforms/Scalar/DxilRemoveUnstructuredLoopExits.cpp, tools/clang/lib/CodeGen/BackendUtil.cpp, tools/clang/test/HLSLFileCheck/hlsl/control_flow/loops/struct_exit_disable.hlsl
Also:
- Replaced undefs with 0's for numeric types.
- Fixed a bug in loop exit structurizer where exit values don't dominate users.
=> Enabled loop exit structurizer by default.

tools/clang/tools/dxcompiler/dxcpdbutils.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
Since we want to use it to query shader hash and PDB path.
=> PDB Util shouldn't fail on DXIL with no debug info

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/ShaderOpTest.cpp, tools/clang/unittests/HLSL/ShaderOpTest.h
The ShaderOpTest code for mesh shaders had a lot of problems. This
corrects the initialization of the pipeline and the dispatch.
In addition, there were various problems with ExecutionTests for atomics
where mesh shaders were used. This adds testing for mesh results that
was being skipped. This required adjustment of the indices.
Also required was proper accumulation of groupshared values between
amplification and mesh shaders.
Various and sundry indexing corrections were also required.
=> Fix mesh and groupshared in ExecutionTest

tools/clang/lib/CodeGen/CGDecl.cpp, tools/clang/test/HLSLFileCheck/validation/UndefConst.hlsl
Previously, codegen attempted to skip the alloca creation that would
be encountered below and just emit the constant init. However, the
code in EmitAutoVarDecl() first checks whether the Init is null using
isTrivialInitializer() and just bails if it is.
This adds the isTrivialInitializer() call to the conditions here
since we fallback to the alloca if there is no constant initializer.
=> Don't create static global for uninited local const

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSLFileCheck/hlsl/namespace/texture_in_namespace.hlsl
Builtin object types such as Texture2D add all their object methods
to the associated decl context when they are first seen. However,
previously, if the code meant to effect that was found in a namespace
it would skip this addition. This removes that restriction so that
the methods can be added and then found when needed.
Fixes #2472
=> Allow adding object methods when in namespace

projects/dxilconv/lib/DxbcConverter/DxbcConverter.cpp, projects/dxilconv/lib/DxbcConverter/DxbcConverterImpl.h
Future work would be confused by current meaning of Set/GetHandle
on DxilResourceBase, which didn't make sense anyway for this narrow
use case limited to DxilConv.
This change replaces that use with a local handle Value* cache keyed off
of the resource class and slot.
This is valid only for SM 5.0 and below, where the cache applies.
It can't be used generally for SM 5.1, which is an existing limitation,
so no change here.
=> DxilConv: localize caching of handles instead of storing in resource obj

tools/clang/lib/SPIRV/FeatureManager.cpp, tools/clang/test/CodeGenSPIRV/raytracing.target-env-error.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
In absence of any extensions, ray tracing is only available on Vulkan 1.2 and later.
Without `-fspv-target-env`, dxc was incorrectly printing a message that "Vulkan 1.1 was required", where in fact Vulkan 1.2 is required.
=> [spirv] Fix target env error message.

tools/clang/lib/SPIRV/AstTypeProbe.cpp, tools/clang/test/CodeGenSPIRV/op.sizeof.hlsl
The code `int foo; .. size(float) * foo` causes failure because
`getElementSpirvBitwidth()` in AstTypeProbe.cpp does not handle the type
of `sizeof()` which is the "unsigned long" type. This commit handles it.
Fixes #2814
=> [spirv] Fix failure caused by multiplying size() and int

tools/clang/unittests/HLSL/CompilerTest.cpp
A recent change produces a warning, which is sometimes interpretted as
an error, causing builds to fail
=> silence sign warning on some systems

tools/clang/include/clang/SPIRV/SpirvFunction.h, tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.cpp, tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.h, tools/clang/test/CodeGenSPIRV/vk.1p2.remove.bufferblock.ptr-to-ptr.example2.hlsl, tools/clang/test/CodeGenSPIRV/vk.1p2.remove.bufferblock.ptr-to-ptr.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] Fix storage class for ptr-to-ptr in Vulkan 1.2.

tools/clang/include/clang/SPIRV/AstTypeProbe.h, tools/clang/lib/SPIRV/AstTypeProbe.cpp, tools/clang/lib/SPIRV/RelaxedPrecisionVisitor.cpp, tools/clang/test/CodeGenSPIRV/decoration.relaxed-precision.bool.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] Don't apply RelaxedPrecision to ops operating on bools

lib/HLSL/WaveSensitivityAnalysis.cpp
The wave sensitivity analysis should produce a result for any relevant
instruction. It fails in some cases, which is a bug. However, the result
of that bug shouldn't be intermittent incorrect errors as it is now.
When a result isn't found, assume that there is no wave sensitivity. The
assert is kept and might produce a warning ultimately. This is meant to
add a guard rail to the worst case scenario.
=> Defined behavior on all wave sensitivity outcomes

lib/HLSL/DxilContainerReflection.cpp
In the original code, there are chances to compare an iterator from m_CBsByName to m_StructuredBufferCBsByName.end(). It crashes if _ITERATOR_DEBUG_LEVEL is not 0. Fix it by comparing an iterator to the container it's from.
=> Fix a crash in reflection when comparing a container's iterator with another's

docs/SPIR-V.rst, tools/clang/include/clang/Basic/Attr.td, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenSPIRV/vk.attribute.error.hlsl, tools/clang/test/CodeGenSPIRV/vk.attribute.shader-record-ext.invalid.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.shader-record-ext.std430.hlsl, tools/clang/test/CodeGenSPIRV/vk.shader-record-ext.hlsl, tools/clang/test/CodeGenSPIRV/vk.shader-record-ext.offset.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
I added support for the Shader Record buffer for the Khronos extension.
The code is adapted from [this](https://github.com/microsoft/DirectXShaderCompiler/pull/2179) previous merge.
It should fix this issue #3177
=> [spirv] Added support for [[vk::shader_record_ext]]

lib/DxilPIXPasses/CMakeLists.txt, lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp, lib/DxilPIXPasses/DxilDebugInstrumentation.cpp, lib/DxilPIXPasses/PixPassHelpers.cpp, lib/DxilPIXPasses/PixPassHelpers.h
These handles are just integers, but drivers compile them to ? and don't like it when you try to store them somewhere in a UAV.
PIX bug #31509503.
=> PIX: Shader debug: don't instrument ray query handles

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp
While the tests were not accounting for the z coord, the number of
expected results was, leading to an attempt to verify uninitiatized
values. These uninitialized values failed to match the expected results
in all but the most infinitescimally improbable cases
=> correct quad2D compute samp test result count

tools/clang/test/HLSL/ShaderOpArith.xml
The AS/MS shader stages were overwriting each other's groupshared output,
and were not using the expected per-thread index when offsetting into
buffers and groupshared memory. Instead, follow the pattern of
AtomicsTest and use the payload data to convey groupshared data between
AS and MS, and use unique ranges of per-thread indices for each stage.
Also make AtomicsFloatTest an SM 6.6 test.
=> Fix AS/MS/PS interaction for AtomicsFloatTest

lib/HLSL/HLSignatureLower.cpp, tools/clang/test/HLSLFileCheck/shader_targets/mesh/matVertexStOutput_colmajor.hlsl, tools/clang/test/HLSLFileCheck/shader_targets/mesh/matVertexStOutput_rowmajor.hlsl
The lowering code for generating `StoreVertexOutput` had a bug for matrix type where vertex id was not added to the argument list when creating a call to `StoreVertexOutput` dxil op function. This was causing a crash due to a mismatch in the number of expected arguments for the dxil op.
Fixes #3341
=> Fix handling of matrix in StoreVertexOutput

tools/clang/unittests/HLSL/ExecutionTest.cpp
A change to silence warnings mistakenly cast a 64-bit value down to
32-bit. This corrects the cast.
=> Cast 64-bit test value to int64_t

lib/HLSL/HLOperationLower.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/StructuredBuffer/struct_buf_mat_load_method.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/StructuredBuffer/struct_buf_mat_subscript_method.hlsl
Fixes three issues related to lowering of structured buffer load. 
The first one is a crash in templated structured buffer load on matrices of size > 4 when using `.Load()` method. The same worked fine for subscript-based loads. For the case of subscript-based loads, the matrix type is not lowered to vector type in `HLMatrixLower`. This allows special handling of matrix type in `HLOperationLower` as the type information is preserved. For the `.Load()` method case, the matrix type is lowered to vector type in `HLMatrixLower` itself. Therefore in the `HLOperationLower` pass, the lowering of matrix-load using the `.Load` method was getting treated as just another load of vector type and was causing a crash when the component count of vector exceeds 4 (in case of matrices).  This PR refactors …
=> Fix issues with structured buffer load lowering

lib/DXIL/DxilCounters.cpp
Noticed a crash because of this while running PIX tests and then narrowed it down with appverif's full page-heap.
The previous "PI" variable was pointing into nowhere because the recursion could cause the map's contents to be reallocated.
"PI" could have been used safely in a few of these places, but rather than spot-fix it, I removed the use of this variable in order to preclude this class of bug from the other locations which I may or may not be exercising in my tests.
=> Fix memory corruption in DxilCounters.cpp

tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/AppendStructuredBuffer/append_mat_col_major.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/AppendStructuredBuffer/append_mat_row_major.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/ConsumeStructuredBuffer/consume_mat_col_major.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/ConsumeStructuredBuffer/consume_mat_row_major.hlsl
The lowering code for `Append()` and `Consume()` methods in `AppendStructuredBuffer` and `ConsumeStructuredBuffer` was inserting LLVM `store` and `load` instructions even for matrix type. This was causing a crash in HLMatrixLowerPass as it would expect  `matLdSt.colLoad` or `matLdSt.rowLoad`  for matrix loads and similarly `matLdSt.colStore` or `matLdSt.rowStore` for matrix stores. This PR handles the matrix types appropriately in the lowering code.
Fixes #1778.
=> Fix crashes with handling of matrix type in append/consume

tools/clang/test/HLSLFileCheck/hlsl/objects/ConsumeStructuredBuffer/consume_mat_col_major.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/ConsumeStructuredBuffer/consume_mat_row_major.hlsl
The change in #3462 introduced changes in the ordering of `rawBufferLoad` dxil op. This necessitates updates in a couple of tests added as part of #3460. Both changes went in parallel which is why the tests missed the update.
=> Update append/consume tests

tools/clang/test/HLSLFileCheck/hlsl/resource_binding/bindings_ms.hlsl, tools/clang/tools/dxcompiler/dxcdisassembler.cpp
The code meant to add an integer to the string indicating the dimension
of the resource binding didn't convert it to a string resulting in a
corrupted string.
Adds a test as well
Fixed #3335
=> Correct disasm printing of sized tex2dms

tools/clang/test/CodeGenSPIRV/fn.param.isomorphism.hlsl, tools/clang/test/CodeGenSPIRV/rich.debug.debugsource.multiple.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.function.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.include-file-3.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.include.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.intrinsic.hlsl, tools/clang/test/CodeGenSPIRV/type.enum.hlsl
`groupshared` variables must not be used in pixel shaders.
This commit removes groupshared variables from unit tests with PS.
=> [spirv] remove groupshared from tests with PS

tools/clang/unittests/HLSL/ExecutionTest.cpp
The warp check doesn't always catch situations where warp is in use.
This modifies it to include all the cases by comparing the adapter as
well.
=> Check for basic adaptor for unsupported warp test

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.check-access-fully-mapped.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample-bias.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample-cmp-level-zero.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample-cmp.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample-grad.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample-level.hlsl, tools/clang/test/CodeGenSPIRV/texture.load-invalid-offset-operand.hlsl, tools/clang/test/CodeGenSPIRV/texture.load.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-bias.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-cmp-level-zero.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-cmp.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-grad.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-invalid-implicit-lod.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-invalid-offset-operand.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-level.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
The new spirv-val rule reports an error if we use a variable (not
`OpConst*`) operand for `Offset` operation of `OpImage*` instructions
other than `OpImage*Gather`:
https://github.com/KhronosGroup/SPIRV-Tools/pull/4118
This CL also let the DXC SPIR-V backend report an error if it checks
the HLSL code uses a variable for the `offset` operand of `Sample*`
and `Load*` built-in methods.
It aligns with the DXIL or FXC behavior. They do not accept a variable
for the `offset` operand of `Sample*` built-in methods.
=> [spirv] do not accept variable for OpImage* Offset

tools/clang/test/HLSL/ShaderOpArith.xml
The render target was unnecessary huge causing failures on Microsoft Basic Render Driver
(which supports Barycentrics in newer Windows versions).
=> Fix BarycentricsTest

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp
Simple fix to test `dx.op.isHelperLane` in driver compiler when testing SM 6.6.
=> HelperLaneTestWave: Compile shaders for SM 6.6 when testing SM 6.6

include/dxc/DXIL/DxilUtil.h, lib/DXIL/DxilUtil.cpp, lib/HLSL/DxilCondenseResources.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilLinker.cpp, lib/HLSL/DxilValidation.cpp, lib/HLSL/HLSignatureLower.cpp
Under certain rare circumstances, it is possible for errors to be
reported for function or global variables that are null.
This eliminates the absolute necessity for a non-null function or GV by
passing in the context needed to report any error. It also avoids some
of the cases where trying to get a debug function would give a null
which would replace the non-null function.
=> Fix crashing from null elements producing errors

lib/Transforms/Utils/InlineFunction.cpp
When trying to fixup line numbers when inlining a function, if the call
instruction had no debug location, the DIsubprogram was queried. That
query took a very long time and was pointless when there is no debug
info.
The code now checks for debug metatdata before trying to get the
disubprogram
Fixes #3130
=> Avoid trying to get disubprogram without debug MD

tools/clang/unittests/HLSL/ExecutionTest.cpp
At some point, these tests were disabled because they didn't run on
WARP. They do now, so I'm enabling them.
Additionally, tests that depend on 6.3 don't need to hide behind a lower
priority, they should be conditional on the availability of shader model
6.3. They still don't run on WARP since it doesn't support 6.3, but they
should run where that support is reported.
=> Enable exec tests for 6.2 that warp supports

lib/DXIL/DxilShaderFlags.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/pixel/attr/attributeAtVertex.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/pixel/attr/attributeAtVertexInt.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/pixel/attr/attributeAtVertexNoOpt.hlsl, tools/clang/test/HLSLFileCheck/hlsl/semantics/sv_barycentrics/barycentrics.hlsl, tools/clang/test/HLSLFileCheck/hlsl/semantics/sv_barycentrics/barycentrics1.hlsl
A Dxil shader flag should be added when SV_Barycentrics semantic is
used. It was defined and member variables created for it, but it wasn't
actually set.
=> Add barycentric shader flag when used

tools/clang/unittests/HLSL/ExecutionTest.cpp
Replace the temporary runtime check for SM66 tests with the proper SKD
check
=> Replace placeholder sm66 runtime check

tools/clang/unittests/HLSL/ExecutionTest.cpp
On devices without native 16-bit support, PackUnpackTest fails to run.  Check and skip the test when unsupported.
D3D12 ERROR: ID3D12Device::CreateComputeShader: Shader uses native 16bit ops, but the device does not support this. To check for support, check device caps via the CheckFeatureSupport() API [ STATE_CREATION ERROR #622: CREATESHADER_INVALIDBYTECODE]
=> Fix PackUnpackTest on HW without 16-bit support

lib/DXIL/DxilModule.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/Buffer/uav64.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/Buffer/uavArray64.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/Buffer/uavUnboundArray64.hlsl
The 64UAV flag is meant to indicate that 9 or more UAVs are in use.
Previously, each UAV was considered as one regardless of range. By
adding up the ranges, we get a more accurate determinatiohn.
Fixes: #2964
=> Consider ranges when counting UAVs for 64UAV

tools/clang/test/HLSLFileCheck/hlsl/types/modifiers/groupshared/groupshared_shadermodels.hlsl
The order of globals() is inconsistent. Since this test depends on that
order, it fails sometimes. By removing the individual characterists of
the errors, the issue is resolved.
=> Resolve groupshared test order reporting issue

lib/DXIL/DxilUtil.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/NonUniformDynamic.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/annotateHandle.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/createFromHeap.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/createFromHeap2.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/createFromHeap3.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/createFromHeap4.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/dynamic_res_global_for_lib.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/dynamic_res_global_for_lib2.hlsl
- SROA was not skipping handle type, now present with dynamic resources
changes, or ConstantBuffer<> / TextureBuffer<> types, as it should.
- Updated unit tests to add combinations of -Od and -Zi.
=> Fix Dynamic Resources when used with -Od

docs/DXIL.rst, include/dxc/DXIL/DxilResource.h, include/dxc/DxilContainer/DxilPipelineStateValidation.h, lib/DXIL/DxilResource.cpp, lib/DxilContainer/DxilContainerAssembler.cpp
To identify resources that are used in 64-bit atomics operations in order to catch invalid use of heap resources
=> Add used by atomics resource flag

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp
Refactor Derivatives test to be clearer, more correct, and more in
keeping with the original intent. Center index is now nearer the center.
Conversion of 2D index to 1D is now correct for the quad layout.
Dispatch sizes are separated by CS, Mesh, and undefined results to make
testing easier and more complete.
Also adds the 2D quad formats while adapting 1D variants to be correct
with the latest spec
=> DerivativesTest: quad2D layout and refactor

tools/clang/lib/CodeGen/CGHLSLMS.cpp
These asserts are not needed, because we skip lowering unsupported store types anyways.
=> Remove unneeded asserts

include/dxc/DXIL/DxilConstants.h, include/dxc/DXIL/DxilMetadataHelper.h, include/dxc/DXIL/DxilResourceProperties.h, include/dxc/DXIL/DxilShaderFlags.h, lib/DXIL/DxilMetadataHelper.cpp, lib/DXIL/DxilResourceProperties.cpp, lib/DXIL/DxilShaderFlags.cpp, lib/HLSL/DxilCondenseResources.cpp, lib/HLSL/DxilValidation.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/atomic/atomic_i64_dynamic_resource.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/atomic/atomic_i64_heap_resource.hlsl, tools/clang/tools/dxcompiler/dxcdisassembler.cpp
When a resource comes from a binding, we can't determine if it is on a
heap or not, so we set a flag on it to let the runtime sort it out.
When a resource comes from the heap directly, we know it's on the heap
so we set the shader flag to check for platform support.
=> 64-bit atomics usage resource flags

lib/DXIL/DxilShaderFlags.cpp
C++17 removes these function templates. they aren't needed anyway
=> Remove unneded, incompatible function inheritance

include/dxc/DxilContainer/DxilRuntimeReflection.h, lib/DXIL/DxilShaderFlags.cpp, lib/DxilContainer/DxilContainerAssembler.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/atomic/atomic_i64_root_resource.hlsl
The previous shader flag code failed to account for the library-specific
handle creation function
=> Correct atomics on heap usage for libs

docs/SPIR-V.rst, tools/clang/include/clang/Basic/Attr.td, tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/include/clang/SPIRV/SpirvContext.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/include/clang/Sema/AttributeList.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/lib/SPIRV/LowerTypeVisitor.h, tools/clang/lib/SPIRV/SpirvContext.cpp, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenSPIRV/vk.attribute.image-format.hlsl, tools/clang/test/CodeGenSPIRV/vk.attribute.image-format.o3.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
According to Vulkan specification when using `OpImageRead/OpImageWrite`, the `OpTypeImage` (`Buffers`, `RWBuffers`, `RWTextures`) must have a format that matches the format on the API side, unless the StorageImageReadWithoutFormat/StorageImageWriteWithoutFormat is added and `Unknown` is used as the format.
This pull request addressess #2498 for the format part by adding an attribute `[[vk::image_format("<image format as spelled in SPIR-V spec>")]].` Example of the syntax:
```
[[vk::image_format("rgba8")]]
RWBuffer<float4> Buf;
[[vk::image_format("rg16f")]]
RWTexture2D<float2> Tex;
RWTexture2D<float2> Tex2; // Works like before
```
The `image_format` only applies to **global variables** of type `Buffer`, `RWBuffer`, `RWTexture`. For variables and function parameters it is propagated by the …
=> [spirv] Add vk::image_format attribute for Buffers, RWBuffers and RWTextures

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp
To test the flag indicating support for 64-bit atomics on heap
resources, the groupshared and raw tests are here altered to use root
descriptors. An nearly identical raw buffer test is kept for heap
testing and the typed resources, requiring heap support implicitly, is
unaltered. 32-bit testing, encompassing typed resources and all else,
are kept in the typed variants
Renamed a few things to make the names less confusing.
=> Split atomics tests into heap/root types

tools/clang/unittests/HLSL/ShaderOpTest.cpp
ShaderOpTest::CreatePipelineState needs to check the return code from ID3D12Device2::CreatePipelineState so failures immediately stop here.
Otherwise we might get a failure in a subsequent call like when CommandListRefs::CreateForDevice() calls ID3D12Device::CreateCommandQueue() - this one will fail with return code 0x887a0005 - The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
=> Add CHECK_HR around CreatePipelineState

lib/Transforms/Scalar/Scalarizer.cpp, tools/clang/test/HLSLFileCheck/passes/llvm/scalarizer/argument_scatter.hlsl
An unrelated earlier change mistakenly removed the return on a line
calling the Scatterer constructor for an argument value. As a result,
the constructor is called, but the resulting object which would insert
new extraction ops in the entry block is not used at all. Instead,
the default case is encountered where the vector PHI op is used as an
insertion point, which places the extractions after the new scalar PHIs
that use them. This is caught in the loop case by an assert because the
assumptions that caused LCSSA to be skipped for this BB are faulty.
=> Return Scatterer object for argument values

lib/HLSL/WaveSensitivityAnalysis.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/wave/reduction/WaveSensitivityAndCycles.hlsl
Cycles in the dependency graph can result in phis and other instructions
failing to get a wave sensitivity result after analysis. This can only
happen when nothing in the loop has wave sensitive operations.
By collecting phis that are unknown and marking them as non-sensitive
after analyze is complete and rerunning it, we can correctly evaluate
their dependants too.
Because incompletely processed blocks might still be wave-sensitive,
unknown phis are only added to be reprocessed when their preds have all
be processed fully.
In addition to cycles preventing wave sensitivity determination on
dependant operations, they can prevent entering blocks that depend on
values with cyclic dependencies. Even when reprocessing all unknown
phis, this can result in not all values getting a determination. …
=> Infer wave-sensitivity of cyclic dependencies

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/unbound_unbound_init.hlsl
Comparing two unbound arrays where one was initilizing the other
resulted in infinitely incrementing both and never reaching a
conclusion.
This adds detection to FlattenedTypeIterator for the situation whereupon
the comparison is terminated and the result returned.
A simple test of the assignment is added expecting the correct error.
=> Fix unbound arrays flattened type compare

lib/Transforms/Scalar/Scalarizer.cpp, tools/clang/test/HLSLFileCheck/passes/llvm/scalarizer/argument_scatter.hlsl
An unrelated earlier change mistakenly removed the return on a line
calling the Scatterer constructor for an argument value. As a result,
the constructor is called, but the resulting object which would insert
new extraction ops in the entry block is not used at all. Instead,
the default case is encountered where the vector PHI op is used as an
insertion point, which places the extractions after the new scalar PHIs
that use them. This is caught in the loop case by an assert because the
assumptions that caused LCSSA to be skipped for this BB are faulty.
(cherry picked from commit bb5dc9fdb070d031fea4d57cb9165307cdac0be8)
=> Return Scatterer object for argument values (#3540)

tools/clang/include/clang/SPIRV/AstTypeProbe.h, tools/clang/lib/SPIRV/AstTypeProbe.cpp, tools/clang/test/CodeGenSPIRV/decoration.relaxed-precision.array.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Currently, arrays of min16float etc. types don't get a RelaxedPrecision decoration for the OpVariable. This has some real performance implications since at least some hardware can fit more RelaxedPrecision variables into registers, and maybe also groupshared memory.
This pull request add the missing RelaxedPrecision decoration for OpVariables of array types in a similar way vector and matrix minimum precision types are already handled.
=> [spirv] Generate RelaxedPrecision decorations also for arrays of minimum precision variables

tools/clang/unittests/HLSL/ExecutionTest.cpp
Technically, the test matched the spec, but the D3D header didn't. I'm
more interested in making this work than who was right though ;)
=> Rename 64-bit atomic heap resource support bit

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/HLSLFileCheck/passes/hl/sroa_hlsl/memcpy_split_regression.hlsl
Fixed a bug where allocas of aggregates might get left behind by the HLSL SROA pass. In O0 there's no other SROA pass running, so the allocas last all the way to the end and fail validation.
HLSL SROA fails to clean these up because `LowerMemcpy` returns true when `ReplaceMemcpy` returns true, even when there could be reads. SROA assumes when `LowerMemcpy` returns true, the whole alloca is not used anymore, and ends up not splitting it.
Here's an example:
```
a = alloca MyStruct
b = alloca MyStruct
c = alloca MyStruct
...
memcpy(b, a, sizeof(MyStruct))
...
memcpy(c, b, sizeof(MyStruct))
```
When `LowerMemcpy` is working on `b`, `ReplaceMemcpy` replaces the memcpy with loads and stores and returns true:
```
a = alloca MyStruct
b = alloca MyStruct
c = alloca MyStruct
...
b->member1 = …
```
=> Fixed some potential O0 failures

include/dxc/Test/DxcTestUtils.h, tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp
Merge some FileCheckerTest improvements:
- VFS captures output files for duration of test, enabling:
- %dxl test IDxcLinker
- add -D to FileCheck args to supply defined variables
- report failing RUN command when not consumed by FileCheck or XFail
=> FileChecker improvements: VFS, %dxl, FileCheck -D, error reporting

lib/DXIL/DxilResourceProperties.cpp, lib/HLSL/DxilContainerReflection.cpp, tools/clang/test/HLSLFileCheck/d3dreflect/texture2dms.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/annotateHandle.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/createFromHeap3.hlsl, tools/clang/test/HLSLFileCheck/hlsl/resource_binding/props_ms.hlsl, tools/clang/tools/dxcompiler/dxcdisassembler.cpp, tools/clang/unittests/HLSL/DxilContainerTest.cpp
- Fix missing component type and count for Texture2DMS in ResProps
- Fix reflection for Texture2DMS with default NumSamples
Fixes #2788
=> Texture2DMS fixes: missing ResProp data; reflection default NumSamples = 0

lib/HLSL/HLMatrixLowerPass.cpp, tools/clang/test/HLSLFileCheck/hlsl/types/matrix/unused_static_global_matrix_array.hlsl
A global static const (involving aggregate type) gets replaced in SROA Param HLSL pass if there are valid users. However, if it is dead, then it gets optimized away later in Global Variable Optimizer (globalopt) pass. This PR updates a misfiring assert in HLMatrixLowering pass to cover the case where a constexpr with no users is allowed as it gets trivially deleted in this pass.   
Fixes #3579
=> Fix a misfiring assert due to unused static const involving matrix type

tools/clang/lib/Sema/SemaExpr.cpp, tools/clang/test/HLSL/array-index-out-of-bounds-HV-2016.hlsl, tools/clang/test/HLSL/attributes.hlsl, tools/clang/test/HLSL/builtin-types-no-inheritance.hlsl, tools/clang/test/HLSL/conversions-non-numeric-aggregates.hlsl, tools/clang/test/HLSL/incomp_array_err.hlsl, tools/clang/test/HLSL/indexing-operator.hlsl, tools/clang/test/HLSLFileCheck/validation/rawbufferstore_uav.hlsl, utils/hct/VerifierHelper.py
- Fix const error check for object subscript operator
- update tests and VerifierHelper.py
Fixes #3572
=> Fix const error check for object subscript operator

tools/clang/lib/CodeGen/CGExprConstant.cpp, tools/clang/test/HLSLFileCheck/hlsl/types/cast/constexpr/constexpr_cast_mat_scalar.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/cast/constexpr/constexpr_cast_mat_type_stack_oveflow_bug.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/cast/constexpr/constexpr_cast_mat_types_same_comp_count.hlsl
Fix a bunch of issues (described below) related to constexpr cast involving matrix types. Also refactor redundant code into a separate function `ExtractConstantValueElems` for better clarity.
**Issue 1:**
We were not handling below component conversion cast for matrix type:
```
CK_HLSLCC_FloatingCast:
CK_HLSLCC_IntegralCast:
CK_HLSLCC_IntegralToBoolean:
CK_HLSLCC_IntegralToFloating:
CK_HLSLCC_FloatingToIntegral:
CK_HLSLCC_FloatingToBoolean:
```
**Issue 2:**
We were not handling cast of kind `CK_HLSLMatrixToScalarCast`:
**Issue 3:**
We were not handling `ConstantAggregateZero` type for `CK_HLSLMatrixTruncationCast` cast kind.
All of the above issues were causing compiler crashes.
Fixes #3041 
Fixes #3590
=> Fix constexpr cast involving matrix type

tools/clang/unittests/HLSL/ShaderOpTest.cpp, tools/clang/unittests/HLSL/ShaderOpTest.h
Because version 6 of the command list pointer was being created whenever
the available SDK supported it, sometimes the test would try to create
version 6 where it wasn't supported.
Instead, this just stores the base pointer type and casts it up where we
know support is available.
=> ShaderOpTest limit commandlist6 to where supported

include/dxc/Support/FileIOHelper.h, lib/DxcSupport/FileIOHelper.cpp, tools/clang/tools/dxcompiler/dxcpdbutils.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
Initializing args for old PDBs (where sources and args are inside the debug module) was going through a different code path, where arg pairs were not being initialized. This change fixes that.
=> Fixed arg pairs not correct for old source in module pdbs

tools/clang/unittests/HLSL/ExecutionTest.cpp
An earlier version of the D3D runtime doesn't handle CheckFeatureSupport
for FEATURE_SHADER_MODEL when the corresponding struct is set to a
unrecognized shader model. Instead of returning the highest supported
shader model that is less than the one provided as documented, the call
fails. In practice, this only occurred for 6.6 tests where the SDK had
6.6 capability, but the installed runtime did not.
To work around this, we don't verify that the call succeeds. Instead,
a failing return result is interpretted the same way as when the highest 
shader model value returned is lower than that requested.
=> Exec test - WAR SM feature check on older runtime

include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, include/llvm/Support/ErrorHandling.h, lib/DxcSupport/HLSLOptions.cpp, tools/clang/tools/dxclib/dxc.cpp
The most common cause of internal compiler errors are access violations
or stack overflows. This registers an exception handler in dxc.exe for
these cases that are otherwise unhandled. It prints a simple message
for these errors and passes the exception along.
In case this is unwanted for some reason, a hidden disabling flag is
added as well.
=> Add dxc exception handler

tools/clang/tools/dxclib/dxc.cpp
The size of ULONG_PTR varies based on the address size of the
architecture. For 32-bit systems, it was invalid to treat it like a
64-bit value. By casting the value to a void pointer and changing the
print code to %p, we get the right thing for all platforms
=> Correct exception handler sprintf for 32-bit

tools/clang/lib/Sema/SemaDXR.cpp
Some compilers (gcc) get really unhappy when your field name matches the
type name. In the defense of such, it does make you wonder what sizeof()
would return if the member were not of its namesake's type.
Anyway, gcc should be able to build. This renames the member to differ
from the type to make all the Gnus happy.
=> Rename payload qualifier field to not match type

tools/clang/unittests/HLSL/ExecutionTest.cpp
- was only run on SM 6.6 supporting devices
- would only run SM 6.6 tests in experimental mode, compiling with -Vd
- wasn't specifying options required to test lifetime fallback paths
=> Fix LifetimeIntrinsicTest issues

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/use.rvalue.for.member-expr.of.array-subscript.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
The newly introduced template support generates a template instance
of a struct method that has a slightly different AST from the one
with hard-coded type. The template instance misses LValueToRValue
cast for an array index. This PR lets SPIR-V backend uses rvalue for
an array index. If the array index expression is not rvalue, it reports
an error.
Fixes #3553
=> [spirv] use rvalue for array index

docs/DXIL.rst, include/dxc/HLSL/DxilValidation.h, lib/DXIL/DxilModule.cpp, lib/HLSL/DxilValidation.cpp, tools/clang/test/CodeGenHLSL/basic.hlsl, tools/clang/unittests/HLSL/ValidationTest.cpp, utils/hct/hctdb.py
- Move validator/dxil version checks up-front
These should fail first rather than side effects of trying to validate
details of a version we don't support.
- Improve message for unsupported validator or dxil version
These errors are most likely if compiling separately from validation
and failing to override the validator version properly, or running on
an external validator that doesn't support a newer dxil.
- Use dxil version from metadata for DxilModule when loading,
rather than just setting it to minimum based on shader model.
- Remove TODO from validator messages that shouldn't be there
(cherry picked from commit 6244ab83371d57a579a05cd9da17fa67537f3e4b)
=> Validator/Dxil version error improvements (#3623)

tools/clang/test/HLSL/ShaderOpArith.xml
The 32-bit atomics test variant was requiring a UAV type unnecessarily.
By using structured buffers for groupshared output, this dependency is
removed.
=> Remove unneeded atomicstest dependency

tools/clang/test/HLSL/ShaderOpArith.xml
The 32-bit atomics test variant was requiring a UAV type unnecessarily.
By using structured buffers for groupshared output, this dependency is
removed.
(cherry picked from commit 73a6706a6f6c6116e12d83d1a00b660d51705cb2)
=> Remove unneeded atomicstest dependency (#3631)

lib/DxilPIXPasses/DxilAddPixelHitInstrumentation.cpp, lib/DxilPIXPasses/DxilDebugInstrumentation.cpp, lib/DxilPIXPasses/DxilOutputColorBecomesConstant.cpp, lib/DxilPIXPasses/DxilPIXMeshShaderOutputInstrumentation.cpp, lib/DxilPIXPasses/DxilShaderAccessTracking.cpp, lib/DxilPIXPasses/PixPassHelpers.cpp, lib/DxilPIXPasses/PixPassHelpers.h
This is little more than a move of the "create-uav" code in lib/DxilPIXPasses/DxilShaderAccessTracking.cpp to PixPassHelpers.cpp, followed by a factoring-out of the parts that create a handle (either pre-SM6.6 fashion, or with the newer create-from-binding etc.).
All the other passes' near-identical code was then deleted and made to call the centralized function.
=> PIX passes: Centralize handle-generation code and update for 6.6

lib/DxilPIXPasses/DxilAddPixelHitInstrumentation.cpp, lib/DxilPIXPasses/DxilDebugInstrumentation.cpp, lib/DxilPIXPasses/DxilOutputColorBecomesConstant.cpp, lib/DxilPIXPasses/DxilPIXMeshShaderOutputInstrumentation.cpp, lib/DxilPIXPasses/DxilShaderAccessTracking.cpp, lib/DxilPIXPasses/PixPassHelpers.cpp, lib/DxilPIXPasses/PixPassHelpers.h
This is little more than a move of the "create-uav" code in lib/DxilPIXPasses/DxilShaderAccessTracking.cpp to PixPassHelpers.cpp, followed by a factoring-out of the parts that create a handle (either pre-SM6.6 fashion, or with the newer create-from-binding etc.).
All the other passes' near-identical code was then deleted and made to call the centralized function.
(cherry picked from commit ea1efe96ba4aa70d1522d14e00a21c69aa6f0b97)
=> PIX passes: Centralize handle-generation code and update for 6.6 (#3628)

tools/clang/tools/dxa/CMakeLists.txt, tools/clang/tools/dxa/dxa.cpp, tools/clang/tools/dxv/CMakeLists.txt, tools/clang/tools/dxv/dxv.cpp
- Set up missing thread malloc and MSFileSystemForDisk causing crashes.
- Removed default "-" input since it doesn't even work to select stdin.
- dxv: Support loading/signing full shader binary, -o for output file if signed.
Fixes #1500.
=> Fix dxa/dxv options, crashes, support signing

lib/DXIL/DxilModule.cpp
When compiling a library without 16-bit support, certain struct types
containing either min precision types or matrices must be saved in
reflection data for conversion after linking. However, this is only
necessary when the types are used by a resource.
Instead of evaluating all matrix types and saving those that meet this
criteria, only the types used by resources are evaluated and possibly
preserved. This significantly shrinks the reflection size in this case.
(cherry picked from commit 82422d776119b3e115072d7113fab0aeb81292e5)
=> Only keep legacy struct types from resources (#3624)

lib/MC/MCObjectStreamer.cpp
PR #3636 (commit 6b44d611f7) changes the definition of
`llvm_unreachable(msg)`. Now it evaluates the `msg` even when
NDEBUG flag is defined.
For the following code,
```
static const char *const BundlingNotImplementedMsg =
"Aligned bundling is not implemented for this object format";
void MCObjectStreamer::EmitBundleAlignMode(unsigned AlignPow2) {
llvm_unreachable(BundlingNotImplementedMsg);
}
```
`llvm_unreachable(BundlingNotImplementedMsg)` did not evaluate
`BundlingNotImplementedMsg`. After PR #3636, it is evaluated and it
results in "undefined object" for `BundlingNotImplementedMsg`.
=> Fix build failure with undefined variable

lib/HLSL/DxilConvergent.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/Texture/convergent_cs.hlsl
The mark convergent pass is meant to prevent unwanted moving of
operations on derivative op input. It was previously only run on pixel
shaders. Because derivatives are supported in CS/MS/AS shaders as part
of shader model 6.6, it needs to be run on these stages for that target
too.
=> Prevent sinking coord calculation for sample

lib/HLSL/DxilConvergent.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/Texture/convergent_cs.hlsl
Amidst catching the CS/AS/MS cases where convergent markers weren't
getting generated, it was pointed out that libs may need these too.
=> No sinking coord calc for sample in libs

lib/DxilPIXPasses/PixPassHelpers.cpp
dbg.value can occasionally return a null value. (Hit this in a customer (343) shader via PIX.) This is expected. From IntrinsicInst.cpp:
```
// When the value goes to null, it gets replaced by an empty MDNode.
```
=> PIX: Null check before dyn_cast

lib/DxilPIXPasses/PixPassHelpers.cpp
dbg.value can occasionally return a null value. (Hit this in a customer (343) shader via PIX.) This is expected. From IntrinsicInst.cpp:
// When the value goes to null, it gets replaced by an empty MDNode.
=> PIX: CP: Null check before dyn_cast (#3654)

tools/clang/include/clang/Sema/Sema.h, tools/clang/lib/Parse/ParseExprCXX.cpp, tools/clang/lib/Parse/Parser.cpp, tools/clang/lib/Sema/SemaDecl.cpp, tools/clang/lib/Sema/SemaTemplate.cpp, tools/clang/test/HLSLFileCheck/hlsl/template/missing_typename.hlsl
Errors were reported for the use of some dependent template names
in cases where the code should have been accepted, caused by the
incorrect handling of some HLSL cases - which are fixed by this
change.
Fixes #3556
=> [templates] Fix issues with dependent template names

utils/hct/hctdb_instrhelp.py
I need to be able to override these when using hctdb as a helper script.
No change in any hctdb behavior.
=> Parameterize the OP, OC, OCC values in the hctdb opcode table gen

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/test/CodeGenSPIRV/oo.call.method.with.same.base.method.name.hlsl, tools/clang/test/CodeGenSPIRV/oo.inheritance.call.base.method.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
When calling a method using an object, we have to correctly pass "this"
object. When the class of the object used for the method call has
multiple base classes, it does not use the correct base class. It simply
uses "this" object. This commit fixes the issue.
Fixes #3644
=> [spirv] Use object of correct base class for method call

tools/clang/include/clang/Basic/Diagnostic.h, tools/clang/test/HLSLFileCheck/hlsl/payload_qualifier/general.hlsl
When a diagnostic that should be emitted with ReportOnce has already been emitted, an invalid DiagnosticsBuilder is returned to prohibit another emittance of the diagnostic. The current implementation, however, does not set IsActive=false and the DiagnosticsEngine tries to emit a diagnostic with an invalid DiagID. This function is currently only used with payload access qualifiers to emit a warning only once if qualifiers are dropped because PAQs are disabled because of the SM version or the user opted-out. (Update the corresponding test accordingly).
=> DiagnosticsEngine incorrectly handles ReportOnce diagnostics and asserts

tools/clang/test/CodeGenSPIRV/type.template.function.template-instance.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
After investigating #3557, I realized we have to change some parts of SPIR-V backend
to support template correctly. The function template instance works fine while the
struct/class template instance has some issues, but I want to add an unit test for the
function template instance to make sure it works fine.
=> [spirv] add unit test to check function template instance

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/test/CodeGenSPIRV/type.template.struct.template-instance.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
This change correctly generates struct type for the following template
instance:
```
template <typename T>
struct Foo { ... use T ... }
...
Foo<int>
Foo<float>
...
```
Fixes #3557
=> [spirv] Handle class template instance

lib/HLSL/DxilPreparePasses.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/Texture/gatherOffset2.hlsl
When converting the internal gatherimm intrinsic to the official dxil
variant after validation has been performed, user iteration went over
the edge, resulting in an app verifier problem. This corrects the
iteration.
Fixes #3674
=> Correct iteration over users for gather offsets

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/HLSLFileCheck/shader_targets/mesh/as-groupshared-nested-payload.hlsl
- In constant GEP case, the outer structure would be reported as used by
the intrinsic, preventing SROA of outer struct and resulting in the wrong
type for the intrinsic.
=> Fix detection of inner UDT ptr used by lowered intrinsic (DispatchMesh)

tools/clang/tools/dxclib/dxc.cpp
These shouldn't ever really get hit, but there is a chance that the
exception is thrown inside a block that returns the hresult and discards
the exception with its message. We'd rather preserve the message, but as
a last resort, these messages are better than nothing
=> Add cases for new dxc exeptions

lib/Transforms/Scalar/DxilRemoveUnstructuredLoopExits.cpp
This was caught when running one internal test with appverifier/heap test enabled.
=> Fix heap corruption due to dependency on StringRef

tools/clang/include/clang/SPIRV/SpirvBasicBlock.h, tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvContext.h, tools/clang/include/clang/SPIRV/SpirvFunction.h, tools/clang/include/clang/SPIRV/SpirvModule.h, tools/clang/lib/SPIRV/AlignmentSizeCalculator.cpp, tools/clang/lib/SPIRV/AlignmentSizeCalculator.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/lib/SPIRV/LowerTypeVisitor.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvFunction.cpp, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.fxc.matrix.array.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.fxc.matrix.global.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.fxc.matrix.majorness.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.fxc.matrix.n-by-m.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.fxc.matrix.simple.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.fxc.matrix.struct.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.fxc.matrix.v2arr.conversion.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.fxc.matrix.v2arr.conversion.o3.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.fxc.offset.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
When a CTBuffer contains a matrix and we use FXC memory layout for it i.e.,
`-fvk-use-dx-layout`, the memory layout of the generated struct is different
from what FXC generates. FXC memory layout rule for matrices or array of
matrices are:
1. `floatMxN` means `N` float vectors and each vector has `M` elements.
- How to calculate size: 16 * (N - 1) + 4 * M bytes
- How to calculate offset:
- If the size is greater than or equal to 16 bytes: the offset must be aligned to 16 bytes
- Otherwise (less than 16): it cannot be split into multiple 16 bytes slots.
- For example, float2x3 has 16 * (3 - 1) + 4 * 2 = 40 bytes as its size. Since its size 40 bytes is greater than 16 bytes, it must be aligned to 16 bytes.
2. `floatMxN[K]` means an array of `floatMxN` with `K` elements.
- size: (K - 1) * N …
=> [spirv] Fix bug of CTBuffer DX memory layout with matrix

CMakeLists.txt
Offical builds always run a full clean build. This should eliminate the race-condition issue with "Cannot restore timestamp".
=> Disable regeneration target for official builds

include/llvm/IR/DebugInfoMetadata.h, include/llvm/IR/IntrinsicInst.h, lib/HLSL/DxilLinker.cpp
- Fixed linker not adding subprogram of inlined functions into CU. Newer versions of LLVM will consider all the debug info invalid and ignore it if a subprogram is not associated with a CU.
- Added some other helper functions that are going to come in handy when cloning debug metadata from one cloned function to another
=> Fixed linker not putting subprogram of inlined functions into CU

lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp, tools/clang/unittests/HLSL/PixTest.cpp
The value-to-declare pass replaces dbg.value with dbg.declare and some getElementPtr/store pairs that the PIX instrumentation uses to discover values. The problem here was that the dbg.value could reside in the program prior to the value it was referring to, and this seems to be legal. It's not correct once the dbg.value has been replaced with the GEP/store pairs, since the store was trying to operate on a value that had not yet been created. The solution is to move the builder's insertion point to that of the value itself, rather than that of the dbg.value.
Also in this change: a simple pair of copy-paste typos in the OffsetManager class.
=> PIX: Change insertion point to after referenced value

tools/clang/lib/SPIRV/EmitVisitor.cpp
In high level, we did
```
llvm::StringRef choppedSrcCode;
{
std::string text ...
choppedSrcCode = text ...
}
// use choppedSrcCode
```
`choppedSrcCode` points a freed string.
Fixes #3702
=> [spirv] fix use-after-free bug

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/cast.flat-conversion.decl-ref.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
The flat conversion method `SpirvEmitter::processFlatConversion()`
conducts bit-casts, composite construction, ... to covert the target to
the specific type. Since we cannot convert a pointer to other types, we
should make sure the target is r-value. In particular, it fixes bugs
when the target is a constant or texture buffer. The existing code just
returns `OpVariable` for the constant or texture buffer conversion, but
`OpVariable` is not r-value and it results in a spirv-val error.
Fixes #3681
=> [spirv] always use r-value for flat conversion target

include/dxc/Support/DxcLangExtensionsCommonHelper.h, include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, include/dxc/dxcapi.internal.h, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/Frontend/CodeGenOptions.h, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/tools/libclang/dxcisenseimpl.h, tools/clang/tools/libclang/dxcrewriteunused.cpp, tools/clang/unittests/HLSL/ExtensionTest.cpp
Introduce below three hidden options to control overriding semantic defines which are passed through the source using `#define` and/or passed in the argument list using the `-D` option.
`-ignore-opt-semdefs`: Ignores all optional semantic defines which are not required to ensure program correctness.
`-ignore-semdef <semantic_define_name>`: Ignores the specific semantic define passed using this flag. 
`-override-semdef <semantic_define_name>=<semantic_define_value>`: Overrides the value of semantic define passed using this flag.
=> Add option to override semantic defines

tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/test/CodeGenSPIRV/type.rwtexture.with.min.precision.scalar.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
For example, following textures have types with minimum precision scalar
as template parameters. We support minimum precision scalar types for
images.
```
RWTexture2D<min10float4> tex0;
RWTexture2D<min16uint4> tex1;
RWTexture2D<min12int4> tex2;
```
Fixes #3280 #3209
=> [spirv] support image with minimum precision scalar data types

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/type.rwtexture.with.min.precision.scalar.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
1. Support image with minimum precision scalar data types
2. Do not set AST result type for `OpImageWrite` instruction.
Note that [OpImageWrite](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpImageWrite)
does not have `Result Type`.
3. Do not set `RelaxedPrecision` decoration if the instruction does not have a result type.
=> [spirv] image with minimum precision scalar data types

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/ByteAddressBuffer/bab-array-alias.hlsl
LowerMemcpy has existing support for subscript op to replace use of
alloca with original pointer from subscript op, eliminating copy and
making sure loads from the local copy load directly from the buffer
instead (such as for dynamic indexing a local array loaded from a buffer).
New templated ByteAddressBuffer::Load<UDT>() method wasn't handled, so
this change adds this support.
Still, only SRV is supported, since additional analysis would be required
to prove replacement is safe for UAV.
=> Support replace for BAB.Load<>() in LowerMemcpy

include/dxc/HLSL/DxilGenerationPass.h, lib/HLSL/DxcOptimizer.cpp, lib/HLSL/DxilCondenseResources.cpp, lib/HLSL/DxilPromoteResourcePasses.cpp, lib/Transforms/IPO/PassManagerBuilder.cpp, tools/clang/lib/CodeGen/CGCall.cpp, tools/clang/lib/CodeGen/CGExprAgg.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp, tools/clang/lib/CodeGen/CGHLSLRuntime.h, tools/clang/test/HLSLFileCheck/hlsl/objects/Cbuffer/CBV-paren-expr.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/Cbuffer/retCBV2.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/Cbuffer/retCBV3.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/Cbuffer/retTBV2.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/Cbuffer/retTBV3.hlsl
ConstantBuffer<> and TextureBuffer<> resource objects were not being
handled when the objects themselves were used instead of just reading from
them.  Examples are passing to/from functions, but also simply an extra
layer of ParenExpr.  For simple ParenExpr case, it's easy to just drill
through, but this isn't possible for other cases.  More temps need to be
potentially marked, so MarkRetTemp/MarkCallArgumentTemp is unified into
MarkPotentialResourceTemp which is also used for temp created during
EmitAggExprToLValue.  CBuffer init code in FinishCodeGen also needed
fixing.  When replacing resource users with subscript operator, users of
the actual resource object need the original HL resource type, which is
constructed through the HL HandleToResCast and stored to an alloca for
pointer …
=> Fix bugs with ConstantBuffer resource object usage

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/test/CodeGenSPIRV/sm6.wave.builtin.no-dup.vulkan1.2.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.multiple.entries.built-in.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.multiple.entries.built-in.vk.1p2.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.multiple.entries.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.multiple.entries.simple.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.multiple.entries.vk.1p2.hlsl, tools/clang/test/CodeGenSPIRV/vk.1p2.entry-point.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
As mentioned in #3759 and https://github.com/KhronosGroup/SPIRV-Tools/pull/4275,
DXC does not generate correct operands of `OpEntryPoint` when the shader has
multiple entry functions. The main reason is that the existing SPIR-V backend does
not separate interfaces between entry functions. This commit lets `DeclResultIdMapper`
keep the information of the entry point of each stage variable in `StageVar` and
lets `SpirvEmitter` correctly emit interfaces for each `OpEntryPoint`.
=> [spirv] emit correct OpEntryPoint operands for multiple entry functions

tools/clang/lib/SPIRV/SpirvEmitter.cpp
Some versions of VisualStudio does not accept
`std::vector(llvm_denseset.begin(), llvm_denseset.end())`. This commit
simply updates the code generating `std::vector` from `llvm::DenseSet`.
=> [spirv] fix build failure caused by vector ctor

include/llvm/ADT/ArrayRef.h, include/llvm/ADT/DenseMap.h, include/llvm/ADT/SmallVector.h, lib/DxcSupport/dxcmem.cpp
And a small clang warning.
Came across these again while testing #3793, having already imported the fixes prior - better to just submit them instead of rotting away on a local branch. They don't nearly cover them all, but especially the `memcpy` is extremely verbose and makes reading the logs unbearable (though, so is `-Wimplicit-fallthrough=` and `-Woverloaded-virtual`).
=> [Linux] Import some LLVM fixes for GCC warnings

include/dxc/DXIL/DxilTypeSystem.h, include/dxc/DXIL/DxilUtil.h, lib/DXIL/DxilMetadataHelper.cpp, lib/DXIL/DxilTypeSystem.cpp, lib/DXIL/DxilUtil.cpp, lib/HLSL/DxilCondenseResources.cpp, lib/HLSL/DxilContainerReflection.cpp, lib/HLSL/HLModule.cpp, tools/clang/include/clang/AST/HlslTypes.h, tools/clang/lib/AST/HlslTypes.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp, tools/clang/test/HLSLFileCheck/hlsl/resource_binding/bindings1.hlsl, tools/clang/test/HLSLFileCheck/hlsl/resource_binding/resource_in_cbuffer.hlsl, tools/clang/test/HLSLFileCheck/hlsl/resource_binding/resource_in_cbuffer2.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/matrix/default-matrix-in-template.hlsl, tools/clang/test/HLSLFileCheck/shader_targets/library/lib_hs_shaders_only.hlsl, tools/clang/test/HLSLFileCheck/shader_targets/library/lib_shaders_only.hlsl, tools/clang/test/HLSLFileCheck/shader_targets/raytracing/raytracing_derived_payload.hlsl, tools/clang/unittests/HLSL/DxilContainerTest.cpp, tools/clang/unittests/HLSL/ValidationTest.cpp
* Fold bitcast-to-base into GEP in MergeGepUse, plus refactor
- Fixes case where bitcast isn't eliminated under -Od.
- Fix issue with constant GEP path that was unintentionally using GEP
from failed prior branch.
- Change to worklist pattern, which simplifies things.
- One case wasn't handled, which was going to complicate code:
GEP -> bitcast -> GEP would combine bitcast -> GEP, but not combine
outer GEP with the new one.
- Add dxilutil::TryReplaceBaseCastWithGep that simply replaces if it matches.
* Fix cbuffer layouts when resources are in structs
- keep track of resources in type annotation information
- fix cbuffer packing locations for things around resources
- when translating struct for legacy:
- remove resource fields from struct types
- properly replace HLSL type
- remove unused …
=> Fold bitcast-to-base into GEP in MergeGepUse, plus refactor and resource fixes

tools/clang/test/HLSL/ShaderOpArith.xml
Mesh shader groupshared initialization and read were asymmetric, resulting in read of uninitialized data. 
The uninitialized data caused nondeterministic behaviour, so it would sometimes pass. It passes consistently with the fix.
=> Fix mesh groupshared atomics test bug

include/dxc/Support/WinAdapter.h
This small change makes it possible to build and use DirectXShaderCompiler on Android, at least on arm64-v8a.
execinfo.h does not exist in Android toolchain. However it is only used by clang-hlsl-tests which can be disabled from the build.
I hope this could be merged, or fixed in another way, since being able to load the compiler on Android can help development quite a bit, even though for a shipped version the binary (~20 MB) would be maybe a bit too large to include in smaller apps (and glslang is not always an option as new HLSL features seem to land into DXC first). I've already used the Android build for debugging shader related issues quickly by hot-reloading shader source code changes directly on the Android device without having to restart the app and compile shaders manually on …
=> Disable execinfo.h include for Android build in WinAdapter.h

lib/DxilPIXPasses/DxilAddPixelHitInstrumentation.cpp, lib/DxilPIXPasses/DxilAnnotateWithVirtualRegister.cpp, lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp, lib/DxilPIXPasses/DxilDebugInstrumentation.cpp, lib/DxilPIXPasses/DxilOutputColorBecomesConstant.cpp, lib/DxilPIXPasses/DxilPIXMeshShaderOutputInstrumentation.cpp, lib/DxilPIXPasses/PixPassHelpers.cpp, lib/DxilPIXPasses/PixPassHelpers.h, lib/HLSL/DxilContainerReflection.cpp
This is a bit of a corner-case, but PIX tripped up on it while capturing an app under d3d11on12.
PIX is probably the only client who cares about this case, since it's only relevant when DXBC->DXIL has been run (e.g. 11on12), and then examined via reflection and/or the PIX-specific passes.
Here's the entry-point metadata provided by DXBC->DXIL for a representative case. It has a null entry point, but a non-null patch-constant function:
```
!dx.entryPoints = !{!7}
!7 = !{null, !"", !8, !2, !24}
!24 = !{i32 0, i64 256, i32 3, !25}
!25 = !{void ()* @pc_main, i32 3, i32 3, i32 2, i32 3, i32 3, float 0.000000e+00}
```
(Documentation of DXBC->DXIL's operation in this case is here: https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/DXIL.rst#hull-shader-representation)
(PIX bug …
=> PIX: Entry point can be null for DXBC->DXIL hull shader

lib/HLSL/DxilPromoteResourcePasses.cpp
We're currently in the process of converting already existing shader assets to raytracing equivalent versions. While doing so we run in to the following compile error when using global static variables in our library export: "static global resource use is disallowed in library exports."
shadercode:
```
Texture2D<float2> RainDepth : register(t1, space1);
SamplerState samplerPoint_BorderWhite 
{ 
Filter = MIN_MAG_MIP_POINT ; 
AddressU = BORDER ; 
AddressV = BORDER ; 
AddressW = BORDER ; 
MipLODBias = 0 ; 
MaxAnisotropy = 1 ; 
BorderColor = float4 ( 1 , 1 , 1 , 1 ) ; 
} ; 
static const SamplerState samplerMIN_MAG_MIP_POINTBORDERBORDERWHITE = samplerPoint_BorderWhite ; 
static const SamplerState samplerStaticRainDepth = samplerMIN_MAG_MIP_POINTBORDERBORDERWHITE ; 
struct Payload{
uint value; …
```
=> Allowing use of const static variables in library exports

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/texture.sample.offset.needs.legalization.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample.offset.needs.legalization.o0.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample.variable-offset.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
When we find a variable offset used for the texture sampling, we have to
- Run legalization if `-fcgl` is not enabled.
- Enable `--before-legalize-hlsl` for spirv-val if `-fcgl` is enabled.
to match the behavior of the DXIL backend.
In order to do that, we set SpirvEmitter::needsLegalization as true when
we find a variable offset used for the texture sampling. SpirvEmitter
will determine enabling `--before-legalize-hlsl` or running the
legalization depending on `-fcgl`.
=> [spirv] set needsLegalization as true when variable offset is found

include/dxc/DXIL/DxilConstants.h, lib/DxilPIXPasses/DxilShaderAccessTracking.cpp, tools/clang/unittests/HLSL/PixTest.cpp
While working on another issue I noticed that I had forgotten these cases.
(PIX uses this pass to detect non-constant indexing into resource arrays in order to decide if it should run the whole "shader access tracking" pass to check for out-of-range access etc. So it was failing to detect dynamic indexing and so could choose not to run the SAT pass.)
=> PIX: Check SM66 handle types for dynamic indexing

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp
Add needed check for wave ops needed for QuadRead* operations.
Correct use of GroupIndex to use WaveLaneIndex since that's how quad
relationships can be ensured. That required changing some other aspects
of the test as well.
=> QuadRead Test fix dependencies and groupIndex

tools/dxexp/CMakeLists.txt
(cherry picked from commit 88ddd4c978e4c2c3d63a43fd682a56eb428c6829)
=> dxexp: add explicit dependency on D3D12 (#3710)

tools/clang/test/HLSL/ShaderOpArith.xml
Resources used as raw RWByteAddressBuffer but created as structured could see conflicting allocation and stride values, resulting in OOB access in some configurations.
Setting the stride to 0 (I like being explicit) and adding the raw/typeless qualifiers, I no longer see OOB accesses.
=> Fix atomics resource declaration issue

lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp
Background: this pass is trying to find all dbg.value and replace them with dbg.declare. In the code being changed, the pass is trying to seek a valid location at which to insert the dbg.declare. It has to come after the value to which it applies (which isn't true of the dbg.value). So there's this little loop trying to move forward to find the right instruction before which to insert new stuff.
I was expecting getNextNode to return null when there is no next node. When called on a terminator, it actually returns a non-null but malformed instruction pointer. So we have to explicitly check for terminators in this loop.
This really short basic block tripped up the pass:
```
; <label>:274                                     ; preds = %.lr.ph55
%RawBufferLoad = call %dx.types.ResRet.i32 …
```
=> PIX: Don't seek beyond terminator instructions (value-to-declare pass)

lib/DxcSupport/HLSLOptions.cpp
The test to determine if an -opt-disable or -opt-enable flag was
contradictory did not take into account hte possibility that the
previous inclusion was also an enable, which wouldn't be a
contradiction.
=> Correct detection of contradictory opt enables

tools/clang/unittests/SPIRV/CMakeLists.txt
This build was failing on windows debug because recent additions pulled
it over a size threshold. This flag is used elsewhere in the compile
already and works fine here.
=> Add /bigobj flag on big spirvtest object

tools/clang/tools/dxcompiler/dxcfilesystem.cpp
- use 10 bits for Offset to support MaxIncludedFiles include files.
- use 16 bits for Length to support nearly arbitrary path length.
Partially addresses #2319 (point 2 and 3)
Fixes #2731
=> Fixed HandleBits struct limitations due to 8bits fields

utils/hct/hctdb_instrhelp.py
Trivial changes to the case of some file names used by hctdb_instrhelp.py
to match the actual case of the files in the repo. This fixes problems
experienced when using the script on Linux.
=> Amend hctdb_instrhelp.py for case-sensitive filesystems

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.get-attribute-at-vertex.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Fix a null pointer dereference which can occur when an unimplemented
intrinsic is used. The repro shader from issue #2955 (added as a unit
test) now fails with a useful message rather than a silent crash.
=> [spirv] Fix null pointer dereference

tools/clang/lib/SPIRV/GlPerVertex.cpp, tools/clang/lib/SPIRV/GlPerVertex.h, tools/clang/test/CodeGenSPIRV/spirv.interface.ps.array.sv_clipdistance.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.ps.multiple.array.sv_clipdistance.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.vs.array.sv_clipdistance.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.vs.clip_distance.type.error.hlsl, tools/clang/test/CodeGenSPIRV/spirv.interface.vs.multiple.array.sv_clipdistance.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
`GlPerVertex` class mainly handles clip/cull distance stage variable.
This change entirely refactors methods of `GlPerVertex` class to
improve the code readability. Mainly it splits each method handling
multiple cases within a single method/loop into multiple methods.
In addition, this change adds the code to support  clip/cull distance
stage vars with array types.
Fixes #3278
=> [spirv] support clip/cull distance stage vars with array types

tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp, tools/clang/unittests/SPIRV/FileTestFixture.cpp, tools/clang/unittests/SPIRV/FileTestFixture.h, tools/clang/unittests/SPIRV/FileTestUtils.cpp, tools/clang/unittests/SPIRV/FileTestUtils.h, tools/clang/unittests/SPIRV/WholeFileTestFixture.cpp
So far we added SPIR-V unittests only with separate HLSL source code
file. To add unittests in a scalable and flexible way, this commit
supports unittests with inlined HLSL code.
=> [spirv] support unittests with inlined HLSL code

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.dot4add.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
The repro shader from issue #2953 now fails with a useful error message
and has been added as a unit test.
=> [spirv] Add null check to binary op processing

tools/clang/test/HLSL/ShaderOpArith.xml
Just to avoid any suspicion about passing float `uv.x` and `uv.y` into
convert2Dto1D which requires uint.  It's a dummy PS and the data written
to g_bufMain (u0) is not read back.
=> Document that ComputeSample PS is a dummy

tools/clang/include/clang/Basic/DiagnosticGroups.td, tools/clang/include/clang/Basic/DiagnosticParseKinds.td, tools/clang/lib/Parse/ParseDecl.cpp, tools/clang/test/HLSL/cpp-errors-hv2015.hlsl, tools/clang/test/HLSL/cpp-errors.hlsl
Intent is to avoid confusion where C++ syntax would allow named constant as bitfield width, which is disallowed in HLSL because of conflict with syntax for semantics.
=> Warns when semantic name same as identifier.

include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/Basic/LangOptions.h, tools/clang/include/clang/Driver/Options.td, tools/clang/lib/Frontend/CompilerInvocation.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSL/conversions-between-type-shapes-strictudt.hlsl, tools/clang/test/HLSLFileCheck/hlsl/functions/arguments/outputArray-strictudt.hlsl, tools/clang/test/HLSLFileCheck/hlsl/template/strict-udt-casting-1.hlsl, tools/clang/test/HLSLFileCheck/hlsl/template/strict-udt-casting-2.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/cast/StructCast-strictudt.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/cast/identical_layout_structs/explicit_cast_as_out_param-strictudt.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/cast/identical_layout_structs/implicit_cast_as_func_param_user_scenario-strictudt.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/cast/identical_layout_structs/implicit_cast_as_streamout_append-strictudt.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/struct/anonymous-strictudt.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/struct/structArray-strictudt.hlsl, tools/clang/test/HLSLFileCheck/passes/hl/sroa_hlsl/memcpy_split_regression-strictudt.hlsl, tools/clang/test/HLSLFileCheck/shader_targets/geometry/streamoutputs/streamout_input_before_output_different_structs-strictudt.hlsl, tools/clang/test/HLSLFileCheck/shader_targets/geometry/streamoutputs/streamout_output_before_input_different_structs-strictudt.hlsl, tools/clang/test/HLSLFileCheck/shader_targets/library/inout_struct_mismatch-strictudt.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/tools/libclang/dxcrewriteunused.cpp, tools/clang/unittests/HLSL/VerifierTest.cpp, utils/hct/VerifierHelper.py
TODO: Enable this by default under -HV 2021
Fixes #3564.
Fixes #3563.
=> -strict-udt-casting prevents implicit casts between unrelated structs

tools/clang/lib/Sema/SemaHLSL.cpp
`IsHLSLAttr(clang::attr::Kind AttrKind)` must return `true` for `clang::attr::HLSLShader` to support SM6.3 `[shader("...")]` attributes.
=> Add attr::HLSLShader to list of HLSL attributes in IsHLSLAttr()

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp, tools/clang/lib/CodeGen/CGHLSLMSHelper.h, tools/clang/lib/CodeGen/CGHLSLRuntime.h, tools/clang/lib/CodeGen/CGStmt.cpp, tools/clang/lib/CodeGen/CodeGenFunction.h, tools/clang/test/HLSLFileCheck/hlsl/control_flow/loops/structurize_multiexit_crash_do.hlsl, tools/clang/test/HLSLFileCheck/hlsl/control_flow/loops/structurize_multiexit_crash_while.hlsl
Clang does a small optimization during codegen for loops of the form
`while(true){...}` and `do{...}while(false)`. It attempts to merge
the loop continue block with the unique successor. Our scope
analysis was not updating its pointers when the original continue
block was removed by this optimization leading to crashes when running
`StructurizeMultiRetFunction()` at the end of codegen.
=> Fix crash when structurizing multi-return loops

lib/HLSL/DxilPromoteResourcePasses.cpp, tools/clang/test/HLSLFileCheck/shader_targets/library/link_mismatch_target.hlsl
- Don't clobber HLSL type on resource if already handle
- Don't walk GV types that are already handle
- Add all non-handle CreateHandleForLib functions and map arg to handle
=> Fix issues in DxilMutateResourceToHandle.

include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/tools/dxclib/dxc.cpp, tools/clang/tools/dxr/dxr.cpp
- Added a --version flag to display the same dxc version info displayed from the -? flag
- Added --version flag description to the help text displayed from the -? flag
=> Add --version flag to print dxc version info

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/test/CodeGenSPIRV/fn.export.hlsl
Add linkageAttributes OpDecorate as required by the spirv spec for the
exported/imported values of Linkage capability
=> [SPIRV] Add linkageAttributes decorates

tools/clang/lib/CodeGen/CGExprScalar.cpp, tools/clang/test/HLSLFileCheck/hlsl/types/matrix/matrix_comma.hlsl
The special HLSL matrix codegen didn't handle the comma operator. Since
the operation is simple enough, skip special handling and fallback to
the default behavior
Fixed #3916
=> Correctly handle comma operator w/matrices

tools/clang/include/clang/Basic/Attr.td, tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/include/clang/SPIRV/SpirvContext.h, tools/clang/include/clang/Sema/AttributeList.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenSPIRV/vk.combined-image-sampler.error.hlsl, tools/clang/test/CodeGenSPIRV/vk.combined-image-sampler.hlsl, tools/clang/test/CodeGenSPIRV/vk.combined-image-sampler.texture-array.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
How to use `vk::combinedImageSampler`:
1. Define `SamplerState` and `Texture2D` with the same descriptor set and binding numbers e.g.,
```
[[vk::combinedImageSampler]][[vk::binding(0, 1)]]
SamplerState sam0;
[[vk::combinedImageSampler]][[vk::binding(0, 1)]]
Texture2D<float4> tex0;
```
2. Use them e.g., `tex0.SampleLevel(sam0, float2(1, 2), 10, 2);`
3. Run the legalization after SPIR-V codegen.
Note that we can use the texture `tex0` with samplers other than `sam0`
but we cannot use `sam0` with textures other than `tex0`.
=> [spirv] support vk::combinedImageSampler

include/dxc/Support/HLSLOptions.td, include/dxc/Support/SPIRVOptions.h, lib/DxcSupport/HLSLOptions.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/reduce.load.size.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Since loading a big object comes with the memory pressure, reduction of
the load size can have some performance benefit. In particular, it is
useful for mobile GPUs. `-fspv-reduce-load-size` removes
OpLoad/OpCompositeExtract of struct/array types by running spirv-opt
--reduce-load-size pass.
Fixes #3889
=> [spirv] add -fspv-reduce-load-size option

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/binary-op.assign.opaque.array.hlsl
RValues with OpaqueArrayType can now be legalized with spirv-opt.
Fixes #3677
=> [spirv] Add support for RValues with OpaqueArrayType

lib/DxcSupport/dxcmem.cpp, tools/clang/unittests/HLSLTestLib/DxcTestUtils.cpp
Without this change we cannot call a sequence of
DxcInitThreadMalloc()
DxcCleanupThreadMalloc()
...
DxcInitThreadMalloc() // <- This will trigger an assert
because we hit an assert that assumes the default malloc pointer is nullptr.
=> Allow calling DxcInitThreadMalloc again after calling DxcCleanupThreadMalloc

tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.h, tools/clang/test/CodeGenSPIRV/vk.spec-constant.reuse.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Fix an issue where specialization constants could be emitted multiple times (once by themselves and once in composites). Resolves #3903.
=> [SPIR-V] Fix an issue with duplicate specialisation constants

lib/HLSL/DxilLegalizeEvalOperations.cpp, lib/HLSL/HLOperationLowerExtension.cpp, lib/HLSL/HLOperations.cpp, tools/clang/unittests/HLSL/ExtensionTest.cpp
- Fixed HL operations and DXIL operations not having the NoUnwind attribute, and therefore not DCE'ed
- Fixed LegalizeEvalOp not checking for the right intrinsic group and incorrectly removing Allocas for HLExtIntrinsic intrinsics
=> NoUnwind fix. HLExtIntrinsic collision fix.

tools/clang/tools/dxclib/dxc.cpp
When processing the DXC_OUT_EXTRA_OUTPUTS output from a compile there
is an attempt to skip non-blob outputs. The check is written incorrectly
because the call to `GetOutput` will fail (when it tries to QueryInterface
on the blob output).
The fix is to check the HRESULT returned from GetOutput and skip the output
if it failed.
Found when using the dxclib from an external project. I did not see an easy
way to add a test for this.
=> Fix check in dxc extra output processing for non-blob output

tools/clang/tools/dxcompiler/dxcompilerobj.cpp
This fixes two compile errors and a runtime error when `SUPPORT_QUERY_GIT_COMMIT_INFO` is disabled:
1. Inheritance list of `DxcCompiler` does no longer have a trailing comma.
https://github.com/microsoft/DirectXShaderCompiler/blob/56e22b30c5e43632f56a1f97865f37108ec35463/tools/clang/tools/dxcompiler/dxcompilerobj.cpp#L552
2. Static cast from `DxcCompiler` to `IDxcVersionInfo` works again as `IDxcVersionInfo3` is derived from `IUnknown` only.
https://github.com/microsoft/DirectXShaderCompiler/blob/56e22b30c5e43632f56a1f97865f37108ec35463/tools/clang/tools/dxcompiler/dxcompilerobj.cpp#L1087
3. The byte count for null terminators must always be added to `VersionStringListSizeInBytes` in `CompilerVersionPartWriter::Init` as those strings are always written even when empty: …
=> Fix build when `SUPPORT_QUERY_GIT_COMMIT_INFO` is disabled

tools/clang/lib/Sema/SemaHLSL.cpp
The check for short curcuit intrinsics failed to account for
intrinsic tables other than the default. This ensures that assumption is
correct before performing the check
As an incidental, added code to catch a few other cases too
=> Limit Sema intrinsic checks to builtin "op" table

include/dxc/Test/D3DReflectionDumper.h, lib/HLSL/DxilContainerReflection.cpp, tools/clang/test/HLSLFileCheck/d3dreflect/anon_struct.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/cb_array.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/cbuf-usage-phi.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/cbuffer_default_val.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/empty_struct2.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/lib_exports1.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/lib_exports2.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/lib_exports3.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/lib_exports4.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/lib_exports_nocollision.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/lib_global.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/raytracing_traceray.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/raytracing_traceray_readback.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/reflect-lib-1.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/sig-array.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/structured_buffer_getdim_stride.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/structured_buffer_layout.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/tbuffer-16bit.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/tbuffer.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/texture2dms.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/FeedbackTexture/feedback-reflect.hlsl, tools/clang/test/HLSLFileCheck/shader_targets/mesh/mesh.hlsl, tools/clang/unittests/HLSLTestLib/D3DReflectionDumper.cpp
- Fix Barycentric system value translation
- Increment Register for array elements
- Add signature dumping to D3DReflectionDumper
- Dump PatchConstantParameters when mesh shader
Fixes #3952
=> Fix bugs in signature reflection, add signatures to dumper and tests

tools/clang/include/clang/Basic/Attr.td, tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/include/clang/SPIRV/SpirvVisitor.h, tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenSPIRV/spv.intrinsic.reference.error.hlsl, tools/clang/test/CodeGenSPIRV/spv.intrinsicInstruction.hlsl, tools/clang/test/CodeGenSPIRV/spv.intrinsicLiteral.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Related to the issue: https://github.com/microsoft/DirectXShaderCompiler/issues/3919
Add these attributes
vk::ext_capability
vk::ext_extension
vk::ext_instruction
=> [SPIRV] Add support of the GL_EXT_spirv_intrinsics

include/llvm/IR/DiagnosticInfo.h, lib/DXIL/DxilUtil.cpp, lib/IR/DiagnosticInfo.cpp, tools/clang/lib/CodeGen/CodeGenAction.cpp, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/resource_conflict.hlsl
`DILocation` can't actually point to any non-local scopes, so can't be used to represent location of a global variable. Must use `DIGlobalVariable` instead.
Changed `DiagnosticInfoDxil` to hold the actual location info instead of a pointer to a `DILocation`.
=> Fixed an assert when a dxil error happens with global variable

tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp, tools/clang/lib/CodeGen/CGHLSLMSHelper.h, tools/clang/test/HLSLFileCheck/hlsl/control_flow/return/if_ret_with_else_ret.hlsl, tools/clang/test/HLSLFileCheck/hlsl/control_flow/return/multi_ret_in_switch_not_whole_scope_ret.hlsl
When structurize return like return 1 in
if (b == 77)
return 0;
else if (b != 3)
return 1;
the end scope of if (b == 77) should be updated to bReturned.Cmp.false
Final cfg should be the right one, left one is wrong cfg without the fix.
to
=> Always update end scope when structurize returns.

include/dxc/DXIL/DxilConstants.h, include/dxc/DXIL/DxilResource.h, lib/DXIL/DxilResource.cpp, tools/clang/unittests/HLSL/CMakeLists.txt, tools/clang/unittests/HLSL/DxilResourceTests.cpp
* Added `IsAnyTextureArray` and `IsAnyTextureCube` helper methods.
* Added test case for all non-trival `Is...(ResouceKind)` methods
=> [NFC] Add additional helper methods for DXT::ResourceKind

lib/IR/ConstantFold.cpp, tools/clang/test/HLSLFileCheck/hlsl/operators/binary/shift-fold.hlsl
- Shift operators (Shl, LShr, AShr) use (RHS & (bitwidth-1))
(5 LSB for 32-bit operation, 6 LSB for 64-bit operation)
=> Follow HLSL rule for shift ops during constant folding

lib/DxilContainer/DxilContainerAssembler.cpp
- Before module serialization, constant users of resource globals could themselves have multiple constant users.  These could be consolidated through module serialization/deserialization, leading to a difference when only the first constant user was followed.  The difference could lead to a validation failure only with external validator (DXIL.dll) since reconstructed RDAT would not match the original RDAT with the missing use.  This would happen in cases such as identical constant indexing of resource arrays from multiple entries.
- Also, fix groupshared usage detection when setting function compat flags for RDAT.
=> Fix missing RDAT function resource usage by recursing constant users

lib/HLSL/DxilPreparePasses.cpp, tools/clang/test/CodeGenHLSL/val-wave-failures-ps.hlsl, tools/clang/test/DXILValidation/val-wave-failures-ps.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/wave/reduction/WaveSensitivityAndCycles.hlsl, tools/clang/test/HLSLFileCheck/validation/val-wave-failures-ps.hlsl
To fix gradient ops warnings generating in non-deterministic order. Added order checking to existing gradient ops warnings tests.
=> Consistent order gradient ops warnings.

tools/clang/tools/dxcompiler/dxcdisassembler.cpp, tools/clang/unittests/HLSL/OptionsTest.cpp
Clang has added new warnings for possible unintended string
concatenations. When concatonating strings in an array literal warpping
the concatenation in parentesis quiets the warning.
=> [NFC] Silence a few new clang warnings

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/test/CodeGenSPIRV/vk.attribute.image-format.simple.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Legalization is required to propagate the correct type of the OpLoad even when
the resource variables are not being passed or assigned
This fixes a validation error in simple shaders using vk::image_format, where legalization
would not be needed otherwise
This fixes https://github.com/microsoft/DirectXShaderCompiler/issues/3767
=> [spirv] Enable legalization when the vk::image_format attribute is used

lib/Support/CMakeLists.txt, lib/Support/Path.cpp, lib/Support/Unix/Path.inc, lib/Support/Windows/MSFileSystem.inc.cpp, lib/Support/Windows/WindowsSupport.h, unittests/ADT/DenseMapTest.cpp, unittests/ADT/SmallPtrSetTest.cpp, unittests/IR/ConstantsTest.cpp, unittests/Support/CMakeLists.txt
This change in conjunction with the work in #4020, will get all of the
LLVM unit tests passing. In addition to minor fixes in several of the
tests, and to the build configuration, this patch adds a new implicit
disk filesystem if the filesystem APIs are used without initializing a
PerThreadFileSystem.
The implicit filesystem is only enabled if `LLVM_INCLUDE_TEST=On`, and
it should allow the LLVM filesystem APIs to behave as LLVM tools and
tests expect them to.
=> Get LLVM Unit Tests Passing

include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcBindingTable/DxcBindingTable.cpp, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/Frontend/CodeGenOptions.h, tools/clang/lib/CodeGen/ModuleBuilder.cpp, tools/clang/test/HLSLFileCheck/dxil/debug/binding-table.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp
Added `-binding-table-define` to make binding table mechanism play well with the preprocessor system. When preprocessing shader, all the info needed to compile the shader should be in a single file, there's no way to do that when an include handler is required to use this feature.
`-import-binding-table` will be deleted later.
=> Added -binding-table-define

tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.h, tools/clang/test/CodeGenSPIRV/shader.debug.line.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
This commit generates end values for lines and columns identical to the
start values. A follow-up commit will add correct end values for lines
and columns.
=> [spirv] Add Shader.DebugInfo.100 support for DebugLine and DebugNoLine

include/dxc/Support/WinIncludes.h, lib/Support/Windows/WindowsSupport.h
Some of the LLVM APIs were expecting Windows XP support, while other
places in the code were going with whatever your SDK configured.
This should get things consistent and avoid mismatches in the Windows
headers.
=> Require Windows 7 Everywhere

tools/clang/test/CodeGenSPIRV/decoration.relaxed-precision.resource.in.struct.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
spirv-opt desc-sroa pass recently handles OpMemberDecorate by adding
OpDecorate instruction for the corresponding element of the resource
array. This commit uses it to preserve RelaxedPrecision decoration used
for resource variables in struct.
Fixes #4047
=> [spirv] test preservation of RelaxedPrecision for resource in struct

cmake/modules/HCT.cmake
We've seen some lingering odd issues with autocrlf. I think this will
resolve them all because our gitattrbutes sets text=auto which is only
overridden if autocrlf=input.
We'll know if this works based on whether or not the AppVeyor build
works.
=> Workaround autocrlf=input

cmake/modules/HCT.cmake
For the `CODE_TAG` sources we need to ensure that they are dependencies
of the generation command. This also requires creating an extra
temporary file so that the dependencies aren't circular.
=> Minor fix for dependencies of generated sources

include/llvm/LinkAllPasses.h, lib/CMakeLists.txt, lib/LLVMBuild.txt, lib/Transforms/IPO/CMakeLists.txt, lib/Transforms/IPO/IPO.cpp, lib/Transforms/IPO/PassManagerBuilder.cpp, tools/LLVMBuild.txt, tools/clang/tools/dxcompiler/CMakeLists.txt, tools/clang/tools/dxrfallbackcompiler/CMakeLists.txt, tools/clang/unittests/DxrFallback/CMakeLists.txt, tools/opt/opt.cpp, utils/hct/hctdb.py
LTO was unused, and ArgumentPromotion would not have any effect on DXIL
until you use noinline, and it might decompose HLSL/DXIL objects, which
could break things.
=> Remove LTO and ArgumentPromotion passes

lib/DxilDia/DxcPixDxilDebugInfo.cpp
This fix is for shaders (in particular those for materials from Unreal Engine) that feature #line directives.
In the UE case, for example, there is one source file called hlsl.hlsl, with many #line directives pointing to the original HLSL files from which the source was assembled via UE's material system.
At the start of shader debugging, all the filenames from DebugLoc are returned from code near here to PIX. Those filenames are the ones from the #line directives.
The previous code would iterate over source file names (which in the UE case would be just hlsl.hlsl), and fail to find the filename that PIX is now asking to find the instructions for.
Instead, we now gather the filenames from the DebugLoc. Note that the filename comparison is done after the line number comparison for …
=> PIX: Use DebugLoc for filenames instead of file list

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/test/CodeGenSPIRV/shader.debug.line.hlsl
In particular, add support for start and end lines and columns for
DebugLine. Previously, end line and column was same as start line and
column.
This is just the first installment of this change. It covers binary ops,
OpAccessChain, OpLoad, OpStore, DebugDeclare, OpSample and OpReturn. A
second commit will complete support.
This commit primarily adds SourceRange to the appropriate emit and
generation functions. This is necessary since sometimes neither value
in the SourceRange matches the accompanying SourceLocation.
Note that while the end column is more correct than it was previously, it
is not perfectly correct. It currently points to the beginning of the last
token of the computation rather than the end of that token. We will
attempt to improve this with a followup commit.
=> [spirv] Improve lines and columns for DebugLine (pt 1)

tools/clang/include/clang/Frontend/LangStandards.def
Digraphs are support in C for non-ASCII conforming keyboards. Pretty
sure we don't really need that, and it doesn't work anyways.
=> [NFC] HLSL doesn't really support digraphs

tools/clang/lib/Parse/ParseStmt.cpp, tools/clang/test/HLSL/loop-induction-scoping-2021.hlsl
This should resolve #584 by adopting C++ for loop scoping rules for
HLSL 2021.
=> [HLSL21] Use C++ for loop scoping rules #584

lib/DxilDia/DxcPixDxilDebugInfo.cpp
This fix is for shaders (in particular those for materials from Unreal Engine) that feature #line directives.
In the UE case, for example, there is one source file called hlsl.hlsl, with many #line directives pointing to the original HLSL files from which the source was assembled via UE's material system.
At the start of shader debugging, all the filenames from DebugLoc are returned from code near here to PIX. Those filenames are the ones from the #line directives.
The previous code would iterate over source file names (which in the UE case would be just hlsl.hlsl), and fail to find the filename that PIX is now asking to find the instructions for.
Instead, we now gather the filenames from the DebugLoc. Note that the filename comparison is done after the line number comparison for …
=> (Cherry-pick) PIX: Use DebugLoc for filenames instead of file list (#4077)

docs/SPIR-V.rst, include/dxc/HlslIntrinsicOp.h, lib/HLSL/HLOperationLower.cpp, tools/clang/include/clang/SPIRV/FeatureManager.h, tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/include/clang/SPIRV/SpirvModule.h, tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/FeatureManager.cpp, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/lib/SPIRV/SpirvModule.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.vkrawbufferload.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp, utils/hct/gen_intrin_main.txt
This PR adds a basic implementation of memory loads through `buffer_reference` mechanism in SPIR-V. Partially addresses #3772.
Current implementation only handles basic `uint` loads, with similar semantics as HLSL `ByteAddressBuffer` (4 byte alignment).
Example shader:
```
uint64_t Address;
float4 main() : SV_Target0 {
uint Value = vk::RawBufferLoad(Address);
return asfloat(Value);
}
```
Proposed change implements the minimal functionality required for Unreal Engine and I would like to keep the scope of this particular PR minimal. Custom alignment, large/vector loads, templated load syntax, stores, etc. would also be great to implement _(and I could do the work, if needed)_, but I would prefer to do them separately.
**Update:** The PR is now rebased and squashed, ready for review.
=> [spirv] Add Vk::RawBufferLoad intrinsic

include/dxc/HlslIntrinsicOp.h, lib/HLSL/HLOperationLower.cpp, tools/clang/include/clang/Basic/Attr.td, tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenSPIRV/spv.intrinsicExecutionMode.hlsl, tools/clang/test/CodeGenSPIRV/spv.intrinsicStorageClass.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp, utils/hct/gen_intrin_main.txt
[[vk::ext_storage_class(uint storage_class)]]
this is part of PRs for the
https://github.com/microsoft/DirectXShaderCompiler/issues/3919
=> [SPIRV] Add support vk::ext_execution_mode

tools/clang/include/clang/Sema/Sema.h, tools/clang/lib/Sema/SemaTemplateDeduction.cpp, tools/clang/lib/Sema/SemaType.cpp, tools/clang/lib/Sema/TreeTransform.h, tools/clang/test/HLSLFileCheck/hlsl/template/template-param-modifiers.hlsl
This addresses two issues that blocked template instantiation of
functions with ParameterModifiers.
The first issue is that template deduction was not propagating
ParameterModifiers, but since the modifiers do influence overload
resolution, matches were never being found.
The second issue is that template instantiation was not propagating
ParameterModifiers, so even if dedution managed to succeed, it would
produce an instantiaton that wouldn't match.
The silly issue that still remains after this is that our
ParameterModifiers sholud be attached to the QualType for the
parameters. We already bake in the effect of the ParameterModifier to
the QualType, so we were getting overload mismatches on identical
functions. If we move the ParameterModifiers to the QualTypes similar
to other type …
=> Propagate ParameterModifiers in templates

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSLFileCheck/hlsl/template/InstantiateBufferParamTypes.hlsl
This is a bit of an oddball situation caused by a two factors.
(1) We verify that template parameters for buffer types are complete
(2) The template expansion for the HLSL buffer types doesn't actually
require instantiation of the parameter type
We could, skip verification of template parameters, but doing so causes
the backend to crash because we need the buffer type expanded for code
generation. Skipping verification might work in some common cases, but
will fail if buffers are unused, and if nothing else forces the
instantiation.
The safe approach is to force instantiation ourselves, and that's what
this change does. Basically if the parameter of a buffer type is a
template specialization, we force the specialization to instantiate by
creating the specialization in the AST.
This allows …
=> [HLSL2021] Fix template parameter for buffer types

tools/clang/lib/SPIRV/AstTypeProbe.cpp, tools/clang/test/CodeGenSPIRV/spirv.stage-io.16bit.hlsl, tools/clang/test/CodeGenSPIRV/spirv.stage-io.relaxed-precision.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Hi, i found that by default, input/output variables 
won't be marked as RelaxedPrecision when using [min16float types](https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#id58). 
So the generated essl for example don't have mediump qualifier.
By considering ReferenceTypes in isRelaxedPrecisionType() function will add the correct decoration: 
```
OpDecorate %out_var_SV_Target0 RelaxedPrecision
OpDecorate %out_var_SV_Target1 RelaxedPrecision
OpDecorate %out_var_SV_Target2 RelaxedPrecision
OpDecorate %38 RelaxedPrecision
OpDecorate %39 RelaxedPrecision
```
```glsl
layout(location = 0) in highp vec4 in_var_TEXCOORD10_centroid;
layout(location = 1) in highp vec4 in_var_TEXCOORD11_centroid;
layout(location = 2) in highp vec4 in_var_TEXCOORD8;
layout(location = 0) out …
```
=> [spirv] isRelaxedPrecisionType() check for referenceTypes as well.

tools/clang/lib/AST/ExprConstant.cpp, tools/clang/test/HLSLFileCheck/hlsl/template/DependentNonTypeParam.hlsl
Non-type template parameters need more complicated constant resolution
because they need to look through layers of templates. This change
makes it so that when evaluating integer constants we use C++ 11
constant expression evaluation to look through template instantiations.
=> [HLSL 2021] Allow dependent non-type parameters

tools/clang/include/clang/AST/HlslTypes.h, tools/clang/include/clang/Basic/Attr.td, tools/clang/include/clang/SPIRV/SpirvContext.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/include/clang/SPIRV/SpirvType.h, tools/clang/lib/AST/ASTContextHLSL.cpp, tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.h, tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvContext.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/lib/SPIRV/SpirvType.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenSPIRV/spv.intrinsicTypeInteger.hlsl, tools/clang/test/CodeGenSPIRV/spv.intrinsicTypeRayquery.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
this is related
https://github.com/microsoft/DirectXShaderCompiler/issues/3919
=> [SPIRV] Add support of [[vk::ext_type_def]]

tools/clang/include/clang/Sema/Sema.h, tools/clang/lib/Sema/SemaExprCXX.cpp, tools/clang/lib/Sema/SemaExprMember.cpp, tools/clang/lib/Sema/TreeTransform.h, tools/clang/test/HLSLFileCheck/hlsl/classes/ThisReference.hlsl, tools/clang/test/HLSLFileCheck/hlsl/template/ThisAccess.hlsl
Prior to this change explicit `this` access inside a struct was treated
as a reference, but implicit `this` was still a pointer type. With this
change `this` is always a reference type.
This has no impact on code generation since references and pointers all
digress to addresses, but it does make the AST more accurately reflect
the types and it fixes #3732.
=> Make `this` more consistently a reference type

lib/Transforms/Scalar/MergedLoadStoreMotion.cpp, tools/clang/test/HLSLFileCheck/passes/mldst-motion/preserve-nonuniform.hlsl
In mldst-motion, use llvm::combineMetadata which is modified to preserve dxil metadata, instead of Instruction::dropUnknownMetadata.
Fixes #4120
=> Fix dropping of DXIL metadata like nonuniform in mldst-motion

tools/clang/lib/Sema/SemaExprCXX.cpp, tools/clang/lib/Sema/SemaOverload.cpp, tools/clang/test/HLSLFileCheck/hlsl/types/struct/method-implicit-this.hlsl
This catches a case I missed in #4112, for handling implicit `this` in
member method lookups.
=> Handle implicit `this` methods

docs/SPIR-V.rst, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/hs.const.output-patch.hlsl, tools/clang/test/CodeGenSPIRV/hs.pcf.output-patch.hlsl, tools/clang/test/CodeGenSPIRV/method.input-output-patch.access.hlsl
The existing code creates a temporary variable with Output storage class
for the parameter with OutputPatch type for the patch constant
functions. However, this adds an additional output stage variable and
consumes more locations. In addition, it can also change the rendering
result depending on the driver.
This commit removes the additional output stage variable and use the
actual output stage variables for the argument passing for the
OutputPatch. This is correctly working because the output stage variable
keeps the output value for all invocation id and we can simply reuse it.
Fixes #2641
=> [spirv] handle hull shader OutputPatch

CONTRIBUTING.md
This more clearly codifies and explains the guidelines we want for PR
titles and descriptions, and how they relate to final git commit
messages.
This isn't really a change from existing policy, but rather a
codification of the current expectations so that we have something clear
to point to.
=> [Doc] Updating guidelines for Pull Requests

lib/Transforms/Scalar/MergedLoadStoreMotion.cpp, tools/clang/test/HLSLFileCheck/passes/mldst-motion/preserve-nonuniform.hlsl
In mldst-motion, use llvm::combineMetadata which is modified to preserve dxil metadata, instead of Instruction::dropUnknownMetadata.
Fixes #4120
(cherry picked from commit ccf845a744627d65832f22000eb862a92399b1f6)
=> Fix dropping of DXIL metadata like nonuniform in mldst-motion (#4122)

include/dxc/Support/FileIOHelper.h, include/dxc/Support/HLSLOptions.td, include/dxc/Support/dxcfilesystem.h, lib/DxcSupport/FileIOHelper.cpp, tools/clang/tools/dxcompiler/dxcfilesystem.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
Extend the current text output `-encoding` option to also specify a default encoding for source files. 
Includes support for UTF-8 and UTF-16 encoded sources with and without BOMs. The default encoding, specified with the `-encoding` option, will be used for the main source file when there is no BOM and the DxcBuffer encoding is not specified. The default encoding will be used for included source files with no BOM.
=> Extend encoding option to specify source encoding

tools/clang/lib/SPIRV/SpirvEmitter.cpp
To ensure a deterministic order of the interface variable in
OpEntryPoint, use a SetVector to hold them.
Fixes #4088
=> [spirv] Use sequential container for ivars

.gitignore
This allows build directories to be ignored as long as they start with
the name `build`.
=> [NFC] Ignore all build* directories

external/CMakeLists.txt
=> [spirv] allow cmake to use external SPIRV-Tools/Headers

lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp
This fixes a regression introduced by https://github.com/microsoft/DirectXShaderCompiler/pull/3985
One IHV's driver compiler was upset by the placement of the allocas generated by this builder (m_B, that is).
Restoring the insertion point to the start of the function makes the driver happy again.
=> PIX: ensure allocas generated by value-to-declare dominate uses

tools/clang/include/clang/Driver/Options.td, tools/clang/lib/Frontend/CompilerInvocation.cpp, tools/clang/unittests/HLSL/VerifierTest.cpp
This fixes two issues in the verifier tests that impacted HLSL 2021.
(1) The verifier test runner only handles one `RUN` line, which results in the tests skipping subsequent lines. This becomes a problem with our pattern of features tests for HLSL 2021, where we verify both the individual feature flag and `-HV 2021`
(2) Turns out, the clang option parser had not been updated for HLSL 2021, and was not able to parse the option at all. We missed this because the second run line is the one that we put `-HV 2021` on, and because of the previous issue, we weren't running those tests. Additionally HLSL 2021 wasn't implemented with the same feature set in the clang driver, so I copied over the feature settings.
=> Fix verifier tests for HLSL 2021

lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp
This fixes a regression introduced by #3985
One IHV's driver compiler was upset by the placement of the allocas generated by this builder (m_B, that is).
Restoring the insertion point to the start of the function makes the driver happy again.
(cherry picked from commit b71cfcb07734948f64747c74eb7438d035dd7758)
=> PIX: ensure allocas generated by value-to-declare dominate uses (#4145)

tools/clang/include/clang/AST/Stmt.h, tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/lib/AST/Stmt.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/GlPerVertex.cpp, tools/clang/lib/SPIRV/GlPerVertex.h, tools/clang/lib/SPIRV/InitListHandler.cpp, tools/clang/lib/SPIRV/InitListHandler.h, tools/clang/lib/SPIRV/RawBufferMethods.cpp, tools/clang/lib/SPIRV/RawBufferMethods.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/test/CodeGenSPIRV/shader.debug.line.branch.hlsl, tools/clang/test/CodeGenSPIRV/shader.debug.line.composite.hlsl, tools/clang/test/CodeGenSPIRV/shader.debug.line.hlsl, tools/clang/test/CodeGenSPIRV/shader.debug.line.include.hlsl, tools/clang/test/CodeGenSPIRV/shader.debug.line.intrinsic.hlsl, tools/clang/test/CodeGenSPIRV/shader.debug.line.operators.hlsl, tools/clang/test/CodeGenSPIRV/shader.debug.line.precedence.hlsl, tools/clang/test/CodeGenSPIRV/shader.debug.line.variables.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
The continues the work of pt 1. In paticular, it improved DebugLine for
constructors; array refs; swizzle; increments; intrinsics; builtins;
if; loops; switch; variable initialization; compound assigns; zero casts;
texture samples; vector and matrix swizzle LHS assignment;
matrix, struct and array initializers; function call args;
matrix element stores; matrix multiply.
=> [SPIR-V] Improve lines and columns for DebugLine (pt 2)

tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSL/vector-select.hlsl, tools/clang/unittests/HLSL/VerifierTest.cpp
This updates the diagnostic for the HLSL 2021 short-circuiting ternary operator to issue a fixit suggesting using the select intrinsic. I don't have a good way right now to execute the FixIt, which makes it difficult to write a test that it applies cleanly. I'm working on that in a subsequent patch, but it's not going well...
This patch does add a test that verifies the error emission, and the diagnostic provided will include a FixIt resulting in the error output:
```
./vector-select.hlsl:14:17: error: condition for short-circuiting ternary operator must be scalar, for non-scalar types use 'select'
rw[0] = rw[0] ? rw[0] : c.f;
~~~~~~^~~~~~~~~~~~~
select(rw[0], rw[0], c.f)
```
=> FixIt diagnostic for HLSL 2021 ?: operator

tools/clang/include/clang/AST/Decl.h, tools/clang/lib/AST/Decl.cpp, tools/clang/test/HLSLFileCheck/hlsl/types/modifiers/precise/disable-nrvo.hlsl
Named return value optimization prevents allocating objects when
returning objects by value. This optimization trips up our
implementation of `precise` whihc requires the attribute be applied to
an `alloca`.
Disabling NRVO for Decls with the HLSLPreciseAttr attached avoids a
crash in the compiler.
Disabling this optimization should have no performance impact on most
existing HLSL code because function calls are inlined, and HLSL doesn't
support side-effecting constructors. Those two factors should allow the
optimizer to eliminte redundant copies even without NRVO enabled.
=> Disable NRVO for `precise` decls

tools/clang/lib/Sema/SemaExpr.cpp, tools/clang/test/HLSL/InputPatch-const.hlsl, tools/clang/test/HLSL/array-const-assign.hlsl, tools/clang/unittests/HLSL/VerifierTest.cpp
This change prevents dropping const qualifiers on array subscript
operators. Without this change the array subscript operator converts
from an lvalue to an rvalue that drops the type qualifiers. Since
arrays are actually addresses to the start of the array, it results in
dropping the qualifiers on the underlying array, making the array
modifiable.
This resolves #2860
=> Preserve qualifiers on array subscript

utils/hct/hctdb_instrhelp.py
Fix #4138 . Change the dict to tuple, because dict is not order preserved.
=> Fix the order of shader profiles in hct code gen

docs/SPIR-V.rst, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/test/CodeGenSPIRV/vk.combined-image-sampler.binding-shift.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
When command-line shift values are provided for binding numbers inferred
for register types, always use the t shift value for combined image
sampler resources, and ignore the s shift value.
Fixes #4166
=> [spirv] Use t shift for combined image samplers

docs/SPIR-V.rst, tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/include/clang/SPIRV/SpirvVisitor.h, tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/lib/SPIRV/CapabilityVisitor.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.h, tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/test/CodeGenSPIRV/spirv.builtin.helper-invocation.hlsl, tools/clang/test/CodeGenSPIRV/spirv.builtin.helper-invocation.vk1p3.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp, tools/clang/unittests/SPIRV/SpirvDebugInstructionTest.cpp, tools/clang/unittests/SPIRV/SpirvTestBase.h
For Vulkan 1.2 or less, we must not use HelperInvocation BuiltIn
decoration. Instread, for a variable with `[[vk::HelperInvocation]]`
attribute, we have to use `OpIsHelperInvocation` instruction:
- Create a variable (with `Private` storage class)
- In the module initialization, execute `OpIsHelperInvocation`
instruction and store the result in the variable
=> [spirv] use OpIsHelperInvocation for [[vk::HelperInvocation]]

tools/clang/tools/dxclib/dxc.cpp, utils/hct/hcttestcmds.cmd
Adding a warning when the shader model version is promoted from an older version to the 6.0 version. 
The motivation for adding this warning is to make this version promotion more explicit, clearing up errors if features from the newer SM are not supported on the driver.  Fixes #4038
=> Adding shader model version promotion warning

lib/Transforms/Scalar/DxilEraseDeadRegion.cpp, tools/clang/test/HLSLFileCheck/passes/EraseDeadRegion/wave_intrinsic_dead_loop.hlsl
Summary of the changes
- Issue was identified that dead loops with wave intrinsics were not being deleted which are marked as having side effects (due to code motion issues elsewhere).
- The code modified here was checking for wave intrinsics, but only for "self-loops". The code was updated to merge the check for safety (no side effects) and the self-loop check which are functionally equivalent in that both have to bail if the block is not safe to delete.
- During testing of the original change, some tests failed due to blocks not being properly deleted. The root cause of this was the walk of the successors is incorrect, since it would attempt to delete instructions that had uses later in the region. The code now does a post-order walk to satisfy these requirements.
=> Wave intrinsics inside of dead loops are not properly deleted

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/HLSLFileCheck/d3dreflect/ConstantBuffer-16bit.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/TextureBuffer-16bit.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/cbuffer-16bit.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/cbuffer-struct-16bit.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/lib_global.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/tbuffer-struct-16bit.hlsl
When using uint64_t fields in structures, the member was not being aligned to 8-bytes in constant buffers like it should be.
Constant buffer offsets come from type annotation information, rather than raw data layout.  The CBufferOffset for FieldAnnotation was not being properly aligned for u64 field types, though it was ok for i64.  This was because the offset alignment code was missing ULongLong when checking the basic type.
This change fixes the issue with a minimal change by adding ULongLong to the if condition.
Modified and added tests to check this case for StructuredBuffer, cbuffer/tbuffer (both inside and outside struct member), ConstantBuffer, and TextureBuffer.
=> Fix cbuffer alignment for u64, add tests

tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/rayquery_init_expr.hlsl, tools/clang/test/CodeGenSPIRV/rayquery_init_expr_error.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
The AST for `RayQuery` always has the initialization Expr e.g.,
```
`-VarDecl 0xba2768 <col:3, col:15> col:15 RayQ 'RayQuery<0>':'RayQuery<0>' callinit
`-CXXConstructExpr 0xba27d8 <col:15> 'RayQuery<0>':'RayQuery<0>' 'void ()'
```
Since the existing SPIR-V code gen simply uses the most recent "this" of
struct/class for CXXConstructExpr, RayQuery var defined after a struct or
class has weird initialization that results in failures.
This commit simply ignores the initialization Expr when it is
CXXConstructExpr e.g., `RayQuery<0> r = RayQuery<0>();` will not have
the initialization in SPIR-V. Note that we correctly handles the
initialization with another RayQuery var e.g.,
```
RayQuery<0> r = RayQuery<0>();
RayQuery<0> q = r;
```
Also note that the type mismatch for the initialization is …
=> [spirv] correctly handle rayquery var init Expr

lib/Support/Unix/Process.inc, tools/clang/include/clang/AST/HlslTypes.h, tools/clang/include/clang/SPIRV/AstTypeProbe.h, tools/clang/lib/AST/ASTContextHLSL.cpp, tools/clang/lib/AST/HlslTypes.cpp, tools/clang/lib/SPIRV/AstTypeProbe.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/lib/SPIRV/LowerTypeVisitor.h, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenSPIRV/spv.intrinsic.result_id.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
As a part of HLSL version of GL_EXT_spirv_intrinsics, this commit adds
vk::ext_result_id<T> type. We must use it for a variable definition or
a function parameter. It means we do not consider it as a physical
storage. Instead, it will be a result id of the instruction.
Related to #3919
=> [spirv] add `vk::ext_result_id<T>` type

lib/IR/AsmWriter.cpp
There was a bug that was reprocessing metadata of the entire function for every BasicBlock. When there's a lot of metadata and a lot of basic blocks, this becomes really slow.
Basically exactly [this](https://github.com/llvm-mirror/llvm/commit/812e1e45de5aac14029573e9fb81885922a2120b) upstream change.
=> Fixed SlotTracker slowness bug

tools/clang/include/clang/Basic/Attr.td, tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenSPIRV/spv.intrinsicDecorate.hlsl
As a part of HLSL version of GL_EXT_spirv_intrinsics, this commit adds
vk::ext_decorate_id attribute.
Related to #3919
=> [spirv] support [[vk::ext_decorate_id]] attribute

lib/HLSL/DxilPrecisePropagatePass.cpp, tools/clang/test/HLSLFileCheck/shader_targets/raytracing/precise_payload.hlsl
This fixes the OOB indexing by ending the loop early if GEP is deeper than the index list being matched.
Libraries with vectors, and intrnisics that operate on aggregate PTRs are not handled properly for precise propagation.
Some potential over/under marking is partially fixed by additional cases in PropagateOnPointerUsers:
- recurse GEP and Bitcast
- skip llvm intrinsics like lifetime
There's still some question as to how much we should really be marking precise (at function boundaries like TraceRay, for instance).
Basically, there's more to be done to improve precise propagation, potentially requiring a rewrite in the future.
But this change should improve things for now, and prevent a crash.
Fixes #4193
=> Fix OOB index when propagating precise through GEP

tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.cpp, tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.h, tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.struct.vulkan1.2.hlsl, tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.struct.vulkan1p2.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
This change modifies the RemoveBufferBlockVisitor to recurse through nested pointers to transform the storage class of inner pointers where required, as well as the fields of structs. Some uses arrays are handled by hasStorageBufferInterfaceType, but this PR leaves as a TODO further verification of the handling of of other composite types.
Fixes #4185, #4187
=> [SPIR-V] Handle storage buffer interfaces in structs

tools/clang/include/clang/SPIRV/FeatureManager.h, tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/lib/SPIRV/CapabilityVisitor.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/FeatureManager.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvModule.cpp, tools/clang/test/CodeGenSPIRV/volatile.interface.raygen.vk1p1.hlsl, tools/clang/test/CodeGenSPIRV/volatile.interface.raygen.vk1p2.hlsl, tools/clang/test/CodeGenSPIRV/volatile.interface.raygen.vk1p3.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Based on Vulkan spec
> VUID-StandaloneSpirv-VulkanMemoryModel-04678
If the VulkanMemoryModel capability is not declared, the Volatile
decoration must be used on any variable declaration that includes
one of the SMIDNV, WarpIDNV, SubgroupSize, SubgroupLocalInvocationId,
SubgroupEqMask, SubgroupGeMask, SubgroupGtMask, SubgroupLeMask, or
SubgroupLtMask BuiltIn decorations when used in the ray generation,
closest hit, miss, intersection, or callable shaders, or with the
RayTmaxKHR Builtin decoration when used in an intersection shader
> VUID-StandaloneSpirv-VulkanMemoryModel-04679
If the VulkanMemoryModel capability is declared, the OpLoad
instruction must use the Volatile memory semantics when it accesses
into any variable that includes one of the SMIDNV, WarpIDNV,
SubgroupSize, …
=> [spirv] propagate Volatile semantics for raytracing interface vars

tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSL/vector-and.hlsl, tools/clang/test/HLSL/vector-or.hlsl, tools/clang/unittests/HLSL/VerifierTest.cpp
Adding FixIts to the diagnostics for short-circuiting logical binary operations && and || on non-scalar values, to suggest logical intrinsics _and()_  and _or()_.
=> FixIt for HLSL 2021 logical operations && and ||

lib/HLSL/DxilValidation.cpp
The validation error was missing the arguments that gave important
information on the problem.
=> Correct validation error for col/row of storeoutput

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/tools/dxil2spv/CMakeLists.txt, tools/clang/tools/dxil2spv/dxil2spvmain.cpp
Modify SpirvBuilder to allow unset astContext, because astContext is
unavilable when translating from DXIL. Initialize a SpirvContext and
SpirvBuilder to generate a basic module, and output as disassembled
SPIR-V to STDOUT.
=> [dxil2spv] Construct minimal SPIR-V module

tools/clang/test/Dxil2Spv/passthru-ps.ll, tools/clang/tools/dxil2spv/CMakeLists.txt, tools/clang/tools/dxil2spv/dxil2spvmain.cpp, tools/clang/tools/dxil2spv/lib/CMakeLists.txt, tools/clang/tools/dxil2spv/lib/dxil2spv.cpp, tools/clang/tools/dxil2spv/lib/dxil2spv.h, tools/clang/unittests/CMakeLists.txt, tools/clang/unittests/Dxil2Spv/CMakeLists.txt, tools/clang/unittests/Dxil2Spv/Dxil2SpvTestOptions.cpp, tools/clang/unittests/Dxil2Spv/Dxil2SpvTestOptions.h, tools/clang/unittests/Dxil2Spv/FileTestUtils.cpp, tools/clang/unittests/Dxil2Spv/FileTestUtils.h, tools/clang/unittests/Dxil2Spv/LitTest.cpp, tools/clang/unittests/Dxil2Spv/TestMain.cpp, tools/clang/unittests/Dxil2Spv/WholeFileTestFixture.cpp, tools/clang/unittests/Dxil2Spv/WholeFileTestFixture.h
Add whole file testing for dxil2spv, starting with a simple passthrough
pixel shader. dxil2spv does not yet generate complete output for this
sample, but adding testing now will help reviewing iterations.
=> [dxil2spv] Add initial testing

tools/clang/include/clang/AST/Decl.h, tools/clang/lib/AST/Decl.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/CodeGen/CGHLSLRuntime.h, tools/clang/lib/CodeGen/CGStmt.cpp, tools/clang/lib/Sema/SemaStmt.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/Scenarios/glc-dynamic-return.hlsl, tools/clang/test/HLSLFileCheck/shader_targets/library/lib_mat_param8.hlsl
NRVO can drop type attributes not captured into QualType, like glc.  HLSL does not need NRVO, and it only poses problems in various areas, so this change turns it off globally for HLSL.
The test required an additional fix to resource return resprops merging, provided by @python3kgae.
=> Globally disable NRVO for HLSL; Merge resprops for resource return

tools/clang/tools/libclang/dxcrewriteunused.cpp, tools/clang/unittests/HLSL/ExtensionTest.cpp
When overrriding a semantic define with the -override-semdef flag
we could generate non-determinstic dxil output because the defines
would be listed in the source in a different order.
This commit fixes that bug by sorting the defines before writing
them into the dxil. We were missing tests for the -override-semdef
flag so I added those as part of this commit.
The newly added tests were passing before this change except for the
test for non-determinism.
=> Fix non-deterministic output when overriding semantic defines

include/dxc/DxilContainer/DxilContainerAssembler.h, lib/DxilContainer/DxilContainer.cpp, lib/DxilContainer/DxilContainerAssembler.cpp, tools/clang/unittests/HLSL/ValidationTest.cpp
- Maintain compatibility for validator version < 1.7.
- DxilContainerWriter_impl verifies size alignment for all parts, unless created with bUnaligned=true, used for backward compatibility.
- DxilValidation uses NewProgramSignatureWriter(), so bUnaligned is based on validator version in module.
Fixes #4236
=> Fix DxilProgramSignature size alignment.

include/dxc/DxilContainer/DxcContainerBuilder.h, lib/DxilContainer/DxcContainerBuilder.cpp, lib/DxilContainer/DxilContainerAssembler.cpp, tools/clang/unittests/HLSL/DxilContainerTest.cpp
Since all other blob parts are expected to be aligned, make sure we always add private data at the end of the container.
Update DxcContainerBuilder to keep private data at the end as well.
=> Allow unaligned private data size, by keeping it at end of container.

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
When replacing constant users, those users could be in functions other than the one being worked on.
The code would happily replace uses of the constant with instructions that weren't in the same function.
This would lead to bizarre consequences due to corrupt IR down the line.
This change prevents that from happenning.
=> Fix ReplaceMemcpy IR corruption on constant user replacement.

tools/clang/lib/Parse/ParseDecl.cpp
During parsing, some properties about attributes are determined by
matching the identifier used in the source with the attribute spelling
in Attr.td. The assumption here was that attributes are all
case-sensitive.  But HLSL attributes are not case-sensitive, and even
though code that matches these attributes to kind and determines
whether the attribute is valid has been adjusted to handle
case-insensitivity, the code that looks up properties had not.
One impact was that identifier arguments were not being recognized and
stored in the attributes properly (attributeHasIdentifierArg).
This change makes normalizeAttrName use lower() to force lowercase for
the incoming attribute name before it gets used in the StringSwitch.
normalizeAttrName now must return std::string instead of StringRef …
=> Fix bug with HLSL case-insensitive attribute parsing

include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLVersion.h, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/Basic/LangOptions.h, tools/clang/include/clang/Driver/Options.td, tools/clang/lib/AST/ASTContextHLSL.cpp, tools/clang/lib/Basic/CMakeLists.txt, tools/clang/lib/Basic/LangOptions.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp, tools/clang/lib/CodeGen/CGHLSLMSHelper.h, tools/clang/lib/Frontend/CompilerInvocation.cpp, tools/clang/lib/Frontend/InitPreprocessor.cpp, tools/clang/lib/Parse/ParseDecl.cpp, tools/clang/lib/Parse/ParseDeclCXX.cpp, tools/clang/lib/Parse/ParseStmt.cpp, tools/clang/lib/Sema/SemaCXXScopeSpec.cpp, tools/clang/lib/Sema/SemaChecking.cpp, tools/clang/lib/Sema/SemaDecl.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/lib/Sema/SemaOverload.cpp, tools/clang/lib/Sema/SemaStmt.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/tools/dxcompiler/dxcutil.cpp, tools/clang/tools/dxlib-sample/lib_share_compile.cpp, tools/clang/tools/dxrfallbackcompiler/dxcutil.cpp, tools/clang/tools/libclang/dxcrewriteunused.cpp, utils/hct/hcttestcmds.cmd
This change converts HLSLVersion to an enum type `hlsl::LangStd`. Most
of the change is a mechanical appending `hlsl::LangStd::v` to the
integers we previously compared for version checks.
Additionally this change does the following:
* Adds a parseHLSLVersion function to unify parsing code
* Parsing code is converted to an llvm::StringSwitch over the possible
values instead of converting to integer
* Added enum value for `vLatest` so that changing the latest version is
done in one place
* Added enum value for `v202x` which parses from 202x to allow new
language features a place to land
=> Refactor HLSLVersion to enum

tools/clang/lib/SPIRV/DebugTypeVisitor.cpp, tools/clang/test/CodeGenSPIRV/shader.debug.runtimearray.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
This is a common construct for bindless shaders.
=> [spirv] Generate correct Shader.DebugInfo for runtime arrays.

include/dxc/HLSL/HLSLExtensionsCodegenHelper.h, tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp, tools/clang/lib/CodeGen/ModuleBuilder.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/ExtensionTest.cpp
WriteSemanticDefines before clang codeGen to update codeGen option based on HLSLOptimizationToggles.
=> WriteSemanticDefines before clang codeGen to update codeGen option

docs/SPIR-V.rst, tools/clang/lib/Frontend/InitPreprocessor.cpp, tools/clang/test/CodeGenSPIRV/ifdef.spirv.hlsl, tools/clang/test/HLSLFileCheck/hlsl/preprocessor/version_defines/define_spirv.hlsl
We implicitly defined `__spirv` when SPIR-V code gen is enabled and
`-spirv` command line option is given. This commit changes it to
__spirv__.
=> [spirv] change __spirv definition to __spirv__

lib/HLSL/DxilPreparePasses.cpp, tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/wave/vote/any-all.hlsl, tools/clang/unittests/HLSL/ExecutionTest.cpp
This adds a first set of execution tests for QuadAny and QuadAll to test
compute, mesh, and amplification shaders. A separate execution test will
be coming for pixel shaders.
=> [SM6.7] QuadAny/All execution test (1/2)

include/dxc/DXIL/DxilUtil.h, lib/DXIL/DxilUtilDbgInfoAndMisc.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/HLSLFileCheck/dxil/debug/scoped_fragments.hlsl
Delete all dbg.declare instructions for allocas that are never touched in scopes. This could greatly improve compilation speed and binary size at the cost of in-scope but unused (part of) variables being invisible in certain functions. For example:
```
struct Context {
float a, b, c;
};
void bar(inout Context ctx) {
ctx.b = ctx.a * 2;
}
void foo(inout Context ctx) {
ctx.a = 10;
bar(ctx);
}
float main() : SV_Target {
Context ctx = (Context)0;
foo(ctx);
return ctx.a + ctx.b + ctx.c;
}
```
Before running this, shader would generate dbg.declare for members `a`, `b`, and `c` for variable `ctx` in every scope (`main`, `foo`, and `bar`). In the call stack with `foo` and `bar`, member `c` is never used in any way, so it's a waste to generate dbg.declare for member `c` for the `ctx` in scope `foo` …
=> Delete dbg.declare in scopes where the alloca is unused

lib/DXIL/DxilShaderFlags.cpp, tools/clang/test/HLSLFileCheck/hlsl/compile_options/res-may-alias.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/Cbuffer/uint64_2.hlsl
Avoid failure in existing driver on unrecognized raw flags.
=> Only set ResMayNotAlias flag when on DXIL 1.7

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
A valid vertex shader output variable with SV_Position semantics may be
constructed from any HLSL BuiltinType that translates to a 32-bit
floating point type in the SPIR-V backend, so relax the requirements to
allow the use of additonal types (such as half4) when
-enable-16bit-types is false.
Fixes #4262
=> [spirv] Relax SV_Position type requirements

tools/clang/lib/CodeGen/CGDebugInfo.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
Include handler is only meant to handle file requests.  However, if DebugCompilationDir is not set, CGDebugInfo::getCurrentDirname() will try to get the current working directory, and on (*nix) it will expand $PWD, then perform status() on that.  With a virtualized file system backed only by an include handler, you can't get thet status of files or directories, so failing the directory detection, it will attempt to open the file, which results in a call to get the file contents of the current working directory from the include handler.
The approach here is just to return DebugCompilationDir on HLSL, even if empty.
This prevents it from trying to fill it in automatically, cutting
off the path normally causing this problem.
Fixes #4212
=> Return empty string from CGDebugInfo::getCurrentDirname()

lib/HLSL/DxilCondenseResources.cpp, tools/clang/test/HLSLFileCheck/d3dreflect/tbuffer-16bit.hlsl
Uniquely detect low 16-bit usage properly for tbuffer, while detecting the case where full 32-bits are used that map to two 16-bit fields, requiring both fields to be marked.
=> Uniquely detect low 16-bit usage properly for tbuffer

include/dxc/Support/WinAdapter.h
REGDB_E_CLASSNOTREG was defined to 1, which is a success code for HRESULT.
This value is returned when trying to create an unsupported object with DxcCreateInstance.
Since create appears to have succeeded, it would lead to a deref of a null pointer - segfault.
=> [linux] Fix incorrect REGDB_E_CLASSNOTREG value

include/dxc/Support/WinAdapter.h, tools/clang/tools/dxcompiler/dxcapi.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/DxilContainerTest.cpp
This never got enabled in dxcapi.cpp in spite of all the code to support
it being in place. This enables the creation of the interface and
enables the tests that were disabled for want of it.
As an incidental, correctly defines the REGDB_E_CLASSNOTREG which made
the lack of this interface on Linux hard to diagnose.
=> Enable Container Builder on *nix

lib/DXIL/DxilShaderFlags.cpp
hasWriteableMSAATextures and hasAdvancedTextureOps were being set if you used CreateHandleFromHeap because of a missing break.
=> Missing break in CreateHandleFromHeap case caused unwanted shader flags

tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/ShaderOpTest.cpp, tools/clang/unittests/HLSL/ShaderOpTest.h
Because the LPCSTR set to shader stages in ShaderOp are used as a key,
the string pointer has to match an entry.  Normally this works because
all strings are added to a string map and the pointer from this is used
for all LPCSTR pointers.
ExecutionTest groups were trying to override the entries by searching each
entry point for the desired name, then setting the stage to the string
pointer of that entry, so the pointer would match.
Another way is to just use insert() on the string map, which is what all
the other code uses (during loading from XML, for instance).
This change adds ShaderOp::GetString() to make it convenient to get the
appropriate string pointer for whatever string you have, so you may simply
set this pointer to the shader stage, without iterating through all shaders, …
=> Exec tests: change string entry setting pattern

tools/clang/unittests/HLSL/ExecutionTest.cpp
Default D3D12SDKPath to ".\D3D12\"
Autodetect version when not specified or "/p:D3DSDKVersion=1"
If D3DSDKVersion specified, fail if it can't use Agility SDK.
=> ExecutionTest: Autofill Path/Version for AgilitySDK

cmake/modules/FindTAEF.cmake, utils/hct/hctbins.cmd, utils/hct/hctstart.cmd, utils/hct/hcttest.cmd
Use environment variable HLSL_AGILITYSDK_DIR which you can point to
extracted contents of an AgilitySDK.
Automatically copy binaries to appropriate location when set.
Look for MinTe binary set from TAEF.  If found, set a local TAEF binary
location.
If this is set when running execution tests, copy MinTe there, and if the
HLSL_AGILITYSDK_DIR was set, also copy agility SDK binaries under the
.\D3D12\ subdir there, so the test can automatically pick it up.
Add hctbins.cmd to copy extra bins necessary for running things out of
the ...\bin or ...\test directories such as HLSLHost.exe.  This includes
AgilitySDK bins if set.
=> New HLSL_AGILITYSDK_DIR and HLSLHost dependency copying help.

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp
This extends the existing compute test to cover Mesh and Amplifiction
shaders.
=> Extending QuadAnyAll test for MS and AS

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp
A texture containing an encoded value representing the X,Y location is
used to retrieve values at various samples using the 8 methods that
newly allow programmable values. Each result is compared to what is
expected based on the given coords and offsets.
=> ExecutionTest Programmable Sample Offsets

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp
A mipmapped texture containing the value of LOD at each location in each
level is used to sample at each level using SampleCmpLevel and confirm
that the correct level is used for the comparison.
Additionally, the result of SampleCmpLevelZero is compared to the
SampleCmpLevel equivalent
=> ExecutionTest for SampleCmpLevel

tools/clang/unittests/HLSL/ExecutionTest.cpp
The test was assigning a pixel shader that didn't exist due to the
conversion of mistaken code that was harmless in the previous form, but
results in an error message in the new.
=> Fix AtomicsShared64 ExecutionTest

tools/clang/include/clang/Lex/Token.h, tools/clang/lib/Parse/ParseDecl.cpp, tools/clang/lib/Parse/ParseDeclCXX.cpp, tools/clang/lib/Parse/ParseTemplate.cpp, tools/clang/test/HLSL/cpp-errors-hv2015.hlsl, tools/clang/test/HLSL/cpp-errors.hlsl, tools/clang/test/HLSLFileCheck/hlsl/namespace/using.hlsl, tools/clang/test/HLSLFileCheck/hlsl/namespace/using2.hlsl, tools/clang/test/HLSLFileCheck/hlsl/namespace/using3.hlsl
Enable 'using' keyword to help move hlsl intrinsic inside hlsl namespace.
This is just reenable existing c++ feature by remove check on HLSL.
=> Enable 'using' keyword.

lib/Analysis/DxilValueCache.cpp, tools/clang/test/HLSLFileCheck/hlsl/control_flow/switch/switch4.hlsl
Without this change, during DxilValueCache::ProcessAndSimplify_PHI,
MayBranchTo will return false for switch. If all but one case or default
block are collapsed into the switch's successor's phi (by simplifycfg), this
causes DxilValueCache to assume the remaining branch is the only predecessor
to the phi. If the corresponding incoming value is constant, DxilValueCache
will assume that's the only possible value, replacing the phi with the
constant.
With the change, MayBranchTo will return false only when a switch with a
constant condition would branch to a different successor.
Fixes #4208
=> DxilValueCache::MayBranchTo: handle phi from switch properly

cmake/modules/HandleLLVMOptions.cmake, include/dxc/DxilContainer/DxilPipelineStateValidation.h, include/dxc/DxilContainer/DxilRuntimeReflection.inl, include/dxc/HLSL/DxilSignatureAllocator.inl, include/dxc/Support/Global.h, lib/DXIL/DxilModule.cpp, lib/HLSL/DxilContainerReflection.cpp, lib/Support/MSFileSystemBasic.cpp, projects/dxilconv/lib/DxbcConverter/DxbcConverter.cpp, tools/clang/lib/AST/HlslBuiltinTypeDeclBuilder.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/tools/dxcompiler/dxcfilesystem.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/tools/dxcompiler/dxcvalidator.cpp, tools/clang/tools/dxrfallbackcompiler/dxcvalidator.cpp, tools/clang/unittests/HLSL/PixTest.cpp
This change removes the `DBG` macro value in favor of `NDEBUG`, and
also converts many uses of `_DEBUG` with `NDEBUG`.
`_DEBUG` is set by MSVC when debug information generation is enabled.
`NDEBUG` is set by CMake debug configurations and by LLVM on all
configurations when `LLVM_ENABLE_ASSERTIONS` is set.
Aligning with LLVM's `NDEBUG` usage allows a consistent pattern
throughout the codebase.
=> Clean up debug preprocessor macros

tools/clang/lib/AST/ASTContextHLSL.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSLFileCheck/hlsl/template/InstantiateObjectMethods.hlsl
Prior to this change the HLSL built in types are inserted into the AST
during initialization as complete types missing their methods. The
method implementations are then inserted during parsing when handling
declarators and parameter declarations of the built in types.
This method of lazy expansion does not work with HLSL templates because
template declarators in dependent contexts are not handled by the
parser, so they bypass the code path that generates method definitions
(see #4315).
This change alters how we lazy initialize types. Instead of
lazy-initializing in parsing, this change lazy initializes when the
type is required to be complete. This is accomplished by creating the
built in type objects as incomplete decls, and adding an override for
`CompleteType` to the …
=> Make external sema source handle type completion

lib/Transforms/IPO/CMakeLists.txt, lib/Transforms/Scalar/CMakeLists.txt, tools/clang/tools/dxil2spv/CMakeLists.txt, tools/clang/tools/dxil2spv/dxil2spvmain.cpp, tools/clang/tools/dxil2spv/lib/CMakeLists.txt, tools/clang/tools/dxil2spv/lib/dxil2spv.cpp, tools/clang/tools/dxil2spv/lib/dxil2spv.h, tools/clang/unittests/Dxil2Spv/FileTestUtils.cpp
Read DXIL file directly into llvm::MemoryBuffer rather than through an
IDxcBlobEncoding. This also allows support for supplying file by STDIN
(not yet with dedicated CLI).
Also clean up some CMake LLVM dependencies.
=> [dxil2spv] Read file directly into llvm::MemoryBuffer

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvFunction.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/include/clang/SPIRV/SpirvUtils.h, tools/clang/lib/SPIRV/CMakeLists.txt, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/lib/SPIRV/SpirvFunction.cpp, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/lib/SPIRV/SpirvUtils.cpp, tools/clang/test/Dxil2Spv/passthru-ps.ll, tools/clang/tools/dxil2spv/lib/dxil2spv.cpp, tools/clang/tools/dxil2spv/lib/dxil2spv.h
Translate a DXIL entry function to a SPIR-V entry function. This is
currently only supporting the few types and instructions needed to
create the entry function for a simple passthrough pixel shader.
=> [dxil2spv] Implement simple entry function creation

lib/Transforms/IPO/CMakeLists.txt, lib/Transforms/Scalar/CMakeLists.txt
It causes circular target dependency when embedding the DXC in an internal project and it does not seem like it is necessary (builds fine without it).
=> Remove LLVMHLSL dependency from IPO and ScalarOpts

tools/clang/include/clang/SPIRV/SpirvUtils.h, tools/clang/lib/SPIRV/CMakeLists.txt, tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/lib/SPIRV/LowerTypeVisitor.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvTypeVisitor.cpp, tools/clang/lib/SPIRV/SpirvTypeVisitor.h, tools/clang/lib/SPIRV/SpirvUtils.cpp, tools/clang/test/Dxil2Spv/passthru-ps.ll, tools/clang/tools/dxil2spv/lib/dxil2spv.cpp, tools/clang/tools/dxil2spv/lib/dxil2spv.h
Add SPIR-V validation after the module is generated, and apply some
fixes required for validation to succeed with a passthrough pixel
shader:
- Add execution mode
- Decorate with SPIR-V Locations
- Refactor some LowerTypeVisitor logic to a visitor that is shared with
dxil2spv
- Remove extra pointerness on stage IO vars now that it is handled by
the above pass
=> [dxil2spv] SPIR-V validation and related fixes

tools/clang/test/HLSLDisabled/memcpy_split_regression-strictudt.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/ExecutionTest.cpp, utils/hct/hcttest.cmd
- add arm64 argument to hcttest; use x86 as BUILD_ARCH instead of Win32 
- temporarily disable tests that have issues on ARM64, ARM64EC and WARP; bugs filed to track.
- remove obsoleted /labmode argument to TE.exe
- do not run arm64 tests in parallel (new TAEF has bug when -parallel is used, TAEF team has been notified)
=> Add -arm64 argument to hcttest; exclude tests with issues on ARM64 & WARP

tools/clang/lib/SPIRV/FeatureManager.cpp, tools/clang/test/CodeGenSPIRV/raytracing.target-env-error.hlsl
When the specific target environment required is exactly
SPV_ENV_VULKAN_1_1_SPIRV_1_4, then make the error message explicitly
note that it is met by Vulkan 1.1 with Spirv 1.4 (rather than simply
requiring Vulkan 1.2).
Fixes #4313
=> [spirv] Improve ray tracing capability error

include/dxc/DXIL/DxilModule.h, lib/DXIL/DxilModule.cpp, lib/DxilPIXPasses/DxilDebugInstrumentation.cpp, lib/DxilPIXPasses/PixPassHelpers.cpp
A couple of minor changes to support PIX shader debugging for hull shaders generated by the 11on12 mapping layer for DXBC originals.
=> Pix hull shader debug

tools/clang/test/Dxil2Spv/passthru-cs.ll, tools/clang/tools/dxil2spv/lib/dxil2spv.cpp, tools/clang/tools/dxil2spv/lib/dxil2spv.h, tools/clang/unittests/Dxil2Spv/LitTest.cpp
Implement first part of support for a passthrough compute shader.
This iteration translates the HLSL resources used in a simple
passthrough compute shader (ByteAddressBuffer and RWByteAddressBuffer)
to the appropriate SPIR-V module variables. Errors are emitted for
unhandled instructions.
=> [dxil2spv] Add initial compute shader support

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/test/Dxil2Spv/passthru-cs.ll, tools/clang/tools/dxil2spv/lib/dxil2spv.cpp, tools/clang/tools/dxil2spv/lib/dxil2spv.h
Translate the dx.op.threadId instruction to a load of a single element
of the SPIR-V BuiltIn GlobalInvocationID.
=> [dxil2spv] Add support for dx.op.threadId

tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.h, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
SPIR-V backend finds the source code by reading the source file,
which does not work when we pass the source code via memory
buffer. This commit adds a fallback for the case.
Fixes #4218
=> [spirv] fix source info bug for in-memory source code

tools/clang/tools/dotnetc/dndxc.csproj.txt
Updating the .NET version from 4.5(deprecated) to 4.8 to build on Windows11 with VS2022.
Fixes #4079
=> Updating the .NET version

tools/clang/include/clang/SPIRV/FeatureManager.h, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/FeatureManager.cpp, tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.cpp, tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.h
According to the SPIR-V validator this annotation was last usable on SPIR-V 1.3:
fatal error: generated SPIR-V is invalid: 2nd operand of Decorate: operand BufferBlock(3) requires SPIR-V version 1.3 or earlier
OpDecorate %type_ByteAddressBuffer BufferBlock
note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
The visitor was originally built to remove/omit it on Vulkan 1.2 and higher only, but since supporting Vulkan 1.1 with SPIR-V 1.4 (in #4364)
- which conveniently sits inbetween SPIR-V 1.3 and Vulkan 1.2 - the check must be made more stict and apply from SPIR-V 1.4 universal onwards.
=> Omit BufferBlock on SPIR-V 1.4 (~ Vulkan 1.1) instead of Vulkan 1.2

tools/clang/tools/dxil2spv/lib/CMakeLists.txt, tools/clang/unittests/Dxil2Spv/CMakeLists.txt
Address the "Policy CMP0023 is not set: Plain and keyword target_link_libraries signatures cannot be mixed." warning.
=> [dxil2spv] Fix build warning

tools/clang/lib/Sema/SemaType.cpp, tools/clang/test/HLSLFileCheck/hlsl/template/complete-array-parameter.hlsl
This is an odd edge case.
C doesn't require array element types to be complete because they decay
to pointers. In HLSL we don't decay to pointers, so we need them to be
complete, otherwise things trip up.
=> Complete builtin types when used as array params

tools/clang/lib/Sema/SemaStmt.cpp, tools/clang/test/HLSLFileCheck/hlsl/control_flow/return/EnableNRVO.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/modifiers/precise/disable-nrvo.hlsl
Enable NRVO when no precise and global coherent to avoid extra memcpy created in clang codeGen.
Also propagate precise from the function to named return value.
=> Reenable NRVO when no precise and global coherent.

lib/DxilPIXPasses/PixPassHelpers.cpp
This mistake was upsetting a certain driver.  The UAV being declared is always u0 in space -2. Also changed the name of one struct type to make it more obvious what PIX had added.
=> PIX: Incorrect index for CreateHandleFromBinding

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/test/Dxil2Spv/passthru-cs.ll, tools/clang/tools/dxil2spv/lib/dxil2spv.cpp, tools/clang/tools/dxil2spv/lib/dxil2spv.h
Add support for translating the first simple binary operator
instruction, shift left, from DXIL to SPIR-V.
=> [dxil2spv] Support shl instruction

include/dxc/HLSL/DxilGenerationPass.h, lib/HLSL/DxilSimpleGVNHoist.cpp, lib/Transforms/IPO/PassManagerBuilder.cpp, tools/clang/test/HLSLFileCheck/passes/hl/simple_gvn_hoists/simple_gvn_delete_region.hlsl, tools/clang/test/HLSLFileCheck/passes/hl/simple_gvn_hoists/simple_gvn_delete_region_inside_loop.hlsl, tools/clang/test/HLSLFileCheck/passes/hl/simple_gvn_hoists/simple_gvn_delete_region_loop.hlsl, tools/clang/test/HLSLFileCheck/passes/hl/simple_gvn_hoists/simple_gvn_delete_region_sideeffect.hlsl, utils/hct/hctdb.py
Sometimes GVN is turned off deliberately to avoid code motion, which can lead to certain redundant code being left behind. This change adds a pass that uses value numbering to identify and remove identical code from two sides of a conditional branch.
=> Added a pass to use GVN to remove redundant branches without doing code motion.

lib/DxilPIXPasses/PixPassHelpers.cpp
This mistake was upsetting a certain driver. The UAV being declared is always u0 in space -2. Also changed the name of one struct type to make it more obvious what PIX had added.
authored-by: Jeff Noyle <jeffno@ntdev.microsoft.com>
=> PIX: Incorrect index for CreateHandleFromBinding (#4382)

include/dxc/DXIL/DxilUtil.h, lib/DXIL/DxilUtil.cpp, lib/Transforms/IPO/PassManagerBuilder.cpp, lib/Transforms/Scalar/DxilEraseDeadRegion.cpp, lib/Transforms/Scalar/DxilRemoveDeadBlocks.cpp, tools/clang/test/HLSLFileCheck/passes/dxil/dxil_remove_dead_pass/delete_dead_region_after_remove_dead_blocks.hlsl
Reordered passes so now ExilEraseDeadRegions happens AFTER DxilRemoveDeadBlocks.
ExilEraseDeadRegions may depend on simplifications made by DxilRemoveDeadBlocks more than the reverse. The only thing that DxilRemoveDeadBlocks needed from ExilEraseDeadRegions was removing dead allocas that only had stores but no loads. This change also factors it out to a helper that both passes can call.
=> Moved DxilEraseDeadRegions to after DxilRemoveDeadBlocks

projects/dxilconv/lib/DxbcConverter/DxbcConverter.cpp
(cherry picked from commit 0c6435124770e9b3edb8dc1e8139d0d0f0e980c9)
=> Fix leak of DxilContainerWriter in DxbcConverter (#4400)

docs/SPIR-V.rst, include/dxc/Support/HLSLOptions.td, include/dxc/Support/SPIRVOptions.h, lib/DxcSupport/HLSLOptions.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/test/CodeGenSPIRV/fspv-entrypoint-name.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Allow renaming the SPIR-V entry point name from the default HLSL entry
point name with `-fspv-entrypoint-name`.
Fixes #2972
Fixes #4356
=> [SPIR-V] Add option to rename SPIR-V entry point

lib/Transforms/Scalar/DxilRemoveDeadBlocks.cpp, tools/clang/test/HLSLFileCheck/passes/dxil/dxil_remove_dead_pass/delete_constant_dce.hlsl, tools/clang/test/HLSLFileCheck/passes/dxil/dxil_remove_dead_pass/delete_constant_dce.ll
In some cases, DxilValueCache can simplify instructions where not all its operands can be simplified, for example:
```
%my_actually_dead_inst = ...
%my_const = fmul 0.0, %my_actually_dead_inst
```
`%my_const` can be simplified to 0, which the simplification pass removes, but `%my_actually_dead_inst` is incorrectly marked as being used by the output.
This change fixes this bug, and also takes extra care to preserve debug info for all deleted instructions that may be reduced to constant.
=> Removed all instruction made dead by their users being simplified in DxilRemoveDeadBlocks

lib/DXIL/DxilOperations.cpp, tools/clang/test/HLSLFileCheck/shader_targets/library/link_multi_traceray.hlsl
FixOverloadNames renames intrinsics to match renamed overload types,
which happen as a result of loading modules with conflicting types into
the same llvm context.  A conflicting type would be one that has the same
name but is a different type.
UDT arguments are always pointer types, so when the intrinsic overload is
based on a UDT argument, the type retrieved by GetOverloadType will be a
pointer.  The code did not handle this case, skipping the overload name fix.
This change adds the check for pointer type so UDT overloads will be fixed.
The test links two libraries with a conflicting UDT by the same name, used
in a TraceRay call.  This previously crashed during bitcode writing because
of invalid IR.
=> Handle UDT ptr collisions in FixOverloadNames

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/test/Dxil2Spv/passthru-cs.ll, tools/clang/tools/dxil2spv/lib/dxil2spv.cpp, tools/clang/tools/dxil2spv/lib/dxil2spv.h
Add support for translating createHandle and bufferLoad DXIL operations
to SPIR-V instructions. The most significant limitation of this current
implementation is the naive translation of descriptor set and binding
numbers, but it is sufficient for simple passthrough shaders.
Some error handling is also simplified with a wrapper function for the
frequently used instructionMap accesses.
=> [dxil2spv] Translate createHandle and bufferLoad

include/llvm/Analysis/DxilValueCache.h, lib/Analysis/DxilValueCache.cpp, tools/clang/test/HLSLFileCheck/passes/dxil/dxil_remove_dead_pass/switch_unroll_bound.hlsl, tools/clang/test/HLSLFileCheck/samples/d3d11/TessellatorCS40_TessellateIndicesCS.hlsl
- Taught DxilValueCache to handle switch statements where each case has more than just a single block.
- Fixed `DxilValueCache::ResetUnknowns` just setting value association to nullptr, which was entirely incorrect. Now it correctly deletes the value association that have been marked as unknown.
- Deleted the idea of 'AlwaysReachable' from DxilValueCache, which is unused, ill-defined, and potentially dangerous.
- Improved the dump function for 'DxilValueCache' for better debugging.
=> Taught DxilValueCache to handle complex switch statements.

include/dxc/Test/DxcTestUtils.h, lib/DxilContainer/DxilContainerAssembler.cpp, tools/clang/test/HLSLFileCheck/hlsl/signature/sig-dedup.hlsl, tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp
Create new `NameOffsetMap` that uses `StringRef` to prevent identical strings from being duplicated. Old behavior is maintained when earlier validator version set by using a `*_nodedup` map that continues to use a pointer to allow duplicates as previous validators did.
Fixes #3844
=> Dedup semantic names in IO signature parts for valver 1.7

tools/clang/test/Dxil2Spv/passthru-cs.ll, tools/clang/tools/dxil2spv/lib/dxil2spv.cpp, tools/clang/tools/dxil2spv/lib/dxil2spv.h
Add support for translation of LLVM extractValue operations and DXIL
bufferStore operations to SPIR-V instructions.
The bufferStore implementation is limited to what is required to
support a simple passthrough compute shader. For the yet unsupported
cases, an error is emitted.
=> [dxil2spv] Translate extractValue and bufferStore

tools/clang/unittests/HLSL/ExecutionTest.cpp
Creates a texture interface that represents an anonymous texture to be
populated with valid values then raw gathered from a shader and copied
to a UAV whose contents are compared with the original to verify correct
behavior. Derived textures use templating to share code that varies
depending on the type, type size, format characteristics (norm, signed,
etc), and number of channels.
This includes a fallback mechanism that uses a standard gather or loads
to retrieve the expected results from the aliased texture.
Some incidental refinements and corrections to the resource and view
creation functions
=> RawGather ExecutionTest

tools/clang/unittests/HLSL/ExecutionTest.cpp
This is causing VS2022 builds to fail with warnings-as-errors enabled.
=> [ATORawGather] Remove unreferenced local variable

lib/DXIL/DxilResourceProperties.cpp, tools/clang/test/HLSLFileCheck/hlsl/resource_binding/props_ms.hlsl, tools/clang/unittests/HLSL/ExecutionTest.cpp
This change fixes DXC to properly pass the SampleCount attribute to DXIL
metadata. A few test issues are also fixed, namely:
- Do not create upload resource for MSAA textures, since this will cause
a sample count mismatch in the runtime and we do not need the upload
resource anyway.
- Fix inverted logic to detect support for ATO and WritableMSAA.
- Pass D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET resource flag when
creating MSAA resource, which is required by the runtime.
=> [SM6.7][WritableMSAA] Front-end and test fixes

tools/clang/test/HLSL/ShaderOpArith.xml
Resource used as UAV must have TransitionTo="UNORDERED_ACCESS" for correct
runtime state.
These tests (by name in ShaderOpArith.xml) were missing this:
- Derivatives
- QuadRead
- ComputeSample
- ProgOffset
- SampleCmpLevel
- Saturate
- AtomicsRoot
- AtomicsHeap
- FloatAtomics
=> Fix TransitionTo for UAVs in various tests

include/dxc/dxcapi.h, tools/clang/tools/dxcompiler/dxclibrary.cpp
GetBlobAsWide was added as a new method to the existing interfaces,
but the existing GetBlobAsUtf16 should have simply been renamed to
GetBlobAsWide instead, since that's what GetBlobAsUtf16 actually did.
Otherwise interface compatibility is broken between builds/releases.
If we want to add a GetBlobAsUtf16 which guarantees UTF16 across platforms,
we can add that in a future interface revision.
=> Fix interface breaks in IDxcUtils and IDxcLibrary from GetBlobAsWide

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp
The following subtests have updated expected results to account for
helper lanes being a part of wave operations in SM 6.7:
- WavePrefixSum
- WaveMultiPrefixSum
- QuadReadAcross for lane 0
- WaveActiveBitXor
The WaveReadLaneFirst waterfall loop test has also been updated to use a
new loop structure for SM 6.7 as suggested by Tex.
=> [SM6.7][HelperLane] Test fixes for HelperLaneTestWave

tools/clang/test/HLSLFileCheck/hlsl/intrinsics/atomic/atomic_cmpstr_i64_and_i32.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/atomic/atomic_cmpxchg_i64_and_i32.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/atomic/atomic_xchg_i64_and_i32.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/atomic/atomicop_i64.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/atomic/atomicop_i64_and_i32.hlsl
The already broad i64 atomics testing was missing most coverage for
texture (image) types. This adds to atomicop_i64, and the various
atomic*_i64_and_i32 tests to use int64 texture types and verify the
DXIL output
=> Enhance i64 atomics testing for texture types

tools/clang/test/Dxil2Spv/passthru-ps.ll, tools/clang/test/Dxil2Spv/passthru-vs.ll, tools/clang/tools/dxil2spv/lib/dxil2spv.cpp, tools/clang/tools/dxil2spv/lib/dxil2spv.h
SV_Position elements in DXIL input signature should be treated as SPIR-V
BuiltIn variables with the Position type rather than regular stage IO
variables with a Location.
=> [dxil2spv] Translate SV_Position to BuiltIn::Position

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/tools/dxil2spv/lib/dxil2spv.cpp, tools/clang/tools/dxil2spv/lib/dxil2spv.h
Add intial handling of DXIL float constants, translating to SPIR-V float
constant instructions. Emit errors for other constant types not yet
handled.
=> [dxil2spv] Translate DXIL constants to SPIR-V

tools/clang/lib/SPIRV/AstTypeProbe.cpp, tools/clang/test/CodeGenSPIRV/oo.inheritance.base-with-byte-address-buffer.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
When we handle `Load/Store` method of ByteAddressBuffer, we first load
the ByteAddressBuffer object if it is a reference of an alias variable.
`this` object is a reference of an alias variable if a
ByteAddressBuffer is a member of the class. The existing code checks
members of the class to determine if it has ByteAddressBuffer or not,
but it does not check its parent. Since we add all members of a parent
to its child class, we have to check members of the parent as well.
This commit fixes the issue and now `loadIfAliasVarRef(..)` properly
loads the access chain to ByteAddressBuffer.
For example,
```
// HLSL:
struct Base {
ByteAddressBuffer buffer;
};
struct Child : Base {
float load(in uint offset) {
return asfloat(buffer.Load(offset));
}
};
// Before:
%param_this = OpFunctionParameter …
```
=> [spirv] Check parent class when setting contains-alias-component

lib/HLSL/DxilCondenseResources.cpp, tools/clang/lib/CodeGen/BackendUtil.cpp
Previously, during optimization passes, 
either exceptions would be thrown and diagnostic data would be lost, 
or fatal errors discovered during the passes would not prevent later passes from executing when execution should stop.
This change's purpose is to allow optimization passes the option to abort further compilation 
(stop later passes from executing), and capture relevant error data in the Diagnostic object before terminating.
This was tested with a cherry-pick here: bece3d4fafe4d7d50f5d0df59597a467d4f89f85,
and an accompanying hlsl file with invalid semantics. The thrown exception looked like this in HLSLSignatureLower.cpp:
```
void HLSignatureLower::Run() {
// Generate error and exit if semantic type
// is not one of the allowed types
if (!ValidateSemanticType(Entry))
throw …
```
=> enable optimization passes to throw hlsl exceptions

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp
Previously, this test failed to test dynamic resources with non-uniform indices.
Now, the test runs with multiple threads, and each thread may use 1 of 2 different indices
to access a resource, depending on pixel location or thread id.
#define NON_UNIFORM 
is used to force the test to enter the Non-uniform path, which (maybe)? is a stricter test than the uniform variant.
Although, the goal is to allow the test suite to define whether or not to run this test in Uniform or NON_uniform mode depending on a define like /DNON_UNIFORM
The default mode is Uniform. 
All resources were duplicated to allow each thread the option to select one or the other duplicate. 
At this point, the Non-Fallback path is passing on NVD hardware. More testing should be done before this gets checked in.
=> add non-uniform dynamic indexing option to dynamic resources uniform indexing test

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/HLSLFileCheck/hlsl/control_flow/unreachable-break.hlsl
CodeGen for unreachable break would normally skip generation, but DxBreak
mechanism would insert conditional branch still.  Unreachable location
means the builder has no insertion point.  This led to null preds for
blocks, and an AV in SimplifyCFG.
Checking CFG.HaveInsertPoint() is the mechanism used elsewhere to skip
CodeGen in unreachable locations, so this is added to EmitHLSLCondBreak.
Fixes #4422
=> Fix AV from DxBreak adding branch to null location (unreachable)

lib/HLSL/HLLowerUDT.cpp, tools/clang/test/HLSLFileCheck/shader_targets/mesh/as-groupshared-payload-method.hlsl
ReplaceUsesForLoweredUDT was calling use.set(NewV), or calling dropAllReferences() on constant user.
This results in modification of the constant operand, which is illegal and led to corruption of constants.
Loop in ReplaceUsesForLoweredUDT relies on all uses being eliminated to terminate, so constant or potentially constant users are now handled with legal replacements and removeDeadConstantUsers at the end as needed.
Fixes #4421
=> Fix use constant corruption from ReplaceUsesForLoweredUDT

lib/Transforms/IPO/PassManagerBuilder.cpp, tools/clang/test/HLSLFileCheck/passes/llvm/instcombine/del_phi_self_reference.hlsl
Lifetime markers require a cleanup pass to eliminate some unnecessary
code, however one of those passes was JumpThreading, which only
eliminated certain dead blocks, which eliminated phi instructions
leaving looped self increments unconditionally incrementing themselves,
which ended up with infinite recursion when trying to process that
instruction.
By adding Instcombining first, all unreachable blocks are elimianted
first so the partial elimination doesn't leave such bad phi users. To
avoid losing convergence for DXIL specific operations, we must first run
the convergent marker pass, so these passes are moved a little later
than before.
=> instcombine pass before jumpthread for lifetimes

cmake/modules/HandleLLVMOptions.cmake
Backport an LLVM cmake option to specify the C/C++ linker to use.
This implementation is simplified and unlike the llvm-project one does not contain any linker-specific tweaks.
On my system, setting `-DLLVM_USE_LINKER=mold` reduces the full build time from 81s to 43s.
=> [cmake] Allow to set C/C++ linker

tools/clang/include/clang/AST/HlslTypes.h, tools/clang/include/clang/Sema/SemaHLSL.h, tools/clang/lib/AST/ASTContextHLSL.cpp, tools/clang/lib/AST/HlslTypes.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/lib/Sema/SemaStmt.cpp, tools/clang/test/HLSLFileCheck/hlsl/control_flow/return/EntryFunctionDisableNVRO.hlsl
Disable NRVO for entry functions and patch constant functions.
For entry functions (and patch constant functions) each write to an output argument creates a new call to dx.storeOutput (or dx.storePatchConstant). With RVO enabled, every write to the return variable becomes an output instruction, which could be excessive. To avoid this, disable NRVO for any entry functions and patch constant functions.
=> Disable NRVO for entry functions and patch constant functions

lib/HLSL/DxilValidation.cpp, lib/Transforms/Scalar/DxilLoopUnroll.cpp, lib/Transforms/Scalar/HoistConstantArray.cpp, lib/Transforms/Scalar/LowerTypePasses.cpp, tools/clang/test/HLSLFileCheck/hlsl/control_flow/attributes/unroll/lib_2d_array_call_export.hlsl, tools/clang/test/HLSLFileCheck/hlsl/control_flow/attributes/unroll/lib_2d_array_call_export_subarray.hlsl, tools/clang/test/HLSLFileCheck/hlsl/functions/return_type/array/lib_function_call.hlsl
The codepath to detect lifetime-marker only uses (bitcast -> lifetime intrinsic), failed to check the instruction itself, which could be a user function call directly using the alloca ptr instead of the expected bitcast for the lifetime marker scenario.
If that user function call was unused (for instance, if it returns void), then it will improperly assume that the instruction is inconsequential and only used by lifetime markers, or is unused, thus doesn't matter.
The fix is to only check onlyUsedByLifetimeMarkers if the instruction is a bitcast, since that's the pattern for lifetime marker use on the alloca.  If the bitcast is unused, that's also safe to continue, since it does nothing on its own.
BreakUpArrayAllocas during DxilLoopUnroll had the same issue.  Targeting and testing this …
=> Fix lifetime marker detection causing other users to be missed

tools/llvm-dis/CMakeLists.txt, tools/llvm-dis/llvm-dis.cpp
This change has no impact on the DXC codebase since we don't use
llvm-dis here, but in LLVM upstream I'm using llvm-dis from DXC to
verify bitcode compatability.
The change here is to intercept the file passed into llvm-dis to detect
DXIL Container files, and read the bitcode out of the DXIL part.
=> Teach llvm-dis to read DXIL out of DXBC files

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/atomic/atomic_method_restypes.hlsl
The check for a const destination param for atomic functions mistakenly
encompassed the first param of atomic methods, which is an offset and
can very well be const. This changes the check to account for methods
when relevant.
Adds a test for this and a few other aspects of atomic methods
=> Correct const check for atomic methods

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp
Previously, no filter was specified for the samplers that perform a comparison. So, the filter defaulted to D3D_FILTER_ANISOTROPIC. The filter type should be D3D_FILTER_COMPARISON_ANISOTROPIC instead.
=> change filter comparison type for samplers, update test name

lib/DXIL/DxilUtil.cpp, lib/Transforms/Scalar/DxilConditionalMem2Reg.cpp, tools/clang/test/HLSLFileCheck/passes/dxil/dxil_remove_dead_pass/delete_dead_allocas.ll, tools/clang/test/HLSLFileCheck/passes/dxil/dxil_remove_dead_pass/delete_dead_allocas_memcpy.ll, tools/clang/test/HLSLFileCheck/passes/dxil/dxil_remove_dead_pass/delete_dead_allocas_memcpy2.ll
- Replaced the code to delete unread allocas in dxil-cond-mem2reg with calling the helper in dxilutils.
- Fixed a crash in the helper caused by walking the entry in forward order, which could invalidate next iterator.
- Added handling of memcpy's in the helper.
- Added tests that actually exercise the memcpy path.
=> Replaced some code in dxil-cond-mem2reg with a dxilutils helper. Fixed a crash.

tools/clang/unittests/HLSL/ExecutionTest.cpp
The previous approach was assigning garbage to the final field of desc1
due to alignment padding in desc0 where that field would be.
This just duplicates the utility function behavior to copy one desc to
the new one
=> Correctly copy to resource_desc1 in rawgather test

tools/clang/unittests/HLSL/ExecutionTest.cpp
Second argument should be D3D12_RESOURCE_DESC for the old version.
Function call needs a semicolon and no open curly brace.
=> Fix build break with new CopyDesc0ToDesc1

projects/dxilconv/lib/DxbcConverter/DxbcConverter.cpp
Thanks @jenatali for noticing the errant Detach()!  I think it was intended to be `->Detach()`, but was `.Detach()`.  The first would have simply cleared the pointer to the buffer that the stream object didn't own, the second tells CComPtr not to clean up the object itself, so nobody was cleaning it up.
However, `->Detach()` is also unnecessary because the stream can't and won't free the buffer that we want to keep anyway.
=> Fix leak of FixedSizeMemoryStream object from DxilConv

projects/dxilconv/lib/DxbcConverter/DxbcConverter.cpp
(cherry picked from commit 07bf1ae857b86777ca209baa58a96e1b597496c8)
=> Fix leak of FixedSizeMemoryStream object from DxilConv (#4483)

lib/HLSL/HLModule.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/HLSLFileCheck/passes/hl/sroa_hlsl/memcpy_digv_replacement.hlsl
Similar to how allocas are skipped when they are popped off of the
worklist and found to have no users, GVs are similarly removed and no
further processing is performed. That processing flattened the unused
GV, creating new child GVs and associating the debug info from the
parent with the children. Since the unused GV had all its uses replaced
with another, no debug info is found and the compiler crashed.
Also includes more graceful failure if debug info isn't found
Add a test that prompts that memcpy replacement order and verifies that
it doesn't crash and doesn't flatten the unused GV
=> Skip trivially dead GVs during SROA

tools/clang/unittests/HLSL/ExecutionTest.cpp
R8G8_B8G8_UNORM and G8R8_G8B8_UNORM are YUV formats really in spite of
not explicitly indicating by their names. We are leaving such out of
format casting for now
=> Remove YUV formats from rawgather test

docs/DXIL.rst, lib/HLSL/DxilValidation.cpp, tools/clang/unittests/HLSL/ValidationTest.cpp, tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp, utils/hct/hctdb.py
This change adds a validation rule for the inherited D3D11 requirement that a UAV store write mask must not contain gaps and therefore be one of the following: .x, .xy, .xyz, .xyzw.
Fixes #4161
=> Validate no gaps in UAV store writemask

include/dxc/Support/HLSLOptions.td, include/dxc/Support/SPIRVOptions.h, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/SPIRV/String.h, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/fspv-print-all.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp, tools/clang/unittests/SPIRV/StringTest.cpp
This debug/development option matches the `--print-all` flag in
spirv-opt or `--print-after-all`/`--print-before-all` in llvm's opt.
The new option can be enabled with `-fspv-print-all`.
=> [spir-v] Add option to print SPIR-V between passes

tools/opt/CMakeLists.txt, utils/hct/hctstart.cmd, utils/hct/hcttest.cmd
If tests are built as ARM64X, the test dll contains two versions of each test - the native ARM64 code and the emulation-ready x64 code (== ARM64EC). By default, TAEF will run both versions of the tests. The tests have the same name, so if one is failing, it is not clear if it is the ARM64 or ARM64EC version. 
It is preferable to run the tests for each platform separately. This PR adds @Architecture parameter to the TAEF tests invocation, which enables exactly that. The hcttest.cmd script has a new argument -arm64ec for running ARM64EC-only tests, and similarly the -arm64 will run only the native ARM64 tests.
Also includes couple of fixes in hctstart.cmd.
=> Add support for separate ARM64 and ARM64EC testing

lib/Support/Windows/Program.inc
This will fix issue when read input from stdin.
Without ChangeStdinToBinary, llvm-dis will get wrong size for stdin input in some case. That will cause 'Invalid bitcode size' error when parse bitcode.
=> Enable ChangeStdin/outToBinary for llvm-dis on Windows.

docs/SPIR-V.rst, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.round.hlsl
The specification for the HLSL round intrinsic function states "Rounds
the specified value to the nearest integer. Halfway cases are rounded to
the nearest even.", so translate it to RoundEven SPIR-V extended
instruction rather than Round.
Fixes #4368
=> [spirv] Translate HLSL round to RoundEven

docs/SPIR-V.rst, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.max.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.min.hlsl, tools/clang/test/CodeGenSPIRV/shader.debug.line.intrinsic.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.intrinsic.hlsl
The specification for the HLSL min and max intrinsic functions states
that if one of the values is NaN, the other will be given as the result,
which is correctly represented by the GLSL.std.450 instructions NMin and
NMax, respectively. By the semantics of the previously used FMin and
FMax instructions, this would be undefined behavior.
Fixes #3221
=> [spirv] Translate HLSL min/max to NMin/NMax

lib/DxcSupport/HLSLOptions.cpp, tools/clang/test/CodeGenSPIRV/spirv.opt.fd.hlsl, tools/clang/test/CodeGenSPIRV/spirv.opt.fre.hlsl, tools/clang/test/CodeGenSPIRV/spirv.opt.qstripreflect.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Some DXC options are not supported in combination with the SPIR-V
backend. Rather than silently ignore them, we should emit a clear error
message. This change adds appropriate error messages for a couple
options that have been mentioned in issues #3111 and #4496, but more
should be added in future.
=> [spirv] Fail when unsupported options are used

docs/SPIR-V.rst, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/test/CodeGenSPIRV/vk.binding.cl.register.missing-bind-globals.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
When -fvk-bind-register is used, all resource must have corresponding
register bindings set, including the Globals cbuffer. This change
clarifies the error message when the latter is the cause of failure and
directs the user to specify -fvk-bind-globals.
Fixes #3781
=> [spirv] Clarify error when Globals binding missing

lib/DxcSupport/HLSLOptions.cpp, tools/clang/test/CodeGenSPIRV/spirv.opt.gis.hlsl
Though we may support -Gis with the SPIR-V backend in future, it is
currently not supported, so this change makes that explicit to the user
with an error message when it is used.
Related to #3331
=> [SPIR-V] Error when -Gis is used with -spirv

docs/SPIR-V.rst, include/dxc/Support/HLSLOptions.td, include/dxc/Support/SPIRVOptions.h, lib/DxcSupport/HLSLOptions.cpp, tools/clang/lib/SPIRV/RawBufferMethods.cpp, tools/clang/test/CodeGenSPIRV/method.byte-address-buffer.templated-load.matrix.hlsl, tools/clang/test/CodeGenSPIRV/method.byte-address-buffer.templated-store.matrix.hlsl, tools/clang/test/CodeGenSPIRV/spv.use-legacy-buffer-matrix-order.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Assume that matrices are stored in the column major order in raw buffers, e.g., `ByteAddressBuffer` and `RWByteAddressBuffer`.
Add a new flag,`-fspv-use-legacy-buffer-matrix-order`, so that shaders that depend on the previous matrix order (row major) can opt-out of this change.
Fixes: https://github.com/microsoft/DirectXShaderCompiler/issues/3370
=> [spirv] Treat matrix load/stores as column major in raw buffers

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/ternary-op.cond-op.hlsl
Sometimes the Clang AST does not include an implicit cast wrapper around
an integer-type condition in the ternary operator, which causes a crash
when the SPIR-V generated has a non-bool type for the
OpBranchConditional. This change checks for this case and casts the
condition to bool.
Example ASTs:
```
// | `-ConditionalOperator 0x24022c82d48 <col:10, col:19> 'bool'
// |   |-ImplicitCastExpr 0x24022c82d00 <col:10> 'bool' <IntegralToBoolean>
// |   | `-IntegerLiteral 0x24022c82c58 <col:10> 'literal int' 1
bool b1, b2;
bool b = 1 ? b1 : b2;
// | `-ConditionalOperator 0x1ede5137380 <col:18, col:27> 'SamplerState'
// |   |-IntegerLiteral 0x1ede5137308 <col:18> 'literal int' 1
SamplerState s1, s2;
SamplerState s = 1 ? s1 : s2;
```
Fixes #3831
=> [spirv] Fix crash on some ternary ops

azure-pipelines.yml
According to Azure pipeline's document, the `$(...)` is used in bash to reference a variable. The original `${...}` doesn't really do it. `CC`, `CXX`, `CXX_FLAGS` are fine because they are also environment variables. But the `configuration` doesn't pass into CMAKE_BUILD_TYPE. The CI is actually build Debug build twice, not a Debug and a Release.
=> Pass parameters to CMake in a correct way

lib/HLSL/HLMatrixLowerPass.cpp, tools/clang/test/HLSLFileCheck/dxil/debug/hl_regression.hlsl
=> Fixed HLMatrixLower not copying over debug location to dbg.delcare

tools/clang/unittests/HLSL/ValidationTest.cpp
SkipDxilVersion skips test if the either the DXIL version (DxCompiler) or
Validator version (DXIL.dll if external) is less than the specified version.
This message is being added in version 1.7, so the skip value needs to be
1.7 to skip unless it's version 1.7 or higher.
Without this fix, these tests fail when run with DXIL.dll version 1.6.
=> Fix version skip for UAVStoreMaskGap to exclude v1.6

lib/Transforms/Scalar/DxilConditionalMem2Reg.cpp, tools/clang/test/HLSLFileCheck/dxil/debug/new_noops_call.hlsl, tools/clang/test/HLSLFileCheck/dxil/debug/no_fold_vec_array.hlsl, tools/clang/test/HLSLFileCheck/passes/hl/mem2reg_hlsl/mem2reg_simple_split.ll, tools/clang/test/HLSLFileCheck/passes/hl/mem2reg_hlsl/mem2reg_simple_split_varlayout.ll
Added a simple transformation before mem2reg to change all allocas of scalar arrays to individual scalar allocas. This could make value deduction easier in Od compilation.
=> Splitting simple array during mem2reg.

tools/clang/unittests/HLSL/ExecutionTest.cpp
Two of the Advanced Texture Ops feature tests were missing the check for
the feature in addition to the check for 6.7 support. This adds those
checks
=> Add checks to advanced tex ops exectests

tools/clang/test/HLSL/ShaderOpArith.xml
For Vertex Shader, use VertexID to check last lane instead of WaveGetLaneIndex() == WaveActiveMax(WaveGetLaneIndex()).
This is for case where 3 vertices not in same wave and g_TestResults[VS_INDEX] will be write more than once with different value.
=> Use VertexID to check last lane.

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/cf.return.void.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
This fixes a bug where invalid SPIR-V would be emitted when returning a void value from a void function. According to the spec, the `Value` of `OpReturnValue` must not have type `OpTypeVoid`; therefore, `OpReturn` will now be emitted instead.
Fixes #3596
=> [SPIRV] Fix crash when returning void

utils/hct/hctgen.py
Depending on build ordering the output directory may not be created
before the output file is written. This resolves the issue by forcing
the creation.
Resolves #4570.
=> NFC. Ensure that the output directory exists

tools/clang/lib/AST/HlslTypes.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/RasterizerOrderedBuffer/rovtype.hlsl
The HLSL type system was failing to recognize the
RasterizerOrderedTexture2D type as a resource type. As a result, it was
not getting annotated properly during UAV codegen and when the time came
to assign a struct member of that type, there was no declaration to use
to do so. This resulted in a validation failure when used as a struct
member.
By simply adding it to the list of detected resource types, the
assignments are successful.
Fixes #4578
=> Recognize RaserizerOrderedTexure as resource type

utils/hct/hctstart.cmd
vs2022 installs in a different location, so finding cmake requires a
slightly different path. Variable assignment in batch files is ugly.
Duplication of code slightly less ugly.
Mostly done by @tex3d
=> Add vs2022 support to hctstart

docs/SPIR-V.rst, include/dxc/HlslIntrinsicOp.h, lib/HLSL/HLOperationLower.cpp, tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.vkrawbufferstore.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp, utils/hct/gen_intrin_main.txt
Previously, dxc only supported vk::RawBufferLoad for vulkan physical device addressing. 
This pull request introduces vk::RawBufferStore, following in the footsteps of the vk::RawBufferLoad feature. 
Fixes #4568
=> [SPIRV] Add support for vk::RawBufferStore

tools/clang/lib/AST/ExprConstant.cpp, tools/clang/test/HLSLFileCheck/validation/NonVLAArrays.hlsl
added an extra case to use the comparison function for "min" when handling intrinsics that define the size of an array.
This PR should partially address #3355
=> allow array sizes defined by min ops to not be treated as variable length

tools/clang/include/clang/SPIRV/AstTypeProbe.h, tools/clang/lib/SPIRV/AstTypeProbe.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/method.rw-structured-buffer.counter.hlsl, tools/clang/test/CodeGenSPIRV/namespace.resources.hlsl, tools/clang/test/CodeGenSPIRV/spirv.legal.counter.nested-struct.hlsl, tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.counter.hlsl, tools/clang/test/CodeGenSPIRV/type.structured-buffer.hlsl, tools/clang/test/CodeGenSPIRV/vk.1p2.remove.bufferblock.ptr-to-ptr.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.cl.register.counter.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.counter.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.default-space.implicit.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.explicit.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.implicit.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.precedence.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.register.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.register.space-only.hlsl
Defer creating counter for RWSBuffer until Inc/DecrementCounter method
is invoked.
Fixes #4569
=> [SPIRV] Do not create counter for RWStructuredBuffer by default

lib/Transforms/Scalar/DxilLoopUnroll.cpp, tools/clang/test/HLSLFileCheck/hlsl/control_flow/attributes/unroll/pass_reuse_regression.hlsl
Fixed when there are multiple functions with loops that can't be unrolled at
the point of doing [unroll], the unroll pass crashes because it didn't clean up
memory between runs.
=> Fix unroller crash in library targets

tools/clang/lib/AST/HlslTypes.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/RasterizerOrderedBuffer/rovtype.hlsl
Includes all the Raster Order Views types in the check for UAVs and add
a test that exercises all of them, verifying they can be assigned
properly.
Followon to fix #4581 for bug #4578
=> Accept all ROV types as resources

lib/HLSL/DxilCondenseResources.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilLinker.cpp, lib/HLSL/DxilPromoteResourcePasses.cpp, lib/HLSL/HLOperationLower.cpp, lib/HLSL/HLSignatureLower.cpp, tools/clang/test/CodeGenHLSL/printf.hlsl, tools/clang/test/HLSLFileCheck/hlsl/operators/swizzle/swizzleAtomic2.hlsl, tools/clang/test/HLSLFileCheck/hlsl/resource_binding/unbound_overlap.hlsl, tools/clang/test/HLSLFileCheck/hlsl/semantics/legacy/obsolete_semantics_ps_1.hlsl, tools/clang/test/HLSLFileCheck/hlsl/semantics/legacy/obsolete_semantics_ps_2.hlsl, tools/clang/test/HLSLFileCheck/hlsl/semantics/sv_clipdistance/clip_planes_output_error.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/modifiers/static/static_global_lib_error.hlsl, tools/clang/test/HLSLFileCheck/shader_targets/mesh/mesh_invalid_interpolation_modes.hlsl, tools/clang/unittests/HLSL/LinkerTest.cpp
This change cleans up the diagnostics emitted in the /lib/HLSL and /lib/DXIL. This started as an exploration of moving post codegen and pre validation diagnostics earlier in compilation. Most of the functional change here is to add testing for untested errors and change unreachable errors to internal compiler errors. For each diagnostic: 
1. Changed to the updated dxilutil error emitting functions
2. Added a test if untested
3. Changed to an internal compiler error if unreachable
=> Add diagnostic tests

include/dxc/DXIL/DxilModule.h, lib/DXIL/DxilModule.cpp
m_bResMayAlias was not initialized, leading to intermittent failures
when it was not explicitly set. The only functional change here is
setting that variable to eliminate that volatility. The other changes
are to move the setting of these simple typed variables to the header to
make it less likely that future added members will suffer the same fate.
Also in the process, I couldn't resist removing an unused variable added
along with the Payload Access Qualifiers in error, removing redundant
private regions, and moving the private methods out of the middle of
all the variable members.
Fixes #4616
=> Initialize all DxilModule members

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/test/CodeGenSPIRV/shader.debug.function.hlsl
The DebugFunctionDefintion in the user's entry function called
by the wrapper is omitted. All other DebugFunctionDefinition
instructions are still generated.
This is done because inlining during legalization omits
inlining the DebugFunctionDefintion because its function
no longer exists. This results in all DebugFunctionDefinitions
being eliminated for HLSL because every function is inlined into
the wrapper function.
The solution is to generate the entry point function's
DebugFunctionDefinition in the wrapper to start with.
=> [SPIR-V] Generate Shader.DebugInfo DebugFunctionDefinition in the wrapper function

include/dxc/Test/DxcTestUtils.h, tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/ShaderOpTest.cpp, tools/clang/unittests/HLSL/ShaderOpTest.h, tools/clang/unittests/HLSL/ValidationTest.cpp, tools/clang/unittests/HLSLTestLib/DxcTestUtils.cpp
This change adds an hlktest to test the isSpecialFloat dxil call. This test facilitated by the implementation of a new feature for the shader op test framework: shader call back functions. This specific test was implemented by taking the dxil generated from an isnan call in the source, and replacing it with the "isSpecialFloat" dxil call using various disassembly replacement functions.
=> Isnormal hlktest

tools/clang/unittests/HLSL/ExecutionTest.cpp
Windows Basic Render Driver on Windows 11 is a separate version than in Windows Server 2022. IsNormal passes on the Win11 version, but not on Win Server 2022. This PR will make the Wintools build pipeline skip the IsNormal HLK test to avoid the known failure that is encountered when running the test in the lab environment. It also pushes this driver detection logic to the top of the test function to avoid doing potentially unnecessary work.
=> Skip test when using BDA, move check logic up as high as possible

cmake/modules/FindD3D12.cmake
Let the build system find the libraries based on the Windows SDK used by cmake.
Enables use of Windows SDK from nuget packages.
=> Remove lookup of full paths of D3D12 libraries

cmake/modules/HandleLLVMOptions.cmake, utils/hct/hctbuild.cmd
This adds a new option to the build to enable link-time optimzied builds of DXC. On Windows with MSVC this seems to give about a 4% runtime performance boost on my one locally run test case... and on Linux I'm seeing about 6% on that same locally run test case.
It's free performance so yay :D
=> Add option to enable LTO/LTCG

lib/Support/MemoryBuffer.cpp, tools/clang/include/clang/SPIRV/FeatureManager.h, tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/lib/SPIRV/FeatureManager.cpp, tools/clang/test/CodeGenSPIRV/semantic.render-target-array-index-core.vs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.viewport-array-index-core.vs.hlsl, tools/clang/test/CodeGenSPIRV/spv.intrinsicInstruction.hlsl, tools/clang/tools/dxclib/CMakeLists.txt, tools/clang/tools/dxclib/dxc.cpp, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp, tools/clang/unittests/SPIRV/FileTestFixture.cpp, tools/clang/unittests/SPIRV/FileTestUtils.cpp, tools/clang/unittests/SPIRV/FileTestUtils.h, tools/clang/unittests/SPIRV/WholeFileTestFixture.cpp
Back in Vulkan1.1, ShaderViewportIndexLayer was required to use SV_RenderTargetArrayIndex. This was promoted in VK1.2:
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_shader_viewport_index_layer.html
Sadly, DXC didn't checked the target SPV environment, and always requested the extension. This commit addresses this.
Additionally, when DXC finishes generating SPIR-V, the binary is disassembled and printed to stdout.
The target env was hardcoded to Vulkan1.1, meaning disassembly would fail if we tried disassembling Vulkan1.2+ SPIR-V.
=> Fix Layer & ViewportIndex ext in 1.2+ 

tools/clang/tools/dxcompiler/dxcpdbutils.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
The entry point member variable is currently only set if the dxilcontainer contains a DFCC_ShaderSourceInfo header.
This change will set the entry point default to main regardless of which headers can be found in the container.
=> move entry point default code

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/binary-op.short-circuited-logical-and.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.short-circuited-logical-or.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
This implements logical AND and logical OR short-circuiting, which was added with HLSL 2021.
Note: the ternary operator is also short-circuited since HLSL 2021. I will implement that in a follow-up PR.
Issue: #4141
=> [SPIR-V] Add short-circuiting logical operators for HLSL 2021

include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/lib/CodeGen/CodeGenAction.cpp, tools/clang/test/HLSLFileCheck/validation/ResourceResolvingNoDI.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp
This is (admittedly) a little hacky. DXC spends a lot of compile time updating debug information because we always generate it so that we can generate diagnostics for late-running validation.
This flag disables that validation resulting in about a 15% compile time improvement on a pessimistic inliner test.
=> Add option to force disabling debug info

include/dxc/DxilContainer/DxilRuntimeReflection.h, include/dxc/DxilContainer/RDAT_Macros.inl, include/dxc/DxilRDATBuilder/DxilRDATBuilder.h, include/dxc/DxilRDATBuilder/DxilRDATParts.h, lib/CMakeLists.txt, lib/DxilContainer/DxilContainerAssembler.cpp, lib/DxilRDATBuilder/CMakeLists.txt, lib/DxilRDATBuilder/DxilRDATBuilder.cpp, lib/DxilRDATBuilder/LLVMBuild.txt, lib/LLVMBuild.txt
- Pulled out RDAT writing from DxilContainerAssembly into its own helper DxilRDATBuilder
- Changed the way RawBytesPart deduplicates inputs. Instead of using the pointer address, use the data's content as keys in a hash table, then writing it to the final buffer in the order they were inserted.
=> Separated RDAT creation code into its own library

tools/clang/lib/SPIRV/DebugTypeVisitor.cpp, tools/clang/test/CodeGenSPIRV/shader.debug.file.composite.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
This fixes a crash when generating source debugInfo for composite types across multiple source files.
=> [SPIR-V] Handle debugInfo for composite types across source files

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/fn.param.default.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
This uses `getUninstantiatedDefaultArg` to get the default value of the parameter and casts it to the appropriate type.
Fixes #4169
=> [SPIR-V] Fix default arguments for function templates

CMakeLists.txt, cmake/modules/HandleLLVMOptions.cmake
I added this upstream a few years ago so that you can control passing `-O1` to the compiler when building debug sanitized builds. Without being able to disable optimizing sanitizer builds it is really tricky to debug sanitizer failures, but without optimizing the build ASan builds take _forever_ to run tests which makes them difficult to use.
=> Add `LLVM_OPTIMZIE_SANITIZED_BUILDS` option

tools/clang/test/HLSL/ShaderOpArith.xml
Use the last lane in the wave with VertexID 2 instead of the lane with VertexID 2 when writes results.
=> Fix issue in HelperLaneTestWave ExecutionTest caused by assume last lane has VertexID 2.

tools/clang/test/HLSL/ShaderOpArith.xml
Use the last lane in the wave with VertexID 2 instead of the lane with VertexID 2 when writes results.
=> Fix issue in HelperLaneTestWave ExecutionTest caused by assume last lane has VertexID 2. (#4670)

lib/DXIL/DxilShaderModel.cpp, utils/hct/hctdb_instrhelp.py
ShaderModel::Get() used a static std::unordered_map which is torn down when custom allocator may no longer be active.
Resolves #4655.
=> Fix error on shutdown when using custom memory allocator

lib/DXIL/DxilShaderModel.cpp, utils/hct/hctdb_instrhelp.py
Fixes a bug introduced in commit 8b8956f82be592ed774ee8c59980d6336a67bff0 (cc @pow2clk)
=> Fix ShaderModel::Get() when entry does not exist in hashToIdxMap

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/test/CodeGenSPIRV/intrinsics.and.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.or.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.select.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Implemented `and`, `or`, and `select`. I used the existing tests for the old behavior of `&&`, `||`, and `?:` in order to verify that they behave as expected (with the caveat of #4673, but that has the same behavior for DXIL as for SPIR-V).
Fixes #4148
=> [SPIR-V] Add support for logical operator intrinsics

include/dxc/DxilContainer/DxilRuntimeReflection.h, include/dxc/DxilContainer/RDAT_Macros.inl, include/dxc/DxilRDATBuilder/DxilRDATBuilder.h
Added MaxRecordSize calling DerivedRecordSize that gets specialized for each base in RDAT_STRUCT_TABLE_DERIVED macro to call the derived MaxRecordStride.  The most-derived version of DerivedRecordSize will use the default implementation, which is the size of that type.
=> Add RDAT::RecordTraits::MaxRecordSize to default to newest version

tools/dxexp/dxexp.cpp
- add D3D12_FEATURE_DATA_D3D12_OPTIONS14 definition if not supported by current WinSDK
- move all D3D_SHADER_MODEL defines into one spot
=> dxexp - report advanced texture ops capability

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSLFileCheck/hlsl/types/cast/implicit-cast-almost-identical.hlsl
It's possible to get a value of a type `unsigned long` in HLSL, such as
the result of sizeof(), while the uint type is `unsigned int` instead.
This leads to the situation where no cast is inserted because the types
look identical when translated down to ArBasicKind, which can lead to an
assert during codegen, such as when passing sizeof() result to a function
call parameter.
This change preserves the original canonical type ptr from clang and
sets the conversion type when these differ, even when ArBasicKind is
identical.
=> Insert cast when types are identical to HLSL but not to clang

include/dxc/DxilRDATBuilder/DxilRDATBuilder.h
On second thought, it's safer to default to the initial version, letting code that writes to RDAT set strides for newer record versions it actually uses, rather than breaking RDAT writing code at runtime when versioned updates are added to the structures.
=> RDAT: Revert default to MaxRecordSize for tables

include/dxc/Test/HlslTestUtils.h
A very strange sequence of copying the run line to a stack char array of size 300, where it would not even null-terminate the line if it hit the limit, seems totally unnecessary, since it's dealing with std::strings in the first place.
This would truncate and pick up garbage from the stack in the stored run line when length >= 300 characters - causing the test to fail, of course. Perhaps some of this is an artifact of some older version of the code.
In any case, this change removes the extra copying step and simply uses the entire std::string result from std::getline() instead.
=> Remove arbitrary run line length limit

include/dxc/HLSL/DxilPoisonValues.h, lib/HLSL/CMakeLists.txt, lib/HLSL/DxilPoisonValues.cpp, lib/HLSL/DxilPreparePasses.cpp, lib/HLSL/HLOperationLower.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/vector_subscript.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/vector_subscript_16bit.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/vector_subscript_16bit_error.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/vector_subscript_error.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/vector_subscript_error_noscope.hlsl
There was a crash when CBuffer vector subscript uses a non-literal index but is replaced with Constant in the optimizer before CBuffer load is lowerd. The CBuffer lowering code expects the constant to be within bounds, since it's translating the GEP to extractvalue. The out of bounds subscript is not correct and should cause an error, but ONLY if it actually exists in the final DXIL.
This change adds a way to emit error that only get emitted if the associated code is not removed by the end of compilation. Instead of emitting an error right away, emit a poison value with line number and error message instead and have it used by the problematic code. If the problematic code is not removed by the end of compilation, then this poison value would also be there, and it's safe to emit a real …
=> Fixed a crash with cbuffer lowering with new poison value mechanism

include/dxc/DxilContainer/DxilContainer.h, include/dxc/Test/DxcTestUtils.h, include/dxc/Test/HlslTestUtils.h, tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/ValidationTest.cpp, tools/clang/unittests/HLSLTestLib/DxcTestUtils.cpp
The IsNormal HLK test depends on a function called ReplaceShaderText.cpp.
As it is currently defined, the function takes a dependency on llvm for regex usage.
This dependency prevents successful builds when copied over to another repo.
IsNormal depends on other functions with bad dependencies, so this is the first of several PRs to get IsNormal 
to a state in which it only depends on what is available in the other repo. 
This PR divides ReplaceDisassemblyText  (RDT) into 3 functions, RDT, RDTWithoutRegex, and RDTWithRegex.
RDT will call the other 2 functions depending on whether the caller specified that any of the LookFor strings contain a regex, with the boolean parameter passed to RDT.
Because RDTWithoutRegex will be defined in HLSLTestUtils.h, it will be available in the other repo …
=> Pull ReplaceDisassemblyText out of DXCTestUtils.cpp

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.asfloat16.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.asint16.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.asuint16.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
This change adds support for 16-bit type cast intrinsics by routing them into the same logic used by the 32-bit type casts. With this change in place, asfloat16, asint16, and asuint16 are now translated into OpBitcast in SPIR-V.
This change also includes new partial disassembly tests for each function similar to the ones used for 32-bit casts.
=> [SPIRV] Support 16-bit Type Cast Intrinsics

include/dxc/DXIL/DxilMetadataHelper.h, include/dxc/DXIL/DxilModule.h, include/dxc/DXIL/DxilTypeSystem.h, include/dxc/HLSL/HLModule.h, lib/DXIL/DxilMetadataHelper.cpp, lib/DXIL/DxilModule.cpp, lib/DXIL/DxilTypeSystem.cpp, lib/HLSL/HLModule.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp, tools/clang/test/HLSLFileCheck/hlsl/resource_binding/resource-in-struct.hlsl
Currently, ResourceAttribute is only used to capture resource type information during CodeGen for the annotate handle generated during AddOpcodeParamForIntrinsic.
Going through a metadata node is totally unnecessary, just adding code and complexity.
This change just stores the DxilResourceProperties instead, renaming `*ResourceAttribute` methods to `*ResourceProperties`.
This change also emits the resource properties to new field annotaion metadata in validator version 1.8+ to preserve through serialization.
=> Remove ResourceAttribute metadata node from DxilFieldAnnotation

include/dxc/DXIL/DxilModule.h, lib/DXIL/DxilModule.cpp, lib/HLSL/DxilPreparePasses.cpp, tools/clang/test/HLSLFileCheck/hlsl/types/enum/enum6.hlsl, tools/clang/test/HLSLFileCheck/shader_targets/mesh/mesh.hlsl
Types no longer in use, potentially due to type translation, are still kept around just because they are referenced in the type annotation metadata.
This change adds a method DxilModule::RemoveUnusedTypeAnnotations() that removes any type annotations not used by resources or function arguments or return types.  Types outside this set should no longer need any type annotations.  This will get rid of extra unused types often left over in final dxil before.
=> Remove unused type annotations

lib/HLSL/DxilPromoteResourcePasses.cpp, tools/clang/test/HLSLFileCheck/hlsl/resource_binding/resource-in-struct.hlsl
DxilMutateResourceToHandle would skip GEP if result type does not need to be mutated. But then the GEP would not have setSourceElementType called with the new source type leaving invalid IR.
The fix makes sure the GEP is added to MutateValSet when skipping recursion.
=> Fix failing test and DxilMutateResourceToHandle case hit by updated test

tools/clang/lib/CodeGen/CGExprScalar.cpp, tools/clang/test/HLSLFileCheck/hlsl/operators/ternary-return-matrix.hlsl
HLSL ternary operators that result in vector or matrix types need
special handling even if the condition is not a vector. This change
allows vector and matrix result types for ternary operators even if
matrix and vector conditions are not allowed.
Preventing matrix and vector conditions is done in Sema, so we should
never be able to reach this code path with a matrix or vector condition
unless the HLSL language version is < 2021.
Fixes #4434
=> Fix broken ternary on matrix return type (#4434)

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/HLSLFileCheck/hlsl/classes/mismatch_class_implicit_cast.hlsl
In some cases, code using getAsStructureType() seemed to expect any user- defined type to result in RecordType here, but only 'struct' types would, leaving 'class' types to fail certain code paths.  Some code paths had an additional getAs<RecordType>() if the getAsStructureType() returned nullptr, but at that point, why bother with getAsStructureType() in the first place?
This updates cases in CGHLSLMS.cpp that looked to be misusing getAsStructureType to simply use getAs<RecordType>() instead.  One case is with constructing type annotations, where two branches are used and code is almost identical, except skipping size return when a member is a resource was only in the struct path.  I think removing this separate path and checking for resource on any RecordType makes sense here.
Fixes …
=> Change some getAsStructureType() uses to getAs<RecordType>()

tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSL/bitfields-and-annotations.hlsl, tools/clang/unittests/HLSL/VerifierTest.cpp
This change makes mixing bitfields and HLSL annotations an error. Since the syntax for HLSL annotations and bitfields are ambiguous, this change works around some issues with the ambiguity by disallowing mixing the two on the same declaration.
Fixes #4686
=> [HLSL2021] Disallow bitfields and annotations

include/dxc/Support/dxcapi.impl.h
This is the warning threated as error: 
```
/home/vsts/work/1/s/DXC/include/dxc/Support/dxcapi.impl.h:88:11: error: enumeration values 'DXC_OUT_NONE', 'DXC_OUT_EXTRA_OUTPUTS', and 'DXC_OUT_FORCE_DWORD' not handled in switch [-Werror,-Wswitch]
switch (kind) {
^
```
=> Fix build warning in dxcapi.impl.h (Linux build)

cmake/config-ix.cmake
When cross compiling for Android on Windows, GetHostTriple.cmake will end up running Linux shell commands.  This small change lets the user pass in LLVM_INFERRED_HOST_TRIPLE via the cmake command line and bypass the need to invoke the GetHostTriple logic.
With this change I was able to build for Android on Windows using the ninja generator and passing -DLLVM_INFERRED_HOST_TRIPLE=x86_64-pc-win32 to cmake.
=> Allow host to be passed to CMake for cross compile

lib/DxilPIXPasses/DxilDebugInstrumentation.cpp, lib/DxilPIXPasses/DxilPIXMeshShaderOutputInstrumentation.cpp, lib/DxilPIXPasses/DxilShaderAccessTracking.cpp, lib/DxilPIXPasses/PixPassHelpers.cpp, tools/clang/test/HLSLFileCheck/pix/AccessTracking.hlsl, tools/clang/test/HLSLFileCheck/pix/AccessTrackingForSamplerFeedback.hlsl, tools/clang/test/HLSLFileCheck/pix/AddThreadIdToMSPayload.hlsl, tools/clang/test/HLSLFileCheck/pix/DebugBasic.hlsl, tools/clang/test/HLSLFileCheck/pix/DebugFlowControl.hlsl, tools/clang/test/HLSLFileCheck/pix/DynamicResourceAccessTracking.hlsl, tools/clang/test/HLSLFileCheck/pix/DynamicSamplerAccessTracking.hlsl, tools/clang/test/HLSLFileCheck/pix/DynamicSamplerOutOfBounds.hlsl, tools/clang/test/HLSLFileCheck/pix/LibAccessTracking.hlsl, tools/clang/test/HLSLFileCheck/pix/TraceRayInline.hlsl, tools/clang/test/HLSLFileCheck/pix/rawBufferStore.hlsl
Three interconnected things:
-Fix up the access tracking pass to cope with CreateHandleForLib
-Switch to RawBufferStore to match what the PIX engine does on the API side.
-Cope with GetElementPtrOperand as the argument to the load that designates a global for CreateHandleForLib
=> PIX: Access tracking for libs, switch to raw IO

lib/HLSL/DxilContainerReflection.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
Fixed DxilShaderReflection::GetThreadGroupSize returning only thread group size only for CS but not MS and AS.
=> Made shader reflection return thread group size for AS and MS

lib/DxilPIXPasses/DxilShaderAccessTracking.cpp
During a refactor this chunk of code was left inside the for loop over functions, which means that many "DynamicallyIndexedBindPoints" were reported, and PIX just assumed there was one and took the first one. The first one is typically a dx.op and so was quite incorrect.
=> PIX: Fix shader-access-tracking pass' reportage of dynamic indexing

README.md
Windows builds are now done with Visual Studio 2022 rather than 2019; update the link to the builds to reflect that.
Fixes #4746
=> Update Windows build link

tools/clang/unittests/HLSL/ExecutionTest.cpp
IDxcResult needs to be used to get to the disassembled text.
=> IsNormalTest - correct Disassemble arguments

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.h, tools/clang/lib/SPIRV/FeatureManager.cpp, tools/clang/lib/SPIRV/GlPerVertex.cpp, tools/clang/lib/SPIRV/InitListHandler.cpp, tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/lib/SPIRV/NonUniformVisitor.cpp, tools/clang/lib/SPIRV/NonUniformVisitor.h, tools/clang/lib/SPIRV/RawBufferMethods.cpp, tools/clang/lib/SPIRV/RemoveBufferBlockVisitor.cpp, tools/clang/lib/SPIRV/SignaturePackingUtil.cpp, tools/clang/lib/SPIRV/SpirvBasicBlock.cpp, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvContext.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/lib/SPIRV/SpirvType.cpp, tools/clang/lib/SPIRV/StageVar.h
Ideally we can add this as a presubmit, but at least this will allow me to use a code formatter in VS Code without changing large swathes of files
=> [SPIR-V] Run clang-format

lib/DxilPIXPasses/DxilDebugInstrumentation.cpp, lib/DxilPIXPasses/DxilPIXMeshShaderOutputInstrumentation.cpp, lib/DxilPIXPasses/DxilShaderAccessTracking.cpp, tools/clang/test/HLSLFileCheck/pix/AccessTracking.hlsl, tools/clang/test/HLSLFileCheck/pix/AccessTrackingForSamplerFeedback.hlsl, tools/clang/test/HLSLFileCheck/pix/AddThreadIdToMSPayload.hlsl, tools/clang/test/HLSLFileCheck/pix/DebugBasic.hlsl, tools/clang/test/HLSLFileCheck/pix/DebugFlowControl.hlsl, tools/clang/test/HLSLFileCheck/pix/DynamicResourceAccessTracking.hlsl, tools/clang/test/HLSLFileCheck/pix/DynamicSamplerAccessTracking.hlsl, tools/clang/test/HLSLFileCheck/pix/DynamicSamplerOutOfBounds.hlsl, tools/clang/test/HLSLFileCheck/pix/LibAccessTracking.hlsl, tools/clang/test/HLSLFileCheck/pix/TraceRayInline.hlsl, tools/clang/test/HLSLFileCheck/pix/rawBufferStore.hlsl
A recent change switched to RawBufferStore, because it's a raw UAV at the API. Some GPUs' drivers were upset by this form of store. Spent quite some time trying to modify parameters to please the driver, but to no avail. Since it doesn't really matter which store operand is used, I switched back to BufferStore, and now all (known) drivers are happy.
=> PIX: Switch back to non-raw buffer stores

tools/clang/test/HLSLFileCheck/hlsl/objects/RasterizerOrderedBuffer/rovtype.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/modifiers/global/global-var-write-test03.hlsl
Things like -DResType=RasterizerOrderedStructuredBuffer<uint> could be workaround with -DResType="RasterizerOrderedStructuredBuffer<uint>" for lit. But clang-hlsl-tests will not work.
So put the template inside the test.
=> Avoid > in FileCheck run line.

tools/clang/lib/SPIRV/AlignmentSizeCalculator.cpp, tools/clang/lib/SPIRV/AlignmentSizeCalculator.h, tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/lib/SPIRV/LowerTypeVisitor.h
This is some preliminary work to bitfield addition into the SPIR-V backend. This commit should not change the behavior of our backend.
The next steps of the bitfield feature can be seen here : https://github.com/Keenuts/DirectXShaderCompiler/tree/bitfields
(state of this branch not guaranteed, as it's my working branch)
=> bitfields: refactorize struct offset computation

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/test/CodeGenSPIRV/cf.for.short-circuited-cond.hlsl, tools/clang/test/CodeGenSPIRV/cf.while.short-circuited-cond.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
With the introduction of short-circuited operators in HLSL 2021, using them as a loop condition currently results in invalid SPIR-V.
The problem lies in the fact that short-circuited operators introduce control flow. Basically, `a && b` becomes equivalent to `bool result = false; if (a) result = b;`. 
This creates a problem when such a construct is used as a loop condition. When generating the loop in SPIR-V, we take the basic block that performs the condition check and reuse it as a loop header block instead of having a bespoke header block. This shortcut only works when the condition can be expressed in a single basic block, which for short-circuited conditions, it can't.
This fix reworks how we generate loop conditions and headers (both for `for` and `while` loops) when we detect such …
=> [SPIR-V] Handle structured conditions in for and while loops

include/dxc/DXIL/DxilUtil.h, lib/DXIL/DxilUtilDbgInfoAndMisc.cpp
- Added a comment warning  about using MergeGepUse while iterating.
- Changed MergeGepUse to return bool for whether anything actually changed.
- Adding GEP's user to worklist, even when GEP and GEP's source pointer GEP cannot be merged.
=> MergeGepUse improvements

lib/DXIL/DxilUtilDbgInfoAndMisc.cpp
Variable `changed` should be set to true as soon as `MergeGEP` returns a value.
=> Fixed bug where MergeGepUse doesn't return true

CMakeLists.txt, cmake/modules/CoverageReport.cmake, cmake/modules/HandleLLVMOptions.cmake, utils/prepare-code-coverage-artifact.py
This cherry-picks a few changes from upstream LLVM, and has one small DXC-specific change on top.
The goal here is to just bring in the basic code coverage tooling so that we can generate coverage reports. With this PR coverage reports on Unix work, but coverage reports on Windows are still WIP.
Looping in @dnovillo and @bogner since they both worked on LLVM's code coverage infrastructure in past lives 😁
=> Bring in code coverage tooling

include/llvm/CodeGen/MachineInstr.h, include/llvm/MC/MCInstrDesc.h, lib/IR/Instructions.cpp, tools/clang/include/clang/Basic/IdentifierTable.h, tools/clang/lib/AST/Type.cpp, tools/clang/lib/CodeGen/CGExpr.cpp, tools/clang/lib/Lex/PPExpressions.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, utils/TableGen/CodeGenDAGPatterns.cpp, utils/TableGen/SequenceToOffsetTable.h
Fixing some clang warnings about mixing logical and bitwise and the use of one deprecated CPP type (Removed in cpp17, same change as seen in https://github.com/microsoft/DirectXShaderCompiler/pull/4761).
Some are using those bitwise operation to avoid operator laziness. It was fixed upstream by an int cast, applying the same fixes.
=> misc: fix clang warnings: deprecated,bitwise-logic

tools/clang/test/CMakeLists.txt, tools/clang/test/clang-hlsl/lit.cfg
Disable the TAEF lit suite on non-Windows platforms.
=> TAEF Tests only work on Windows

unittests/ADT/ArrayRefTest.cpp
The initializer list goes out of scope after the expression it is used in, so the ArrayRef points to invalid memory. This change keeps the initialization list around so that the array ref remains valid through the test.
=> Fix failing LLVM ArrayRef unit test

tools/clang/lib/SPIRV/SpirvEmitter.cpp
Before this commit, struct field indices were computed from the AST type. This was correct as SPIR-V types and AST types had the same structure.
When adding bitfields, we started to squash some fields together, as long as some rules were respected (bitfield, same type, doesn't span over multiple type-sized words, etc).
This means indices now diverge between SPIR-V types and AST types.
This requires us to lower the AST type before the lowering pass, when generating instructions like OpAccessChain.
A cleaner alternative would be to lower all types before instruction generation, and only operate on SPIR-V type. But cost of making this refactoring is large, and we don't believe it is worth it since we plan to upstream to clang (hence rewrite this code).
note: this code prevents AST indices to …
=> [SPIR-V] get field index from SPIR-V type, not AST

.github/workflows/coverage-gh-pages.yml
This is a first stab at generating a github action to generate code coverage reports.
This is built using GitHub actions because it streamlines publishing to GitHub Pages... hopefully this works.
=> Create action to generate code coverage

utils/hct/hctbuild.cmd
This change adds a new `-clang` flag to hctbuild. It also fixes an issue where ninja builds were getting passed the MSBuild parallelization option.
Note: The clang-cl build does not compile successfully at this time. This change is just a required building block to get there.
=> Add option for building with clang-cl and ninja

CMakeLists.txt, tools/clang/lib/Sema/CMakeLists.txt
I encountered two issues building arm64ec. First CMake and/or link.exe seem to have a disagreement about flag ordering and how to handle `/INCREMENTAL`. This change results in disabling kernel-mode debugging on arm64ec builds, but it means we can build... so that's a win.
The other issue is that libClangSema has some files that have gotten too big, so we need `/bigobj` for Sema.
=> Workarounds for arm64ec build

include/dxc/DxilContainer/DxilRuntimeReflection.h, include/dxc/Test/RDATDumper.h, lib/DxcSupport/dxcapi.use.cpp, lib/DxilDia/DxcPixTypes.cpp, lib/DxilDia/DxcPixVariables.cpp, lib/DxilDia/DxilDiaSymbolManager.cpp, lib/Support/Windows/Program.inc, projects/dxilconv/lib/DxbcConverter/DxbcConverterImpl.h, projects/dxilconv/lib/DxbcConverter/DxbcUtil.h, projects/dxilconv/unittests/DxilConvTests.cpp, tools/clang/tools/dxa/dxa.cpp, tools/clang/tools/dxcompiler/DXCompiler.cpp, tools/clang/tools/dxcompiler/dxclinker.cpp, tools/clang/tools/dxlib-sample/dxlib_sample.cpp, tools/clang/tools/dxrfallbackcompiler/DXCompiler.cpp, tools/clang/tools/dxrfallbackcompiler/dxcdxrfallbackcompiler.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSLTestLib/RDATDumper.cpp, tools/dxexp/dxexp.cpp
MSVC's C++ language implementation deviates from the standard in a number of ways, this patch cleans up several issues that become errors if you build DXC using clang-cl and C++ 17, which has a more strict interpretation of C++.
This change should not have any functional impact.
Specific changes include:
* static_assert(false...) is removed, this is always ill-formed by the C++ standard.
* Under template instantiations implicit `this` is not always allowed.
* Character array `<` comparision is... probably not what was intended.
* Implicit conversions are stricter than MSVC enforces.
* Template base types need explicit type specialization when referred to.
* It is illegal to initialize more than one member of a union.
* Scope nested enums cannot be forward declared.
* Header paths should …
=> Cleanup Windows code to conform to stricter C++ 17 compiler

docs/SPIR-V.rst, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp
-fspv-debug=vulkan will be kept for testing purposes but will not be documented in usage or README (for now).
=> [SPIR-V] Add -fspv-debug=vulkan-with-source to usage and README

.github/workflows/coverage-gh-pages.yml
There were a few things missing in the initial attempt at this workflow. I left off the file extension for the CMake cache file, and also forgot to initialize the submodules.
Additionally using make is... slow. Using make `-j` causes the VM to run out of memory. To resolve those issues I'm installing ninja and using ninja instead. I'm also setting `LLVM_USE_LINKER=lld` to reduce linker memory usage and `LLVM_PARALLEL_LINK_JOBS=1` to only run one link at a time.
I've also added `--rerun-failed` and `--output-on-failure` to the ctest invocation so that if it fails we get some hopefully helpful output.
=> Update GitHub workflow to (hopefully) work

lib/DxilPIXPasses/DxilAnnotateWithVirtualRegister.cpp, lib/DxilPIXPasses/DxilDebugInstrumentation.cpp, lib/DxilPIXPasses/DxilShaderAccessTracking.cpp, lib/DxilPIXPasses/PixPassHelpers.cpp, lib/DxilPIXPasses/PixPassHelpers.h, tools/clang/unittests/HLSL/PixTest.cpp, utils/hct/hctdb.py
This PR does a few things to fix PIX's operation on lib targets:
-Remove the check for "use_empty" on a function. Lib entry functions have no uses! This was done by centralizing the discovery of interesting (to PIX) functions in a new helper in PixPassHelpers.cpp
-In DxilDebugInstrumentation.cpp, remove the early "return" inside runOnModule. There are more functions left to instrument!
-Add reporting from the virtual register pass that reveals the start and end instruction ordinal for interesting functions. PIX can use these values to disambiguate different functions within a module for e.g. shader debugging output.
=> PIX: Fix instrumentation of libraries; instruction numbering reports

azure-pipelines.yml
This updates the ADO yaml to select the latest version of the OS. In the case of MacOS, this will still be 11 for now. For Ubuntu, it will silence the warnings that we are using a deprecated version and save us the headache of having to do this again.
The risk is that a new version of either OS will cause the build to break without our intervention, but the real motivation for explicit versions was an earlier impulse to support the minimal build system that is no longer a priority. As for the risk, I feel it is minimal and we can respond in a timely fashion if it should occur.
=> Update macos/linux builds to *-latest

tools/clang/lib/AST/DeclPrinter.cpp, tools/clang/test/HLSL/rewriter/spirv.hlsl, tools/clang/unittests/HLSL/RewriterTest.cpp
The rewriter emits the internal `namespace vk` in `DeclPrinter` when `-spirv` is specified and `RewriterOpts::RemoveUnusedGlobals` is enabled.
This results in HLSL parse errors because `long` and `extern` are reserved keywords amongst other follow-up errors:
```
input.hlsl:4:33: error: 'long' is a reserved keyword in HLSL
extern T RawBufferLoad(unsigned long long addr);
^
input.hlsl:3:19: warning: default template arguments for a function template are a C++11 extension
template <class T = unsigned int>
^   ~~~~~~~~
input.hlsl:6:1: error: 'extern' is not a valid modifier for a function
extern T RawBufferLoad(unsigned long long addr, unsigned int alignment);
^
```
This PR just quits the `DeclPrinter::VisitNamespaceDecl` visitor when the namespace declaration's name is `"vk"` as this is a …
=> Don't emit built-in 'vk' namespace in DeclPrinter

.github/workflows/coverage-gh-pages.yml
The coverage builds take a _long_ time to run on the standard GitHub action bots. I initially thought cancelling and restarting was a good idea and have since reconsidered...
=> Don't cancel in-progress coverage builds

tools/clang/test/CXX/lit.local.cfg, tools/clang/test/CodeCompletion/lit.local.cfg, tools/clang/test/CodeGenCUDA/lit.local.cfg, tools/clang/test/CodeGenHLSL/lit.local.cfg, tools/clang/test/CodeGenSPIRV/lit.local.cfg, tools/clang/test/Coverage/lit.local.cfg, tools/clang/test/CoverageMapping/lit.local.cfg, tools/clang/test/DXILValidation/lit.local.cfg, tools/clang/test/FixIt/lit.local.cfg, tools/clang/test/Format/lit.local.cfg, tools/clang/test/HLSL/lit.local.cfg, tools/clang/test/HLSLDisabled/lit.local.cfg, tools/clang/test/HLSLFileCheck/lit.local.cfg, tools/clang/test/Headers/lit.local.cfg, tools/clang/test/Index/lit.local.cfg, tools/clang/test/Integration/lit.local.cfg, tools/clang/test/Layout/lit.local.cfg, tools/clang/test/Lexer/lit.local.cfg, tools/clang/test/Misc/lit.local.cfg, tools/clang/test/PCH/lit.local.cfg, tools/clang/test/Parser/lit.local.cfg, tools/clang/test/Preprocessor/lit.local.cfg, tools/clang/test/Profile/lit.local.cfg, tools/clang/test/Sema/lit.local.cfg, tools/clang/test/SemaCUDA/lit.local.cfg, tools/clang/test/SemaCXX/lit.local.cfg, tools/clang/test/SemaTemplate/lit.local.cfg, tools/clang/test/Tooling/lit.local.cfg, tools/clang/test/VFS/lit.local.cfg
This disables all the existing clang lit shell test suites.
Basically all of these suites will fail outright anyways because DXC doesn't function as a C/C++/OpenCL/CUDA compiler anymore. Disabling them gets us one step closer to having a starting point where `check-clang` will pass in the repo, which is a step towards getting `check-all` working.
=> Disable Clang LIT shtest suites

CMakeLists.txt, tools/clang/test/CMakeLists.txt, tools/clang/test/Unit/lit.site.cfg.in, tools/clang/test/taef/lit.cfg, tools/clang/test/taef/lit.site.cfg.in, tools/clang/unittests/CMakeLists.txt, tools/clang/unittests/HLSL/CMakeLists.txt, utils/lit/lit/formats/taef.py
* Setup dependencies for check-clang.
* Proprely adjust shlibdir for multi-configuraiton builds.
* Move TAEF platform verification earlier to avoid issues on Linux.
* Adjust TAEF suite config to handle build_mode specialization.
* Remove another DXC_BUILD_ARCH that snuck in.
* Add the intermediate library path as an rpath for unit tests.
* Make ClangUnitTests depend on ClangHLSLTests so taef tests build.
* Add clang-test-depends and test-depends targets.
=> Tweaks and fixes to clang build and test configs

test/YAMLParser/spec-09-02.test, unittests/Support/MemoryBufferTest.cpp, utils/unittest/googletest/include/gtest/internal/gtest-port.h
This handles a few last Windows fixes for LLVM tests.
* The YAML praser convertes \r to \n, resulting in repeated newlines in YAML tests on Windows.
* The MS filesystem changes on Windows cause one of the MemoryBuffer tests to fail. I've disabled that test on Windows.
* Because we convert many crash cases to exceptions on Windows the GoogleTest DEATH tests fail to die on Windows.
This change addresses the same issue #4794 solves, but restricts the change to Windows only. I'm only merging this since @python3kgae is out and I don't really want to wait until he returns.
utils/unittest/googletest/include/gtest/internal/gtest-port.h
=> Fix or disable last LLVM tests on Windows

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSLFileCheck/hlsl/operators/ternary-enum.hlsl
Note: existing path that limits operator to basic numeric types still allowed enum due to it being AR_TOBJ_BASIC, rather than using a new ArTypeObjectKind. It's questionable whether this was intentional, but changing it would require another special case to allow enums, like exists for object types, and it might have other side effects as well.
Fixes #4826
=> Fix ternary operator for enum result type

include/dxc/DxilContainer/DxilRuntimeReflection.h
This default method implementation is necessary for the base->derived size version mechanism to work. This is only specialized when a base has a derived, and it relies on the newest version to use the default implementation (no specialization).
The implementation was removed in commit 8ee6ed19f3adfe993e91708a24f96efb0f3a00bc.
=> Restore impl of DerivedRecordSize in RDAT

include/dxc/Support/FileIOHelper.h, lib/DxcSupport/FileIOHelper.cpp, projects/dxilconv/tools/dxbc2dxil/dxbc2dxil.cpp, tools/clang/tools/dxclib/dxc.cpp, tools/clang/tools/dxcompiler/dxclibrary.cpp, tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/dxc_batch/dxc_batch.cpp
The exceptions thrown by ReadBinaryFile and WriteBinaryFile give a noticeable performance impact, especially when being called by managed code which automatically tracks and logs exceptions called from native code. The exception logic can be replaced by error code return values. Adding this change greatly improved performance when calling the DXC API directly since exceptions were being thrown and reported all over the place while looking for include files.
=> Replacing fileIO exceptions with error codes

include/dxc/dxcisense.h
- dxcapi.h is in the same directory and the dxc directory does not exist in shipped packages
- WinAdapter.h not needed on Windows
=> Fix dxcisense.h includes

include/dxc/dxcisense.h
- dxcapi.h is in the same directory
- WinAdapter.h not needed on Windows
(cherry picked from commit 12515e884bda1eb35f05d14bd862091373ce5824)
=> Fix dxcisense.h includes (#4852)

tools/clang/lib/Sema/SemaTemplate.cpp, tools/clang/test/HLSLFileCheck/hlsl/template/4771-udt-parameter-validation.hlsl
HLSL built-in templates have some special rules for verifying template type parameters. These break with some common C++ template patterns. This change applies HLSL template argument validation only to HLSL implicit templates.
Fixes #4771
=> [HLSL2021] UDT template parms follow C++ rules

lib/HLSL/DxilContainerReflection.cpp, tools/clang/test/HLSLFileCheck/d3dreflect/lib_global.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/lib_requires_flags.hlsl, tools/clang/unittests/HLSLTestLib/D3DReflectionDumper.cpp
ID3D12FunctionReflection was leaving the `RequiredFeatureFlags` blank, but the information is available.  This change fixes that omission.
Like the equivalent for ID3D12ShaderReflection (see `DxilShaderReflection::GetRequiresFlags`), the flags are the same between the `SHADER_FEATURE_*` flags and `D3D_SHADER_REQUIRES_*` flags, except that `D3D_SHADER_REQUIRES_EARLY_DEPTH_STENCIL` collides with `SHADER_FEATURE_COMPUTE_SHADERS_PLUS_RAW_AND_STRUCTURED_BUFFERS_VIA_SHADER_4_X` not exposed in `RequiredFeatureFlags`.  So, the `D3D_SHADER_REQUIRES_EARLY_DEPTH_STENCIL` flag is patched in based on the flag captured in the shader props (`ShaderProps.PS.EarlyDepthStencil`) for library pixel shader entry points.
Fixes #4715
=> Fill in RequiredFeatureFlags in library function reflection

tools/clang/include/clang/AST/HlslTypes.h, tools/clang/lib/AST/HlslTypes.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/SPIRV/AstTypeProbe.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/HLSL/template-udt-load.hlsl, tools/clang/test/HLSLFileCheck/hlsl/template/ByteAddressBufferLoad.hlsl, tools/clang/test/HLSLFileCheck/shader_targets/raytracing/builtin-ray-types-anyhit.hlsl, tools/clang/test/HLSLFileCheck/shader_targets/raytracing/builtin-ray-types-callable.hlsl, tools/clang/test/HLSLFileCheck/shader_targets/raytracing/builtin-ray-types-miss.hlsl, tools/clang/unittests/HLSL/VerifierTest.cpp
There was an assumtion in the HLSL sema code that a template
specialization could never be a UDT. This assumption is incorrect now.
I've reworked the code so that we instead assume built-in types are
marked as `implicit` (which they all should and seem to be).
Correcting this in `IsHLSLNumericUserDefinedType` resulted in some
breakge in raytracing code generation because we used that method to
deterimine if structures could be payloads or attributes. That was an
incorrect API usage because we do have some builtin types that are
allowed.
The change here does the following:
* Introduce `IsHLSLBuiltinRayAttributeStruct` which returns true for the
builtin raytracing data types that behave like UDTs.
* Introduce `IsHLSLCopyableAnnotatableRecord` returns true for
user-defined trivially copyable …
=> Remove assumption that templates are never UDTs

tools/clang/lib/Sema/TreeTransform.h, tools/clang/test/HLSLFileCheck/hlsl/template/enum-scope-in-template-func.hlsl
While enums were introduced in HLSL 2017, this code should only be reached on HLSL if we are HLSL 2021 or greater, so an additional language version check does not appear necessary here.
=> Fix enum scope used inside template function.

tools/clang/test/HLSLFileCheck/hlsl/template/ByteAddressBufferLoad.hlsl
High-level opcode is not stable, except within a build.  Tests should not take a dependency on these opcode numbers.
Fixed the template/ByteAddressBufferLoad test that was failing due to this dependency.
=> Remove template/ByteAddressBufferLoad test dependency on high-level opcode

include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, include/dxc/Support/dxcapi.impl.h, include/dxc/dxcapi.h, lib/DxcSupport/HLSLOptions.cpp, tools/clang/test/DXC/ftime-report.hlsl, tools/clang/test/HLSLFileCheck/infra/ftime-report.hlsl, tools/clang/test/lit.cfg, tools/clang/tools/dxclib/dxc.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp, utils/hct/hcttestcmds.cmd
This just surfaces and plumbs throug the `-ftime-report` clang flag in
dxc.exe.
`-ftime-report` prints timing data for different parts of the compile
to help identify and track down performance issues. When using the
dxcompiler library interface the output for the time report is returned
as a DXC_OUT_TIME_REPORT buffer.
I've set up the -ftime-report tests to run against the DXC command
line. On Windows this usees the hcttestcmds file, on Linux (and windows
if enabled) this will test through a lit shell suite.
=> Enable -ftime-report flag

include/dxc/DxilContainer/DxilPipelineStateValidation.h, include/llvm/ADT/BitVector.h, lib/DxcSupport/FileIOHelper.cpp, lib/DxilCompression/miniz.c, lib/DxilRootSignature/DxilRootSignatureSerializer.cpp, lib/Support/SmallVector.cpp, lib/Support/regmalloc.cpp, tools/clang/include/clang/AST/OperationKinds.h
Undefined Behavior Sanitizer causes hard failures on runtime conditions that exhibit undefined behavior as defined by C and C++. These issues may not cause immediately identifiable software errors, but the code behavior is dependent on the compiler and runtime implementation. As a result they may become difficult to diagnose or detect errors in the future if the compiler or runtime changes.
This change addresses occurrences of the following undefined behaviors.
* Performing arithmetic operations on null pointers.
* Calling memcpy with a source or destination pointer that is null.
* Calling memset with a destination pointer that is null.
* Assigning an enum a value which is not a valid enum for that enum.
* Reading from unaligned pointers is undefined behavior.
After this change, there are …
=> [NFC] Address some low hanging fruit UBSan failures

lib/IR/ConstantFold.cpp, tools/clang/lib/CodeGen/CGExprScalar.cpp, tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp, tools/clang/test/HLSLFileCheck/hlsl/operators/binary/shift-mask.hlsl, unittests/IR/ConstantsTest.cpp
The HLSL bit shift behavior was implemented in constant folding which alters the semantics of the IR. Alternatively we can implement it in the front end, leveraging the existing OpenCL code paths.
This results in the same final IR optimization and allows reverting the ConstantFolder and IR tests back to match LLVM 3.7.
The HLSL shift behavior's optimized behavior is verified in existing tests like the shift-fold.hlsl test, which is unimpacted by this change.
The big motiviation for this change is heading off subtle bugs. All our tests cover cases where the shift's size is known at compile time. In those cases the compiler can resolve the masking behavior automatically. We have _no_ tests, nor compiler changes that impact shifts that aren't compile-time known.
This means that prior to this …
=> Move HLSL shift behavior to frontend

tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.counter.method.hlsl
Previously, the test spirv.legal.sbuffer.counter.method.hlsl would cause errors if compiled with the DXIL backend:
```
../DirectXShaderCompiler/tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.counter.method.hlsl:72:19: error: cannot map resource to handle.
float value = localBundle.getCSBuffer().Consume();
^
../DirectXShaderCompiler/tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.counter.method.hlsl:87:5: error: cannot map resource to handle.
localWrapper.getASBuffer().Append(4.2);
^
../DirectXShaderCompiler/tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.counter.method.hlsl:72:19: error: local resource not guaranteed to map to unique global resource.
float value = localBundle.getCSBuffer().Consume();
^
../DirectXShaderCompiler/tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.counte …
```
=> [SPIR-V] Fix invalid HLSL in test

include/llvm/Support/raw_ostream.h, tools/clang/test/DXC/show-includes.hlsl, utils/hct/hcttestcmds.cmd
Double buffering a string stream writing in memory is silly. Upstream LLVM made this change a few years ago based on analysis that most string implementations are sane:
https://github.com/llvm/llvm-project/commit/65b1361
=> Unbuffer raw_string_stream

utils/hct/hcttest.cmd
This patch attempts to translate HCTTest options to LIT build targets. Since HCTTest and lit break up tests differently the mapping isn't quite the same, but it should be close enough.
Before we can migrate our automation builds to using lit we need to separate out the exec tests so that they can be disabled on the ADO bots.
=> Add -enable-lit option to hcttest

tools/clang/include/clang/Serialization/ContinuousRangeMap.h
This was found while moving to c++20 by an anonymous internal contributor. Integrating the finding to mainline.
std::unique iterates on elements of the container, and removes all but the first element matching the predicate, but does not resize the container. This means the following code doesn't assert.
```cpp
std::vector<int> v = { 1, 1, 2, 2, 3, 3 };
assert(v.size() == 6);
std::unique(v.begin(), v.end());
assert(v.size() == 6);
```
The function returns a past-end iterator, and all the undefined elements are at the end of the container, meaning we can safely erase them, and fix the container size.
Signed-off-by: Nathan Gauër <brioche@google.com>
=> Fixing a [[nodiscard]] error in DXC

include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, include/dxc/Support/dxcapi.impl.h, include/dxc/dxcapi.h, include/llvm/Support/TimeProfiler.h, include/llvm/Support/raw_ostream.h, lib/Analysis/IPA/CallGraphSCCPass.cpp, lib/DxcSupport/HLSLOptions.cpp, lib/IR/LegacyPassManager.cpp, lib/Support/CMakeLists.txt, lib/Support/TimeProfiler.cpp, tools/clang/include/clang/Driver/Options.td, tools/clang/include/clang/Frontend/CodeGenOptions.def, tools/clang/include/clang/Frontend/FrontendOptions.h, tools/clang/lib/CodeGen/BackendUtil.cpp, tools/clang/lib/CodeGen/CodeGenModule.cpp, tools/clang/lib/Driver/Tools.cpp, tools/clang/lib/Frontend/CompilerInstance.cpp, tools/clang/lib/Frontend/CompilerInvocation.cpp, tools/clang/lib/Parse/ParseAST.cpp, tools/clang/lib/Parse/ParseDeclCXX.cpp, tools/clang/lib/Parse/ParseTemplate.cpp, tools/clang/lib/Sema/Sema.cpp, tools/clang/lib/Sema/SemaTemplateInstantiate.cpp, tools/clang/lib/Sema/SemaTemplateInstantiateDecl.cpp, tools/clang/test/DXC/ftime-trace.hlsl, tools/clang/tools/dxclib/dxc.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp, utils/hct/hcttestcmds.cmd
This change back-ports the -ftime-trace feature implemented by Aras Pranckevičius (@aras-p) into DXC.
Aras has a great blog post describing the motivaiton for this feature and how to use it (see:
https://aras-p.info/blog/2019/01/16/time-trace-timeline-flame-chart-prof iler-for-Clang/).
As shaders are getting more and more complex we need better timing data for ourselves as compiler writers and our users as HLSL writers to know how to improve compile times of complex shaders.
This implementation is a starting point to give us data to help drive our efforts to improve compile-time performance.
Because DXC's LLVM is very far removed from the version of LLVM the patch was originally written for this change is not strictly a cherry-pick of …
=> Backport -ftime-trace from upstream llvm & clang

include/dxc/Test/HlslTestUtils.h
TestConfig.h is not available in HLK test build. This change enables skipping of the include.
=> Include TestConfig.h only if DEFAULT_TEST_DIR is not already defined

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.and.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.or.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.select.hlsl
This enables the `select`, `and`, and `or` intrinsics in older HLSL language modes to ease transitioning to HLSL 2021.
=> Enable 2021 operator intrinsics in older modes

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.and.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.or.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.select.hlsl
This enables the `select`, `and`, and `or` intrinsics in older HLSL language modes to ease transitioning to HLSL 2021.
=> Enable 2021 operator intrinsics in older modes (#4882)

include/dxc/Test/HlslTestUtils.h
TestConfig.h is not available in HLK test build.
The test library uses _HLK_CONF define to distinguish between Exec tests-only and HLK-only code.
=> Do not include TestConfig.h for all HLK build

tools/clang/lib/Frontend/PrintPreprocessedOutput.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
There are some captures that cause problems when preprocessing the extracted source. It appears like some of the source files have already been preprocessed. This change prevents the preprocessor from blowing up when receiving a preprocessed file as input Two tests should be added to test this behavior.
1. Make sure that when the preprocessor receives a preprocessed file, it doesn't blow up.
(this is checked by the new test, PreprocessCheckBuiltinIsOk).
2. Make sure that the preprocessor itself doesn't produce files with the line '#line 1 "<built-in>"' at the top.
(this is already satisfied by PreprocessWhenValidThenOK)
=> add test to handle preprocessing an already preprocessed file.

docs/BuildingAndTestingDXC.rst
This document tries to capture the basics of a unified build and test workflow for all platforms. It is complete enough to start using but not yet ready to be the default build mode.
=> [Docs] Add new docs on unified build workflow

tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
`previousField` was accessing an element from `loweredFields` **after** it has been invalidated through `emplace_back`. This change uses indexed access instead. This _might_ also be related to a segmentation fault mentioned in issue #4727
=> [SPIR-V] Fix dangling pointer to previous field in LowerTypeVisitor

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/HLSLFileCheck/hlsl/functions/arguments/copyin-copyout-operators.hlsl
Previous to this change if we modified arguments for C++ operator calls we were sliding the modified parameters in the argument list relative to where they should have been. This results in mismatched arguments in calls and all sorts of nastiness.
=> Fix argument translation for C++ member operators

lib/DxilDia/DxilDiaSymbolManager.cpp, tools/clang/unittests/HLSL/PixTest.cpp
This has been a long-standing issue for PIX. Certain structs (with e.g., embedded arrays of structs) don't pay attention to their alignment requirements.
=> PIX: Account for alignment when computing member offset

lib/DxilPIXPasses/DxilAnnotateWithVirtualRegister.cpp, tools/clang/unittests/HLSL/PixTest.cpp
llvm::Instruction::printAsOperand is quite slow. The "DxilAnnotateWithVirtualRegister" calls printAsOperand for each instruction in the shader and returns that string to PIX (in order to allow PIX to match Value names to the ordinals that this pass is adding). In shaders with tens of thousands of instructions, the overhead adds up. Previously, I did work in PIX to gather the same information directly from a one-time disassembly of the shader, obviating the need for this per-assembly print.
The resulting speed up is worth a 10x perf improvement in certain PIX UI scenarios with large shaders.
=> PIX: Remove per-instruction disassembly in annotation pass output

lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp, tools/clang/unittests/HLSL/PixTest.cpp
This assert fires (fired!) under many PIX tests. No actual functional change required.
=> PIX: Fix overactive assert in value-to-declare pass

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/HLSLFileCheck/hlsl/types/boolean/bool_codegen_cast_init_list.hlsl
The scenario:
- Empty struct field in MyStruct2 causes init list cast path in CodeGen
- DXASSERT that the value type matches the ConvertType for the bool
- value type is i32 based on field in MyStruct from RecordLayout
- ConvertType for bool is i1, while ConvertTypeForMem will be i32.
The assert should instead check both ConvertType and ConvertTypeForMem.
=> Fix assert when bool field in nested struct during init list casting

tools/clang/include/clang/Basic/DiagnosticGroups.td, tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/lib/CodeGen/CGCleanup.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp, tools/clang/lib/CodeGen/CGHLSLMSHelper.h, tools/clang/lib/CodeGen/CGHLSLRuntime.h, tools/clang/test/HLSLFileCheck/hlsl/control_flow/return/lifetime-markers.hlsl
structurize-returns uses scope-end blocks recorded during codegen to transform the control flow. When "cleanup" blocks are generated (for example for lifetime-markers), structurize-returns as is cannot transform the control flow safely. This change disables structurize-returns and emits a warning when cleanup blocks are detected in the affected function.
=> Turn off structurize-returns when cleanup blocks are present.

tools/clang/tools/dxcompiler/dxcpdbutils.cpp
In the lib case, m_EntryPoint will be non-null but empty, but shouldn't be set anyway. 
(Also, not clearing m_EntryPoint first can result in an assert in CComPtr that the poiner is non-null, and then the pointer is overwritten, resulting in a small memory leak.)
=> PIX: dxcpdbutils: Don't set default entry name in lib case

utils/hct/hcttest.cmd
This parameter was removed when the execution tests were split into a separate dll from clang-hlsl-tests.dll. When the tests are run on the same machine that they were built on this parameter is not needed. However, for ARM64 the tests are running on a different machine and the infrastructure is using hct scripts and HLSL environment variables, so the build machine defaults do not work here.
=> Add HlslDataDir parameter back to execution tests

tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/test/CodeGenSPIRV/op.buffer.access.hlsl, tools/clang/test/CodeGenSPIRV/type.buffer.hlsl, tools/clang/test/CodeGenSPIRV/type.rwbuffer.half.hlsl, tools/clang/test/CodeGenSPIRV/type.rwtexture.hlsl, tools/clang/test/CodeGenSPIRV/type.rwtexture.with.64bit.scalar.hlsl, tools/clang/test/CodeGenSPIRV/type.rwtexture.with.min.precision.scalar.hlsl
This commit aim to fix #4773. In SPIR-V, image type must be specified, and GLSL has the syntax for it. In HLSL, we don't, until #3395. When this attribute is not specified, we decided to guess the type, not using Unknown anymore.
But the type guessing was a bit too optimistic, and thus allowed a 3 component layout to be upgraded to 4 component layout.
Changing the guessing function to either give a close type, or return Unknown, adding the capability on load/store to the variable.
=> spirv: keep image format to unknown if it is.

lib/DxilDia/DxilDiaSymbolManager.cpp, lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp, tools/clang/unittests/HLSL/PixTest.cpp
These fixes were the result of a single shader from a well-known game engine, all of which resulted in mismatched offsets between PIX's offsets-into-fake-allocas and the offsets into aggregates for dbg.value statements.
-Base class sizes weren't being added to derived classes
-Samplers+Resources weren't being given any size at all
-Raygen payloads (referred to by pointer) were triggering an assert
Added a new set of tests for the type system to exercise these.
=> PIX: Educate type system about samplers and resources, base classes

tools/clang/include/clang/Lex/HeaderMap.h, tools/clang/include/clang/Lex/MacroArgs.h, tools/clang/lib/Analysis/BodyFarm.h
Importing fa5113893229876b156d80469b1930adc3221225 from upstream LLVM. This fixes a compilation issue for cpp20.
=> Import "Make headers self-contained." commit.

include/dxc/Support/Global.h, include/dxc/Support/WinAdapter.h, tools/clang/lib/Parse/HLSLRootSignature.cpp
Newest clang makes use of older version a warning, which we get as an error
=> Explicitly use n* version of vsnprintf

.github/workflows/coverage-gh-pages.yml
This job requires repository settings that most forks won't set up.
=> Disable code coverage action on forks

lib/HLSL/DxilValidation.cpp
We would create the dxil runtime reflection object but never free it.
Using a unique_ptr here does the job.
Found by running external tests with appverifier enabled.
=> [bug] Fix memory leak in dxil validator

.github/workflows/pr-description-checker.yml
This action just verifies that PRs contain descriptions. Our policy requires PR descriptions, but we don't have consistent application of the policy. This should help correct that.
=> Add a github action to verify PR descriptions

lib/DxilPIXPasses/DxilDebugInstrumentation.cpp
The previous formulation had a single member variable for several Values which would be used in multiple functions of a lib, which of course means that in all but one of those functions, the Values' creation function was not the right one. Funnily enough, I had got this right in the access-tracking pass but somehow neglected to do it in the debugging pass. (Also need to audit the other passes to make sure I haven't been repeating the mistake.)
=> Pix: Debug instrumentation: Create values per-function

include/dxc/Support/Global.h, include/dxc/Support/WinAdapter.h, tools/clang/lib/Parse/HLSLRootSignature.cpp
Newest clang makes use of older version a warning, which we get as an error
(cherry picked from commit 79efe5342e2ae15e8b9ebcdf5680098bf3204dd8)
=> Explicitly use n* version of vsnprintf (#4957)

utils/hct/hcttest.cmd
`hcttest.cmd file-check` runs the `CompilerTest::ManualFileCheckTest` test which is normally Ignored because it's only there to run a custom manual filecheck path. A prior change removed the /runIgnoredTests argument, breaking the testing mode.  This change just adds it back.
This was broken by PR #4963.
=> Fix hcttest file-check mode with /runIgnoredTests

azure-pipelines.yml
I didn't have this configured correctly to run on failing builds... obviously that is where this is more useful.
=> Update Azure pipelines to report results

lib/Transforms/Scalar/LowerTypePasses.cpp, lib/Transforms/Scalar/Scalar.cpp, tools/clang/test/HLSLFileCheck/passes/dxil/lower_type/vec_array_param.ll, tools/clang/test/HLSLFileCheck/shader_targets/library/vec_array_param.hlsl
To allow vector array parameter for extern functions.
When the parameter used as argument for call.
Just bitcast it to the argument type.
=> Fix lower type crash on vector array parameter.

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
1. The StringRef in the `stringLiterals` in the `SpirvBuilder` can have a
dangling reference causing undefined behaviour.
2. Two symbols can have the same name, so when we sort a vector of symbols by
name, we want to use std::stable_sort to make sure we get deterministic
behaviour.
=> Fix two issues found in our internal build

external/CMakeLists.txt
A careless endif in cmake to enable catching a particular compiler warning introduced an irritating cmake warning. The corrects the mismatched endif
=> Silence cmake endif mismatch warning

lib/Transforms/Scalar/Scalarizer.cpp, tools/clang/test/HLSLFileCheckLit/passes/llvm/scalarizer/shuffle_use_extract_elt.ll
When scalarize shuffle inst which has extract element as the input element, create clone before the shuffle instead of after.
Because later when replace the shuffle, new vector will be inserted before the shuffle. The elt will be after its use if inserted before the shuffle earlier.
=> Fix instruction order issue in scalarizer

tools/clang/unittests/HLSL/CMakeLists.txt
After execution tests moved into their own place, a lot of the libraries and headers that unittests required weren't necessary anymore. This pares those requirements down as far as possible
=> Simplify header/link dependencies for unittests

CMakeLists.txt, include/dxc/dxcapi.h, include/dxc/dxcisense.h
dxcapi.h and dxcisense.h had inconsistent and unhelpful for release
include paths to find WinAdapter.h. By adding the necessary -I flag,
the include can be found without including the paths
Fixes #4918
=> Correct WinAdapter path assumptions in public headers

include/dxc/Support/dxcapi.use.h, lib/DxcSupport/CMakeLists.txt, lib/DxcSupport/HLSLOptions.cpp, lib/DxcSupport/SharedLibAffix.inc, lib/DxcSupport/dxcapi.use.cpp, projects/dxilconv/unittests/DxilConvTests.cpp, tools/clang/tools/dxclib/dxc.cpp, tools/clang/tools/dxcompiler/dxcutil.cpp, tools/clang/tools/dxcompiler/dxillib.cpp, tools/clang/tools/dxopt/dxopt.cpp, tools/clang/tools/dxrfallbackcompiler/dxcutil.cpp, tools/clang/tools/dxrfallbackcompiler/dxillib.cpp, tools/clang/unittests/DxrFallback/test_DxrFallback.cpp, tools/clang/unittests/HLSLExec/ShaderOpTest.cpp
When present in the library search path, linux builds of libdxcompiler.so and the dxc executable should load libdxil.so and use it for validation and signing. However, the code to do that was still searching for dxil.dll even on these platforms. This adds code to search for the right name on the right platforms.
=> Allow libdxcompiler.so and dxc to find libdxil.so

include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/Basic/LangOptions.h, tools/clang/lib/AST/ASTDumper.cpp, tools/clang/test/HLSLFileCheck/hlsl/template/FloatLiteralParameter.hlsl, tools/clang/test/HLSLFileCheck/hlsl/template/IntLiteralParameter.hlsl, tools/clang/test/HLSLFileCheck/infra/ast-dumping.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp
This change reworks how we were filtering top-level implicit decls from the `-ast-dump` output. The change has a couple of key differences, but the behavior of the `-ast-dump` flag remains unchanged.
The differences in this change are:
* By default Decl::dump _will_ dump implicit top-level decls which allows attached debuggers to dump top-level decls.
* Top-level implicit decls are determined by the decl's `Implicit` bit rather than an invalid source location.
* Disabling dumping implicit decls is now a language option, so it can be toggled.
* A new `-ast-dump-implicit` flag is added to dump the AST including implicit top-level decls.
The attached test case verifies that the `-ast-dump` flag does not dump implicit top-level decls, and it is intended to be strict enough that if we add new …
=> Support dumping implicit top-level decls

cmake/modules/AddLLVM.cmake
This is a bit hacky. We don't want to have SO versions but we do want SO names. This makes it a bit wonky since CMake doesn't support this usage.
=> Remove SO version from unix binaries

tools/clang/test/lit.cfg
All clang related commands are disabled.
Once clang is build, we can reenable these commands.
=> Fix hcttest fail caused by cannot find clang.

tools/clang/include/clang/Basic/Attr.td, tools/clang/lib/AST/ASTContextHLSL.cpp, tools/clang/lib/Frontend/ASTConsumers.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/lib/Sema/SemaOverload.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/Buffer/buf_index.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/RWTexture/RWTexture-ast.hlsl, tools/clang/test/HLSLFileCheck/hlsl/operator_overloading/subscript-operator.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/matrix/matrix-ast.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/vector/vector-ast.hlsl
This change should have no functional impact on compilation. The goal is to remove cases where we rely on the subscript operator's name for special resolution rules and instead key the behavior off an attribute on the method declaration.
The added test cases are not exhaustive but try to cover at least one object type exercising each code path modified in this change.
Partially fixes #4340
=> Introduce HLSLCXXOverload attribute

tools/clang/unittests/HLSL/CMakeLists.txt
Reverts microsoft/DirectXShaderCompiler#5009
I came upon this change through experimentation on my own system. I'm not sure why it worked there and in the automated tests, but the headers and libraries involved are used by these tests for the most part, so I'm restoring them here.
=> Revert "Simplify header/link dependencies for unittests"

include/dxc/Support/dxcapi.use.h, tools/clang/unittests/HLSL/DxilContainerTest.cpp
This patch resolves an issue where dxil.so was failing to load but the error status was not being propagated, which caused repeated load attempts and eventually incorrect error propagation in a test case.
A bunch of this code is fairly gnarly, but the general gist is that `dlopen` is not required to set `errno`, so we were returning back success on failure cases unless there happened to be a previous failure value in `errno`.
Resolving this issue should get AppVeyor back on the rails.
There's a related PR that tries to handle the errors correctly (#4713), and we should adopt something similar.
=> Fix AppVeyor Linux tests failing loading dxil.so

tools/clang/unittests/HLSLExec/ExecutionTest.cpp
HLK tests are failing for IsNormal and BarycentricsChecKOrdering.
This fix repairs the IsNormal test. 
The Barycentrics test seems to be a driver problem, since the output of the shader differs at the lowest level, when compared against a different IHV's driver.
=> remove uninitialized assign to an unused variable

include/dxc/Support/WinFunctions.h, lib/DxcSupport/WinFunctions.cpp, tools/clang/tools/libclang/dxcisenseimpl.cpp, tools/clang/unittests/HLSL/DXIsenseTest.cpp
This patch got a bit away from me. It started as me trying to remove one of the Windows system functions we have a custom implementation of (StringCchCopyEx). It didn't really make sense to me that we needed a custom override of a function where we could have just used `strncpy` or other LLVM utilities to provide the functionality.
After I rewrote the code calling `StringCchCopyEx`, I wanted to make sure it was tested, which led me to discover that it was never called in our existing tests (see:
https://microsoft.github.io/DirectXShaderCompiler/coverage/home/runner/w ork/DirectXShaderCompiler/DirectXShaderCompiler/lib/DxcSupport/WinFuncti ons.cpp.html#L27).
I then looked into the behavior of
`clang_getCursorSpellingWithFormatting`, which it turns out _does_ return fully qualified names. …
=> [NFC] Remove custom StringCchCopyEx

include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/test/DXC/diagnostic-verifier.hlsl, tools/clang/tools/dxclib/dxc.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, utils/hct/hcttestcmds.cmd, utils/not/not.cpp
This patch exposes the clang diagnostic verifier out therough the dxc command line interface. This makes it much easier to develop and test diagnostics and will enable us to transition our diagnostic tests into lit tests.
The `-verify` flag for DXC also implies the clang `-fsyntax-only` flag. At some point it may make sense to separate those, but for now this gives the support we currently have in our verifier tests with a smaller change.
=> Add `-verify` flag to DXC

lib/DxilPIXPasses/DxilAnnotateWithVirtualRegister.cpp, tools/clang/test/HLSLFileCheck/pix/AnnotateVirtualRegs-Raygen.hlsl, tools/clang/unittests/HLSL/PixTest.cpp
In some cases structs like the RayDesc built-in type (one of the arguments to TraceRays) will be placed in an alloca. The PIX annotation code wasn't properly counting all the leaf-node values of aggregates within such structs when determining offsets for later members. The result of this was erroneous attribution of writes to those members during PIX shader debugging.
* PIX:Descend Type Hierarchy for Alloca'd structs
* Add test, vectors are scalar-only
* New file-check for metadata nodes
(cherry picked from commit f98f8d6c5993e8191247b3da6d6c68df253c70ed)
=> Cherry-Pick: PIX:Descend Type Hierarchy for Alloca'd structs (#5028)

lib/DxilDia/DxcPixDxilDebugInfo.cpp, tools/clang/unittests/HLSL/PixTest.cpp
(Found while PIX shader debugging raygen, with a breakpoint set in the closest-hit shader)
For a lib, the "entry point" will be null. That's OK. We can look elsewhere.
=> PIX: DxcPixDxilInstructionOffsets should operate on libs

tools/clang/test/CodeGenSPIRV/op.array.access.hlsl, tools/clang/test/CodeGenSPIRV/semantic.viewport-array-index.vs.hlsl, tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.counter.method.hlsl, tools/clang/test/HLSLFileCheck/hlsl/classes/this_cast_to_base_class.hlsl
FileCheck will skip typo lines like CHECK-LABLE.
Fix the typo so we got things tested.
=> [NFC] Fix typo in FileCheck line.

lib/DxcSupport/CMakeLists.txt
It is currently generated into lib\DxcSupport build output directory. Since it is a header, it should go into include/dxc/Support build output directory with other generated .h and .inc files.
=> Generate SharedLibAffix.h into the include directory

tools/clang/lib/CodeGen/CGCall.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/CodeGen/CGHLSLRuntime.h
This code is all unreachable. Reverting this strips out some cascading changes adding an unused parameter to a few functions.
=> Delete some dead/unreachable code in CGCall

tools/clang/include/clang/Basic/Attr.td, tools/clang/include/clang/Basic/DiagnosticGroups.td, tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/lib/Analysis/UninitializedValues.cpp, tools/clang/lib/Sema/AnalysisBasedWarnings.cpp, tools/clang/lib/Sema/SemaDecl.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSL/cxx11-attributes.hlsl, tools/clang/test/HLSL/mintypes-promotion-warnings.hlsl, tools/clang/test/HLSL/more-operators.hlsl, tools/clang/test/HLSL/out-param-diagnostics.hlsl, tools/clang/test/HLSLFileCheck/hlsl/functions/arguments/maybe_unused_out.hlsl, tools/clang/test/HLSLFileCheck/hlsl/functions/arguments/out-param-diagnostics-disabled.hlsl, tools/clang/unittests/HLSL/VerifierTest.cpp
This change adds diagnostic support for uninitialized `out` parameters. With this change, `out` parameters are treated as uninitiailzed values until they are initialized and use of the values produdces a diagnostic.
This change is a slightly hacky extension of Clang's uninitiailzed values analysis which is achieved by adding ParamVarDecls for `out` parameters to the list of variables to analyize. It also adds dummy uses of the variables on `return` statements.
Fixes #4951
=> Add diagnostics for uninitialized `out` parameters

tools/clang/lib/Analysis/UninitializedValues.cpp, tools/clang/lib/Sema/AnalysisBasedWarnings.cpp, tools/clang/test/HLSL/more-operators.hlsl, tools/clang/test/HLSL/out-param-diagnostics.hlsl
The UninitializedValues analysis doesn't correctly handle arrays or pointer objects, so we should not enable `out` parameter analysis for those types. Additionally, because the HLSL ASTs incorrectly represent structure `out` parameters as non-reference types, the analysis will generate incorrect diagnostics for uses of structs in call expressions. There isn't really an easy solution for that. This change takes a conservative approach to addressing those issues by disabling the analysis for values that we can't correctly identify.
This change also disables the "suggest initialization" fix-it for `out` parameters. Default initialization for `out` parameters doesn't work, and would be confusing.
=> Only track scalar `out` params

lib/DxcSupport/CMakeLists.txt, lib/DxcSupport/dxcapi.use.cpp
The file dxcapi.use.cpp is used in other projects and would require build changes if the #include did not change.
=> Change SharedLibAffix.h include path to eliminate the need to change he build setting

tools/clang/lib/Analysis/UninitializedValues.cpp, tools/clang/test/HLSL/out-param-diagnostics.hlsl
Initially the change here was forcing unannotated parameters to be treated as uses (`in` parameters). Instead this changes to not handle them explicitly.
Most `in` parameter uses should produce `LValueToRValue` casts which will be identified as uses through other means, but by removing this special case we can support unannotated AST nodes from generated ASTs through this analysis based on their type and usage alone.
Fixes #5093
=> No special case for unannotated params

utils/hct/ExtractIRForPassTest.py
This script automates some operations to make it easier to write IR tests:
1. Gets the pass list for an HLSL compilation using -Odump
2. Compiles HLSL with -fcgl and outputs to intermediate IR
3. Collects list of passes before the desired pass and adds -hlsl-passes-pause to write correct metadata
4. Invokes dxopt to run passes on -fcgl output and write bitcode result
5. Disassembles bitcode to .ll file for use as a test
6. Inserts RUN line with -hlsl-passes-resume and desired pass
=> Add script to compile to intermediate IR for easier pass test authoring

lib/IR/Value.cpp
This file uses std::current_exception, so it should include <exception>
=> build: add exception header

tools/clang/lib/SPIRV/InitListHandler.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/type.template.function.empty-struct-argument.hlsl
`indexAST` must be in the half-open range [0, N) instead of [0, N]. This caused a crash while I was fixing other issues with empty structs. I will file separate PRs for these fixes.
=> [SPIR-V] Fix composites with empty struct fields.

cmake/modules/AddLLVM.cmake
This pulls in a couple upstream commits by myself and @bogner.
commit 3adaa8cf4a6df45430b47a62c649c7cb54bb1626
Author: Justin Bogner <mail@justinbogner.com>
Date:   Wed Jun 8 22:36:37 2016 +0000
cmake: Simplify add_lit_testsuites
cmake 3.4 introduced LIST_DIRECTORIES to glob recurse, which can be
used to simplify this code greatly.
llvm-svn: 272217
commit 25ef9e34c9de7b1edc327189b78200459337f7e5
Author: Justin Bogner <mail@justinbogner.com>
Date:   Mon Jul 25 18:07:14 2016 +0000
cmake: When adding lit testsuites, ignore Output directories
With in-tree builds we can get Output directories scattered among
our
tests. Recursing into those to find tests doesn't make sense.
Thanks to nlewycky for noticing this!
llvm-svn: 276667
commit a44ef999fb5e9243df9c4459df1b17b66aa3fd23
Author: Chris …
=> Extend add_lit_testsuites to cover more cases

lib/DXIL/DxilMetadataHelper.cpp
To prevent potential out of bounds assignments to the vector in the future, MDVals now uses push_back instead of [] assignment.
=> Fill in MDVals with push_back for maintainability.

tools/clang/lib/SPIRV/GlPerVertex.cpp, tools/clang/lib/SPIRV/GlPerVertex.h, tools/clang/test/CodeGenSPIRV/spirv.interface.ps.inheritance.sv_clipdistance.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
When a semantic was in an inherited class, it was missed and caused issues later down the pipe. This was because we assumed semantic fields would only be present at the top-level struct, ignoring inheritance.
This commit also changes the parameter type from `DeclaratorDecl` to `NamedDecl` as it only requires methods up to `NamedDecl`. Loosening this requirement allowed me to pass a CXXRecordDecl.
=> spirv: fix GL semantic in inherited classes

tools/clang/test/HLSLFileCheck/passes/llvm/instcombine/nosink.hlsl, tools/clang/test/HLSLFileCheck/passes/llvm/instcombine/sink.hlsl
Under HLSL 2021 short circuiting ternary operators result in _very_ different control flow in these tests, so they aren't really portable. Changing these tests to being HV 2018 keeps them working with minimal changes.
=> [NFC] Update tests that depend on 2018 behavior

gcp-pipelines/x86_64-linux-clang.yml, gcp-pipelines/x86_64-windows-msvc.yml
Those files are the required to drive the new GCP pipeline aimed to replace AppVeyor. As-is, those file have no effect on the repo. What's needed to add the CI is to setup some repository permissions, and only then CI will be able to run.
This CI will build x86_64 versions of DXC on both Linux and Windows, run tests, and allow retrieving build artifacts (same as Appveyor).
=> ci: add GCP pipeline files to replace AppVeyor

utils/unittest/googletest/src/gtest-all.cc
This is for enable-lit by default.
gtest got link error for missing dup/dup2/close/creat.
=> Fix build error for deprecated function in UCRT.

utils/hct/hcttest.cmd
This is for enable lit by default.
It fix issue when running single test instead of all test under lit. %TEST_CLANG% will not get update until out of the if.
=> [enable-lit] use !TEST_CLANG! to get updated result.

lib/Transforms/Scalar/Reg2MemHLSL.cpp, tools/clang/test/HLSLFileCheck/passes/hl/mem2reg_hlsl/mem2reg_hlsl.ll, tools/clang/test/HLSLFileCheck/passes/hl/mem2reg_hlsl/mem2reg_loop_crit_edge.ll
A DXIL shader containing a loop, where the `phi` node at the beginning of the loop is re-used outside the loop, does not get translated correctly by this version of reg2mem. Running critical edge splitting beforehand resolves the issue.
Excerpt of example DXIL:
```llvm
; <label>:19                                      ; preds = %43, %13
%20 = phi i32 [ %15, %13 ], [ %36, %43 ]
%21 = phi i32 [ %16, %13 ], [ %37, %43 ]
%22 = phi i32 [ %17, %13 ], [ %38, %43 ]
%23 = phi i32 [ %18, %13 ], [ %39, %43 ]
%24 = bitcast i32 %21 to float
%25 = bitcast i32 1065353216 to float
%26 = fadd fast float %24, %25
%27 = bitcast i32 %22 to float
%28 = bitcast i32 1065353216 to float
%29 = fadd fast float %27, %28
%30 = bitcast i32 %23 to float
%31 = bitcast i32 1065353216 to float
%32 = fadd fast float %30, …
```
=> Require break-critical-edges to run before reg2mem_hlsl

lib/Transforms/Scalar/Reg2MemHLSL.cpp, tools/clang/test/HLSLFileCheck/passes/hl/mem2reg_hlsl/mem2reg_hlsl.ll, tools/clang/test/HLSLFileCheck/passes/hl/mem2reg_hlsl/mem2reg_loop_crit_edge.ll
* Require break-critical-edges to run before reg2mem_hlsl
A DXIL shader containing a loop, where the `phi` node at the beginning of the loop is re-used outside the loop, does not get translated correctly by this version of reg2mem. Running critical edge splitting beforehand resolves the issue.
* Add a test which verifies the fix
(cherry picked from commit 012d48cdd16d659e305f4ab9f9817cbda51f2ca2)
=> Cherry-pick reg2mem_hlsl fix (#5180)

tools/clang/lib/SPIRV/RawBufferMethods.cpp, tools/clang/lib/SPIRV/RawBufferMethods.h, tools/clang/test/CodeGenSPIRV/cf.return.memory-layout.hlsl, tools/clang/test/CodeGenSPIRV/method.byte-address-buffer.load.layout.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
They layout rules for value coming from processTemplatedLoadFromBuffer
are inconsistent, and this is causing problems. This PR changes the
function to return an instruction whose layout rule is Void.
This should remove the inconsistenty.
Fixes #5123
=> Set the layout rule in processTemplatedLoadFromBuffer

lib/DxcSupport/CMakeLists.txt, lib/DxcSupport/dxcapi.use.cpp
- Generate SharedLibAffix.h into the include directory (#5058)
- Change SharedLibAffix.h include path to eliminate the need to change build setting (#5085)
=> Cherry-pick of 2 changes related to SharedLibAffix.h

utils/hct/hcttest.cmd
Also run exec test separately.
This is help to keep existing workflow after switch to lit.
=> [enable-lit] Allow file-check when enable-lit

lib/DxilDia/DxilDiaSession.cpp, tools/clang/unittests/HLSL/PixTest.cpp
These passes have already been run by PIX at this point, and running them twice is both a waste and a source of issues: the annotate-with-virtual-registers pass might thereby change virtual register ordinals, which will cause PIX's view of HLSL variables to degrade as the user steps further into a long function.
=> PIX: Don't run PIX prep passes during variable evaluation (PIX already did that)

lib/Transforms/IPO/GlobalOpt.cpp, test/Transforms/GlobalOpt/alias-used.ll
Patch by Jake VanAdrighem!
Summary:
Fix the way we sort the llvm.used and llvm.compiler.used members.
This bug seems to have been introduced in rL183756 through a set of improper casts to GlobalValue*. In subsequent patches this problem was missed and transformed into a getName call on a ConstantExpr.
Reviewers: silvas
Subscribers: silvas, llvm-commits
Differential Revision: http://reviews.llvm.org/D12851
llvm-svn: 248728
=> [GlobalOpt] Sort members of llvm.used deterministically

include/dxc/dxcapi.h
[doc] Update inline API reference docs for dxcapi.h
Documentation comments are now formatted using Doxygen-style markup.  Although there's no automated processes in place to generate documentation from this markup, aligning around this style allows for comments that are more readable than xmldoc when viewed as text.
=> Update inline API reference docs for dxcapi.h

include/dxc/DxilContainer/DxilPipelineStateValidation.h, tools/clang/unittests/HLSL/DxilContainerTest.cpp
GetViewIDOutputMask and GetInputToOutputTable take an output index to support multiple stream outputs in geometry shaders. Previously, these functions would map the same local pointer to a location for serializing or deserializing the dependency bit vectors. This causes data to overlap and size to be computed based only on the last used stream.
This change fixes this by using an array of pointers for each of these. Then, a new test verifies output for two streams, which fails without this fix.
Fixes #5199
=> PSV0: Fix GS multi stream out ViewID dependency serialization

tools/clang/test/CMakeLists.txt
This enables generation of per-directory test targets in non-IDE generators, and preserves a limited set of targets for IDE generators.
=> Enable generating per-directory lit test targets

tools/opt/CMakeLists.txt, tools/opt/opt.cpp
call hlsl::SetupRegistryPassForHLSL in opt to initialize all HLSL/DXIL passes.
This is for FileCheck test which use opt to test HLSL/DXIL passes.
=> [opt] initialize HLSL passes with SetupRegistryPassForHLSL

include/llvm/Analysis/DxilValueCache.h, lib/Analysis/DxilValueCache.cpp, tools/clang/include/clang/Basic/Version.h
Bugs found during Vulkan SDK 1.3.243 compilation under Fedora 38
- changes meaning of ‘ValueMap’ error
- missing cstdint include
=> Compilation error fixes

tools/clang/test/HLSLFileCheck/hlsl/semantics/sv_viewid/viewid12.hlsl, tools/clang/test/HLSLFileCheck/shader_targets/geometry/multiStreamGS.hlsl, tools/clang/unittests/HLSL/ValidationTest.cpp
PSV0 ViewID dependency data was not filled in correctly for prior releases. This was recently fixed.  This adds dxilver 1.7 requirement to prevent these tests from being run against older vaildator releases, where they will fail validation because the compiler-generated PSV0 won't match the validator's expected PSV0 data.
=> Limit multi-stream GS tests to dxilver 1.7 due to fix in PSV0

lib/DxilDia/DxilDiaSymbolManager.cpp
Additionally, cast uint64_t to unsigned for comparison and for expected var arg based on format string.
=> Fix unused local dwOffsetInBytes in DxilDiaSymbolManager.cpp

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/HLSLFileCheck/passes/hl/sroa_hlsl/single_memcpy_use_with_multiple_defines.ll
When src of memcpy is the only read from src and dst of memcpy is the only write to dst, as long all writes to src are before the memcpy, it is safe to replace dst with src.
=> Support case when memcpy src/dst are only use/def of the src/dst.

tools/clang/include/clang/AST/HlslTypes.h, tools/clang/include/clang/Basic/Attr.td, tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/include/clang/Sema/Sema.h, tools/clang/lib/AST/HlslTypes.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Sema/SemaChecking.cpp, tools/clang/lib/Sema/SemaDecl.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/lib/Sema/SemaStmt.cpp, tools/clang/test/HLSL/globallycoherent-errors.hlsl, tools/clang/test/HLSL/globallycoherent-mismatch.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/glc_merge.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/glc_merge2.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/glc_merge3.hlsl, tools/clang/unittests/HLSL/VerifierTest.cpp
This change moves the `globallycoherent` mismatch diagnostics out of code generation and into semantic analysis. Additionally the diagnostic is enhanced to provide more information in the text about the mismatch, and to fire in source locations more directly attributable to the location of the mismatch.
This change also allows the `globallycoherent` annotation to apply to functions, where it applies to the return type of the function, and mismatches can be diagnosed on assignment of the return value and on the return statements.
Fixes #4537.
=> Enhance `globallycoherent` mismatch diagnostics

tools/clang/test/DXC/embed_dbg.test, tools/clang/test/DXC/fd_zs.test, tools/clang/test/DXC/recompile.test, tools/clang/test/DXC/root_sig.test, tools/clang/test/DXC/strip_dbg.test
Avoid use file -E because ls is more available on Windows.
Use ls -1 %T | not grep "\\.pdb$" instead of not ls -1 %T because not ls *.pdb not work on windows.
=> [lit] Use ls -l instead of file -E

tools/clang/lib/Sema/SemaTemplate.cpp, tools/clang/test/HLSL/function-template-default.hlsl, tools/clang/unittests/HLSL/VerifierTest.cpp
Default parameters for function templates is a C++11 feature. Since HLSL is defined as C++03 using default parameters for function templates produces a language extension warning. There is really no need for the warning since the template syntax is disallowed in HLSL 2018 and earlier and we effectively always support this syntax in 2021.
This change suppresses the warning by treating HLSL as C++11 when diagnosing default template arguments. This changes the warning to a C++98 compatability warning, which is only enabled if explicitly requested.
In the future we should consider making future HLSL language versions based on a more modern C++ to avoid issues like this.
Fixes #5221
=> Allow function template default parameters in HLSL

tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
The args in the PDB and debug DXIL are based `CodeGenOptions::HLSLArgs`. This list was created by copying the raw unprocessed arg list and excluding any args equal to the input file name. When the entry point happens to be the same as the input filename, it would get excluded from this list and the PDB and debug module end up with corrupted arg list where -E has no value or wrong value.
Fixed by only excluding args that are InputClass.
=> Fixed entry point omitted from the PDB when it's the same as input filename

docs/CommandGuide/lit.rst, utils/lit/lit/TestRunner.py, utils/lit/lit/main.py, utils/lit/tests/Inputs/shtest-if-else/lit.cfg, utils/lit/tests/Inputs/shtest-if-else/test-neg1.txt, utils/lit/tests/Inputs/shtest-if-else/test-neg2.txt, utils/lit/tests/Inputs/shtest-if-else/test-neg3.txt, utils/lit/tests/Inputs/shtest-if-else/test-neg4.txt, utils/lit/tests/Inputs/shtest-if-else/test.txt, utils/lit/tests/shtest-if-else.py
Based on
https://github.com/llvm/llvm-project/commit/1041a9642ba035fd2685f925911d705e8edf5bb0
This syntax allows to modify RUN lines based on features
available. For example:
RUN: ... | FileCheck %s --check-prefix=%if windows %{CHECK-W%} %else %{CHECK-NON-W%}
CHECK-W: ...
CHECK-NON-W: ...
This is merged to allow dxilver check apply on each RUN line.
=> [lit] Port Support %if ... %else syntax for RUN lines from upstream

tools/clang/test/CodeGenSPIRV/texture.sample-offset.with.loop-unroll.hlsl
This also required a fix to the unrolling loop, as the SPIRV optimizer has changed upstream.
=> Update SPIRV-Tools submodule.

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.dot.hlsl
When processing the dot intrinsic, there is an assert that ensure the return type is the same as the componentent type of the operands. This is not true when the types were originally half. At that point, the operands will have been promoted to float, but the return type will be promoted later.
Since the assert is not universally true, I will remove it.
Fixes #5048
=> Remove unneeded assert

lib/Analysis/DependenceAnalysis.cpp, lib/Bitcode/Reader/BitcodeReader.cpp, lib/DXIL/DxilCounters.cpp, lib/DXIL/DxilUtilDbgInfoAndMisc.cpp, lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp, lib/DxilRootSignature/DxilRootSignatureSerializer.cpp, lib/HLSL/DxilContainerReflection.cpp, lib/HLSL/DxilValidation.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/AST/Type.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/CodeGen/CGRecordLayoutBuilder.cpp, tools/clang/lib/Frontend/InitHeaderSearch.cpp, tools/clang/lib/Parse/ParseExpr.cpp, tools/clang/lib/SPIRV/DebugTypeVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/RawBufferMethods.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/Sema/SemaCodeComplete.cpp, tools/clang/unittests/SPIRV/FileTestFixture.cpp
GCC generates some warnings when building DXC in a WSL environment. This PR is meant to reduce some of the warnings, mainly targeting unused variables / functions, and fallthroughs in switch statements.
=> Remove some warnings from GCC when building DXC

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/HLSLFileCheck/d3dreflect/bitfield-enum.hlsl
Support bit field on enum type.
Fixes 5257 https://github.com/microsoft/DirectXShaderCompiler/issues/5257
=> [BitField] Fix crash on enum bit field.

tools/clang/test/HLSLFileCheck/hlsl/intrinsics/atomic/atomic.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/atomic/atomic_float.hlsl
HLSL HL Opcodes are unstable so we shouldn't have them in the check lines.
=> [NFC] Remove unstable opcodes from filecheck matches

utils/hct/hcttest.cmd
Replaced all the `if "%var%"==""` with `if [not] defined var`, which is the proper way to determine whether the variable is defined or empty. The other way breaks if statement parsing under various conditions.
This fixes handling of TAEF's `/p:"var=val"` parameter syntax as long as you specify your additional TAEF parameters after a `--` argument break.
=> Fix variable definition checks in hcttest.cmd

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/test/CodeGenSPIRV/sm6.wave-get-lane-count.ps.hlsl, tools/clang/test/CodeGenSPIRV/sm6.wave-get-lane-index.ps.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
We get this validation error, if the pixel shader use WaveGetLaneIndex() or WaveGetLaneCount() functions. 
```
generated SPIR-V is invalid: [VUID-StandaloneSpirv-Flat-04744] Fragment OpEntryPoint operand 4 with Input interfaces with integer or float type must have a Flat decoration for Entry Point id 1.
%SubgroupLocalInvocationId = OpVariable %_ptr_Input_uint Input
```
Cause of the error:  https://github.com/KhronosGroup/SPIRV-Tools/blob/59b4febd819977b440692674f6a862d6d17731b5/source/val/validate_decorations.cpp#L876
Fixes #5014
=> [Spirv] Fix for validation error VUID-StandaloneSpirv-Flat-04744

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/op.vector.swizzle.hlsl
When handling the swizzles in the SPIR-V backen, there is a special case when
the final result returns the original vector. It tries to avoid adding the
vector shuffle instruction in spir-v. However, that path calls `doExpr` instead
of `loadIfGLValue` like the other path. This can sometimes cause a load to be
omitted.
This is changed so that `loadIfGLValue` is called for both cases.
Fixes #5275
=> Fix special case with vector swizzle

utils/update_spirv_deps.sh
As per discussion in
https://github.com/microsoft/DirectXShaderCompiler/pull/5246, the repositories re2 and effcee should not be updated when rolling submodules forward.
=> Prevent update_spirv_deps.sh from updating re2 and effcee.

lib/DXIL/DxilMetadataHelper.cpp, tools/clang/test/HLSLFileCheck/d3dreflect/bitfield-combine-to-unsigned.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/bitfield-enum.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/bitfield_in-structured-buffer.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/bitfield_single_member.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/bitfield_spill-over.hlsl
Only emit bitfield annotation for validator version >= 1.7
This is to avoid validation error on old validator.
=> [Metadata] Limit bitfield annotation to validator version >= 1.7

lib/Support/Unix/Signals.inc
Fixes #5271
backported from https://github.com/llvm-mirror/llvm/commit/fa92ec8e9e59d57a1556ec7b2024de94001485ae
Note that this doesn't touch a similar possible race condition for `UnregisterHandlers()`.
---
Several static functions from the signal API can be invoked simultaneously; RemoveFileOnSignal for instance can be called indirectly by multiple parallel loadModule() invocations, which might lead to the assertion:
Assertion failed: (NumRegisteredSignals < array_lengthof(RegisteredSignalInfo) && "Out of space for signal handlers!"),
function RegisterHandler, file /llvm/lib/Support/Unix/Signals.inc, line 105.
RemoveFileOnSignal calls RegisterHandlers(), which isn't currently mutex protected, leading to the behavior above. This potentially affect a few other users of RegisterHandlers() …
=> Unix: Avoid concurrency hazard in signal handler registration

lib/DxilDia/DxcPixEntrypoints.cpp
Remove scope resolution on call to SetupAndRun. This works on MSVC presumably because of it's former non-conformant two-phase lookup. Clang can be made to emulate this behaviour by enabling
`-fdelayed-template-parsing`, but GCC does not seem to support this flag. It seems easier to just fix the code this way.
=> Fix clang build depending on delayed template parsing

include/llvm/Config/config.h.cmake
Although seemingly unnecessary for CMake builds of DXC, for our GN build, we needed to write a script to replicate the behaviour of CMake's "configure_file". Having an variable expansion with no variable ("${}") made the script more complex. Besides, this looks like a bug.
=> Add missing CMake variable  for configure_file

include/llvm/ADT/iterator.h
When using libc++, the build fails with errors like:
error: incomplete type 'clang::DeclContext::udir_iterator' used in type trait expression
: public integral_constant<bool, __is_base_of(_Bp, _Dp)> {};
^
note: while substituting deduced template arguments into function template 'iterator_adaptor_base' [with U = const llvm::iterator_adaptor_base<clang::DeclContext::udir_iterator, clang::DeclContextLookupResult::iterator, std::random_access_iterator_tag, clang::UsingDirectiveDecl *> &]
class iterator_adaptor_base
This was fixed in upstream LLVM in this CL:
https://github.com/llvm/llvm-project/commit/e78e32a443aaaba63d081faaed7e2cb881424458 (also see original review: https://reviews.llvm.org/D22951#change-zKJSAlLXXy11) Unfortunately, the CL does not explain why this change was made, so I …
=> Fix build when compiling against libc++

include/dxc/DxilPIXPasses/DxilPIXPasses.h, lib/DxilPIXPasses/CMakeLists.txt, lib/DxilPIXPasses/DxilPIXDXRInvocationsLog.cpp, lib/DxilPIXPasses/DxilShaderAccessTracking.cpp, lib/DxilPIXPasses/PixPassHelpers.cpp, tools/clang/test/HLSLFileCheck/pix/LibAccessTracking.hlsl, tools/clang/unittests/HLSL/PixTest.cpp, utils/hct/hctdb.py
This PR adds a new PIX pass that instruments DXR 1.0 shaders (intersection, any/closest hit and miss). The new pass emits each shader invocation's [ray system values](https://microsoft.github.io/DirectX-Specs/d3d/Raytracing.html#system-value-intrinsics) and DispatchRaysIndex into a UAV that can be read back later. This will enable new DXR debugging features in PIX.
=> [PIX] Add pass to log DXR 1.0 shader invocation info into a UAV

tools/clang/lib/SPIRV/AstTypeProbe.cpp, tools/clang/test/CodeGenSPIRV/cast.float1.half1.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Vectors of 1 element are handled as scalars in the spir-v backend
because the element count of [vectors in
spir-v](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpTypeVector)
must be at least 2.
This case is not handled in getTypeWithCustomBitwidth and is causing an
assert. The fix is to add code to explicitly handle vectors of size one.
Fixes #5130
=> Handle size 1 vectors in getTypeWithCustomBitwidth

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/method.rw-byte-address-buffer.atomic.hlsl
The type of the RWByteAddressBuffer is always uint in the SPIR-V
representation. This means that the OpAtomicCompareExchange instruction
must have parameters and a result of type uint. If the original code
used an in for the result, then there is a type mismatch when storing
the value. This is fixed by add a cast when appropriate.
Fixes #4741
=> Add cast after RWByteAddressBuffer atomic compare exchange

tools/clang/test/HLSLFileCheck/d3dreflect/mesh-groupshared.hlsl
Test relies on validator version 1.8, but doesn't specify this version requirement.  Added requirement.
=> Add missing dxilver 1.8 to test.

lib/DxilPIXPasses/DxilDebugInstrumentation.cpp
Recent small regression: the WinPIX shader debug pass should always write to UAV 0 (that's the only one that's correctly setup by WinPIX).
=> WinPIX: Shader debug should use UAV 0 always

include/dxc/DxilPIXPasses/DxilPIXPasses.h, lib/DxilPIXPasses/CMakeLists.txt, lib/DxilPIXPasses/DxilDebugInstrumentation.cpp, lib/DxilPIXPasses/DxilPIXDXRInvocationsLog.cpp, lib/DxilPIXPasses/DxilShaderAccessTracking.cpp, lib/DxilPIXPasses/PixPassHelpers.cpp, tools/clang/test/HLSLFileCheck/pix/InvocationsLog_ClosestHit.hlsl, tools/clang/test/HLSLFileCheck/pix/LibAccessTracking.hlsl, tools/clang/unittests/HLSL/PixTest.cpp, utils/hct/hctdb.py
Recent small regression: the WinPIX shader debug pass should always write to UAV 0 (that's the only one that's correctly setup by WinPIX).
=> Cherry-Pick: WinPIX: Pass to log shader invocations + regression fix (#5301, #5315)

tools/clang/lib/SPIRV/LiteralTypeVisitor.cpp, tools/clang/test/CodeGenSPIRV/select.long.lit.hlsl, tools/clang/test/CodeGenSPIRV/select.short.lit.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
For a BitCast instruction, the bitwidth of the operand must be the same
as the bitwidth of the result type. That requirement is coded into the
LiteralTypeVisitor, so that we do not get validation errors.
Fixes #5319.
=> Propagate bitwidth for BitCast in LiteralTypeVisitor

include/llvm/InitializePasses.h, include/llvm/Transforms/Scalar.h, lib/HLSL/DxilLinker.cpp, lib/HLSL/DxilNoops.cpp, tools/clang/unittests/HLSL/LinkerTest.cpp, utils/hct/hctdb.py
For `-Od`/`-O0` compilations, the compiler generates nop instructions in the form of:
```
@dx.nothing.a = internal constant [1 x i32] zeroinitializer
...
%0 = load i32, i32* getelementptr inbounds ([1 x i32], [1 x i32]* @dx.nothing.a, i32 0, i32 0)
```
This instruction is intended to be a complete no-op, and backends that recognizes this pattern can turn it into proper hardware specific no-op instructions for debug purposes.
When linking DXIL libraries, the passes that run end up removing these nops. This change adds a new pass `DxilReinsertNops` to run at the beginning of linking to read the `LoadInst`s representing nops and turn them back into calls of `dx.noop`, before turning back into loads again at the end.
=> Made linker preserve nops for Od.

include/llvm/ADT/SmallPtrSet.h, lib/Support/SmallPtrSet.cpp
There are a number of changes required to get ReverseIterator support into DXC. Rather than attempting to do it all as one large PR, it makes more sense to break it up into smaller PRs of 2-3 changes.
These first two are just some small refactoring in the SmallPtrSet classes and should not change any behavior.
There was one small change in the DXC codebase that was necessary to bring forward which deviates from the original cherry-pick slightly (will mark it in a comment).
=> [NFC] Cherry-picking some changes to prepare for ReverseIterator support

utils/lit/lit/TestingConfig.py
This is to fix the failure when running hcttest inside docker image.
Upstream PR is in
https://github.com/llvm/llvm-project/commit/9de63b2e051cb3e79645cc20b83b4d33d132cba0
=> [lit] Pass the USERPROFILE variable through on Windows

tools/clang/lib/SPIRV/AlignmentSizeCalculator.cpp, tools/clang/test/CodeGenSPIRV/type.struct.empty-struct.array-stride.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] emit valid stride for array of empty struct

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/bug_report_spirv.md, .github/ISSUE_TEMPLATE/feature_request.md
This change introduces three new issue templates for DXC. The three issue templates are:
* feature_request - Issues filed with this template will get automatically tagged with the `enhancement` label
* bug_report - Issues filed with this template will get automatically get tagged with the `bug` label
* bug_report_spirv - Issues filed with this template will get automatically tagged with the `bug` and `spirv` labels
The bug_report and bug_report_spirv templates are otherwise identical, but could diverge to better meet the needs of the supporting teams.
Fixes #4975.
=> Introduce issue templates

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/class.enum.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
The SPIR-V emitter does not process enum that are declared in class.
This leads to errors in some places it will be used. The fix is to
process the enum in the same place that static variables for an enum are
processed. They are essentially treated like a static variable.
Fixes #5325
=> Process enums in class

tools/clang/lib/SPIRV/LiteralTypeVisitor.cpp, tools/clang/lib/SPIRV/LiteralTypeVisitor.h, tools/clang/test/CodeGenSPIRV/select.long.lit.hlsl2021.hlsl, tools/clang/test/CodeGenSPIRV/select.short.lit.hlsl2021.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
We currently do not do anything to determine the correct type for
variables with a literal type. This leads to type mismatches. In this
commit, I propagate the type the result of the load to the variable that
is loaded. This makes sure that the load is correct.
Fixes #5319
=> Propagate literal types through loads.

CMakeLists.txt, include/llvm/ADT/EpochTracker.h, include/llvm/ADT/ilist_node.h, include/llvm/Config/abi-breaking.h.cmake, include/llvm/Config/config.h.cmake, include/llvm/Config/llvm-config.h.cmake, include/llvm/Support/ErrorHandling.h, lib/Support/ErrorHandling.cpp
The macro LLVM_ENABLE_ABI_BREAKING_CHECKS is moved to a new header abi-breaking.h, from llvm-config.h. Only headers that are using the macro are including this new header.
LLVM will define a symbol, either EnableABIBreakingChecks or DisableABIBreakingChecks depending on the configuration setting for LLVM_ABI_BREAKING_CHECKS.
The abi-breaking.h header will add weak references to these symbols in every clients that includes this header. This should ensure that a mismatch triggers a link failure (or a load time failure for DSO).
On MSVC, the pragma "detect_mismatch" is used instead.
Differential Revision: https://reviews.llvm.org/D26876
llvm-svn: 288082
=> Add link-time detection of LLVM_ABI_BREAKING_CHECKS mismatch

utils/hct/hctbuild.cmd
This is used set a path that lit will use to write out an xml file containing the test results.
I had tried to reuse the existing `-dxc-cmake-extra-args` flag to set the output, but I ran into a lot of problems getting the arg value to parse correctly since it has embedded `=` signs that cmd treats as a command line separator the same as a space (we need to pass a value like `-DLLVM_LIT_ARGS=--xunit-xml-output=log.xml`). No combination of quotes and backslashes could get the arg value passed through correctly, so I opted for the direct route taken in this PR.
=> Add -lit-xml-output-path option to hctbuild.cmd

utils/lit/lit/TestingConfig.py
This is for case where git usr bin is not in winreg.
=> [lit] allow find git usr bin in path directly.

include/llvm/ADT/STLExtras.h, lib/CodeGen/AsmPrinter/ARMException.cpp, unittests/ADT/CMakeLists.txt, unittests/ADT/RangeAdapterTest.cpp
Cherry-picks to get some good changes, specifically in STLExtras
=> Few more cherry-picks to prep for reverse iterator changes

.github/workflows/coverage-gh-pages.yml
I found other users reporting a similar issue:
https://github.com/actions/deploy-pages/issues/188
The root cause seems to be that the deploy-pages action changed to stop correcting permissions problems in the upload since it was slowing down deployment. The recommended fix is to set the permissions before uploading the artifact.
Let's see if this works.
Fixes #5376
=> Update build artifact permissions

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/op.structured-buffer.reconstruct.bitfield.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
HLSL/SPIR-V structs have some layout differences due to bitfields being squashed.
The reconstruction logic was using the AST layout, and not the new SPIR-V layout, meaning we could generate invalid indices during extraction/construction.
This PR fixes a potential bug with bitfields, while making the code reusable.
=> Fix SPIRV struct reconstruction with bitfields

tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/test/CodeGenSPIRV/intrinsics.vkrawbufferload.bitfield.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.vkrawbufferstore.bitfields.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.vkrawbufferstore.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
When the SPV_EXT_physical_storage_buffer extensions is used, vulkan can load raw addresses. For structs loaded through this mecanism, the offsets must be explicit.
This commit fixes decoration emission by attaching the correct layout when a struct is loaded using this extensions.
(Specifying a layout different than void forces explicit offsets).
Fixes #5327
=> [SPIRV] Emit Offset decoration for PhysicalStorage structs

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/test/CodeGenSPIRV/template.static.var.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
There is an assert that checks if a variable will be placed in the
Function or Private storage class in the spir-v. However, the condition
checked in that assert is inconsistent with the part of the code that
determines which storage class a variable belongs to.
The fix is to make the function `isExternalVar` available outside of
SprivEmitter.cpp, and use that in the assert. Now the same check is used
everywhere.
Fixes #5273
=> Make assert consistent with the code

include/dxc/DxilContainer/DxilContainerAssembler.h, lib/DxilContainer/DxilContainerAssembler.cpp, lib/HLSL/DxilValidation.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/tools/dxcompiler/dxcutil.cpp, tools/clang/tools/dxcompiler/dxcutil.h, tools/clang/tools/dxrfallbackcompiler/dxcutil.cpp, tools/clang/unittests/HLSL/DxilContainerTest.cpp
This PR is the first of 2 PRs to prevent libraries of different compiler versions from linking together. This first PR implements adding the compiler version information into the Dxil Container itself, to allow for comparison later. It also adds some basic validation to the new part in the Dxil Container.
=> Error on diff blob versions part 1
