tools/clang/unittests/HLSL/ValidationTest.cpp, utils/hct/hcttest-samples.py
- Fix some validation test issues found during integration
- Undo premature D3D12Warp.dll name change made in hcttest-samples.py
=> Fix validation test issues found during integration

lib/DxcSupport/HLSLOptions.cpp, utils/hct/hcttestcmds.cmd, utils/hct/smoke.hlsl
Modifying "no-warnings" option handling to enable this option expected
=> Fix dxc option to supress warnings.

tools/clang/tools/dxcompiler/dxcontainerbuilder.cpp
- resolving signed/unsigned comparison issue
=> Fix build fail for x86

tools/clang/tools/dxopt/dxopt.cpp
Support both text (.ll) and binary (.bc) inputs on stdin.
=> Allow dxopt.exe to read from stdin

include/dxc/HLSL/DxilShaderModel.h, include/dxc/Support/Global.h, lib/Analysis/CMakeLists.txt, lib/HLSL/CMakeLists.txt, lib/HLSL/WaveSensitivityAnalysis.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp
=> Match filename cases

.gitignore, cmake/modules/FindTAEF.cmake, utils/hct/hctgettaef.py, utils/hct/hctstart.cmd
Also allows the use of the SDK version currently deployed by Visual Studio 2017.
=> Add support for an inline TAEF install rather than requiring WDK

include/dxc/HLSL/DxilResourceBase.h, include/dxc/HLSL/DxilSemantic.h
=> No need to qualify methods with class name in class body

lib/HLSL/HLModule.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp
std::make_unique is a C++14 feature.
=> Use llvm::make_unique instead of std::make_unique

utils/hct/hctbuild.cmd
Defaults to VS2017 if VS2015 isn't available.
Avoids using the VS2015 tools when VS2017 is selected.
=> Updates hctbuild to better handle VS2017

utils/appveyor/appveyor_setup.ps1
No longer necessary to install WDK!
=> Pull taef binaries from blessed location for appveyor builds

docs/SPIR-V.rst
=> Add doc for SPIR-V codegen

utils/appveyor/appveyor_test.ps1
This change makes the test result display properly on the test tab in appveyor.
=> Use Post instead of Put to upload tests

README.md, utils/hct/hctbuild.cmd
=> Fix hctbuild -b -ninja and explain ninja build steps in README.

tools/clang/unittests/HLSL/ShaderOpArithTable.xml
Changing test value of isfinite(NaN) to 0.
=> Fix expected value of isfinite(NaN) to 0.

docs/DXIL.rst, tools/clang/unittests/HLSL/ShaderOpArithTable.xml, utils/hct/hctdb_inst_docs.txt
1. Update expected value of atan(NaN) to NaN
2. Update spec for Fabs for denorm
=> Update execution test for atan and spec for Fabs

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/CodeGenHLSL/Samples/DX11/PNTriangles11_DS.hlsl, tools/clang/test/CodeGenHLSL/mat_param.hlsl, tools/clang/test/CodeGenHLSL/mat_param2.hlsl, tools/clang/test/CodeGenHLSL/mat_param3.hlsl, tools/clang/test/CodeGenHLSL/recursive.ll, tools/clang/test/CodeGenHLSL/resCopy.hlsl, tools/clang/test/CodeGenHLSL/resource_param.hlsl, tools/clang/test/CodeGenHLSL/vector_array_param.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/ValidationTest.cpp
Lower vector/matrix/resource/multi-dim array parameters to
scalars/array/handle/one-dim array.
=> Lower parameter

include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/Basic/LangOptions.h, tools/clang/include/clang/Driver/Options.td, tools/clang/lib/Frontend/CompilerInvocation.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
- Fix detection of invalid options in dxcompilerobj
=> Add HLSL 2017 (-HV 2017) option.

.vs/launch.vs.json, CMakeSettings.json
1. Add  DXC_BUILD_ARCH to find TAEF.
2. Change build root to  hlsl.bin.
3. Add lauch.vs.json to debug  dxc.
=> Fix building with VS 2017 integrated cmake

lib/HLSL/DxilValidation.cpp
- Fixes SV_Position must be float4 #89
- Needs additional testing and comparison of flexibility with fxc.
=> DxilValidation accept more legal component types in signatures

include/dxc/HLSL/DxilContainer.h, include/llvm/ADT/Hashing.h, lib/HLSL/ComputeViewIdState.cpp, lib/HLSL/DxilModule.cpp, tools/clang/tools/dxcompiler/CMakeLists.txt, tools/clang/unittests/HLSL/CMakeLists.txt
Integrate os change e4aba062897e
=> Change to DxilProgramSigSemantic::Barycentrics for runtime alignment

include/dxc/HLSL/DxilConstants.h, lib/HLSL/ComputeViewIdState.cpp, utils/hct/hctdb.py
Note: changed viewid_state to viewid-state for consistency
=> Add NumOpCodes_Dxil_1_1 and ComputeViewIdState pass to hctdb

tools/clang/tools/dxopt/dxopt.cpp, utils/hct/hcttestcmds.cmd
Adds support for external and external-fn arguments.
Adds support for a pf file with the pass configuration.
=> Add support for external libraries to dxopt.

include/dxc/HLSL/DxilPipelineStateValidation.h, include/dxc/HLSL/DxilSignatureAllocator.h, include/dxc/HLSL/DxilSignatureAllocator.inl, include/dxc/HLSL/ViewIDPipelineValidation.inl
- update DxilPipelineStateValidation with MaxVertexCount
- Add option to ignore indexing constraint in DxilSignatureAllocator
- Fix issues with ViewIDPipelineValidation
=> ViewIDPipelineValidation fixes

CMakeLists.txt, lib/HLSL/DxilContainerAssembler.cpp, lib/Transforms/Utils/SimplifyCFG.cpp, tools/clang/unittests/HLSL/ShaderOpTest.h
- Fixed potential null pointer access
- make existence of external directory optional
- add DxilContainerAssembler change missing from ViewID Validation changes
- fix in ShaderOpTest.h for other build tools.
=> Merge integration fixes

appveyor.yml
=> [spirv] Check SPIR-V using Appveyor

include/dxc/HLSL/DxilOperations.h, include/dxc/HLSL/DxilSignature.h, include/dxc/HLSL/DxilTypeSystem.h, lib/HLSL/DxilOperations.cpp, lib/HLSL/DxilSignature.cpp, lib/HLSL/DxilTypeSystem.cpp
Add copy function for DxilSignature and DxilTypeSystem.
Also make OP::RefreshCache() public.
=> Add copy function for DxilSignature and DxilTypeSystem.

cmake/modules/HandleLLVMOptions.cmake, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilOperations.cpp, lib/HLSL/HLMatrixLowerPass.cpp, lib/HLSL/HLOperationLower.cpp
The DBG define was set even for release builds.
=> Fix debug flags for non-debug VS builds

lib/HLSL/DxilModule.cpp, tools/clang/test/CodeGenHLSL/multiUAVLoad5.hlsl, tools/clang/test/CodeGenHLSL/multiUAVLoad6.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
Multi component UAV load check should only be done on Load operation, not Store operations.
=> Check multi component uav on load not store operations.

tools/clang/test/CodeGenHLSL/barycentrics.hlsl
=> Fix barycentrics codegen test

utils/hct/hctdb_instrhelp.py
Fixup the usage in a few functions. No change in generated code.
=> Use the get_db_dxil() function to get the db

lib/HLSL/DxilGenerationPass.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/include/clang/AST/HlslTypes.h, tools/clang/lib/AST/HlslTypes.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Sema/SemaChecking.cpp, tools/clang/lib/Sema/SemaExpr.cpp, tools/clang/test/CodeGenHLSL/resource-array-param.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
=> Add limited support for unbounded resource arrays in parameter list

tools/clang/unittests/HLSL/ExecutionTest.cpp
Right now this test is assuming that QuadReadLaneAt is returning correctly values for all lanes in same quad, which could result in false positive test passes. New test is fixed so that only assumption we make is that WaveReadLaneFirst always returns correct values.
=> WaveIntrinsicsInPS Test Fix

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/CodeGen/CGCall.cpp, tools/clang/test/CodeGenHLSL/lib_arg_flatten.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
=> Support case struct parameter used as function call argument.

tools/clang/tools/dxcompiler/dxcdia.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
This commit adds an implemenation of line number lookup by RVA.
The major changes needed to support this interface are:
1. Add a new map from instruction pointer to RVA in the dia instance
2. Keep an instruction instance in the DxcDiaLineNumber object instead of an index
3. Add support for creating a line number table with a subset of instructions
=> Add dxc dia implementation of `findLinesByRelativeVirtualAddress`

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/include/clang/SPIRV/Structure.h, tools/clang/lib/SPIRV/EmitSPIRVAction.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/Structure.cpp, tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv, tools/clang/test/CodeGenSPIRV/passthru-vs.hlsl2spv, tools/clang/unittests/SPIRV/ModuleBuilderTest.cpp
* Add support for generating stage IO variables
* Add support for interface variable ids in entry point
* Add support for OpReturnValue
=> [spirv] Fully translate pass-through pixel shader!

include/dxc/HLSL/DxilConstants.h, include/dxc/HLSL/DxilShaderModel.h, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilShaderModel.cpp, lib/HLSL/DxilValidation.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/DxcTestUtils.h, tools/clang/unittests/HLSL/DxilModuleTest.cpp, tools/clang/unittests/HLSL/ValidationTest.cpp
Bumping up version to shader model 6.2. This is just a version number change, and actual contents of new shader model are TBD.
=> Update shader model 6.2

tools/clang/include/clang/SPIRV/InstBuilder.h, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/include/clang/SPIRV/Structure.h, tools/clang/include/clang/SPIRV/Type.h, tools/clang/lib/SPIRV/EmitSPIRVAction.cpp, tools/clang/lib/SPIRV/InstBuilderManual.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/Structure.cpp, tools/clang/lib/SPIRV/Type.cpp, tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv, tools/clang/test/CodeGenSPIRV/passthru-vs.hlsl2spv, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp, tools/clang/unittests/SPIRV/StructureTest.cpp, tools/clang/unittests/SPIRV/WholeFileCheck.cpp
* Handled structs as entry point output type
* Handled local variable of struct type
* Replaced the term of "interface variable" with "stage variable"
=> [spirv] Fully translate pass-through vertex shader!

tools/clang/include/clang/SPIRV/InstBuilder.h, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/EmitSPIRVAction.cpp, tools/clang/lib/SPIRV/InstBuilderManual.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/test/CodeGenSPIRV/binary-op.arithmetic.scalar.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
* Covers the following operations: +, -, *, /, %
=> [spirv] Translate arithmetic operations for integers and floats

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/shader-compat-suite/in_out.hlsl, tools/clang/test/CodeGenHLSL/shader-compat-suite/lib_no_flat_extern_func.hlsl
1. Support in out as inout.
2. Support function call on extern functions which don't need to flatten.
=> Minor bug fixes.

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/EmitSPIRVAction.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/test/CodeGenSPIRV/if-stmt.nested.hlsl, tools/clang/test/CodeGenSPIRV/if-stmt.plain.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Support plain and nested if statments now. Complicated cases (like
with early returns and other control flow statements in body) yet
to be covered.
=> [spirv] Translate if statement

include/dxc/HLSL/DxilUtil.h, include/dxc/HLSL/HLModule.h, lib/HLSL/CMakeLists.txt, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/DxilPreparePasses.cpp, lib/HLSL/DxilUtil.cpp, lib/HLSL/DxilValidation.cpp, lib/HLSL/HLMatrixLowerPass.cpp, lib/HLSL/HLModule.cpp, lib/HLSL/HLOperationLower.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp
1. Move DxilEmitMetadata out of DxilGenerationPass.cpp
2. Move helper function out of HLModule.
=> Code cleanup.

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/EmitSPIRVAction.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/test/CodeGenSPIRV/binary-op.comparison.scalar.hlsl, tools/clang/test/CodeGenSPIRV/for-stmt.plain.hlsl, tools/clang/test/CodeGenSPIRV/unary-op.prefix-inc.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
* Only the basic for statement are tested. More complicated cases
yet to be implemented and tested.
* Also add support for less than and prefix increment operator.
=> [spirv] Translate for statement

tools/clang/include/clang/SPIRV/Structure.h, tools/clang/lib/SPIRV/Structure.cpp, tools/clang/unittests/SPIRV/CMakeLists.txt, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp, tools/clang/unittests/SPIRV/InstBuilderTest.cpp, tools/clang/unittests/SPIRV/ModuleBuilderTest.cpp, tools/clang/unittests/SPIRV/SPIRVContextTest.cpp, tools/clang/unittests/SPIRV/SPIRVTestUtils.h, tools/clang/unittests/SPIRV/StructureTest.cpp, tools/clang/unittests/SPIRV/TestMain.cpp, tools/clang/unittests/SPIRV/WholeFileTestFixture.cpp, tools/clang/unittests/SPIRV/WholeFileTestFixture.h
* Changed Instruction to a class
* Created SimpleInstBuilder for building instructions in tests
* Various cosmetic changes
=> [spirv] Improve SPIR-V structures and tests for them

include/dxc/HLSL/DxilContainer.h, tools/clang/tools/dxcompiler/dxcompilerobj.cpp
- also update ShaderFeatureInfoCount and static_assert that the
count matches in disassembler
=> Add new feature info names to disassembler

docs/SPIR-V.rst, tools/clang/lib/SPIRV/EmitSPIRVAction.cpp, tools/clang/test/CodeGenSPIRV/binary-op.arithmetic.mixed.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.arithmetic.vector.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.comparison.mixed.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.comparison.scalar.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.comparison.vector.hlsl, tools/clang/test/CodeGenSPIRV/constant.vector.hlsl, tools/clang/test/CodeGenSPIRV/type.vector.hlsl, tools/clang/test/CodeGenSPIRV/unary-op.prefix-inc.hlsl, tools/clang/test/CodeGenSPIRV/var.init.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
* Translated vector types and operations on vector types
* +, -, *, /, % on vector <op> vector and vector <op> scalar
* Prefix increment on vectors
* < on vector <op> vector and vector <op> scalar
* Covered both constant initializer and variable initializer
* Applied constant modifier to variables
* Covers <, <=, >, >=, ==, != comparison operators
* Also update docs about arithmetic and comparison operators
=> [spirv] Vector types, variable initializers, and comparison

tools/clang/lib/SPIRV/EmitSPIRVAction.cpp, tools/clang/test/CodeGenSPIRV/binary-op.arith-assign.mixed.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.arith-assign.scalar.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.arith-assign.vector.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
=> [spirv] Translate arithmetic assign operators

docs/SPIR-V.rst, tools/clang/include/clang/SPIRV/InstBuilder.h, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/EmitSPIRVAction.cpp, tools/clang/lib/SPIRV/InstBuilderManual.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/test/CodeGenSPIRV/binary-op.bitwise-assign.mixed.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.bitwise-assign.scalar.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.bitwise-assign.vector.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.bitwise.mixed.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.bitwise.scalar.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.bitwise.vector.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
* Covers ~, &, |, ^, <<, >>, &=, |=, ^=, <<=, >>=
* For int/uint and vector of int/uint
=> [spirv] Translate bitwise operators

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/EmitSPIRVAction.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/test/CodeGenSPIRV/binary-op.arith-assign.vector.hlsl, tools/clang/test/CodeGenSPIRV/binary-op.arithmetic.mixed.hlsl, tools/clang/test/CodeGenSPIRV/op.vector.swizzle.hlsl, tools/clang/test/CodeGenSPIRV/op.vector.swizzle.size1.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Most the cases for vector swizzling are handled except:
* Compound assignment used as lhs
=> [spirv] Add support for vector swizzling

tools/clang/lib/SPIRV/EmitSPIRVAction.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.all.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.any.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.asfloat.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.asint.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.asuint.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
The current implementation does not support matrix arguments.
=> [spirv] Intrinsic function all, any, asfloat, asint, and asuint

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h
Previously we parse the string by ourselves.
=> [spirv] Create hlsl::ShaderModel out of shader model string

docs/SPIR-V.rst, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/EmitSPIRVAction.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/for-stmt.nested.hlsl, tools/clang/test/CodeGenSPIRV/while-stmt.nested.hlsl, tools/clang/test/CodeGenSPIRV/while-stmt.plain.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Also added the translation for `loop` and `unroll` attributes.
Similar to for loops, the current implementation does not support
early exits, or early returns.
=> [spirv] Translation of while loops

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/if-stmt.plain.hlsl, tools/clang/test/CodeGenSPIRV/type.typedef.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Also use BinaryOperator methods to test compound assignment and
add tests for typedefs.
=> [spirv] Handle variable definitions in if statements

docs/SPIR-V.rst, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/spirv.storage-class.hlsl, tools/clang/test/CodeGenSPIRV/var.static.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
These variables should be using the Private storage class.
And local static variables should be initialized once.
=> [spirv] Handle static global and local variables

tools/clang/lib/SPIRV/InitListHandler.cpp, tools/clang/lib/SPIRV/InitListHandler.h, tools/clang/test/CodeGenSPIRV/constant.matrix.hlsl, tools/clang/test/CodeGenSPIRV/constant.struct.hlsl, tools/clang/test/CodeGenSPIRV/type.struct.hlsl, tools/clang/test/CodeGenSPIRV/var.init.matrix.1x1.hlsl, tools/clang/test/CodeGenSPIRV/var.init.matrix.1xn.hlsl, tools/clang/test/CodeGenSPIRV/var.init.matrix.mx1.hlsl, tools/clang/test/CodeGenSPIRV/var.init.matrix.mxn.hlsl, tools/clang/test/CodeGenSPIRV/var.init.struct.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Now we can decompose matrices appeared in init lists. Also we can
decompose and construct structs from init lists.
=> [spirv] More support for matrices and structs in init lists

docs/SPIR-V.rst
* Restructured sections
* Explained how HLSL semantics are handled
* Highlighted source code
=> [spirv] Update SPIR-V.rst doc

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/fn.call.hlsl, tools/clang/test/CodeGenSPIRV/fn.param.inout.hlsl, tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv, tools/clang/test/CodeGenSPIRV/passthru-vs.hlsl2spv, tools/clang/test/CodeGenSPIRV/spirv.entry-function.inout.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
We need to write out the values for parameters having out/inout
modifiers.
=> [spirv] Support input modifiers on function parameters

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.cross.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.max.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.min.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.pow.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.reflect.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.step.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
* cross
* min
* max
* pow
* reflect
* step
=> [spirv] Translation of more intrinsic HLSL functions

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/intrinsics.clamp.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Uses SPIR-V Extended Instructions for GLSL.
=> [spirv] Process the clamp intrinsic function

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/InitListHandler.cpp, tools/clang/lib/SPIRV/InitListHandler.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/constant.array.hlsl, tools/clang/test/CodeGenSPIRV/op.array.access.hlsl, tools/clang/test/CodeGenSPIRV/type.array.hlsl, tools/clang/test/CodeGenSPIRV/var.init.array.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
* Supported constant array types
* Supported operator[] on arrays
* Supported initializer list containing arrays
=> [spirv] Add support for constant array type

tools/clang/tools/dxcompiler/dxcdia.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
=> Support findInjectedSource

include/dxc/HLSL/DxilInstructions.h, tools/clang/include/clang/AST/Decl.h, tools/clang/lib/AST/ASTDumper.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSL/ctbuf.hlsl, tools/clang/tools/dxcompiler/dxcdisassembler.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/FileCheckerTest.cpp, utils/hct/hctdb.py
1. Update oprand name for BFI.
2. Dump HLSLBufferDecl info in ASTDumper::dumpDecl.
=> Code cleanup

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/op.cbuffer.access.hlsl, tools/clang/test/CodeGenSPIRV/type.cbuffer.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.explicit.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.implicit.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.register.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.nested.std140.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.std140.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
* Added support for the cbuffer type
* Added support for accessing elements in cbuffer
* Added support for std140 layout rules
=> [spirv] Support cbuffer and layout decorations

tools/clang/test/CodeGenSPIRV/passthru-cs.hlsl2spv, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Using raw buffers (ByteAddressBuffer and RWByteAddressBuffer).
=> [spirv] Add test for passthrough compute shader.

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/op.array.access.hlsl, tools/clang/test/CodeGenSPIRV/op.constant-buffer.access.hlsl, tools/clang/test/CodeGenSPIRV/type.cbuffer.hlsl, tools/clang/test/CodeGenSPIRV/type.constant-buffer.hlsl, tools/clang/test/CodeGenSPIRV/var.init.array.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.explicit.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.implicit.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.register.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Also optimized codgen for consecutive array/struct indexing
expressions to avoid generating multiple OpAccesChains.
=> [spirv] Add support for ConstantBuffer

tools/clang/unittests/HLSL/ExecutionTest.cpp
WaveOps: if FALSE, WaveLaneCountMin=WaveLaneCountMax=0,
WaveOps: if TRUE, WaveLaneCountMin>0
WaveLaneCountMin <= WaveLaneCountMax
=> Execution Test: Wave Intrinsics Caps check

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/ShaderOpArithTable.xml, tools/clang/unittests/HLSL/ShaderOpTest.cpp, tools/clang/unittests/HLSL/ShaderOpTest.h
Since this feature is planned to be supported in future release, the test will fail on current OS versions.
This test case should be tested once there is a driver support for float16 option.
=> Initial implementation for cBuffer test for float16.

tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/op.rwtexture.access.hlsl, tools/clang/test/CodeGenSPIRV/rwtexture.write.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
=> [spirv] Access and assigment for RWTexture types.

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/op.texture.access.hlsl, tools/clang/test/CodeGenSPIRV/op.texture.mips-access.hlsl, tools/clang/test/CodeGenSPIRV/op.texture.sample-access.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.load.hlsl, tools/clang/test/CodeGenSPIRV/texture.load.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
=> [spirv] Texture operator[], .mips[][], .sample[][]

docs/SPIR-V.rst, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/type.scalar.hlsl
=> [spirv] Support other primitive int/float types.

tools/clang/tools/dxl/CMakeLists.txt, tools/clang/tools/dxl/dxl.cpp
=> Print error message when link fail.

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/binary-op.comma.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
=> [spirv] Translation for Comma operator.

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/method.struct.method.hlsl
These functions are just translated into standalone functions
through the normal translation path.
=> [spirv] Support static struct member functions

docs/SPIR-V.rst, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/intrinsics.atan2.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.distance.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.firstbithigh.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.firstbitlow.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.fma.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.fmod.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.frac.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.isfinite.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.isinf.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.isnan.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.refract.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.saturate.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.sincos.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.smoothstep.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.transpose.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Translation for the following intrinsic functions:
* Matrix transpose
* smoothstep
* refract
* distance
* isinf
* isnan
* isfinite
* sincos
* saturate
* atan2
* fma
* fmod
* frac
* firstbithigh
* firstbitlow
=> [spirv] Translation of several intrinsic functions

docs/SPIR-V.rst
=> [spirv] Update doc for ByteAddressBuffer methods.

external/CMakeLists.txt, tools/clang/lib/SPIRV/CMakeLists.txt, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/unittests/SPIRV/FileTestUtils.cpp
When seeing opaque types within structs in function parameter,
function return, and variable definition, invoke SPIRV-Tools
legalization passes.
Also refreshed external projects
=> [spirv] Call SPIR-V legalization passes from SPIRV-Tools

docs/SPIR-V.rst, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/intrinsics.clip.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.countbits.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.frexp.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.ldexp.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.lerp.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.log10.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.mad.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.modf.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.reversebits.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
* frexp
* countbits
* clip
* ldexp
* lerp
* log10
* mad
* modf
* reversebits
=> [spirv] Translate several intrinsic functions.

docs/SPIR-V.rst, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/method.append-structured-buffer.get-dimensions.hlsl, tools/clang/test/CodeGenSPIRV/method.consume-structured-buffer.get-dimensions.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
GetDimensions for AppendStructuredBuffer
GetDimensions for ConsumeStructuredBuffer
=> [spirv] GetDimension for ACSBuffer.

lib/HLSL/HLSignatureLower.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/CodeGenHLSL/MatArrayOutput.hlsl, tools/clang/test/CodeGenHLSL/MatArrayOutput2.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
Also remove sret when flatten functions.
=> Fix row index for array of matrix input/output.

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h
Just refactoring. No logic change.
=> [spirv] Refactoring: create dedicated functions for method calls

docs/SPIR-V.rst, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.ddx-coarse.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.ddx-fine.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.ddx.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.ddy-coarse.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.ddy-fine.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.ddy.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.isfinite.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Also:
* ddx_coarse, ddx_fine
* ddy_coarse, ddy_fine
=> [spirv] Intrinsic ddx and ddy.

lib/HLSL/DxilAddPixelHitInstrumentation.cpp, tools/clang/test/HLSL/pix/pixelCounterAddPixelCost.hlsl
pretty sure this is the last one :-)
=> Another instance of parameters-that-should-have-been-undef

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/bezier.domain.hlsl2spv, tools/clang/test/CodeGenSPIRV/bezier.hull.hlsl2spv, tools/clang/test/CodeGenSPIRV/semantic.domain-location.ds.hlsl, tools/clang/test/CodeGenSPIRV/semantic.inside-tess-factor.ds.hlsl, tools/clang/test/CodeGenSPIRV/semantic.inside-tess-factor.hs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.output-control-point-id.hs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.position.ds.hlsl, tools/clang/test/CodeGenSPIRV/semantic.primitive-id.hs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.tess-factor.ds.hlsl, tools/clang/test/CodeGenSPIRV/semantic.tess-factor.hs.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Added necessary functionality to handle domain shader tranlsation.
Also added Bezier domain shader as test.
Also added Patch decoration to the hull shader patch constant outputs and
the domain shader patch constant inputs.
=> [spirv] Translation of domain shaders.

tools/clang/tools/dxcompiler/dxcdia.cpp
Dia impl. was emitting only the first arg...
Are there any tests that might need updating? hcttest seemed to pass...
=> DIA: Emit all the args

docs/SPIR-V.rst, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/intrinsics.f16tof32.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.f32tof16.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Fixes https://github.com/Microsoft/DirectXShaderCompiler/issues/785
=> [spirv] Add support for f16tof32() and f32tof16()

include/dxc/Support/HLSLOptions.td
Improve dxc help message for target, hlsl version, and enable-16bit-types.
=> Fix dxc help message

cmake/modules/AddLLVM.cmake, include/llvm/Option/OptTable.h, lib/DxcSupport/HLSLOptions.cpp, lib/Option/OptTable.cpp, tools/clang/lib/Basic/CMakeLists.txt, tools/clang/lib/Basic/Version.cpp, tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp, tools/clang/tools/dxc/dxc.cpp, tools/clang/tools/dxcompiler/dxcutil.cpp, tools/clang/unittests/dxc_batch/dxc_batch.cpp
- bump up dll version for fixed version
- show dxcompiler and dxil version number for dxc help message 
- emit warnings for dxcompiler validator that container will not be signed
=> Clean up for versions

lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/HLOperationLower.cpp
Change DXASSERT to DXASSERT_LOCALVAR to suppress unused variable warnings
=> Fix build warnings

include/dxc/HLSL/DxilInstructions.h, utils/hct/hctdb.py
Change rangeID parameter for CreateHandle to const
=> Change rangeID parameter for CreateHandle to const

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/test/CodeGenSPIRV/semantic.on-struct.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
All fields will inherit the semantic attached to the struct, with
index increasing sequentially.
=> [spirv] Add support for semantics on structs

docs/SPIR-V.rst, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/hs.pcf.view-id.1.hlsl, tools/clang/test/CodeGenSPIRV/hs.pcf.view-id.2.hlsl, tools/clang/test/CodeGenSPIRV/semantic.view-id.ds.hlsl, tools/clang/test/CodeGenSPIRV/semantic.view-id.gs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.view-id.hs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.view-id.ps.hlsl, tools/clang/test/CodeGenSPIRV/semantic.view-id.vs.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Also error out on seeing unknown patch constant function parameter.
=> [spirv] Add support for SV_ViewID

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/op.vector.swizzle.const-scalar.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Also support 'literal float' to 'float' conversion.
=> [spirv] Convert floats of different bit widths

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/cast.flat-conversion.implicit.hlsl, tools/clang/test/CodeGenSPIRV/type.scalar.hlsl
Also update the FlatConversion code to handle float and boolean
initializers.
=> [spirv] Handle literal int and 64-bit int.

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/method.buffer.load.hlsl, tools/clang/test/CodeGenSPIRV/method.rwtexture.load.hlsl, tools/clang/test/CodeGenSPIRV/op.buffer.access.hlsl, tools/clang/test/CodeGenSPIRV/op.rwtexture.access.read.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
OpImageRead should return a 4-component vector.
=> [spirv] Fix OpImageRead return type

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp
* Restructured DeclEvalInfo to contain a SpirvEvalInfo
* Refactored various variable creation methods
* Formatted code
=> [spirv] Code refactoring

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/texture.array.sample-bias.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample-cmp.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample-grad.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-bias.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-cmp.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-grad.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample.hlsl
This is a build-up for supporting Status arguments in Sample methods.
=> [spirv] Support Clamp argument in Sample methods.

tools/clang/unittests/HLSL/ExecutionTest.cpp, tools/clang/unittests/HLSL/HlslTestUtils.h, tools/clang/unittests/HLSL/ShaderOpArithTable.xml, utils/hct/hctdb_test.py
Execution tests for Shader Model 6.2 denorm mode
'FAdd', 'FSub', 'FMul', 'FDiv', 'FMad' instructions are used for testings
=> Denorm float tests

tools/clang/tools/dotnetc/EditorForm.Designer.cs, tools/clang/tools/dotnetc/EditorForm.cs, tools/clang/tools/dotnetc/EditorModels.cs
Some perf improvements to colorization.
=> Restore variable width font, !dbg scrolls into view and highlights col.

docs/SPIR-V.rst, tools/clang/include/clang/SPIRV/InstBuilder.h, tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/InstBuilderManual.cpp, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/method.buffer.load.hlsl, tools/clang/test/CodeGenSPIRV/method.rwtexture.load.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.load.hlsl, tools/clang/test/CodeGenSPIRV/texture.load.hlsl
Also updated documentation of all methods with status arg.
=> [spirv] Support Load methods that take Status arg.

lib/Transforms/IPO/PassManagerBuilder.cpp, lib/Transforms/Scalar/Scalarizer.cpp, tools/clang/test/CodeGenHLSL/quick-test/res_select.hlsl, tools/clang/test/HLSL/pix/msaaLoad.hlsl
Also fix scalarizer fail when scattered element is null.
=> Support resource select inside loop.

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/op.matrix.access.mx1.hlsl, tools/clang/test/CodeGenSPIRV/op.matrix.access.mxn.hlsl, tools/clang/test/CodeGenSPIRV/op.struct.access.hlsl, tools/clang/test/CodeGenSPIRV/op.vector.access.hlsl
Also added a method for creating temporary variables.
=> [spirv] Allow indexing into temporary struct

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/var.static.hlsl
Static function variable should be initialized once. We were
emitting if checks to make sure that but got the branch wrongly
flipped.
=> [spirv] Fix static function variable initialization

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/spirv.legal.cbuffer.hlsl, tools/clang/test/CodeGenSPIRV/spirv.legal.tbuffer.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Assigning a ConstantBuffer<T> to a T is indeed a copy.
For addressing #838.
=> [spirv] Fix ConstantBuffer/TextureBuffer assignment

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h
Only the last commit needs review.
=> [spirv] Emit fatal error for failing to find counter variable

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/type.struct.hlsl
Fixes https://github.com/Microsoft/DirectXShaderCompiler/issues/952
=> [spirv] Support embedded struct definition in cbuffer/tbuffer

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/SpirvEvalInfo.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.struct.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
We need to change the type of these struct fields to have an extra
level of pointerness. Also, loads of the pointers should be emitted
appropriately.
=> [spirv] Legalization: support structured/byte buffer in structs

tools/clang/unittests/HLSL/ExecutionTest.cpp
- Fix warnings for implicit type conversions
- Block tests for 6.2 if driver does not support 6.2
=> Clean up Execution Test

README.md
Add information about intel driver support for DXIL and links to driver supporting DXIL
=> Add Intel support info to Hardware support section

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/method.consume-structured-buffer.consume.hlsl, tools/clang/test/CodeGenSPIRV/method.structured-buffer.load.hlsl, tools/clang/test/CodeGenSPIRV/op.array.access.hlsl, tools/clang/test/CodeGenSPIRV/op.rw-structured-buffer.access.hlsl, tools/clang/test/CodeGenSPIRV/op.structured-buffer.access.hlsl, tools/clang/test/CodeGenSPIRV/ternary-op.cond-op.hlsl
Also improved the literal type hints.
=> [spirv] Better handling of ConditionalOperator.

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.counter.struct.hlsl
This commit supports assigning nested structs as a whole.
=> [spirv] Legalization: associated counter in nested structs

tools/clang/lib/Sema/SemaHLSL.cpp
Initializing scalar TypedefDecl for CorrectTypo lookup
=> Fix for CorrectTypo lookup for intrinsics

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/test/CodeGenSPIRV/oo.inheritance.stage-io.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
We need to go over all base classes and handle stage IOs inside
them too.
=> [spirv] Handle OO inheritance in stage IOs

tools/clang/unittests/HLSL/ShaderOpArithTable.xml, utils/hct/hctdb_test.py
=> Fix div denorm ftz

include/dxc/Support/HLSLOptions.h, tools/clang/unittests/HLSL/FileCheckerTest.cpp
=> DxcOpts: init flags, FileCheckerTest: fix error handling for ReadDxcOpts.

lib/Transforms/Scalar/Scalarizer.cpp
Test still to come, but it's not easy and the fix is needed, so it would be good to get this in now.
=> Fix scalarizer for shuffle on vector produced later

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/test/CodeGenSPIRV/cs.groupshared.hlsl, tools/clang/test/CodeGenSPIRV/semantic.dispatch-thread-id.cs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.dispatch-thread-id.uint.cs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.dispatch-thread-id.uint2.cs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.group-id.cs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.group-id.uint.cs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.group-id.uint2.cs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.group-thread-id.cs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.group-thread-id.uint.cs.hlsl, tools/clang/test/CodeGenSPIRV/semantic.group-thread-id.uint2.cs.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Support uint/uint2 for DispatchThreadID
Support uint/uint2 for GroupThreadID
Support uint/uint2 for GroupID
Also updated SPIR-V Tools.
=> [spirv] Update SPIR-V Tools and Fix Builtin usage.

tools/clang/test/CodeGenSPIRV/cast.matrix.splat.hlsl, tools/clang/test/CodeGenSPIRV/cast.vector.splat.hlsl, tools/clang/test/CodeGenSPIRV/cf.if.for.hlsl, tools/clang/test/CodeGenSPIRV/constant.scalar.16bit.disabled.hlsl, tools/clang/test/CodeGenSPIRV/constant.scalar.64bit.hlsl, tools/clang/test/CodeGenSPIRV/constant.scalar.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.D3DCOLORtoUBYTE4.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.log10.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.gather-cmp.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.gather.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample-bias.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample-cmp-level-zero.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample-cmp.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample-grad.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample-level.hlsl, tools/clang/test/CodeGenSPIRV/texture.array.sample.hlsl, tools/clang/test/CodeGenSPIRV/texture.gather-cmp.hlsl, tools/clang/test/CodeGenSPIRV/texture.gather.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-bias.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-cmp-level-zero.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-cmp.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-grad.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample-level.hlsl, tools/clang/test/CodeGenSPIRV/texture.sample.hlsl, tools/clang/test/CodeGenSPIRV/vk.spec-constant.init.hlsl
* Canged to use max_digits10 for float precision
* Fixed bugs regarding OpImageTexelPointer
=> [spirv] Refresh SPIRV-Tools

tools/clang/test/HLSL/include-declarations.h, tools/clang/test/HLSL/include-main.hlsl, tools/clang/tools/dxcompiler/dxcfilesystem.cpp, utils/hct/hcttestcmds.cmd
=> Fix compile shaders with relative path and include files

docs/SPIR-V.rst, include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/SPIRV/EmitSPIRVOptions.h, tools/clang/lib/SPIRV/CMakeLists.txt, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/EmitSPIRVOptions.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/lib/SPIRV/SpirvEvalInfo.h, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.fxc.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.sbuffer.fxc.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
This layout rule can be turned on using -fvk-use-fxc-layout.
=> [spirv] Add support for DX layout rules

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/namespace.functions.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
TODO: Support for global variables in namespaces & resources in namespaces.
=> [spirv] Preliminary support for namespaces.

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/oo.struct.method.hlsl
=> [spirv] Member fn call use Function storage class.

tools/clang/include/clang/SPIRV/FeatureManager.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/FeatureManager.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h, tools/clang/test/CodeGenSPIRV/spirv.stage-io.16bit.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
This feature will require the SPV_KHR_16bit_storage extension.
=> [spirv] Support 16-bit types in stage IO

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/texture.get-dimensions.hlsl
=> [spirv] Allow signed integer args in GetDimensions

lib/HLSL/HLOperationLower.cpp
Improvement towards cross-platform compilation.
=> Use constants from math.h

lib/DxcSupport/LLVMBuild.txt, lib/HLSL/LLVMBuild.txt
Also add missing dependencies for lib/HLSL.
These dependencies only manifest themselves in Debug mode.
=> [linux-port] Define LLVMBuild.txt for DxcSupport.

appveyor.yml
Added header files, *.lib files, and *.pdb files.
cc @chaoticbob
=> [appveyor] Package more build artifacts

appveyor.yml, cmake/modules/FindDiaSDK.cmake, utils/hct/hctbuild.cmd, utils/hct/hctstart.cmd
- change build script to prefer VS2017 
- add cmake 3.11.2 to the list of supported versions
=> Update to VS 2017 and CMake 3.11.2

docs/SPIR-V.rst, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/test/CodeGenSPIRV/vk.layout.attr.offset.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Also update the SPIR-V doc about [[vk::offset]]
=> [spirv] Handle nested structs for [[vk::offset]]

lib/HLSL/DxilLegalizeSampleOffsetPass.cpp, tools/clang/test/CodeGenHLSL/quick-test/sample-offset-imm-test01.hlsl, tools/clang/test/CodeGenHLSL/quick-test/sample-offset-imm-test02.hlsl, tools/clang/test/CodeGenHLSL/quick-test/sample-offset-imm-test03.hlsl, tools/clang/test/CodeGenHLSL/quick-test/sample-offset-imm-test04.hlsl
Scalarize aggregates before loop unroll to enable mem2reg
=> Scalarize aggregates before loop unroll to enable mem2reg

tools/clang/lib/CodeGen/CGExpr.cpp, tools/clang/test/CodeGenHLSL/quick-test/matrix_return_sub2.hlsl
=> Fix crash when get matrix element on a function call.

utils/hct/VerifierHelper.py
Update VerifierTest.py to support py v3
=> Update VerifierTest.py to support py v3

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/quick-test/min10float.hlsl, tools/clang/test/CodeGenHLSL/quick-test/min10float_to_float.hlsl, tools/clang/test/CodeGenHLSL/quick-test/min12int.hlsl, tools/clang/test/CodeGenHLSL/quick-test/min12int_to_int.hlsl
Fix crash issue with min12int and min10float
=> Fix crash issue with min12int and min10float

tools/clang/unittests/HLSL/CMakeLists.txt, tools/clang/unittests/HLSL/TestMain.cpp, tools/clang/unittests/HLSL/VerifierTest.cpp
Enable gtest support and convert path name to ascii for ifstream
=> [linux-port] Enable VerifierTest for Unix

tools/clang/include/clang/SPIRV/ModuleBuilder.h, tools/clang/lib/SPIRV/ModuleBuilder.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
This covers intrinsic functions, intrinsic methods, and user-
defined functions.
=> [spirv] Add OpLine for function calls

docs/SPIR-V.rst, include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/include/clang/SPIRV/EmitSPIRVOptions.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/spirv.opt.cl.oconfig.hlsl, tools/clang/test/CodeGenSPIRV/spirv.opt.invalid-flag.cl.oconfig.hlsl, tools/clang/test/CodeGenSPIRV/spirv.opt.multiple.cl.oconfig.hlsl, tools/clang/test/CodeGenSPIRV/spirv.opt.with-O0.cl.oconfig.hlsl, tools/clang/test/CodeGenSPIRV/spirv.opt.with-O1.cl.oconfig.hlsl, tools/clang/test/CodeGenSPIRV/spirv.opt.with-O2.cl.oconfig.hlsl, tools/clang/test/CodeGenSPIRV/spirv.opt.with-O3.cl.oconfig.hlsl, tools/clang/test/CodeGenSPIRV/spirv.opt.with-O4.cl.oconfig.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp, tools/clang/unittests/SPIRV/FileTestUtils.cpp
Also updated SPIR-V Tools to get the latest API.
=> [spirv] Expose -Oconfig for running custom optimizer recipes

lib/HLSL/HLOperationLower.cpp, tools/clang/lib/CodeGen/CGExprCXX.cpp, tools/clang/test/CodeGenHLSL/quick-test/typedbuf_dblsubstript.hlsl
=> Fix array operator access to a buffer resource vector member

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSL/enums.hlsl
=> Comparison with an enum causes compiler to crash

lib/HLSL/HLOperationLower.cpp, tools/clang/test/CodeGenHLSL/quick-test/matrix_idx_with_expr_test01.hlsl
Fix crash issue with matrices having indices as expressions
=> Fix crash issue with matrices having indices as expressions

tools/clang/lib/CodeGen/CGHLSLMS.cpp
- also don't try to export unused patch constant functions when default
is ExternalLinkage, when function is not compatible with linking.
=> Don't export unused patch constant functions or candidates.

tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.h, tools/clang/test/CodeGenSPIRV/sm6.wave-active-count-bits.hlsl, tools/clang/test/CodeGenSPIRV/sm6.wave-prefix-count-bits.hlsl
Fixed the compilation time regression introduced by loop
unrolling.
=> [spirv] Update SPIRV-Tools to improve compilation time

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/quick-test/bool_cast_initializer_syntax_test.hlsl
Fix bool casting logic when using initializer syntax.
=> Fix bool casting logic when using initializer syntax

lib/HLSL/DxilTypeSystem.cpp
=> Replace usage of strnicmp with _strnicmp as the former is deprecated

tools/clang/unittests/HLSL/ExecutionTest.cpp
Add BasicShaderModel61/63 tests
Fix CBufferTestHalf
=> ExecutionTest update

tools/clang/test/CodeGenSPIRV/attribute.instance.gs.hlsl, tools/clang/test/CodeGenSPIRV/attribute.instance.missing.gs.hlsl, tools/clang/test/CodeGenSPIRV/attribute.max-vertex-count.hlsl, tools/clang/test/CodeGenSPIRV/primitive.line.gs.hlsl, tools/clang/test/CodeGenSPIRV/primitive.lineadj.gs.hlsl, tools/clang/test/CodeGenSPIRV/primitive.point.gs.hlsl, tools/clang/test/CodeGenSPIRV/primitive.triangle.gs.hlsl, tools/clang/test/CodeGenSPIRV/primitive.triangleadj.gs.hlsl
* Removed dangling OpDecorateId
* Stopped scalarizing spec constant sized arrays
=> [spirv] Update SPIRV-Tools for bug fixes

tools/clang/test/CodeGenSPIRV/legal-examples/0-copy-sbuf-ok.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/1-copy-global-static-ok.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/10-if-stmt-select-ok.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/11-if-stmt-const-ok.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/12-switch-stmt-select-fail.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/13-switch-stmt-const-ok.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/14-loop-var-fail.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/15-loop-var-unroll-ok.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/16-loop-var-range-fail.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/17-loop-var-float-fail.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/18-multi-func-call-ok.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/19-multi-func-ret-fail.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/2-write-global-static-ok.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/20-multi-func-ret-const-ok.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/21-combined-ok.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/3-copy-local-struct-ok.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/4-copy-local-nested-struct-ok.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/5-func-param-sbuf-ok.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/6-func-param-rwsbuf-ok.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/7-func-ret-tmp-var-ok.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/8-func-ret-direct-ok.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/9-if-stmt-select-fail.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/README.md, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp, tools/clang/unittests/SPIRV/FileTestFixture.cpp, tools/clang/unittests/SPIRV/FileTestFixture.h, tools/clang/unittests/SPIRV/FileTestUtils.cpp, tools/clang/unittests/SPIRV/FileTestUtils.h
These examples are meant to show what cases are accepted and
what cases are not accepted for HLSL legalization for SPIR-V.
=> [spirv] Add examples for legalization cases

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/quick-test/function-param-typedef-test.hlsl
Resolve typedefs before param annotation.
=> Resolve typedefs before param annotation

tools/clang/include/clang/SPIRV/AstTypeProbe.h, tools/clang/lib/SPIRV/AstTypeProbe.cpp, tools/clang/lib/SPIRV/CMakeLists.txt, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/GlPerVertex.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/lib/SPIRV/TypeTranslator.cpp, tools/clang/lib/SPIRV/TypeTranslator.h
This is just refactoring. No logic change at all.
=> [spirv] Pull certain type probing functions into its own file

lib/Transforms/IPO/PassManagerBuilder.cpp, tools/clang/test/CodeGenHLSL/quick-test/legalize-offset-higher-opts.hlsl
Always try to legalize sample offsets
=> Always try to legalize sample offsets

tools/clang/test/CodeGenSPIRV/legal-examples/12-switch-stmt-select-fail.hlsl, tools/clang/test/CodeGenSPIRV/legal-examples/19-multi-func-ret-fail.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Fixes https://github.com/Microsoft/DirectXShaderCompiler/issues/1598
=> [spirv] Refresh SPIRV-Tools for new validation and bug fixes

lib/HLSL/DxilConvergent.cpp
Propagate convergent operands only once
=> Propagate convergent operands only once

lib/HLSL/HLOperationLower.cpp, tools/clang/test/CodeGenHLSL/quick-test/check-modf.hlsl
=> Fix modf implementation

lib/HLSL/HLOperationLower.cpp, tools/clang/test/CodeGenHLSL/Samples/DX11/ContactHardeningShadows11_VS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/DecalTessellation11_HS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/DecalTessellation11_PS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/DetailTessellation11_PS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/DetailTessellation11_TessVS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/DetailTessellation11_VS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/PNTriangles11_DS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/PNTriangles11_HS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/PNTriangles11_TessVS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/PNTriangles11_VS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/SimpleBezier11DS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/SimpleBezier11PS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/SubD11_BezierEvalDS.hlsl, tools/clang/test/CodeGenHLSL/Samples/DX11/SubD11_SmoothPS.hlsl, tools/clang/test/CodeGenHLSL/quick-test/normalize.hlsl, tools/clang/test/CodeGenHLSL/quick-test/normalize_scalar.hlsl
Change  a / length(a) to a * (rsqrt(dot(a))).
=> Change normalize implementation.

lib/HLSL/HLOperationLower.cpp, tools/clang/test/CodeGenHLSL/quick-test/mat_row_dyn_cb.hlsl
=> Fix dynamic indexed row_major matrix from cbuffer

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/quick-test/subobjects.hlsl, tools/clang/test/HLSL/string.hlsl, tools/clang/test/HLSL/subobjects-syntax.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/VerifierTest.cpp, utils/hct/VerifierHelper.py
+add error on empty root signature value or subobject to export association.
=> Subobject tests

tools/clang/lib/SPIRV/InitListHandler.cpp, tools/clang/lib/SPIRV/InitListHandler.h, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/cast.flat-conversion.vector.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Fixes https://github.com/Microsoft/DirectXShaderCompiler/issues/1673
Fixes https://github.com/Microsoft/DirectXShaderCompiler/issues/1675
Fixes https://github.com/Microsoft/DirectXShaderCompiler/issues/1676
=> [spirv] Add support for casting involving vector decomposition

tools/clang/test/CodeGenHLSL/quick-test/texture_16bittypes.hlsl
This was already working but this test verifies it.
Fixes #739
=> Added a test for gather/load of textures of 16-bit types.

tools/clang/test/CodeGenHLSL/quick-test/disasm_struct_layout_ctbuffer.hlsl, tools/clang/test/CodeGenHLSL/quick-test/disasm_struct_layout_structbuf.hlsl, tools/clang/tools/dxcompiler/dxcdisassembler.cpp
=> Fixed disassembler structured buffer layout output and added tests.

include/dxc/DXIL/DxilConstants.h, lib/HLSL/DxilContainerReflection.cpp
A number of properties were unimplemented. I implemented all those that are related to shader properties, not code complexity.
Fixes #1540
=> Better support for D3D12_SHADER_DESC reflection.

tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/include/clang/Sema/Sema.h, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Sema/SemaDecl.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/CodeGenHLSL/quick-test/bitfields_error.hlsl, tools/clang/test/HLSL/cpp-errors-hv2015.hlsl, tools/clang/test/HLSL/cpp-errors.hlsl, tools/clang/test/HLSL/rewriter/correct_rewrites/cpp-errors_gold.hlsl, tools/clang/test/HLSL/rewriter/cpp-errors_noerr.hlsl
=> Add an error when bitfields are used.

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp
Add ExecutionTest / HLK test entries for testing RawBuffer Load/Store
Modify HLSL for Barycentric test
=> Barycentric test update; Add RawBuffer Load/Store HLK test entries

tools/clang/lib/SPIRV/SPIRVEmitter.cpp
=> [spirv] Fix Linux/macOS build.

lib/Transforms/Utils/LCSSA.cpp, tools/clang/test/CodeGenHLSL/nolcssa-on-struct-type.hlsl
=> Skip inserting redundant phi nodes on struct type

tools/clang/lib/SPIRV/InstBuilderAuto.cpp, tools/clang/lib/SPIRV/SPIRVEmitter.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.allmemorybarrier.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.allmemorybarrierwithgroupsync.hlsl, tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
Update the submodules.  There is no particular commit that is needed, but
it is good to not fall too far behind.
=> [spirv] Update Spriv-tools and Spriv-Headers

lib/CMakeLists.txt, lib/DxilDia/CMakeLists.txt, lib/DxilDia/LLVMBuild.txt, lib/DxilDia/dxcdia.cpp, lib/LLVMBuild.txt, tools/clang/tools/dxcompiler/CMakeLists.txt
Moves Dxil DIA support out of dxcompiler, and into its own library under lib/.
=> moves Dxil DIA support out of dxcompiler

tools/clang/test/CodeGenHLSL/quick-test/implicit_numerical_shape_conversions.hlsl
=> Add a test for implicit conversions between numerical shapes

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Sema/SemaType.cpp, tools/clang/test/CodeGenHLSL/declarations/functions/array_return_type/entrypoint.hlsl, tools/clang/test/CodeGenHLSL/declarations/functions/array_return_type/entrypoint_matrix.hlsl, tools/clang/test/CodeGenHLSL/declarations/functions/array_return_type/entrypoint_vector.hlsl, tools/clang/test/CodeGenHLSL/declarations/functions/array_return_type/non_entrypoint.hlsl
This was suspiciously easy, I can't believe it just worked. Any suggestions for further testing are welcome.
Fixes #1808
=> Add support for returning arrays from functions

lib/HLSL/HLMatrixLowerPass.cpp, tools/clang/lib/CodeGen/CGExprScalar.cpp, tools/clang/test/CodeGenHLSL/expressions/operators/matrices/increment_decrement_locals.hlsl, tools/clang/test/CodeGenHLSL/expressions/operators/matrices/increment_decrement_structbuf.hlsl, tools/clang/test/CodeGenHLSL/expressions/operators/matrices/pre_increment_decrement_chain.hlsl
=> Fix matrix pre/post increment/decrement

tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/unittests/SPIRV/CMakeLists.txt, tools/clang/unittests/SPIRV/SpirvConstantTest.cpp, tools/clang/unittests/SPIRV/SpirvContextTest.cpp, tools/clang/unittests/SPIRV/SpirvTestBase.h, tools/clang/unittests/SPIRV/SpirvTypeTest.cpp
=> [spirv] Refactor and add more unit tests

tools/clang/tools/libclang/dxcrewriteunused.cpp
1. Constant buffer globals could get removed, causing the layout of the implicit constant buffer to change.
2. For cases like `static struct { int x; } s;` (which happen in some commercial shaders), we would be left with `struct { int x; };` at the global scope, which is illegal. This change cleans up anonymous records if we remove their last declared variable.
There's no testing infrastructure for this and I'm unconvinced it's worth adding.
Fixes #1907
=> Fix two issues with DXR -remove-unused-globals

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvFunction.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/include/clang/SPIRV/SpirvType.h, tools/clang/lib/SPIRV/CMakeLists.txt, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/GlPerVertex.cpp, tools/clang/lib/SPIRV/GlPerVertex.h, tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/lib/SPIRV/PreciseVisitor.cpp, tools/clang/lib/SPIRV/PreciseVisitor.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvFunction.cpp, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/lib/SPIRV/SpirvType.cpp, tools/clang/test/CodeGenSPIRV/decoration.no-contraction.hlsl, tools/clang/test/CodeGenSPIRV/decoration.no-contraction.stage-vars.hlsl, tools/clang/test/CodeGenSPIRV/decoration.no-contraction.struct.hlsl, tools/clang/test/CodeGenSPIRV/decoration.no-contraction.variable-reuse.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp, tools/clang/unittests/SPIRV/SpirvTypeTest.cpp
=>  [spirv] Support HLSL 'precise' keyword

lib/DxilPIXPasses/DxilPIXVirtualRegisters.cpp
The bug was caused by adding an LocalAsMetadata to an MDNode, which
is not allowed. This would happen whenever a shader would have
indirect access.
=> Fix the pix-alloca-reg-write metadata.

lib/DxilDia/DxilDiaSymbolManager.cpp
In the general case, bit_pieces might be only for part of a register or register range. For example a half in a VGPR or a SGPRx4 for which we only have debug info for the first register.
=> Remove DXIL Dia assert making assumptions about dwarf bit pieces.

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
This is trivial and specific enough that I think a test is not worth it.
=> Fixed a null DIExpression which survived in the matrix return case.

tools/clang/test/CodeGenSPIRV/vk.binding.register.space-only.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
The real test file was never running :(
=> [spirv] Fix wrong test file name.

lib/DxilDia/DxilDiaTableSymbols.cpp
`StringCompareOrdinal` lives in `kernel32.dll`, better than previous implementations which pulled functions from `user32.dll` or `shlwapi.dll`.
=> Remove shell dll dependency due to string functions.

tools/clang/include/clang/AST/HlslTypes.h, tools/clang/lib/AST/HlslTypes.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSL/conversions-non-numeric-aggregates.hlsl, tools/clang/unittests/HLSL/VerifierTest.cpp
=> Fix a crash converting between numerical and non-numerical types.

lib/HLSL/HLOperationLower.cpp, tools/clang/test/CodeGenHLSL/batch/expressions/intrinsics/unsupported_error.hlsl
=> Error instead of crash on unsupported intrinsic.

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp, tools/clang/unittests/SPIRV/FileTestFixture.cpp, tools/clang/unittests/SPIRV/FileTestFixture.h, tools/clang/unittests/SPIRV/FileTestUtils.cpp, tools/clang/unittests/SPIRV/FileTestUtils.h, tools/clang/unittests/SPIRV/WholeFileTestFixture.cpp
=> [spirv] --relax-logical-pointer to --before-hlsl-legalization

tools/clang/include/clang/SPIRV/SpirvInstruction.h
Renamed old PR #2218 
@ehsannas for review
=> [spirv] Remove unused enum ContextUsageKind from SpirvInstruction.

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.saturate.hlsl
=> [spirv] fix vector size 1 argument bug of seturate()

docs/SPIR-V.rst, tools/clang/include/clang/SPIRV/FeatureManager.h, tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/FeatureManager.cpp, tools/clang/test/CodeGenSPIRV/vk.shading-rate.hlsl, tools/clang/test/CodeGenSPIRV/vk.shading-rate.vs-error.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] Add support for SV_ShadingRate as a PS input

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/cast.vector.splat.hlsl
=> [spirv] fix vector splat cast bug

tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.check-access-fully-mapped.without-sampler.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] fix CheckAccessFullyMapped without sampler

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/oo.struct.this.alias.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] handle this param alias case

lib/HLSL/DxilContainerReflection.cpp, tools/clang/test/CodeGenHLSL/batch/misc/d3dreflect/structured_buffer_layout.hlsl
=> Fix StructuredBuffer field offsets in reflection

lib/HLSL/DxilValidation.cpp, tools/clang/test/CodeGenHLSL/batch/validation/array1.hlsl
=> Fix validation error when element size for array of struct is not aligned

tools/clang/lib/CodeGen/CGHLSLMS.cpp
`CGMSHLSLRuntime::EmitHLSLAggregateCopy` tends to generate a lot of `getelementptr %ptr, 0`, which is a no-op and decreases the signal-to-noise ratio when investigating codegen issues. We can easily avoid this.
=> Avoid generating nop geps in CGMSHLSLRuntime::EmitHLSLAggregateCopy

README.md
=> Update README.md to reflect python3 requirement

cmake/modules/AddLLVM.cmake
=> fix typo to resolve issue #2320

include/dxc/DXIL/DxilConstants.h, tools/clang/lib/AST/ASTContextHLSL.cpp, tools/clang/test/CodeGenHLSL/batch/shader_stages/raytracing/rayquery/tracerayinline.hlsl, tools/clang/test/CodeGenHLSL/batch/shader_stages/raytracing/raytracing_builtin.hlsl, tools/clang/test/CodeGenHLSL/batch/shader_stages/raytracing/subobjects_raytracingPipelineConfig1.hlsl, tools/clang/tools/dxcompiler/dxcdisassembler.cpp
Added missing DXR 1.1 flags support + tests
=> added missing DXR 1.1 flags

lib/HLSL/HLOperationLower.cpp, tools/clang/test/CodeGenHLSL/batch/expressions/operators/vectors/buf_index.hlsl, tools/clang/test/CodeGenHLSL/batch/expressions/operators/vectors/buf_index_nonuniform_index.hlsl
Also support dynamic indexing on buffer load vector.
=> Only add nonuniform on resource ptr.

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/include/clang/SPIRV/SpirvModule.h, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.h, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/lib/SPIRV/SpirvModule.cpp, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.branch.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.composite.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.entry.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.function.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.include-file-1.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.include-file-2.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.include-file-3.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.include.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.intrinsic.control.barrier.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.intrinsic.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.intrinsic.vulkan1.1.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.operators.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.precedence.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.variables.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] use presumed loc for line info

tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/CodeGenHLSL/batch/expressions/conversions_and_casts/negative_literal_int_to_float.hlsl
=> Fix conversions of literal negative ints to FP16 types

tools/clang/include/clang/SPIRV/AstTypeProbe.h, tools/clang/lib/SPIRV/AlignmentSizeCalculator.cpp, tools/clang/lib/SPIRV/AstTypeProbe.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/test/CodeGenSPIRV/raytracing.nv.enum.hlsl, tools/clang/test/CodeGenSPIRV/type.enum.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] support enum type

docs/DXIL.rst, include/dxc/DXIL/DxilConstants.h, include/dxc/HLSL/DxilValidation.h, lib/HLSL/DxilValidation.cpp, tools/clang/test/CodeGenHLSL/mesh-val/msOversizeOutput.hlsl, tools/clang/test/CodeGenHLSL/mesh-val/msOversizePayloadOutput.hlsl, tools/clang/unittests/HLSL/ValidationTest.cpp, utils/hct/hctdb.py
Hi Tex
Could you please help review this PR?
Thank you!
Zhiwei
=> add DXIL tests to verify mesh shader's output size and payload plus output size

docs/SPIR-V.rst, tools/clang/test/CodeGenSPIRV/meshshading.nv.buffer.mesh.hlsl, tools/clang/test/CodeGenSPIRV/meshshading.nv.fncall.amplification.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
- Also cleans up SPIR-V.rst documentation issues.
Adding @jaebaek @ehsannas for code review
=> [spirv] Add mesh/amplification shader tests for use of buffers and fn calls

tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/GlPerVertex.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h
Adding @ehsannas and @jaebaek for code review.
=> [spirv] Add comments and missing initializations for mesh shader implementation

lib/DxilDia/DxilDiaSymbolManager.cpp
=> PIX/DIA: Calculate offsets for embedded arrays

tools/clang/lib/SPIRV/AstTypeProbe.cpp, tools/clang/test/CodeGenSPIRV/vk.layout.non-fp-matrix.array.struct.error.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Handling array of structure of non-float col-major matrix case.
=> [spirv] report error for non-float col matrix

tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/mul/mul.hlsl
=> Choose UMad instead of IMad for unsigned matrix multiplication

tools/clang/test/CodeGenSPIRV/intrinsics.non-uniform-resource-index.hlsl, tools/clang/test/CodeGenSPIRV/type.runtime-array.hlsl
Getting all the recent updates.
=> [spirv] Update SPIRV-Tools.

include/dxc/HLSL/HLOperations.h, include/dxc/HlslIntrinsicOp.h, lib/DXIL/DxilOperations.cpp, lib/HLSL/DxilPreparePasses.cpp, lib/HLSL/HLOperationLower.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/include/clang/AST/HlslTypes.h, tools/clang/lib/AST/ASTContextHLSL.cpp, tools/clang/lib/AST/HlslTypes.cpp, tools/clang/lib/CodeGen/CGClass.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/lib/Sema/gen_intrin_main_tables_15.h, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/basic/abs1.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/RayQuery/rayquery-array-2d-dynamic.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/RayQuery/rayquery-array.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/RayQuery/rayquery-decls.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/RayQuery/rayquery-no-cse.hlsl, utils/hct/gen_intrin_main.txt, utils/hct/hctdb.py, utils/hct/hctdb_instrhelp.py
- Doesn't yet support dynamically indexed arrays (will crash)
=> Fix RayQuery allocation for CSE, DCE, statics, arrays, and lifetimes

lib/DxilPIXPasses/DxilDebugInstrumentation.cpp, tools/clang/test/HLSLFileCheck/pix/DebugAs.hlsl, tools/clang/test/HLSLFileCheck/pix/DebugMs.hlsl
Also re-ordered all the switch statements so that the pipeline stages are always in pipeline order (or near enough).
=> PIX: Add Amplification/Mesh shader to shader debugging instrumentation

lib/DxilDia/DxilDiaSymbolManager.cpp
A previous bug in dxcompiler meant that there was no linkage from SubProgram to Function. 
Some of PIX's customers' traces still have bitcode generated with this problem, so as a workaround, the DIA front-end can look at the DXIL module's entry point function instead, and start iterating over basic blocks from there.
=> PIX: (DIA front-end): Use module entry point as backup iteration start

tools/clang/tools/dxcompiler/dxcassembler.cpp, tools/clang/tools/dxcompiler/dxclinker.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/tools/dxcompiler/dxcutil.cpp, tools/clang/tools/dxcompiler/dxcutil.h, tools/clang/tools/dxrfallbackcompiler/dxcdxrfallbackcompiler.cpp, tools/clang/tools/dxrfallbackcompiler/dxcutil.cpp, tools/clang/tools/dxrfallbackcompiler/dxcutil.h
Also fixes requiring debug info enabled to set the debug name.
=> Fix recording debug name when validation disabled (-Vd)

include/dxc/HLSL/HLOperations.h, lib/HLSL/HLOperationLower.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/Texture/cube_gather.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/Texture/cube_sample.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/Texture/gatherCubeOffset.hlsl
Fixes #2534 
Adds a bunch of tests.
=> Fix lowering for all TextureCube[Array] Sample* and Gather* overloads

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/op.array.access.hlsl
=> [spirv] Allow result of logical ops as array index.

lib/HLSL/HLModule.cpp, tools/clang/test/HLSLFileCheck/hlsl/types/modifiers/precise/precise-matrix-subscript.hlsl
=> Fix precise on matrix with matrix subscript.

tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/tools/dxcompiler/dxcutil.cpp, tools/clang/tools/dxcompiler/dxcutil.h, tools/clang/tools/dxcompiler/dxcvalidator.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/ValidationTest.cpp
Cherry-pick c54dd6b57 (#2560) from master to release-1.5.1910.
=> Support valiadation/signing of root signature target output

include/dxc/HLSL/HLModule.h, lib/HLSL/HLModule.cpp, lib/HLSL/HLOperationLower.cpp, tools/clang/test/HLSLFileCheck/hlsl/resource_binding/resource_in_cbuffer.hlsl
TODO: use correct register binding if exist.
=> Clear register binding for resource in cbuffer.

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/test/CodeGenSPIRV/spirv.user-semantic.vs.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] Fix the UserSemantic decoration string.

lib/HLSL/DxilLinker.cpp
Fix non-determinism in dxil linker.
Fixes #2329
=> Fix non-determinism in dxil linker

lib/HLSL/HLOperationLower.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/pixel/clip_constant.hlsl
=> Don't emit discard when input is non-negative

lib/HLSL/DxilCondenseResources.cpp
This is one issue impacting #2608.
It doesn't completely fix it because we still need to:
- respect [unroll] on /Od (will fix the simple repro on its own, but only for unrolled loops or other cases)
- not fail on poison values in dead code paths by either running simplify CFG or by being a lot smarter and using dxil value cache or something in FailOnPoisonResources().
=> Translate resource poison value to undef index instead of assert

include/dxc/DXIL/DxilConstants.h, include/dxc/DXIL/DxilShaderModel.h, include/dxc/Support/HLSLOptions.td, lib/DXIL/DxilShaderModel.cpp, lib/HLSL/DxilValidation.cpp, utils/hct/hctdb_instrhelp.py
Shader model 6.6 is not yet fully supported.
=> Change highest supported shader model to 6.5 for the release.

include/dxc/dxcpix.h, lib/DxilDia/CMakeLists.txt, lib/DxilDia/DxcPixBase.h, lib/DxilDia/DxcPixDxilDebugInfo.cpp, lib/DxilDia/DxcPixDxilDebugInfo.h, lib/DxilDia/DxcPixDxilStorage.cpp, lib/DxilDia/DxcPixDxilStorage.h, lib/DxilDia/DxcPixEntrypoints.cpp, lib/DxilDia/DxcPixLiveVariables.cpp, lib/DxilDia/DxcPixLiveVariables.h, lib/DxilDia/DxcPixLiveVariables_FragmentIterator.cpp, lib/DxilDia/DxcPixLiveVariables_FragmentIterator.h, lib/DxilDia/DxcPixTypes.cpp, lib/DxilDia/DxcPixTypes.h, lib/DxilDia/DxcPixVariables.cpp, lib/DxilDia/DxilDiaSession.cpp, lib/DxilDia/DxilDiaSession.h, lib/DxilDia/DxilDiaSymbolManager.cpp, lib/DxilPIXPasses/DxilAnnotateWithVirtualRegister.cpp, lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp, lib/DxilPIXPasses/DxilPIXPasses.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp, utils/hct/hctdb.py
This adds the initial implementation of the DxcPix API. This implementation
provides an API inspecting variables and their locations, to enable HLSL.
=> Adds the DxcPixDxilDebugInfo interface and friends.

include/dxc/DxrFallback/DxrFallbackCompiler.h, include/dxc/Support/dxcapi.use.h, include/llvm/ExecutionEngine/ExecutionEngine.h, lib/DxilContainer/DxilContainerAssembler.cpp, lib/DxilDia/DxilDiaSession.cpp, lib/DxilDia/DxilDiaSession.h, lib/DxrFallback/DxrFallbackCompiler.cpp, lib/DxrFallback/FunctionBuilder.h, lib/DxrFallback/LLVMUtils.cpp, lib/DxrFallback/StateFunctionTransform.cpp, lib/ExecutionEngine/ExecutionEngine.cpp, lib/HLSL/DxilContainerReflection.cpp, tools/clang/include/clang-c/Index.h, tools/clang/include/clang/Lex/ModuleLoader.h, tools/clang/include/clang/Lex/PreprocessorOptions.h, tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/tools/c-index-test/c-index-test.c, tools/clang/tools/dxrfallbackcompiler/dxcdxrfallbackcompiler.cpp, tools/llvm-objdump/MachODump.cpp
=> Rename 'module' to 'hModule' for C++20 compat

include/dxc/dxcpix.h
PIX's code-analysis pass complained about the SAL in this file. These changes make it happy.
=> PIX debug header: Update to correct(er) SAL

lib/DxilPIXPasses/DxilShaderAccessTracking.cpp, tools/clang/test/HLSLFileCheck/pix/TraceRayInline.hlsl
RayQuery_TraceRayInline needed special-case.
=> Add tracerayinline to access tracking

tools/clang/tools/dxcompiler/dxcompilerobj.cpp
- Older validators cannot validate/sign root signature-only containers
Fixes #2747
=> Skip root signature container validation on validator < 1.5

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
When splitting a memcpy because of faile dependency checks, any memcpy
created to copy part of the original is going to have the same
characteristics that caused the first to be split. Instead of splitting
repeatedly, just use the alternative code generation built into splitCpy
=> Prevent repeated memcpy splitting

lib/DXIL/DxilOperations.cpp, lib/HLSL/DxilConvergent.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/FeedbackTexture/feedback_convergent.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/Texture/cube_gather.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/Texture/gather_cs.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/Texture/gather_not_convergent.hlsl, utils/hct/hctdb.py
Also fixed:
- remove SampleCmpLevelZero in DxilConvergent
- next_op_idx assert message in hctdb.py
- add WriteSamplerFeedback to gradient and convergent ops
#2759 is fixed by this, but will require updated validator.
=> Gather should not be considered a gradient operation.

.travis.yml
This is still work-in-progress
=> [build] Attempt to store Linux&macOS build artifacts.

lib/HLSL/HLLegalizeParameter.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/HLSLFileCheck/shader_targets/library/lib_arg_flatten/lib_empty_struct_arg.hlsl
TODO: enable code to avoid the copy.
=> Enable copy-in copy-out for lib profile.

lib/HLSL/DxilPreparePasses.cpp
Because VisitedPhis parameter to the recursive function to cull wave
sensitive blocks was not passed by reference, PHI nodes were getting
repeated. This corrects that issue and also adds bailouts for when no
break blocks are left or when the call instruction isn't in the current
function.
=> Correct long loops for wave-sensitive tracing

CMakeLists.txt, cmake/modules/AddLLVM.cmake, external/CMakeLists.txt
It's a follow up work of #2879. Flip the option name and default value.
=> Change HLSL_DISABLE_DEBUG_ITERATORS to more natural HLSL_ENABLE_*

tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/raytracing.khr.closesthit.hlsl, tools/clang/test/CodeGenSPIRV/vk.layout.shader-record-nv.std430.hlsl, tools/clang/test/CodeGenSPIRV/vk.shader-record-nv.hlsl, tools/clang/test/CodeGenSPIRV/vk.shader-record-nv.offset.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] Enforce SPIR-V 1.4 for SPV_KHR_ray_tracing.

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/include/clang/SPIRV/SpirvVisitor.h, tools/clang/lib/SPIRV/CMakeLists.txt, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.h, tools/clang/lib/SPIRV/NonUniformVisitor.cpp, tools/clang/lib/SPIRV/NonUniformVisitor.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.non-uniform-resource-index.hlsl, tools/clang/test/CodeGenSPIRV/spirv.debug.opline.intrinsic.hlsl
=> [spirv] Improve codegen for NonUniform

cmake/modules/FindTAEF.cmake
Cherry-picked from https://github.com/microsoft/DirectXShaderCompiler/commit/c5d0449380923be4ad900614b2152495512e2ac6.
=> Enable TAEF path specification via environment variable (#2778)

tools/clang/lib/AST/DeclPrinter.cpp, tools/clang/test/HLSL/rewriter/correct_rewrites/attributes_gold.hlsl, tools/clang/test/HLSL/rewriter/correct_rewrites/packreg_gold.hlsl, tools/clang/test/HLSLFileCheck/rewriter/init_use.hlsl, tools/clang/test/HLSLFileCheck/rewriter/nested_struct.hlsl, tools/clang/tools/libclang/dxcrewriteunused.cpp
1. print space for resource.
2. check use of global in init.
3. support nested struct.
=> More fix for rewriter.

tools/clang/include/clang/Basic/DiagnosticASTKinds.td, tools/clang/lib/AST/ExprConstant.cpp, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/warnings/constexpr_cast_overflow_nowarning.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/warnings/constexpr_cast_overflow_warning.hlsl
Generate warning when overflow happen during const expr cast
=> Generate warning when overflow happen during const expr cast

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.multiprefix.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] Fix unsafe pointer access.

tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/test/CodeGenSPIRV/spirv.cf.ret-missing.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/no_return.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/enum/enum4.hlsl
=> Default to error on missing return from non-void function.

tools/clang/include/clang/SPIRV/AstTypeProbe.h, tools/clang/lib/SPIRV/AstTypeProbe.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resource-mix.error.1.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resource-mix.error.2.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resources.1.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resources.2.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resources.3.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resources.4.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resources.contains-buffer-error.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resources.optimized.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/2695
=> [spirv] Support globals structs of Textures/Samplers

include/llvm/Transforms/Scalar.h, lib/HLSL/DxcOptimizer.cpp, lib/Transforms/IPO/PassManagerBuilder.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/HLSLFileCheck/hlsl/types/modifiers/static/cb_static_temp_static.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/modifiers/static/staticGlobals3.hlsl, utils/hct/hctdb.py
This will allow memcpy replacement works for case like cb->global->alloca->global.
=> SROA alloca and global variable at same worklist.

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
As of the recent -Werror enable, this unused function causes clang
builds to fail. It is a duplicate and removing this resolves it.
=> Remove unused function from SROA_HLSL

lib/HLSL/DxilPreparePasses.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/wave/reduction/WaveAndBreakPS.hlsl
Previously, only PHI instructions were collected and prevented from
repeating. This was the minimum required to prevent infinite compiles,
but in complicated shaders with a lot of wave dependencies that feed in
through multiple operands, compilation can take a very long time.
By including all encountered instructions, no repetition of traversal is
performed. The cost is lookups into a much larger set, but that seems
the vastly more performant option.
=> Don't reprocess instr in CullSensitiveBlocks

lib/HLSL/DxilContainerReflection.cpp
- Switches to StringRef for keys since these won't attempt to allocate string on find.
- Ensure string is owned by the CShaderReflectionConstantBuffer object.
- catch potential issues (don't leak exceptions) in PDB stream load.
Fixes #2969.
=> Fix thread malloc issue with GetConstantBufferByName

include/dxc/DXIL/DxilOperations.h, lib/DXIL/DxilOperations.cpp, lib/DXIL/DxilShaderFlags.cpp, lib/HLSL/DxilTranslateRawBuffer.cpp, lib/HLSL/DxilValidation.cpp, lib/HLSL/HLOperationLowerExtension.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, utils/hct/hctdb_instrhelp.py
Some sundry changes encountered while working on other things. Each is explained in its individual commit message.
=> Sundry code cleanups

tools/clang/unittests/HLSL/ExecutionTest.cpp
+ move behind marker for shared DxilConf tests
=> Update highest supported shader model definition with newest Windows releases

tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/test/CodeGenSPIRV/unary-op.sizeof.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] support sizeof()

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/ternary-op.cond-op.hlsl
=> [spirv] Support boolean matrix as ternary condition.

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/unary-op.minus.hlsl
=> [spirv] Support UnaryOperator for negating a matrix.

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/test/CodeGenSPIRV/semantic.inner-coverage.type-error.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] Error out if SV_InnerCoverage is not uint.

tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/test/CodeGenSPIRV/raytracing.acceleration-structure.hlsl, tools/clang/test/CodeGenSPIRV/raytracing.nv.acceleration-structure.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] Add needed capabilities for Raytracing AccelerationStructure.

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/method.rwtexture.load.hlsl
=> [spirv] Handle resource templated by vec1.

tools/clang/unittests/HLSL/ShaderOpTest.cpp, tools/clang/unittests/HLSL/ShaderOpTest.h
Add support for mipmaps and mesh shaders
=> Enhance ShaderOpTest

README.md
=> Add note regarding .js assocation to readme

tools/clang/include/clang/SPIRV/AstTypeProbe.h, tools/clang/lib/SPIRV/AstTypeProbe.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/cast.matrix.trunc.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.mul.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.transpose.hlsl
=> [spirv] Handle corner cases of transpose and mul.

tools/clang/tools/dxcompiler/dxcassembler.cpp
=> Add autofilesys for disassemble entrypoint

tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/test/CodeGenSPIRV/spirv.debug.source.non.existing.file.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] support non-existing header file include

lib/HLSL/HLOperations.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/barrier/no_dup.hlsl
=> Not dup barrier in HL level.

include/dxc/DXIL/DxilConstants.h, include/dxc/DXIL/DxilShaderModel.h, include/dxc/Support/HLSLOptions.td, lib/DXIL/DxilShaderModel.cpp, lib/HLSL/DxilValidation.cpp, utils/hct/hctdb_instrhelp.py
Shader model 6.6 is not yet fully supported.
=> Change highest supported shader model to 6.5 for the 2010 release

tools/clang/lib/SPIRV/SpirvEmitter.cpp
As SPIRV-Tools supports the debug info preservation for the full
optimization, we want to allow DXC users to use the full optimization
for the debug info generation.
This change updates SPIRV-Tools and SPIRV-Headers.
=> [spirv] allow debug info generation to use full optmization

tools/clang/unittests/HLSL/ExecutionTest.cpp
=> Add caps check for optional 16bit ops support to several execution tests

lib/HLSL/DxilPrecisePropagatePass.cpp, tools/clang/test/HLSLFileCheck/hlsl/types/modifiers/precise/precise5.hlsl
propagate through:
- non-FP paths that might have been dependent on FP paths
- intrinsics that aren't simple FP math intrinsics (such as Sample)
- pointers to matching GEPs
- conditions for control dependent branches
=> Fix precise propagation through various missing paths

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resource-mix.error.1.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resource-mix.error.2.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resources.1.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resources.2.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resources.3.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resources.4.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resources.contains-buffer-error.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resources.optimized.hlsl, tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resources.pass-legalization.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp, tools/clang/unittests/SPIRV/FileTestUtils.cpp
=> [spirv] Move descriptor scalar replacement to legalization stage.

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/binary-op.mul-assign.type-mismatch.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] Fix compound MulAssign with type mismatches.

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/oo.struct.derived.methods.hlsl, tools/clang/test/CodeGenSPIRV/oo.struct.derived.methods.override.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] Fix read/write to base struct member from derived struct

docs/SPIR-V.rst, tools/clang/include/clang/SPIRV/SpirvContext.h, tools/clang/include/clang/SPIRV/SpirvType.h, tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/lib/SPIRV/SpirvContext.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/rayquery_assign.cs.hlsl, tools/clang/test/CodeGenSPIRV/rayquery_equal.cs.hlsl, tools/clang/test/CodeGenSPIRV/rayquery_init_ds.hlsl, tools/clang/test/CodeGenSPIRV/rayquery_init_gs.hlsl, tools/clang/test/CodeGenSPIRV/rayquery_init_hs.hlsl, tools/clang/test/CodeGenSPIRV/rayquery_init_ps.hlsl, tools/clang/test/CodeGenSPIRV/rayquery_init_rahit.hlsl, tools/clang/test/CodeGenSPIRV/rayquery_init_rcall.hlsl, tools/clang/test/CodeGenSPIRV/rayquery_init_rchit.hlsl, tools/clang/test/CodeGenSPIRV/rayquery_init_rgen.hlsl, tools/clang/test/CodeGenSPIRV/rayquery_init_rint.hlsl, tools/clang/test/CodeGenSPIRV/rayquery_init_rmiss.hlsl, tools/clang/test/CodeGenSPIRV/rayquery_init_vs.hlsl, tools/clang/test/CodeGenSPIRV/rayquery_tryAllOps.cs.hlsl, tools/clang/test/CodeGenSPIRV/raytracing.acceleration-structure.hlsl, tools/clang/test/CodeGenSPIRV/raytracing.khr.closesthit.hlsl, tools/clang/test/CodeGenSPIRV/raytracing.nv.library.hlsl, tools/clang/test/CodeGenSPIRV/raytracing.nv.raygen.hlsl
1. Add OpTraceRayKHR
2. Remove "provisional" in files
3. Update the SPIRV Headers/Tools to latest version
=> [spirv]Updates to RayTracing semantics

tools/clang/lib/SPIRV/AlignmentSizeCalculator.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/oo.inheritance.layout-differences.hlsl, tools/clang/test/CodeGenSPIRV/oo.inheritance.layout.empty-struct.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] Fix issues related to struct inheritance memory layout

cmake/modules/FindTAEF.cmake
- prioritize TAEF path from environment variable
- find TAEF binaries based on the header location
- refactor libraries search
=> TAEF cmake fixes

tools/clang/unittests/HLSL/ExecutionTest.cpp
Buffers were being created as Texture1D Views, which causes problems on
some hardware.
=> Correct Resource Views in Resource Execution Test

utils/hct/hctbuild.cmd
=> Disable voice in build script by default

tools/clang/unittests/HLSL/ExecutionTest.cpp
A resource being treated like a texture in the shader was being created
as a buffer. This caused problems on some platforms including warp,
which required an ugly workaround that this removes
=> Resources test Tex/Buffer mismatch fix

tools/clang/unittests/HLSL/ExecutionTest.cpp
Corrected quadread index calculation which was not fully updated
Also ups priority only skipping when warp is used so this won't be
missed again and improves the error output by using equals macros
=> Correct QuadRead index

docs/DXIL.rst, include/dxc/HLSL/DxilValidation.h, include/dxc/HlslIntrinsicOp.h, lib/HLSL/HLOperationLower.cpp, utils/hct/hctdb.py
Update validation rule info in hctdb.py
=> Update validation rule info in hctdb.py

utils/llvm-build/llvmbuild/main.py
=> Disable LLVMBuild.txt dependencies and DummyConfigureOutput writing for official builds

tools/clang/unittests/HLSL/ExecutionTest.cpp
Various resources have been created inconsistently with the shader
representation. After running out of bandaids, this refactors that code
to give the caller the tools necessary to create the resources
correctly.
=> Refactor resource creation in resources exec test

tools/clang/unittests/HLSL/ExecutionTest.cpp
The lifetime test had parameters for UAV creation in the wrong order so
they were misassigned. The use of lib creation also didn't depend on
raytracing support as it should.
correct some other sm66 cap bit checks too
=> Lifetime test: UAVcreation/raytracing conditionals

docs/DXIL.rst, include/dxc/DXIL/DxilConstants.h, include/dxc/DXIL/DxilInstructions.h, include/dxc/HlslIntrinsicOp.h, lib/Analysis/DxilConstantFolding.cpp, lib/DXIL/DxilOperations.cpp, lib/HLSL/DxilValidation.cpp, lib/HLSL/HLOperationLower.cpp, tools/clang/lib/Sema/gen_intrin_main_tables_15.h, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/helper/IsHelperLane.hlsl, tools/clang/tools/dxcompiler/dxcdisassembler.cpp, utils/hct/gen_intrin_main.txt, utils/hct/hctdb.py
Todo: implement fallback for downlevel shader models.
=> Implement IsHelperLane()

include/dxc/DxilContainer/DxilContainerAssembler.h, include/dxc/DxilContainer/DxilPipelineStateValidation.h, lib/DxilContainer/DxilContainerAssembler.cpp, lib/HLSL/DxilValidation.cpp
- Add ResourceKind and NumThreads(X,Y,Z)
- Increment MAX_PSV_VERSION to 2
- Clean up versioning logic
=> Add ResourceKind/NumThreads to PSV0 (DxilPipelineStateValidation)

include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/test/HLSLFileCheck/hlsl/lifetimes/lifetimes.hlsl
Intended for debugging and workarounds
=> Add hidden option to disable lifetime markers

lib/DXIL/DxilMetadataHelper.cpp, lib/HLSL/HLOperationLower.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/NonUniformResourceIndex/nonUniformIndex_propagation.hlsl
Should only mark nonUniform on user of CI.
=> Fix bug when lower NonUniformResourceIndex.

tools/clang/test/HLSL/ShaderOpArith.xml, tools/clang/unittests/HLSL/ExecutionTest.cpp
Change test to represent both 1D and 2D quad layout options
=> Add 2D quads to ComputeSample test

lib/HLSL/HLOperationLower.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/StructuredBuffer/struct_buf_mat_load_method.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/StructuredBuffer/struct_buf_mat_subscript_method.hlsl
Load remainder raw buffer elements in the end. 
Fixes #3457.
=> Load remainder buffer elements in the end

lib/HLSL/HLOperationLower.cpp, lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/cb_array_mutate.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/cb_array_mutate2.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/cb_array_mutate3.hlsl
float4 cb[16];
float v[64] = cb;
=> Avoid cbuffer copy for special pattern.

lib/HLSL/HLOperationLowerExtension.cpp, tools/clang/unittests/HLSL/ExtensionTest.cpp
Any extension function that includes the specical string "$o" in its name
needs to have the $o replaced with the type name of the overload. Previously
we used a default heuristic to select the overload type from a function
argument.
This commit adds support for explicitly setting the argument to use for the
overload name by appending a ":<ArgIndex>" to the overload marker. For example,
using a name like "my_special_function.$o:3" would take the overload type from
the third function argument.
=> Add support for specifying overload arg index in extension function

include/dxc/DXIL/DxilConstants.h, tools/clang/tools/dxcompiler/dxcdisassembler.cpp
=> Correct 64-bit atomics on heap resource flags

include/dxc/DXIL/DxilConstants.h, include/dxc/DXIL/DxilShaderFlags.h, lib/DXIL/DxilShaderFlags.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/atomic/atomic_i64_dynamic_resource.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/NonUniformDynamic.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/createFromHeap.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/createFromHeap2.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/createFromHeap3.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/createFromHeap4.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/dynamic_res_global_for_lib.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/dynamic_res_global_for_lib2.hlsl
Set shader flags for resource and sampler descriptor heap indexing based
on the CreateHandleFromHeap call and its ShaderHeap argument
=> Set shader flags for dynamic resources

docs/DXIL.rst, include/dxc/HLSL/DxilValidation.h, lib/HLSL/DxilValidation.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/cbufferSize1.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/cbufferSize2.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/cbufferSize3.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/cbufferSize4.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/cbufferSize5.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/cbufferSize6.hlsl, utils/hct/hctdb.py
=> Validate CBuffer size to max of 65536 bytes

tools/clang/unittests/HLSL/ExecutionTest.cpp
merge from #3545
(cherry picked from commit 7e1a660ae99858722d00b3e329f07a40bc05ce52)
=> Check for Resource Binding Tier 3 before running DynamicResources test

lib/HLSL/HLOperationLower.cpp, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/vec_indexing_with_offset.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/vec_indexing_with_offset_16bit.hlsl
* Take care case dynamic indexing on vector start with offset.
=> Take care case dynamic indexing on vector start with offset. (#3558)

tools/clang/unittests/HLSL/ExecutionTest.cpp
(cherry picked from commit 5f760473132dbfe11ce59634ab47798c495d2fae)
=> ComputeSampleTest: reset test between runs (#3561)

lib/HLSL/DxilPreparePasses.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/helper/IsHelperLane_fallback_no_use.hlsl
=> Fix coverage being used to init dx.ishelper when only discard is used

lib/DXIL/DxilShaderFlags.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/helper/IsHelperLane.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/pixel/attr/attributeAtVertex.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/pixel/attr/attributeAtVertexNoOpt.hlsl, tools/clang/test/HLSLFileCheck/hlsl/lifetimes/lifetimes_lib_6_3.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/cbufferSize1.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/cbufferSize3.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/cbufferSize5.hlsl, tools/clang/test/HLSLFileCheck/hlsl/objects/CbufferLegacy/cbufferSize6.hlsl, tools/clang/test/HLSLFileCheck/hlsl/semantics/sv_barycentrics/barycentrics.hlsl, tools/clang/test/HLSLFileCheck/hlsl/semantics/sv_barycentrics/barycentrics1.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/conversions/semantics_Mod.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/modifiers/groupshared/groupshared_shadermodels.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/DxilModuleTest.cpp, tools/clang/unittests/HLSL/LinkerTest.cpp
Fix back-compat issues and tests for released 1.4 and 1.5 validators.
=> Fix Dxil validator compat and test issues

lib/HLSL/DxilValidation.cpp
Module with stripped reflection will have no name for error messages.
Try to get the name from the debug module.
Failing that, use ID, type and binding info.
=> Generate descriptions for resources with no names

README.md
=> Fix artifacts download link

lib/DXIL/DxilModule.cpp
When compiling a library without 16-bit support, certain struct types
containing either min precision types or matrices must be saved in
reflection data for conversion after linking. However, this is only
necessary when the types are used by a resource.
Instead of evaluating all matrix types and saving those that meet this
criteria, only the types used by resources are evaluated and possibly
preserved. This significantly shrinks the reflection size in this case.
=> Only keep legacy struct types from resources

lib/DxilPIXPasses/DxilShaderAccessTracking.cpp, lib/HLSL/DxilValidation.cpp, tools/clang/test/CodeGenHLSL/basic.hlsl, tools/clang/test/HLSLFileCheck/pix/AccessTracking.hlsl, tools/clang/test/HLSLFileCheck/pix/AccessTrackingForSamplerFeedback.hlsl, tools/clang/test/HLSLFileCheck/pix/DynamicResourceAccessTracking.hlsl, tools/clang/test/HLSLFileCheck/pix/DynamicResourceOutOfBounds.hlsl, tools/clang/test/HLSLFileCheck/pix/DynamicSamplerAccessTracking.hlsl, tools/clang/test/HLSLFileCheck/pix/DynamicSamplerOutOfBounds.hlsl, tools/clang/test/HLSLFileCheck/pix/TraceRayInline.hlsl, tools/clang/test/HLSLFileCheck/pix/rawBufferStore.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/ValidationTest.cpp
Cherry-pick these changes to release:
634cd49ba Disallow CreateHandle in SM66+ and library targets (#3629)
880c1359c PIX SM 6.6 resource access tracking (#3594)
=> Merge fixes for release branch

tools/clang/unittests/HLSL/ExecutionTest.cpp
(cherry picked from commit 6e0f1f96ff101bd3bb6eabe7790842c7877c1281)
=> Remove artificial FL12 requirement for CreateDevice (#3633)

tools/clang/test/HLSLFileCheck/hlsl/objects/Texture/convergent_cs.hlsl
Allows running on limited platforms
=> Constrain convergent_cs mesh test threads

include/llvm/IR/BasicBlock.h, include/llvm/Option/OptTable.h, lib/IR/BasicBlock.cpp, lib/Option/OptTable.cpp, lib/Transforms/Scalar/MergedLoadStoreMotion.cpp, tools/clang/tools/dxcompiler/dxcpdbutils.cpp, tools/clang/tools/dxcompiler/dxcshadersourceinfo.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/ExecutionTest.cpp
Cherry-pick these commits to release branch:
1f6d1facb Fixed a potential codegen difference with Zi (#3665)
c8123cf7f Fixed a bug in pdb where -W[...] type options are split into two tokens (#3646)
098af75e4 Move ExecutionTest setup out of area shared with HLK code. (#3682)
d878c0a71 Enable experimental shaders option in HLK tests (#3601)
=> Merge fixes for release - refactor setup, -Zi and PDB fixes

tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/offsets.hlsl, tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/offsets_gather.hlsl
Gathers are more complicated and deserve more thorough testing in an
individual unit test
=> Split gather offsets into separate test

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/intrinsics.asuint.rvalue.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] Make sure asuint() argument is r-value

lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp
Two things:
First recurse down type hierarchy. The previous code only went down 2 levels...
Second, derive base type from enum classes when populating fake debug-store locations
=> PIX: Allow debug of enum classes

utils/hct/hctbuild.cmd
Cherry-picked from master:
56e22b30c5  Enable random order of hctbuild arguments (#3741)
7f44ae2e4c  Add -cmake-system-version argument to hctbuild.cmd to enable setting of target Windows version (min WinSDK version) (#3704)
=> Merge hctbuild.cmd changes from master

tools/clang/lib/Sema/SemaDXR.cpp, tools/clang/test/HLSLFileCheck/hlsl/payload_qualifier/access.hlsl
Payloads with an initializer are not handled correctly. If a payload struct is input to a TraceRay call, and the payload struct was initialized through list or copy initialization handle it as field write for every field in the struct.
Compound assignment operators were not correctly handled as reads. The recursive check for a DeclRef was bailing out on the first DeclRef instead of checking all children of the statement.
Added testcases for both issues.
=> Minor fix for PAQ diagnostics

tools/clang/lib/CodeGen/CGDecl.cpp, tools/clang/test/HLSLFileCheck/hlsl/functions/misc/const-pos-out.hlsl
=> Fix const var init with NRVO

tools/clang/lib/SPIRV/SpirvEmitter.cpp
`--before-legalize-hlsl` option for spirv-val must be used when the
SPIR-V code has to be legalized by spirv-opt but it is not legalized
i.e., "SPIR-V generated from HLSL before legalize". Therefore, we have
to run the legalization or pass the `--before-legalize-hlsl` option to
spirv-val but we do not need to do both. This CL lets DXC does not pass
`--before-legalize-hlsl` option when it legalizes the SPIR-V code.
=> [spirv] separate legalization and before-legalize-hlsl

README.md
Adding information for DirectX landing page
=> Adding information for DirectX landing page

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/HLSLFileCheck/hlsl/types/struct/embeddedEmptyStruct.hlsl
=> Handles empty embedded struct as first field of struct.

tools/clang/lib/CodeGen/CGExpr.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/HLSL/bitfields.hlsl, tools/clang/test/HLSL/cpp-errors.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/struct/bitfields.hlsl, tools/clang/test/HLSLFileCheck/hlsl/types/struct/bitfields_error.hlsl, tools/clang/unittests/HLSL/VerifierTest.cpp, utils/hct/VerifierHelper.py
=> Enables HLSL bitfields.

lib/Support/CommandLine.cpp
This bug caused one of our cooks in UE5 to produce several of these error messages:
```
: CommandLine Error: Option '
```
I presume the last changed line was intended to be `Opt->ArgStr[0] != 0` instead of `!Opt->ArgStr[0]` as the error message is cropped. I replaced this and two other conditions with the appropriate function `hasArgStr()`.
=> Fix command line parsing on empty string.

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
The vertex shader output variable with SV_Position semantics must have
float4 type or an aggregate type recursively contains only float4. This
CL adds the type check and lets DXC report an error if the type is
invalid.
Fixes #3736
=> [spirv] report SV_Position with invalid type

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/cast.vec-to-mat.implicit.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] Add support for casting from floatM to floatMx1

tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp, tools/clang/test/CodeGenHLSL/atan2_vector_argument.hlsl, tools/clang/test/CodeGenHLSL/isnan_vector_argument.hlsl, tools/clang/unittests/HLSL/CompilerTest.cpp
=> Support const vector argument for isnan(), atan2()

include/dxc/HLSL/HLOperationLower.h, lib/HLSL/DxilCondenseResources.cpp, lib/HLSL/DxilGenerationPass.cpp, lib/HLSL/HLOperationLower.cpp, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/dynamic_append_buf.hlsl, tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/dynamic_res_array.hlsl
Fix issue when updateCounter for dynamic resource, also remove createHandleForLib on handle type when not a library.
=> Fix issue when updateCounter for dynamic resource

azure-pipelines.yml
Hopefully this will let it find the right python
=> Update macos for azure

azure-pipelines.yml
Finding python3 has been a bit hit or miss. Hopefully this will make it
hit consistently
=> Add an explicit python version

tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/texture.load.hlsl, tools/clang/test/CodeGenSPIRV/type.texture.hlsl
Add support for bool typed textures to be compatible with FXC.
Fixes #3236
=> [spirv] Support bool* as texture template type

lib/HLSL/DxilCondenseResources.cpp, tools/clang/test/HLSLFileCheck/d3dreflect/anon_struct.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/cb_1x1array.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/cb_array.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/cb_sizes.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/cbuf-usage-lib.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/cbuf-usage-phi.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/cbuffer_default_val.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/empty_struct2.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/lib_cb_matrix_array.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/lib_global.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/reflect-lib-1.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/structured_buffer_layout.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/tbuffer-16bit.hlsl, tools/clang/test/HLSLFileCheck/d3dreflect/tbuffer.hlsl
=> Fix cbuffer variable usage in reflection for SM 6.6

tools/clang/include/clang/Sema/AttributeList.h, tools/clang/lib/Sema/AttributeList.cpp
Attributes size exceeds to the limit of the 255, use 16 bit AttrKind
=> Expand AttrKind from 8bit to 16 bits

lib/Support/Windows/WindowsSupport.h
This isn't hit in all build configuraitons, but it is in some...
=> Adding a missing include

utils/hct/hctbuild.cmd
This change adds -update-generated-sources to the hctbuild -help spew.
=> NFC. Document -update-generated-sources flag

lib/DXIL/DxilModule.cpp, lib/DxilPIXPasses/PixPassHelpers.cpp
This happens in the 11on12 case...
=> PIX: Check for null HS entry point (pass-through case)

lib/HLSL/DxilValidation.cpp, utils/hct/hctgen.py
This code should be part of the generated file not the hard coded bits.
=> Missed a bit of generated code

lib/HLSL/HLMatrixLowerPass.cpp, tools/clang/test/HLSLFileCheck/hlsl/types/matrix/constMat5.hlsl
(cherry picked from commit 39dd31f3552632de480fcc575de452f673915737)
=> Fix assert from matrix lower needlessly casting constant to instruction. (#4115)

tools/clang/test/HLSLFileCheck/hlsl/template/3731-resource-descriptor-heap.hlsl
This test case worked in PR tests, but was broken on merge to master
due to other changes that were merged between when the PR went up and
when it was merged.
=> [NFC] Fix broken template test case

tools/clang/lib/SPIRV/SpirvEmitter.cpp
Fixes #3705 with KhronosGroup/SPIRV-Tools@d0a827a
=> [spirv] Update SPIRV-Tools and SPIRV-Headers submodules

tools/clang/test/HLSLFileCheck/hlsl/template/DependentWithBuiltinTemplate.hlsl
Test case authored by @tex3d!
This test case covers a whole bunch of edge conditions around using
templates with builtin types. Huge thank you to @tex3d for writing this
up and giving me a great basis to write fixes based on.
This test case covers a bunch of super common use cases for templates
interacting with builtin types.
=> Add additional template test case

tools/clang/test/HLSLFileCheck/hlsl/template/DependentWithBuiltinTemplate.hlsl
This test case contained some invalid HLSL (dependent typedef), and
slipped in because there was a bug in templates that allowed dependent
typedefs at the time this test was posted. The bug was fixed before the
PR was approved and merged, so we are now broken :(.
=> Removing invalid hlsl from test

include/dxc/Support/HLSLOptions.td, tools/clang/include/clang/SPIRV/FeatureManager.h, tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/include/clang/SPIRV/SpirvInstruction.h, tools/clang/include/clang/SPIRV/SpirvVisitor.h, tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/lib/SPIRV/CapabilityVisitor.h, tools/clang/lib/SPIRV/EmitVisitor.cpp, tools/clang/lib/SPIRV/EmitVisitor.h, tools/clang/lib/SPIRV/FeatureManager.cpp, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvInstruction.cpp, tools/clang/test/CodeGenSPIRV/cf.discard.to-demote.hlsl, tools/clang/test/CodeGenSPIRV/vk.1p3.discard.to-demote.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp, tools/clang/unittests/SPIRV/FileTestUtils.cpp
After getting the first review, I will send separate PRs to split it into small commits.
=> [spirv] support Vulkan1.3

azure-pipelines/Integration.GitHub-to-DXC.yml
=> Add azure pipeline entry point for integration of master and release branches

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/test/CodeGenSPIRV/type.constant-buffer.bindless.array.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [spirv] support bindless array of ConstantBuffer

CMakeLists.txt, tools/clang/tools/CMakeLists.txt, tools/clang/tools/dxil2spv/CMakeLists.txt, tools/clang/tools/dxil2spv/dxil2spvmain.cpp
Add a new dxil2spv target that can parse DXIL files containig IR or bitcode.
=> Add initial dxil2spv executable

lib/DxilPIXPasses/DxilShaderAccessTracking.cpp
Under -Od, a resource handle (passed to a function?) can be zero-initialized.
=> PIX: Handle zeroInitializer for SM6.6 resource handles.

tools/clang/tools/dxil2spv/dxil2spvmain.cpp, tools/clang/tools/dxil2spv/lib/dxil2spv.cpp, tools/clang/tools/dxil2spv/lib/dxil2spv.h, tools/clang/unittests/Dxil2Spv/FileTestUtils.cpp
Use CompilerInstance for managing diagnostics.
=> [dxil2spv] Add CompilerInstance object

lib/Transforms/Scalar/DxilEraseDeadRegion.cpp, tools/clang/test/HLSLFileCheck/passes/EraseDeadRegion/bigger_dead_loop.hlsl, tools/clang/test/HLSLFileCheck/samples/d3d11/TessellatorCS40_NumVerticesIndicesCS.hlsl, tools/clang/test/HLSLFileCheck/samples/d3d11/TessellatorCS40_TessellateIndicesCS.hlsl
- Replaced the self-loop code with simplifying more general loops.
- Made some safety checks more general.
- Changed some tests to explicitly use values produced by loops that don't get used so the loops don't get deleted.
=> Taught DxilEraseDeadRegion to handle more general loops.

lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp, lib/DxilPIXPasses/DxilDebugInstrumentation.cpp, tools/clang/test/HLSLFileCheck/pix/DebugDS.hlsl, tools/clang/test/HLSLFileCheck/pix/DebugHS.hlsl
Cherry-pick from master:
PIX: avoid crash on enumerated types without int base type (#4254)
PIX: Shader debugging instrumentation for HS+DS (#4251)
=> PIX: Cherry-pick: DS/HS debugging, enum types crash fix

tools/clang/unittests/HLSL/ExecutionTest.cpp
Don't free D3D12 module just after setting modes that will be lost if unloaded.
=> Enable Agility SDK from execution test arguments.

tools/clang/unittests/HLSL/CompilerTest.cpp, tools/clang/unittests/HLSL/ExecutionTest.cpp
We need to investigate what is going on.
=> Disable tests that have issues on ARM64

tools/clang/unittests/HLSL/ExecutionTest.cpp
Writes sample values to a RWTexture2DMS that are the sample index plus 1
in the shader. It copies that data to an output UAV in a separate shader
then reads it back and verifies that it matches.
Incidentally cleans up some of the DX12 utility functions and comments
=> ExecutionTest for Writable MSAA

tools/clang/include/clang/SPIRV/SpirvBuilder.h, tools/clang/lib/SPIRV/SpirvBuilder.cpp, tools/clang/test/CodeGenSPIRV/spirv.string.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Still need to add test.
Fixes #4360
=> [SPIR-V] Add support for empty string

tools/clang/unittests/HLSL/ExecutionTest.cpp
This introduces the correct mechanism for creating resources that might
be cast to a different format of the same bit size when enhanced
variables are found to be available. It also limits the formats to those
that are natively castable unless the relaxed format casting feature is
available.
To allow this, the resource creation utility function now has the
ability to provide these potential casting targets if supported, new
queries for these features are added, and some of the formats were shuffled
to make it easier to isolate the relevant ones.
Also, retreive advanced tex ops caps bits from from proper options struct
The previous implementation drew from options13, but the settings ended
up on options14
=> Align RawGather Exe Test with dependencies

tools/clang/unittests/HLSL/ExecutionTest.cpp
The previous implementation had some parameters out of place
=> Fix new resource creation in rawgather test

include/dxc/Support/d3dx12.h, tools/clang/unittests/HLSL/ExecutionTest.cpp
The previous usage of createCommittedResource3 had a parameter of the
incorrect type too
=> Refix new resource creation in rawgather test

tools/clang/tools/dxil2spv/dxil2spvmain.cpp, tools/clang/tools/dxil2spv/lib/dxil2spv.cpp, tools/clang/tools/dxil2spv/lib/dxil2spv.h
Add some missing error checking for possible nullptrs, and use result of
diagnostic client for setting a succes/failure return value.
=> [dxil2spv] Add additional error checking

lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp, tools/clang/test/HLSLFileCheck/hlsl/functions/return_type/array/lib_function.hlsl
=> Fix memcpy replacement removing memcpy to output argument

lib/DxilDia/DxcPixLiveVariables.cpp, lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp, tools/clang/unittests/HLSL/PixTest.cpp
Co-authored-by: Jeff Noyle <jeffno@ntdev.microsoft.com>
=> PIX: Changes to operate on libraries (#4555)

lib/DxilPIXPasses/DxilPIXMeshShaderOutputInstrumentation.cpp
Co-authored-by: Jeff Noyle <jeffno@ntdev.microsoft.com>
=> PIX: MeshShaderOutput: Disambiguate meshlets in no-AS case (#4579)

include/dxc/Support/HLSLOptions.h, include/dxc/Support/HLSLOptions.td, lib/DxcSupport/HLSLOptions.cpp, tools/clang/tools/dxclib/dxc.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp, tools/clang/unittests/HLSL/OptionsTest.cpp
/P will write to InputFile.i
/P -Fi filename will write to filename.
/P filename still work with hack.
=> Change /P to match cl.exe /P behavior.

include/dxc/DxilCompression/DxilCompression.h, include/dxc/DxilCompression/DxilCompressionHelpers.h, lib/CMakeLists.txt, lib/DxilCompression/CMakeLists.txt, lib/DxilCompression/DxilCompression.cpp, lib/DxilCompression/LICENSE.TXT, lib/DxilCompression/LLVMBuild.txt, lib/DxilCompression/miniz.c, lib/DxilCompression/miniz.h, lib/LLVMBuild.txt, tools/clang/tools/dxcompiler/CMakeLists.txt, tools/clang/tools/dxcompiler/dxcshadersourceinfo.cpp
Refactor the zlib compression code into its own library. This does not change functionality, just a refactor to prepare for further work. No new tests needed.
=> Pulled the zlib compression code into a library

include/dxc/DxilContainer/DxilContainer.h, include/dxc/DxilContainer/DxilRuntimeReflection.h, include/dxc/DxilContainer/RDAT_Macros.inl, include/dxc/DxilContainer/RDAT_PdbInfoTypes.inl, include/dxc/DxilPdbInfo/DxilPdbInfoWriter.h, include/dxc/dxcapi.h, lib/CMakeLists.txt, lib/DxilPdbInfo/CMakeLists.txt, lib/DxilPdbInfo/DxilPdbInfoWriter.cpp, lib/DxilPdbInfo/LLVMBuild.txt, lib/LLVMBuild.txt, tools/clang/tools/dxcompiler/dxcpdbutils.cpp, tools/clang/unittests/HLSL/CompilerTest.cpp
- Added new PDBI part for PDBs to eventually replace SRCI
- Added new IDxcPdbUtils2 that can read PDBI
- Removed all functionalities to do with GetFullPDB (and its tests)
=> Added new DxilPDBInfo definition

tools/clang/unittests/HLSL/AllocatorTest.cpp
This test relies on a stack allocation remaining live after the scope of an if block that it is allocated in... Clearly no good.
=> [NFC] Fix asan error in test case

tools/clang/unittests/HLSL/ExecutionTest.cpp
This change avoids dependency on DXIL container helper functions defined in DxilContainer.cpp.
=> IsNormalTest: Use IDxcContainerReflection interface

utils/FileCheck/FileCheck.cpp
Merge from https://github.com/llvm/llvm-project/commit/fd557cb01f8ddf21202b3330f4d58d3c02912b72#diff-216ac5edd1cbc96da1241dc98b8d114529a874800aac4622871dbc99d16892d7
=> Add check-prefixes support for FileCheck.

lib/DXIL/DxilMetadataHelper.cpp
=> Fix hitgroup meta data mix-up

utils/hct/hcttestcmds.cmd
Fix problem with expression under :failed subroutine, and preserve Failed variable on endlocal in :cleanup subroutine.
Use environment variable HLSL_TESTCMD_CLEANUP_ON_FAILURE to drive whether hcttestcmd cleans up temporary files on failure. Defaults to 1 (true) unless it's already set.
You can set it to 0 to disable cleanup when the test fails.
Fix originally intended behavior for -Vi test and check files for cleanup.
=> hcttestcmds: Fix error handling and support skip cleanup on failure

lib/Support/Windows/Program.inc
Merge https://github.com/llvm/llvm-project/commit/87780300f624e5437aee0c5a2d7ca30ea87b5ba2 to fix test issue where not.exe cannot find file.exe in https://github.com/microsoft/DirectXShaderCompiler/blob/main/tools/clang/test/DXC/embed_dbg.test#L4
=> Fix issue sys::findProgramByName cannot find exe on path

lib/DxilPIXPasses/DxilDebugInstrumentation.cpp
The previous formulation had a single member variable for several Values which would be used in multiple functions of a lib, which of course means that in all but one of those functions, the Values' creation function was not the right one. Funnily enough, I had got this right in the access-tracking pass but somehow neglected to do it in the debugging pass. (Also need to audit the other passes to make sure I haven't been repeating the mistake.)
=> Pix: Debug instrumentation: Create values per-function (#4976)

tools/clang/lib/CodeGen/CGExprAgg.cpp, tools/clang/lib/Sema/SemaOverload.cpp, tools/clang/test/HLSLFileCheck/hlsl/classes/this_cast_to_base_class.hlsl
Copy will be generated from this to tmp base class ptr.
=> Support this cast to base class.

tools/clang/include/clang/AST/HlslTypes.h, tools/clang/lib/AST/HlslTypes.cpp
This code is completely dead and unused.
=> [NFC] Delete dead code

include/dxc/HLSL/DxilGenerationPass.h, lib/HLSL/DxilPreparePasses.cpp, tools/clang/test/HLSLFileCheckLit/passes/dxil/dxilfinalize/illegal_metadata.ll, tools/opt/opt.cpp
To fix validation error when noinline enabled.
Also add DxilModuleInit init pass for opt to test pass which require dxil module exist.
=> Remove dx.temp metadata.

tools/clang/tools/dxopt/dxopt.cpp
=> Fix opt.exe external lib loading

tools/clang/lib/Lex/Pragma.cpp, tools/clang/test/HLSL/pragma-region.hlsl, tools/clang/unittests/HLSL/VerifierTest.cpp
Add the pragma region handler to the HLSL pragma handlers list.
Fixes #676
Sorry for the slow turn around time.
=> Add #pragma region support

tools/clang/include/clang/Basic/LangOptions.h, tools/clang/include/clang/Frontend/CodeGenOptions.h, tools/clang/lib/CodeGen/CGHLSLMS.cpp, tools/clang/tools/dxcompiler/dxcompilerobj.cpp
This is for use the information in Sema.
=> Move HLSLDefaultRowMajor to LangOptions.

test/Transforms/lit.local.cfg, tools/clang/test/HLSLFileCheck/passes/llvm/globalopt/alias-used.ll
This is just a test addition to be picked up by our current test runners. Please note it should be deleted when the original location is supported.
Original PR: https://github.com/microsoft/DirectXShaderCompiler/pull/5209
=> Adding test as a copy into currently supported testsuite (for PR #5209)

tools/clang/tools/dotnetc/EditorForm.cs
This will allow dump ast to add option like -HV 2021.
=> [dndxc] Add option when dump ast.

tools/clang/test/HLSLFileCheck/pix/InvocationsLog_ClosestHit.hlsl
A test for the DXR invocations log pass
=> WinPIX: File-check test for new DXR invocations log pass

tools/clang/test/CodeGenSPIRV/type.struct.empty-struct.array-stride.hlsl
This was introduced from an out-of-date PR.
=> [NFC] Fix RUN line in SPIR-V test

include/dxc/Support/HLSLOptions.h, lib/DxcSupport/HLSLOptions.cpp
Make HLSLOptions getter methods const
=> Make HLSLOptions getter methods const

include/llvm/ADT/DenseMap.h, include/llvm/ADT/SmallPtrSet.h, lib/Support/SmallPtrSet.cpp, unittests/ADT/DenseMapTest.cpp
Continuing work from https://github.com/microsoft/DirectXShaderCompiler/pull/5329
Another 2 cherry picks. Bit bigger this time, but no changes required apart from the free->delete change as before
=> [NFC] More cherry picks in preparation of ReverseIterator changes

README.md, utils/lit/lit/TestingConfig.py
This will avoid test fail when forget to add git usr bin to PATH.
Port from https://github.com/llvm/llvm-project/commit/0f1f13fcb17fbc8c93d505da989a04ab5cbd9ed3
=> [lit] Add git usr bin to path automatically.

include/llvm/Support/ManagedStatic.h, lib/Support/ManagedStatic.cpp
This patch is consolidated from the following upstream patches:
- llvm/llvm-project@3d5360a4398b
- llvm/llvm-project@928071ae4ef5
- llvm/llvm-project@56349e8b6d85
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/5119
=> Fix mutex use after free in llvm_shutdown

include/llvm/Support/ManagedStatic.h, lib/Support/ManagedStatic.cpp
This patch is consolidated from the following upstream patches:
- llvm/llvm-project@3d5360a4398b
- llvm/llvm-project@928071ae4ef5
- llvm/llvm-project@56349e8b6d85
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/5119
=> Fix mutex use after free in llvm_shutdown (#5463)

tools/clang/lib/SPIRV/AstTypeProbe.cpp, tools/clang/lib/SPIRV/LowerTypeVisitor.cpp, tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.array.counter.indirect2.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
This commit adds support for local arrays of RWStructuredBuffers.
=> Handle local arrays of RWStructrued buffers

tools/clang/include/clang/SPIRV/FeatureManager.h, tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/test/CodeGenSPIRV/intrinsics.sm6_6.ishelperlane.hlsl, tools/clang/test/CodeGenSPIRV/intrinsics.sm6_6.ishelperlane.vk1p3.hlsl, tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
=> [SPIRV] Add SM6.6 IsHelperLane

utils/hct/hctbuild.cmd
=> [HCT] Fix up typos, add spirv options to help msg

include/dxc/WinAdapter.h, lib/DxcSupport/WinAdapter.cpp, tools/clang/tools/dxr/dxr.cpp, unittests/DxcSupport/WinAdapterTest.cpp
=> WArgV is needed only on non-Windows platforms

include/dxc/WinAdapter.h, lib/DxcSupport/WinAdapter.cpp, tools/clang/tools/dxr/dxr.cpp, unittests/DxcSupport/WinAdapterTest.cpp
Fixes internal build break.
(cherry picked from commit f206b3d19d487d974e16d7bb41fa0cdcf79b4836)
=> WArgV is needed only on non-Windows platforms (#5576)

lib/DxilDia/DxcPixTypes.cpp
This should fix a build issue in the 2380 release branch.
=> PIX: Use CA2W in original fashion, to avoid build issue on release branch

lib/DxilDia/DxcPixTypes.cpp, lib/DxilPIXPasses/DxilAnnotateWithVirtualRegister.cpp, lib/DxilPIXPasses/DxilDebugInstrumentation.cpp, tools/clang/test/HLSLFileCheck/pix/AnnotateVirtualRegs-Raygen.hlsl, tools/clang/test/HLSLFileCheck/pix/DebugLimitedInstructionOverrides.hlsl, tools/clang/unittests/HLSL/PixTest.cpp, utils/hct/hctdb.py
=> CP: PIX: unnamed types, and debug instrumentation control

lib/HLSL/HLOperations.cpp, tools/clang/lib/CodeGen/CGHLSLMS.cpp
A number of places had if else chains to convert strings into enum values. This unapoligetically uses StringSwitch for all of them and moves one that already did in line with the rest for consistency
In HLOperations, There was a complex cascading swith on characters that was error prone. Using StringSwitch is easily maintainable and reasonably performant
This also required submitting only the substring relevant to the operation group as before it only attended to the first few characters
part of #5364
=> StringSwitch CodeGen/HLops string->enums

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/test/CodeGenSPIRV_Lit/partial.template.specialization.hlsl
=> [SPIR-V] Remove incorrect assert from Decl mapper

azure-pipelines.yml, tools/clang/tools/dxclib/dxc.cpp
Update comment for sanitizer fix in https://github.com/microsoft/DirectXShaderCompiler/pull/5851
=> [NFC] Update comment

tools/clang/test/HLSL/array-index-out-of-bounds-HV-2016.hlsl, tools/clang/test/HLSL/array-index-out-of-bounds.hlsl, tools/clang/test/HLSL/builtin-types-no-inheritance.hlsl, tools/clang/test/HLSL/conversions-between-type-shapes-strictudt.hlsl, tools/clang/test/HLSL/conversions-between-type-shapes.hlsl, tools/clang/test/HLSL/conversions-non-numeric-aggregates.hlsl, tools/clang/test/HLSL/incomplete-type.hlsl, tools/clang/test/HLSL/mintypes-promotion-warnings.hlsl, tools/clang/test/HLSL/sizeof.hlsl
Just add the missing expected-note.
This is for https://github.com/microsoft/DirectXShaderCompiler/issues/5870
=> [Test] Remove use of -verify-ignore-unexpected.

lib/Support/Unix/Signals.inc
This is a follow up to #5932
There is some extra code that isn't used that may be deleted. IT should also be deleted since it references code that has already been deleted in #5932. 
This polishes #5922
=> [UNIX] Clean up Signals.inc

tools/clang/include/clang/Basic/DiagnosticSemaKinds.td, tools/clang/lib/Sema/SemaHLSL.cpp, tools/clang/test/SemaHLSL/hlsl/objects/WaveMatrix/array_of_wave_matrix.hlsl
Report error on array of WaveMatrix types.
This is for https://github.com/microsoft/DirectXShaderCompiler/issues/5892
=> [Diag] disallow array of WaveMatrix

tools/clang/test/SemaHLSL/loop-induction-scoping-2021.hlsl, tools/clang/test/SemaHLSL/overloading-unsupported-operators.hlsl, tools/clang/test/SemaHLSL/spec.hlsl, tools/clang/test/SemaHLSL/template-diag-deferred.hlsl
Move the verify shaders which not enabled in taef to lit.
This is for #5870
=> [lit] convert verify test as lit FileCheck test part3

tools/clang/test/SemaHLSL/hlsl/workgraph/attribute_diags.hlsl, tools/clang/test/SemaHLSL/hlsl/workgraph/dispatchgrid_diags.hlsl, tools/clang/test/SemaHLSL/hlsl/workgraph/invalid_node_record_type.hlsl, tools/clang/test/SemaHLSL/hlsl/workgraph/invalid_nodelaunch.hlsl, tools/clang/test/SemaHLSL/hlsl/workgraph/member_write_diagnostics.hlsl, tools/clang/test/SemaHLSL/hlsl/workgraph/node_input_array.hlsl, tools/clang/test/SemaHLSL/hlsl/workgraph/node_input_compatibility.hlsl, tools/clang/test/SemaHLSL/hlsl/workgraph/nodeoutput_array.hlsl, tools/clang/test/SemaHLSL/hlsl/workgraph/outputcomplete_unsupported_nodeio.hlsl, tools/clang/test/SemaHLSL/hlsl/workgraph/rwnodeinputrecord_sv_dispatchgrid.hlsl, tools/clang/test/SemaHLSL/hlsl/workgraph/work-graphs.hlsl, tools/clang/test/SemaHLSL/hlsl/workgraph/zero_sized_node_record.hlsl, tools/clang/test/SemaHLSL/max_output_records_duplicate.hlsl, tools/clang/test/SemaHLSL/max_output_records_identical_duplicates.hlsl, tools/clang/test/SemaHLSL/max_output_records_invalidref.hlsl, tools/clang/test/SemaHLSL/shader_attribute.hlsl, tools/clang/test/SemaHLSL/shader_attribute_no_mismatch.hlsl, tools/clang/unittests/HLSL/VerifierTest.cpp
=> [SM68] convert workgraph verify test as lit test

tools/clang/unittests/HLSL/PixDiaTest.cpp
I had a couple of test updates that should have gone in my previous PR but got left out due to me forgetting, due to a two-week mental context switch :-). The new test adds some useful regression testing, so here it is.
=> WinPix: Inline functions test update

.github/workflows/clang-format-checker.yml
Updates the format checker action yaml to conform to our policies
=> Update format checker action

tools/clang/test/HLSLFileCheck/hlsl/objects/WaveMatrix/WaveMatrix67.hlsl
=> Add test to make sure WaveMatrix is not allowed in shader model 6.7 and 6.8

lib/HLSL/DxilValidation.cpp, tools/clang/test/CodeGenDXIL/validation/val-SampleCmpBiasGrad-shader-model-ps67.ll, tools/clang/test/CodeGenDXIL/validation/val-SampleCmpBiasGrad-shader-model-vs67.ll, tools/clang/test/CodeGenDXIL/validation/val-SampleCmpBiasGrad-shader-model-vs68.ll, tools/clang/test/CodeGenDXIL/validation/val-SampleCmpBiasGrad.ll
Add sampleCmpBias/Grad to ValidateImmOperandForMathDxilOp.  
And add validation test.
=> [SM6.8] Add validation for sampleCmpBias/Grad.

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/spv.intrinsicExecutionMode.template.hlsl
=> [SPIR-V] Evaluate arguments to ext_execution_mode

tools/clang/unittests/SPIRV/LibTestFixture.h
Add the comments that were missing from  https://github.com/microsoft/DirectXShaderCompiler/pull/6152.
=> Add member variable comments.

tools/clang/test/HLSLFileCheck/validation/val-SampleCmpBiasGrad-shader-model-ps67.ll, tools/clang/test/HLSLFileCheck/validation/val-SampleCmpBiasGrad-shader-model-vs67.ll, tools/clang/test/HLSLFileCheck/validation/val-SampleCmpBiasGrad-shader-model-vs68.ll, tools/clang/test/HLSLFileCheck/validation/val-SampleCmpBiasGrad.ll
This is to avoid test fail on old validator.
=> [SM68] add dxilver check for validation tests.

tools/clang/test/CodeGenSPIRV/meshshading.ext.optimized.hlsl
Bring SPIRV-Tools changes required to optimize code using this extension.
Fixes #6087
=> [SPIR-V] add SPV_EXT_mesh_shader to opt allowlist

tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/test/CodeGenSPIRV/using.hlsl
=> [SPIR-V] Allow `using` and `using namespace` declarations

tools/clang/lib/SPIRV/SpirvEmitter.cpp
One of the current test has an out of bounds memory access in a vector.
We access `scalars[0]` vector after all of the elements have been
removed. This is used to get the source location. The solution is to get
the source location earlier, and use the local variable.
No new test is needed because a current test exposed the problem on a
platform and build that asserts when the access happens.
=> [SPIRV] Fix out of bounds vector access

tools/clang/test/SemaHLSL/hlsl/workgraph/ast-EmptyNodeOutputArrayTypes.hlsl, tools/clang/test/SemaHLSL/hlsl/workgraph/ast-NodeOutputArrayTypes.hlsl
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/6199
=> [SM68] Add AST test for [Empty]NodeOutputArray types

tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/node-object-export-link-1.hlsl
Rewrote the test so that the test does not depend on the order that the functions appear in the module.
=> Fixed the new test depending on the order of functions in the module

tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/node-objects-metdata.hlsl, tools/clang/test/lit.cfg
This will allow lit test check dxil version to avoid running on unsupported dxil.dll.
=> [lit] Add dxil version to available_features for lit

tools/clang/test/LitDXILValidation/illegalDXILOp.ll, tools/clang/test/lit.cfg
Check dxc version and dxil version separately.
=> [lit] Simplify regex for dxil version check.

README.md, docs/BuildingAndTestingDXC.rst
This workflow has been around long enough to stop treating it as the "experimental" workflow and just update the documentation to use it.
We've gotten numerous issues lately related to problems building, so this will hopefully help.
Fixes: #5762
Related: #6151
=> [Docs] Update Readme and build instruction docs

tools/clang/unittests/HLSL/PixDiaTest.cpp
=> [ClangCL] Fix warning in PixDiaTest.cpp

.github/ISSUE_TEMPLATE/support.md
This adds a new issue template for user support issues. These are distinct from bug reports because they may not be bugs and might just be users needing help.
=> Add User Support issue template.

tools/clang/test/CodeGenSPIRV/op.pushconstant.access.bitfield.hlsl, tools/clang/test/CodeGenSPIRV/op.uniform.access.bitfield.hlsl
Our internal tests were failing due to this.
=> [SPIR-V] Fix test runline

lib/DxilContainer/DxilContainer.cpp, lib/DxilContainer/DxilContainerAssembler.cpp
=> [ClangCL] fix clang-cl build warning.

tools/clang/include/clang/AST/HlslTypes.h, tools/clang/lib/AST/HlslTypes.cpp, tools/clang/lib/Basic/TargetInfo.cpp, tools/clang/lib/Frontend/InitPreprocessor.cpp, tools/clang/lib/Sema/SemaExpr.cpp, tools/clang/test/SemaHLSL/v202x/conforming-literals/asfloat16.hlsl, tools/clang/test/SemaHLSL/v202x/conforming-literals/valid-literals.hlsl, tools/clang/tools/dxcompiler/dxcompilerobj.cpp
This change implements the conforming literals proposal as documented in proposal 0017:
https://github.com/microsoft/hlsl-specs/blob/main/proposals/0017-conform ing-literals.md
Fixes #6537
=> [202x] Implementaiton of conforming literals

docs/DXIL.rst
This patch adds documentation about string function attribute in DXIL.
=> [DOC] Add doc about string function attribute in DXIL.

docs/ReleaseNotes.md
Add initial release note for 1.8.2407.
(cherry picked from commit https://github.com/microsoft/DirectXShaderCompiler/commit/4cde6be81288039ad6b30e18b16730646401a985)
=> [Release Note] Add release note for 1.8.2407 (#6776)

tools/clang/lib/SPIRV/DeclResultIdMapper.cpp, tools/clang/lib/SPIRV/DeclResultIdMapper.h, tools/clang/lib/SPIRV/SpirvEmitter.cpp, tools/clang/lib/SPIRV/SpirvEmitter.h, tools/clang/test/CodeGenSPIRV/mesh.invert.y.hlsl
=> [SPRIV] Allow vk-invert-y for MS shaders

docs/ReleaseNotes.md
Add remove WaveMatrix in release note.
=> [DOC] update release note for remove WaveMatrix.

azure-pipelines.yml, cmake/config-ix.cmake
This is to work around LeakSanitizer issue 'LeakSanitizer has encountered a fatal error.'
For #6769
=> [Build] Update to clang-18 for linux clang pipeline

README.md
Replaced 'As of of' to 'As of'
=> Typo fix in Readme file

docs/ReleaseNotes.md
Add release notes for dxildll open sourced.
Fixes #6808
=> [Doc] Update release notes for dxil validator hash.

tools/clang/tools/libclang/CMakeLists.txt
Simplification of the code due to the fact that both blocks of the if statement are identical.
=> Both blocks of the if statement are identical.

docs/SPIR-V.rst
=> [SPIRV] Update link to inline spirv wiki

include/dxc/DXIL/DxilConstants.h, lib/DXIL/DxilOperations.cpp, utils/hct/hctdb.py
Pre-allocate opcode range to simplify merging PRs with new DXIL opcodes.
=> [SER] Reserve DXIL opcode range [258, 303)

lib/DxilValidation/DxilContainerValidation.cpp
Polishing up changes made to improve dxc buildability in different environments.
=> Shorten bool conversion, remove unneeded change

docs/SPIR-V.rst
This is all about updating urls and tables in docs/SPIR-V.rst. I'm currently working on a demo & tutorial about how to work with Vulkan+HLSL+dxc toolchain so I made this PR. Thanks a lot for your contribution to the ecosystem, and glad to see your feedback!
=> [NFC][Doc] Update HLSL to SPIR-V document

.github/workflows/clang-format-checker.yml
This time I actually tested the workflow over on this PR:
https://github.com/llvm-beanz/DirectXShaderCompiler/pull/6
=> Actually fix the changed-files workflow

docs/SPIR-V.rst
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/7176
=> Fix typo in SPIR-V.rst

tools/clang/utils/check_cfc/setup.py
Update the print statements to be compatible with Python 3
=> Update print statements to be compatible with Python 3

docs/ReleaseNotes.md
This change updates release notes with notable changes for release 1.8.2505.
Closes #7480
=> Update Release notes for 1.8.2505

include/llvm/ADT/StringExtras.h, include/llvm/CodeGen/SelectionDAGNodes.h, include/llvm/DebugInfo/DWARF/DWARFDebugRangeList.h, include/llvm/Support/LEB128.h, lib/Bitcode/Reader/BitcodeReader.cpp, lib/Bitcode/Writer/BitcodeWriter.cpp, lib/DXIL/DxilUtil.cpp, lib/Support/APFloat.cpp, lib/Support/DataExtractor.cpp, lib/Transforms/IPO/DeadArgumentElimination.cpp, lib/Transforms/InstCombine/InstCombineSimplifyDemanded.cpp, tools/clang/lib/Lex/LiteralSupport.cpp, tools/clang/lib/Sema/SemaDecl.cpp
=> [NFC] Address compiler warnings: C4146 - Cases where we can swap to using ~ operator

lib/HLSL/DxilCondenseResources.cpp, tools/clang/include/clang/Sema/Overload.h, tools/clang/lib/Format/FormatToken.h, tools/clang/lib/Sema/SemaOverload.cpp
Resolves `C33010` which is currently blocking the release pipeline.
=> [NFC] Clear C33010 Warning

lib/DxilDia/DxcPixDxilStorage.cpp, lib/DxilPIXPasses/DxilAnnotateWithVirtualRegister.cpp, lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp, lib/DxilPIXPasses/DxilDebugInstrumentation.cpp, lib/DxilPIXPasses/DxilPIXVirtualRegisters.cpp, tools/clang/test/HLSLFileCheck/pix/DbgValueToDbgDeclare_dynamic_array_index.hlsl, tools/clang/test/HLSLFileCheck/pix/Debug_dynamic_array_index.hlsl, tools/clang/unittests/HLSL/PixDiaTest.cpp, tools/clang/unittests/HLSL/PixTest.cpp
cherry picked from commit
7e0d771197110c10a39d279dc6a3c3c213c056d3
8a77b0c714d0e0db4b1c0202f2697f91ce3928a8
Original PRs:
https://github.com/microsoft/DirectXShaderCompiler/pull/7536
https://github.com/microsoft/DirectXShaderCompiler/pull/7557
=> PIX: CP of 2 fixes (dynamic indices for local arrays, and bitfields)

tools/clang/lib/SPIRV/CapabilityVisitor.cpp, tools/clang/test/CodeGenSPIRV/node.barrier.spirv-intrinsic.hlsl
=> Handles SpirvIntrinsicInstruction barriers in CapabilityVisitor.
