- docs/SPIR-V.rst
- include/dxc/Support/HLSLOptions.td
- include/dxc/Support/SPIRVOptions.h
- lib/DxcSupport/HLSLOptions.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/spv.preserve-interface.hlsl
- tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Add `-fspv-preserve-interface` CLI option to prevent DCE optimization pass from compiling out interface variables. It happens if these variables are unused.
The option may be useful when decompiling SPIR-V back to HLSL. Personally, I need it to convert DX12 shaders to DX11 ones using SPIRV-Cross as a tool for converting SPIR-V, produced by DXC, to the old shader model HLSL.
SPIR-V Tools now have a parameter in `RegisterPerformancePasses()` and `RegisterLegalizationPasses()` for this. This PR creates a new command line option in DXC and passes it to the `spvtools::Optimizer`.
Closes #4567
> [SPIRV] Add option to preserve interface variables

- lib/DxcSupport/HLSLOptions.cpp
A previous PR added this spriv option.  The default should have been false, but in the block that checks for spirv options on a non-spirv build, the default was set to true.  This broke testing on non-spirv builds.
> Fix test break on non-spirv build

- tools/clang/lib/SPIRV/DebugTypeVisitor.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/rich.debug.member.function.param.hlsl
- tools/clang/test/CodeGenSPIRV/rich.debug.type.composite.hlsl
- tools/clang/test/CodeGenSPIRV/rich.debug.type.composite.warning.hlsl
- tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
When generating debug instructions for a function, each one is linked to its scope.
In case of member functions, this scope is the class.
When declaring a class, all its member, including functions must be declared.
This cycle requires a forward reference, which is allowed by the debug instruction spec, but not by parents: NonSemantic & SPIR-V specs. This is a spec issue we have to fix. In the meantime, we decided to emit a warning, and generate slightly worse debug instructions.
Context: https://github.com/KhronosGroup/SPIRV-Registry/issues/203
> SPIRV: don't generate invalid debug instructions

- tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Updates the submodules, and disables validation on two tests. The SPIR-V
is invalid, and spir-val just started checking it. Since we have been
generating this code for a while, I do not see the need to modify the
generated code immediatly.
> Update spirv-headers and spirv-tools

- CMakeLists.txt
- include/dxc/CMakeLists.txt
- include/dxc/Support/WinFunctions.h
- include/dxc/Support/WinIncludes.h
- include/dxc/Support/microcom.h
- include/dxc/WinAdapter.h
- include/dxc/config.h.cmake
- lib/DxcSupport/CMakeLists.txt
- lib/DxcSupport/WinFunctions.cpp
- lib/DxcSupport/WinIncludes.cpp
- lib/DxcSupport/dxcmem.cpp
- projects/dxilconv/tools/dxilconv/dxilconv.cpp
- tools/clang/tools/dxclib/dxc.cpp
- tools/clang/tools/dxcompiler/DXCompiler.cpp
- tools/clang/tools/dxcompiler/dxcapi.cpp
- tools/clang/tools/dxcompiler/dxclinker.cpp
- tools/clang/tools/dxrfallbackcompiler/DXCompiler.cpp
- tools/clang/unittests/HLSL/ValidationTest.cpp
- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
- tools/clang/unittests/dxc_batch/dxc_batch.cpp
Add macro DXC_DISABLE_ALLOCATOR_OVERRIDES which, if defined, will use
the default CRT allocator for new/delete and malloc/realloc/free.
We need this on Chrome for our GN build of DXC, because our component
builds use libc++as a shared library, and we end up with mismatched
new/delete calls between libc++ and these custom overrides.
> Add macro to disable usage of allocator overrides

- lib/HLSL/DxilValidation.cpp
- lib/HLSL/WaveSensitivityAnalysis.cpp
- lib/IR/Statepoint.cpp
A recent change to libc++ added a 'struct __noop' to the 'std' namespace. When building with clang-cl using libc++ on Windows, this now introduces an ambiguity between this std::__noop struct, and the MSVC __noop intrinsic, in translation units where 'using namespace std;' is used. This commit replaces these with using clauses for the exact symbols required in the non-test cpp files.
> Remove 'using namespace std' to fix __noop ambiguity with latest libc++

- lib/DxrFallback/CMakeLists.txt
- lib/HLSL/CMakeLists.txt
- lib/Transforms/IPO/CMakeLists.txt
- lib/Transforms/Scalar/CMakeLists.txt
- tools/clang/tools/dxcompiler/CMakeLists.txt
Add LLVMHLSL dependency to LLVMIPO and LLVMScalarOpts. Remove passprinters from LLVMHLSL to avoid cycle.
This is to fix link error found when trying to enable clang_cc1.
> [Build] cleanup build dependency

- lib/HLSL/DxilLinker.cpp
- tools/clang/test/HLSLFileCheck/shader_targets/library/lib_global_ctor_with_export.hlsl
When linking to library with a list of `-exports`, the linker erases functions that are not exported assuming they are no longer used. This assumption is not correct when the function is a constructor for a global variable. This change fixes the crash by first checking whether the function still has uses before erasing.
This change adds a regression test with a non-trivially removable global variable constructor that would crash without this change.
> Fixed a crash when linker erases functions that still have users.

- tools/clang/tools/dxcompiler/dxclinker.cpp
- tools/clang/unittests/HLSL/LinkerTest.cpp
This PR aims to accomplish the final step of the task to prevent blobs compiled with different compiler versions from being linked together.
The same compiler is used to compile both blobs in the test, but the compilerversion part in the first blob is forcefully changed to conflict with the compilerversion part within the second blob.
The test detects the correct error message, which mentions the names of the two libraries that differ, and what their differing versions are exactly.
The PR aims to resolve this issue:
https://github.com/microsoft/DirectXShaderCompiler/issues/5310
> Error out if two blobs compiled with different compiler versions are linked.

- tools/clang/lib/SPIRV/AstTypeProbe.cpp
- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/type.append-structured-buffer.array.hlsl
- tools/clang/test/CodeGenSPIRV/type.consume-structured-buffer.array.hlsl
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.array.counter.const.index.hlsl
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.array.counter.flatten.hlsl
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.array.counter.hlsl
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.array.nocounter.flatten.hlsl
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.unbounded.array.counter.hlsl
- tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
This commit adds code to generate counters for single dimensional arrays
of RW,consume, and append structured buffers.
After this commit, the counter can be used if the global resource is
used directly.
> Generate counter for arrays of RW, consume, and append structured buffers.

- utils/hct/hcttest.cmd
It is not easy to pass through the quoted /p options thru python. And these options are mainly for local debug filter, not for taef FileCheck tests. Just fall back to taef for these options and treat them like taef helper.
This is help to allow lit FileCheck shell test.
> [lit] fall back to taef for taef only test options

- README.md
- utils/lit/lit/TestingConfig.py
This will avoid test fail when forget to add git usr bin to PATH.
If git usr bin already on PATH, it will just use it.
Port from
https://github.com/llvm/llvm-project/commit/0f1f13fcb17fbc8c93d505da989a04ab5cbd9ed3
> [lit] Merge git usr bin changes to release branch

- tools/clang/include/clang/AST/DeclBase.h
- tools/clang/include/clang/Sema/Sema.h
- tools/clang/lib/AST/DeclBase.cpp
- tools/clang/lib/Sema/SemaExpr.cpp
- tools/clang/lib/Sema/SemaTemplateInstantiate.cpp
- tools/clang/lib/Sema/SemaTemplateInstantiateDecl.cpp
- tools/clang/test/CodeGenSPIRV/fn.param.default.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/template/InstantiateDefaultArg.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/template/InstantiateDefaultArgMember.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/template/InstantiateDefaultArgResource.hlsl
This addresses a latent bug in Clang that was fixed _way_ after DXC was forked. We encounter it in DXC because of the way that we inject AST bits through the external sema source, but it likely wasn't exposable through C++.
This change is mostly a back porting of the following upstream LLVM commits:
llvm-project/73c6a2448f24
llvm-project/f721e0582b15
llvm-project/c601377b2376
llvm-project/4409a83c2935
The end result of this change is that we still lazily instantiate default arguments, but we do force them to be instantiated during sema when they are used.
Fixes #5145
> Instantiate argument default parameters

- include/llvm/ADT/ilist.h
- lib/DxilDia/DxcPixLiveVariables_FragmentIterator.cpp
- lib/DxilDia/DxilDiaSymbolManager.cpp
Add another template typename for pointer <-> ilist_iterator comparison operators. C++20 considers these ambiguous for the same reasons outlined in https://github.com/godotengine/godot/issues/54058
The rest of the changes are general bug fixes which are now caught by the compiler.
> Fixes to build with C++20

- CMakeLists.txt
- README.md
The SPIR-V-Tools project requires 3.17.2. To simplify our project dependencies we should just require that everywhere. 3.17.2 was released in May 2020, so it is now over three years old.
Fixes #2616.
> Update required CMake version to 3.17.2

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/DeclResultIdMapper.h
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.array.counter.const.index.hlsl
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.array.counter.flatten.hlsl
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.array.counter.indirect.hlsl
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.unbounded.array.counter.hlsl
- tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
getFinalACSBufferCounter currently returns a CounterIdAliasPair. This is
because all cases in the original design could return the entire
counter variable. When using arrays for RWStructuredBuffers, we will
need to be able to return something the represents a portion of the
array that is needed. The best method of doing that is to write reusable
functions that return a SpirvInstruction whose result is a pointer to
the approparite element of the array.
This is then used to allow copying individual counter variables.
It does not handle copying the entire array of counter variables.
> Handle passing an element of a RWStructureBuffer array to a function

- tools/clang/lib/Sema/SemaExpr.cpp
- tools/clang/test/HLSL/workgraph/member_write_diagnostics.hlsl
Issue 5372 highlighted obsolete code left over from an earlier version of work graph implementation. After investigation it is confirmed that none of the changes there are currently required, so this change reverts to the previous version of the function, and also updates the related test.
Fixes #5372
> Cleanup HLSLCheckForModifiableLValue

- tools/clang/test/CMakeLists.txt
- tools/clang/test/taef_exec/lit.cfg
- utils/hct/hctbuild.cmd
- utils/hct/hcttest.cmd
This is for support adapter option for exec test when using lit. no_priority is enabled for clang test too.
CMake behavior will be the same except not support adapter option.
Also hcttest cmd will only run cmd test for lit.
> [lit] use lit.py directly to allow send parameter to lit from hcttest

- lib/DxilContainer/LLVMBuild.txt
The dependency is necessary because DxilContainerAssembler.cpp uses llvm::CloneModule.
> Add TransformUtils dependency to DxilContainer for Linux builds

- include/dxc/Support/Global.h
- lib/DxcSupport/dxcmem.cpp
- tools/clang/tools/dxcompiler/DXCompiler.cpp
- tools/clang/tools/dxlib-sample/dxlib_sample.cpp
- tools/clang/tools/dxrfallbackcompiler/DXCompiler.cpp
Allow new/delete operators to be called before DllMain and allocator initialization in DxcInitThreadMalloc().
The operators can be called before DllMain from CRT libraries when static linking is enabled. If that happens, the new/delete operators will fallback to the standard allocator and use CoTaskMemAlloc/Free directly instead of CoGetMalloc, Alloc/Free & Release for better perf.
Enables fixing of [#5163](https://github.com/microsoft/DirectXShaderCompiler/issues/5163) and [#5178](https://github.com/microsoft/DirectXShaderCompiler/issues/5178).
> Allow new/delete operators to be called before DllMain

- tools/clang/include/clang/Basic/Attr.td
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.array.binding.attributes.hlsl
- tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
The `vk::counter_binding` binding attribute is defined to only apply to scalars because until recently arrays of RWStructuredBuffers and the like could not be arrays. That has changed, so the attribute can apply to the arrays of RWStructuredBuffers.
> Enable the vk::counter_binding attribute for arrays

- tools/clang/test/CodeGenSPIRV_Lit/lit.local.cfg
To avoid test fail when spirv build is not enabled.
> [lit] Only enable spirv lit test when spirv build is enabled.

- tools/clang/lib/SPIRV/AstTypeProbe.cpp
- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/DeclResultIdMapper.h
- tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
- tools/clang/lib/SPIRV/LowerTypeVisitor.h
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/spirv.legal.cbuffer.hlsl
- tools/clang/test/CodeGenSPIRV/spirv.legal.tbuffer.hlsl
- tools/clang/test/CodeGenSPIRV/type.constant-buffer.assign.hlsl
- tools/clang/test/CodeGenSPIRV/type.constant-buffer.bindless.array.hlsl
- tools/clang/test/CodeGenSPIRV/type.constant-buffer.return.hlsl
- tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Previously, `ConstantBuffer<T>` in variable declarations were being lowered in `SpirvEmitter`, and in all other cases in `LowerTypeVisitor`, which was improperly lowering the type. This pull request changes the existing logic so only `ConstantBuffer<T>` declarations without an initializer (ie, global declarations) are lowered in `SpirvEmitter`, and adds logic to lower `ConstantBuffer<T>` as `T` in `LowerTypeVisitor`.
This does result in two separate type declarations for `ConstantBuffer<T>`, but after legalization the output is correct in the cases I've checked.
Fixes #5401
> [SPIR-V] Handle non-global ConstantBuffer

- include/llvm/Support/Path.h
Merge upstream change
https://github.com/llvm/llvm-project/commit/91c8daf3009209a63534b4312d74322e1399bba1
In converting this over to iterator_facade_base, some member
operators and methods are no longer needed since iterator_facade
implements them in the base class using CRTP.
This is part of enable C++17.
> [C++17] Merge upsteam change for Don't use std::iterator in PATH.h

- tools/clang/test/HLSLFileCheck/d3dreflect/amp-groupshared.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/cbuf-usage-lib.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/comp-groupshared.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/empty_broadcasting_nodes.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/empty_thread_nodes.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/lib_exports1.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/lib_exports2.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/lib_exports3.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/lib_hs_export2.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/mesh-groupshared.hlsl
Some D3DReflect tests compare size values literally, when the size will change depending on the validator version.
This PR changes the literal integer in the checkline to a regex, so that the size value changing between validators won't break the test. 
Fixes  #5386
> [Test] Replace size integer literal with regex

- projects/dxilconv/test/taef/lit.cfg
- projects/dxilconv/test/taef/lit.site.cfg.in
- tools/clang/test/taef/lit.cfg
- tools/clang/test/taef/lit.site.cfg.in
- tools/clang/test/taef_exec/lit.cfg
- tools/clang/test/taef_exec/lit.site.cfg.in
- utils/lit/lit/formats/taef.py
Lit TAEF files fixes:
- Use filter parameter when enumerating tests. This enables listing of just the tests that should run, and it also filtering by architecture. This is crucial for isolating ARM64 and ARM64EC versions of tests that are in the same test dll.
- Fix verbose parameter - it was not getting applied
Related to #5489.
> Lit TAEF fixes: Use filter when listing tests and fix verbose parameter

- tools/clang/test/HLSLFileCheck/hlsl/control_flow/if_else/short-circuit-and.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/control_flow/if_else/short-circuit-or.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/control_flow/if_else/short-circuit-select.hlsl
These tests were in the wrong location so they weren't getting run. Moving them to the filecheck location enables their testing
Additionally adds an explicit HLSL 2018 parameter to the legacy behavior since HLSL 2021 has become the default now
> Enable testing HLSL 2021 short-circuit tests

- tools/clang/test/PIX/DebugAs.hlsl
- tools/clang/tools/dxopt/dxopt.cpp
When input is from stdin, need to add '\n' after each line.
This is for use dxopt to test pix passes.
opt doesn't support passes which has parameters right now. We could switch it to opt once pass parameter is supported.
> [lit] support dxopt in lit

- tools/clang/include/clang/AST/DeclCXX.h
- tools/clang/lib/AST/DeclCXX.cpp
- tools/clang/lib/CodeGen/CodeGenModule.cpp
- tools/clang/lib/Sema/SemaExpr.cpp
- tools/clang/lib/Sema/SemaExprCXX.cpp
- tools/clang/lib/Sema/SemaExprMember.cpp
- tools/clang/lib/Sema/SemaOverload.cpp
- tools/clang/lib/Sema/SemaTemplate.cpp
- tools/clang/lib/Sema/TreeTransform.h
- tools/clang/test/HLSLFileCheck/hlsl/classes/template_base_this.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/classes/this_reference_2018.hlsl
This fixes a few cases that were missed when I updated `this` objects to be references. Specifically we were still generating some implicit `this` cases as pointers, and we were not always correctly looking through the reference types.
Fixes #4709
> This is really a reference

- include/dxc/dxcapi.internal.h
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/DXC/select_samplers.hlsl
- utils/hct/gen_intrin_main.txt
- utils/hct/hctdb.py
Add any_sampler builtin parameter type. This will match any sampler type as the select() built-in added with HLSL 2021 requires.
Adds a new built-in overload that takes the any_sampler type and ensures that the last two arguments and return type match. Many of the changes were required because we never had to ensure object parameter types matched nor transmit that type to the return type before. Most of the changes to MatchArguments in SemaHLSL are addressing new issues this revealed. Non-basic types can pass the conversion check if they outright match.
Adds testing to select() and the ternary operator that it supplements for these usages
Fixes #4673
(cherry picked from commit a6497c389403adf3ab76eef8f380cc749b93d818)
> Allow select() to work with samplers (#5508)

- lib/DxilPIXPasses/DxilAnnotateWithVirtualRegister.cpp
- lib/DxilPIXPasses/DxilDebugInstrumentation.cpp
- lib/DxilPIXPasses/PixPassHelpers.cpp
- lib/DxilPIXPasses/PixPassHelpers.h
- tools/clang/test/HLSLFileCheck/pix/DebugHitGroupAndMiss.hlsl
…shaders (#5499)
Two main themes:
-Add instrumentation to the DXR hit group and miss shader types -Return a bit more info to the caller (PIX) via output text
(cherry picked from commit 3693755da61cfa419187dac56fe009e5c838a69c)
> CP: Pix changes for hitgroup/miss debugging

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
The wave matrix tests had a remaining __debug_break() call left in the code.
There was also a function that risked returning the wrong comparison value due to underflow behavior.
This PR improves the stability of the wave matrix tests by removing the __debug_break() call and preventing underflow from happening.
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/5498
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/5369
> [Wave Matrix] Improve stability of wave matrix tests

- tools/clang/lib/CodeGen/CGDebugInfo.cpp
- tools/clang/test/HLSLFileCheck/hlsl/template/templateStructFunc.hlsl
My recent changes to correct AST inaccuracies around `this` objects caused crashes in debug info generation for `this`. This resolves the crashes by making the code behave correctly when `this` is a reference.
This has no change to debug info output. The added test case should verify the same output we've always had, but is an important addition since this was not tested in our pre-merge testing.
Fixes #5530
> Fix debug info generation for `this`

- tools/clang/lib/CodeGen/CGDebugInfo.cpp
- tools/clang/test/HLSLFileCheck/hlsl/template/templateStructFunc.hlsl
My recent changes to correct AST inaccuracies around `this` objects caused crashes in debug info generation for `this`. This resolves the crashes by making the code behave correctly when `this` is a reference.
This has no change to debug info output. The added test case should verify the same output we've always had, but is an important addition since this was not tested in our pre-merge testing.
Fixes #5530
Cherry-pick of dc82ed29c9330127341f1419ac99936be369bd8f
> Fix debug info generation for `this` (#5534)

- include/dxc/HLSL/HLSLExtensionsCodegenHelper.h
- include/dxc/Support/DxcOptToggles.h
- include/dxc/Support/HLSLOptions.h
- lib/DxcSupport/HLSLOptions.cpp
- tools/clang/include/clang/Frontend/CodeGenOptions.h
- tools/clang/lib/CodeGen/BackendUtil.cpp
- tools/clang/lib/CodeGen/CGDecl.cpp
- tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp
- tools/clang/tools/dxcompiler/dxcompilerobj.cpp
Refactored -opt-enable and -opt-disable.
- Added `hlsl::option::OptimizationToggles` to manage the toggles instead of checking a `std::map`.
- All the options are moved into `hlsl::options::TOGGLE_*` constants, where each constant contains both the option's name and whether it's default on or off.
+ Previously, every check had to be either `toggles.count("my-flag") && toggles.find("my-flag")->second` for default off, and `!toggles.count("my-flag") || toggles.map.find("my-flag")->second` for default on.
+ Now, a check is simply `toggles.IsEnabled(TOGGLE_MY_FLAG)`.
> [NFC] Refactor -opt-enable and -opt-disable

- tools/clang/test/HLSLFileCheck/hlsl/template/templateStructFunc.hlsl
A recent fix (#5534) modified this test by removing the `-HV 2021` flag. That change was fine because flag is not needed now that 2021 is the default language version.
However, we have a downstream consumer of this repo where we have not yet migrated to 2021 as the default language version. Rather than modifying the test in the downstream repo it was suggested that we add the flag back in the upstream repo to minimize churn.
> Add `-HV 2021` to test that uses templates

- tools/clang/test/DXILValidation/compute_node_compatibility.hlsl
- tools/clang/test/HLSL/workgraph/node_compute_compatibility.hlsl
- tools/clang/unittests/HLSL/ValidationTest.cpp
Update both the verifier and validator tests for the node and compute compatibility errors.
The front-end error diagnostics and the validator checks for node and compute incompatibilities are already present in the preview branch. This updates both the verifier and validator test cases to make them more comprehensive.
Fixes #5346
> Update node compute compatibility tests

- tools/clang/unittests/HLSL/DxilContainerTest.cpp
- tools/clang/unittests/HLSL/FunctionTest.cpp
- tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp
These tests all build and pass on non-Windows platforms, so we should run them there too.
> Enable some tests on non-Windows

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.array.multidim.counter.error.hlsl
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.array.unbounded.counter.hlsl
- tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
I added at test for unbounded arrays. This case works, so no code changes were required.
I also added a test for multi-dimensional arrays. This case is not handled allowed in Vulkan, so I chose to issue an error. If we need to support it, we could try improve it later by transforming the array into a single dimensional array.
See https://gitlab.khronos.org/spirv/SPIR-V/-/issues/743 and https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#interfaces-resources-setandbinding.
> Add tests for multi-dim arrays and unbounded arrays

- tools/clang/unittests/HLSL/CompilerTest.cpp
On my local machine the CodeGenHashStability test takes 15 seconds to run. While that is longer than the entire rest of the test suite, it makes the full test suite run only take 17 seconds, which is still reasonable.
This change then goes a step further and breaks up the CodeGenHashStability test into multiple smaller tests. With that refactoring the full test suite drops from 17s to 10s. The end result is that enabling CodeGenHashStability costs only 1s on Release+Aserts builds.
Here is a rough breakdown of the performance impact of this change on test time for the full test suite:
```
┌───────────────┬───────────────┬───────────────┐
│               │Release+Asserts│ Debug+Asserts │
├───────────────┼───────────────┼───────────────┤
│ Before        │      9s       │      57s      │ …
```
> Enable CodeGenHashStability tests by default on all platforms

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
The IsNormal tests required an addition to the testing framework provided by ShaderOpTest.cpp, known as the MakeShaderReplacementCallback function. This function takes a shader, compiles it to DXIL, disassembles it into a string, replaces anything specified in the function parameters, and reassembles the shader back into a dxil container. The problem with the initial implementation was that after disassembling the shader, the signature applied to the shader on the compile step would be lost.
This PR adds a validation / signing step right after assembling the shader to ensure the new DXIL container has a signature. This will prevent problems with calling CreateComputePipelineState due to a missing signature.
Verified that this fails when disabling experimental mode, and passes only when …
> [ExecutionTests] Add validation and signing step to isNormal Test

- LICENSE.TXT
The root license file made reference to licenses in subdirectories. This change brings those licenses into the root file.
This changes nothing about licensing legally, but simply makes the license more clear. This is required for Google to be able to ship DXC as part of Chrome.
> Inline sub-licenses into root license file

- cmake/modules/AddLLVM.cmake
- tools/clang/unittests/HLSL/CompilerTest.cpp
Enable Exception for ClangCL.
Disable the DivByZero exception test for ClangCL.
This is for turn on ClangCL build.
> [ClangCL] exception related fix for ClangCL

- lib/DxilDia/DxcPixDxilDebugInfo.cpp
- tools/clang/unittests/HLSL/PixTest.cpp
The comment from the checkin kinda says it all:
// DINamespace has a getScope member (that hides DIScope's)
// that returns a DIScope directly, but if that namespace
// is at file-level scope, it will return nullptr.
(The upshot of this is that you couldn't step into functions within a namespace in WinPIX's shader debugger)
> PIX: Educate debug data interface about nested namespaces

- lib/DxilDia/DxcPixDxilDebugInfo.cpp
- tools/clang/unittests/HLSL/PixTest.cpp
The comment from the checkin kinda says it all:
// DINamespace has a getScope member (that hides DIScope's) // that returns a DIScope directly, but if that namespace
// is at file-level scope, it will return nullptr.
(The upshot of this is that you couldn't step into functions within a namespace in WinPIX's shader debugger)
(cherry picked from commit c2233c6c0a528ecaf5d2d008684e08daf722d845)
> PIX: CP of "Educate debug data interface about nested namespaces (#5558)"

- CMakeLists.txt
- lib/Support/MSFileSystemBasic.cpp
- lib/Support/Process.cpp
- lib/Support/Windows/MSFileSystem.inc.cpp
- lib/Support/Windows/Mutex.inc
- lib/Support/Windows/Process.inc
- projects/dxilconv/lib/DxilConvPasses/DxilCleanup.cpp
- tools/clang/lib/Parse/ParseStmt.cpp
- tools/clang/unittests/HLSLHost/CMakeLists.txt
- utils/unittest/googletest/include/gtest/gtest-printers.h
This is for enable clang-cl build on windows.
The gtest fix is merging from
https://github.com/google/googletest/pull/1620/commits/f66ab00704cd47e4e63ef6d425ca14b9192aaebb
to work around 'operator <<' is ambiguous on DefaultPrintNonContainerTo.
> [C++17] Force C++17 when build DXC

- tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp
Compare hash0 and hash1 instead of hash0 and hash0.
> [Test] Fix typo in RunDxcHashTest

- tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
The bug that required these tests to be disabled appears to have been fixed at some point. Re-enabling validation as they now pass.
Closes #3006
> [spirv] Re-enable MeshShading tests

- include/dxc/DXIL/DxilConstants.h
- include/dxc/DXIL/DxilCounters.h
- include/dxc/DXIL/DxilShaderModel.h
- include/dxc/DXIL/DxilSigPoint.inl
- include/dxc/DxilContainer/RDAT_LibraryTypes.inl
- include/dxc/Support/FileIOHelper.h
- lib/DXIL/DxilCounters.cpp
- lib/DXIL/DxilMetadataHelper.cpp
- lib/DXIL/DxilOperations.cpp
- lib/DXIL/DxilShaderModel.cpp
- lib/HLSL/DxilSignatureValidation.cpp
- projects/dxilconv/include/Support/DXIncludes.h
- projects/dxilconv/lib/ShaderBinary/ShaderBinaryIncludes.h
- tools/clang/include/clang/AST/HlslTypes.h
- tools/clang/unittests/HLSL/DxilContainerTest.cpp
This change prepares DXC sources to be ready to clang-format. This change adds annotations to skip formatting parts of the code that will break if clang-format modifies them due to include ordering or generated C++. It also adds missing include and forward declarations where clang-formatting resulted in moving things around that caused code breakages.
> [NFC] Prepare DXC sources for clang-format

- cmake/modules/HandleLLVMOptions.cmake
Use CMAKE_CXX_STANDARD instead of -std=c++14 for linux.
Dependent on https://github.com/microsoft/DirectXShaderCompiler/pull/5520
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/5479
> [C++17] Remove std option for linux build

- include/dxc/HLSL/HLOperationLowerExtension.h
- lib/HLSL/HLOperationLowerExtension.cpp
- tools/clang/unittests/HLSL/ExtensionTest.cpp
A downstream consumer requires the use of custom function lowering using a json string as well as methods. For instance, a direct memory load not based on a resource.
> Custom extensions to enable lowering for non-resource based functions

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/test/CodeGenSPIRV_Lit/vk.location.double4.error.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/vk.location.reassigned-for-input.error.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/vk.location.reassigned-for-output.error.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/vk.location.reassigned.error.hlsl
- tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
When explicit location number assignments are used, ensure that if a variable consumes more than one Location (for example, in the case of double4) that all Locations are marked as used so that error messages are correctly emitted.
Small improvements to error messaging and fixed up existing affected tests while migrating them to LIT at the same time.
Fixes #5540
> [spirv] Prevent overlapping explicit locations

- include/dxc/Support/HLSLOptions.h
- include/dxc/Support/HLSLOptions.td
- include/llvm/IR/LegacyPassManager.h
- include/llvm/IR/LegacyPassManagers.h
- lib/DxcSupport/HLSLOptions.cpp
- lib/IR/LegacyPassManager.cpp
- tools/clang/include/clang/Frontend/CodeGenOptions.h
- tools/clang/lib/CodeGen/BackendUtil.cpp
- tools/clang/test/DXC/print-passes.hlsl
- tools/clang/tools/dxcompiler/dxcompilerobj.cpp
These match `-print-after` and `-print-after-all`, and are needed if we want the opt pipeline view to work in compiler explorer.
> Add `-print-before` and `-print-before-all` flags

- lib/DXIL/DxilUtil.cpp
- lib/HLSL/DxilGenerationPass.cpp
- lib/HLSL/HLLowerUDT.cpp
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/called_function_arg_nodeoutput.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/called_function_arg_record_object.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/case085_thread_emptynodeinput.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/member_atomics.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/member_matrix_write.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/multi_dim_array_record.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/nodeoutputarray.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/test_increment_output_count.hlsl
IsHLSLNodeIOType is supposed to capture all node object types, but was missing output record and output array types.
TranslateHLCastHandleToRes had LLVM_FALLTHROUGH in for two cases where it made no sense to fall through to the next case.
MergeGepUse is needed after lowering GetRecordPtr to collapse GEP chains that could result in intermediate multi-dimension array pointers from GEPs, which is considered an invalid DXIL type.
Updated some tests for -Od compilations.  Added a test for the multi-dim GEP case.
Some CHECKs needed specialization for -Od:
- align 4 added to load/store only with optimizations enabled
- no CSE of index/annotate node handle
- also, use CHECK-LABEL to make failure investigations easier
Fixes #5597
> Fix asserts when compiling node objects with -Od

- tools/clang/test/CodeGenHLSL/lib_cs_entry.hlsl
- tools/clang/test/CodeGenHLSL/lib_cs_entry2.hlsl
- tools/clang/test/CodeGenHLSL/lib_cs_entry3.hlsl
- tools/clang/test/CodeGenHLSL/lib_entries.hlsl
- tools/clang/test/CodeGenHLSL/lib_global2.hlsl
- tools/clang/test/CodeGenHLSL/lib_res_bound1.hlsl
- tools/clang/test/DXILValidation/atomics.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/comp-groupshared.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/dynamic_res_global_for_lib.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/intrinsics/createHandleFromHeap/dynamic_res_global_for_lib2.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/types/vector/VectorIndexingAsArgument.hlsl
- tools/clang/test/HLSLFileCheck/passes/llvm/mem2reg/undef_phi.hlsl
- tools/clang/test/HLSLFileCheck/pix/GlobalBackedGlobalStaticEmbeddedArrays_NoDbgValue.hlsl
- tools/clang/test/HLSLFileCheck/pix/GlobalBackedGlobalStaticEmbeddedArrays_WithDbgValue.hlsl
- tools/clang/test/HLSLFileCheck/shader_targets/library/lib_cs_entry.hlsl
- tools/clang/test/HLSLFileCheck/shader_targets/library/lib_cs_entry2.hlsl
- tools/clang/test/HLSLFileCheck/shader_targets/library/lib_cs_entry3.hlsl
- tools/clang/test/HLSLFileCheck/shader_targets/library/lib_entries.hlsl
- tools/clang/test/HLSLFileCheck/shader_targets/library/lib_res_param.hlsl
- tools/clang/test/HLSLFileCheck/shader_targets/library/lib_res_param_x.hlsl
- tools/clang/unittests/HLSL/CompilerTest.cpp
- tools/clang/unittests/HLSL/PixTest.cpp
The team has come to a decision that no inferences should be made on function declarations that have a numthreads attribute (specifically, inferences on whether or not the function represents a shader, or a compute shader, even). 
However, some tests exist that were written with the expectation that they would be treated as a compute shader, and they lack the compute shader attribute. This PR addresses the problem by correctly adding the compute shader attribute to the function declarations in these tests. The PR is necessary so that these tests won't fail when the inference behavior is removed. 
Fixes #5623
> [Test][NFC] Add shader stage attribute to test shaders

- tools/clang/test/CodeGenDXIL/operators/select/select_samplers.hlsl
The opcode is variable at this stage, so it shouldn't be explicit. This just replaces the CHECK lines with regex for those integers
Followon to #5525
> Make select_sampler handle different opcodes

- tools/clang/unittests/HLSL/LinkerTest.cpp
The container builder determines whether to include the version in the compiled shader library depending on the validator version. If the version is below 1.8, it won't include it and any linking is allowed. If it is 1.8 or above, the version will prevent linking with a non-versioned compile.
RunLinkWithTempReg assembled one library shader and compiled another. As such, one had a version and the other didn't. By forcing the compile to use an earlier validator version, the link is again allowed
Followup to #5378
> Require validator ver 1.7 for link without version

- CMakeLists.txt
Add CET Shadow Stack Compatible flag when building DXC to safeguard against ROP/JOP attacks.
Fixes [#5578](https://github.com/microsoft/DirectXShaderCompiler/issues/5578)
> Add CET Shadow Stack Compatible flag

- include/dxc/DxilContainer/DxilContainerReader.h
- include/dxc/DxilContainer/RDAT_Macros.inl
- include/dxc/HLSL/DxilSignatureAllocator.inl
This change fixes a few of the most awful clang-format missteps in the codebase. I'm not intending to fix all the things clang-format will do something bad with, just a few of the worst ones.
Further formatting fixups can be done after the clang-format change goes in.
> [NFC] Fix most egregious clang-format missteps

- include/dxc/DxilContainer/DxilRuntimeReflection.h
including `WinIncludes.h` here pulls in a bunch of dependencies like ATL even though we really don't need those in this header. Given that the only things we're using that include for is to use LPCWSTR and LPCVOID spellings in a way that works on both windows and unix, just expand those macros to their definitions instead.
> Avoid extra dependencies in the DxilRuntimeReflection header. NFC

- tools/clang/test/CodeGenSPIRV_Lit/binary-op.assign.image.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/binary-op.bitwise-assign.shift-left.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/binary-op.bitwise-assign.shift-right.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/binary-op.bitwise.shift-left.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/binary-op.bitwise.shift-right.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/rich.debug.scope.after.compound.statement.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/shader.debug.line.composite.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/shader.debug.line.intrinsic.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/spirv.debug.opline.composite.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/spirv.debug.opline.intrinsic.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/var.init.matrix.mxn.hlsl
Some of the names for the variables in the filecheck tests append a
series of 0s to distinguish them. That is not very readable, so this
commit replaces them with <name>_<number of zeros - 1>. That is `c_0_0`
becomes `c_1` and `p_0_0_0_0` becomes `p_3`.
> Give more meaningful filecheck names

- appveyor.yml
The whole file passthru tests were moved in #5634, so this change fixes up their paths in the appveyor test script.
> Fix Appveyor whole file test test paths

- projects/dxilconv/test/taef/lit.cfg
- projects/dxilconv/test/taef/lit.site.cfg.in
- tools/clang/test/taef/lit.cfg
- tools/clang/test/taef/lit.site.cfg.in
- tools/clang/test/taef_exec/lit.cfg
- tools/clang/test/taef_exec/lit.site.cfg.in
- utils/lit/lit/formats/taef.py
Lit TAEF files fixes:
- Use filter parameter when enumerating tests. This enables listing of just the tests that should run, and it also filtering by architecture. This is crucial for isolating ARM64 and ARM64EC versions of tests that are in the same test dll.
- Fix verbose parameter - it was not getting applied
- Enable verbose on all tests - the output is shown only when the test fails
Related to #5489.
(cherry picked from commit 96e13a0e0aa66622447a7bfe6fe091c94d1de3ac)
> Lit TAEF fixes: Use filter when listing tests and fix verbose parameter (#5494)

- test/Analysis/Delinearization/lit.local.cfg
- test/Analysis/Lint/lit.local.cfg
- test/Bitcode/lit.local.cfg
- test/MC/Markup/lit.local.cfg
- test/MC/lit.local.cfg
- test/Object/lit.local.cfg
- test/Other/lit.local.cfg
- test/Transforms/EarlyCSE/AArch64/lit.local.cfg
- test/Transforms/SimplifyCFG/AArch64/lit.local.cfg
- test/lit.cfg
- test/tools/lit.local.cfg
- test/tools/llvm-cov/lit.local.cfg
- test/tools/llvm-lit/lit.local.cfg
- test/tools/llvm-profdata/lit.local.cfg
- tools/clang/test/CodeGenHLSL/lit.local.cfg
- tools/clang/test/CodeGenSPIRV/lit.local.cfg
- tools/clang/test/DXILValidation/lit.local.cfg
- tools/clang/test/Frontend/lit.local.cfg
- tools/clang/test/HLSL/lit.local.cfg
- tools/clang/test/HLSLDisabled/lit.local.cfg
- tools/clang/test/HLSLFileCheck/lit.local.cfg
- tools/clang/test/Index/lit.local.cfg
- tools/clang/test/Index/skip-parsed-bodies/lit.local.cfg
- tools/clang/test/lit.cfg
- utils/hct/hctbuild.cmd
- utils/hct/hcttest.cmd
Improve output of DXC test runs:
- Add `-lit-verbose` option to `hctbuild` to setup lit test runs with verbose output (`hcttest` will list test names as they run)
- Hide tests that are never supported (there was over 10K of unsupported tests found by LIT discovery)
- Show warnings about non-essential tools only in LIT debug mode
- Skip over file copying and non-LIT part of `hcttest.cmd` if all requested tests have already been run
- CMD tests have been move under clang's lit tests; keep the `hcttest cmd` option for running cmd tests separately
Number of unsupported tests was reduced from 10452 to 1 if spir-v is enabled, 39 if not. The number of tests that run did not change.
(cherry picked from commit b503da7084b4200909d2a3b7dcfc18e8d2944eec)
> DXC Tests: Filter out unsupported test, add verbose option and improve output (#5537)

- lib/DxilDia/DxcPixTypes.cpp
- tools/clang/unittests/HLSL/PixTest.cpp
...and other types while I'm at it. There are tests for all of the possible unnamed types (structs, members, arrays). Don't think I can express an unnamed scalar or typededf so there's no test for those.
(This was hit in the wild while debugging a pixel shader in a WinPIX capture of a Large Well-Known Engine.)
> Pix: Fix crash getting type name of unnamed structs

- tools/clang/include/clang/SPIRV/FeatureManager.h
- tools/clang/lib/SPIRV/CapabilityVisitor.cpp
- tools/clang/lib/SPIRV/CapabilityVisitor.h
- tools/clang/lib/SPIRV/FeatureManager.cpp
- tools/clang/test/CodeGenSPIRV_Lit/capability.trimmed.o3.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/capability.untrimmed.fcgl.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/capability.untrimmed.o0.hlsl
Adds the extension `SPV_EXT_fragment_shader_interlock` and the related capabilities
- `spv::Capability::FragmentShaderSampleInterlockEXT`
- `spv::Capability::FragmentShaderPixelInterlockEXT`
- `spv::Capability::FragmentShaderShadingRateInterlockEXT`
to every shader by default, and let the `spirv-opt` capability trimming pass remove them if unnecessary.
> [SPIR-V] Add fragment interlock extension by default

- lib/DxilPIXPasses/DxilAnnotateWithVirtualRegister.cpp
- lib/DxilPIXPasses/DxilDebugInstrumentation.cpp
- tools/clang/test/HLSLFileCheck/pix/AnnotateVirtualRegs-Raygen.hlsl
- tools/clang/test/HLSLFileCheck/pix/DebugLimitedInstructionOverrides.hlsl
- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
- utils/hct/hctdb.py
Two related things:
-Move value/store annotations before instruction number annotations so that we can avoid giving instruction numbers to the allocas that the value-to-declare pass adds, since they are only there to implement PIX shader debugging and do not need to be debugged by the PIX end-user. And, otherwise, adding them messes up the instruction numbering for the next part:
-Add parameters that allow PIX to limit instrumentation to a smaller range of instruction numbers. This is a crude way to make instrumentation workable for very large (>100k or so instructions) shaders which otherwise will break the GPU driver either via out of memory or via TDRs when the instrumentation is run.
> Pix: Shader debug speedup

- tools/clang/lib/SPIRV/CapabilityVisitor.cpp
- tools/clang/lib/SPIRV/CapabilityVisitor.h
- tools/clang/test/CodeGenSPIRV_Lit/raytracing.acceleration-structure.ray_query.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/raytracing.acceleration-structure.ray_tracing.hlsl
Both the ray_query and ray_tracing extensions brings new SPIRV types. But some hardware only support one type.
This decision cannot be taken by the trimming pass as both choices could be valid, instead, we should check what extension the user needed.
What can be removed however is the logic to emit the capability. This commit also does that.
Fixes #4385
> spirv: correctly choose ray_tracing/ray_query caps

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV_Lit/intrinsics.interlocked-methods.compareexchange.reference.hlsl
This function takes a reference as 4th parameter. This was not validated by the backend, meaning we'd generate invalid SPIR-V and fail validation.
This PR adds a check to emit a fatal error if an immediate is used.
Fixes #5647
> spirv: validates parameters for InterlockedAddExch

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/intrinsics.vkrawbufferload.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/intrinsics.vkrawbufferload.error.hlsl
Before this change, the alignment argument needed to be an integer literal to be evaluated correctly at compile time. This change now makes a reasonable attempts to evaluate it if it is a constant value.
Fixes #4594
> [SPIRV] Evaluate RawBuffer alignment argument

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/intrinsics.log10.hlsl
When the spirv backend sees the log10 intrinsic, it will generate a multiple with a constant. The type of that constant is hard coded to be a float. However, if the type of the parameter is not a float, there is a type mismatch on the multiple instruction.
This commit changes that so the type of the contanst matches the scalar type of the parameter. That is, it will be a type T if the parameter is type T, a vector of type T, or a matrix of type T.
Fixes #5608
> Handle log10 with float16_t parameter

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/intrinsics.firstbithigh.64bit.hlsl
- tools/clang/test/CodeGenSPIRV/intrinsics.firstbithigh.hlsl
- tools/clang/test/CodeGenSPIRV/intrinsics.firstbitlow.64bit.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/shader.debug.line.intrinsic.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/spirv.debug.opline.intrinsic.hlsl
- tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
The SPIR-V backend was incorrectly choosing to emit either FindSMsb or FindUMsb based on whether the result type of the call expression was signed or unsigned. Since the AST result type was always unsigned (and wrapped in a cast if necessary), this meant FindSMsb was never generated. FindSMsB should however be generated when the argument type is signed. This is indicated by the HLSL intrinsic op code (firstbithigh for signed and ufirstbithigh for unsigned). The SPIR-V generated now matches the DXIL generated.
This bug was discovered while investigating #4702, so at the same time some error checking is added to make unimplemented cases explicit. Because the underlying GLSL.std.450 instructions FindSMsb, FindUMsb and FindILsB are currently limited to 32-bit width components, we now emit an …
> [spirv] Fix firstbithigh/low signedness

- tools/clang/test/CodeGenSPIRV/type.texture.hlsl
Those are not used as we compile in `-fcgl`.
> spirv: remove superfluous test lines.

- include/dxc/Support/HLSLOptions.td
The current default language version is 2021.
> Update DXC help default language version

- tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
- tools/clang/unittests/SPIRV/FileTestFixture.cpp
- tools/clang/unittests/SPIRV/FileTestFixture.h
Remove unused method for runFileTest and enable validation for all tests. This will help code review when convert to lit FileCheck test.
> [SPIRV] simplify FileTest.

- include/dxc/Support/HLSLOptions.td
The current default language version is 2021.
(cherry picked from commit 67fd9dd84e007d57235df540da93fb73c55dcb4f)
> Update DXC help default language version (#5677)

- tools/clang/tools/dxcompiler/dxclinker.cpp
- tools/clang/unittests/HLSL/LinkerTest.cpp
This change modifies the IDxcLinker::Link api to return outputs via the
IDxcResult interface. We now support getting the following outputs from the
IDxcResult returned from the call to Link
DXC_OUT_REFLECTION
DXC_OUT_SHADER_HASH
DXC_OUT_ERRORS
DXC_OUT_ROOT_SIGNATURE
Additionally, the DXC_OUT_OBJECT output will now set its name based on the `/Fo`
command line flag.
This makes the api more consistent with the Compile output and makes it easier
to access these outputs without having to crack open the dxil container.
Original patch by @tex3d. Tests added by @dmpots.
> Add outputs to the IDxcResult when linking

- include/dxc/DXIL/DxilOperations.h
- include/dxc/DXIL/DxilUtil.h
- lib/DXIL/DxilOperations.cpp
- lib/DXIL/DxilUtil.cpp
- lib/HLSL/DxilGenerationPass.cpp
- lib/Transforms/Utils/Local.cpp
- tools/clang/test/HLSLFileCheck/validation/verify_output_complete_dce.ll
Elimination of incorrect output complete calls was located in an awkward spot. The code has been moved over to DCE. 
Fixes #5363
> [DCE] Move output complete removal code later to DCE

- lib/Analysis/LazyValueInfo.cpp
When the reference 'e' to stack top is popped, the call to erase(e) reads from this now invalid reference. ASAN catches this as a container overflow. We fix this by taking a copy of the stack top instead.
Note that this was similarly fixed in upstream LLVM as well: https://github.com/llvm/llvm-project/commit/9987d983704cb3086b0275043a07c1f599d9eaad
> Fix asan container-overflow

- tools/clang/lib/Sema/SemaHLSL.cpp
Fix asan use-after-return
In cases where arg 0's template id set to one of
INTRIN_TEMPLATE_FROM_TYPE, INTRIN_TEMPLATE_VARARGS,
or INTRIN_TEMPLATE_FROM_FUNCTION), this code would erroneously index
beyond Template's size.
ASAN helped to catch this error, reporting it as a use-after-return.
> Fix asan stack use after return

- tools/clang/unittests/HLSL/LinkerTest.cpp
Require a lesser validator version for linking without version for RunLinkWithTempReg test in order to allow the test to run on older validators. 1.3 is the lowest version that supports libraries
Another follow up to #5378
> Require validator ver 1.3 for link without version

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
stringstream is defined in sstream, not strstream. Include the correct one.
> Use the correct header for stringstream

- tools/clang/unittests/SPIRV/FileTestFixture.h
This variable was never initialized so it was always whatever garbage bits were left there. I've defaulted it to `true` because a bunch of tests fail if it is set to `false`, but all tests pass if it is true.
It would be great if someone with more SPIR-V experience could take a look at this.
> [NFC] Fix ubsan failure

- include/dxc/DxilContainer/DxilRuntimeReflection.h
- include/dxc/Support/D3DReflection.h
- include/dxc/Test/D3DReflectionStrings.h
- tools/clang/tools/dxcompiler/dxcutil.h
`DxilRuntimeReflection.h` uses `size_t`, which is defined by `<cstddef>`.
`dxcutil.h` uses `hlsl::SerializeDxilFlags` by value whcih is declared in `DxilContainer.h`.
`D3DReflectionStrings.h` relies on windows tyoes like `LPCSTR`. It also includes `D3DReflection.h`, which in turn includes `d3d12shader.h` (from DirectXHeaders), which relies on basically the whole `WinAdapter.h`.
I've included `WInAdapter.h` in both `D3DReflectionStrings.h` and `D3DReflection.h` to make both headers indipendently resilient.
> [NFC] Add missing includes in reflection headers

- utils/llvm-lit/llvm-lit.in
This will make it possible to run taef test from llvm-lit.py directly
without set clang_taef_site_config and clang_taef_exec_site_config.
> [lit] set clang_taef_site_config in llvm-lit.py

- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/HLSL/shader_attribute.hlsl
- tools/clang/test/HLSL/shader_attribute_no_mismatch.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/disallow_multiple_attrs.hlsl
#5679 removed some code in the CodeGen pass that allowed node + compute, and some tests were updated. 
In this follow up PR, code is changed in the Sema pass that used to allow validation exemptions for node + compute. The appropriate tests were updated. This is an improvement to #5601
Fixes #5601
> Remove node + compute validation exemption in sema

- tools/clang/unittests/HLSL/PixTest.cpp
- tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp
A few tests were calling CompileWithDebug, passing in pointer that gets set to the debug name, but was never freed.
> Fix memory leaks of debug name in a couple of tests

- unittests/ADT/StringMapTest.cpp
The MallocAllocator originally used malloc and free, but this was changed for DXC to use operator new/delete. The test called free() on the object that is now allocated with new. Fixed the test by passing in the allocator explicitly, and destroying the object using it.
> Fix ASAN alloc-dealloc-mismatch (operator new vs free)

- unittests/Support/CommandLineTest.cpp
When StackOption is destructed, it reads the its ArgStr member, which in this test is set to local variable ArgString. Since ArgString was declared after TestOption, it would be destructed first, and thus result in a stack-use-after-scope. Fix this by swapping the declaration order.
> Fix ASAN stack-use-after-scope in unit test

- tools/clang/unittests/HLSL/FunctionTest.cpp
Test was writing to a std::vector reserved buffer with a size of 0. Fix by resizing the buffer.
> Fix ASAN container-overflow in FunctionTests

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
- Rename `Placeholder*` functions
- Rename `expectedMatrices`/`expectedLeftCols`/`expectedRightRows` variables to `matrices`/`leftCols`/`rightRow` when they are used for both the initial and the expected values
- Mark test as skipped when it is disabled by external TAEF parameter
- hide debugging-only `PrintMat` function under `#ifndef NDEBUG`
Fixes [#5371](https://github.com/microsoft/DirectXShaderCompiler/issues/5371)
> WaveMatrix tests cleanup

- projects/dxilconv/test/taef/lit.cfg
- tools/clang/test/taef/lit.cfg
- tools/clang/test/taef_exec/lit.cfg
- utils/lit/lit/formats/taef.py
The way taef tests were gathered and executed previously flattened the list of arguments to a string. This allowed the weird /select: flag to work correctly, but if any of the arguments had spaces, they were misinterpretted having lost the implicit quotes around each.
By removing the flattening, putting a space between the flag and the argument for /select: and removing the explicit quotes around that argument, the command executes properly whether there are spaces or not
Additionally added a way to detect when these commands failed since they were silently failing and skipping a large swath of testing when spaces were present.
Fixes #5719
> [lit] allow for spaces in taef commands

- tools/clang/lib/Sema/SemaOverload.cpp
- tools/clang/test/HLSL/workgraph/outputcomplete_unsupported_nodeio.hlsl
- tools/clang/test/HLSL/workgraph/outputcomplete_unsupported_nodio.hlsl
- tools/clang/unittests/HLSL/VerifierTest.cpp
This was added to address a special case where OutputComplete was expecting a templated type, but got the wrong one and gave an unhelpful "no matching function" error instead of the error more specific to the requirements of OutputComplete.
Since OutputComplete no longer takes this as a parameter and is instead a method of the object, the hack is not needed.
Also restores testing for this by `node_emptynodeinput` in
tools/clang/test/HLSL/workgraph/outputcomplete_unsupported_nodeio.hlsl
```hlsl
[Shader("node")]
[NodeLaunch("Coalescing")]
void node_emptynodeinput([MaxRecords(5)] EmptyNodeInput emptyNodeInput)
{
emptyNodeInput.OutputComplete(); // expected-error {{no member named 'OutputComplete' in 'EmptyNodeInput'}}
}
```
part of #5364
> Remove unneeded Sema equal param special case

- .github/workflows/clang-format-checker.yml
This action runs clang-format-diff on the difference between the head and the merge base to identify introductions of clang-format violtions in changed code.
> Add clang-format checker GitHub action.

- lib/Support/MemoryBuffer.cpp
ErrorOr has a implicit constructor. A move is required for construct an ErrorOr object. Then it's returned by the function. Write the construction explicit to fix the compilation on clang, and reduce the confusion.
> Fix compilation issues on clang

- cmake/modules/HCT.cmake
- lib/DXIL/DxilMetadataHelper.cpp
- lib/DXIL/DxilOperations.cpp
Clang-format determines if a header is the "main" header by looking at the header name without the last extension and matching it against the source file (with some extra handling for cuda files).
The automation generating temporary files with a `.tmp` suffix tripped this up so it wasn't matching the "main" header when sorting includes.
This corrects the issue by writing temporaries to a tmp directory instead of munging the suffix.
> [NFC] Fix clang-formatting generated sources

- lib/Support/Atomic.cpp
When cross-compiling from Linux/MacOS targeting Windows, the #include of "Intrin.h" ends up including the one from the Windows SDK because the host OS is case-sensitive, rather than "intrin.h" from the host standard library. Fix this by renaming the include with the correct case-sensitive name.
> Fix cross-compile from non-Windows to Windows

- tools/clang/unittests/HLSLExec/ShaderOpArith.xml
Add `-opt-disable sink` to HelperLaneTest shader compilation to prevent sinking of `ddx_fine`/`ddy_fine` intrinsics into flow control.
Separate issue has been filed to track down the root of the problem:
#5744: Intrinsics ddx_fine/ddy_fine should not be allowed to sink into flow control
> Fix HelperLaneTest

- .github/workflows/clang-format-checker.yml
This change _should_ fix the permissions issues and allow the PR format
checker to post comments into PRs on failure. The comments should
include the first 50 lines of the diff that clang-format produces and an
error with a link to the full log.
Unfortunately this can't really be tested until it is merged. The
`pull_request_target` event only occurs once the action is in the target
branch.
Parts of this change have been tested separately, but they haven't all
been tested together.
> Add a clang-format error to force workflow failure

- docs/DXIL.rst
- include/dxc/DXIL/DxilConstants.h
- include/dxc/DXIL/DxilInstructions.h
- include/dxc/HLSL/HLOperations.h
- include/dxc/HlslIntrinsicOp.h
- lib/DXIL/DxilOperations.cpp
- lib/HLSL/HLOperationLower.cpp
- tools/clang/test/CodeGenDXIL/hlsl/objects/texture/SampleCmpBias.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/objects/texture/SampleCmpGrad.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/objects/texture/Sample_node.hlsl
- utils/hct/gen_intrin_main.txt
- utils/hct/hctdb.py
1. Add DXIL opcode for SampleCmpBias and SampleCmpGrad.
Merged from https://github.com/microsoft/DirectXShaderCompiler/pull/5562
2. Add hlsl intrinsic for  SampleCmpBias and SampleCmpGrad.
3. Lower the intrinsic to DXIL.
This is for https://github.com/microsoft/hlsl-specs/issues/30
Fixes #5560
> Add SampleCmpBias and SampleCmpGrad

- tools/clang/test/CMakeLists.txt
- utils/hct/hcttest.cmd
Enable exec test for hcttest -all.
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/5551
> [lit] Enable exec test by default for hcttest

- .github/workflows/clang-format-checker.yml
There were a few bugs that were difficult to reproduce. The pull request branch ref needs to be fetched and checked out manually in order to get the PR diff to construct. This change also fixes formatting to get a nice diff printed of the PR output.
See an example of the error output this produces here:
https://github.com/llvm-beanz/DirectXShaderCompiler/pull/2
> Fix the clang-format workflow

- lib/Support/assert.cpp
When building with apple-clang on MacOS, we get a linker error:
ld64.lld: error: undefined symbol: llvm_assert
Because the llvm_assert implementation is missing the last parameter.
> Fix apple-clang debug build failing to link llvm_assert

- lib/DXIL/DxilMetadataHelper.cpp
- test/DXILValidation/Metadata/known_nodeio_tags.ll
- test/DXILValidation/Metadata/nodeio_tags.hlsl
- test/DXILValidation/Metadata/unknown_nodeio_tags.ll
- test/DXILValidation/lit.local.cfg
- test/lit.cfg
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/case001_dispatchgrid_shader.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/case014_getrecordcount_nodeinputarray.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/case030_outputcomplete_nodeoutput.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/case129_nodeoutputisvalid_nodeoutput.hlsl
When unrecognized metadata is encountered, it needs to be recorded so that validation will fail. Additionally, this removes the assert that was there so that the code can be tested. Asserts for code that can be encountered through potential input isn't ideal anyway.
Adds testing for the same which involves introducing dxv testing into the llvm test directory requiring enabling .ll tests for that subdirectory and enabling lit to understand %dxv.
Incidentally fixes some comments in unrelated workgraph tests that had outdated values for some of the metadata that might lead to confusion
Fixes #5609
> Indicate extra metadata with unknown nodeio tag

- .github/workflows/clang-format-checker.yml
Based on GitHubs docs, I think `GITHUB_SHA` will be the last commit from the target ref that is included in the PR's base ref. That should be the right compare point rather than `GITHUB_REF`, which would be the target branch's head ref.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-w orkflows#pull_request_target
> Use GITHUB_SHA instead of GITHUB_REF

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
Add `-opt-disable sink` to HelperLaneTest shader compilation to prevent sinking of `ddx_fine`/`ddy_fine` intrinsics into flow control.
Separate issue has been filed to track down the root of the problem: #5744: Intrinsics ddx_fine/ddy_fine should not be allowed to sink into flow control
> Fix HelperLaneTest (release branch version)

- tools/clang/include/clang/AST/HlslTypes.h
- tools/clang/include/clang/Basic/Attr.td
- tools/clang/lib/AST/ASTContextHLSL.cpp
- tools/clang/lib/AST/HlslTypes.cpp
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/ast-nodeinput.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/ast-nodeoutput.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/ast-rwnodeinput.hlsl
This change avoids the need to string match type names for node input and output types by using an unspellable AST attribute that translates the node type to an enum (and back to a string if needed).
> Don't string match node type names

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
This replaces a hand-rolled string parser with an
llvm::StringSwitch that matches full strings. This should be more resilient and maintainable.
> [NFC] Use llvm::StringSwitch

- lib/DxilDia/DxilDiaSession.cpp
- projects/dxilconv/include/DxilConvPasses/ScopeNest.h
- projects/dxilconv/lib/DxbcConverter/DxbcConverter.cpp
- projects/dxilconv/unittests/DxilConvTests.cpp
- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
- tools/clang/unittests/HLSLHost/HLSLHost.cpp
- tools/clang/unittests/dxc_batch/dxc_batch.cpp
- tools/dxexp/dxexp.cpp
1. Can't mix char* and const char*
2. Remove redundant const and std::move
3. Use standard types and macros to replace platform dependent ones
> More conforming to C++ standards

- include/dxc/Support/HLSLVersion.h
This missing include is causing some downstream build failures.
> Add missing StringRef include

- lib/DxilDia/DxcPixCompilationInfo.cpp
- lib/DxilDia/DxilDiaEnumTables.h
- lib/Support/MSFileSystemBasic.cpp
- projects/dxilconv/include/DxilConvPasses/ScopeNest.h
- projects/dxilconv/include/DxilConvPasses/ScopeNestIterator.h
- projects/dxilconv/lib/DxbcConverter/DxbcConverter.cpp
- projects/dxilconv/lib/DxilConvPasses/DxilCleanup.cpp
- tools/clang/unittests/HLSL/MSFileSysTest.cpp
- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
- tools/clang/unittests/HLSLExec/ShaderOpTest.h
1. Wrong usage of memset
2. Member initializer list in order of declaration
3. Add explicit to MSFileSystemHandle's single parameter constructors
> Fix several bugs in code

- lib/Transforms/Scalar/DxilLoopUnroll.cpp
- lib/Transforms/Scalar/DxilRemoveUnstructuredLoopExits.cpp
- tools/clang/test/HLSLFileCheck/hlsl/control_flow/attributes/unroll/unroll_switch_exit_crash.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/control_flow/attributes/unroll/unroll_switch_exit_crash.ll
- utils/hct/hctdb.py
The code to structurize loop exits assumed exiting blocks always use BranchInst and never SwitchInst. This caused a crash. This change makes the structurizer preemptively check whether this assumption is true before attempting.
> Fixed a crash in unroller when exiting blocks use switch instead of branch

- lib/DxilDia/DxcPixDxilDebugInfo.cpp
- tools/clang/unittests/HLSL/PixTest.cpp
From a customer bug report, the previous code would skip over a DISubProgram scope if that scope was contained in a DINamespace (as in the first test case herein, wherein an include file is enclosed in a namespace). This would result in DXIL being attributed to the includer file instead of the included file.
(cherry picked from commit 5adc7bcf678a39d82be532cb1c3615195e3f420d)
> WinPIX: Cherry-pick of "Find correct filename for subroutines in included headers within namespaces (#5776)"

- tools/clang/include/clang/SPIRV/AstTypeProbe.h
- tools/clang/lib/SPIRV/AstTypeProbe.cpp
- tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
- tools/clang/test/CodeGenSPIRV_Lit/type.rasterizer-ordered-buffer.unimplemented.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/type.rasterizer-ordered-byte-address-buffer.unimplemented.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/type.rasterizer-ordered-structured-buffer.unimplemented.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/type.rasterizer-ordered-texture-1d-array.unimplemented.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/type.rasterizer-ordered-texture-1d.unimplemented.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/type.rasterizer-ordered-texture-2d-array.unimplemented.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/type.rasterizer-ordered-texture-3d.unimplemented.hlsl
I meant to send this a couple weeks ago. I'll be sending in a PR soon that implements this so up to you if you think it makes sense to merge this first.
> [SPIR-V] Add error for rasterizer ordered view types

- tools/clang/include/clang/AST/HlslTypes.h
- tools/clang/lib/AST/ASTContextHLSL.cpp
- tools/clang/lib/Sema/SemaHLSL.cpp
This function is always called with `IsComplete = true`, so there is no need for this parameter.
> [NFC] Remove unneeded IsComplete parameter

- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/lib/Sema/SemaDeclCXX.cpp
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/SemaHLSL/v2021/operators/global-overload-disallowed.hlsl
HLSL 2021 can't resolve calls to global operator overloads and was never intended to support them, but it didn't error on them being declared. This change emits a diagnostic when declaring any operator outside class or struct scope so that users won't instead be greeted by less intuitive errors from overload resolution.
Fixes #5792
> Error when declaring global operator overloads

- docs/BuildingAndTestingDXC.rst
Fixing documentation code tag for BuildingAndTestingDXC.rst doc file, Lack of new line between code and content makes the code dissapear. Removed also new line escape.
Sample sh code is now visible.
Results:
> Fixing documentation code tag for BuildingAndTestingDXC.rst 

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
The IsNormal tests required an addition to the testing framework
provided by ShaderOpTest.cpp, known as the MakeShaderReplacementCallback
function. This function takes a shader, compiles it to DXIL,
disassembles it into a string, replaces anything specified in the
function parameters, and reassembles the shader back into a dxil
container. The problem with the initial implementation was that after
disassembling the shader, the signature applied to the shader on the
compile step would be lost.
This PR adds a validation / signing step right after assembling the
shader to ensure the new DXIL container has a signature. This will
prevent problems with calling CreateComputePipelineState due to a
missing signature.
Verified that this fails when disabling experimental mode, and passes
only when …
> [ExecutionTests] Add validation and signing step to isNormal Test CherryPick

- tools/clang/lib/Sema/SemaOverload.cpp
Fixes UBSAN error:
```
include/llvm/ADT/iterator.h:171:7: runtime error: applying non-zero offset 8 to null pointer
```
When ULE has no decls, `decls_begin` returns a null-ptr iterator, and
adding 1 to this pointer is undefined behaviour. We fix this by adding a
check that ULE actually has decls before doing this.
Fixes 332 of these reported from running check-all.
> Fix UBSAN error in iterator.h

- lib/DxilRootSignature/DxilRootSignatureSerializer.cpp
Fix UBSAN error:
```
lib/DxilRootSignature/DxilRootSignatureSerializer.cpp:134:5: runtime error: store to misaligned address 0x7fff812daf5f for type 'unsigned int', which requires 4 byte alignment
```
Use memcpy to write to unaligned address.
Fixes 63 of these reported from running check-all.
> Fix UBSAN error in DxilRootSignatureSerializer

- azure-pipelines.yml
Address sanitizer can detect all sorts of memory usage related bugs. Things like overflows, underflows, use-after-free, and (on Linux) leaks. Due to the great work by @amaiorano, DXC is now asan-clean in our test suite. Enabling this in our PR builds will allow us to stay that way.
I've chosen the Linux builds because the Linux runtime hooks capture more errors than on other platforms. It only runs in the Release configuration because asan can have significant runtime overhead so running it in a release configuration will mitigate that substantially. I've also changed the build to use libc++ instead of libstdc++ because the libc++ headers have additional address sanitizer annotations to catch misuses of C++ standard library containers.
> Enable asan on our Linux Release pipeline

- tools/clang/unittests/HLSL/CompilerTest.cpp
- tools/clang/unittests/HLSL/DxilContainerTest.cpp
- tools/clang/unittests/HLSL/RewriterTest.cpp
- tools/clang/unittests/HLSLErrors/HLSLErrors.cpp
- tools/clang/unittests/HLSLHost/HLSLHost.cpp
- tools/clang/unittests/dxc_batch/dxc_batch.cpp
1. remove unused variable.
2. use 1u instead 1 to avoid signed unsigned mismatch.
3. use std::size to replace _countof.
4. Use LPCWSTR/LPCSTR instead of LPWSTR/LPSTR.
> [ClangCL] fix warning for clang unit test.

- lib/DxilDia/DxcPixCompilationInfo.cpp
- lib/DxilDia/DxcPixDxilDebugInfo.h
- lib/DxilDia/DxcPixDxilStorage.h
- lib/DxilDia/DxcPixTypes.h
- lib/DxilDia/DxcPixVariables.cpp
- lib/DxilDia/DxilDiaDataSource.cpp
- lib/DxilDia/DxilDiaDataSource.h
- lib/DxilDia/DxilDiaEnumTables.h
- lib/DxilDia/DxilDiaSession.cpp
- lib/DxilDia/DxilDiaSession.h
- lib/DxilDia/DxilDiaTable.h
- lib/DxilDia/DxilDiaTableInjectedSources.h
- lib/DxilDia/DxilDiaTableLineNumbers.h
- lib/DxilDia/DxilDiaTableSourceFiles.h
- lib/DxilDia/DxilDiaTableSymbols.cpp
- lib/DxilDia/DxilDiaTableSymbols.h
- tools/clang/unittests/HLSL/PixTest.cpp
- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
1. add override for override methods.
2. remove unnecessary std::move
3. remove unused lambda capture
4. use same enum when compare.
5. fix field order in constructor.
6. add const for when cast from a const variable.
> [ClangCL] Fix warning for DxilDia

- lib/Support/MemoryBuffer.cpp
ErrorOr has a implicit constructor. A move is required for construct an ErrorOr object. Then it's returned by the function. Write the construction explicit to fix the compilation on clang, and reduce the confusion.
(cherry picked from commit c22d103059672f4a0e40cc0f1ab6a86ee0637f86)
Plus added explicit ErrorOr template argument to fix a build error
> Fix compilation issues on clang (#5683)

- lib/HLSL/DxilValidation.cpp
- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/CodeGenDXIL/hlsl/objects/texture/CalcLODWithSamplerComparison.hlsl
- tools/clang/test/SemaHLSL/hlsl/objects/texture/CalculateLODWithSamplerComparisonState.hlsl
- utils/hct/gen_intrin_main.txt
New overloads are added for CalculateLevelOfDetail and CalculateLevelOfDetailUnclamped. Also update validator to allow SamplerComparisonState for shader model higher than 6.7.
Fixes https://github.com/microsoft/DirectXShaderCompiler/pull/5183
> Allow SamplerComparisonState when CalculateLevelOfDetail

- lib/HLSL/DxilPreparePasses.cpp
- tools/clang/test/HLSLFileCheckLit/passes/dxil/dxilfinalize/illegal_metadata_lib.ll
This change makes `DxilFinalizeModule` remove `dx.temp` metadata regardless of target profile.
`DxilFinalizeModule` pass removes metadata that the validator disallows in the final DXIL. These metadata are only removed for non-lib target, however dx.temp is something that the validator does not allow even in lib target. There is no reason to keep this metadata because it's only used for inserting nops and that's not something we do when linking libraries.
> Removing dx.temp for lib target, since it's disallowed by the validator

- cmake/modules/HandleLLVMOptions.cmake
The remaining errors are non-trivial to fix, so let's disable this for now.
> Disable UBSAN sanitizing alignment errors

- include/dxc/DxilContainer/DxilContainerReader.h
- projects/dxilconv/include/DxilConvPasses/ScopeNestIterator.h
- projects/dxilconv/lib/DxbcConverter/DxbcConverter.cpp
- projects/dxilconv/lib/DxbcConverter/DxbcConverterImpl.h
- projects/dxilconv/lib/DxbcConverter/DxbcUtil.cpp
- projects/dxilconv/tools/dxbc2dxil/dxbc2dxil.cpp
- projects/dxilconv/unittests/DxilConvTests.cpp
- tools/clang/tools/dxlib-sample/lib_share_compile.cpp
1. fix order of fields in constructor.
2. fix compare warning for type mismatch by cast to same type.
3. use {} instead of {0} when initialize to all zero.
4. add override for override methods.
> [ClangCL] fix warning in DxbcConverter

- include/llvm/Support/Program.h
- lib/DxilCompression/miniz.c
- lib/HLSL/DxilContainerReflection.cpp
- tools/clang/tools/dxlib-sample/lib_share_compile.cpp
- unittests/Support/ProgramTest.cpp
1. add noexcept for methods with __declspec(nothrow)
2. add override for override methods.
3. add const when cast const ptr for a const argument.
4. change 0 to 0u for immediate to avoid signed unsigned mismatch.
> [ClangCL] Fix warning for rest part except clang.

- docs/DXIL.rst
- lib/HLSL/DxilValidation.cpp
- tools/clang/test/DXILValidation/compute_node_compatibility.hlsl
- tools/clang/unittests/HLSL/ValidationTest.cpp
- tools/clang/unittests/SPIRV/FileTestFixture.cpp
- utils/hct/hctdb.py
Update the DXIL validation for compute node compatibility, and for node input vs launch type compatibility, to make the diagnostics more informative, and update the validation tests accordingly.
Fixes #5348
> Amend compute node compatibility DXIL validation

- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/HLSL/workgraph/dispatchgrid_diags.hlsl
- check nested structs for `SV_DispatchGrid` semantics
- check base classes first before iterating through fields to improve error message locations
Related PR: #5806
> More NodeMaxDispatchGrid diagnostic fixes in Sema

- tools/clang/include/clang/Basic/DiagnosticIDs.h
- tools/clang/lib/Basic/DiagnosticIDs.cpp
- tools/clang/lib/Frontend/ASTUnit.cpp
Overflow of a diagnostic group could lead to a crash, and we just overflowed the diagnostics in the SEMA group.
This change bumps the count for SEMA and adds several checks to catch this in the future:
- static_asserts to prevent overflow of group IDs
- assert to catch invalid ID in group more clearly
- assert to catch failure of setSeverityForGroup in ASTUnit::LoadFromCommandLine
- keep crash on invalid DiagID to prevent late failure with NDEBUG
> Fix clang diagnostics overflow in SEMA group; add static_assert

- include/dxc/Support/WinIncludes.h
- include/dxc/WinAdapter.h
Header changes to make Direct3D WSL build work:
- Move non-WIN32 IMalloc definition back to `WinAdapter.h` (it was there until commit 44f88339383018d35155ff4f337ce73eefa5cb11)
- Define DEFINE_ENUM_FLAG_OPERATORS only if it was not already defined
(cherry picked from commit f14b0cc8c27e874cb0b49bbc22269e0a4cecb05b)
> Direct3D WSL build header changes (#5843)

- tools/clang/unittests/HLSLExec/CMakeLists.txt
- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
- tools/clang/unittests/HLSLExec/ShaderOpTest.cpp
- tools/clang/unittests/HLSLExec/ShaderOpTest.h
- move `GetHardwareAdapter` and `UseHardwareDevice` helper functions into `st` namespace to avoid linking conflicts
- do not define wave matrix data types if using newer `d3d12.h` that already has them
- Use `#include "d3dx12.h"` without subdirs to enable swapping of this header for a newer version in build settings
> Exec test changes to enable build inside undocked Direct3D repo

- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/HLSL/workgraph/attribute_diags.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/sparsenodes.hlsl
Recently added checks for legal attributes on node objects were incorrectly disallowing [AllowSparseNodes] on non-array outputs.
This change fixes this regression and updates the tests.
Fixes #5863
> allow [AllowSparseNodes] on non-array outputs

- include/dxc/Support/microcom.h
- include/dxc/Test/HlslTestUtils.h
- projects/dxilconv/include/ShaderBinary/ShaderBinary.h
- tools/clang/lib/CodeGen/CGBuilder.h
- tools/clang/unittests/HLSL/AllocatorTest.cpp
- tools/clang/unittests/HLSL/DXIsenseTest.cpp
- tools/clang/unittests/HLSL/LinkerTest.cpp
- tools/clang/unittests/HLSL/MSFileSysTest.cpp
- tools/clang/unittests/HLSL/Objects.cpp
- tools/clang/unittests/HLSL/OptionsTest.cpp
- tools/clang/unittests/HLSL/PixTest.cpp
- tools/clang/unittests/HLSL/RewriterTest.cpp
- tools/clang/unittests/HLSL/VerifierTest.cpp
- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
- tools/clang/unittests/HLSLExec/ShaderOpTest.cpp
- tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp
- tools/dxexp/dxexp.cpp
- utils/hct/hctbuild.cmd
1. printf format mismatch.
2. avoid cast from CComPtr<IncludeHandlerVFSOverlayForTest> to CComPtr<IDxcIncludeHandler>.
3. fix signed unsigned mismatch.
4. fix order of fields in constructor.
5. add override for override methods.
6. port https://github.com/llvm/llvm-project/commit/01f4209631f32ccec686b232039238066a0866d9
7. add copy assignment operator to avoid -Wdeprecated-copy-with-user-provided-copy
8. disable -Wignored-qualifiers for taef header WexTestClass.h.
9. remove unused fields.
10. add -clang-cl for hctbuild.
> [ClangCL] Cleanup rest clang-cl warnings

- tools/clang/lib/SPIRV/InitListHandler.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV_Lit/undefined.static.template.member.hlsl
When a variable declaration is not found, an error is emitted, and a null value returned. Not all function know what to do with that null value. I fix this by adding a few extra nullptr checks so that the compiler can unwind the stack and return gracefully.
Fixes [SPIR-V] `-Wundefined-internal` SIGSEGVs the compiler when `-spirv` output #5821
> Add nullptr checks to handle undefined arrays

- CONTRIBUTING.md
Specify the clang-format requirement in the contributing documentation.
> [Docs] Update contributing doc for clang-format

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
If `_FORCE_EXPERIMENTAL_SHADERS` is defined the execution tests will always turn on experimental mode, regardless of the `ExperimentalShaders` runtime TAEF parameter.
> Add _FORCE_EXPERIMENTAL_SHADERS define to ExecutionTests

- CMakeLists.txt
- cmake/modules/HandleLLVMOptions.cmake
- utils/hct/hctbuild.cmd
A slightly complex series of events causes invocations of hctbuild after the first to enable asserts in release builds. This sets the build type even when it isn't needed to avoid it.
Because the build type was not being set when generating for visual studio in hctbuild, when generating the cmake files using CMakeLists, it would produce an alarming message saying it was defaulting to debug, but, in fact, since it didn't care for the purposes of sln file generation, that wasn't actually a problem, just confusing. It did set a variable to enable asserts, but didn't do this for release variant builds
The real problem occurs if hctbuild is invoked again, at that point, instead of defaulting to Debug, it leaves the build type empty because of another variable set in the cache.
Additionally, …
> Make hctbuild cmake gen consistent with asserts

- include/dxc/HlslIntrinsicOp.h
- lib/HLSL/HLOperationLower.cpp
- utils/hct/gen_intrin_main.txt
The ImplicitRecordToStructCast intrinsic is left over dead code that should be removed. This PR removes the intrinsic from existence. Partially addresses https://github.com/microsoft/DirectXShaderCompiler/issues/5351
> Remove implicit record to struct cast intrinsic

- CMakeLists.txt
- cmake/modules/HandleLLVMOptions.cmake
- utils/hct/hctbuild.cmd
The previous PR #5881 didn't do what it meant to and had a lot of debug code due to a mistaken commit. This reverts that commit and restores the setting of the build type flag
> Revert mistaken debug changes to hctbuild

- lib/DXIL/DxilSignatureElement.cpp
- tools/clang/unittests/HLSL/DxilModuleTest.cpp
When DxilModule metadata is serialized, semantic strings for system values are canonicalized.  If these strings are used anywhere, this can lead to a difference in behavior between an original DxilModule that has not undergone serialization and one that has been deserialized.
This change canonicalizes the string as soon as a DxilSignatureElement is created, thereby removing the possibility of accidentally relying on the non-canonical string for a system value.
> Make DxilSignatureElement::m_SemanticName canonical for system values

- azure-pipelines.yml
hcttest noexec will execute clang tests.
Clang tests include both spirv lit tests and unit tests. So running hcttest spirv_only is redundant.
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/5890
> [CI] Remove redundant SPIRV tests run for Windows pipeline

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV_Lit/operator.overloading.subscript.hlsl
In order to handle types such as `RWStructuredBuffer`, which has the method `operator[]()`, `operator[]` is treated as a special case by our access chain creation code - it's treated similarly to `ArraySubscriptExpr`. This has the unfortunate side effect that user-defined `operator[]` overloads are not called in all cases.
To fix this, this PR adds a check for whether a type is user-defined before handling `operator[]` in `collectArrayStructIndices`.
Part of the fix for #5638.
> [SPIR-V] Correctly handle subscript overload in access chain

- include/llvm/ADT/Triple.h
- lib/Transforms/InstCombine/InstCombineAndOrXor.cpp
- test/HLSL/passes/instcombine/disable-bswap-match.ll
DXIL doesn't support the bswap intrinsic, normally a backend would lower this intrinsic to something else, in this case we don't have a backend so we just end up generating invalid DXIL.
The solution here is to disable bswap matching when targeting DXIL.
Fixes #5104
> [Instcombine] Disable bswap match for DXIL

- include/llvm/IR/Operator.h
- lib/DXIL/DxilUtilDbgInfoAndMisc.cpp
- lib/Transforms/Scalar/LowerTypePasses.cpp
- test/HLSL/passes/multi_dim_one_dim/gep_addrspacecast_gep.ll
- tools/clang/test/CodeGenDXIL/ByteAddressBuffer/store_groupshared_struct_with_array.hlsl
This commit fixes a crash in the compiler when lowering a groupshared variable with a multi-dimensional array type. The root cause of the bug was that we had a nested gep expression that could not be merged into a single gep because of an intervening addrspacecast.
The `MultiDimArrayToOneDimArray` pass flattens the multi-dimension global variables to a single dimension. It relies on the `MergeGepUse` function to flatten any nested geps into a single gep that fully dereferences a scalar element.
The fix is to modify the `MergeGepUse` function to look through addrspacecast instructions when trying to merge geps. We can now merge geps like
gep(addrspacecast(gep(p0, gep_args0)) to p1*, gep_args1)
into
addrspacecast(gep(p0, gep_args0+gep_args1) to p1*)
We also added a call to …
> [bug] Fix crash when lowering multi-dimension groupshared variable

- tools/clang/test/CodeGenSPIRV_Lit/decoration.no-contraction.stage-vars.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/decoration.no-contraction.struct.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/decoration.no-contraction.variable-reuse.hlsl
These tests are failing in our downstream builds after migrating to Lit due to CHECK-NOTs referencing variables before they are defined. Those CHECK-NOTs have now been replaced with an `--implicit-check-not` that checks that there are no `OpDecorate ... NoContraction` instructions other than those CHECKed in the test.
> [SPIR-V] Fixup tests failing downstream

- tools/clang/test/CodeGenSPIRV_Lit/raytracing.khr.closesthit.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/raytracing.khr.closesthit.vulkan1.1spirv1.4.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/raytracing.nv.anyhit.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/raytracing.nv.closesthit.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/raytracing.nv.enum.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/raytracing.nv.library.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/raytracing.nv.raygen.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/unsupported/rayquery_init_rgen.hlsl
CHECK-COUNT-# was not yet implemented in the version of FileCheck used in DXC, so these lines were not checked at all. Switching them to CHECKs caused the tests to fail, so they're now replaced with a combination of a CHECK and CHECK-NOT that pass.
This was caught by the downstream test runner that uses a newer version of FileCheck which does check CHECK-COUNTs.
> [SPIR-V] Remove invalid CHECK-COUNTs

- lib/Support/Unix/Signals.inc
While theoratically required in pre-C++11 to avoid re-allocation upon call, C++11 guarantees that c_str() returns a pointer to the internal array so pre-calling c_str() is no longer required.
llvm-svn: 242983
> Remove unnecessary in C++11 c_str() calls

- utils/hct/ExtractIRForPassTest.py
The default generated RUN line generated by ExtractIRForPassTest.py adds the desired pass to the options, but forgot to add the '-', so it would fail with difficult to diagnose error in dxopt during argument parsing.
This adds the missing '-' so the RUN line doesn't have to be fixed in this way every time the script is used.
> Add missing '-' for pass in ExtractIRForPassTest.py

- lib/Transforms/Scalar/DxilRemoveDeadBlocks.cpp
- tools/clang/test/HLSLFileCheck/passes/dxil/dxil_remove_dead_pass/delete_constant_dce.ll
DxilRemoveDeadBlocks assumed it could run with an uninitialized DxilModule, because the test case had been captured from live state without the needed DXIL metadata. DxilRemoveDeadBlocks relies on DxilValueCache, which relies on code in DxilSimplify, which assumes we have a DxilModule if there are dxil ops. Without an initialized DxilModule with the correct low-precision mode, cached ops and types may be wrong.
This change:
- modifies DxilRemoveDeadBlocks to remove bSkipInit
- updates the test to contain the metadata needed to initialize DxilModule
> Make DxilRemoveDeadBlocks init DxilModule, fix test

- lib/Support/Unix/Signals.inc
While theoratically required in pre-C++11 to avoid re-allocation upon call, C++11 guarantees that c_str() returns a pointer to the internal array so pre-calling c_str() is no longer required.
llvm-svn: 242983
---------
> Remove unnecessary in C++11 c_str() calls (#5932)

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV_Lit/ddx.compute.hlsl
This commit adds the execution mode to compute shaders when derivatives
are used. I only added a single test because the derivatives are all
handled in one place. The choice of execution mode was tested using the
implicit LOD instructions.
> Add execution mode for derivatives in compute shaders

- tools/clang/include/clang/Basic/Attr.td
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/CodeGenSPIRV_Lit/spv.inline.executionmode.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/spv.inline.executionmode.undefined.hlsl
Implements `vk::spvexecutionmode` from https://github.com/microsoft/hlsl-specs/blob/main/proposals/0011-inline-spirv.md#execution-modes.
> [SPIR-V] implement vk::spvexecutionmode attribute for inline SPIR-V

- include/dxc/dxcpix.h
- lib/CMakeLists.txt
- lib/DxilDia/CMakeLists.txt
- tools/clang/unittests/HLSL/CMakeLists.txt
- tools/clang/unittests/HLSL/PixTest.cpp
DxilDia is enabled for Linux with only DxcPixLiveVariables_FragmentIterator enabled for PixTest.
Enabled PixTest for Linux build.
This is for #5877
> [Linux] Enable PixTest for Linux

- include/dxc/DXIL/DxilOperations.h
- lib/DXIL/DxilModule.cpp
- lib/DXIL/DxilOperations.cpp
- lib/HLSL/HLModule.cpp
- tools/clang/lib/CodeGen/CGHLSLMS.cpp
- tools/clang/test/DXILValidation/val-dx-type-lowprec.ll
- tools/clang/test/DXILValidation/val-dx-type-minprec.hlsl
- tools/clang/test/DXILValidation/val-dx-type-minprec.ll
- tools/clang/unittests/HLSL/ValidationTest.cpp
Fix module loading and validation issues
There are a couple interacting issues:
1. When RefreshCache occurs, it doesn't fill in the m_pResRetType cache.
- This is because in GetOpFunc, if it finds a function matching the
expected name, it simply returns that, skipping function type
construction.
- This causes a validation error if CheckAccessFullyMapped is validated
before a function that calls it.  This depends on the order of
function declarations/definitions in the module.
- The solution is to move the check after type construction, and verify
that the function type matches expectations as well.
2. When RefreshCache() and FixOverloadNames() was called from DxilOperations
constructor, the m_LowPrecisionMode has not yet been set, leading to
incorrect overload types when allowing function …
> Fix module loading and validation issues

- include/dxc/DXIL/DxilConstants.h
- include/dxc/DxilContainer/DxilRuntimeReflection.h
- include/dxc/DxilContainer/RDAT_LibraryTypes.inl
- include/dxc/DxilContainer/RDAT_SubobjectTypes.inl
- include/dxc/Test/DumpContext.h
- lib/DxilContainer/DxilContainerAssembler.cpp
- lib/DxilContainer/RDATDumper.cpp
- tools/clang/test/HLSLFileCheck/d3dreflect/amp-groupshared.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/cbuf-usage-lib.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/comp-groupshared.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/empty_broadcasting_nodes.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/empty_thread_nodes.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/lib_exports1.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/lib_exports2.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/lib_exports3.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/lib_hs_export2.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/mesh-groupshared.hlsl
- Reorganize part and table IDs to move shader info after ver 1.8
- Move NodeShaderInfo into RuntimeDataFunctionInfo2 shader info union, since it is mutually exclusive with other shader types
- Remove RuntimeDataFunctionInfo3
- Re-organize RDAT_LibraryTypes into 3 sections by versioning
- Format unformatted section of RDAT_LibraryTypes due to typo
- Add indentation to make definitions easier to read and disable clang-format for RDAT_LibraryTypes.inl and RDAT_SubobjectTypes.inl
- Include Node in ShaderStageFlags for 1.8+
- Added some explicit scopes due to VS IDE thinking they were ambiguous
- RDATDumper: Don't try to visit or print null records
- Fix reflection tests:
- tests meant to check shader info use: -Vd -validator-version 0.0
- use regex for record strides for versioning …
> Fix RDAT table versioning for ver 1.8

- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/HLSL/workgraph/dispatchgrid_diags.hlsl
- tools/clang/test/SemaHLSL/hlsl/workgraph/dispatch_grid.hlsl
verify that the input record field with SV_DispatchGrid semantic is a valid type: 32 or 16-bit uint scalar or array/vector with up to 3 components.
Fixes #5845
> [Diag] report error when SV_DispatchGrid has illegal type.

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/test/CodeGenSPIRV_Lit/image.format.incompat.type.r64i.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/image.format.incompat.type.r64ui.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/image.format.incompat.type.rgba32f.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/image.format.incompat.type.rgba32i.float.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/image.format.incompat.type.rgba32i.uint.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/image.format.incompat.type.rgba32ui.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/vk.attribute.image-format.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/vk.attribute.image-format.o3.hlsl
This adds an error when the OpImageType create would violate the
requirements in
https://docs.vulkan.org/spec/latest/appendices/spirvenv.html#spirvenv-format-type-matching.
Fixes #5955
> Add error message for incompatible image format and sampled type.

- tools/clang/tools/libclang/dxcrewriteunused.cpp
Reorder the GetStatus check that earlies out of the function before creating a MemBufferCopy, otherwise it leaks upon early out.
This is a quick fix, but not the ideal one. The unique_ptr<MemoryBuffer> gives the false impression that the buffer will be automatically cleaned up; however, MemoryBuffer is just a pair of string and raw pointer to a buffer, so no cleanup occurs. Indeed, there's no real need for unique_ptr at all here. The ASTUnit::RemappedFile is passed down a chain of functions until SetupCompilerCommon is called, where the buffer is passed to compiler.getPreprocessorOpts().addRemappedFile, where ownership is established. Ideally, a unique_ptr to the buffer would be passed down, safely transferring ownership so that if an error occurs, no memory is leaked. This will be for …
> Fix ASAN leak in HLSL/ClangHLSLTests/RewriterTest.RunSpirv

- tools/clang/unittests/HLSL/PixTestUtils.cpp
PixStructAnnotation tests were converting an IDxcBlobEncoding to a std::string, but this isn't valid if the underlying object is an InternalDxcBlobEncoding_Impl, which holds a buffer that may not be null-terminated. Fix this by using the BlobToUtf8 helper, which handles this case gracefully.
Fixes 23 ASAN failures.
> Fix ASAN heap-buffer-overflow in PixTests

- azure-pipelines.yml
Two commits:
azure-pipelines: Use 'lld' linker for Linux builds
This should speed up the total build time using a faster linker.
azure-pipelines: Add verbose flag to LLVM_LIT_ARGS
With `--xunit-xml-output` set, stderr is not fed to stdout, so we cannot
easily see the errors in the build log. The errors only appear in the
pipeline's "Test" tab. Adding the verbose flag allows it to also output
stderr to the log.
> Improve pipeline build

- azure-pipelines.yml
Two commits in this one:
azure-pipelines: Fix ASAN not being enabled on Linux bot
Unfortunately, the following CL did not correctly spell out the CMake
variable to enable ASAN properly:
https://github.com/microsoft/DirectXShaderCompiler/pull/5799
This commit fixes that.
azure-pipelines: disable ASAN alloc_dealloc_mismatch checks
We are currently hitting false positives because of this. See the issue
I opened: https://github.com/microsoft/DirectXShaderCompiler/issues/5971
Perhaps a future Linux image will include a build of libc++ that does
not exhibit this false positive, at which point this workaround can be
reverted.
> Fix enable asan on pipeline

- azure-pipelines.yml
Now that all UBSAN issues have been fixed, we can enable UBSAN checks on our CI.
> azure-pipelines: Enable UBSAN on Linux_Clang_Release

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV_Lit/intrinsics.dot4add.hlsl
This change implements the translation of the two DP4a intrinsics into pairs of operations:
```
dot4add_i8packed -> OpSDot + OpIAdd
dot4add_u8packed -> OpUDot + OpIAdd
```
Note that the `OpSDotAccSat` and `OpUDotAccSat` operations are not matching the HLSL intrinsics as there should not be any saturation.
The SPIR-V test for these intrinsics is also updated by copying and adjusting the corresponding test from the DXIL side.
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/4528
> [SPIRV] Implement dot4add_i8packed and dot4add_u8packed intrinsics

- include/dxc/DxilContainer/RDAT_LibraryTypes.inl
- include/dxc/DxilContainer/RDAT_SubobjectTypes.inl
Turn off clang formatting for `RDAT_LibraryTypes.inl` and `RDAT_SubobjectTypes.inl`. Macro indentation makes these files easier to read.
This PR was created in 2 steps:
1. `RDAT_LibraryTypes.inl` and `RDAT_SubobjectTypes.inl` were reverted to the version `64348c7e~1` The commit 64348c7eec9d4c966797c7ba73da2f499d0242e8 is the first that started preparing the code base for clang formatting. Except for that there were no functional commits done to these files since then.
2. `//clang-format off` and a comment with explanation was added to the top of these files
> Turn off clang formatting for RDAT_LibraryTypes.inl and RDAT_SubobjectTypes.inl

- .github/workflows/clang-format-diff-apply.yml
- utils/git/code-format-diff-apply.py
When hit clang-format error in a pull request, edit the comment with diff.  
Add @apply-format at the beginning of the comment and Update comment.  
New added "Apply code format" workflow will be triggered.  
It will checkout the code from compare branch of the pull request, apply the diff,  
then commit and push it to the compare branch to fix the format issue.  
The process should be get clang-format diff comment first.  
Then review the diff in the comment.
If the diff looks good, edit and add @apply-format to apply the diff.
> [CI] add workflow to apply clang-format diff

- include/dxc/WinAdapter.h
- lib/DxcSupport/WinAdapter.cpp
- tools/clang/unittests/HLSL/CompilerTest.cpp
Added CComBSTR::Length for WinAdapter.
Use VERIFY_ARE_EQUAL_WSTR to verify CComBSTR.
Use UTF8 for Linux test.
This is for #5877
> [Linux] Enable PDBUtil test for Linux build

- CMakeLists.txt
Since we don't use dndxc as startup project in most cases, just remove the VS_STARTUP_PROJECT so not need cmake3.4 to build on windows.
> [Build] remove VS_STARTUP_PROJECT to avoid require cmake3.4

- tools/clang/lib/SPIRV/SpirvModule.cpp
This is a quick fix to unblock users, but it could hide other issues.
During this iteration, some function down the line push_back to the debugInstructions vector. If the storage gets moved, then we fail.
Fixes #5566
Signed-off-by: Nathan Gauër <brioche@google.com>
> [SPIRV][NFC] Fix iterator usage after invalidation

- lib/HLSL/HLLowerUDT.cpp
- tools/clang/test/CodeGenDXIL/hlsl/types/modifiers/groupshared/addrspacecast.hlsl
For users of hlsl::ReplaceUsesForLoweredUDT, only EmitGetNodeRecordPtrAndUpdateUsers will has V and NewV with different address space. But there will be no addrspacecast for NodeRecordPtr from clangCodeGen, because NodeRecordPtr doesn't have address space before HLLowerOperation.
As a result, when hit addrspacecast in hlsl::ReplaceUsesForLoweredUDT, the address space of V and NewV should match. So InsertAddrSpaceCastIfRequired will always has AddrSpace != Ty->getPointerAddressSpace().
Removed InsertAddrSpaceCastIfRequired and add assert for address space mismatch.
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/5695
> Remove InsertAddrSpaceCastIfRequired which is redundant

- tools/clang/test/HLSLFileCheck/hlsl/workgraph/ast-nodeinput.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/ast-nodeoutput.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/ast-rwnodeinput.hlsl
Several workgraph tests had AST checks which check not only the expected operation attribute by name, but included the opcode value, which is not stable when HL operations are changed.
This change removes the high-level opcode value from the CHECK lines.
> Make tests robust for high-level opcode changes.

- lib/DxilDia/DxcPixLiveVariables.cpp
- lib/DxilDia/DxilDiaSession.cpp
- tools/clang/unittests/HLSL/PixDiaTest.cpp
From the comment in one of the changed files:
// If a function is inlined, then the scope of variables within that function
// will be that scope. Since many such callers may inline the function, we
// actually need a "scope" that's unique to each "instance" of that function.
// The caller's scope would be unique, but would have the undesirable
// side-effect of smushing all of the function's variables together with the
// caller's variables, at least from the point of view of PIX. The pair of
// scopes (the function's and the caller's) is both unique to that particular
// inlining, and distinct from the caller's scope by itself.
> WinPix: variables in subroutines called from multiple functions

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/CodeGenSPIRV_Lit/attribute.numthreads.lib.missing.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/attribute.numthreads.missing.hlsl
- tools/clang/test/SemaHLSL/attributes/NecessaryAttribsInLib.hlsl
Currently we error out in validation if a compute shader doesn't have
a numthreads attribute:
```
<source>:2: error: Declared Thread Group X size 2833376888 outside valid range [1..1024].
<source>:2: error: Declared Thread Group Y size 21956 outside valid range [1..1024].
<source>:2: error: Declared Thread Group Z size 2833381336 outside valid range [1..64].
<source>:2: error: Declared Thread Group Count 3863291136 (X*Y*Z) is beyond the valid maximum of 1024.
```
Instead, diagnose this in Sema like we do for mesh and amplitude shaders
> [Diag] Diagnose missing numthreads in compute shaders

- azure-pipelines.yml
The CI build is currently running on any new branch in the repo. We should run it only on `main` and `release*` branches.
> Run CI builds only on main and release branches

- include/dxc/DxilContainer/DxilPipelineStateValidation.h
- lib/DxilContainer/DxilContainerAssembler.cpp
- tools/clang/unittests/HLSL/DxilContainerTest.cpp
- In `DxilPipelineStateValidation.h`, add `PSVRuntimeInfo3` derived from `PSVRuntimeInfo2`, containing one `uint32_t EntryFunctionName` member.
- Update `MAX_PSV_VERSION` and `RuntimeInfoSize()` for new version.
- Add pointer to `DxilPipelineStateValidation` and assign in `ReadOrWrite` along with other versioned pointers.
- Add `DxilPipelineStateValidation::GetEntryFunctionName()` accessor to look up name in string table.
- Update PSV0 versioning to key off validator version 1.8 in `DxilContainerAssembler.cpp`
- Add entry name to string table and set `EntryFunctionName` to offset.
- Add initialization to DxilPSVWriter members
- Add asserts in DxilPSVWriter::write() to ensure buffer sizes not changed after m_PSVInitInfo is set.
- Add test to DxilContainerTest, adding/updating common …
> Add EntryFunctionName to PSV0 data

- .github/workflows/clang-format-checker.yml
- utils/git/code-format-save-diff.py
Fix issues hit when apply format.
1. tmp diff file is not opened binary form, don't need to encode.
2. add contents write to "Check code formatting" workflow for commit and push change.
3. put main branch to different path to avoid issue when checkout head branch to same path.
> [CI] fix issue when apply format

- tools/clang/test/CodeGenDXIL/hlsl/types/modifiers/groupshared/addrspacecast.hlsl
In the test added by ba90e249d "Remove InsertAddrSpaceCastIfRequired which is redundant (#5862)" we have a check line for a `dx.hl.op` that refers to an opcode. Since the HL opcodes aren't stable, we should avoid that.
> Don't rely on a high level opcode in a test

- .github/workflows/clang-format-checker.yml
This is avoid possible issue when git add . might add main.
> [CI] use build/main_src instead main when checkout main for save diff

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV_Lit/intrinsics.interlocked-methods.cs.hlsl
This implements the atomic exchange for floating point values that was
added in SM6.6. See https://microsoft.github.io/DirectX-Specs/d3d/HLSL_SM_6_6_Int64_and_Float_Atomics.html#interlockedexchange.
> [SM66,SPIRV] Implement InterlockedExchange for floats

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
Parameter was missing from error message so decl name was not being emitted.
> [SPIR-V] Add name to unregisterd decl error

- lib/DxilDia/DxcPixLiveVariables.cpp
- lib/DxilDia/DxilDiaSession.cpp
- lib/DxilPIXPasses/DxilDebugInstrumentation.cpp
This is a cherry-pick of the big clang-format change in main, but restricted to just three files for which I intend to CP subsequent changes from main. I generated this PR with the following commands:
git cherry-pick -n https://github.com/microsoft/DirectXShaderCompiler/commit/37ed613864cdc269d8b1fc0e40ecd5aa4a7f2905
git reset -- .
rem variables in subroutines called from multiple functions
git add lib/DxilDia/DxcPixLiveVariables.cpp
git add lib/DxilDia/DxilDiaSession.cpp
rem Instrument ret instructions for shader debugging
git add lib/DxilPIXPasses/DxilDebugInstrumentation.cpp
git restore .
del include\dxc\Support\DxcOptToggles.h
> PIX: CP of clang-format change prepping for subsequent CPs

- lib/DxilDia/DxcPixLiveVariables.cpp
- lib/DxilDia/DxilDiaSession.cpp
- lib/DxilPIXPasses/DxilDebugInstrumentation.cpp
- tools/clang/test/HLSLFileCheck/pix/DebugInstrumentRet.hlsl
These are two fixes needed for a point release of WinPIX
Original PRs:
https://github.com/microsoft/DirectXShaderCompiler/pull/6033
https://github.com/microsoft/DirectXShaderCompiler/pull/5954
Since PixDiaTest.cpp would require bringing over a whole bunch of changes that were made for the linux build, I elected to remove that file from the CP. These commands were used to generate this PR:
git cherry-pick -n -x 2c19e8121b5290e7310db5bc98242dddf98e9e7b
git rm tools/clang/unittests/HLSL/PixDiaTest.cpp
git commit -am "CP of 2c19e8121b5290e7310db5bc98242dddf98e9e7b without PixDiaTest.cpp"
git cherry-pick -x 5ffdf1452748491d13b77d49702c0cb8b2471bbe
> PIX: CP of two fixes (vars in inline fns, instrument ret for shader debug)

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
Direct3D version 611 does not have SM 6.8 support yet.
> Update WinSDK version with WaveMatrix support

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/CodeGenSPIRV_Lit/intrinsics.interlocked-methods.compareexchange.output.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/intrinsics.interlocked-methods.compareexchange.reference.hlsl
Interlock* functions takes output parameters. Because HLSL had no real concept of references, this is allowed:
```
int value;
takeAnOutput(value);
```
This weirdness makes using `isLValue()` to validate output parameters a bit tricky. If a function returns a local array, and we take the subscript of this r-value, the r-value is now marked as l-value, but this shouldn't be allowed.
This forces us to walk the expression, and add heuristics to determine if the output parameter is valid or not. Not pretty, but I think this is required until HLSL gets proper references.
Fixes #5772
> [SPIR-V] Fix interlock output parameter validation

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/test/CodeGenSPIRV_Lit/spirv.interface.holes.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/spirv.interface.hs.large.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/vk.location.large.hlsl
There was an arbitrary limit to set the maximum number of locations to 64.
This commit allows the set to be resized, to allow arbitrarily large location indices.
Curiously, one test, vk.location.large.hlsl started to fail. This test assumed 123456 was an invalid location. From the SPIR-V spec, I don't think this is true, as it only days Location should be an arbitraty number.
In addition, it seems like this test was triggering an out-of-bound access, which is now solved. Only drawback: we now end-up with a 123456 sized bitset.
I believe this is OK, as WHY would someone only require this index.
Fixes #3735
> [SPIRV] allow location index to be > than 64

- tools/clang/include/clang/AST/HlslTypes.h
- tools/clang/lib/AST/HlslTypes.cpp
- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/InitListHandler.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV_Lit/sm6_6.objects.descriptorheap.hlsl
Emit an explicit error message when HLSL `ResourceDescriptorHeap` or `SamplerDescriptorHeap` are used with `-spirv` as they are not yet supported.
Fixes #5913
> [SPIR-V] Emit error for unsupported HLSL res obj

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
Version 612 does not have a public WaveMatrix support yet.
> Update WinSDK version with WaveMatrix support to 613

- tools/clang/include/clang/AST/HlslTypes.h
- tools/clang/lib/AST/HlslTypes.cpp
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/SemaHLSL/hlsl/workgraph/dispatch_grid.hlsl
- tools/clang/test/SemaHLSL/hlsl/workgraph/dispatch_grid_type_nodeinput.hlsl
- tools/clang/test/SemaHLSL/hlsl/workgraph/dispatch_grid_type_nodeoutput.hlsl
Check both Input and Output node type when diagnose Semantic of DispatchGrid.
Fixes #5958
> [SM6.8] Diagnostic for output records with SV_DispatchGrid

- tools/clang/lib/CodeGen/CGHLSLMSHelper.h
NodeInputRecordProps is used in this file, but the corresponding header is not directly included. This breaks out build.
> build: add missing include file

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV_Lit/error.no.validation.hlsl
When the codegen fails, it shows an error, but the SPIR-V validation still runs. Because the generation fails, the generated SPIR-V code could be invalid without it being a compiler bug. But the validation error message could confuse the user as it says this is a DXC bug.
> [SPIR-V] disable validation on error

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/DeclResultIdMapper.h
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV_Lit/vk.layout.shader-record-ext.std430.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/vk.layout.shader-record-nv.std430.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/vk.push-constant.constantbuffer.assign.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/vk.push-constant.constantbuffer.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/vk.shader-record-ext.constantbuffer.assign.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/vk.shader-record-ext.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/vk.shader-record-ext.offset.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/vk.shader-record-nv.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/vk.shader-record-nv.offset.hlsl
Since `ConstantBuffer` is now lowered in `LowerTypeVisitor`, lower `push_constant` and `shader_record_*` with `ConstantBuffer` types there as well.
Fixes #5808.
> [SPIR-V] Fix push_constant and shader_record_ext to work with LowerTypeVisitor

- tools/clang/include/clang/SPIRV/SpirvBuilder.h
- tools/clang/include/clang/SPIRV/SpirvInstruction.h
- tools/clang/lib/SPIRV/EmitVisitor.cpp
- tools/clang/lib/SPIRV/EmitVisitor.h
- tools/clang/lib/SPIRV/SpirvBuilder.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/lib/SPIRV/SpirvInstruction.cpp
- tools/clang/test/CodeGenSPIRV_Lit/cf.switch.opswitch.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/cf.switch.opswitch.literal.hlsl
Allow 64-bit integer variables as switch statement selectors and clarify the error message for literal selectors (related to #4338).
> [SPIR-V] Add support for 64-bit switch sel

- lib/DxilPIXPasses/DxilDebugInstrumentation.cpp
- tools/clang/test/HLSLFileCheck/pix/DontDebugNoRegnum.hlsl
CP of main PR (#6053), regression caused by main PR https://github.com/microsoft/DirectXShaderCompiler/pull/6033
The misplacement of that "return" in DxilDebugInstrumentation.cpp meant that a thread would continue to the following call to addStepDebugEntryValue, even if pix_dxil::PixDxilReg::FromInst had failed (i.e. returned false), which means that RegNum is not valid (although initialized to 0).
This meant that PIX was instrumenting a bunch of void-return DXIL instructions that it shouldn't have.
Didn't think to test that it WASN'T instrumenting instructions, but herein is added a test to do just that.
(cherry picked from commit 71afbcc7cf5d7c3631a4aef9979762fa120c7c0b)
> PIX: CP of shader debugger regression

- tools/clang/include/clang/Basic/Attr.td
- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV_Lit/spv.inline.capability.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/spv.inline.extension.hlsl
- tools/clang/test/CodeGenSPIRV_Lit/spv.inline.extension.unused.hlsl
`ext_extension` and `ext_capability` can only be added to functions at the moment. This PR enables adding them to variable declarations, so that using the variable results in the extensions and capabilities being added to the module. This is useful for the builtin variable syntax proposed in https://github.com/microsoft/hlsl-specs/pull/129.
> [SPIR-V] Enable vk::ext_extension and vk::ext_capability for variables

- .github/workflows/clang-format-checker.yml
Only apply_diff job needs conntents write permission. 
code_formatter job only needs pull-request write permission.
> [CI] remove contents write permission from code_formatter job.

- utils/hct/hctgen.py
- utils/hct/hctgettaef.py
In parallel builds of DXC, hctgen.py in particuilar would sometimes throw an exception from os.makedirs because the directory would already exist. The conditional check for file existence introduces a race when running the script in parallel. Fix this, and all other cases where such conditional checks were done, by using the `exist_ok = True` argument.
> Python: fix calls to os.makedirs to avoid existence check races

- cmake/modules/FindDiaSDK.cmake
Fail to find DIASDK when using VisualStudio "Open a local folder". Both VS_DIA_INC_PATH and VSWHERE_LATEST are empty. But MSVC_DIA_SDK_DIR is set correctly.
Add MSVC_DIA_SDK_DIR/include as hint for DIASDK_INCLUDE_DIR.
> [CMake] add another hint for DIASDK

- cmake/modules/FindD3D12.cmake
FindD3D12.cmake sets WIN10_SDK_VERSION to
CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION; however, this latter variable is only defined when using a Visual Studio CMake generator. When using Ninja instead, for example, this variable will be empty, and WIN10_SDK_VERSION will remain unset.
This change detects when CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION and attempts to retrieve the latest SDK by listing directories under ${WIN10_SDK_PATH}/Include.
> CMake: fix FindD3D12.cmake when using non-VS generators

- tools/clang/lib/Sema/SemaOverload.cpp
While emitting diagnostic notes about conversions, the code for checking `OutConversions` was not included in the loop. This caused an OOB when `I >= NumConversions`. Normally, this does not affect anything (other than not emitting the diagnostics for `OutConversions`), since most of the time `OutConversions[I].isBad()` happens to return false. However, in some cases when `OutConversions[I].isBad()` is true, calling `DiagnoseBadConversion()` on the invalid entry will crash.
> Fixed an OOB that potentially causes a crash

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/DeclResultIdMapper.h
The `createStageVars` function is very large, and difficult to fix. In support of two bug fixes, I want to refactor the function so try to make the code cleaner.
This change will try to keep the exact same functionality. I believe their could be further simplification after this if needed.
> Refactor create stage vars

- include/dxc/DXIL/DxilShaderModel.h
- lib/DXIL/DxilModule.cpp
- lib/DXIL/DxilShaderModel.cpp
The IsRay() function defined in the ShaderModel class can be misleading. It is included in a set of functions that are used to test whether or not the shader in question was targeted to a specific shader stage. However, it is impossible for a shader to be targeted to, say, the "raygeneration" stage, or any other stages associated with the kinds that the IsRay() function checks for. Like the "node" shader kind, a shader can only have these shader kinds if the associated attribute is found on the function declaration. To prevent confusion, and to keep the Is*() functions inside the ShaderModel class restricted to only those targetable shader stages, the IsRay() function can be removed. This PR comes as a response to #6008
> [NFC] Remove misleading function

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
WaveMatrix wasn't checking WaveMMATier before running tests (assuming it was always supported for SM 6.8). This change fixes this.
D3D12_SDK_VERSION check for WAVE_MMA feature structure and enum definitions assumed they will be defined in SDK version 613. This isn't accurate, so this block of local definitions will always be enabled until we have the correct version in the future.
> Check WaveMatrix support; locally declare feature struct for now

- include/dxc/Test/HlslTestUtils.h
- include/dxc/WinAdapter.h
- lib/DxilDia/DxcPixLiveVariables.cpp
- tools/clang/unittests/HLSL/PixDiaTest.cpp
- tools/clang/unittests/HLSL/PixTestUtils.cpp
- tools/clang/unittests/HLSL/PixTestUtils.h
In DxcPixLiveVariables.cpp, UniqueScopeForInlinedFunctions::AscendScopeHierarchy tries to keep track of a variable's scope and the scope at which its containing function was inlined, if any.
This scope duo has to be the same in two places for things to work out: the scopes inferred from dbg.declare, and then again when the scope hierarchy is ascended in order to discover all variables accessible from a given point in the program.
AscendScopeHierarchy was forgetting to update the inlined part of the scope, resulting in, for example, PIX's debugger losing track of variables outside of, for example, a for loop, even though the code can see those variables at that point.
Just setting the inlined scope to be the same as the function scope fixes this problem.
(In addition to these new tests, …
> PIX: Fix scope ascension for variable lookup

- lib/DxilDia/DxcPixLiveVariables.cpp
As in my previous PIX CP, I've removed the test changes from the cherry-pick since the test file in question (PixDiaTest.cpp) doesn't even exist in this branch (it was split off from PixTest.cpp in main to deal with linux build issues).
> CP of PIX scope ascension fix

- tools/clang/unittests/SPIRV/CMakeLists.txt
This reverts commit 36bfa748784966e1406f8c1823e379bb97f4dc81.
CodeGenSpirvTest.cpp has been cut down significantly from its original >10,000 line size, so this flag should no longer be necessary.
Fixes #3867
> Revert "Add /bigobj flag on big spirvtest object (#3858)"

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
Remove unused function VerifyOutputWithExpectedValueUInt4.
> [ClangCL] fix clang-cl warning

- tools/clang/lib/SPIRV/DeclResultIdMapper.h
This codebase is using C++17, but to remain compatible with C++20, I need to remove this.
Starting C++20, an aggregate is required to have no user-declared constructors, vs before, no user-provided constructors.
So even if if the only the default constructor is provided, this is enough to prevent us from using this class as an aggregate in c++20.
> spirv: fix build for C++20

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/DeclResultIdMapper.h
- tools/clang/test/CodeGenSPIRV/semantic.unsigned-nonzero-base-instance.vs.hlsl
A regression was introduced by Refactor create stage vars (#6059)
because it created the BaseInstance variable as an int in all cases it
was created for the option vk-support-nonzero-base-instance enabled. In
some cases it was used as an unsigned int.
This comment get the type for BaseInstance from the type of the instance
id variable, and adds a test for unsigned.
Fixes #6118.
> Allow unsigned int for nonzero base instance

- docs/SPIR-V.rst
- tools/clang/lib/SPIRV/CapabilityVisitor.cpp
- tools/clang/lib/SPIRV/CapabilityVisitor.h
- tools/clang/lib/SPIRV/FeatureManager.cpp
The docs were out of date stating that the `SPV_AMD_gpu_shader_half_float` extension was added when half types were used. This is now corrected to show that the Float16 capability is added and no extension.
The remaining code that could have added that extension in certain cases has been dead code since #2503 since none of the instructions checked in that list are ones that are emitted by DXC, so it is removed to clean up.
Evidence that this is dead code:
1. `git grep "InterpolateAt"` finds no uses other than those removed here.
2. All tests still pass when it's removed.
3. The comments in #2503 also say they were not able to find a mapping from any HLSL intrinsics to these instructions, which is why no tests were added.
Follow-up from: …
> [SPIR-V] Remove dead code and correct Float16 docs

- lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
- tools/clang/test/HLSLFileCheck/hlsl/signature/sig-flatten-struct-array.hlsl
Semantic index assignment for flattened arguments would incorrectly increment the argument index after an array of struct field was encountered. It would misinterpret any array of struct as a basic type because it wasn't a struct type.
This fixes the bug by drilling into the array element before checking the type.
Fixes #6121
> Fix bad arg indexing after array of struct in semantic assignment

- utils/lit/lit/Test.py
- utils/lit/lit/main.py
- utils/lit/tests/Inputs/test-data/lit.cfg
- utils/lit/tests/Inputs/test-data/utf8_output_message.ini
- utils/lit/tests/xunit-output.py
This commit modifies the xml output of lit so that we always open the file as utf-8 and also encode any invalid characters with the xml character reference.
I was hitting an encoding error on windows for some test output because the xml file was using the windows cp1252 encoding and it ran into some characters that could not be encoded.
In order to test the change I added a new flag to lit `--xml-include-test-output` which will include all test output in the xml. That way we can still expect the lit run to pass and also validate that the xml file is properly encoded.
> Write lit xml output as utf-8

- tools/clang/include/clang/Sema/SemaHLSL.h
- tools/clang/lib/Sema/CMakeLists.txt
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/lib/Sema/SemaHLSLDiagnoseTU.cpp
Since DiagnoseTranslationUnit is after Sema, it doesn't need to be part of SemaHLSL. 
This is in preparation for moving DiagnoseHLSLMethodCall to hlsl::DiagnoseTranslationUnit for access to the call graph.
Only move code to new file, not other changes except replace OutputDebugFormat with llvm::dbgs for CallGraphWithRecurseGuard::dump.
For https://github.com/microsoft/DirectXShaderCompiler/issues/5855
> [NFC] Move hlsl::DiagnoseTranslationUnit to separate file.

- docs/DXIL.rst
The documentation for sample incorrectly implied that textureCUBE resources should have 3 active offsets. Actually, cube textures have no sample method overloads that include offsets.
This corrects the table indicating the number of active elements for sample and also for sampleGrad as it incorrectly stated that the number of active gradients is the same as the number of offsets. Again for cube textures this is inaccurate. Cube textures take 3 gradients, but still allow no active offsets.
> Correct sampling param error in DXIL docs

- tools/clang/lib/Sema/SemaCodeComplete.cpp
The clang-12 warning is:
error: fallthrough annotation in unreachable code [-Werror,-Wimplicit-fallthrough]
These LLVM_C_FALLTHROUGH were originally added to silence GCC warnings, but the GCC PR validation build is has succeeded, so it looks like they are not needed.
> Remove LLVM_C_FALLTHROUGH instances that cause warnings on clang-12

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/test/CodeGenSPIRV/hs.bool.input.hlsl
Inputs and outputs that are boolean in HLSL cannot be bools in SPIR-V
because it is not allowed by the spec. So they need to be treated as
ints in the interface.
This was not tested with Hull shaders, where these input and outputs
must also be turned into arrays. This commit adds the code that will
handle casting the arrays between int and bool.
Fixes #3744
> Handle bool in HS input and outputs

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/hs.const.output-patch.out.hlsl
The documentation for the patch constant functions only mention
> The outputs are usually defined by a structure and is
identified by HS_CONSTANT_DATA_OUTPUT in this example; the structure
depends on the domain type and would be different for triangle or
isoline domains.
This is why we did not realize that we needed to implement out variables
as well. This commit implement the alternate method of having an output.
Fixes #3743
> [SPIRV] Implement out variables in patch constant functions

- tools/clang/lib/CodeGen/CGHLSLMS.cpp
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/class_input_record.hlsl
- tools/clang/test/SemaHLSL/hlsl/workgraph/class_input_record.hlsl
Node input records may be a struct or a class, but CodeGen failed to correctly handle the case when a class was used. This change fixes the error, and adds a test case.
Fixes #6119
> Allow node input record to be a class

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/intrinsics.dot4add.hlsl
This is a follow-up for https://github.com/microsoft/DirectXShaderCompiler/pull/5959
The SPIR-V spec [requires](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpSDot) that `OpSDot` and `OpUDot` have an extra Packed Vector Format operand when Vector 1 and Vector 2 are scalar integer types. My previous implementation didn't add that operand - sorry about that. The generated code worked on NVIDIA GPUs but produced incorrect ouptut on AMD and resulted in a crash on Intel ARC. This PR fixes the generated code so that it works on all three vendors' GPUs.
> [SPIRV] Fix the code generated for dot4add_u8packed and dot4add_i8packed

- tools/clang/include/clang/Basic/SourceManager.h
- tools/clang/lib/Basic/SourceManager.cpp
- tools/clang/lib/SPIRV/EmitVisitor.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/rich.debug.debugsource.multiple.hlsl
- tools/clang/test/CodeGenSPIRV/rich.debug.function.parent.hlsl
- tools/clang/test/CodeGenSPIRV/spirv.debug.opline.include.hlsl
- tools/clang/test/CodeGenSPIRV/spirv.debug.opsource.include-file.hlsli
- tools/clang/test/CodeGenSPIRV/spirv.debug.opsource.include.hlsl
The current implementation generates SPIR-V OpSource instructions from within EmitVisitor::emitDebugLine(), part of OpLine processing, improperly tying the two together.  Only files including instructions that generate an OpLine will generate an OpSource, meaning that many include files are missed.  An included file may include nothing more than preprocessor macro definitions, but that should still generate an OpSource.  
The SourceManager already tracks the correct and complete list of files generated by the preprocessor in LineTable.  We therefore propose a new pair of SourceManager api's that expose the LineTable.  SpirvEmitter::HandleTranslationUnit() may now simply and directly create all required OpSource instructions.
> [SPIRV] Generate OpSource for All Includes

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/spv.inline.capability.hlsl
- tools/clang/test/CodeGenSPIRV/spv.inline.extension.hlsl
`ext_capability` and `ext_extension` were previously only handled when translating a CallExpr. Since the entry point is never called, they were ignored when attached to it.
> [SPIR-V] Handle vk::ext_capability and vk::ext_extension on entry point

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/type.type-alias.hlsl
- tools/clang/test/CodeGenSPIRV/type.type-alias.template.hlsl
- tools/clang/test/CodeGenSPIRV/var.template.hlsl
Apparently the frontend already provides everything we need for these declarations to work; we just needed to ignore them when handling `Decl`s.
Fixes #5751.
> [SPIR-V] Implement type alias, type alias templates, and variable templates

- tools/clang/test/SemaHLSL/ds-error-outputpatch-size.hlsl
- tools/clang/test/SemaHLSL/hs-error-inputpatch-size.hlsl
The tests are for an error message that originates from Sema HLSL, it is a not a spirv-specific code. The `-spirv` test case does not bring any additional value. And since these tests are not marked spirv-only (as they should not be), they are failing when the compiler is built without SPIRV support.
> Remove SPIRV test case from Sema tests related to DS/HS patch size

- include/dxc/DXIL/DxilConstants.h
- lib/DXIL/DxilOperations.cpp
- tools/clang/test/HLSLFileCheck/hlsl/objects/WaveMatrix/WaveMatrix_Add-limited.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/objects/WaveMatrix/WaveMatrix_Depth.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/objects/WaveMatrix/WaveMatrix_Fill-acc.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/objects/WaveMatrix/WaveMatrix_Fill-in.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/objects/WaveMatrix/WaveMatrix_LoadStore-acc.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/objects/WaveMatrix/WaveMatrix_LoadStore-in.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/objects/WaveMatrix/WaveMatrix_Multiply-Add-acc.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/objects/WaveMatrix/WaveMatrix_ScalarOps-acc.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/objects/WaveMatrix/WaveMatrix_SumAccumulate-acc.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/objects/WaveMatrix/lit.local.cfg
- utils/hct/hctdb.py
Adds max opcode value for DXIL 1.8 and moves WaveMatrix intrinsics into future shader model 6.9.
Contributes to #6133
Related to #6125
> Add DXIL 1.8 op code cap and move WaveMatrix intrisics to SM 6.9

- include/dxc/DXIL/DxilConstants.h
- include/dxc/DXIL/DxilShaderFlags.h
- lib/DXIL/DxilShaderFlags.cpp
- tools/clang/test/HLSLFileCheck/hlsl/objects/Texture/SampleCmpBias.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/objects/Texture/SampleCmpGrad.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/objects/Texture/has_lod_clmap.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/objects/Texture/no_lod_clmap.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/semantics/ExtendedCommandInformation/no_in_sig_input.hlsl
- tools/clang/tools/dxcompiler/dxcdisassembler.cpp
New feature flag ShaderFeatureInfo_SampleCmpGradientOrBias = 0x80000000 and 
ShaderFeatureInfo_ExtendedCommandInfo = 0x100000000 were added. 
They will be set when SampleCmpBias/Grad startInstance/VertexLocation exists.
> [SM68] Add feature flag for SampleCmpBias/Grad and StartInstance/VertexLocation

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
WaveMatrix is moved out of SM 6.8, so the requirement in the test needs to be updated to SM 6.9 to exclude the test from execution until at least experimental SM 6.9 is supported by the device.
> Update WaveMatrix test shader model requirement to 6.9

- cmake/modules/HCT.cmake
- lib/DXIL/DxilShaderModel.cpp
The build is failing due to clang-format modifying these lines. I've changed them to what clang-format wants even though it's a bit odd, and updated the CMake script to make the error message more clear when this type of failure occurs.
> Make clang-format happy

- tools/clang/test/HLSLFileCheck/hlsl/objects/WaveMatrix/WaveMatrix67.hlsl
Published validators do not have consistent error messages.
> Use internal validator for WaveMatrix67.hlsl test

- lib/DxilDia/DxilDiaSession.cpp
- lib/DxilDia/DxilDiaSession.h
- lib/DxilDia/DxilDiaSymbolManager.cpp
The init of the dia symbol manager presents an unneccessary performance hit for WinPix. It's quite simple to defer the init, so here we are.
(This dia implementation was originally added specifically for WinPix, but was then superseded by a simpler API. It's entirely possible that there are no other clients of the dia interface at all, but it has been published, so we're probably bound to maintain it.)
(Note that there are other deferment opportunities here, but the larger pending work is to disentangle the dia implementation from that of the new "IDxcPix*" API that WinPix uses, which would obviate deferment altogether, but that's way out of scope for me for now.)
> Defer DiaSession's symbol init (it is unused by WinPix (or anyone?))

- include/dxc/Support/Global.h
When asserts are disabled (LLVM_ENABLE_ASSERTIONS=0), DXASSERT* macros are defined to nothing, resulting in no statements followed by a semicolon. This results in:
warning C4390: ';': empty controlled statement found; is this the intent?
Which fails because warnings are treated as errors.
Fix by adding the standard "do {} while(0)". Also opportunistically remove the extra semicolon for non-WIN32 builds.
> Fix empty control statement warnings when asserts are diabled on MSVC

- tools/clang/test/HLSLFileCheck/dxil/intrinsics/launch_types_coalescing.ll
- tools/clang/test/HLSLFileCheck/dxil/intrinsics/launch_types_thread.ll
Internal pipeline issues revealed that certain launch type tests that were recently merged were running with older validators.
This PR ensures that the tests run with validator version 1.8.
> Ensure dxil validator 1.8 runs for launch type tests

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/fn.param.inout.stage.hlsl
Always copy-in and copy-out inout parameters, so that parameters with semantics that map to stage variables are properly propagated.
Fixes #6113
> [SPIR-V] Propagate stage variables for inout

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
The D3D12_EXPERIMENTAL_WAVE_MATRIX define will be removed in the future and replaced with WinSDK version that includes runtime support for WaveMatrix.
> Gate local WaveMatrix runtime definitions on D3D12_EXPERIMENTAL_WAVE_MATRIX define

- tools/clang/lib/SPIRV/CMakeLists.txt
- tools/clang/lib/SPIRV/ConstEvaluator.cpp
- tools/clang/lib/SPIRV/ConstEvaluator.h
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
This moves functions for evaluating constant expressions and translating LLVM AP types to SPIR-V constants into a new class. These functions need to be used from LowerTypeVisitor in #6156, so I am factoring them out to avoid duplication.
> [SPIR-V] Move constant evaluation code into a new class

- tools/clang/lib/SPIRV/AstTypeProbe.cpp
- tools/clang/test/CodeGenSPIRV/decoration.user-type.hlsl
Update implementation of SPV_GOOGLE_user_type following the spec changes in: https://github.com/KhronosGroup/SPIRV-Registry/pull/230
> [SPIR-V] Update SPV_GOOGLE_user_type

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/cast.flat-conversion.literal-initializer.hlsl
- tools/clang/test/CodeGenSPIRV/cast.flat-conversion.matrix.hlsl
- tools/clang/test/CodeGenSPIRV/cast.flat-conversion.vector.hlsl
- tools/clang/test/CodeGenSPIRV/cast.struct-to-int.hlsl
- tools/clang/test/CodeGenSPIRV/spirv.legal.cbuffer.hlsl
- tools/clang/test/CodeGenSPIRV/spirv.legal.tbuffer.hlsl
- tools/clang/test/CodeGenSPIRV/type.constant-buffer.bindless.array.hlsl
The implementation of flat conversion in the spir-v codegen is very
adhoc. This changes the implemetation to match what is done in DXIL. For
now I have only reimplemented to catch all case. I will leave the
special cases as they seem to be correct for what they do, and will
generate less verbose code.
Fixes #4906
> [SPIRV] Reimplement flat conversion.

- tools/clang/lib/SPIRV/FeatureManager.cpp
- tools/clang/test/CodeGenSPIRV/spirv.environment.invalid.hlsl
When the env isn't valid, we emit an error. But instead of returning, we continued and still tried to load the optional value, which triggered an assert.
> [SPIR-V] Fix invalid optional read

- include/dxc/Test/HlslTestUtils.h
Recognize 'Microsoft Basic Render Driver' in execution tests as a valid adapter name equivalent to WARP.
> Recognize 'Microsoft Basic Render Driver' in execution tests

- include/dxc/Support/SPIRVOptions.h
- tools/clang/lib/SPIRV/EmitVisitor.cpp
- tools/clang/tools/dxcompiler/dxcompilerobj.cpp
- tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
This PR improves the experience for debugging tools that consume SPIR-V produced by passing in-memory strings to dxcompiler.dll.  When dxc.exe is used, OpSource and OpDebugSource are populated by reading original source from the filesystem.  dxcompiler.dll users instead find their input string is preprocessed, which is confusing behavior.  
Contrary to the leading comment in the code this change modifies, debugging tools do not want preprocessed source.  Such tools show and allow editing of include files.  If everything is pasted into a single source string, finding what to edit is difficult.  Editing the preprocessed source has the additional complication that a user would have to edit also the #line markers, which is hard to get right manually.  In the preprocessed source, all comments …
> [SPIRV] Always provide original source to debug

- tools/clang/lib/SPIRV/FeatureManager.cpp
- tools/clang/test/CodeGenSPIRV/meshshading.ext.no-explicit-exts-spv1.4.mesh.hlsl
- tools/clang/test/CodeGenSPIRV/meshshading.nv.request-nv-with-spv1.4.mesh.hlsl
- This changes the FeatureManager constructor, so that EXT_mesh_shader is still the default choice for mesh shaders when SPIR-V 1.4 or above is supported, but is not forced even when NV_mesh_shader is requested. Before, it was impossible to choose NV_mesh_shader in that case.
Fixes #6193
> [SPIR-V] Don't always force EXT_mesh_shader override

- cmake/modules/HCT.cmake
When not updating the in-tree sources, the compare step would always run because the comparison was part of the target. This prevents that by having the comparison be its own custom command that produces an output and the target depends on the "output" of the comparison step.
> [CMake] Don't always run compare steps

- tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
- tools/clang/test/CodeGenSPIRV/type.buffer.half.hlsl
According to the Vulkan spec:
OpTypeImage must declare a scalar 32-bit float, 64-bit integer, or 32-bit integer type for the “Sampled Type” (RelaxedPrecision can be applied to a sampling instruction and to the variable holding the result of a sampling instruction)
We want to avoid translating a true HLSL 16-bit floating point texture object to a 32-bit texture object with relaxed precision, as this will break backwards compatibility if Vulkan does support 16-bit texture types in the future.
This change adds an error message in cases where the code generated would otherwise fail validation for the above reasons.
Closes #4372
> [SPIR-V] Emit error for 16-bit texture types

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/type.byte-address-buffer.hlsl
An "aliased" variable is on where the compiler has implicitly added an
extra level indirection. So when we access one of these variable, we
have to do an extra load.
When we do an array access on an aliased variable, we do the extra load
before doing the access chain, but we still treat the result of the
access chain as if it is an aliased value. This causes an extra load and
generates invalid spir-v.
The fix is to change `isReferencingNonAliasStructuredOrByteBuffer` so
that we do not distinguish between externally and internally visible
variable if we see an array subscript.
Fixes #6110
> [SPIR-V] Mark array reference to aliased var as unaliased

- include/dxc/DxilContainer/DxilRuntimeReflection.inl
- include/dxc/DxilContainer/RDAT_Macros.inl
These TODOs were intended for if we were to implement deep RDAT validation rather than relying on the exact binary comparison.
This isn't happening for SM 6.8, so these are no longer PRERELEASE-TODOs.
The comment in RDAT_Macros.inl didn't really belong there in the first place, so I removed it.
Fixes #5699.
> NFC: Resolve PRERELEASE-TODO cases related to deep RDAT validation

- include/dxc/Support/HLSLOptions.td
- include/dxc/Support/SPIRVOptions.h
- lib/DxcSupport/HLSLOptions.cpp
- tools/clang/include/clang/SPIRV/FeatureManager.h
- tools/clang/lib/SPIRV/CapabilityVisitor.cpp
- tools/clang/lib/SPIRV/FeatureManager.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/spv.default-maximal-reconvergence.hlsl
- tools/clang/test/CodeGenSPIRV/spv.enable-maximal-reconvergence.hlsl
This option is not enabled by default. When enabled, this option adds the MaximallyReconvergesKHR execution mode to the module, and the associated extension.
Related to #6222
> [SPIR-V] Add fspv-enable-maximal-reconvergence opt

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/test/CodeGenSPIRV/spirv.interpolation.mesh.hlsl
Mesh shader output variables may be decorated with the `nointerpolation` attribute, which should be translated to a `Flat` decoration in the SPIR-V backend.
Fixes #6250
> [SPIR-V] Apply nointerpolation to mesh output

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/bezier.hull.hlsl2spv
- tools/clang/test/CodeGenSPIRV/binary-op.assign.composite.hlsl
- tools/clang/test/CodeGenSPIRV/fn.param.unsized-opaque-array.hlsl
- tools/clang/test/CodeGenSPIRV/op.array.access.hlsl
- tools/clang/test/CodeGenSPIRV/op.cbuffer.access.majorness.hlsl
- tools/clang/test/CodeGenSPIRV/op.constant-buffer.access.hlsl
- tools/clang/test/CodeGenSPIRV/op.rw-structured-buffer.access.hlsl
- tools/clang/test/CodeGenSPIRV/op.struct.access.hlsl
- tools/clang/test/CodeGenSPIRV/op.structured-buffer.access.hlsl
- tools/clang/test/CodeGenSPIRV/op.texture-buffer.access.hlsl
- tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.usage.hlsl
- tools/clang/test/CodeGenSPIRV/type.byte-address-buffer.hlsl
- tools/clang/test/CodeGenSPIRV/vk.1p2.block-decoration.hlsl
- tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resources.2.hlsl
- tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.boolean.hlsl
- tools/clang/test/CodeGenSPIRV/vk.push-constant.hlsl
- tools/clang/test/CodeGenSPIRV/vk.shader-record-ext.hlsl
- tools/clang/test/CodeGenSPIRV/vk.shader-record-nv.hlsl
In the current implementation, a single OpAccessChain is generated for
all array subscripts and member accesses. This causes a problem if the
member access is an aliased variable, and we need to generate and
OpAccessChains for the member, a load, and then another OpAccessChain
to index into the aliased array.
This change cause an array subscript to be process as a single
OpAccessChian. Note that we still process array sub scripts with the
member access when it is a subnode of the member access. We will
probably need to fix that up later as well, but I want to keep the
change small.
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/6110.
> [SPIR-V] Process array subscript individually

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/intrinsics.get-attribute-at-vertex.var.idx.hlsl
The SPIR-V path currently fails when a variable is passed at the index
to GetAttributeAtVertex. Not only should we not crash, but the variable
does not seem to be a problem for the SPIR-V validator. So we can simply
generate an access chain with a variable idx.
> [SPIRV] Allows variable vertex index for GetAttributeAtVertex

- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/SemaHLSL/hlsl/objects/texture/CalculateLODExtraDiag.hlsl
- tools/clang/test/SemaHLSL/hlsl/objects/texture/CalculateLODNoWarning.hlsl
- tools/clang/test/SemaHLSL/hlsl/objects/texture/CalculateLODWithSamplerComparisonState.hlsl
- tools/clang/test/SemaHLSL/hlsl/objects/texture/CalculateLODWithSamplerComparisonState_warning.hlsl
This change is made to prevent errors in unused code that might impact existing shaders.
Fixes #6249
Fixes #6235
> [DIAG] Limit derivative warning to intrinsic overload added in sm6.8

- lib/HLSL/HLSignatureLower.cpp
- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/SemaHLSL/IgnoredAttributes.hlsl
- tools/clang/test/SemaHLSL/attributes.hlsl
- tools/clang/test/SemaHLSL/attributes/wavesize_66.hlsl
- tools/clang/test/SemaHLSL/overloading-unsupported-operators.hlsl
- tools/clang/unittests/HLSL/DXIsenseTest.cpp
For every attribute that is only meaningful on an entry-point, produce a warning indicating that this could be a problem.
The attributes are ignored, so it's harmless, but it still might indicate a mistake on the part of the user. 
Previously, some of these would cause the function to be implicitly made a certain kind of entry point.
These warnings will soften the impact of that change. 
Fixes #6100
> Warn on ignored attributes on library non-entry points

- docs/DXIL.rst
- include/dxc/DXIL/DxilFunctionProps.h
- lib/DXIL/DxilMetadataHelper.cpp
- lib/HLSL/DxilValidation.cpp
- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/CodeGenDXIL/hlsl/wavesize/wavesize-range-not-int.ll
- tools/clang/test/CodeGenDXIL/hlsl/wavesize/wavesize-range-not-three-params.ll
- tools/clang/test/HLSLFileCheck/hlsl/entry/attributes/wavesize-compute-node-ast.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/entry/attributes/wavesize-compute-node-dxil.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/entry/attributes/wavesize-compute-node-rdat.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/wavesize.hlsl
- tools/clang/test/HLSLFileCheck/validation/wavesize/outdated-metadata-tag.ll
- tools/clang/test/HLSLFileCheck/validation/wavesize/too-modern-metadata-tag.ll
- tools/clang/test/HLSLFileCheck/validation/wavesize/wavesize-range-invalid-preferred-value.ll
- tools/clang/test/HLSLFileCheck/validation/wavesize/wavesize-range-invalid-range-value.ll
- tools/clang/test/HLSLFileCheck/validation/wavesize/wavesize-range-multiple-legacy-tags.ll
- tools/clang/test/HLSLFileCheck/validation/wavesize/wavesize-range-multiple-range-tags.ll
- tools/clang/test/HLSLFileCheck/validation/wavesize/wavesize-range-valid-preferred-value-out-of-range.ll
- tools/clang/test/SemaHLSL/attributes/wavesize_range.hlsl
- utils/hct/hctdb.py
Upon further discussion, the team has agreed that in certain degenerate cases, the current diagnostics are insufficient.
In the case that min == max in the wave size range attribute, a defaultError warning should be emitted. Additionally, there should be an explicit way to handle the case where 0,0,0 is passed to the wavesize range attribute.
This PR directly handles and tests both of these cases. Fixes #6161
---------
Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
(cherry picked from commit cadf3bfed1dbfc598fa46d6c9e487d9d37d98a31)
> [Sema] Add final touches to wave size range implementation (#6202)

- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/SemaHLSL/IgnoredAttributes.hlsl
- tools/clang/test/SemaHLSL/attributes.hlsl
- tools/clang/test/SemaHLSL/attributes/wavesize_66.hlsl
- tools/clang/test/SemaHLSL/overloading-unsupported-operators.hlsl
- tools/clang/unittests/HLSL/DXIsenseTest.cpp
For every attribute that is only meaningful on an entry-point, produce a warning indicating that this could be a problem.
The attributes are ignored, so it's harmless, but it still might indicate a mistake on the part of the user.
Previously, some of these would cause the function to be implicitly made a certain kind of entry point.
These warnings will soften the impact of that change.
Fixes #6100
---------
Co-authored-by: Joshua Batista <jbatista@microsoft.com>
Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
(cherry picked from commit 53b2930a1b3ad79cbc060d5db451906a30c2691b)
> Warn on ignored attributes on library non-entry points (#6243)

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/intrinsics.get-attribute-at-vertex.var.idx.hlsl
We are able to pass a variable as the index to GetAttributeAtVertex, but
only if it is signed. If the value is unsigned, no cast is needed, and
the current code will skip the LValueToRValue cast. This causes the
load to be skipped generating invalid code.
> [SPIRV] Do not ignore RValue cast for vertex id in GetAttributeAtVertex

- .github/CODEOWNERS
As per the schedule in #6203, we will begin AskMode on 2/12, at which time all PRs will be required to have at least one sign off from a member of @microsoft/hlsl-release.
Adding this CODEOWNERS file allows us to have GitHub enforce that requirement.
Note: This PR does not enable AskMode, it just puts the infrastructure in place. AskMode will not be enabled until 2/12.
> Add CODEOWNERS to release

- include/dxc/DXIL/DxilMetadataHelper.h
- lib/DXIL/DxilMetadataHelper.cpp
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/record_type_metadata.ll
Metadata loading for node record properties assumed fixed positions for values in a (key,value) property list, skipping and ignoring the keys.
This was not correct, fragile, and not the intended implementation of the key,value property pattern.
There is no functional change, but this makes the loader robust to additional properties instead of crashing or loading the wrong thing.
Fixes #6276
> Correct metadata load for NodeRecordType for robustness

- include/dxc/DXIL/DxilMetadataHelper.h
- lib/DXIL/DxilMetadataHelper.cpp
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/record_type_metadata.ll
Metadata loading for node record properties assumed fixed positions for values in a (key,value) property list, skipping and ignoring the keys.
This was not correct, fragile, and not the intended implementation of the key,value property pattern.
There is no functional change, but this makes the loader robust to additional properties instead of crashing or loading the wrong thing.
Fixes #6276
(cherry picked from commit b3be6f252298c251189e0e60530ed057abf60c5d)
> Correct metadata load for NodeRecordType for robustness (#6277)

- include/dxc/DXIL/DxilConstants.h
- lib/DXIL/DxilShaderModel.cpp
This missing default case statement would cause build break when compiling with additional warning settings, such as /Wall /WX in VC++.
Fixes #6287.
> NFC: Fix switch with missing default case in DxilShaderModel.cpp

- tools/clang/include/clang/Basic/DiagnosticGroups.td
- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/SemaHLSL/attributes.hlsl
- tools/clang/test/SemaHLSL/attributes/wavesize_66.hlsl
- tools/clang/test/SemaHLSL/no-warning-when-entr-attr-without-shader-attr-in-lib.hlsl
In implementing this PR:
https://github.com/microsoft/DirectXShaderCompiler/pull/6243 somehow, the condition to only emit the warning for library shaders was left out.
This PR is a follow up on #6243 to properly restrict the emission of this warning for non-library shaders.
This should properly fix #6100
(cherry picked from commit dbf60d777156b98ea2f8cafc8336bc62bf65213c)
> [Sema] Only emit warnings on entry point attrs with missing shader attr for libraries (#6284)

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/meshshading.ext.cullprimative.hlsl
When SV_CULLPRIMITIVE is the output of a mesh shader, its type is
changed to uint because a Vulkan interface variable cannot be a bool.
However, we do not change the access to the variable to match.
This change will modify stores to the variable to be stores of a uint
instead of a bool.
Fixes #6042
> [SPIRV] Cast SV_CULLPRIMITIVE to uint

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/DeclResultIdMapper.h
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/vk.layout.shader-record-ext.std430.hlsl
Only add raytracing stage var to `OpEntryPoint` interface if it is actually used by that entry point.
Fixes #6265.
> [SPIR-V] Remove duplication of raytracing stage vars

- tools/clang/lib/CodeGen/CGDebugInfo.cpp
- tools/clang/test/HLSLFileCheck/dxil/debug/templated_struct.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/template/templateStructFunc.hlsl
Made the debug info type for the `this` argument a reference type. `DxilRewriteOutputArgDebugInfo` then turns the reference type into a value type to preserve the value mapping when the alloca that `this` points to becomes registers.
> Made the `this` variable in templated struct member functions references

- include/dxc/dxcpix.h
- lib/DxilDia/DxcPixEntrypoints.cpp
- lib/DxilDia/DxcPixLiveVariables_FragmentIterator.cpp
- lib/DxilDia/DxcPixTypes.cpp
- lib/DxilDia/DxcPixTypes.h
- lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp
- tools/clang/unittests/HLSL/PixDiaTest.cpp
Two related sets of changes:
1) Modify the value-to-declare pass to tolerate bitfields, which are detected by their habit of being smaller than the type in which they are contained. The pass produces dbg.declare statements that map each HLSL variable to some storage. With bitfields, that mapping becomes many-to-one, because many bitfields can be stored in the same basic type. Most of the changes are to preserve the size of the bitfield as the code descends the type hierarchy into the underlying basic type, which is what motivates these new "type overrride" parameters to some functions. Complications to watch out for are min16 types, which may or may not be their own purpose-made (16-bit) types depending on whether or not they are enabled.
2) Modify the PIX debug-info API to return enough …
> CP: WinPIX: Changes to support bitfields in PIX's shader debugger (#6219)

- tools/clang/include/clang/SPIRV/AstTypeProbe.h
- tools/clang/lib/SPIRV/AstTypeProbe.cpp
- tools/clang/lib/SPIRV/InitListHandler.cpp
- tools/clang/lib/SPIRV/InitListHandler.h
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/var.init.struct.hlsl
The spir-v backend currently treats each bitfield as a separate member
in the spir-v type when processing an initializer list. This commit
changes that so that it matches the behaviour of the DXIL backend.
In particular, if `{bf1, bf2}` is used to initialize a struct with two
bitfield, then `bf1` and bf2` will be merged into a single field when
constructing the struct.
Fixes #5688
> [SPIRV] Handle bit fields with initializer lists

- include/dxc/DXIL/DxilConstants.h
- lib/DXIL/DxilShaderModel.cpp
This missing default case statement would cause build break when compiling with additional warning settings, such as /Wall /WX in VC++.
Fixes #6287.
(cherry picked from commit 627e400dea0b76c28a2f209110ce49162c41b9e2)
> NFC: Fix switch with missing default case in DxilShaderModel.cpp (#6288)

- lib/DxilDia/DxcPixLiveVariables.cpp
- tools/clang/unittests/HLSL/PixDiaTest.cpp
PIX's code for parsing debug data operates at the module level. When the same global is referenced by multiple functions in a module, that variable is referred to by multiple dbg.value/dbg.declare statements, and those are mapped (by the PIX passes) to multiple fake allocas using its usual scheme. This code was written before libraries were a thing, and wasn't expecting this duplication. A little more attention to the variable's scope fixes the issue.
Also, the changed code's original "return false" broke the whole process of discovering variables with the results that PIX's shader debugger locals window was completely empty. Makes more sense to ignore the one variable and keep going.
(cherry picked from commit 64cdb9cfc07ce37a8156c219c04f2b00f5beb547)
> CP: PIX: Deduplicate globals when referenced in multiple library fns (#6305)

- include/dxc/DXIL/DxilInstructions.h
- utils/hct/hctdb.py
DXIL operations should use is_const=True for constant arguments.  This allows for convenience methods to retrieve the constant value, and could (should, but currently doesn't) result in validation that the argument is constant.
`BarrierByNodeRecordHandle` SemanticFlags argument must be constant.
`MetadataIdx` for both `createNodeOutputHandle` and `CreateNodeInputRecordHandle` must be constant.
> NFC: Fix DXIL op is_const for Barrier and node create handle ops

- lib/DXIL/DxilModule.cpp
- lib/HLSL/DxilValidation.cpp
- tools/clang/test/HLSLFileCheck/shader_targets/raytracing/subobjects_raytracingPipelineConfig1.hlsl
In validator version 1.7 and below, the RaytracingTier1_1 module flag was set on every function if any StateObjectConfig subobject had the AllowStateObjectAdditions flag set. This was incorrect, as the requirement is validated in the runtime based on the use of the subobject instead. Subobjects are removed from the module and placed in RDAT during container serialization, so the requirement would be lost when recomputing the flags in validation. This didn't break validation because flag validation was completely disabled for libraries!
This change fixes this problem, and allows DxilValidation to validate ShaderFlags because they will no longer mismatch due to this issue. Running CollectShaderFlagsForModule is also necessary for collecting per-function shader flags which will be used by …
> Don't set RaytracingTier1_1 based on subobjects; enable flag validation

- include/dxc/Support/Path.h
- tools/clang/tools/dxcompiler/dxcpdbutils.cpp
- tools/clang/unittests/HLSL/CompilerTest.cpp
- tools/clang/unittests/HLSL/TestHeaders/TestPdbUtilsPathNormalizations.h
There was a typo in dxcpdbutils where the normalized file path wasn't actually being used. This change fixes that and adds thorough testing for the DxcPdbUtils path normalization. Also fixed another case where `/dir/my_file` gets normalized to `.\\dir\my_file`.
> Fixed PdbUtils not actually normalizing the file paths

- include/dxc/DXIL/DxilInstructions.h
- utils/hct/hctdb.py
DXIL operations should use is_const=True for constant arguments. This allows for convenience methods to retrieve the constant value, and could (should, but currently doesn't) result in validation that the argument is constant.
`BarrierByNodeRecordHandle` SemanticFlags argument must be constant. `MetadataIdx` for both `createNodeOutputHandle` and `CreateNodeInputRecordHandle` must be constant.
(cherry picked from commit df588beb485958a3ece128bfbeda5fb888e2dfce)
> NFC: Fix DXIL op is_const for Barrier and node create handle ops (#6280)

- lib/DXIL/DxilModule.cpp
- lib/HLSL/DxilValidation.cpp
- tools/clang/test/HLSLFileCheck/shader_targets/raytracing/subobjects_raytracingPipelineConfig1.hlsl
In validator version 1.7 and below, the RaytracingTier1_1 module flag was set on every function if any StateObjectConfig subobject had the AllowStateObjectAdditions flag set. This was incorrect, as the requirement is validated in the runtime based on the use of the subobject instead. Subobjects are removed from the module and placed in RDAT during container serialization, so the requirement would be lost when recomputing the flags in validation. This didn't break validation because flag validation was completely disabled for libraries!
This change fixes this problem, and allows DxilValidation to validate ShaderFlags because they will no longer mismatch due to this issue. Running CollectShaderFlagsForModule is also necessary for collecting per-function shader flags which will be used by …
> Don't set RaytracingTier1_1 based on subobjects; enable flag validation (#6320)

- docs/DXIL.rst
- lib/DXIL/DxilCounters.cpp
- lib/DXIL/DxilOperations.cpp
- lib/DXIL/DxilShaderFlags.cpp
- lib/HLSL/DxilValidation.cpp
- tools/clang/test/LitDXILValidation/illegalDXILOp.ll
- utils/hct/hctdb.py
- utils/hct/hctdb_instrhelp.py
Replace assert on illegal DXIL op with return illegal value. Check the illegal cases in validation.
Fixes #6168
> Fix crash in DXIL.dll caused by illegal DXIL intrinsic.

- tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/lit.local.cfg
Add lit.local.cfg to set unsupported when not dxil-1-8.
> [Test] Limit NodeObjects test to dxil-1-8

- lib/DXIL/DxilModule.cpp
- lib/HLSL/DxilValidation.cpp
- tools/clang/test/HLSLFileCheck/shader_targets/raytracing/subobjects_raytracingPipelineConfig1.hlsl
It turns out that in the prior validator version, if a subobject required DXR 1.1, the DXR 1.1 flag would be set on each function in RDAT output, as well as the global flags. It didn't appear this was the case through a D3DReflect test because that goes through disassembly to assembly step, where subobjects are lost because they aren't in the llvm IR. The previous change assumed this was not the case when the subobjects were removed, but this removal occurs after the RDATWriter constructor, which does the full RDAT serialization since size if required right away.
This restores the detection code and hooks it into DxilModule::ComputeShaderCompatInfo when validator version is in range [1.5, 1.7]. DXR 1.1 was introduced in 1.5, and we no longer tag every function as requiring DXR 1.1 based …
> Fix downlevel validator compatibility with DXR 1.1 flag

- include/llvm/Support/GenericDomTreeConstruction.h
- tools/clang/test/HLSLFileCheck/hlsl/diagnostics/warnings/diagnose_raytracing_payload_access_crash.hlsl
Fix crash if a RayGen shader contains a `while(true)` loop, caused by dominator tree construction not ignoring `nullptr` successor AST nodes which occur in this case.
Also add regression test case.
Fixes #5035.
> Fix crash in dominator tree construction used by DiagnoseRaytracingPayloadAccess

- tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/node-object-export-1.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/node-object-export-2.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/node-object-export-link-1.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/node-object-noinline.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/node-objects-metdata.hlsl
- tools/clang/test/SemaHLSL/hlsl/objects/NodeObjects/node-object-export-1.hlsl
- tools/clang/test/SemaHLSL/hlsl/objects/NodeObjects/node-objects.hlsl
More testing of node shader objects passed as arguments. noinline and export still not work, added as XFail.
For https://github.com/microsoft/DirectXShaderCompiler/issues/6124
(cherry picked from commit 13609db462a21a0c982d171750690062a5e22770)
> [SM68] Add test for node objects as function parameter. (#6231)

- docs/DXIL.rst
- lib/DXIL/DxilCounters.cpp
- lib/DXIL/DxilOperations.cpp
- lib/DXIL/DxilShaderFlags.cpp
- lib/HLSL/DxilValidation.cpp
- tools/clang/test/LitDXILValidation/illegalDXILOp.ll
- utils/hct/hctdb.py
- utils/hct/hctdb_instrhelp.py
Replace assert on illegal DXIL op with return illegal value. Check the illegal cases in validation.
Fixes #6168
(cherry picked from commit 5dee81ce1d38acf5410d40516047d45b3b0d1317)
> Fix crash in DXIL.dll caused by illegal DXIL intrinsic. (#6302)

- lib/HLSL/HLLowerUDT.cpp
- tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/array-in-workgraphrecord-1.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/array-in-workgraphrecord-2.hlsl
In EmitGetNodeRecordPtrAndUpdateUsers, the type will be mutated. And the GEP user of the RecordPtr will be merged at same time. This make things complex because the GEP index need to be updated since type is mutated.
To make things easier, merge the GepUse after mutate type.
Fixes #6223
(cherry picked from commit 823125b32ef92e76721023d6477e528ac2ea5a07)
> [DXIL generation] Merge GepUse last to avoid crash in EmitGetNodeRecordPtrAndUpdateUsers

- tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/lit.local.cfg
- tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/node-objects-metdata.hlsl
- tools/clang/test/LitDXILValidation/illegalDXILOp.ll
- tools/clang/test/lit.cfg
dxil-1-* will be added as available_features for lit config.
There're 3 ways to use it.
1. Whole file limit use required dxil-1-8
2. Single RUN line with %if dxil-1-8 %{ %}
3. Whole folder with check dxil-1-8 to set config.unsupported in lit.local.cfg
> [lit] support dxil version check in lit test

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
- tools/clang/unittests/HLSLExec/ShaderOpArith.xml
This PR fixes several issues in the `ExecutionTest::DerivativesTest`:
- Use 1D quad order only when writing 1D derivative results. 2D results are expected in standard 2D form.
- Use separate derivatives verification function for SM 6.6 compute, mesh and amplification shaders. In these cases the quad layout is well defined, and so are the expected results. There is only one possible result for `ddx_fine`/`ddy_fine` and two for `ddx_coarse`/`ddy_coarse`. This is different from pixel shaders where the quad layout can vary quite a bit, and so do the expected results.
- Change the expected values to match results for texture pixel `(2,2)`
- Adjust mesh shader dispatch dimensions to make sure `X * Y * Z <= 128`
- Use same logic (shared function) to calculate center pixel for compute, mesh and …
> CP: Fix ExecutionTest::DerivativesTest issues (#6311)

- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/CodeGenSPIRV/spv.inline.builtin.enum.hlsl
The SPIR-V backend uses `ValidateAttributeIntArg` for the `vk::ext_builtin_input` and `vk::ext_builtin_output` attrs, as well as some others. It is convenient for users to be able to pass in an enum value to this attribute, for example:
```
enum class BuiltIn {
HelperInvocation = 23
};
[[vk::ext_builtin_input(BuiltIn::HelperInvocation)]]
static const bool gl_HelperInvocation;
```
If you think `ValidateAttributeIntArg` *should* warn if a user passes in an enum value, I'll create a separate function for validating `vk::ext_builtin_input` instead.
Fixes #6337
> [Sema] Allow int arguments for attributes to be enum values

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
- tools/clang/unittests/HLSLExec/ShaderOpArith.xml
This PR adds execution testing to wave range size attributes, on top of the already existing WaveSizeTest HLK test.
It implements the necessary coverage of the new wave range size attribute, as described in the hlsl-specs here: https://github.com/microsoft/hlsl-specs/blob/main/proposals/0013-wave-size-range.md#execution-testing
Fixes #6347
> [ExecutionTest] Add Wave Range Size HLK Tests

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
This PR adds execution testing to wave range size attributes, on top of the already existing WaveSizeTest HLK test.
It implements the necessary coverage of the new wave range size attribute, as described in the hlsl-specs here:
https://github.com/microsoft/hlsl-specs/blob/main/proposals/0013-wave-size-range.md#execution-testing Fixes #6347
---------
Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
(cherry picked from commit b6b6b6d903aaae840aebf0779061359969e28a30)
> [ExecutionTest] Add Wave Range Size HLK Tests (#6348)

- tools/clang/test/HLSLFileCheck/validation/callgraph/barrier-group-in-nested-fn-vs-lib68.hlsl
- tools/clang/test/HLSLFileCheck/validation/callgraph/deriv-in-nested-fn-vs-lib68.hlsl
Issue #6367 identifies a problem with the auto-dxilver logic based on -T target option in %dxc part when using FileCheckerTest.cpp.
This change adds a manual %dxilver 1.8 to two tests that run into this problem, as a workaround.
> Add dxilver to tests using -Vd to work around auto-dxilver bug

- tools/clang/test/HLSLFileCheck/validation/callgraph/barrier-group-in-nested-fn-vs-lib68.hlsl
- tools/clang/test/HLSLFileCheck/validation/callgraph/deriv-in-nested-fn-vs-lib68.hlsl
Issue #6367 identifies a problem with the auto-dxilver logic based on -T target option in %dxc part when using FileCheckerTest.cpp.
This change adds a manual %dxilver 1.8 to two tests that run into this problem, as a workaround.
(cherry picked from commit bbcbb2de14a67b5d8f4a0bff9b9db274b27b7fc5)
> Add dxilver to tests using -Vd to work around auto-dxilver bug (#6369)

- utils/version/CMakeLists.txt
- utils/version/gen_version.py
Do not use `git describe`, it is using tags which might be out of date and unrelated to the current build and version.
> Use git rev-parse to get last commit sha

- include/dxc/DXIL/DxilMetadataHelper.h
- include/dxc/DXIL/DxilNodeProps.h
- include/dxc/DxilContainer/RDAT_LibraryTypes.inl
- lib/DXIL/DxilMetadataHelper.cpp
- lib/DxilContainer/DxilContainerAssembler.cpp
- tools/clang/lib/CodeGen/CGHLSLMS.cpp
- tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/array-in-workgraphrecord-1.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/array-in-workgraphrecord-2.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/node-objects-metdata.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/empty_broadcasting_nodes.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/empty_thread_nodes.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/node-record-alignment-16bit.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/node-record-alignment.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/case001_dispatchgrid_shader.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/case014_getrecordcount_nodeinputarray.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/case030_outputcomplete_nodeoutput.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/case037_finishedcrossgroupsharing.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/sparsenodes.hlsl
This change adds NodeRecordType alignment field to RDAT to make it possible to validate pointer and stride alignment in the runtime.
This includes a change to DXIL metadata to preserve the record alignment without requiring recovery by looking for GetNodeRecordPtr.
Fixes #6270
(cherry picked from commit 66ba5a152964fe4559a1658194cc9ee5aaac8bcb)
> Add alignment to NodeRecordType including DXIL metadata update (#6279)

- utils/version/gen_version.py
Do not use `git describe`, it is using tags which might be out of date and unrelated to the current build and version.
(cherry picked from commit aaab2a708a7d70006674f52b2f72739d63f98fe2)
> CP: Use git rev-parse to get last commit sha (#6366)

- include/dxc/Support/HLSLOptions.h
- include/dxc/Support/HLSLOptions.td
- include/llvm/Support/TimeProfiler.h
- lib/DxcSupport/HLSLOptions.cpp
- lib/Support/TimeProfiler.cpp
- tools/clang/include/clang/Frontend/CodeGenOptions.def
- tools/clang/include/clang/Frontend/FrontendOptions.h
- tools/clang/test/DXC/ftime-trace-granularity.hlsl
- tools/clang/tools/dxcompiler/dxcompilerobj.cpp
This commit adds a new optional -ftime-trace-granularity option that is already implemented in llvm-project. This change is a surgical port of an existing feature from the upstream llvm-project repo into the DXC codebase.
The following commits in the llvm-project repo were copied and followed for this change. Clean cherry picks were not possible due to the differences in repos like change of file locations and other dependant changes made in the repo.
*** Adds the granularity configuration setting ***
'Time profiler: small fixes and optimizations'
Commit: 26536728591d5fdac373ef535ae122b873f73292
*** Wires up the commandline option -ftime-trace-granularity to the TraceProfiler code ***
'[Support] Fix -ftime-trace-granularity option'
Commit: 4fdcabf259c4ab94654e6cd5d95d0e0313159c70
Fixes …
> Implement -ftime-trace-granularity option to set time granularity value for the time profiler

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/cf.return.void.hlsl
Even when a function's return type is void, it is still valid to return an void expression, and that expression should be evaluated before the function is terminated to match DXIL behavior.
Although I don't see this explicitly mentioned in HLSL documention, the cpp reference states (abridged):
> `return expression;`
> Evaluates the expression, terminates the current function and returns the result of the expression to the caller, after implicit conversion to the function return type.
> In a function returning void, the return statement with expression can be used, if the expression type is void.
Fixes #5464
> [SPIR-V] Evaluate void return expressions

- tools/clang/lib/SPIRV/InitListHandler.cpp
- tools/clang/test/CodeGenSPIRV/var.init.struct.hlsl
Because the layout rule was not propagated from the initializer object to the OpCompositeExtract when decomposing a struct in the InitListHandler, it could result in cases where the result types were mismatched.
Fixes #5625
> [SPIR-V] Set layout rule when decomposing struct

- tools/clang/include/clang/SPIRV/SpirvBuilder.h
- tools/clang/lib/SPIRV/SpirvBuilder.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/method.buffer.load.offset.error.hlsl
The `Load` function's optional `Offset` parameter must be an immediate value to match the behavior of the DXIL backend. Further, the existing logic in the SPIR-V backend to evaluate it as a variable offset generated invalid SPIR-V that violated the `VUID-StandaloneSpirv-Offset-04663` rule:
> Image operand Offset must only be used with OpImage*Gather instructions
The logic for processing the argument as a variable value has been removed and replaced with an error message that matches DXIL's.
Note that `handleOffsetInMethodCall` is left unmodified because it is also used to process HLSL `.Gather()` calls, which are lowered to `OpImageGather` SPIR-V instructions and can therefore accept non-const `Offset`s as image operands.
It would be nice to move this error message earlier in execution …
> [SPIR-V] Disallow variable offsets in texture Load

- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp
- tools/clang/lib/Sema/SemaHLSLDiagnoseTU.cpp
- tools/clang/test/CodeGenSPIRV/semantic.hull-input.size-mismatch.hs.hlsl
- tools/clang/test/HLSLFileCheck/samples/SimpleHs12.hlsl
The check was done in the DXIL backend, and not in the SPIR-V backend. This causes the issue to be ignored on the SPIR-V side. Moved the check earlier to SEMA so a single check works for both backends.
I had to split the existing HLSL check as it doesn't support having 2 run lines (AFAIK).
Fixes #3739
> sema: check input patch size mismatch earlier.

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/ternary-op.short-circuited-cond-op.sampler-state.hlsl
`castToType` can return null after emitting an error, so `doShortCircuitedConditionalOperator` should exit when true or false branches failed to compile, otherwise it will crash inside `createStore`.
This can be reproduced with in the main branch with a ternary operator selectin a `SamplerState`, which should only emit an error but crashes with a SIGSEGV:
https://godbolt.org/z/j9EGGxWTh
`$ dxc -spirv -E PSMain -T ps_6_0 -HV 2021`
```hlsl
SamplerState SamplerA;
SamplerState SamplerB;
Texture2D Tex;
bool WhichSampler;
float4 SampleTex() {
return Tex.Sample(WhichSampler ? SamplerA : SamplerB, (float2)0);
}
float4 PSMain() : SV_Target0 {
return SampleTex();
}
```
> [SPIR-V] Fix null pointer crash in short-circuit ternary op.

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
The `ComputeSampleTest` is verifying `Sample` and `CalculateLevelOfDetail` intrinsics calls on a texture in compute, mesh and amplification shaders. The test is set up in a way that the reported LOD values should be increasing as the X and Y coordinates increase.
However, since the test results are stored in quad z-order, and it is perfectly valid for the X-derivative-LOD to decrease when going from top-right to bottom-left pixel in a quad because in this case the X coordinate decreases. Therefore, the test needs verify the LOD values are increasing everywhere except for the bottom-left quad pixel (every output with `index % 4 == 2`).
Previously, the test coincidentally worked for compute shaders because it uses thread group of 336 and the 1/336 difference between 0 and pixel 1's X …
> Fix verification in ExecutionTest::ComputeSampleTest

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/test/CodeGenSPIRV/vk.push-constant.static.hlsl
Struct lowering is slightly different for push constants, and we didn't checked if the field was static or not.
In SPIR-V, when a field is const static, we either replace all loads by a the immediate (when usage is `Struct::field`), or create a global variable we initialize to the correct value and reference instead. The field is then ignored from the struct definition, and this variable is used.
This hasn't changed with this commit, I just made push-buffers use the same logic.
Fixed #6006
> [SPIR-V] Fix static const in push constants

- tools/clang/lib/SPIRV/InitListHandler.cpp
- tools/clang/test/CodeGenSPIRV/initializelist.undefined.hlsl
The list initializer code was not always checking the initializer list size before reading it, causing crashes.
Checking the list size led me to discover paths in which the code could crash by dereferencing null pointers.
Added a few guards to check if a subpath failed before continuing.
Fixes #6143
> [SPIR-V] Fix list initializer code

- tools/clang/lib/SPIRV/SpirvBuilder.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/intrinsics.get-attribute-at-vertex.non-pixel-shader.hlsl
This builtin should only be called from a pixel shader.
> [SPIR-V] Only allow GetAttributeAtVertex in PS

- lib/DxcSupport/Unicode.cpp
If last arg lpUsedDefaultChar is non-null, the function must set this value to true or false. WideToEncodedString conditionally passes in a pointer to 'usedDefaultChar', which was not getting written to, and causing ubsan to fail on reading an invalid boolean value:
```
.../lib/DxcSupport/Unicode.cpp:156:14: runtime error: load of value 208, which is not a valid value for type 'BOOL' (aka 'bool')
```
> Fix ubsan failure on uninitialized read of bool param to WideCharToMultiByte

- tools/clang/unittests/HLSL/PixTest.cpp
Use BlobToUtf8 which handles the case of InternalDxcBlobEncoding_Impl not having a null-terminated pointer when converting to string.
Effectively a repeat of this PR:
https://github.com/microsoft/DirectXShaderCompiler/pull/5973
> Fix asan heap overflow in PixTests (again)

- cmake/modules/HandleLLVMOptions.cmake
This adds the same 'no-sanitize=alignment' option in the branch for both asan and ubsan that I missed as part of this PR:
https://github.com/microsoft/DirectXShaderCompiler/pull/5803
> Disable ubsan alignment errors properly

- lib/HLSL/HLMatrixLowerPass.cpp
- tools/clang/test/DXC/matrix_crash.ll
When lowering an hl.cast, when the operand was an undef matrix, the pass would insert a call to a mat2vec stub, but since the undef value is not an alloca, it never gets handled, and the call to the temporary stub remains. Since the stub FunctionVal gets deleted, when the instruction is accessed in a future pass, it reads a dangling pointer.
The fix is to handle undef similarly to how constant 0 is handled, and to return an undef vector from lowerHLCast.
Fixes #6423
> Fix HLMatrixLowerPass leaving call to dangling FunctionVal

- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/SemaHLSL/operator-overload.hlsl
Use identifier name without check the identifier exists will cause crash.
Fixes #6426
> [Sema] Check FunctionDecl has identifier before getName.

- include/llvm/ADT/SparseBitVector.h
- include/llvm/Analysis/IVUsers.h
- include/llvm/CodeGen/MachineBasicBlock.h
- include/llvm/CodeGen/MachineFunction.h
- include/llvm/CodeGen/SelectionDAG.h
- include/llvm/CodeGen/SlotIndexes.h
- include/llvm/IR/BasicBlock.h
- include/llvm/IR/Function.h
- include/llvm/IR/Instruction.h
- include/llvm/IR/Module.h
- include/llvm/Transforms/Utils/SymbolRewriter.h
- tools/clang/include/clang/StaticAnalyzer/Core/BugReporter/BugReporter.h
This is a temporary workaround until we fix:
https://github.com/microsoft/DirectXShaderCompiler/issues/6446
This should allow us to enable asan/ubsan checks:
https://github.com/microsoft/DirectXShaderCompiler/pull/6428
> Disable "downcast of address" UBSAN runtime error

- include/dxc/Support/SPIRVOptions.h
- lib/DxcSupport/HLSLOptions.cpp
- tools/clang/include/clang/SPIRV/FeatureManager.h
- tools/clang/lib/SPIRV/CapabilityVisitor.cpp
- tools/clang/lib/SPIRV/FeatureManager.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/opt.denorm.error.hlsl
- tools/clang/test/CodeGenSPIRV/opt.denorm.hlsl
The -denorm option allows the shader to select the desired behavior with respect to denormal values.
Note that this can't take advantage of the SPIRV-Tools capability trimming pass for the same reasons as described in: https://github.com/microsoft/DirectXShaderCompiler/pull/6248#discussion_r1481073348
Fixes #6434
> [SPIR-V] Add support for Denorm Mode

- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/lib/Sema/SemaDecl.cpp
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/SemaHLSL/hlsl/semantics/semantic.vertex.position.hlsl
- tools/clang/test/SemaHLSL/hlsl/semantics/semantic.vertex.position.nowarn.hlsl
Before SM4, POSITION was equivalent to today's SV_Position. However, as HLSL moved to system semantics (SV_), the support for those old semantics has been deprecated.
Some like VFACE are now completely forbidden, but others like POSITION or COLOR have been handled differently by FXC and DXC.
Today, usage of POSITION in place of SV_Position is probably a mistake as POSITION is now considered to be a user-defined semantic.
This commit adds a warning when POSITION is used as an output semantic for a vertex shader, as most cases should be the result of a mistake. If this is expected, the warning can be disabled by using `-Wno-dx9-deprecation`.
Fixes #3742
> Sema: warn when POSITION[0] is used intead of SV_Position

- docs/DXIL.rst
- include/dxc/DXIL/DxilConstants.h
- lib/HLSL/DxilValidation.cpp
- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/HLSLFileCheck/hlsl/functions/attribute/patch_constant_function_missing.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/types/conversions/attributes_Mod.hlsl
- tools/clang/test/SemaHLSL/attributes.hlsl
- tools/clang/test/SemaHLSL/recursion/library_hull_recursion.hlsl
- tools/clang/unittests/HLSL/ValidationTest.cpp
- utils/hct/hctdb.py
According to the documentation: "A hull shader is implemented with an HLSL function, and has the following properties: [...] The shader output is between 1 and 32 control points".
https://learn.microsoft.com/en-us/windows/win32/direct3d11/direct3d-11-advanced-stages-tessellation#hull-shader-stage
This change adds a check to verify that the outputcontrolpoints attribute is set on Hull shaders and has an argument in the valid range.
Fixes #3733 (by making the error consistent between backends)
> Require valid outputcontrolpoints on Hull shader

- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/SemaHLSL/operator-overload.hlsl
Use identifier name without check the identifier exists will cause crash.
Fixes #6426
---------
Co-authored-by: Tex Riddell <texr@microsoft.com>
Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
(cherry picked from commit 7581ff4d297d124b340d6715b709f1c423909ca5)
> [Sema] Check FunctionDecl has identifier before getName. (#6439)

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/intrinsics.dot2add.hlsl
Add support for the Shader Model 6.4 intrinsic dot2add which was missing from the SPIR-V backend.
Fixes #6442
> [SPIR-V] Implement dot2add intrinsic function

- lib/Support/MSFileSystemBasic.cpp
- tools/clang/unittests/HLSL/MSFileSysTest.cpp
d3dcommon.h seems to be canonical path name in Win SDK
Windows Kits/10/Include/10.0.22621.0/um/d3dcommon.h
so use d3dcommon.h rather than D3Dcommon.h
> fix non-portable include path

- lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
- tools/clang/test/DXC/unreferenced_struct_selft_assignment_crash.hlsl
When deleting an unused memcpy, ScalarReplAggregatesHLSL was attempting to delete both the target and the source of the memcpy without first checking if they were both same, resulting in a double-delete.
> Fix ASAN use-after-free on unreferenced self-assignment of struct instance

- tools/clang/test/SemaHLSL/hlsl/semantics/semantic.vertex.position.hlsl
- tools/clang/test/SemaHLSL/hlsl/semantics/semantic.vertex.position.nowarn.hlsl
These are semantic verification tests, the `-spir-v` option is not necessary. 
It also breaks our internal test passes for builds that do include SPIR-V backend.
> Remove -spirv from new HLSL Sema tests

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/test/CodeGenSPIRV/op.pushconstant.access.bitfield.hlsl
- tools/clang/test/CodeGenSPIRV/op.uniform.access.bitfield.hlsl
When implementing bitfields, we miss a code path which lowered the AST type to the SPIR-V type, and thus failed to propagate the bitfield information.
This commit addresses that.
Fixes #6409
> [SPIR-V] Fix bitfields with RWStructured & Push-constants

- lib/DxcSupport/HLSLOptions.cpp
- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/test/DXC/disable_paq.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/payload_qualifier/access.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/payload_qualifier/general.hlsl
The original payload access qualifiers change disallowed disabling them on 6.8+ versions. This wasn't an intended feature of 6.8. We'd prefer to maintain the ability to disable these when needed to avoid issues that might crop up.
This change extends respect of the disable-payload-qualifiers flag for all versions. It rewords the warning that is produced when they are encountered when disabled to be more applicable. Tests are also added to verify that the implicit enabling in 6.7+ works in the basic cases and also that disabling in the 6.7+ cases works as well.
Fixes #6462
> Allow disabling payload access qualifiers in 6.8+

- lib/DxilDia/DxilDiaSession.cpp
backslash is not portable, so use slash instead.
> fix #include path separator from backslash to slash

- lib/DXIL/DxilNodeProps.cpp
- lib/HLSL/DxilValidation.cpp
- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/mesh-node-input-parameters.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/mesh-node-invalid-input-parameters.hlsl
- tools/clang/test/HLSLFileCheck/validation/mesh-node-inputs.hlsl
- tools/clang/test/HLSLFileCheck/validation/mesh-node-inputs.ll
- tools/clang/test/SemaHLSL/hlsl/workgraph/attribute_diags.hlsl
- tools/clang/test/SemaHLSL/hlsl/workgraph/dispatchgrid_diags.hlsl
- tools/clang/test/SemaHLSL/hlsl/workgraph/node_input_array.hlsl
- tools/clang/test/SemaHLSL/hlsl/workgraph/zero_sized_node_record.hlsl
This allows the intersection of system values shared by mesh shaders and broadcasting nodes to be used by allowing mesh nodes to accept most input values that broadcasting nodes do. The exception is the writable DispatchRecords. It also involved rewording some error messages to account for mesh nodes which required changing some existing tests to just accept the new diagnostic. New tests were added to ensure that all the system values are accepted and treated properly and also that invalid usages were rejected.
Fixes #6470
> Enable system values for mesh nodes

- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp
- tools/clang/lib/Sema/SemaHLSLDiagnoseTU.cpp
- tools/clang/test/CodeGenDXIL/semantic.hull-output.size-mismatch.hs.hlsl
- tools/clang/test/CodeGenSPIRV/semantic.hull-output.size-mismatch.hs.hlsl
- tools/clang/test/HLSLFileCheck/samples/SimpleHs12.hlsl
DXIL had a check in the backend for those values.
Moving it to Sema to share it between DXIL and SPIR-V.
Fixes #6387
> [Sema] Move outputcontrolpoints check to Sema

- tools/clang/lib/SPIRV/AlignmentSizeCalculator.cpp
- tools/clang/lib/SPIRV/AlignmentSizeCalculator.h
- tools/clang/test/CodeGenSPIRV/op.uniform.access.bitfield.array.hlsl
- tools/clang/test/CodeGenSPIRV/vk.layout.struct.bitfield.array.hlsl
The struct size & alignment computations were wrong when
bitfields were in use. This was due to a mismatch between size
computations at the AST level, and at the SPIR-V level.
This commit adds logic to correctly compute bitfields offsets on
an AST struct.
**note: there are 2 commits in this PR, one that moves code around with no change, and one that adds the logic. To help you review.**
Fixes #5648
> [SPIR-V] Fix struct size computation with bitfields

- tools/clang/lib/SPIRV/PervertexInputVisitor.cpp
- tools/clang/test/CodeGenSPIRV/intrinsics.get-attribute-at-vertex.cbuf.var.hlsl
Some SPIR-V types are not direct translations of an AST type, hence they don't have an AST type attached to it.
The code didn't checked for this possibility when visiting all variables.
Fixes #2955
> [SPIR-V] Fix crash in GetAttributeAtVertex impl.

- lib/DXIL/DxilModule.cpp
- lib/DXIL/DxilOperations.cpp
- lib/HLSL/DxilValidation.cpp
- tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/mesh-node-invalid-set-mesh-output-counts.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/mesh-node-set-mesh-output-counts.hlsl
- utils/hct/hctdb.py
Allow the usage of SetMeshOutputCounts() in mesh launch node shaders and no other launch type nodes. This requires identifying the op initially as permitted in node shaders, but restraining that permission later on. Given the availability of launch type and opcode information, the locations for doing that were limited. Future implementation might opt to encode the launch type in the stage mask or else at least temporarily use a different opcode for a SetMeshOutputCounts call within a node shader.
Fixes #6473
> Support SetMeshOutputCounts in mesh nodes

- tools/clang/unittests/HLSL/ValidationTest.cpp
Error message was updated in #6196 which cause test fail on older validator.
Since this issue is only caused by error message update, the validation itself is still the same.
The compiler didn't generate anything that behaves badly with older validators.
So just limit these tests to sm6.8+ to make it work on older validator.
> [Test] skip test for older validator which check different value.

- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/include/clang/Sema/Sema.h
- tools/clang/lib/Sema/SemaChecking.cpp
- tools/clang/lib/Sema/SemaExpr.cpp
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/CodeGenSPIRV/intrinsics.get-attribute-at-vertex.cbuf.var.hlsl
- tools/clang/test/CodeGenSPIRV/intrinsics.get-attribute-at-vertex.s.funcParam.hlsl
- tools/clang/test/CodeGenSPIRV/intrinsics.get-attribute-at-vertex.s.funcParam.neg.hlsl
- tools/clang/test/SemaHLSL/getattribute-at-vertex.legal.hlsl
- tools/clang/test/SemaHLSL/getattribute-at-vertex.legal.nointerpolation.call.hlsl
- tools/clang/test/SemaHLSL/getattribute-at-vertex.missing.nointerpolation.call.dxil.hlsl
- tools/clang/test/SemaHLSL/getattribute-at-vertex.missing.nointerpolation.call.hlsl
- tools/clang/test/SemaHLSL/getattribute-at-vertex.missing.nointerpolation.dxil.hlsl
- tools/clang/test/SemaHLSL/getattribute-at-vertex.missing.nointerpolation.hlsl
This commit adds new sema checks for SPIR-V to restrict the scope of the feature: the `nointerpolation` attribute is now required on all parameters used in GetAttributeAtVertex, and doesn't propagage magically to parent/child functions.
The current accepted cases this now blocks were mostly broken later in the codegen, so this should be an acceptable 'regression'.
Related to #6220
Fixes #6384, #6383, #6382
> [SPIR-V][Sema] Requires nointerpolation on GetAttributeAtVertex param #0

- tools/clang/test/CodeGenHLSL/mesh-val/multipleSetMeshOutputCounts.hlsl
The multipleSetMeshOutputCounts.hlsl test file needs to be gated on dxil validator version 1.9
> Gate experimental mesh test on validator version 1.9

- tools/clang/tools/dxclib/dxc.cpp
When codegen is broken, and spirv-dis fails, DXC doesn't return any error, and simply displays nothing, and returns 0.
> [SPIR-V] fix silent failure if disassembly fails

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
- tools/clang/unittests/HLSLExec/ShaderOpArith.xml
Invalid thread group size testing is included in the compiler/validator tests (PR #6332, commit 696a13a). It does not belong in the execution tests because is it not verifying the driver execution results. The shaders with invalid thread group sizes fail validation and cannot be executed.
Also fixing compile warning and override defines in the derivatives test HLSL code.
Note that the test is incorrectly using the term `dispatch size` instead of `thread group size`.
Fixes internal bug #49806539. Reported from RITP pass.
> DerivativesTest: Remove invalid thread group size test cases 

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
- tools/clang/unittests/HLSLExec/ShaderOpArith.xml
Invalid thread group size testing is included in the compiler/validator tests (PR #6332, commit 696a13a). It does not belong in the execution tests because is it not verifying the driver execution results. The shaders with invalid thread group sizes fail validation and cannot be executed.
Also fixing compile warning and override defines in the derivatives test HLSL code.
Note that the test is incorrectly using the term `dispatch size` instead of `thread group size`.
Fixes internal bug #49806539. Reported from RITP pass.
---------
(cherry picked from commit 14ec4b49d419195b787d41464d4a4489bba87bb2)
> DerivativesTest: Remove invalid thread group size test cases  (#6496)

- tools/clang/tools/dxa/dxa.cpp
SIZE_T is unsigned long for x86 while size_t is unsigned int for x86. Cast SIZE_T to size_t to avoid integer mismatch warning.
> [ClangCL] fix x86 only warning

- tools/clang/include/clang/SPIRV/SpirvBuilder.h
- tools/clang/lib/SPIRV/InitListHandler.cpp
- tools/clang/lib/SPIRV/SpirvBuilder.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/op.struct.access.bitfield.sized.hlsl
SPIR-V supported OpBitFieldInsert on all integer types. But Vulkan requires the operands to be 32bit integers.
This means we need to emulate this instruction for types other then i32.
This PR only adds emulation for OpBitFieldInsert. The next PR will add support for emulating OpBitFieldExtract,
Related to #6327
> [SPIR-V] Emulate OpBitFieldInsert for type != i32

- tools/clang/include/clang/Basic/Diagnostic.h
- tools/clang/include/clang/Frontend/TextDiagnosticPrinter.h
- tools/clang/lib/CodeGen/CodeGenAction.cpp
Make TextDiagnosticPrinter::setPrefix a virtual function in base class DiagnosticConsumer. This allows us to avoid using dynamic_cast in BackendConsumer::DxilDiagHandler, required for codebases that do not enable RTTI. This is also the only place in the codebase that uses RTTI (AFAICT).
> Replace dynamic_cast with virtual call

- include/dxc/DXIL/DxilShaderModel.h
- tools/clang/include/clang/Basic/DiagnosticGroups.td
- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/include/clang/Sema/Sema.h
- tools/clang/lib/Sema/SemaChecking.cpp
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/lib/Sema/SemaHLSLDiagnoseTU.cpp
- tools/clang/lib/Sema/SemaOverload.cpp
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/case118_barrier_objectarg.hlsl
- tools/clang/test/HLSLFileCheck/validation/callgraph/barrier-group-in-nested-fn-vs-lib68.hlsl
- tools/clang/test/SemaHLSL/hlsl/intrinsics/barrier/barrier-cs-errors.hlsl
- tools/clang/test/SemaHLSL/hlsl/intrinsics/barrier/barrier-cs-local-errors.hlsl
- tools/clang/test/SemaHLSL/hlsl/intrinsics/barrier/barrier-cs.hlsl
- tools/clang/test/SemaHLSL/hlsl/intrinsics/barrier/barrier-node-errors.hlsl
- tools/clang/test/SemaHLSL/hlsl/intrinsics/barrier/barrier-node.hlsl
- tools/clang/test/SemaHLSL/hlsl/intrinsics/barrier/barrier-vs-errors.hlsl
- tools/clang/test/SemaHLSL/hlsl/intrinsics/barrier/barrier-vs.hlsl
- tools/clang/test/SemaHLSL/hlsl/objects/NodeObjects/node-objects.hlsl
- tools/clang/test/SemaHLSL/hlsl/objects/texture/CalculateLODExtraDiag.hlsl
- tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp
Context-specific diagnostics are warnings with DefaultError, since in theory they could be dead code at this stage.
There were some changes to existing Sema diagnostic hooks along the way.
SemaHLSLDiagnoseTU.cpp - HLSLMethodCallDiagnoseVisitor
- extend to non-method calls and pass CallExpr
- instead of skipping when call reached from multiple entry/export functions, pass locallyVisited flag for skipping of redundant diags not dependent on entry properties.
- use llvm::SmallPtrSet for DiagnosticCalls
- capture launch type for entry and pass it down
Replace DiagnoseHLSLMethodCall hook with CheckHLSLFunctionCall:
Move hook into Sema::CheckFunctionCall in SemaChecking.cpp to be general to either a function call or a method call.
Refactor existing code in DiagnoseHLSLMethodCall into …
> Add barrier MemoryTypeFlags and SemanticFlags diagnostics

- .github/CODEOWNERS
In release branches we've added enforcement of AskMode where approval is required before merging. This just adds the requisite file to the `main` branch so that it will appear in future release branches. It DOES NOT apply the branch protection policy, which is a setting controlled in GitHub.
There is no policy change to contributions to main with this change.
> Add CODEOWNERS to main

- lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
- tools/clang/test/DXC/scalarrepl-param-hlsl-replace-zero-recurse-to-float.ll
- tools/clang/test/DXC/scalarrepl-param-hlsl-replace-zero-recurse-to-int.ll
During memcpy replacement, the scalarrepl-param-hlsl pass will replace certain uses of a zero-initialized global variable.  The pass uses a recursive algorithm to replace uses of that global by a zero value. The current code expects the recursion to bottom out in an aggregate type. But it can bottom out in a scalar integer or scalar float.
This patch fixes the scalar cases.
Lit-based pass tests are included.
> Fix recursive zero replacement bottoming out in scalars.

- lib/HLSL/DxilPreparePasses.cpp
- tools/clang/test/CodeGenDXIL/hlsl/shaders/node/mesh-node.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/RDATUsageMaskRepro.hlsl
- tools/clang/test/HLSLFileCheck/d3dreflect/mesh-node-rdat.hlsl
Previously, the step that is typically taken to set the usage mask for signature elements was not executed, due to mesh nodes being defined in library shaders. The mask was only written for non-lib shaders. Now that mesh nodes exist in library shaders, we need to allow usage masks to be set for mesh nodes, even though they are in library shaders.
This PR adds an alternative case for mesh nodes. In this case, usage masks are written for all mesh nodes defined in a library shader, by iterating over all functions declared in a library module. An accompanying test was written that shows the RDAT now contains the usage mask, and it is non-null. 
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/6521
> Write usage masks for mesh nodes in libraries into RDAT

- tools/clang/test/DXC/ftime-trace-granularity.hlsl
ftime-trace-granularity test was failing in test runs due to the configured time filter value being too small.  The latest test run was recording duration times of 322308 which is larger than the test's specified filter value of 99999 causing timings to not be filtered out.
The test is now updated to have a filter value of 999999, which should properly filter out timings.
Fixes #6528
> Increase filter time value for failing ftime-trace-granularity test

- tools/clang/test/CodeGenDXIL/hlsl/shaders/node/mesh-node-incorrect-input-record-type-validation.ll
- tools/clang/test/CodeGenDXIL/hlsl/shaders/node/mesh-node-no-invalid-input-record.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/shaders/node/mesh-node-no-outputs.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/shaders/node/mesh-node-no-outputs.ll
- tools/clang/test/CodeGenDXIL/hlsl/shaders/node/mesh-node-rwdispatch-allowed.hlsl
These mesh nodes tests were missing REQUIRES: dxil-1-9 to prevent them from running on down-level validator test pass.  This change fixes that and should unblock the internal build.
> Add missing REQUIRES: dxil-1-9 to tests

- lib/HLSL/HLSignatureLower.cpp
MS outputs require vertex or primitive ID parameters and so do not require an undefined value to be set to initialize the parameter value This just adds comments to clarify the potentially confusing code.
Fixes #6486
> Add clarifying comments for default vtx/prim IDs

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/test/CodeGenSPIRV/meshshading.ext.amplification.hlsl
- tools/clang/test/CodeGenSPIRV/meshshading.ext.triangle.mesh.hlsl
The existing logic from `VK_NV_mesh_shader` was incorrectly adapted for the `VK_EXT_mesh_shader` implementation when it comes to the handling of payloads as in/out variables. Because `TaskPayloadWorkgroupEXT` must be applied to a single global `OpVariable` for each task/mesh shader, the struct should not be flattened. Further, Location assignment is not necessary for these input and output variables, so the usual reason for flattening structs does not apply.
This change now removes the inner struct member global variables and ensures the parent payload is decorated with `TaskPayloadWorkgroupEXT`. Note that for amplification/task shaders, the payload variable is created with the `groupshared` decl, and then its storage class needs to be updated when that variable is used as a parameter to …
> [SPIR-V] Fix mesh payload global variable for VK_EXT_mesh_shaders

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
- tools/clang/test/CodeGenSPIRV/rich.debug.cbuffer.dxlayout.hlsl
When the requested constant buffer layout is DX, some type lowering can become complex (Nx1 matrices for ex). To simplify the lowering, the backend "clones" those variables:
- on one end, we expose the correct layout
- but then, we copy this to a local variable to have a different layout compatible with the operations we usually do on such types.
This means the type can sometimes be an HybridStructType, which is not completely lowered, or a normal lowerer SPIR-V type. Both should be allowed, but some codepaths had to be updated to reflect this.
> [SPIR-V] Fix debug instruction with cbuffer + FXC

- tools/clang/include/clang/SPIRV/SpirvBuilder.h
- tools/clang/include/clang/SPIRV/SpirvInstruction.h
- tools/clang/lib/SPIRV/SpirvBuilder.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvInstruction.cpp
- tools/clang/test/CodeGenSPIRV/op.struct.access.bitfield.sized.read.hlsl
This is a follow up to #6491 which adds emulation for OpBitField*Extract
This is required because Vulkan requires OpBitField*Extract operands to
be 32-bit integers.
Fixes #6327
> [SPIR-V] Emulate OpBitFieldExtract for type != i32

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/cast.bitwidth.hlsl
- tools/clang/test/CodeGenSPIRV/cast.flat-conversion.literal-initializer.hlsl
- tools/clang/test/CodeGenSPIRV/cast.struct-to-int.hlsl
OpConvertFToU and FToS convert numerically from floating point to integer, with rounding toward 0.0, matching the defined behavior of HLSL without any need for an initial bitwidth conversion from floating point to floating point, which can result in incorrect rounding behavior (see #6501).
Note that behavior is undefined if the target type is not wide enough to hold the converted value, however this was also true with an initial bitcast (because an N-bit FP can hold values outside the range of an N-bit int), and I can't come up with any case where an intial truncation would result in correct defined behavior where this straight conversion would be undefined since the precision will inevitably be lost anyways.
Fixes #6501
> [SPIR-V] Remove bitcast from float->int conversion

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/intrinsics.64bit-interlocked-methods.cs.hlsl
- tools/clang/test/CodeGenSPIRV/intrinsics.interlocked-methods.compareexchange.output.hlsl
- tools/clang/test/CodeGenSPIRV/intrinsics.interlocked-methods.cs.hlsl
Set the scope of atomic operation on Workgroup-shared variables to the Workgroup rather than the Device.
Fixes #6508
> [SPIR-V] Scope Atomic ops on Workgroup memory

- lib/Transforms/Scalar/DxilRemoveUnstructuredLoopExits.cpp
- lib/Transforms/Scalar/LoopUnrollPass.cpp
- tools/clang/test/DXC/loop_structurize_exit_inner_latch_regression.ll
- tools/clang/test/HLSLFileCheck/hlsl/control_flow/loops/struct_exit_inner_latch_regression.ll
- utils/hct/hctdb.py
Fixed a bug in `hlsl::RemoveUnstructuredLoopExits` where when a new exiting block is created from splitting, it was added to the current loop being processed, when it could also part of an inner loop. Not adding the new block to inner loops that it's part of makes the inner loops malformed, and causes crash.
This fix adds the new block to the inner most loop that it should be part of. Also adds the `StructurizeLoopExits` option to `loop-unroll` pass for dxopt, which was missing before.
> Fixed crash in loop unroll caused by bug in structurize loop exits

- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.packoffset.error.hlsl
- tools/clang/test/CodeGenSPIRV/vk.layout.cbuffer.packoffset.hlsl
- tools/clang/test/SemaHLSL/attributes/packoffset-invalid.hlsl
- tools/clang/test/SemaHLSL/packreg.hlsl
- tools/clang/test/SemaHLSL/semantics.hlsl
Check  mix packoffset elements with nonpackoffset elements in a cbuffer at Sema::ActOnFinishHLSLBuffer. Also check packoffset for aggregate type.
Fixes #3724
> [Sema] Report warning when mix packoffset with nonpackoffset

- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/SemaHLSL/hlsl/intrinsics/barrier/barrier-cs-errors.hlsl
- tools/clang/test/SemaHLSL/hlsl/intrinsics/barrier/barrier-cs-local-errors.hlsl
- tools/clang/test/SemaHLSL/hlsl/intrinsics/barrier/barrier-cs-sm67-compat.hlsl
- tools/clang/test/SemaHLSL/hlsl/intrinsics/barrier/barrier-cs-sm67-errors.hlsl
- tools/clang/test/SemaHLSL/hlsl/intrinsics/barrier/barrier-cs.hlsl
- tools/clang/test/SemaHLSL/hlsl/intrinsics/barrier/barrier-node-errors.hlsl
- tools/clang/test/SemaHLSL/hlsl/intrinsics/barrier/barrier-node.hlsl
- tools/clang/test/SemaHLSL/hlsl/intrinsics/barrier/barrier-vs-errors.hlsl
- tools/clang/test/SemaHLSL/hlsl/intrinsics/barrier/barrier-vs.hlsl
Tests are split between one containing cases that could potentially be translated to legacy barrier op in the future, and a test without translatable barrier ops.
Part of #6538.
> Add diag for new Barrier intrinsic on SM < 6.8

- tools/clang/test/HLSLFileCheck/infra/auto-dxilver.hlsl
- tools/clang/unittests/HLSLTestLib/FileCheckerTest.cpp
In FileCheckerTest.cpp, the -T target of a %dxc part is checked for compatibility. However, if you use -Vd, it skips the version check for the validator. This isn't quite right since the validator version will be set from the attached validator, unless you explicitly set -validator-version or use -select-validator internal. Also, if -validator-version is explicitly set, we should check the validator against that version, not just the one based on shader model.
This change fixes the initial check logic to only skip validator check when using -select-validator internal or -validator-version. It also checks against an explicitly requested -validator-version when an external validator will be used.
Fixes #6367
> Fix auto-dxilver logic in FileCheckerTest

- tools/clang/include/clang/Basic/DiagnosticGroups.td
- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/lib/Sema/SemaChecking.cpp
- tools/clang/test/SemaHLSL/float-promotion.hlsl
This adds the Clang 3.8 `-Wdouble-promotion` warning group to DXC. This is added as part of the mitigations for the HLSL 202x conforming literals feature which (among other things) changes the conversion rank of unsuffixed literal values.
Resolves #6571
> Backport `-Wdouble-promotion` from Clang 3.8

- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/CodeGenDXIL/hlsl/objects/NodeObjects/mesh-node-invalid-attribs.hlsl
Bool attribute argument values of true would be interpreted as -1 and generate a warning that it expects a uint literal argument.
This change translates bool expression to either 0 or 1 when translating to int, just as normal expression evaluation would.
> Fix bool attribute argument handling

- docs/SPIR-V.rst
- tools/clang/include/clang/SPIRV/FeatureManager.h
- tools/clang/lib/SPIRV/CapabilityVisitor.cpp
- tools/clang/lib/SPIRV/FeatureManager.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/sm6_5.wave-match.hlsl
Adds support for the `WaveMatch()` intrinsic function from Shader Model 6.5 using the `OpGroupNonUniformPartitionNV` instruction from the `SPV_NV_shader_subgroup_partitioned` extension.
SPIRV-Tools bumped to include: https://github.com/KhronosGroup/SPIRV-Tools/pull/5648
Fixes #6545
> [SPIR-V] Implement WaveMatch intrinsic function

- tools/clang/include/clang/Basic/DiagnosticGroups.td
- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/lib/Sema/SemaExpr.cpp
- tools/clang/test/SemaHLSL/literals.hlsl
- tools/clang/test/SemaHLSL/v202x/conforming-literals/valid-literals.hlsl
This adds new literal warnings to identify integer literals that may have breaking behavior changes between HLSL 2021 and 202x as a result of the conforming literals change.
The spec update for this is in: https://github.com/microsoft/hlsl-specs/pull/229
Resolves #6581
> [202x] Implement -Whlsl-legacy-literal warnings

- include/dxc/Support/HLSLOptions.td
This commit adds the compiler option (-Qsource_in_debug_module) to the help text.
New help text output below:
```
Utility Options:
-dumpbin              Load a binary file rather than compiling
-extractrootsignature Extract root signature from shader bytecode (must be used with /Fo <file>)
-getprivate <file>    Save private data from shader blob
-link                 Link list of libraries provided in <inputs> argument separated by ';'
-P                    Preprocess to file
-Qembed_debug         Embed PDB in shader container (must be used with /Zi)
-Qsource_in_debug_module
Embed source info in PDB
-Qstrip_debug         Strip debug information from 4_0+ shader bytecode  (must be used with /Fo <file>)
-Qstrip_priv          Strip private data from shader bytecode  (must be used with /Fo …
```
> Add compiler option -Qsource_in_debug_module for embedding source in debug builds to documented help text

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
Now that WARP is actually getting bugfixes and features, and has a way for folks to get new versions without waiting years for an OS update, stop hiding the places where it's failing. Having these hardcoded skips in place makes it impossible to run the tests to see if it's still failing. If we really need these skips, we at least need some kind of command line option to override them for debugging and fixing the failures.
> Remove all WARP skips

- tools/clang/lib/CodeGen/CGExpr.cpp
- tools/clang/lib/CodeGen/CGExprCXX.cpp
- tools/clang/test/CodeGenDXIL/operators/swizzle/indexSwizzledBoolVec.hlsl
When indexing a swizzled bool vector, some HLSL-specific code in EmitCXXMemberOrOperatorMemberCallExpr kicks in to handle the HLSLVecType. In this case, we’re dealing with an ExtVectorElt because of the swizzle, so this function creates a GEP, Load, and Store on the vector. However, boolean scalars are returned as type i11 while the store is storing to a bool, which is an i32, so we need to insert a cast before the store.
> Fix invalid module bitcode when indexing a swizzled bool vector

- utils/hct/ExtractIRForPassTest.py
Also, emit a better message when the desired pass does not exist (or is mis-spelled). Before this change, there would only be a confusing message about 'after' being None.
> ExtractIRForPassTest: use %dxopt on the RUN line

- test/Transforms/Reassociate/lit.local.cfg
This change adds a local lit configuration file to re-enable the reassociate pass tests.
> Add local lit config to re-enable reassociate tests

- tools/clang/lib/SPIRV/DebugTypeVisitor.cpp
- tools/clang/test/CodeGenSPIRV/raytracing.nv.debug.hlsl
- This change adds a switch case for TK_AccelerationStructureNV in lowerToDebugType
- Before, compiling a shader for vulkan containing an acceleration structure and using -fspv-debug=vulkan-with-source would cause a crash.
Fixes #5113
> [SPIR-V] Add debug type for acceleration structure

- lib/DxilPIXPasses/DxilPIXAddTidToAmplificationShaderPayload.cpp
- lib/DxilPIXPasses/DxilPIXMeshShaderOutputInstrumentation.cpp
- tools/clang/test/HLSLFileCheck/pix/AddThreadIdToASPayload.hlsl
- tools/clang/test/HLSLFileCheck/pix/MSOutputInstrumentationCoerceValues.hlsl
- tools/clang/test/HLSLFileCheck/pix/MSOutputInstrumentationWithoutAS.hlsl
- utils/hct/hctdb.py
PIX requires that all vertex information generated by these passes be uniquely identified by vertex id and MS thread id.
This change fixes the MS thread id part in two places: the amplification shader and the mesh shader.
To be unique across an entire DispatchMesh call, we must uniquify the AS thread group, the AS thread, the MS thread group and the MS thread. This is a lot of multiplying and adding, and there wasn't quite enough math going on here before.
In the AS case, we now generate a unique "flat" thread id from the flat-thread-id-in-group (the already-available system value) and the "flat group id", which we synthesize by multiplying together the group id components with the DispatchMesh API's thread group counts, and then multiplying that by the number of threads each AS group …
> PIX: Correct the disambiguation of AS+MS threads for mesh shader output

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/spv.intrinsicLiteralVariable.error.hlsl
- tools/clang/test/CodeGenSPIRV/spv.intrinsicLiteralVariable.hlsl
If a parameter annotated with `[[vk::ext_literal]]` is not lowered to a SpirvConstant, make a best-effort attempt to evaluate it to a constant literal value. If unsuccessful, fail gracefully rather than crash.
Fixes #6586
> [SPIR-V] Best effort const eval of vk::ext_literal

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/vk.spec-constant.init.hlsl
> [SPIR-V] Allow const-evaluatable spec constants

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/intrinsics.interlocked-methods.cs.hlsl
- tools/clang/test/CodeGenSPIRV/method.rw-byte-address-buffer.atomic.hlsl
RWByteAddressBuffer has overloads for InterlockedMin and InterlockedMax for signed ints that were failing to compile due to mismatched types in the generated SPIR-V instruction. This adds the missing cast if necessary.
At the same time, some redundant code is removed from the InterlockedMin/Max intrinsic non-member functions' codegen to modify the opcode. If it was necessary in the past, the frontend has since been fixed and it is no longer necessary. Tests to verify these combinations and the necessary implicit casts have also been added.
Fixes #3196
Related to #4189, #6254, #5707
> [SPIR-V] Fix InterlockedMin/Max codegen

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/intrinsics.firstbithigh.64bit.hlsl
- tools/clang/test/CodeGenSPIRV/intrinsics.firstbithigh.hlsl
- tools/clang/test/CodeGenSPIRV/intrinsics.firstbitlow.64bit.hlsl
The code gen for firstbithigh and -low was incorrectly checking the size of the full (possibly composite) type rather than the element size. This is now fixed, and I've also switch the error check from whether the element type is == 64-bit to != 32-bit, so that it matches the current limitations of the GLSL extended instructions.
https://registry.khronos.org/SPIR-V/specs/unified1/GLSL.std.450.html#:~:text=%3Cid%3E%0AValue-,FindSMsb,-Signed%2Dinteger%20most
Related to #4702
> [SPIR-V] Fix firstbit{high,low} elem check

- lib/Transforms/Scalar/DxilRemoveDeadBlocks.cpp
- tools/clang/test/DXC/Passes/DxilRemoveDeadBlocks/switch-with-multiple-same-successor.hlsl
- tools/clang/test/DXC/Passes/DxilRemoveDeadBlocks/switch-with-multiple-same-successor.ll
Given a switch with a constant condition and all cases the same (branching to the same successor), dxil-remove-dead-blocks would incorrectly remove the switch when replacing it with a branch, by forgetting to remove the N-1 incoming values to the PHIs in the successor block.
> Fix dxil-remove-dead-blocks removing switch with multiple same successor

- lib/Transforms/Scalar/Reassociate.cpp
- test/Transforms/Reassociate/basictest.ll
This PR pulls the upstream change, Reassociate: add global reassociation algorithm (https://github.com/llvm/llvm-project/commit/b8a330c42ab43879119cd3a305756d28aefe9fe6), into DXC with miminal changes.
For the code below:
foo = (a * b) * c
bar = (a * d) * c
As the upstream change states, it can identify the a*c is a common factor and redundant.
This is part 1 of the fix for #6593.
> Reassociate: add global reassociation algorithm

- include/dxc/Support/DxcOptToggles.h
- include/llvm/Transforms/IPO/PassManagerBuilder.h
- include/llvm/Transforms/Scalar.h
- lib/Transforms/IPO/PassManagerBuilder.cpp
- lib/Transforms/Scalar/Reassociate.cpp
- tools/clang/lib/CodeGen/BackendUtil.cpp
- tools/clang/test/DXC/Passes/reassociate/reassociation-flag.hlsl
- tools/clang/test/DXC/Passes/reassociate/reassociation-flag.ll
- utils/hct/hctdb.py
This PR (https://github.com/microsoft/DirectXShaderCompiler/pull/6598) pulls the upstream global reassociation algorithm change in DXC and can reduce redundant calculations obviously.
However, from the testing result of a large offline suite of shaders, some shaders got worse compilation results and couldn't benefit from this upstream change.
This PR adds a flag for the upstream global reassociation change. It would be easier to roll back if a shader get worse compilation result due to this upstream change.
This is part 2 of the fix for #6593.
> Add a flag for the upstream global reassociation algorithm change

- lib/Transforms/IPO/PassManagerBuilder.cpp
- tools/clang/test/DXC/Passes/reassociate/fp-common-factor-optimization.hlsl
Although DXC applied the upstream change, Reassociate: add global reassociation algorithm (https://github.com/llvm/llvm-project/commit/b8a330c) in this PR (https://github.com/microsoft/DirectXShaderCompiler/pull/6598), it still might overlook some obvious common factors.
One case has been observed is:
```
%Float4_0   = call %dx.types.CBufRet.f32 @dx.op.cbufferLoadLegacy.f32(i32 59, %dx.types.Handle %1, i32 1)
%Float4_0.w = extractvalue %dx.types.CBufRet.f32 %Float4_0, 3
%Float2_0   = call %dx.types.CBufRet.f32 @dx.op.cbufferLoadLegacy.f32(i32 59, %dx.types.Handle %1, i32 0)
%Float2_0.y = extractvalue %dx.types.CBufRet.f32 %Float2_0, 1
/* %Float4_1 is redundant with %Float4_0 since they invokes cbufferLoadLegacy with same parameters */
%Float4_1   = call %dx.types.CBufRet.f32 …
```
> More aggressive reassociations

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/texture.sample-cmp-level.hlsl
SampleCmpLevel is similar to SampleCmpLevel0, except the LOD level can be specified using either a const-offset, or a variable. This should be available starting SM6.7
Fixes #6613
> [SPIR-V] Add support for SampleCmpLevel

- tools/clang/lib/SPIRV/AlignmentSizeCalculator.cpp
- tools/clang/test/CodeGenSPIRV/empty_struct.hlsl
We have a special case to that the the size and alignment for an empty
struct is `{1,0}`. However that is not correct. See
https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#interfaces-alignment-requirements.
> An empty structure has a base alignment equal to the size of the smallest
scalar type permitted by the capabilities declared in the SPIR-V module. (e.g.,
for a 1 byte aligned empty struct in the StorageBuffer storage class,
StorageBuffer8BitAccess or UniformAndStorageBuffer8BitAccess must be declared
in the SPIR-V module.
I'm not 100% sure how DXC handle this minimum alignment, but I figured I
would inialize the alignment to 1. If there are not members, then it
will remain 1, and I would let the rest of the logic happen. No special
case.
Fixes #2882
> Fix aligment for empty structs

- lib/HLSL/HLMatrixLowerPass.cpp
- tools/clang/test/DXC/matrix_mat_struct_align.ll
- tools/clang/test/HLSLFileCheck/hlsl/types/modifiers/groupshared/groupshared-member-matrix-subscript-align.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/types/modifiers/groupshared/groupshared-member-matrix-subscript2.hlsl
When flattening the global for a groupshared matrix, the alignment information was getting lost. As a result, the alignments of the loads and stores were calculating their own alignment based on preferred alignment and trailing zeros of the index. The preferred alignment switched to 16 when the type size was over 128 bits due to a heuristic whose rationale is lost to time. When the global has its own alignment, that gets used, so by retaining it through lowering, the alignments are consistent and reliable.
Includes testing for a few matrix variants
fixes #6416
> Retain alignment when lowering groupshared matrices

- lib/Transforms/Scalar/LoopDeletion.cpp
- tools/clang/test/DXC/Passes/DxilLoopDeletion/dxil-loop-deletion-phi-with-duplicate-preds.ll
LoopDeletion was incorrectly updating PHI nodes in the target block when it had duplicate input edges. This happens, for example, when deleting a loop that uses a switch with multiple cases that exit the same way.
After determining that this was the bug, I found this fix in LLVM: https://reviews.llvm.org/D34516 and applied it here.
> Fix LoopDeletion incorrectly updating PHI with multiple duplicate inputs

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/test/CodeGenSPIRV/sm6_5.sampler_feedback.hlsl
Sampler feedback resource types are not supported by the SPIR-V backend, but they would previously fail silently until a function was called on them. This change makes the error message more explicit on the type.
Related to #6614
> [SPIR-V] Add error message for SamplerFeedback

- utils/TableGen/AsmWriterEmitter.cpp
This is to fix compile error like
```
../../third_party/dxc/utils/TableGen/AsmWriterEmitter.cpp(974): error C2666: '`anonymous-namespace'::IAPrinter::operator ==': overloaded functions have similar conversions
../../third_party/dxc/utils/TableGen/AsmWriterEmitter.cpp(739): note: could be 'bool `anonymous-namespace'::IAPrinter::operator ==(const `anonymous-namespace'::IAPrinter &)'
../../third_party/dxc/utils/TableGen/AsmWriterEmitter.cpp(739): note: or 'bool `anonymous-namespace'::IAPrinter::operator ==(const `anonymous-namespace'::IAPrinter &)' [synthesized expression 'y == x']
../../third_party/dxc/utils/TableGen/AsmWriterEmitter.cpp(974): note: while trying to match the argument list '(`anonymous-namespace'::IAPrinter, `anonymous-namespace'::IAPrinter)'
```
in dawn project which is …
> fix compile error for newer VS toolchain

- include/llvm/IR/ValueHandle.h
- lib/IR/Value.cpp
This PR pulls the upstream change, Use accessors for ValueHandleBase::V; NFC (https://github.com/llvm/llvm-project/commit/6f08789d3028d2ae46c15804c038d5d3f107a348), into DXC.
Here's the summary of the change:
>    This changes code that touches ValueHandleBase::V to go through getValPtr and (newly added) setValPtr.  This functionality will be used later, but also seemed like a generally good cleanup.
> 
>    I also renamed the field to Val, but that's just to make it obvious that I fixed all the uses.
This is part 1 of the fix for #6659.
> Use accessors for ValueHandleBase::V; NFC

- lib/Transforms/Scalar/DxilRemoveUnstructuredLoopExits.cpp
- test/HLSL/passes/dxil_remove_unstructured_loop_exits/exit-to-unrelated-loop.ll
- test/HLSL/passes/dxil_remove_unstructured_loop_exits/multi-level-exit-from-latch.ll
- test/HLSL/passes/dxil_remove_unstructured_loop_exits/multi-level-exit-regression.ll
- test/HLSL/passes/dxil_remove_unstructured_loop_exits/multi-level-exit.ll
- tools/clang/test/HLSLFileCheck/hlsl/control_flow/loops/multi_level_exit_regression.hlsl
Before doing any major surgery on an exit from loop L, ensure that if an exit edge from L goes to block X, then X is in L's parent loop or no loop at all.
Add test cases:
- a reduced test case where the exiting block does not dominate its own loop latch.
- a reduced test case where the exiting block is the latch for its own loop. This reproduces the assert triggered by the original HLSL.
- the original HLSL that triggered this bug fix.
- the intermediate module from the original HLSL, taken just before the attempt to remove unstructured loop exits.
> Fix RemoveUnstructuredLoopExits when an exiting edge jumps out multiple levels of loops.

- lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
- tools/clang/test/DXC/Passes/ScalarReplHLSL/scalarrepl-param-hlsl-dyn-idx-gep-of-const-idx-gep.ll
When processing global values to determine when to flatten vectors, this pass was only checking the immdiate users of the value for non-dynamic indexing of the vector. But this would fail in the case of a dynamic indexed GEP of a constant indexed GEP (e.g. h[0][a]) because the first level GEP was constant indexed, but not the second. We fix this by
checking the full User tree of the value in `hasDynamicVectorIndexing`.
> Fix crash in scalarrepl-param-hlsl when dynamically indexing a GEP of a constant indexed GEP

- include/dxc/Support/HLSLOptions.td
- include/dxc/Support/SPIRVOptions.h
- lib/DxcSupport/HLSLOptions.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/max_id.hlsl
Vulkan implementation can have different limits on the maximum value
used as an id in a SPIR-V binary. SPIRV-Tools generall assumes this
limit is 0x3FFFFF because all implementations must support at least that
value for an id.  Since many implementations can support larger values,
the tools allows an option that will set a different limit. This commit
add an option to DXC to do the same.
Fixes #6636
> Add option to set the max id

- CMakeLists.txt
- projects/dxilconv/include/ShaderBinary/ShaderBinary.h
This PR contains two changes:
1) Moves a pragma to disable a warning, which seems to be required by the new compiler.
2) Adds a preprocessor define to workaround the crashes caused by the runner image mismatching C++ runtime versions.
The second change we will want to revert once the runner images are fixed. The issue tracking the runner images is:
https://github.com/actions/runner-images/issues/10004
Related #6668
> Workaround broken GitHub runner images

- lib/Transforms/Utils/SimplifyCFG.cpp
- tools/clang/test/DXC/Passes/SimplifyCFG/simplifycfg-uaf-phi-condition.ll
In certain cases of unreachable code, SimplifyCFG could try to replace a phi node with a select where the phi node itself was the select's condition. This resulted in an ASAN use-after-free during SimplifyCFG.
The test case added isn't quite ideal because by the end of the SimplifyCFG pass, the phi node is restored to its original state both before and after this fix. However, an ASAN build of `dxopt` or `check-clang-dxc` will identify a heap-use-after-free failure in the intermediary steps of this test without this patch and succeeds with it.
This was also fixed in upstream LLVM: https://github.com/llvm/llvm-project/commit/602ab248335e1540e82667e74fea44b7f042e112
> Fix another UAF in SimplifyCFG

- lib/Transforms/InstCombine/InstCombineCompares.cpp
- tools/clang/test/DXC/Passes/InstructionCombining/instcombine-opt-overflow-check-inserts-at-add.ll
When optimizing an overflow check of an add followed by a compare, the new instruction was being inserted at the compare, and the add removed. This produced invalid IR in cases where there were other uses of the former add between it and the compare. This fix makes sure to insert the new instruction at the old add location, rather than at the compare.
Note that this was also fixed in LLVM:
https://github.com/llvm/llvm-project/commit/6f5dca70ed1c030957a45ad91bd295921f17b18d
> Fix instcombine overflow check inserting inst at wrong place

- tools/clang/test/CodeGenSPIRV/intrinsics.nonuniform.arithmetic.extension.hlsl
- tools/clang/test/CodeGenSPIRV/meshshading.ext.cullprimative.hlsl
- tools/clang/test/CodeGenSPIRV/meshshading.ext.no-explicit-exts-spv1.4.mesh.hlsl
- tools/clang/test/CodeGenSPIRV/meshshading.ext.triangle.mesh.hlsl
- tools/clang/test/CodeGenSPIRV/meshshading.nv.line.mesh.hlsl
- tools/clang/test/CodeGenSPIRV/meshshading.nv.point.mesh.hlsl
- tools/clang/test/CodeGenSPIRV/meshshading.nv.request-nv-with-spv1.4.mesh.hlsl
- tools/clang/test/CodeGenSPIRV/meshshading.nv.triangle.mesh.hlsl
- tools/clang/test/CodeGenSPIRV/raytracing.khr.closesthit.hlsl
- tools/clang/test/CodeGenSPIRV/raytracing.khr.closesthit.vulkan1.1spirv1.4.hlsl
- tools/clang/test/CodeGenSPIRV/raytracing.khr.terminate.hlsl
- tools/clang/test/CodeGenSPIRV/raytracing.nv.anyhit.hlsl
- tools/clang/test/CodeGenSPIRV/raytracing.nv.callable.hlsl
- tools/clang/test/CodeGenSPIRV/raytracing.nv.closesthit.hlsl
- tools/clang/test/CodeGenSPIRV/raytracing.nv.enum.hlsl
- tools/clang/test/CodeGenSPIRV/raytracing.nv.intersection.hlsl
- tools/clang/test/CodeGenSPIRV/raytracing.nv.library.hlsl
- tools/clang/test/CodeGenSPIRV/raytracing.nv.miss.hlsl
- tools/clang/test/CodeGenSPIRV/raytracing.nv.raygen.hlsl
- tools/clang/test/CodeGenSPIRV/spv.intrinsicStorageClass.hlsl
- tools/clang/test/CodeGenSPIRV/vk.layout.shader-record-ext.std430.hlsl
- tools/clang/test/CodeGenSPIRV/vk.layout.shader-record-nv.std430.hlsl
- tools/clang/test/CodeGenSPIRV/vk.shader-record-ext.constantbuffer.assign.hlsl
- tools/clang/test/CodeGenSPIRV/vk.shader-record-ext.hlsl
- tools/clang/test/CodeGenSPIRV/vk.shader-record-nv.hlsl
[SPIR-V] Fix GroupNonUniform capabilities+ext
Fixes emission of GroupNonUniform capabilities and related extensions,
in particular SPV_NV_shader_subgroup_partitioned.
Since this PR bumps SPIR-V headers + tools, some test changes are required due to opcode changes. Those are in a separate commit, but same PR.
Fixes #6672
> [SPIR-V] Fix GroupNonUniform capabilities+ext 

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/DeclResultIdMapper.h
- tools/clang/test/CodeGenSPIRV/attribute.location.lib.hlsl
- tools/clang/test/CodeGenSPIRV/implicit.location.lib.hlsl
The code that adds the input and output decoration in the entry points
inputs and outputs assumes that there is a single entry point in the
module. When using the `lib` profile that is not true.
This commit modifies the code so that it groups the stage variables by
entry point, and runs the current code on each group separably.
I hesitate to make this change because it will change the locations for
code that currently works, and will force users to update their
applications accordingly. Or they could modify their shaders
to use explicit locations attributes. Neither is great.
However, the advantage is that this allows the implicit locations to match what would happen if the shader were compiled individually. It also makes the locations more predictable  because change in another shader …
> Make the location map run per entry point

- tools/clang/unittests/HLSLExec/ShaderOpArithTable.xml
Update tolerance for ExecutionTest::UnaryHalfOpTest#AcosHalf test.
Enables implementations to calculate `acos` for fp16 type by converting to fp32, doing fp32 math, and then converting back to fp16 using round-to-nearest-even conversing (RTNE) per D3D11 spec. For more details please see issue #6179.
As mentioned in the linked issue, for these floating point tests a fixed point tolerance does not really make sense. It should vary based on the magnitude of the expected value. But we are already using this approach in many similar test cases and the simplest fix now is to update the tolerance to accommodate the fp32-to-ft16 conversion.
Fixes #6179
> ExecutionTest::UnaryHalfOpTest#AcosHalf: Update tolerance

- tools/clang/include/clang/SPIRV/SpirvBuilder.h
- tools/clang/include/clang/SPIRV/SpirvInstruction.h
- tools/clang/include/clang/SPIRV/SpirvModule.h
- tools/clang/include/clang/SPIRV/SpirvVisitor.h
- tools/clang/lib/SPIRV/EmitVisitor.cpp
- tools/clang/lib/SPIRV/EmitVisitor.h
- tools/clang/lib/SPIRV/SpirvBuilder.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvInstruction.cpp
- tools/clang/lib/SPIRV/SpirvModule.cpp
- tools/clang/test/CodeGenSPIRV/spirv.cf.ret-missing-resource.hlsl
- tools/clang/test/CodeGenSPIRV/spirv.cf.ret-missing.hlsl
- tools/clang/test/CodeGenSPIRV/spirv.cf.ret-undef-shared.hlsl
Before this change, OpConstantNull was emitted when an undef value was required.
This causes an issue for some types which cannot have the OpConstantNull value.
In addition, it mixed well-defined values with undefined values, which prevents any kind of optimization/analysis later on.
Fixes #6653
> [SPIR-V] Emit OpUndef for undefined values

- lib/Transforms/Scalar/DxilRemoveUnstructuredLoopExits.cpp
- test/HLSL/passes/dxil_remove_unstructured_loop_exits/nondedicated-latch-exit.ll
- test/HLSL/passes/dxil_remove_unstructured_loop_exits/shared-exit.ll
Previously, if the latch exit was reachable from a different exit block for the loop, then the pass would introduce a loop involving that exit block and the latch exit.  This is unwanted and unaccounted for.
- Add a test for shared exits.
- Add a test for non-dedicated latch exit
> Remove unstructured loop exits: Don't introduce loops

- CMakeLists.txt
This removes the hack introduced in #6683 to workaround issues in the GitHub and ADO runner image:
https://github.com/actions/runner-images/issues/10004
Rumor has it the runner images are now fixed... let's see.
Fixes #6674
> Remove Windows C++ redist hack

- lib/Transforms/Scalar/IndVarSimplify.cpp
- test/HLSL/passes/indvars/preserve-phi-when-replacement-is-in-loop.ll
- test/Transforms/IndVarSimplify/preserve-phi-when-replacement-is-in-loop.ll
Induction variable simplification (indvars) tries to rewrite exit values; these appear as phi nodes in loop exit blocks. If the replacement for the phi is still in the loop, then that would break the LCSSA property. Don't do that.
Add a test for this.
> indvars: don't replace a phi when that breaks LCSSA

- tools/clang/lib/SPIRV/DebugTypeVisitor.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/rich.debug.type.composite.warning.hlsl
- tools/clang/test/CodeGenSPIRV/rich.debug.vulkan.member.function.param.hlsl
This commit bumps SPIR-V tools version, and re-add support for objects debug instructions when using Vulkan's debug instructions.
Because OpenCL debug instructions are not a non-semantic set, the SPIR-V spec would need to be modified, as today it does not allows forward references.
Fixes #6691
> [SPIR-V] Re-enable rich debug instructions for objects

- include/llvm/IR/ValueHandle.h
- lib/IR/Value.cpp
- unittests/IR/ValueHandleTest.cpp
Originally @lizhengxing's PR. Retargeting main.
This PR pulls 2 upstream changes, Add a new WeakVH value handle; NFC (https://github.com/llvm/llvm-project/commit/f1c0eafd5b10d33d957457ef292c56e6bab17938) and Use a 2 bit pointer in ValueHandleBase::PrevPair; NFC (https://github.com/llvm/llvm-project/commit/b297bff1cc974023a49d6ad898badf78a08692c3), into DXC.
Here's the summary of the changes:
Add a new WeakVH value handle; NFC 
>       WeakVH nulls itself out if the value it was tracking gets deleted, but it does not track RAUW.
> 
>       Reviewers: dblaikie, davide
> 
>       Subscribers: mcrosier, llvm-commits
> 
>       Differential Revision: https://reviews.llvm.org/D32267
Use a 2 bit pointer in ValueHandleBase::PrevPair; NFC
> This was an omission in r301813.  I had made the …
> Add a new WeakVH value handle; NFC

- test/MC/ELF/empty-twice.ll
- test/Object/opt-twice.ll
- tools/llc/llc.cpp
- tools/opt/opt.cpp
This PR pulls the following upstream changes into DXC:
[llc/opt] Add an option to run all passes twice (https://github.com/llvm/llvm-project/commit/04464cf7313a7c2873f2b8a9011a19f1685b44c1)
>   Lately, I have submitted a number of patches to fix bugs that only occurred when using the same pass manager to compile
>   multiple modules (generally these bugs are failure to reset some persistent state).
> 
>   Unfortunately I don't think there is currently a way to test that from the command line. This adds a very simple flag to both
>   llc and opt, under which the tools will simply re-run their respective
>   pass pipelines using the same pass manager on (a clone of the same module). Additionally, we verify that both outputs are
>   bitwise the same.
> 
>   Reviewers: yaron.keren
[opt] Fix …
> [llc/opt] Add an option to run all passes twice

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/intrinsics.vkrawbufferload.hlsl
- tools/clang/test/CodeGenSPIRV/intrinsics.vkrawbufferstore.hlsl
The first first fix in #5392 was not correct. It relied on the layout
rule for the address to be the correct layout rule, but that is not
always the case. The address is just an integer that could exist in any
storage class. The correct solution is to explicitly set the layout rule
for the BitCast operation when expanding the RawBuffer* functions. We
know that the result of the BitCast is a pointer to the physical storage
buffer storage class, so we know the layout need to be the storage
buffer layout.
Fixes #6554
> Set the layout rule explicitly for raw buffer operations

- projects/dxilconv/include/ShaderBinary/ShaderBinary.h
Internal build that has DXC as a submodule and that is built with a different VC toolset version started failing after the pragma got moved up in commit 0b9acdb75. Adding a duplicate pragma back at the original location makes both compiler versions happy.
> Add duplicate pragma

- lib/DxilPIXPasses/DxilAnnotateWithVirtualRegister.cpp
- tools/clang/test/DXC/Passes/PIX/validatorNoDowngrade.ll
- tools/clang/test/DXC/Passes/PIX/validatorUpgrade.ll
This pass was attempting to compare different things. The return values of GetDxilVersion are not shader models, but... dxil version. Since the code is trying to upgrade the validator version, I changed this to GetValidatorVersion, to pair with SetValidatorVersion.
The previous code was breaking the nvidia driver on workgraphs.
> Fix a PIX pass's attempt to set the validator version

- .github/ISSUE_TEMPLATE/release.md
As we prepare to do a release, we generally create an issue that contains instructions and checklists for the mechanics of the release.  This change adds a template for these issues.
> Add template for "release" issues

- tools/clang/utils/TableGen/TableGen.cpp
- utils/TableGen/TableGen.cpp
On MinGW, NOMINMAX is defined by default, so guard it to avoid redefinition warnings.
> Avoid NOMINMAX redefinition warnings

- include/dxc/Support/microcom.h
This fixes the following compiler error with clang 18.1.6 with mingw-w64 toolchain.
microcom.h:190:43: error: unknown type name 'nullptr_t'; did you mean 'std::nullptr_t'?
190 | template <typename T> HRESULT AssignToOut(nullptr_t value, T *pResult) {
|                                           ^~~~~~~~~
|                                           std::nullptr_t
microcom.h:207:43: error: unknown type name 'nullptr_t'; did you mean 'std::nullptr_t'?
207 | template <typename T> void AssignToOutOpt(nullptr_t value, T *pResult) {
|                                           ^~~~~~~~~
|                                           std::nullptr_t
> [NFC] Use full qualified name with std::nullptr_t type

- docs/DXIL.rst
The `ResElem` type doesn't exist, and the example here seemed to imply that the similar `ResRet` type was used in resource metadata. This is incorrect, so fix the examples to match types that would actually show up in this metadata.
Note: In practice the metadata doesn't generally actually refer to a variable, but just an `undef` of the right type. I've opted not to change the examples to reflect that here to minimize the change, but it might be nice to describe when/why this occurs.
Fixes #3411
> Clean up inaccurate type information in resource metadata docs

- docs/ReleaseNotes.md
Moving the source file for the README.md for github and nuget releases
into the DXC repo. It should be updated with relevant notes for the
upcoming release whenever they are made in main such that they will
already be available when the release is built.
Part of #6697
> Enable Living Release Notes

- CMakeLists.txt
- include/dxc/config.h.cmake
- tools/clang/lib/CodeGen/BackendUtil.cpp
When enabled, any hlsl::Exception thrown during code generation and optimization will cause the process to trap.
---
edit: I've changed the implementation to generate a trap, instead of std::abort
> Add CMake option DXC_CODEGEN_EXCEPTIONS_TRAP

- CMakeLists.txt
- projects/dxilconv/include/ShaderBinary/ShaderBinary.h
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/SemaHLSL/operator-overload.hlsl
Merges the following changes into mesh nodes to fix a known bug that required a point release in the march release branch and also some build fixes for new visual studio diagnostics. 
9ca52f4e0 Add duplicate pragma (#6732)
7809c0bd3 Remove Windows C++ redist hack (#6692)
33277a123 Workaround broken GitHub runner images (#6683)
1b9a79643 [Sema] Check FunctionDecl has identifier before getName. (#6439) (#6457)
> Merge needed march release followups into mesh nodes

- CONTRIBUTING.md
Add guidance for how release notes should be documented at the time
of the change going in as well as some suggestions for how to format
that documentation.
Contributes to #6697
> Add Release Notes Guidance to CONTRIBUTING

- docs/ReleaseNotes.md
Moving the source file for the README.md for github and nuget releases into the DXC repo. It should be updated with relevant notes for the upcoming release whenever they are made in main such that they will already be available when the release is built.
Part of #6697
(cherry picked from commit 8fce06b03c38bc0558dcc3305aa20fe5580da293)
> Enable Living Release Notes (#6772)

- docs/ReleaseNotes.md
Add initial release note for 1.8.2407.
> [Release Note] Add release note for 1.8.2407

- docs/SPIR-V.rst
The documentation says that we use the HitTKHR builtin to implement
RayTCurrent. However, HitTKHR was renamed to RayTMaxKHR. We update
the documentation to represent that change.
Fixes #6739
> [SPIRV] Fix documentation for RayTCurrent

- tools/clang/include/clang/Basic/Attr.td
- tools/clang/include/clang/SPIRV/FeatureManager.h
- tools/clang/include/clang/SPIRV/SpirvBuilder.h
- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/DeclResultIdMapper.h
- tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/spv.inline.capability.hlsl
- tools/clang/test/CodeGenSPIRV/spv.inline.extension.hlsl
- tools/clang/test/CodeGenSPIRV/spv.inline.extension.unused.hlsl
- tools/clang/test/CodeGenSPIRV/spv.inline.type.hlsl
This implements the changes proposed in
https://github.com/microsoft/hlsl-specs/pull/270.
> Allow cap and extention attribute on member variables and type aliases

- docs/ReleaseNotes.md
The behavior was changed with #6317 so that regardless of spelling in the shader, the include path will conform to the host OS style for the purposes of the include handler. This just adds a release note for that new behavior.
Fixes #6669
(cherry picked from commit 9fa4618de91a0d80168a13cf71e1fc0355001b7c)
> Release Note for OS-normalized include paths (#6789)

- tools/clang/test/CodeGenDXIL/literal/fmod_const_eval.hlsl
- tools/clang/test/CodeGenDXIL/literal/length_const_eval.hlsl
- tools/clang/test/CodeGenDXIL/literal/normalize_const_eval.hlsl
Certain HL ops with no double overload will generate double overloads for literal types. These are lowered to double DXIL overloads, some of which are not legal for these ops. We currently rely on illegal intermediate DXIL op overloads for constant evaluation. If constant evaluation fails, we end up with illegal DXIL overloads in final DXIL, which is caught by the validator.
The prior revert restored the ability to run these scenarios (with asserts disabled).
This change adds tests for #6419 so automated testing will test across configurations and prevent regressions of this scenario in this branch.
(cherry picked from commit 9c2b82878e3c52367d4be2d3bf7ee8bd49763483)
> Add tests for literal overloads of fmod, length, and normalize (#6437)

- lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
- tools/clang/test/HLSLFileCheck/passes/hl/sroa_hlsl/array-from-cbvec-1.ll
- tools/clang/test/HLSLFileCheck/passes/hl/sroa_hlsl/array-from-cbvec-2.ll
- tools/clang/test/HLSLFileCheck/passes/hl/sroa_hlsl/array-from-cbvec-3.ll
In the special code to handle the memcpy pattern where a constant buffer contains a vector array that initializes a local (or static global) scalar array for use by the shader, an invalid assumption was made that if the memcpy dest was global, that the src is global as well.
This was not the case, and when expecting to generate constant expressions to index the src, these generated orphaned instructions instead, leading to invalid IR.
This fixes the issue by leveraging ReplaceConstantWithInst, and setting the insertion point for the Builder.  Now, replacement *could* fail, if src instructions don't dominate replacement uses, so bool for replaced all is returned from replaceScalarArrayWithVectorArray.
Another issue was that it would replace the dest for the original memcpy with src along …
> Fix CB vector to scalar array translation generating invalid IR

- cmake/modules/HCT.cmake
This change adds a new CMake configuration option
`HLSL_DISABLE_SOURCE_GENERATION` which allows a user to disable generating the in-tree sources which contributte to DXC's source releases. This option should only be used by users building DXC and not modifying it.
Resolves #6728
> [CMake] Add an option to disable source generation

- tools/clang/include/clang/Analysis/CFG.h
This imports upstream commit
https://github.com/llvm/llvm-project/commit/54bff1522fc863329894d875d54c2fe4cd1b4f3f
This fixes the following compiler error with clang 18.1.8 with mingw-w64 toolchain.
CFG.h:916:22: error: expected a qualified name after 'typename'
916 |   template <typename CALLBACK>
|                      ^
minwindef.h:90:18: note: expanded from macro 'CALLBACK'
90 | #define CALLBACK __stdcall
|                  ^
> [NFC]: Rename a template parameter conflict with CALLBACK macro

- tools/clang/tools/dxcompiler/dxcdisassembler.cpp
There is an extra "signature" in the Patch Constant signature part of the disassembler output, causing the "Patch Constant signature signature" to appear. This PR removes the extra "signature" from the output.
Example HLSL input:
```hlsl
struct OutputConstantData {
float tessFactor[4] : SV_TessFactor;
float insideTessFactor[2] : SV_InsideTessFactor;
};
OutputConstantData HSConstant() {
OutputConstantData output;
return output;
}
[domain("quad")]
[partitioning("integer")]
[outputtopology("triangle_cw")]
[outputcontrolpoints(1)]
[patchconstantfunc("HSConstant")]
void HSMain() {}
```
Example Disassembler output:
```diff
...
;
- ; Patch Constant signature signature:
+ ; Patch Constant signature:
;
; Name                 Index   Mask Register SysValue  Format   Used
; -------------------- …
```
> Disassembler: Remove duplicated "signature" in output

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/intrinsics.isnan.hlsl
IsNan returns a boolean, even is the input-type is a float. This was working in most cases except:
- if the layout was not Void
- if the input type was not a matrix
The first bug is because a bool memory layout/representation is not specified, and shall never be exposed to externaly-accessible memory. Hence, if we saw a layout rule != Void, we converted it to a UINT. When calling isnan, the layout rule should not be propagated as we loose any layout info.
The second is because our codegen assumed matrix operations returned a matrix with the same type as the input parameters. In the case of isnan, this was just wrong.
Fixes #6712
> [SPIR-V] Fix invalid isnan codegen

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/cf.switch.ifstmt.early-return.hlsl
When the [branch] annotation is used, switches are converted into an if/else tree.
Issue arise when declaring a variable into a switch case:
- when flattened, the same variable could be traversed twice in case of a case fall-through.
In addition, there was a small bug in the flattening logic: only breaks were stopping the handling of further statements, while early-returns were ignored. This was not an important bug as it only added more dead-code, but it was wrong.
Fixes #6718
> [SPIR-V] Fix flattened SPIR-V variable codegen.

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/fn.param.inout.type-mismatch.hlsl
When a scalar variable is passed as the argument to an inout vector parameter,
then the scalar is suppose to be splatted. After returning from the
function, we need to extract the first element from the parameter to
store back into the scalar.
Fixes #6568
> Splat function argument

- tools/clang/lib/SPIRV/RawBufferMethods.cpp
- tools/clang/test/CodeGenSPIRV/method.byte-address-buffer.load.hlsl
- tools/clang/test/CodeGenSPIRV/method.byte-address-buffer.store.hlsl
The code that implements `RWByteAddressBuffer::Store` will iterate over
all of the fields in a struct to write each element in the struct.
However, it does not use the "Spir-V fields", which accounts for
multiple fields being packed into the same bitfield. This is fixed by
using the `forEachSpirvField` function to make sure that the bitfield
are correctly handled.
Fixes #6483
> Iterate over the spir-v fields to handle bitfields

- lib/HLSL/DxilContainerReflection.cpp
In CalcResTypeSize function, UNREFERENCED_PARAMETER macro is used with a
parameter which is referenced in return statement. That macro was added in
6ee4074a4b43fa23bf5ad27e4f6cafc6b835e437 but it was not removed when
"DxilModule &M" was referenced in 86073a3b0b45fe41b8ffe6c8a33c9b7c913e6b8c
This fixes the following compiler error with clang 18.1.8 with mingw-w64 toolchain.
DxilContainerReflection.cpp:1512:3: error: object of type 'DxilModule'
cannot be assigned because its copy assignment operator is implicitly deleted
1512 |   UNREFERENCED_PARAMETER(M);
|   ^
winnt.h:1387:40: note: expanded from macro 'UNREFERENCED_PARAMETER'
1387 | #define UNREFERENCED_PARAMETER(P) {(P) = (P);}
|                                        ^
> [NFC] Fix incorrect use of UNREFERENCED_PARAMETER macro

- docs/ReleaseNotes.md
This is the section where the next release notes will be inserted. It's just a placeholder instruction for now.
Fixes #6697
> Add upcoming release section to release notes

- lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp
- tools/clang/lib/CodeGen/CGDebugInfo.cpp
- tools/clang/test/DXC/min16vector_disabled.hlsl
- tools/clang/test/DXC/min16vector_enabled.hlsl
- tools/clang/unittests/HLSL/PixDiaTest.cpp
This fixes a bug where the offsets for elements in vectors with 16-bit types doesn't take into account alignment bits and PIX wouldn't display vector element values correctly in the shader debugger. Eg. if `-enable-16bit-types` wasn't set, the offsets for a min16float4 would be 0, 16, 32, 48 instead of 0, 32, 64, 96.
Also removed the assert in PopulateAllocaMap_StructType that was checking whether the calculated aligned offset matches the packed offset (from SortedMembers) because it was false for members with sizes smaller than the alignment size.
> Fix debug info offsets for vectors with 16-bit types

- .github/workflows/pr-description-checker.yml
We should use the pull_request_target option here so that the PR runs from the pipeline in the target rather than the PR source branch. This allows the action to run with reduced security implications.
> [Action] Use pull_request_target

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/spirv.entry-function.prototype.hlsl
When the prototype of an entrypoint was defined, the codegen crashed because it failed to filter this partial declaration when adding functions to the work-queue.
Fixes #6750
> [SPIR-V] Fix crash when using entrypoint prototype

- tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
- tools/clang/test/CodeGenSPIRV/type.enum.templated.hlsl
Templated enums lowering was not supported. This commit fixes those cases.
Fixes #6753
> [SPIR-V] Lower templated enums correctly.

- lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
- tools/clang/test/HLSLFileCheck/passes/hl/sroa_hlsl/array-from-cbvec-1.ll
- tools/clang/test/HLSLFileCheck/passes/hl/sroa_hlsl/array-from-cbvec-2.ll
- tools/clang/test/HLSLFileCheck/passes/hl/sroa_hlsl/array-from-cbvec-3.ll
In the special code to handle the memcpy pattern where a constant buffer contains a vector array that initializes a local (or static global) scalar array for use by the shader, an invalid assumption was made that if the memcpy dest was global, that the src is global as well.
This was not the case, and when expecting to generate constant expressions to index the src, these generated orphaned instructions instead, leading to invalid IR.
This fixes the issue by leveraging ReplaceConstantWithInst, and setting the insertion point for the Builder. Now, replacement *could* fail, if src instructions don't dominate replacement uses, so bool for replaced all is returned from replaceScalarArrayWithVectorArray.
Another issue was that it would replace the dest for the original memcpy with src along …
> Fix CB vector to scalar array translation generating invalid IR (#6777)

- tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp
- tools/clang/test/DXC/FinishCodeGen/construct-global-array-of-struct.hlsl
In CGHLSLMSFinishCodeGen's BuildImmInit, when initializing an array, if the init value type doesn't match the array element type, we must bail and instead, have it inject a call to the global ctor. Without this, builds with asserts enabled would assert later with "Wrong type in array element initializer". In non-assert builds, this invalid IR would be removed, and valid code emitted.
See https://github.com/microsoft/DirectXShaderCompiler/issues/5294
> Fix assertion when compiling array of struct init

- tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp
- tools/clang/test/DXC/FinishCodeGen/construct-global.hlsl
In #6814, we modified the compiler to avoid generating bad code in some cases for array initializers. However, this caused a crash in the case where the initializer does not use a GEP expression for addressing because the `GV` will be null.
I considered setting `GV` to the value in the `store` pointer operand, but it looked like `GV` was also checked elsewhere for null and did not want to modify the behavior of the code in other places.
The fix is to check if we found a global variable before validating the array case.
> Fix crash in constant initializer lowering for global variable.

- docs/ReleaseNotes.md
Add note for loop structurizer fixes.
Fix the ReleaseNotes.md path.
> [Doc] Release note update for 1.8.2407.

- docs/ReleaseNotes.md
Add note for loop structurizer fixes.
Fix the ReleaseNotes.md path.
(cherry picked from commit 0777bff09272bbf666e933e039060c17e4b374ca)
> [Doc] Release note update for 1.8.2407. (#6821)

- include/llvm/ADT/SmallVector.h
Hit when compiled with `-fsanitize-memory-use-after-dtor`. This was fixed upstream here:
https://github.com/llvm/llvm-project/commit/527352b6ac01100f8a2d36ca895b663482202f00 This applies the same patch.
> Fix MSAN use-after-free in SmallVectorImpl dtor

- tools/clang/test/lit.cfg
Change Python regexp ' clang\+\+ ' to ' clang\\+\\+' We're trying to match fixed strings like ` clang++ `, but `\+` is not a valid Python escape sequence.  Use `\\+` so the regexp machinery sees `\+`
> Fix escape in Python string in lit.cfg

- lib/Transforms/Scalar/DxilFixConstArrayInitializer.cpp
- tools/clang/test/DXC/Passes/DxilFixConstArrayInitializer/negative-index.ll
If the index on a constant store into an array is negative or out of bounds, that's an error, but shouldn't make the compiler index a vector out of bounds.
Fixed: #6824
> Avoid OOB index when fixing constant array-initialization

- CMakeLists.txt
- include/llvm/llvm_assert/assert.h
- lib/Support/assert.cpp
- tools/clang/lib/SPIRV/String.cpp
This makes it possible to define how assert works on all platforms. The header was already being included by String.cpp, and was already designed to work for non-Windows platforms.
Also modify the non-Windows llvm_assert to emit the assertion message to stderr and trap. We cannot call standard assert as we are overriding it via include dirs, so there's no way to include the standard one and call it.
> Use llvm_assert/assert.h on all platforms, not just Windows

- tools/clang/lib/Sema/SemaHLSLDiagnoseTU.cpp
- tools/clang/test/SemaHLSL/hlsl/intrinsics/barrier/barrier-node-errors.hlsl
By default, the launch type should be set to ‘Broadcast’ when diagnosing barriers. However, the current behavior sets the default launch type to ‘Invalid,’ resulting in warnings when the launch type is not explicitly specified as an attribute.
To address this issue, we’ll adjust the default setting to ‘Broadcast’ and thereby resolve the problem.
Fixes #6836
> Fix warning when use implicit launch type.

- tools/clang/lib/Sema/SemaHLSLDiagnoseTU.cpp
- tools/clang/test/SemaHLSL/hlsl/intrinsics/barrier/barrier-node-errors.hlsl
By default, the launch type should be set to ‘Broadcast’ when diagnosing barriers. However, the current behavior sets the default launch type to ‘Invalid,’ resulting in warnings when the launch type is not explicitly specified as an attribute.
To address this issue, we’ll adjust the default setting to ‘Broadcast’ and thereby resolve the problem.
Fixes #6836
---------
Co-authored-by: Damyan Pepper <damyanp@microsoft.com>
(cherry picked from commit ef043e90f3f3c5b2db899380591b5091b05f002e)
> Fix warning when use implicit launch type. (#6837)

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/test/CodeGenSPIRV/implicit.global.ubo.hlsl
The code the decides which global variables to include in the implicit
global cbuffer does not check for spec constant or push constant. They
end up being incorrectly include in it, causing problems.
The solution is to add those to the type of variable that should be
skipped.
Fixes #4542
> [spirv] Avoid adding spec and push constants to global ubo

- include/dxc/Support/SPIRVOptions.h
- lib/DxcSupport/HLSLOptions.cpp
- tools/clang/lib/SPIRV/EmitVisitor.cpp
- tools/clang/test/CodeGenSPIRV/spirv.opt.gis.hlsl
- tools/clang/tools/dxcompiler/dxcompilerobj.cpp
> [SPIRV] Implement Gis option for spir-v

- lib/Transforms/Scalar/Reassociate.cpp
- test/HLSL/passes/reassociate/constant-counting.ll
In the middle of rewriting expressions like (A*B + A*C + D) to pull common factor A out, the algorithm finds that there's actually only one A. This is unexpected, and it fires an assertion.
This can occur when A is a constant, and constant -A also appears in the terms somewhere else.
There is no harm in this situation, however, because the algorithm then creates an addition-tree, but with a single element, and that's still correct.
This bookkeeping issue was fixed later in LLVM, at https://github.com/llvm/llvm-project/commit/95abfa35d6c0b8a769399262496a3f692177ef12
Unfortunately the associated test doesn't translate cleanly to DXC-era LLVM. I've added test case reduced from our original case.
Fixed: #6829
> Reassociation: fix counting of constant multiplicative factors

- tools/clang/lib/AST/ASTDumper.cpp
- tools/clang/lib/CodeGen/CodeGenAction.cpp
- tools/clang/lib/Sema/SemaExpr.cpp
When declaring a lambda with a value-capture default [=, ...], the this pointer is implicitly captured by value as well. This results in potentially-unintuitive behavior and has been deprecated in C++20. It produces a warning in newer versions of clang (https://reviews.llvm.org/D142639).
This PR makes the implicit captures explicit, preventing the warning. It does not change the compiled code at all, since it's just removing some syntactic sugar.
> [NFC] Remove implicit `this` capture in lambdas

- include/dxc/dxcapi.h
The ppOutputName parameter can be nullptr and can return nullptr. Change its SAL to _COM_Outptr_opt_result_maybenull_.
Related to #4149 .
> Fix the SAL of IDxcResult::GetOutput

- include/dxc/HLSL/DxilValidation.h
- lib/HLSL/DxilValidation.cpp
- tools/clang/tools/dxcompiler/dxcompilerobj.cpp
- tools/clang/tools/dxcompiler/dxcutil.cpp
- tools/clang/tools/dxcompiler/dxcvalidator.cpp
- tools/clang/tools/dxcvalidator/dxcvalidator.cpp
- tools/clang/tools/dxcvalidator/dxcvalidator.h
- tools/clang/tools/dxrfallbackcompiler/dxcutil.cpp
- tools/clang/tools/dxrfallbackcompiler/dxcvalidator.cpp
This change ensures that data validation occurs within the container itself, 
rather than relying on the module—especially since the module may be modified during container assembly.
Furthermore, simplifying the validator’s interface would be an added benefit.
> [Validator] Remove the pModule input for RunInternalValidator

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resource.and.array.hlsl
- tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resources.optimized.hlsl
When struct contains opaque resources, we must legalize the SPIR-V to move those resources out of the struct (Vulkan doesn't allow composite to store opaque resources).
Before this change, any resource array would also be flattened due to the pass flattening everything by default.
Patched SPIRV-Tools to allow some level of selection in what we flatten. Not perfect, as we would flatten all arrays or all composites and cannot pick only one variable to flatten, but for now this should be enough.
Fixes #6745
Signed-off-by: Nathan Gauër <brioche@google.com>
> [SPIR-V] Don't flatten arrays during legalization

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/shader.debug.function.hlsl
This PR moves the DebugFunctionDefinition instruction from the SPIR-V wrapper to the real function.   This supplies debugger users with greater accuracy.
> [SPIRV] Generate DebugFunctionDefinition in real function instead of wrapper

- include/dxc/DxilHash/DxilHash.h
- lib/CMakeLists.txt
- lib/DxilHash/CMakeLists.txt
- lib/DxilHash/DxilHash.cpp
- unittests/CMakeLists.txt
- unittests/DxilHash/CMakeLists.txt
- unittests/DxilHash/DxilHashTest.cpp
This pull request introduces the open-source implementation of hashing functionality for DXIL containers.
DxilHash.cpp: Implements DXBC/DXIL container hashing functions.
This is first part for #6808
> Open source DxilHash

- include/dxc/Support/HLSLOptions.td
- include/dxc/Support/SPIRVOptions.h
- lib/DxcSupport/HLSLOptions.cpp
- tools/clang/include/clang/SPIRV/SpirvBuilder.h
- tools/clang/include/clang/SPIRV/SpirvModule.h
- tools/clang/lib/SPIRV/CapabilityVisitor.cpp
- tools/clang/lib/SPIRV/FeatureManager.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/lib/SPIRV/SpirvModule.cpp
- tools/clang/test/CodeGenSPIRV/decoration.coherent.hlsl
- tools/clang/test/CodeGenSPIRV/intrinsics.interlocked-methods.ps.hlsl
- tools/clang/test/CodeGenSPIRV/intrinsics.interlocked-methods.raygeneration.hlsl
- tools/clang/test/CodeGenSPIRV/volatile.interface.raygen.vk1p1.hlsl
Some recent features require the vulkan memory model. We need a way to
support it in DXC. This commit adds an option to enable the Vulkan
memory model. The generated code will not change, but the compiler will
call the upgrade-memory-model pass in spirv-opt to generate the correct
code.
The expectation is that new code that requieres the vulkan memory model
can be written using the vulkan memory model, and then have the pass
update other references.
This change will undo the fix for #6066. The device scope in GLSL450 was
not a real device scope. It corresponds to QueueFamily scope in the
Vulkan memory model. We will start to use that scope for the atomic
operations in order to keep the behavoiur of the atomics the same
between the two memory models.
Haveing a true device scope atomic will …
> [SPIRV] Add vulkan memory option to DXC

- lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
- tools/clang/test/DXC/Passes/ScalarReplHLSL/scalarrepl-param-hlsl-entry-replace-zero-recurse-to-float.ll
- tools/clang/test/DXC/Passes/ScalarReplHLSL/scalarrepl-param-hlsl-entry-replace-zero-recurse-to-int.ll
This is the same fix as was done in
https://github.com/microsoft/DirectXShaderCompiler/pull/6516 except that this is for replace uses of zero-init for instructions in the entry block.
> scalarrepl-param-hlsl: fix zero replacement in entry

- .gitignore
The build* entry in .gitignore was intended to exclude any build directories with whatever suffixes a developer might use for various build configurations. The way it was written made it exclude any file that had build in the name, which was more aggressive than needed.
By adding a leading slash, it is limited to items in the git root directory. By adding a trailing slash, it is limited to directories in the root directory. This accomplishes the intended exclusions as narrowly as possible.
(I swear I'm not trying to win a bet on writing the longest description of a two character change in history)
Fixes #4733
> Correct build exclusion in gitignore

- docs/SPIR-V.rst
- tools/clang/include/clang/Basic/LangOptions.h
- tools/clang/include/clang/SPIRV/FeatureManager.h
- tools/clang/lib/Frontend/InitPreprocessor.cpp
- tools/clang/lib/SPIRV/FeatureManager.cpp
- tools/clang/test/CodeGenSPIRV/spirv.version.hlsl
- tools/clang/tools/dxcompiler/dxcompilerobj.cpp
With inline spir-v, it becomes important for users to know which version
of SPIR-V is being targeted. They may need to generate different code
depending on the version.
This commit add these `__SPIRV_MAJOR_VERSION__` and
`__SPIRV_MINOR_VERSION__` to the compiler.
> Add SPIRV version macros to DXC

- tools/clang/lib/SPIRV/LiteralTypeVisitor.cpp
- tools/clang/test/CodeGenSPIRV/select.int.lit.to.bool.hlsl
The code has an assert when processing an OpLoad in the literal visitor
to make sure that the result of the load is not a literal type. This is
not always true. If there is a compiler-generated, temporary variable
that gets its type from a literal, then the result type of the load will
have to be decuded by the literal visitor. That is not always possible.
However, the code already handle this situation correctly. If the result
of the load is a literal type, then the function will return true
without doing anything because `canDeduceTypeFromLitType` will return
false, as it should.
Fixes #6798
> Remove invalid assert in literal visitor

- lib/DxilContainer/DxilPipelineStateValidation.cpp
- tools/clang/test/DXC/dumpPSV_DS.hlsl
- tools/clang/test/DXC/dumpPSV_GS.hlsl
- tools/clang/test/DXC/dumpPSV_HS.hlsl
- tools/clang/test/DXC/dumpPSV_MS.hlsl
- tools/clang/test/DXC/dumpPSV_PS.hlsl
- tools/clang/test/DXC/dumpPSV_VS.hlsl
1. Number of SemanticIndex should match number of rows instead of number of columns.
2. Mesh shader could have ViewID mask for Primitive output.
For #6817.
> [Dump] Fix PSV dump issues.

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/nested.static.var.hlsl
The spir-v backend does not recurse into structs defined in struct in
doRecoredDecl. This causes us to miss some declarations.
Fixes #5916
> Process subrecord decls in spirv backend

- include/dxc/Support/HLSLOptions.td
- include/dxc/Support/SPIRVOptions.h
- lib/DxcSupport/HLSLOptions.cpp
- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/DeclResultIdMapper.h
- tools/clang/test/CodeGenSPIRV/semantic.nonzero-base-vertex.vs.hlsl
- tools/clang/test/CodeGenSPIRV/semantic.unsigned-nonzero-base-vertex.vs.hlsl
There is already a workaround for the SV_BaseInstance inconsistency between HLSL and SPIR-V. The same issue applies to SV_BaseVertex, but no such option is available. This commit adds the -fvk-support-nonzero-base-vertex option, which behaves the same as the -fvk-support-nonzero-base-instance option.
> [SPIR-V] add -fvk-support-nonzero-base-vertex option

- lib/DxilPIXPasses/DxilDbgValueToDbgDeclare.cpp
- tools/clang/lib/CodeGen/CGDebugInfo.cpp
- tools/clang/test/DXC/min16vector_disabled.hlsl
- tools/clang/test/DXC/min16vector_enabled.hlsl
- tools/clang/unittests/HLSL/PixDiaTest.cpp
This fixes a bug where the offsets for elements in vectors with 16-bit types doesn't take into account alignment bits and PIX wouldn't display vector element values correctly in the shader debugger. Eg. if `-enable-16bit-types` wasn't set, the offsets for a min16float4 would be 0, 16, 32, 48 instead of 0, 32, 64, 96.
Also removed the assert in PopulateAllocaMap_StructType that was checking whether the calculated aligned offset matches the packed offset (from SortedMembers) because it was false for members with sizes smaller than the alignment size.
(cherry picked from commit 84c0a095576c63d8103ffffc56bb165b3cf9ddf3)
> Cherry-Pick: Fix debug info offsets for vectors with 16-bit types (#6775)

- lib/HLSL/ComputeViewIdStateBuilder.cpp
- tools/clang/test/DXC/dumpPSV_MS.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/semantics/sv_viewid/mesh_shader_dependence.hlsl
Currently, viewid mask for primitive output is always empty. This change will fix it by treat entry as PC entry and skip output when it is not what is checking.
For #6817
> [ViewID] build viewid mask for primitive output

- lib/DxilPIXPasses/DxilAddPixelHitInstrumentation.cpp
- lib/DxilPIXPasses/DxilDebugInstrumentation.cpp
- lib/DxilPIXPasses/DxilOutputColorBecomesConstant.cpp
- lib/DxilPIXPasses/DxilPIXDXRInvocationsLog.cpp
- lib/DxilPIXPasses/DxilPIXMeshShaderOutputInstrumentation.cpp
- lib/DxilPIXPasses/DxilShaderAccessTracking.cpp
- lib/DxilPIXPasses/PixPassHelpers.cpp
- lib/DxilPIXPasses/PixPassHelpers.h
- tools/clang/test/HLSLFileCheck/pix/AccessTracking.hlsl
- tools/clang/test/HLSLFileCheck/pix/AccessTrackingForSamplerFeedback.hlsl
- tools/clang/test/HLSLFileCheck/pix/DebugBasic.hlsl
- tools/clang/test/HLSLFileCheck/pix/DebugCSParameters.hlsl
- tools/clang/test/HLSLFileCheck/pix/DebugMs.hlsl
- tools/clang/test/HLSLFileCheck/pix/DebugPSParameters.hlsl
- tools/clang/test/HLSLFileCheck/pix/DebugPreexistingSVInstance.hlsl
- tools/clang/test/HLSLFileCheck/pix/DebugPreexistingSVPosition.hlsl
- tools/clang/test/HLSLFileCheck/pix/DebugPreexistingSVVertex.hlsl
- tools/clang/test/HLSLFileCheck/pix/DebugVSParameters.hlsl
- tools/clang/test/HLSLFileCheck/pix/rawBufferStore.hlsl
- tools/clang/unittests/HLSL/PixTest.cpp
The impetus for these changes was unexplained crashes in a display driver while attempting to create a debug-instrumented shader for PIX. The heart of it is the new test in pixtest.cpp: use the compiler to generate a raw UAV, and then compare the generated DXIL with what PIX generates for the same purpose.
Some of the PIX passes need only one UAV for a module, but some need two or more. In the latter case, the previous code was a bit loose about what it was doing with respect to adding the UAV resource, and creating its handles for each interested function. Most of the actual changes herein are to do with that.
Lastly, the PIX UAV is raw at the D3D API level, but the instrumentation had been doing non-raw writes. No driver seemed to care, but I've fixed it anyway.
(cherry picked from …
> Cherry-Pick: PIX: Rationalize UAV generation (#6883)

- tools/clang/test/DXC/dumpPSV_AS.hlsl
- tools/clang/test/DXC/dumpPSV_CS.hlsl
- tools/clang/test/DXC/dumpPSV_DS.hlsl
- tools/clang/test/DXC/dumpPSV_GS.hlsl
- tools/clang/test/DXC/dumpPSV_HS.hlsl
- tools/clang/test/DXC/dumpPSV_MS.hlsl
- tools/clang/test/DXC/dumpPSV_PS.hlsl
- tools/clang/test/DXC/dumpPSV_VS.hlsl
- tools/clang/unittests/HLSL/PixTest.cpp
This change adds validation version check for the tests.
This is for fix tests fail when running on different version of validator.
> [Test] Add validator version check for tests

- tools/clang/lib/SPIRV/CapabilityVisitor.cpp
- tools/clang/test/CodeGenSPIRV/fn.export.hlsl
- tools/clang/test/CodeGenSPIRV/fn.export.with.entrypoint.hlsl
- tools/clang/test/CodeGenSPIRV/fn.fixfuncall-linkage.hlsl
We currently add the linkage attribute only if there are no extry
pointer. However, there are cases where we may want an extry point with
an exported function.
This commit add the linkage capability any time it sees the linkage
attribute decoration. Note I do not add the linkage attribute all of the
time and leave it to the capability trimming pass because having this
capability with vulkan shaders is generally illegal, and I don't want
the unoptimized code to fail validation.
Fixes #6738
> Add linkage capability based on decorations

- docs/SPIR-V.rst
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/texture.calculate-lod-unclamped.cmp.hlsl
- tools/clang/test/CodeGenSPIRV/texture.calculate-lod.cmp.hlsl
- tools/clang/test/CodeGenSPIRV/texture.sample-cmp-bias.hlsl
- tools/clang/test/CodeGenSPIRV/texture.sample-cmp-grad.hlsl
Compile `SampleCmpBias` using `OpImage*SampleDrefImplicitLod` and `SampleCmpGrad` using `OpImage*SampleDrefExplicitLod`.
The existing handlers for `CalculateLevelOfDetail` and `CalculateLevelOfDetailUnclamped` work for the
`SamplerComparisonSampler` overload, so no new code is needed other than tests.
> [SPIRV-V] Implement Shader Model 6.8 Expanded Comparison Sampling

- tools/clang/unittests/HLSL/PixTest.cpp
Partial cherry pickfrom commit  0fd84aa81440b6827705785a927d32b9d726349d
https://github.com/microsoft/DirectXShaderCompiler/commit/0fd84aa81440b6827705785a927d32b9d726349d
Original PR: https://github.com/microsoft/DirectXShaderCompiler/pull/6901
> PIX: Partial cherry pick of validator version fix 

- lib/Transforms/Scalar/DxilConditionalMem2Reg.cpp
- tools/clang/test/DXC/Passes/DxilConditionalMem2Reg/precise-vector-alloca-followed-by-use.hlsl
ScalarizePreciseVectorAlloca would iterate over all instructions, then for each instruction use, would iterate and potentially erase the instruction. If the erased instruction was the immediate next instruction after the alloca, this would invalidate the outer instruction iterator. Fixed by collecting the allocas in a vector first.
> Fix ASAN UAF in DxilConditionalMem2Reg

- projects/CMakeLists.txt
Target dxildll depends on DxcRuntimeEtw, so make sure to add this target, even when HLSL_BUILD_DXILCONV is false.
> Fix CMake gen failing when HLSL_BUILD_DXILCONV=0

- tools/clang/lib/Headers/hlsl/LICENSE.txt
- tools/clang/lib/Headers/hlsl/README.txt
As we're starting to grow some new language features that are more convienent to write in headers, having a set of headers that are distributable without attribution requirement is a big win. These headers will all be contributed under the Apache 2.0 with LLVM exception license to align with upstream LLVM and provide apporpriate protections.
> Add license and readme for HLSL header library

- tools/clang/lib/Headers/hlsl/vk/spirv.h
- tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
- tools/clang/lib/SPIRV/LowerTypeVisitor.h
- tools/clang/test/CMakeLists.txt
- tools/clang/test/CodeGenSPIRV/workgroupspirvpointer.hlsl
- tools/clang/test/CodeGenSPIRV/workgroupspirvpointer.varpointer.hlsl
- tools/clang/test/lit.cfg
- tools/clang/test/lit.site.cfg.in
Add specific handling for inline spirv pointer types
We currently blindly create a new type for all vk::SpirvType* types.
This can cause problems when the type is suppose to match another type.
In this case, we want a spirv pointer type to match the pointer type of the
variable. The OpTypePointer for the variable is implicitly created when
declaring the variable, but, if we want to explicitly declare the
pointer as a SpirvType, we get two different OpTypePointer instructions
in the module. So technically the types do not match.
To fix this, I add special handling in the SPIR-V backend to be able to
merge the implicit pointer type created and the SpirvType when they
match.
This implements the SPIR-V Pointers in [HLSL spec proposal …
> Add specific handling for inline spirv pointer types

- include/dxc/DxilContainer/DxilPipelineStateValidation.h
- lib/DxilContainer/DxilContainerAssembler.cpp
- lib/DxilContainer/DxilPipelineStateValidation.cpp
- lib/DxilValidation/DxilContainerValidation.cpp
- projects/dxilconv/lib/DxbcConverter/DxbcConverter.cpp
- tools/clang/test/DXC/dumpPSV_HS.hlsl
- tools/clang/test/DXILValidation/hs_signatures.hlsl
- tools/clang/unittests/HLSL/ValidationTest.cpp
- utils/hct/hctdb.py
Replace the memcpy check for PSV0 part.
Build DxilPipelineStateValidation object from data in PSV0 part. Then compare the content with information from input DxilModule.
With this change, the order of signature elements and resources could be different between the container and the DxilModule.
And the StringTable could be in different order as well.
Second step for #6817
> [Validator] Check content of PSV0 part in validation

- include/dxc/DxilContainer/DxilPipelineStateValidation.h
DxilPipelineStateValidation.h is included from multiple environments. Conditionally include <assert.h> here is to avoid overwriting the assert that's using by the code which includes this header.
Fixes #6922
> Conditionally include <assert.h> in DxilPipelineStateValidation.h

- include/dxc/Support/HLSLOptions.td
- include/dxc/Support/SPIRVOptions.h
- lib/DxcSupport/HLSLOptions.cpp
- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/DeclResultIdMapper.h
- tools/clang/test/CodeGenSPIRV/sm6_6.descriptorheap.aliasing.hlsl
- tools/clang/test/CodeGenSPIRV/sm6_6.descriptorheap.flag.invalid.hlsl
- tools/clang/test/CodeGenSPIRV/sm6_6.descriptorheap.flag.missing.hlsl
- tools/clang/test/CodeGenSPIRV/sm6_6.descriptorheap.flag.negative.hlsl
- tools/clang/test/CodeGenSPIRV/sm6_6.descriptorheap.implicit-bindings.cbuffer.flag.hlsl
- tools/clang/test/CodeGenSPIRV/sm6_6.descriptorheap.implicit-bindings.counter.flag.hlsl
- tools/clang/test/CodeGenSPIRV/sm6_6.descriptorheap.implicit-bindings.flag.hlsl
- tools/clang/test/CodeGenSPIRV/sm6_6.descriptorheap.implicit-bindings.reserved.hlsl
- tools/clang/test/CodeGenSPIRV/sm6_6.descriptorheap.implicit-bindings.uav.flag.hlsl
- tools/clang/test/CodeGenSPIRV/sm6_6.descriptorheap.implicit-set.counter.unused.hlsl
Those flags allow the user to hardcode the binding ID for the heaps. This allow the user to either force heap aliasing, or simply have more control over the heaps.
Fixes #6913
> [SPIR-V] Add -fvk-bind-*-heap flag to DXC

- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/CodeGenHLSL/SplatGroupSharedScalar.hlsl
- tools/clang/test/CodeGenSPIRV/op.vector.swizzle.hlsl
- tools/clang/test/CodeGenSPIRV/op.vector.swizzle.size1.hlsl
When splatting a groupshared scalar, we would trip an "Invalid constantexpr cast!" assertion. This would happen while evaluating the ImplicitCastExpr to turn the groupshared scalar into a vector because the scalar expression was in a different address space (groupshared) vs the target vector (local). The fix is to ensure that when looking up the vector member expression, insert an lvalue-to-rvalue cast if necessary; i.e. when a swizzle contains duplicate elements.
> Fix assertion on splat of groupshared scalar

- lib/DxcSupport/HLSLOptions.cpp
> [SPIR-V] Fix build with -DENABLE_SPIRV_CODEGEN=OFF

- tools/clang/lib/Headers/hlsl/vk/khr/cooperative_matrix.h
- tools/clang/lib/Headers/hlsl/vk/khr/cooperative_matrix.impl
- tools/clang/lib/Headers/hlsl/vk/opcode_selector.h
- tools/clang/lib/Headers/hlsl/vk/spirv.h
- tools/clang/lib/SPIRV/EmitVisitor.cpp
- tools/clang/lib/SPIRV/EmitVisitor.h
- tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/convert.selector.hlsl
- tools/clang/test/CodeGenSPIRV/coopmatrix.arithmetic.hlsl
- tools/clang/test/CodeGenSPIRV/coopmatrix.convert.hlsl
- tools/clang/test/CodeGenSPIRV/coopmatrix.element.access.hlsl
- tools/clang/test/CodeGenSPIRV/coopmatrix.globallycoherent.hlsl
- tools/clang/test/CodeGenSPIRV/coopmatrix.groupshared.hlsl
- tools/clang/test/CodeGenSPIRV/coopmatrix.memory.operand.hlsl
- tools/clang/test/CodeGenSPIRV/coopmatrix.old.spirv.hlsl
- tools/clang/test/CodeGenSPIRV/coopmatrix_muladd_test.hlsl
- tools/clang/test/CodeGenSPIRV/workgroupspirvpointer.const.hlsl
This pr will introduce the HLSL standard header files. This will become the a
way to add new extensions to HLSL without having to make modifications to the
compiler.
This first example is a fairly complex example that demonstrates how to do a few
different things:
1. Trying to create a simple class interface that allows the compiler to
naturally enforce the validation rules. In this case, we might be more strict
than the spir-v validation, but I believe this is still usable.
2. How to create a builtin that can be expanded by the spir-v backend. The 
OpCooperativeMatrixLengthKHR instruction does not have an interface that is
natural in a language like HLSL. However, we can define a function that is, and
have the backend, make small adjustments. These cases should be avoided as much
as …
> Add header file to define cooperative matrices in spir-v

- tools/clang/test/CodeGenSPIRV/workgroupspirvpointer.hlsl
- tools/clang/test/CodeGenSPIRV/workgroupspirvpointer.varpointer.hlsl
The workgroupspirvpointer tests use `dxc` in the run commands, and it
should be `%dxc`.
> [SPIRV] Change "dxc" to "%dxc" in tests

- tools/clang/lib/SPIRV/EmitVisitor.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/shader.debug.opsource.include.hlsl
- tools/clang/tools/dxcompiler/dxcompilerobj.cpp
Previously, we fixed the SPIRV OpenCL debug info to always represent all include files, even those that only have preprocessor definitions.  This work was merged in https://github.com/microsoft/DirectXShaderCompiler/pull/6094.  This PR applies the same fix to the NonSemantic debug info, and resolves https://github.com/microsoft/DirectXShaderCompiler/issues/6907
> [SPIRV] Fix NonSemanticDebugInfo to include all files

- docs/ReleaseNotes.md
- include/dxc/DxilContainer/DxilPipelineStateValidation.h
- lib/DxilContainer/DxilContainerAssembler.cpp
- lib/DxilContainer/DxilPipelineStateValidation.cpp
- lib/DxilValidation/DxilContainerValidation.cpp
- tools/clang/unittests/HLSL/ValidationTest.cpp
- utils/hct/hctdb.py
Check size of PSV part matches the PSVVersion.
Updated DxilPipelineStateValidation::ReadOrWrite to read based on initInfo.PSVVersion.
And return fail when size mismatch in RWMode::Read.
Fixes #6817
> [Validator] Check size of PSV.

- lib/DXIL/DxilTypeSystem.cpp
- tools/clang/unittests/HLSL/DxilModuleTest.cpp
> Fix DxilPayloadFieldAnnotation::GetPayloadFieldQualifier

- lib/DxilPIXPasses/DxilDebugInstrumentation.cpp
- lib/DxilPIXPasses/DxilShaderAccessTracking.cpp
- tools/clang/test/HLSLFileCheck/pix/AccessTrackingDXRDynamicTLAS.hlsl
- tools/clang/test/HLSLFileCheck/pix/DebugBasic.hlsl
Simple missing case, should have implemented it in the first place.
Also noticed that from a recent change to move to raw buffer writes, the debug output UAV offset was being set to a non-dword aligned offset. No drivers/hardware seem to care, but it's a concerning thing to leave as-is.
> PIX: Implement shader access tracking for descriptor-heap-indexed TLAS for TraceRay

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/DeclResultIdMapper.h
- tools/clang/test/CodeGenSPIRV/static_member_var.hlsl
Some variable can have multiple decls. In one case, there could be a
declaration of a const static member variable that is later defined. All
of these decls need to be in astDecls and associated with the same
variable.
The current code will only add the decl for the defintion. This leads to
problems when trying to find the variable for the declaration.
Fixes #6787
> [SPIRV] Register all decls for a variable.

- tools/clang/lib/SPIRV/AlignmentSizeCalculator.cpp
- tools/clang/test/CodeGenSPIRV/array.scalar.layout.hlsl
We currently pick the size of a struct to be the stride of the array
elements when doing scalar layout. This is not correct because this
could cause the struct to not be correctly aligned.
This is fixed by rounding the size of the struct up to a mutliple of the
alignment.
Fixes #6947
> [SPIRV] Round the stride to be a multiple of the alignment.

- tools/clang/lib/SPIRV/DeclResultIdMapper.h
- tools/clang/test/CodeGenSPIRV/ext_builtin_input.lib.hlsl
The function `DeclResultIdMapper::isInputStorageClass` tries to
determine the storage class for the stage variable by looking at its
SigPoint. This does not always work.
This change simply looks at the storage class that is already associated
with the variable, which should have been set when the StageVar was
created.
Fixes #6959
> [SPIRV] Simplify looking for input storage class

- include/llvm/Support/DataTypes.h.cmake
Apply LLVM patch: https://reviews.llvm.org/D21553
GitHub commit: https://github.com/llvm/llvm-project/commit/f4437e9b488d3340e0c01642e925ca6c54f5c426#diff-5fb0c3e347a7fc69d806be92c7b786cda1018152b3d264e3293697a1ac41eb7eR61
This fixes compilation of DXC with latest libc++, which removes C headers like locale.h and stdint.h:
https://github.com/llvm/llvm-project/commit/aa7f377c965ca79cf3022ddafe6cbd419bd52db5
> Do not require __STDC_LIMIT_MACROS and others

- tools/clang/test/CodeGenSPIRV/vk.shading-rate.optimized.hlsl
Updated the SPIRV-Tools version to bring 2 fixes.
Fixes #6915
> [SPIR-V] Fixes SPV_KHR_fragment_shading_rate preventing optimizations

- tools/clang/include/clang/SPIRV/SpirvContext.h
- tools/clang/lib/SPIRV/CapabilityVisitor.cpp
- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
- tools/clang/test/CodeGenSPIRV/op.buffer.access.hlsl
- tools/clang/test/CodeGenSPIRV/vk.attribute.image-format.unknown.hlsl
- tools/clang/test/CodeGenSPIRV/vk.attribute.image-format.unknown.read.hlsl
By default, texture format is guessed from the type. But the `vk::image_format` attribute can be added to specify it.
The `unknown` value was used to convey `no format selected`, and require the guess to happen.
This made selecting `unknown` as value impossible.
Once the optional added, we have a new issue:
- The format setup relied on the legalizer.
- load/stores are done using the default format, then we fix it, then we use the legalizer to propagate the format fix to all users.
The capability visitor is running before the legalizer, meaning it can look at a non-fixed load, which still carries the old type.
The way to solve this is to remove this logic, and move the capability addition/deletion to the capability_trimming pass, run after legalization.
Fixes #6981
> [SPIR-V] Fix image write to unknown format

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/intrinsics.asuint.hlsl
`asuint` should be able to take vectors in addition to scalar values. Previously, it would be lowered as a bitcast from the input value to a vector of uints with a width of 2, which is not large enough if the input value is larger than a scalar value. In order to handle, for example, an input value that is a `double4`, we instead perform a component-wise bitcast.
Fixes #6735
> [SPIR-V] Handle vectors passed to asuint

- lib/DxilPIXPasses/DxilDebugInstrumentation.cpp
- lib/DxilPIXPasses/DxilShaderAccessTracking.cpp
- tools/clang/test/HLSLFileCheck/pix/AccessTrackingDXRDynamicTLAS.hlsl
- tools/clang/test/HLSLFileCheck/pix/DebugBasic.hlsl
Turns out some drivers DO care. Specifically new hardware from a particular hardware partner. Original PR comment:
Simple missing case, should have implemented it in the first place. Also noticed that from a recent change to move to raw buffer writes, the debug output UAV offset was being set to a non-dword aligned offset. No drivers/hardware seem to care, but it's a concerning thing to leave as-is.
(cherry picked from commit 080aeb7199e66e4b0a2b6383fd26a9f8d2cccbf5)
> CP: PIX: Implement shader access tracking for descriptor-heap-indexed TLAS (#6950)

- tools/clang/lib/SPIRV/InitListHandler.cpp
- tools/clang/test/CodeGenSPIRV/init.list.cast.hlsl
- tools/clang/test/CodeGenSPIRV/shader.debug.line.composite.hlsl
- tools/clang/test/CodeGenSPIRV/spirv.debug.opline.composite.hlsl
- tools/clang/test/CodeGenSPIRV/type.template.function.empty-struct-argument.hlsl
- tools/clang/test/CodeGenSPIRV/var.init.matrix.mxn.hlsl
When an a chain of casts were performed in an initializer list, only the source and destination types were considered. This means float -> uint was the same as float -> int -> uint. This however is not correct: intermediate casts can change the result.
Removing the shortcut we took solves this issue.
Fixes #6975
> [SPIR-V] Fix cast elision with initializer lists

- tools/clang/unittests/HLSL/DxilContainerTest.cpp
Compare hashFromPart and hashFromResult.
Fixes #5147
> [Test] fix typo in CompileToShaderHash which compares same value.

- test/HLSL/opt/help.ll
- tools/opt/opt.cpp
Add -help option to opt in opt.cpp.
The -help option for opt in clean llvm3.7 was disabled with 
[disable -help](https://github.com/microsoft/DirectXShaderCompiler/commit/d5bb3089cf20456d70941b2b00febd7f7dde4a53#diff-1c7e1b16bc72f52ebd811ef2a24aa91fc4df0f9b47c279b75d0bbb0ae1684d0aR1719)
Fixes #5514
> [tools] add -help option for opt.

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/rich.debug.debugscope.hlsl
- tools/clang/test/CodeGenSPIRV/rich.debug.function.param.hlsl
- tools/clang/test/CodeGenSPIRV/rich.debug.global-variable.hlsl
- tools/clang/test/CodeGenSPIRV/rich.debug.local-variable.hlsl
- tools/clang/test/CodeGenSPIRV/rich.debug.type.float.hlsl
- tools/clang/test/CodeGenSPIRV/shader.debug.function.hlsl
https://github.com/microsoft/DirectXShaderCompiler/pull/6758 unfortunately caused a regression for shaders compiled without -fcgl.  This PR extends the original fix and corrects the regression.  We now emit DebugFunction and DebugFunctionDefinition pairs for both the wrapper and the main functions, and a DebugEntrypoint that points at the wrapper function.  This survives inlining.
> [SPIRV] Emit DebugFunction/Definition for both wrapper and real functions

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/func.noidentifier.hlsl
We hit an assert when trying to get the name of `operator()`. This is
fixed by first checking if it function declatarion is an identifier.
Fixes #6973
> [SPIRV] Check if decl is identifier before getting name

- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/CodeGenDXIL/hlsl/types/type-enum-cast.hlsl
- tools/clang/test/CodeGenSPIRV/type.enum.cast.hlsl
- tools/clang/test/CodeGenSPIRV/type.enum.hlsl
An implicit cast from int enum to a float should be a Floating_Integral cast, not an Integral_Conversion.
Fixes #6884
> sema: fix int enum implicit cast to float.

- lib/DxilPIXPasses/DxilAnnotateWithVirtualRegister.cpp
- lib/DxilPIXPasses/DxilShaderAccessTracking.cpp
- tools/clang/unittests/HLSL/PixTest.cpp
- tools/clang/unittests/HLSL/PixTestUtils.cpp
Original PRs:
https://github.com/microsoft/DirectXShaderCompiler/pull/6990
(cherry picked from commit https://github.com/microsoft/DirectXShaderCompiler/commit/a03a77f7efa49eabe341b331b9066e60ae9aadce)
https://github.com/microsoft/DirectXShaderCompiler/pull/7010
(cherry picked from commit https://github.com/microsoft/DirectXShaderCompiler/commit/848b7c42bd8da13693273513412c0a554c7918a1)
> PIX: Cherry pick (split vector writes, and SAT pass returns modification status)

- tools/clang/lib/SPIRV/EmitVisitor.cpp
- tools/clang/test/CodeGenSPIRV/shader.debug.line.composite.hlsl
Update submodules in preparation for release.
> [SPIR-V] Update submodules

- lib/IR/AsmWriter.cpp
- unittests/IR/AsmWriterTest.cpp
- unittests/IR/CMakeLists.txt
Applying patch from upstream LLVM:
https://github.com/llvm/llvm-project/commit/b9b50aaffddf9b3d7b22f42a332811dddb6b9440#diff-69d28d03f6d27b8c800ff1dafb34ede6999a3165c109263e7da48dbbdf964f0aR9
> Fix crash when printing instructions that have a metadata attached but no parent.

- lib/Analysis/LoopPass.cpp
This adds time trace hooks to instrument loop pass manager exectuion logging the function as a scope and each pass under the function.
> [NFC] Instrument loop pass manager

- cmake/modules/HandleLLVMOptions.cmake
Newer versions of CMake have a more robust way of handling debug information settings for Windows. Forcing this on breaks the ability to control how debug info is generated and gets in the way of using sccache.
See CMake's docs:
https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_DEBUG_INFORMATION_FORMAT.html
> Don't force /Zi when using CMAKE_MSVC_DEBUG_INFORMATION_FORMAT

- include/dxc/Support/DxcOptToggles.h
- include/llvm/ADT/StringRef.h
Small change to switch from llvm::StringRef to char* to prevent incurring a large number of static initializers.  See dump of static initializers before and after this change from a release build of dxcompiler.dll.
[static_initializers_after.txt](https://github.com/user-attachments/files/17283018/static_initializers_after.txt)
[static_initializers_before.txt](https://github.com/user-attachments/files/17283019/static_initializers_before.txt)
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/6896
> Remove static initializers for llvm::StringRef

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/rich.debug.debugscope.hlsl
- tools/clang/test/CodeGenSPIRV/rich.debug.function.param.hlsl
- tools/clang/test/CodeGenSPIRV/rich.debug.global-variable.hlsl
- tools/clang/test/CodeGenSPIRV/rich.debug.local-variable.hlsl
- tools/clang/test/CodeGenSPIRV/rich.debug.type.float.hlsl
- tools/clang/test/CodeGenSPIRV/rich.debug.vulkan.member.function.param.hlsl
- tools/clang/test/CodeGenSPIRV/shader.debug.function.hlsl
Recent changes to the debug information generated by the wrapper function lacked one fix. This produced mismatches between function parameter DebugLocalVariable's and DebugDeclare instructions.  Following wrapper generation, the DebugScope should be set to src_main, not the wrapper.  This PR corrects this oversight.
> [SPIRV] Correct local variable declaration scope

- lib/Analysis/VectorUtils2.cpp
- tools/clang/test/CodeGenHLSL/minimal2.ll
The simplify instruction pass has a function called `findScalarElement`.
This function will possibly recurse infinitely into the first operand of the instruction that it is passed. If this instruction, for example, is  `%2 = insertelement <2 x i32> %2, i32 %sub, i32 0`
Then the pass will recurse into the first operand of the insertelement instruction, which is the same insertelement instruction, and so on. This PR prevents infinite recursion and stack overflow by bailing out of the function early if there is a detection of the same value in the first operand.
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/7034
> [DXIL] Avoid infinite loop / stack overflow on invalid instruction

- tools/clang/lib/SPIRV/RawBufferMethods.cpp
- tools/clang/test/CodeGenSPIRV/method.byte-address-buffer.load.double.capability.hlsl
- tools/clang/test/CodeGenSPIRV/method.byte-address-buffer.templated-load.matrix.hlsl
- tools/clang/test/CodeGenSPIRV/method.byte-address-buffer.templated-load.scalar.hlsl
- tools/clang/test/CodeGenSPIRV/method.byte-address-buffer.templated-load.vector.hlsl
- tools/clang/test/CodeGenSPIRV/method.byte-address-buffer.templated-store.struct.hlsl
When loading a Float64 from a raw buffer, we used an Int64, which required an additional capability, even if the code wasn't using any Int64.
In practice, it seems most devices supporting Float64 do also support Int64, but this it doesn't have to.
By changing the codegen a bit, we can avoid the Int64 value.
Tested the word-order using a vulkan compute shader, and checking the returned value on the API side.
```hlsl
double tmp = buffer.Load<double>(0);
if (tmp == 12.0)
buffer.Store<double>(0, 13.0);
```
Fixes #7038
> [SPIR-V] Avoid emitting Int64 when loading Float64

- tools/clang/test/CodeGenHLSL/vector-and.hlsl
- tools/clang/test/CodeGenHLSL/vector-or.hlsl
- tools/clang/test/CodeGenSPIRV/intrinsics.and.hlsl
- tools/clang/test/CodeGenSPIRV/intrinsics.or.hlsl
- utils/hct/gen_intrin_main.txt
And/or intrinsics were set to allow any parameters, which is consistent with the behavior of the && and || operators they were meant to replace, however this meant that if they were passed floating point values, those values would be applied to the binary and/or operands, which isn't allowed. Instead, they should be converted to booleans to be consistent with the behavior of && and ||. This can be done simply by restricting the parameters to booleans which forces the appropriate conversions. Adds tests for for using bools, ints, and floats in scalars, different sized vectors, and matrices as parameters to or and and.
Fixes: #7057
FIxes: #6995
> Fix and/or intrinsics with non-int parameters

- azure-pipelines.yml
When the pipeline builds and tests in a windows environment, the time limit of 90 minutes reached. There is an insufficient amount of time available to run the pipeline in the windows environment. So, this PR increases the limit to 120 minutes.
Here is an example of insufficient time constraints:
https://github.com/microsoft/DirectXShaderCompiler/pull/7065
Additionally, this PR explicitly adds a trigger when a PR is created, so that the pipeline is explicitly run when that event happens. This allows the pipeline to be run with stricter security rules.
> [Pipelines] Extend time and add PR trigger

- docs/ReleaseNotes.md
- tools/clang/test/CodeGenHLSL/vector-and.hlsl
- tools/clang/test/CodeGenHLSL/vector-or.hlsl
- tools/clang/test/CodeGenSPIRV/intrinsics.and.hlsl
- tools/clang/test/CodeGenSPIRV/intrinsics.or.hlsl
- utils/hct/gen_intrin_main.txt
Cherry-pick of #7060 to release-1.8.2502
And/or intrinsics were set to allow any parameters, which is consistent
with the behavior of the && and || operators they were meant to replace,
however this meant that if they were passed floating point values, those
values would be applied to the binary and/or operands, which isn't
allowed. Instead, they should be converted to booleans to be consistent
with the behavior of && and ||. This can be done simply by restricting
the parameters to booleans which forces the appropriate conversions.
Adds tests for for using bools, ints, and floats in scalars, different
sized vectors, and matrices as parameters to or and and.
Fixes: #7057
Fixes: #6995
(cherry picked from commit 25faa88053437c30e599b9e5323c94addc2397a1)
> Fix and/or intrinsics with non-int parameters (cp to 1.8.2502)

- lib/DxilContainer/DxcContainerBuilder.cpp
- tools/clang/tools/dxclib/dxc.cpp
- tools/clang/unittests/HLSL/ValidationTest.cpp
Some error handling changes were incorrectly made to the container assembler, as described in the issue below. 
This is bad because the API protocol for error handling must remain consistent across all functions. This PR
aims to restore the correct semantic meaning of returning bad HR values. 
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/7051
> [Error Handling] Fix DxcContainerBuilder error handling

- azure-pipelines.yml
- cmake/modules/Nuget.cmake
- tools/clang/test/CMakeLists.txt
- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
- utils/hct/hctbuild.cmd
- utils/hct/hcttest.cmd
Cherry-pick of https://github.com/microsoft/DirectXShaderCompiler/pull/7101 to release-1.8.2502
Add a test target to run exec tests with latest warp from nuget
**Overview:**
This PR resolves https://github.com/microsoft/DirectXShaderCompiler/issues/6505. It adds a cmake file with logic to install nuget
packages. It was specifically added so the exec tests could install the
latest d3d warp nuget, ensuring the latest shader model support we have.
Additionally, the nuget install logic has the ability to install the
latest prerelese d3d warp nuget. Selection of the prerelease vs release
is toggled using an environment variable. This new logic is accessible
by using a new test target 'check-clang-taef-exec-warp'. Alternatively,
you can use the the hctbuild script and 'hcttest exec-warp' or …
> Add a test target to run exec tests with latest warp from nuget (cp to 1.8.2502)

- .github/ISSUE_TEMPLATE/release.md
- README.md
- docs/ReleaseNotes.md
Some update to clarify the release procedure and to update the current release notes with PR links. The readme should also now mention the inclusion of dxv.exe in each release.
> [NFC][Docs] Update release notes / release template process

- lib/Support/assert.cpp
- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
Some functions need to be removed / changed to unblock some internal pipelines. They are emitting warnings that they are unused.
Specifically, `CompareOutputWithExpectedValueFloat`, `CompareOutputWithExpectedValueHalf`, and `CompareOutputWithExpectedValueFloat` need to be removed because they are unused.
Additionally, there is a case in assert.cpp where `llvm_assert_trap` is left unused depending on what's been defined and how the preprocessor directives execute. This needs to be remedied so that the function is only defined when it is used.
> [NFC] Remove unused functions in ExecutionTest.cpp and assert.cpp

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/texture.calculate.lod.compute.linear.hlsl
- tools/clang/test/CodeGenSPIRV/texture.calculate.lod.compute.quad.hlsl
- tools/clang/test/CodeGenSPIRV/texture.calculate.lod.unclamped.compute.linear.hlsl
- tools/clang/test/CodeGenSPIRV/texture.calculate.lod.unclamped.compute.quad.hlsl
- tools/clang/test/CodeGenSPIRV/texture.sample.compute.linear.hlsl
- tools/clang/test/CodeGenSPIRV/texture.sample.compute.quad.hlsl
- tools/clang/test/CodeGenSPIRV/texture.samplebias.compute.linear.hlsl
- tools/clang/test/CodeGenSPIRV/texture.samplebias.compute.quad.hlsl
- tools/clang/test/CodeGenSPIRV/texture.samplecmp.compute.linear.hlsl
- tools/clang/test/CodeGenSPIRV/texture.samplecmp.compute.quad.hlsl
That pass was intended to remove derivative instructions used in
non-fragment shaders. Now they are available in more places because of
new extensions. In general,
it is better practice to issue an error if they are used in an place
they are not allowed.
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/7086
> [SPIRV] Stop running ReplaceInvalidOpcPass

- tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
- tools/clang/test/CodeGenSPIRV/vk.attribute.image-format.hlsl
A case was missed when adding the `vk::image_format` to the image types.
We did not handle runtime arrays. We fix that oversight.
Fixes #6880
> [SPIRV] Add the vk::image_format to runtime arrays

- docs/ReleaseNotes.md
An internal fix has changed the way PDB files are packaged on release. This change is worth noting in the release notes for 1.8.2502.
> Add PDB release note to 1.8.2502

- tools/clang/include/clang/Basic/Attr.td
- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/include/clang/SPIRV/SpirvType.h
- tools/clang/include/clang/Sema/AttributeList.h
- tools/clang/lib/SPIRV/EmitVisitor.cpp
- tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
- tools/clang/test/CodeGenSPIRV/inline-spirv/spv.inline.decorate.member.hlsl
- tools/clang/test/SemaHLSL/attributes/spv.inline.decorate.member.hlsl
- tools/clang/utils/TableGen/ClangAttrEmitter.cpp
This commit implements adding the `vk::ext_decorate` on a field. It also
adds an error in sema if `vk::ext_decorate_id` or
`vk::ext_decorate_string` are used on members.
For `vk::ext_decorate_id`, there is no `OpMemberDecorateId` instruction,
so we cannot add apply these decorations to members.
For `vk::ext_decorate_string`, there is only one decoration that uses
OpDecorateString or OpMemberDecorateString, UserSemantic. However, that
decoration could have used OpDecorate or OpMemberDecorate because those
instructions accept string literals. I do not expect any new decorations
to use OpDecorateString or OpMemberDecorateString. I may eventually want
to deprecate `vk::ext_decorate_string`.
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/4195
> [SPIRV] Fix decoration attributes on members.

- tools/clang/lib/SPIRV/SpirvBuilder.cpp
- tools/clang/test/CodeGenSPIRV/op.struct.access.bitfield.sized.read.hlsl
For an unsigned integer, we should OpShiftRightLogical instead of OpShiftRightArithmetic. Otherwise the value may be extended incorrectly.
For example:
```
struct S {
uint16_t m1 : 8;
uint16_t m2 : 8;
};
void main() {
S s;
s.m1 = 0xff;
s.m2 = 0xff;
uint16_t result = s.m1;
}
```
If we do OpShiftRightArithmetic here, the result will be 0xffff.
> [SPIR-V] Fix OpBitFieldExtract emulation for unsigned integer

- tools/clang/test/CodeGenDXIL/hlsl/intrinsics/dot.hlsl
When built without spirv, the CGL tests were offset by 5 because of the missing opcodes. This captures the preliminary opcode and confirms that it matches everywhere it should.
> Make unsigned dot test more robust

- README.md
- cmake/config-ix.cmake
- cmake/modules/FindMetalIRConverter.cmake
- include/dxc/Support/HLSLOptions.h
- include/dxc/Support/HLSLOptions.td
- lib/DxcSupport/HLSLOptions.cpp
- tools/clang/test/DXC/metal.test
- tools/clang/test/DXC/no_metal.test
- tools/clang/test/DXC/no_metal_disassembly.test
- tools/clang/test/lit.cfg
- tools/clang/test/lit.site.cfg.in
- tools/clang/tools/dxcompiler/CMakeLists.txt
- tools/clang/tools/dxcompiler/dxcompilerobj.cpp
This adds a new `-metal` flag to DXC which can be used to generate Metal's IR directly from DXC after compilation. There are some limitations in this flag which are worth noting:
1) It does not support library shaders (yet)
2) It does not support disassembly (yet)
3) It is _wildly_ under tested because wtihout (2) we can't do anything to really verify correct output (yay?)
> [Metal] Add experimental Metal support

- lib/DxilValidation/DxilContainerValidation.cpp
DxilContainerValidation.cpp has some int / bool comparisons that cause default error warnings in some of the private builds.
This needs to be addressed. This PR changes the comparisons by converting the numerical expressions into the appropriate boolean, then comparing the booleans.
> Resolve some default error warnings

- lib/DxilValidation/DxilContainerValidation.cpp
DxilContainerValidation.cpp has some int / bool comparisons that cause default error warnings in some of the private builds. This needs to be addressed. This PR changes the comparisons by converting the numerical expressions into the appropriate boolean, then comparing the booleans.
> Resolve some default error warnings (#7191)

- include/dxc/dxcapi.internal.h
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/unittests/HLSL/ExtensionTest.cpp
- utils/hct/hctdb.py
- utils/hct/hctdb_instrhelp.py
HLSL_INTRINSIC will need to be updated for SM 6.9, specifically:
- to add a new flag
- to encode minimum shader model version for an availability attribute
Changing this structure is a breaking change to the internal intrinsic table protocol, which is used for the extension mechanism.
This change separates out the breaking change with no functional changes for simpler review and testing.
For the new flag, this change switches to using a UINT Flags field to make flags extensible without breaking the table format. For the version, a UINT MinShaderModel will be the encoded version format used elsewhere: (Major << 4) | (Minor & 0xF)
Commented code for using the MinShaderModel is provided for when a subsequent change will implement the availability attribute checks.
> NFC: Update HLSL_INTRINSIC struct for Flags and MinShaderModel fields

- tools/clang/lib/SPIRV/SpirvBuilder.cpp
- tools/clang/test/CodeGenSPIRV/op.struct.access.bitfield.sized.rvalue.hlsl
Otherwise, the result of bitfield extract emulation is treated as LValue and may have an extra OpLoad generated.
> [SPIR-V] Set RValue for the result of bitfield extract emulation

- .github/workflows/clang-format-checker.yml
Aligning with upstream LLVM's action definition.
> Switch from tj-actions/changed-files to step-security/changed-files

- .github/workflows/clang-format-checker.yml
- tools/clang/include/clang/Basic/DiagnosticSemaKinds.td
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/SemaHLSL/hlsl/types/invalid-longvec-swizzle.hlsl
This PR addresses https://github.com/microsoft/DirectXShaderCompiler/issues/7194 by adding a new error string in DiagnosticSemaKinds.td and emitting it in SemaHLSL.cpp. 
@pow2clk implemented most of this in his [fork](https://github.com/microsoft/DirectXShaderCompiler/commit/a41e0a69db6fd072ffe8f1c811bf3dadcc2ab8fe). I'm just helping to finish it.
**How verified:**
1. Several new test cases were added and verified locally
2. Ran hcttest locally
> Disallow swizzling on long vectors

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/lib.fn.export.with.entrypoint.hlsl
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/7161
> [SPIRV] Don't assume entry points are at the start of the worklist.

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/cs.groupshared.function-param.out.hlsl
- tools/clang/test/CodeGenSPIRV/fn.fixfuncall-compute.hlsl
- tools/clang/test/CodeGenSPIRV/fn.fixfuncall-linkage.hlsl
- tools/clang/test/CodeGenSPIRV/fn.param.inout.storage-class.hlsl
- tools/clang/test/CodeGenSPIRV/fn.param.inout.vector.hlsl
- tools/clang/test/CodeGenSPIRV/fn.param.isomorphism.hlsl
This did not solve all of the cases for the issue it was fixing. A new
fix was done in the inliner in spirv-opt. This change is no longer
needed.
This reverts commit 8967dacb03f1d95fc0292aa7a2e48b0acf50dcd9.
> Revert "[SPIRV] Use copy-in/copy-out for non-declaration (#7127)"

- tools/clang/tools/libclang/CMakeLists.txt
When targeting arm64 Debug, this error is detected:
`libclang\dxcrewriteunused.cpp(1,1): error C1128: number of sections exceeded object file format limit: compile with /bigobj`
This PR adds a compile option for the folder that contains dxcrewriteunused.cpp, so that the limit on the number of sections is increased, and compilation may succeed.
> Add /bigobj compile option to MSVC build

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
This PR changes some code in ExecutionTests.cpp to use the wide string variants of Windows API calls explicitly. This is because some internal builds will get confused about which overload to resolve the GetModuleHandle function to. By being explicit, this should eliminate the error that an arg can't be converted to LPCWSTR.
Cherry picked from https://github.com/microsoft/DirectXShaderCompiler/pull/7235
> Use Wide String variants explicitly for Windows API calls 

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
This PR changes some code in ExecutionTests.cpp to use the wide string variants of Windows API calls explicitly. This is because some internal builds will get confused about which overload to resolve the GetModuleHandle function to. By being explicit, this should eliminate the error that an arg can't be converted to LPCWSTR.
> Use Wide String variants explicitly for Windows API calls

- tools/clang/test/SemaHLSL/attributes/spv.inline.decorate.member.hlsl
This PR adds a // REQUIRES: spirv line to the top of a test that uses spirv.
This prevents failures in dev environments that don't have spirv enabled.
> Add constraint to test that requires spirv support

- tools/clang/test/CodeGenSPIRV/vk.binding.global-struct-of-resource.and.array.hlsl
Updates the submodules. One test is updated because spirv-opt does not
common the load of a sampler anymore to avoid using a value from a
different basic block.
> [SPIRV] Update submodules and fix test

- tools/clang/include/clang/SPIRV/FeatureManager.h
- tools/clang/lib/SPIRV/FeatureManager.cpp
- tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/type.buffer.half4.hlsl
We have a check that the sample type for an image cannot be a 16-bit
float. This is true for Vulkan, but not true for general spir-v.
We modify this check to only apply when the target env is vulkan. Wew
also move the check to spirvemitter where the error handling is better.
In its current location, the compiler continue to run with an unexpected
nullptr.
Fixes #6987
Fixes #6989
> [SPIRV] Allow sampled type to be half for universal

- include/dxc/DXIL/DxilConstants.h
- include/dxc/DXIL/DxilInstructions.h
- include/dxc/DXIL/DxilOperations.h
- lib/DXIL/DxilOperations.cpp
- tools/clang/test/DXILValidation/ser_hitobject_make_passing.ll
- utils/hct/hctdb.py
- utils/hct/hctdb_instrhelp.py
- DXIL opcodes for HitObject_MakeNop and HitObject_MakeMiss
- DXV validation test
> [SER] HitObject_MakeNop|Miss DXIL opcodes and verification tests

- .github/workflows/coverage-gh-pages.yml
Coverage generation has failed because of the deprecation of versions of upload-artifact before v4 which the version of upload-pages-artifact that DXC used made use of. This bumps that and all other actions to the latest versions.
> Update github actions versions to enable coverage

- docs/SPIR-V.rst
- tools/clang/include/clang/SPIRV/FeatureManager.h
- tools/clang/lib/SPIRV/CapabilityVisitor.cpp
- tools/clang/lib/SPIRV/FeatureManager.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/ddx.compute.khr.hlsl
- tools/clang/test/CodeGenSPIRV/texture.calculate.lod.compute.linear.khr.hlsl
Add support for KHR_compute_shader_derivatives
- DirectxShaderCompiler already supports `NV_compute_shader_derivatives` which is functionality identical to `KHR_compute_shader_derivatives`
- The KHR extension will be used by default instead of the NV one following the same approach as the RT extension. 
- We currently explain this in a comment in `tools/clang/lib/SPIRV/FeatureManager.cpp` `FeatureManager::enabledByDefault`.
- Check commit introducing RT for more info 04a84f05a54949d2075daec656a6a4c0c6829c43
Fixes #7179
> Add support for KHR_compute_shader_derivatives

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/DeclResultIdMapper.h
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/meshshading.nv.triangle.indices.out.hlsl
The parameters tagged with indices are linked to a builtin. Because their layout is different between HLSL and SPIR-V, there is a common mechanism to handle those 'stage I/O variables'.
Usually, a local variable with the correct HLSL layout is created, and when required, the value is copied in and copied out in the entrypoint wrapper. Then, a function-scoped pointer is passed to sub-functions.
The issue is that `indices` marks an array which is also shared across invocations. Meaning we cannot simple copy-in/copy-out. We are only allowed to write to the indices touched by the shader.
This required pushing the handling to the assignment expression handling: when a value is assigned to such builtin, the layout transformation is done, and the builtin written to.
Issue was how to find back …
> [SPIR-V] Fix usage of indices in subfunctions

- CMakeLists.txt
- tools/clang/CMakeLists.txt
Hopefully this works and gets us able to build with CMake 4+.
> Require CMake 3.17, remove CMP0051

- lib/DxilPIXPasses/PixPassHelpers.cpp
- tools/clang/unittests/HLSL/PixTest.cpp
- tools/clang/unittests/HLSL/PixTestUtils.cpp
The DXR invocation counting pass calls a function to add an output UAV twice. As part of adding the UAV, any DXIL-defined rootsigs will be extended to include this new UAV. If the UAV already exists in the rootsig, we should not add it again. (Doing so results in root sig that will fail validation.)
Note: the test is not a file-check style because dxil-defined subobjects don't get rehydrated into the DxilModule when the output of dxc.exe is piped into the input of opt.exe, meaning that the broken case can't be exercised.
> PIX: Check for existing PIX UAV in roots sigs before adding it again

- tools/clang/lib/CodeGen/CGStmt.cpp
- tools/clang/test/DXC/FinishCodeGen/unreachable-discard.hlsl
When emitting discard in an unreachable code context (e.g. after an infinite loop), DXC would assert (if asserts enabled), or trigger a UBSAN failure because the discard instruction would have no parent. When an infinite loop is emitted during CodeGen, the InsertPt is cleared, thus subsequent discard instructions would be created, but no parent set. We skip emitting discard in this case, which follows the same pattern as is done for EmitIfStmt, and EmitSwitchStmt.
> Fix assert due to unreachable discard

- .github/CODEOWNERS
MS just changed policy to enforce code owners across the whole enterprise, which is _not_ what we want. So we need to disable this in main for the time being.
> Disable code owners in main

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
Keep seeing this comment typo and wanted to rectify.
> Fix typo in exec tests comment

- tools/clang/CMakeLists.txt
- tools/clang/test/SemaHLSL/rayquery-omm-DXR-entry-point.hlsl
- tools/clang/test/SemaHLSL/rayquery-omm-type-diag.hlsl
- tools/clang/test/SemaHLSL/raytracingpipelineconfig1-no-errors.hlsl
This PR adds 2 tests that were mentioned in the spec that haven't yet been added.
1. A test that makes sure that restricted flags are diagnosed in DXR entry shaders.
2. A test that makes sure that no diagnostics are emitted when a restricted flag is used for a subobject in a non-library shadaer target.
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/7282
> [OMM] Add DXR Entry point test, non-library target test, conforming tests to spec.

- docs/SPIR-V.rst
- tools/clang/include/clang/SPIRV/FeatureManager.h
- tools/clang/include/clang/SPIRV/SpirvBuilder.h
- tools/clang/include/clang/SPIRV/SpirvInstruction.h
- tools/clang/lib/SPIRV/CapabilityVisitor.cpp
- tools/clang/lib/SPIRV/EmitVisitor.cpp
- tools/clang/lib/SPIRV/FeatureManager.cpp
- tools/clang/lib/SPIRV/SpirvBuilder.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/lib/SPIRV/SpirvInstruction.cpp
- tools/clang/test/CodeGenSPIRV/sm6.quad-any-all.hlsl
If `"SPV_KHR_quad_control"` can be used, uses `OpGroupNonUniformQuadAnyKHR` and `OpGroupNonUniformQuadAllKHR`. If not, falls back to constructing the value using `OpGroupNonUniformQuadBroadcast`.
Fixes #7247
> [SPIR-V] Implement QuadAny and QuadAll

- include/dxc/WinAdapter.h
Fixes #7248
Fix Clang Compilation on Linux without Microsoft extensions enabled.
Clang support depends on the `-fms-extensions` compiler flag. [[1]](https://clang.llvm.org/docs/UsersManual.html#microsoft-extensions)
If enabled, the `_MSC_EXTENSIONS` macro is defined. [[2]](https://github.com/llvm/llvm-project/blob/19a319667b567a26a20f9829a0ae7e6a5c259cba/clang/lib/Basic/Targets/OSTargets.cpp#L248)
> Add UUID compiler extension check on Clang

- CONTRIBUTING.md
This change seeks to address some recent questions about how the LLLVM Coding Standards are applied in DXC.
> Update DXC's CONTRIBUTING file

- lib/DxilValidation/DxilValidation.cpp
Capitalize all the variables and rename a few in DxilValidation.cpp in keeping with https://llvm.org/docs/CodingStandards.html#name-types-functions-variables-and-enumerators-properly
As this file was easily mistaken for applying to the golden rule: https://llvm.org/docs/CodingStandards.html#name-types-functions-variables-and-enumerators-properly it is at serious risk of receiving changes that will get hung up by requirements to follow the LLVM coding guidelines. This brings the cases where variable capitalization is not in line with the coding standards to avoid such pitfalls in the future.
> [NFC] Standardize DxilValidation variable capitalization

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
This PR modifies WaveSizeRange test which depends on shader model 6.8.
The compiler needs -select-validator internal.
This will allow the tests to be run in different testing environments when an external validator that isn't sufficient is available.
> Use internal validator for execution test that requires SM 6.8

- azure-pipelines.yml
The name matches for azure pipelines to run excluded staging branches. This adds them in.
Not sure this is desired, but it's here if we want it.
> Add staging branches to azure pipeline testing

- CMakeLists.txt
- include/dxc/DxilPIXPasses/DxilPIXPasses.h
- lib/DxilPIXPasses/CMakeLists.txt
- lib/DxilPIXPasses/DxilNonUniformResourceIndexInstrumentation.cpp
- lib/DxilPIXPasses/DxilShaderAccessTracking.cpp
- lib/DxilPIXPasses/PixPassHelpers.cpp
- lib/DxilPIXPasses/PixPassHelpers.h
- tools/clang/CMakeLists.txt
- tools/clang/unittests/HLSL/PixTest.cpp
- tools/clang/unittests/HLSL/PixTestUtils.cpp
- utils/hct/hctdb.py
Brings in these PRs:
#7272 [PIX] Add a pass for PIX to log missing NonUniformResourceIndex usage into a UAV.
#7238 [PIX: Check for existing PIX UAV in roots sigs before adding it again.
> PIX: CP NURI pass, multi-UAV bugfix

- lib/DXIL/DxilOperations.cpp
- lib/HLSL/HLOperationLower.cpp
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-scalarized-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-binary-float-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-binary-int-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-scalarized-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-tertiary-float-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-tertiary-int-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-unary-float-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-unary-int-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/passes/longvec-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/passes/longvec-intrinsics.ll
- utils/hct/hctdb.py
This enables the generation of native vector DXIL Operations
that are "trivial", meaning they take only a single DXOp Call
instruction to implement as well as a few others that either only took
such a call and some llvm operations or were of particular interest for
other reasons.
This involves allowing the overloads by adding the vector indication in
hctdb, altering the lowering to maintain the vectors instead of
scalarizing them, and a few sundry changes to fix issues along the way.
The "trivial" dxil operations that return a different value from the
overload type had to be moved out of the way and given their own
lowering function so that the main function could generate vectors
conditional on the version and vector type. These will be added in a
later change.
While the long vector …
> [SM6.9] Enable trivial native vector Dxil Operations plus a few

- include/dxc/DXIL/DxilInstructions.h
- lib/DXIL/DxilOperations.cpp
- lib/HLSL/HLOperationLower.cpp
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-scalarized-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-binary-float-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-binary-int-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-scalarized-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-tertiary-float-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-tertiary-int-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-unary-float-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-unary-int-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/passes/longvec-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/passes/longvec-intrinsics.ll
- utils/hct/hctdb.py
Merge latest main into staging-sm6.9.
> Merge main to staging-sm6.9

- include/dxc/DXIL/DxilConstants.h
- include/dxc/DXIL/DxilInstructions.h
- lib/DXIL/DxilOperations.cpp
- tools/clang/test/DXILValidation/ser_hitobject_fromrayquery_passing.ll
- tools/clang/test/LitDXILValidation/ser_hitobject_fromrayquery_passing.ll
- utils/hct/hctdb.py
tests
DXC SER implementation tracker: #7214
> [SER] HitObject_FromRayQuery[WithAttrs] DXIL opcodes and check-pass

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/vk.buffer-pointer.rvalue.hlsl
[spirv] Handles rvalue as implicit object argument of vk::BufferPointer::Get().
Fixes #7302.
> [spirv] Handles rvalue as implicit object argument of vk::BufferPointer::Get().

- tools/clang/lib/AST/ASTContextHLSL.cpp
- tools/clang/lib/Sema/SemaExprCXX.cpp
- tools/clang/test/CodeGenSPIRV/vk.buffer-pointer.from-uint.hlsl
Constructors are now properly attached to the template class declaration instead of a specialization.
Closes #6489 (again).
> [spirv] Fixes vk::BufferPointer constructor expression construction.

- CMakeLists.txt
- docs/DXIL.rst
HctGen of DXIL.rst should happen on every ordinary build, and be updated with other HctGen modified files.
This isn't about building the doc, it's about updating it when definitions change in hctdb.py.
We've been missing updates to DXIL.rst for quite a while due to this issue, introduced [here](https://github.com/microsoft/DirectXShaderCompiler/pull/6715/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR768-R770).
This also brings DXIL.rst up to date.
> Add HctGen of DXIL.rst back to build without LLVM_BUILD_DOCS required

- tools/clang/lib/CodeGen/CGDebugInfo.cpp
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-field-di.hlsl
Fix OOB accesses for debug info vector field names for vectors of length >4.
> Fix field names in long vector DICompositeType

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/test/CodeGenSPIRV/bezier.domain.hlsl2spv
- tools/clang/test/CodeGenSPIRV/semantic.domain-location.ds.hlsl
- tools/clang/test/CodeGenSPIRV/spirv.interface.ds.hlsl
This PR fixes https://github.com/microsoft/DirectXShaderCompiler/issues/7187.  gl_TessCoord is not a per-patch builtin and therefore the SPIRV should not be decorated with Patch.  This is clear in the GLSL specification, and a SPIRV spec clarification is online here: https://gitlab.khronos.org/spirv/SPIR-V/-/issues/819
> [SPIRV] Remove patch decoration from gl_TessCoord (#7187)

- azure-pipelines.yml
DXC seems to be building inocrrectly with GCC-13 and later, which is causing our pre-merge testing on 24.04 to fail. This will take some time to sort out, so in the meantime I'm reverting to 22.04 on our pipelines.
> Revert ADO pipelines to Ubuntu 22.04 temporarily

- azure-pipelines.yml
DXC seems to be building inocrrectly with GCC-13 and later, which is causing our pre-merge testing on 24.04 to fail. This will take some time to sort out, so in the meantime I'm reverting to 22.04 on our pipelines.
Cherry pick of https://github.com/microsoft/DirectXShaderCompiler/pull/7365
> Revert ADO pipelines to Ubuntu 22.04 temporarily (#7365)

- tools/clang/lib/Sema/SemaDXR.cpp
- tools/clang/test/SemaHLSL/hlsl/objects/HitObject/hitobject_traceinvoke_payload.hlsl
- tools/clang/test/SemaHLSL/hlsl/objects/HitObject/hitobject_traceinvoke_payload_udt.hlsl
- Generalize raypayload validation to HitObject::TraceRay|Invoke
- Reject non-numeric payload types in [HitObject::]TraceRay|Invoke
Specification: https://github.com/microsoft/hlsl-specs/blob/main/proposals/0027-shader-execution-reordering.md
Bug: #7234    [SER] Diagnose and validate illegal use of HitObject in unsupported contexts
> [SER] Diagnose payload in HitObject::TraceRay|Invoke

- tools/clang/test/CodeGenSPIRV/fn.export.with.entrypoint.hlsl
Update the submodules to release candidates for the next Vulkan SDK.
> [SPIRV] Update submodules

- include/dxc/HLSL/HLOperations.h
- lib/HLSL/HLOperationLower.cpp
- lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/CodeGenDXIL/hlsl/objects/HitObject/hitobject_fromrayquery.hlsl
- tools/clang/test/DXC/Passes/DxilGen/hitobject_fromrayquery_dxilgen.ll
- tools/clang/test/DXC/Passes/ScalarReplHLSL/hitobject_fromrayquery_scalarrepl.ll
- tools/clang/test/SemaHLSL/hlsl/objects/HitObject/hitobject_fromrayquery.hlsl
* HLSL -> DXIL lowering
* ast, hlsl->dxil, dxilgen, and ScalarReplAggregatesHLSL tests
SER implementation tracker (#7214)
> [SER] HitObject::FromRayQuery  HLSL -> DXIL lowering

- docs/DXIL.rst
- lib/DxilValidation/DxilValidation.cpp
- tools/clang/test/CodeGenDXIL/hlsl/objects/HitObject/hitobject_accessors.hlsl
- tools/clang/test/LitDXILValidation/ser_hitobject_accessors_failing.ll
- tools/clang/test/LitDXILValidation/ser_hitobject_accessors_passing.ll
- tools/clang/test/SemaHLSL/hlsl/objects/HitObject/hitobject_accessors.hlsl
- utils/hct/hctdb.py
Validate:
HitObject_GeometryIndex
HitObject_HitKind
HitObject_InstanceID
HitObject_InstanceIndex
HitObject_IsHit
HitObject_IsMiss
HitObject_IsNop
HitObject_LoadLocalRootTableConstant
HitObject_ObjectRayDirection
HitObject_ObjectRayOrigin
HitObject_ObjectToWorld3x4
HitObject_PrimitiveIndex
HitObject_RayFlags
HitObject_RayTCurrent
HitObject_RayTMin
HitObject_SetShaderTableIndex
HitObject_ShaderTableIndex
HitObject_WorldRayDirection
HitObject_WorldRayOrigin
Rules:
* No undef parameters (HitObject, RecordIndex, RootTableOffset)
* row/col/component indices are constant and in-bounds
* If constant, RootTableOffset % 4 == 0
SER implementation tracker: https://github.com/microsoft/DirectXShaderCompiler/issues/7214
> [SER] Validate HitObject accessors

- lib/DxilValidation/DxilValidation.cpp
- tools/clang/test/LitDXILValidation/ser_hitobject_make_failing.ll
Validate:
HitObject_MakeMiss
Rules:
No undef MissShaderIndex or RayFlags
SER implementation tracker: #7214
> [SER] Validate MakeMiss

- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/CodeGenDXIL/hlsl/objects/HitObject/hitobject_make.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/objects/HitObject/hitobject_traceinvoke.hlsl
- tools/clang/test/SemaHLSL/hlsl/objects/HitObject/hitobject_fromrayquery.hlsl
The first parameter of the HLSL_INTRINSIC record is actually a dummy entry for the function name.
When builtin member function templates are instantiated, the 'this' ptr is added as the first ParamVarDecl, which has the same index as the first argument in the HLSL_INTRINSIC record.
This shifts the parameter names by one for static member functions, as those do not have a 'this' pointer, as in:
```
| | | `-CXXMethodDecl {{[^ ]+}} <<invalid sloc>> <invalid sloc> used MakeMiss 'dx::HitObject (unsigned int, unsigned int, RayDesc)' static
| | |   |-TemplateArgument type 'dx::HitObject'
| | |   |-TemplateArgument type 'unsigned int'
| | |   |-TemplateArgument type 'unsigned int'
| | |   |-TemplateArgument type 'RayDesc'
| | |   |-ParmVarDecl {{[^ ]+}} <<invalid sloc>> <invalid sloc> MakeMiss …
```
> Fix static member call instantiation

- docs/DXIL.rst
- include/dxc/DXIL/DxilConstants.h
- include/dxc/DXIL/DxilInstructions.h
- include/dxc/DxilContainer/RDAT_LibraryTypes.inl
- include/dxc/HLSL/HLOperations.h
- include/dxc/HlslIntrinsicOp.h
- lib/DXIL/DxilOperations.cpp
- lib/DxilValidation/DxilValidation.cpp
- lib/HLSL/HLOperationLower.cpp
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/CodeGenDXIL/hlsl/intrinsics/linalg_builtins/check-shader-stages.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/intrinsics/linalg_builtins/linalg-builtins.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/intrinsics/linalg_builtins/lit.local.cfg
- tools/clang/test/CodeGenDXIL/hlsl/intrinsics/linalg_builtins/mat-vec-mul-add_multioverload.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/intrinsics/linalg_builtins/mat-vec-mul_multioverload.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/intrinsics/linalg_builtins/outer-product-accumulate-multioverload.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/intrinsics/linalg_builtins/vector-accumulate.hlsl
- tools/clang/test/DXC/Passes/DxilGen/linalg-builtins.ll
- tools/clang/test/SemaHLSL/hlsl/linalg/unavailable-pre-sm69.hlsl
- utils/hct/gen_intrin_main.txt
- utils/hct/hctdb.py
- utils/hct/hlsl_intrinsic_opcodes.json
Authored-by: Anupama Chandrasekhar <anupamac@nvidia.com>
Implements
HLSL:
__builtin_MatVecMul
__builtin_MatVecMulAdd
__builtin_OuterProductAccumulate
__builtin_VectorAccumulate
Lowered to
DXIL:
@dx.op.matVecMul
@dx.op.matVecMulAdd
@dx.op.outerProductAccumulate
@dx.op.vectorAccumulate
---------
Co-authored-by: Anupama Chandrasekhar <anupamac@nvidia.com>
Co-authored-by: Simon Moll <smoll@nvidia.com>
(cherry picked from commit 1db8c5b30b41f600c4c014fad7669d0e8f154a45)
> Implementation of the CoopVec Inference and Training builtin intrinisics (#7290)

- tools/clang/include/clang/SPIRV/SpirvBuilder.h
- tools/clang/include/clang/SPIRV/SpirvInstruction.h
- tools/clang/include/clang/SPIRV/SpirvModule.h
- tools/clang/include/clang/SPIRV/SpirvVisitor.h
- tools/clang/lib/SPIRV/CapabilityVisitor.cpp
- tools/clang/lib/SPIRV/CapabilityVisitor.h
- tools/clang/lib/SPIRV/EmitVisitor.cpp
- tools/clang/lib/SPIRV/EmitVisitor.h
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/lib/SPIRV/SpirvInstruction.cpp
- tools/clang/lib/SPIRV/SpirvModule.cpp
- tools/clang/test/CodeGenSPIRV/inline-spirv/spv.intrinsicExecutionModeId.hlsl
The current implementation of OpExecutionModeId assumes that the
operands must be OpConstants. However, they could be the id of a
spec constant. The first step in allowing OpExecutionModeId is to modify
the internal representation of the instruction to hold general spirv
instructions.
Part of https://github.com/microsoft/DirectXShaderCompiler/issues/5960
and https://github.com/microsoft/DirectXShaderCompiler/issues/3092.
> [SPIRV] Refactor OpExecutionModeId

- tools/clang/lib/Headers/hlsl/dx/linalg.h
- tools/clang/test/CodeGenDXIL/hlsl/linalg/mat-vec-mul.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/linalg/mat-vec-muladd.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/linalg/outerproductaccumulate.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/linalg/vectoraccumulate.hlsl
- tools/clang/test/SemaHLSL/hlsl/linalg/make-interp-vec-errors.hlsl
- tools/clang/test/SemaHLSL/hlsl/linalg/mat-vec-mul-errors.hlsl
- tools/clang/test/SemaHLSL/hlsl/linalg/mat-vec-mul-transpose-errors.hlsl
- tools/clang/test/SemaHLSL/hlsl/linalg/mat-vec-muladd-errors.hlsl
- tools/clang/test/SemaHLSL/hlsl/linalg/outerproductaccumulate-errors.hlsl
- tools/clang/test/SemaHLSL/hlsl/linalg/outerproductaccumulate-spirv-errors.hlsl
- tools/clang/test/SemaHLSL/hlsl/linalg/vectoraccumulate-errors.hlsl
This PR introduces the linear algebra header file, and places it in a location that is by default included in all HLSL compilation. The builtins in the API aren't yet defined, and depend on the #7290 PR merging first.
The tests that have been added have temporary diagnostic messages while 7290 is in progress. They will need to be updated. Open to feedback on better / suggested error messages, or whether there shouldn't be any sema-level validation for these errors.
Fixes
[#7304](https://github.com/microsoft/DirectXShaderCompiler/issues/7304)
Cherrypick of https://github.com/microsoft/DirectXShaderCompiler/pull/7350
> [CoopVec] Add Linear Algebra common header with tests (#7350)

- lib/DxilValidation/DxilValidation.cpp
- tools/clang/test/CodeGenDXIL/hlsl/intrinsics/maybereorder_od.hlsl
Validator did not recognize %dx.types.HitObject as an allowed type. This lead to validation failures in -Od compiles where allocas, loads and stores remain in the generated DXIL:
```
dxc.exe -T lib_6_9 -Od \tools\clang\test\CodeGenDXIL\hlsl\intrinsics\maybereorder.hlsl
error: validation errors
error: Declaration '%dx.types.HitObject = type { i8* }' uses a reserved prefix.
```
Closes #7387
> [SER] Validate %dx.types.HitObject as legal type same as handle

- include/dxc/Support/HLSLOptions.h
- tools/clang/tools/dxcompiler/dxcutil.cpp
This PR changes the default validation behavior to use the internal validator by default.
If no options are specified, the internal validator will be used, and if it fails, then compilation fails.
The external validator can still be run but must be explicitly chosen.
Specifying internal works just as before.
There is plenty of testing and infrastructure that needs to be added to verify this change, but that needs to be added in a separate change. This change is step 1.
Addresses https://github.com/microsoft/DirectXShaderCompiler/issues/7389
> Change default validation behavior

- docs/ReleaseNotes.md
Add upcoming release section to the release notes.
> Add upcoming release

- lib/DxilValidation/DxilValidation.cpp
- tools/clang/test/LitDXILValidation/ser_hitobject_fromrayquery_failing.ll
Validate:
HitObject_FromRayQuery
HitObject_FromRayQueryWithAttrs
Rules:
No `undef` inputs
SER implementation tracker: #7214
> [SER] Validate HitObject_FromRayQuery[WithAttrs]

- tools/clang/lib/SPIRV/EmitVisitor.cpp
- tools/clang/test/CodeGenSPIRV/spv.intrinsicConstantValue.hlsl
We will get a crash when use spirv intrinsic to create a constant value.
```fundamental
fatal error: generated SPIR-V is invalid: Constant cannot appear in a function declaration
%spirvIntrinsicType_42 = OpConstant %spirvIntrinsicType 42
```
> [SPIRV] Fix constant value in function

- lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
This PR removes a dead fallthrough statement after a switch-statement's case that is terminated by a break;
This needs to be removed, because the way linux builds dxc in our internal infrastructure, it errors when a dead fallthrough statement is detected.
For context, here is the relevant error:
```
ScalarReplAggregatesHLSL.cpp:2822:9: error: fallthrough annotation in unreachable code [-Werror,-Wimplicit-fallthrough]
LLVM_FALLTHROUGH;
^
... DXC/include/llvm/Support/Compiler.h:224:26: note: expanded from macro 'LLVM_FALLTHROUGH'
#define LLVM_FALLTHROUGH [[fallthrough]]
^
1 error generated.
```
> [Internal] Remove dead fallthrough statement

- .github/workflows/clang-format-checker.yml
This updates the clang-format-checker action workflow to pull the format checker and tools from `main` instead of from the PR.
Note: This PR basically can't be tested pre-merge since the pre-merge check will use the version of the action in `main`.
> Pull format checking tools from `main`

- lib/DXIL/DxilOperations.cpp
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-scalarized-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-unary-float-intrinsics.hlsl
- utils/hct/hctdb.py
Several intrinsics that were enabled for native vectors late got their testing removed as it expected scalarized forms. This adds tests for pow, modf, and abs in their native vector intrinsic forms. It removes native vector intrinsics for derivative operations as they require more scalarization removal due to their convergent markers and restores the scalarized testing for them. The 1024 size was removed from longvec-intrinsics as the verbose way that constant vectors are represented in the disassembly made the test take significantly longer.
> [SM6.9] Disable native vec deriv ops and expand testing

- docs/DXIL.rst
- lib/DxilValidation/DxilValidation.cpp
- tools/clang/test/LitDXILValidation/ser_reordercoherent_invalid_incdec.ll
- tools/clang/test/LitDXILValidation/ser_reordercoherent_invalid_sm.ll
- tools/clang/unittests/HLSL/DxilContainerTest.cpp
- tools/clang/unittests/HLSL/ValidationTest.cpp
- utils/hct/hctdb.py
Validates:
All resources
All instructions using resources
Rules:
'reordercoherent' may only be used in SM6.9+ in resource handles and
resource declarations.
Increment/DecrementCounter unsupported on 'reordercoherent' resources.
Create a new DXIL 1.9 variant of the 'CompileWhenOkThenCheckRDAT' container test and restore the old one without 'reordercoherent' (pre-#7250). The validator now rejects 'reordercoherent' in DXIL 1.3 and accepts from DXIL 1.9+.
SER implementation tracker: #7214
> [SER] Validate 'reordercoherent' resource property

- tools/clang/lib/CodeGen/CGHLSLMS.cpp
- tools/clang/test/HLSLFileCheck/hlsl/workgraph/nested_sv_dispatchgrid.hlsl
The SV_DispatchGrid DXIL metadata for a node input record was not generated in cases where:
- the field with the SV_DispatchGrid semantic was in a nested record
- the field with the SV_DispatchGrid semantic was in a record field
- the field with the SV_DispatchGrid semantic was inherited from a base record
- in any combinations of the above
Added FindDispatchGridSemantic() to be used by the AddHLSLNodeRecordTypeInfo() function, and added a test case.
Fixes #6928
> Support SV_DispatchGrid semantic in a nested record

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/intrinsics.vkrawbufferload.hlsl
It is possible to have two struct types in spir-v that are the same
except for the decorations. Sometimes we have to reconstruct the value
from one type to another.
In the case of a vk::SpirvType, we do not know anything about the type,
so this should not happen. When trying to reconstuct the value, we
should simply return the original value.
Fixes #6963
> [SPIRV] Treat vk::Spirv*Type as opaque when reconstructing

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/groupshared.init.warning.hlsl
To be consistent with DXIL, we will start emitting a warning for
extenally visible variables that have an initializer. Until now, there
were silently ignored.
Fixes #3950
> [SPIRV] Add warning for initialized globals

- tools/clang/lib/AST/HlslTypes.cpp
- tools/clang/test/CodeGenSPIRV/enum_sizeof.hlsl
- tools/clang/test/SemaHLSL/enum_sizeof.hlsl
> [SEMA] Don't emit an error for sizeof an enum.

- tools/clang/unittests/HLSLExec/CoopVec.h
- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
This change refactors the CoopVec test config selection to enforce running the minimum support set. Drivers that do not report all required data formats and interpretations will fail the test.
The handling of `D3D12EnableExperimentalFeatures` is also refactored to apply only to the CoopVec tests, without the use of `-p:CooperativeVectorExperimental=*`.
> [CoopVec] Check for minimum support set

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
The switch that sets SrcEltSize and DestEltSize is missing an FP32 case.
This results in the matrix buffer not being initialized with all 1.0s and causes tests to fail due to expected result being off by -1.0.
Verified correctness with NVIDIA internal driver build.
> [SM 6.9] Fix OuterProductAccumulate FP32 Accumulator case in ExecTest.

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/intrinsics.mul.hlsl
When dealing with the Load method on buffers, the operator call can emit a pointer instead of an actual load, and the user is then responsible on loading the value if required.
The `mul` instrinsic code was not handling this, hence caused the pointer to be passed as-is in SPIR-V.
Fixes #7246
> [SPIR-V] Fix r-value being used in mul intrinsic

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/meshshading.ext.amplification.payload.hlsl
This commit fixes the missing payload parameter for the OpEmitMeshTasksEXT instruction.
Errors such as the passed variable storage class or type are already tested.
Fixes #7082
Co-Authored-by: baldurk <baldurk@baldurk.org>
> [SPIR-V] Add payload to OpEmitMeshTasksEXT

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/op.vector.swizzle.buffer-store.hlsl
HLSL resources can store booleans. SPIR-V resources can't. We handle this by using integers in resources, and casting at the interface.
Swizzle path was handled a bit differently, and was not going through the common load/store path which handles the cast.
Fixes #7475
> [SPIR-V] Fix bool cast on buffers with swizzle

- azure-pipelines.yml
- utils/asan/x86_64-pc-linux-gnu.lsan.supp
Address-sanitizer reports a leak coming from the dynamic shared library loading code, though dlopen() is paired with dlclose(). This leak doesn't manifest on main yet because dxc adds dxcompiler directly to target_link_libraries (which it shouldn't have to), and dxil is loaded within that library. A PR to remove dxil loading from dxcompiler exposes the leak when dxc loads dxil dynamically.
This change adds a suppressions file for LSAN to suppress the leak in the loader code that happens under call_init. This also changes the Linux_Clang_Release build to RelWithDebInfo so symbols are present.
> NFC: Add LSAN leak suppression to ASAN pipeline

- tools/clang/lib/AST/HlslTypes.cpp
- tools/clang/lib/Sema/SemaDXR.cpp
- tools/clang/lib/Sema/SemaExpr.cpp
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/SemaHLSL/raytracing-entry-diags.hlsl
- tools/clang/test/SemaHLSL/sizeof-requires-complete-type.hlsl
- tools/clang/test/SemaHLSL/template-udt-load.hlsl
This change adds two additional calls to Sema::RequireCompleteType, one when evaluating unary `sizeof`, which fixes a reported issue with templates. The second is in the DXR diagnostics where complete type should be required but not diagnosed because ordering in the compiler is a bit wonky when diagnosing DXR entry points.
Fixes #7510
> Require complete types in some missing places

- utils/version/latest-release.json
This avoids other unrelated changes which didn't intend to change this file from having to update the file just to make clang-format happy.
> NFC: Update indentation in latest-release.json for clang-format

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/node.renamed.hlsl
The node index parameter of `OpAllocateNodePayloadsAMDX` was being set to the value of the NodeId index argument (which is captured in the `PayloadNodeBaseIndexAMDX` decoration).  Instead, it should be set to the node's index in the node array, if any, or zero for a single node.
> [spirv] Corrects output node index parameter.

- tools/clang/lib/AST/HlslTypes.cpp
- tools/clang/lib/Sema/SemaDXR.cpp
- tools/clang/lib/Sema/SemaExpr.cpp
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/SemaHLSL/raytracing-entry-diags.hlsl
- tools/clang/test/SemaHLSL/sizeof-requires-complete-type.hlsl
- tools/clang/test/SemaHLSL/template-udt-load.hlsl
This change adds two additional calls to Sema::RequireCompleteType, one when evaluating unary `sizeof`, which fixes a reported issue with templates. The second is in the DXR diagnostics where complete type should be required but not diagnosed because ordering in the compiler is a bit wonky when diagnosing DXR entry points.
Fixes #7510
---------
(cherry picked from commit 77dcbb61f7efdee92a19e4e289f03f2c77365222)
> Require complete types in some missing places (#7511)

- tools/clang/include/clang/SPIRV/AstTypeProbe.h
- tools/clang/lib/SPIRV/AstTypeProbe.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/logical_copy.hlsl
When DXC needs to change the layout of a value, it currently has to
extract each individual scalar, and then reconstruct using the type with
the different layout.
If you have a large array or struct with many member, this generates a
lot of extra code.
Starting in SPIR-V 1.4, the OpCopyLogical instruction is available to do
the reconstruction.
This should help generate less code, which will lead to improved compile
time and maybe smaller binary sizes.
Fixes #7493
> [SPIRV] Use OpCopyLogical to reconstruct values

- tools/clang/lib/SPIRV/EmitVisitor.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/rich.debug.function.param.hlsl
- tools/clang/test/CodeGenSPIRV/shader.debug.function.hlsl
Legalization and optimization will produce inaccurate NS100 debug info if there is no DebugScope emitted in the wrapper function.  This PR corrects this oversight and renames the wrapper to "__dxc_setup".  This may cause a stack frame named __dxc_setup to appear in an HLSL debugger, however, users should be familiar with this type of thing.  A C debugger might show crt0, or a debugger can filter this frame out of the user's view.  This PR addresses [7341](https://github.com/microsoft/DirectXShaderCompiler/issues//7341)
> [SPIRV] Emit DebugScope in wrapper (#7341)

- tools/clang/lib/Sema/SemaExpr.cpp
- tools/clang/test/HLSLFileCheck/hlsl/diagnostics/errors/integer_literal_too_large.hlsl
Two instances of the err_integer_literal_too_large diagnostic in HLSL specific code within Sema::ActOnNumericConstant() had a missing argument. When these diagnostics were raised this caused an assert in an assert enabled DXC, and random corruption of the diagnostic text in a non-assert enabled DXC.
The trivial fix is to supply the required argument.
Fixes #7425
> Add missing diagnostic argument

- include/llvm/DebugInfo/DWARF/DWARFDebugAranges.h
- include/llvm/Support/BlockFrequency.h
- include/llvm/Support/LEB128.h
- lib/Analysis/LoopAccessAnalysis.cpp
- lib/Transforms/InstCombine/InstructionCombining.cpp
- lib/Transforms/Scalar/LoadCombine.cpp
- tools/clang/include/clang/AST/Expr.h
- tools/clang/lib/AST/Expr.cpp
- tools/clang/lib/CodeGen/CGExprScalar.cpp
- tools/clang/lib/Lex/Lexer.cpp
- tools/clang/lib/Sema/SemaExpr.cpp
- tools/clang/lib/Sema/SemaType.cpp
- utils/TableGen/FixedLenDecoderEmitter.cpp
Addresses #7558. There is also one trivial change to use the ~ operator included in LEB128.h. My notes on the files were wrong and suggested that it should use std::numeric_limits<T> but looking at it again using ~0ULL made more sense.
> [NFC] Address compiler warnings: C4146 - Trivial std::numeric_limits<T> cases

- tools/clang/include/clang/SPIRV/SpirvBuilder.h
- tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
- tools/clang/test/CodeGenSPIRV/node.empty-node-input.hlsl
- tools/clang/test/CodeGenSPIRV/type.buffer.hlsl
- tools/clang/test/CodeGenSPIRV/type.rasterizer-ordered-buffer.hlsl
- tools/clang/test/CodeGenSPIRV/type.rasterizer-ordered-texture.hlsl
- tools/clang/test/CodeGenSPIRV/type.rwtexture.hlsl
I just learned more about the VK feature. In VK1.3, the validation rule was moved from the existence of the capability to being specific to the format. It is possible that people will see regressions if their code runs on a driver that does not support VK_FORMAT_FEATURE_2_STORAGE_WRITE_WITHOUT_FORMAT_BIT or 
VK_FORMAT_FEATURE_2_STORAGE_READ_WITHOUT_FORMAT_BIT for the format used by the developer.
Reverts microsoft/DirectXShaderCompiler#7528
> Revert "[SPIRV] Use unknown image format in vk1.3 and later"

- lib/Analysis/BasicAliasAnalysis.cpp
- lib/Analysis/ConstantFolding.cpp
- lib/Analysis/InstructionSimplify.cpp
Addresses https://github.com/microsoft/DirectXShaderCompiler/issues/7565
A few more instances where we can take advantage of -N being equivalent to (~N + 1)
> [NFC] Address compiler warnings: C4146 - Another round of use two's complement instead of negation

- include/dxc/DXIL/DxilConstants.h
- lib/DXIL/DxilOperations.cpp
- lib/DxilValidation/DxilValidation.cpp
- lib/HLSL/HLOperationLower.cpp
- tools/clang/test/CodeGenDXIL/hlsl/intrinsics/buffer-agg-load-stores.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/intrinsics/buffer-load-stores-sm69.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/intrinsics/buffer-load-stores.hlsl
Cherry-picked to release-1.8.2505 from #7513
There were two problems with processing the status parameter with the rework of the buffer load code. The first was that the status was not being passed down to the load instruction generation for aggregate types in any shader model version. The second was that the status retrieval from the resret returned by the raw buffer loads was using the wrong index for native vectors supported by shader model 6.9.
The status Value was not getting passed all the way down to the load instruction generation for aggregate types because the refactored helper constructor would always set it to null. It needs to be explicitly stated since by that point, the original call instruction it came from has been lost amidst subsequent GEPs, bitcasts, and/or loads that …
> Fix errors in retrieving and assigning load status parameter

- cmake/modules/HandleLLVMOptions.cmake
- include/llvm/ADT/IntervalMap.h
- lib/Analysis/LoopAccessAnalysis.cpp
- lib/Transforms/Scalar/LoadCombine.cpp
- lib/Transforms/Vectorize/LoopVectorize.cpp
- tools/clang/lib/AST/SelectorLocationsKind.cpp
- tools/clang/lib/CodeGen/ItaniumCXXABI.cpp
- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
- tools/clang/unittests/HLSLExec/ShaderOpTest.cpp
- tools/clang/unittests/HLSLExec/ShaderOpTest.h
- unittests/ADT/APIntTest.cpp
- unittests/ADT/BitVectorTest.cpp
- unittests/Support/DataExtractorTest.cpp
Addresses #7584 by removing the warning disable for 4146. Also includes a few trivial fixes for C4146 across several files that were missed in previous PRs.
> Address compiler warnings: Enable warning C4146 as a break. 

- lib/HLSL/DxilCondenseResources.cpp
- tools/clang/include/clang/Sema/Overload.h
- tools/clang/lib/Format/FormatToken.h
- tools/clang/lib/Sema/SemaOverload.cpp
Cherry-picked to release-1.8.2505 from https://github.com/microsoft/DirectXShaderCompiler/pull/7603
Resolves `C33010` which is currently blocking the release pipeline.
Addresses #7605
> [NFC] Clear C33010 Warning (#7603)

- docs/SPIR-V.rst
I was trying to debug a Vulkan Storage Buffer-related memory alignment issue in my application where I was using SPIR-V generated via `dxc` with `-fvk-use-dx-layout`. In `SPIR-V.rst`, I happened to miss the paragraph that follows the list of layout rules (removed in this proposal). That paragraph starts with "To use scalar layout", which given my use of DirectX layout, I did not think was relevant to me. However, the next sentence of that paragraph sneakily and indirectly mentions that `VK_EXT_scalar_block_layout` is required for the DirectX memory layout as well.
I have proposed explicitly stating the extension requirement when the relevant layout rules are listed.
> [SPIR-V] Explicitly state which layout rules require scalar block layout

- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/CodeGenSPIRV/spv.intrinsicInTemplate.hlsl
SPIR-V intrinsics allow us to create spirv basic type and opaque type in HLSL, but these type are object and not allowed in template parameter.
```fundamental
error: object 'Int8Type' is not allowed in builtin template parameters
/* OpTypeCooperativeMatrixKHR */ 4456, Int8Type,
^
```
This doesn't make sense to me, and is not convenience to use. This change wants to allow that use those in template parameter.
> [SPIRV] Allow spirv type as template parameter

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/amplification_shader_derivative.hlsl
- tools/clang/test/CodeGenSPIRV/mesh_shader_derivative.hlsl
- tools/clang/test/CodeGenSPIRV/vertex_shader_derivative_in_branch.hlsl
DXC allows user to use decrivative instruction in shader models that do
not allow it, but they must be dead code that will be removed. However,
when we see a derivative instruction in the SPIR-V backend that is not
in a pixel shader we assume it need the DerivativeGroup execution mode,
and we fail when we try to add it to a vertex shader.
To allow out implementation to match DXIL, we will not assume we can add
the execution mode. We will only add it for shader that we know can use
is, and skip the other.
If the derivative instruction is not removed during optimizations, there
will be a validation error.
While fixing this, we observed another bug that is fixed at the same
time since they are closely related. The TaskNV and TaskEXT shader types
do not have the same id, and the …
> [SPIRV] Add the derivative group execution mode only on shader types that allow it.

- tools/clang/include/clang/Sema/ExternalSemaSource.h
- tools/clang/include/clang/Sema/Sema.h
- tools/clang/lib/Sema/SemaCodeComplete.cpp
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/lib/Sema/SemaLookup.cpp
- tools/clang/lib/Sema/SemaOverload.cpp
- tools/clang/test/SemaHLSL/effects-syntax.hlsl
- tools/clang/test/SemaHLSL/raytracings.hlsl
- tools/clang/test/SemaHLSL/using-namespace-dx-errors.hlsl
- tools/clang/test/SemaHLSL/using-namespace-dx.hlsl
This change fixes issues with intrinsic lookup caused by not correctly respecting the using declaration(s) that impact unqualified lookups.
This probably isn't a perfect solution because I'm sure there's some nuance of unqualified lookups in C++ that I'm not handling, but this does respect scoped using directives and allows us to get things working.
Additionally this change disables emitting some "declared here" notes when the source location referred to is invalid.
Fixes #7495
> Fix intrinsic lookup with namespaces

- tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
- tools/clang/lib/SPIRV/LowerTypeVisitor.h
- tools/clang/test/CodeGenSPIRV/cbuffer.overlap.hlsl
The issue:
simple vertex shader like so
```
uniform float4x4 gMVP : register(c0);
uniform float4   gFoo : register(c5);
uniform float4   gBar : register(c5);
float4 main(float4 pos : POSITION) : SV_Position {
return mul(gMVP, pos * gFoo + gBar);
}
```
will result in an internal crash
```
dxc.exe -spirv -T vs_6_2 -E main test.hlsl -Fo test.spirv
Internal compiler error: access violation. Attempted to read from address 0x0000000000000000
```
Due to `LowerTypeVisitor` trying to assign offsets to fields without explicit locations.
It'll sort fields first, which will fill the map with the fields first. And since it's using `std::map` - if there's fields with the same `register` number - it'll only insert first, other will be left out, resulting nullptrs in the output vector.
We read the …
> [SPIR-V] Fixed a crash if encounter constant buffer fields with overlapping register assignments

- include/dxc/HLSL/HLOperations.h
- lib/HLSL/HLOperationLower.cpp
- lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp
- tools/clang/include/clang/Sema/Sema.h
- tools/clang/lib/Sema/SemaChecking.cpp
- tools/clang/lib/Sema/SemaExpr.cpp
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/CodeGenDXIL/hlsl/objects/HitObject/hitobject_attributes.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/objects/HitObject/hitobject_attributes_builtin.hlsl
- tools/clang/test/DXC/Passes/DxilGen/hitobject_attributes_dxilgen.ll
- tools/clang/test/SemaHLSL/hlsl/objects/HitObject/hitobject_attributes.hlsl
- tools/clang/test/SemaHLSL/hlsl/objects/HitObject/hitobject_attributes_invalid_longvec.hlsl
- tools/clang/test/SemaHLSL/hlsl/objects/HitObject/hitobject_attributes_invalid_udt.hlsl
- tools/clang/test/SemaHLSL/hlsl/types/invalid-hitobject-decls-struct.hlsl
- tools/clang/test/SemaHLSL/hlsl/types/invalid-hitobject-decls-templated.hlsl
- tools/clang/test/SemaHLSL/hlsl/types/invalid-longvec-decls.hlsl
- utils/hct/gen_intrin_main.txt
```
Old: T    HitObject::GetAttributes<T>()
New: void HitObject::GetAttributes(out udt)
```
- remove HitObject::GetAttributes<T> template code path from DeduceTemplateArgumentsForHLSL
- cleanup intersection attribute diagnostic code path
- adjust GetAttributes calls and expected AST, HLOps in tests (DXIL unaffected)
Closes #7534
This is a breaking change. Merge and release must be coordinated with:
- hlsl-spec change (https://github.com/microsoft/hlsl-specs/issues/495)
- HLK releases (SM6.9 preview tests use old signature)
> [SER] GetAttributes(out udt) instead of templated return

- tools/clang/include/clang/Basic/Attr.td
- tools/clang/lib/CodeGen/CGExpr.cpp
- tools/clang/lib/Sema/SemaHLSL.cpp
- tools/clang/test/HLSLFileCheck/hlsl/intrinsics/atomic/atomic.hlsl
- tools/clang/test/HLSLFileCheck/hlsl/intrinsics/atomic/atomic_float.hlsl
- tools/clang/test/SemaHLSL/hlsl/linalg/unavailable-pre-sm69.hlsl
- tools/clang/test/SemaHLSL/using-namespace-dx-errors.hlsl
- tools/clang/test/SemaHLSL/using-namespace-dx.hlsl
- tools/clang/unittests/HLSL/ExtensionTest.cpp
HLSL intrinsics were previously being added to the translation unit decl but assigned a namespace decl context which was then used only in codegen to determine if special handling was needed for the namespace. This causes an odd array of behaviors including strange mangling and confusing diagnostics.
This PR removes the HLSL namespace and properly adds intrinsics to namespaces when appropriate for the `vk` and `dx` namespaces. This should allow qualified and unqualified name lookup to behave as expected, correct odd mangling, and improve the confusing diagnostics.
The PR introduces a new HLSLBuiltinCallAttr to replace the use of the hlsl namespace. This attribute denotes when a function declaration should be emitted in codegen as an HLSL builtin. It is subtly different from …
> Remove `hlsl` namespace from SemaHLSL

- tools/clang/include/clang/SPIRV/SpirvBuilder.h
- tools/clang/include/clang/SPIRV/SpirvModule.h
- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/EmitVisitor.cpp
- tools/clang/lib/SPIRV/EmitVisitor.h
- tools/clang/lib/SPIRV/SpirvBuilder.cpp
- tools/clang/lib/SPIRV/SpirvModule.cpp
- tools/clang/test/CodeGenSPIRV/spirv.legal.counter.nested-struct.hlsl
- tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.counter.hlsl
- tools/clang/test/CodeGenSPIRV/type.append-structured-buffer.array.hlsl
- tools/clang/test/CodeGenSPIRV/type.append-structured-buffer.hlsl
- tools/clang/test/CodeGenSPIRV/type.consume-structured-buffer.array.hlsl
- tools/clang/test/CodeGenSPIRV/type.consume-structured-buffer.hlsl
- tools/clang/test/CodeGenSPIRV/type.enum.hlsl
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.array.binding.attributes.hlsl
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.array.counter.const.index.hlsl
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.array.counter.flatten.hlsl
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.array.counter.hlsl
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.array.counter.indirect.hlsl
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.array.counter.indirect2.hlsl
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.array.unbounded.counter.hlsl
- tools/clang/test/CodeGenSPIRV/type.rwstructured-buffer.unbounded.array.counter.hlsl
- tools/clang/test/CodeGenSPIRV/vk.1p2.block-decoration.hlsl
- tools/clang/test/CodeGenSPIRV/vk.layout.asbuffer.std430.hlsl
- tools/clang/test/CodeGenSPIRV/vk.layout.csbuffer.std430.hlsl
The value that decorates another value must be declared before the value
it decorates. See https://github.com/KhronosGroup/SPIRV-Tools/pull/6227.
> [SPIRV] Fix declaration order of values in decorations

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/template.class.partial.specialization.hlsl
The SpirvEmitter does not handle
ClassTemplatePartialSpecializationDecl. Since it extends RecordDecl, DXC
attempts to generate code for the partial specialization, but fails
because that is not possible.
We need to avoid trying to generate code for the partial specialization
and wait for a full specialization.
Fixes #7007
> [SPIRV] Handle partial template class specialization

- tools/clang/include/clang/SPIRV/SpirvModule.h
- tools/clang/lib/SPIRV/DebugTypeVisitor.cpp
- tools/clang/lib/SPIRV/SpirvBuilder.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvModule.cpp
- tools/clang/test/CodeGenSPIRV/rich.debug.debugsource.multiple.hlsl
- tools/clang/test/CodeGenSPIRV/rich.debug.function.parent.hlsl
- tools/clang/test/CodeGenSPIRV/shader.debug.line.include.hlsl
- tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Currently, dxc emits multiple DebugCompilationUnits for one spirv module.  This is incorrect, as acknowledged in [this comment:](https://github.com/microsoft/DirectXShaderCompiler/issues/7569#issuecomment-3019493146).  This PR corrects the problem.
> [SPIRV] Create only 1 DebugCompilationUnit per spirv module

- tools/clang/test/CodeGenSPIRV/type.cbuffer.including.resource.hlsl
The code emitted with this test would not pass validation rules for 06677 as the empty cbuffers generate a UniformConstant variable with no binding decoration.
Seems like an oversight from DXC which would be OK if it only happened with `-fcgl` but since this also happens in `-O0` this is a bug.
Related to #7681
> [SPIR-V] Disable validation for a broken test

- tools/clang/unittests/HLSLExec/TableParameterHandler.cpp
This PR fixes a bug in the Exec tests utility TableParamaterHandler which parses TAEF metadata which has either been populated via an xml file or TAEF macros. There was a bug when parsing a TableParameter::BOOL a string was being passed to TryGetValue instead of a bool.
The first argument to TryGetValue is the name of the parameter and the second is a reference to the variable to store the value. 
How tested: I'm adding a test that's using the handler to retrieve a bool value. I confirmed that it's working now.
> Execution Tests: Fix bug parsing bools in TableParameterHandler

- lib/HLSL/DxilPreparePasses.cpp
- tools/clang/test/CodeGenDXIL/hlsl/intrinsics/IsSpecialFloat6.8.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/intrinsics/IsSpecialFloat6.9.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-isspecial-intrinsics.hlsl
- tools/clang/test/CodeGenSPIRV/intrinsics.isfinite.16bit.hlsl
- tools/clang/test/CodeGenSPIRV/intrinsics.isinf.16bit.hlsl
- tools/clang/test/CodeGenSPIRV/intrinsics.isnan.16bit.hlsl
- utils/hct/gen_intrin_main.txt
Add 16 bit overloads for isinf, isnan, and isfinite
For SM6.8 and below; emulate these operations using IR by bitcasting the half to an i16 and performing comparisons to constants
For SM6.9 and later; the 16 bit isSpecialFloat DXIL Op Class is used.
Add tests showing for SM6.8 the emulation in DXIL for isinf, isnan, and isfinite
Add tests showing for SM6.9 the 16 bit version of isSpecialFloat is used
Add tests for SPIRV showing the 16 bit OpIsInf and OpIsNan are used
isinf: Closes #7650, Closes #7645, Closes #7653
isnan: Closes #7651, Closes #7646, Closes #7654
isfinite: Closes #7652, Closes #7647, Closes #7655
Closes #7496
> IsSpecialFloat 16 bit implementation for isinf, isnan, and isfinite

- tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
- tools/clang/lib/SPIRV/DeclResultIdMapper.h
- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/type.cbuffer.empty.hlsl
- tools/clang/test/CodeGenSPIRV/type.cbuffer.including.resource.hlsl
Each variable in the Uniform/Uniform Constant storage class must be decorated with DescriptorSet + Binding.
-> VUID-StandaloneSpirv-UniformConstant-06677
When a cbuffer was empty (or only contained resources), an empty struct and variable in the uniform storage class was created. Because the cbuffer was empty, no binding/descriptor set was assigned, hence no decoration was emitted.
This was fine as long as we compiled with optimizations on, as DCE would get rid of this unused cbuffer. But compiling with -O0 would yield a validation error.
Fixes #7681
> [SPIR-V] Fix invalid codegen for empty cbuffers

- tools/clang/unittests/HLSLExec/LongVectors.cpp
- tools/clang/unittests/HLSLExec/LongVectors.h
This PR shortens template argument names to shorter standard names. 'DataTypeT' -> 'T'.
In earlier revisions of these tests there were multiple template arguments being used. The template argument names were made more descriptive but since then the code has been simplified. The longer names have been driving me a little nuts. So this PR shortens them back to standard template argument names again.
> [NFC] Execution Tests: Long Vector tests update template parameter names

- tools/clang/unittests/HLSLExec/LongVectors.cpp
This PR fixes a bug where the AsTypeOp tests were not parsing the scalar input flags from the taef metadata.
> [Bug] Execution Tests: Long Vector tests aren't parsing scalar flags for AsType op tests

- tools/clang/unittests/HLSLExec/ExecutionTest.cpp
- tools/clang/unittests/HLSLExec/ShaderOpArith.xml
- tools/clang/unittests/HLSLExec/ShaderOpArithTable.xml
- update HLK test for 16 bit isinf to specify SM6.9 Closes #7600 
- update HLK test for 16 bit isnan to specify SM6.9 Closes #7601 
- update HLK test for 16 bit isfinite to specify SM6.9 Closes #7602 
- add 16 bit HLK test for isnormal which specifies SM6.9 Closes #7644
- Move 32 bit HLK test for isnormal to use isnormal instead of isnan Closes #7664
> Add/Update HLK tests for IsSpecialFloat Ops

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/test/CodeGenSPIRV/intrinsics.abs.hlsl
Fix the spirv codegen for `abs()` on `uint`, to **not** generate `OpExtInst` instruction but simply load and pass the value. Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/7512
```
[numthreads(1,1,1)]
void main() {
uint32_t A = uint32_t(0xffffffff);
uint32_t B = abs(A);
}
```
```
%A = OpVariable %_ptr_Function_uint Function
%B = OpVariable %_ptr_Function_uint Function
OpStore %A %uint_4294967295
%13 = OpLoad %uint %A
%14 = OpExtInst %int %1 SAbs %13
OpStore %B %14
```
```
%A = OpVariable %_ptr_Function_uint Function
%B = OpVariable %_ptr_Function_uint Function
OpStore %A %uint_4294967295
%13 = OpLoad %uint %A
OpStore %B %13
```
which is equivalent to 
```
[numthreads(1,1,1)]
void main() {
uint32_t A = uint32_t(0xffffffff);
uint32_t B = A;
}
```
> [SPIR-V]: Fix spirv codegen for `uabs` intrinsic when argument is unsigned.

- docs/DXIL.rst
- include/dxc/DXIL/DxilConstants.h
- include/dxc/DXIL/DxilInstructions.h
- lib/DXIL/DxilOperations.cpp
- lib/HLSL/HLOperationLower.cpp
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-scalarized-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/passes/longvec-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/passes/longvec-intrinsics.ll
- tools/clang/test/LitDXILValidation/lv_illegalDxilOp.ll
- utils/hct/hctdb.py
- utils/hct/hctdb_instrhelp.py
Fixes #7689 
Lowers vector calls to `dot` under SM6.9 to a single operation. Relies on https://github.com/microsoft/hlsl-specs/pull/622 being accepted
> [SM6.9] Lower vector dot calls to vector op

- tools/clang/unittests/HLSLExec/LongVectorOps.def
- tools/clang/unittests/HLSLExec/LongVectorTestData.h
- tools/clang/unittests/HLSLExec/LongVectors.cpp
This PR adds tests for the bitwise intrinsics saturate, reversebits, countbits, firstbithigh, and firstbitlow.
A new input value set 'Bitwise' was added to include bounadry cases for the respective types.
Resolves #7467
> Execution Tests: Long Vector Bitwise intrinsics

- tools/clang/unittests/HLSLExec/LongVectorOps.def
- tools/clang/unittests/HLSLExec/LongVectors.cpp
- tools/clang/unittests/HLSLExec/ShaderOpArith.xml
Remove the test cases for ternary assignment. Upon closer inspection I realized that there are no unique DXIL ops or LLVM instructions exercised via ternary assignment (or select for that matter).
> Execution Tests: Long Vectors Remove ternary assignment

- tools/clang/unittests/HLSLExec/LongVectorOps.def
- tools/clang/unittests/HLSLExec/LongVectorTestData.h
- tools/clang/unittests/HLSLExec/LongVectors.cpp
- tools/clang/unittests/HLSLExec/ShaderOpArith.xml
This PR adds test cases for explicit casts of long vectors. Bitwise NOT was removed as I realized it resolves to XOR and comparison ops that already have coverage. Other unary ops listed in the issue have a similar story.
Resolves https://github.com/microsoft/DirectXShaderCompiler/issues/7617
> Execution Tests: Long Vector finish implementing unary operators

- tools/clang/lib/SPIRV/SpirvEmitter.cpp
- tools/clang/lib/SPIRV/SpirvEmitter.h
- tools/clang/test/CodeGenSPIRV/intrinsics.reversebits.hlsl
Fix SPIRV codegen for `reversebits` HLSL intrinsic  on 16- and 64- bit integers. From the [validator specs](https://vulkan.lunarg.com/doc/view/1.4.313.1/windows/antora/spec/latest/appendices/spirvenv.html#VUID-StandaloneSpirv-Base-04781), `OpBitReverse` requires all arguments to be 32-bit integers.
Tested SPIRV correctness in https://github.com/luciechoi/amber/commit/02d1a357fe24f9765fe1683a741160557add63d6
1) Cast `ushort` to `uint`
2) Reverse bits
3) Right shift by 16
4) Cast back to `ushort`
which is similar to 
```
[numthreads(1,1,1)]
void main() {
uint16_t s = 1;
s = uint16_t(reversebits(uint(i)) >> 16);
}
```
1) Get the lower half `uint` by casting `ulong` to `uint`
2) Right shift the original `ulong` by 32 and get the upper half bits. Cast to `uint`
3) Reverse both `uint`s
4) Cast …
> [SPIR-V]: Fix codegen for `reversebits` on 16bit and 64bit width integers.

- utils/hct/hctbuild.cmd
This change allows us to control which nuget.config is used.
This is to allow internal builds to override the nuget feed that's used.
> Add hctbuild.cmd parameter to specify the nuget config file

- lib/DXIL/DxilOperations.cpp
- lib/HLSL/DxilScalarizeVectorIntrinsics.cpp
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-trivial-scalarized-intrinsics.hlsl
- tools/clang/test/CodeGenDXIL/hlsl/types/longvec-wave-intrinsics.hlsl
- utils/hct/hctdb.py
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/7714
Vectorize Quad Broadcast intrinsics
Note: The tests were already written for the SM6.9 library being linked to SM6.8 so no new test was added there. The existing code (nearly) already handling the lowering as if it was a "trivial" intrinsic
> [SM 6.9] Vector lower Quad Broadcast intrinsics

- tools/clang/lib/Headers/hlsl/enable_if.h
- tools/clang/lib/Headers/hlsl/vector_utils.h
- tools/clang/lib/Headers/hlsl/vectors.h
- tools/clang/test/SemaHLSL/hlsl/vectors/slice-errors.hlsl
- tools/clang/test/SemaHLSL/hlsl/vectors/slice.hlsl
Fixes https://github.com/microsoft/DirectXShaderCompiler/issues/7688
Adds a new stdlib function for slicing a long vector into a smaller one in a single instruction. Can be used similarly to vector swizzles which are not allowed for long vectors.
Also ensures at compile time that slicing out of bounds doesn't occur
> [SM6.9] Add vector slice to hlsl stdlib
